#!/bin/bash
cat $1 |grep decode |awk '{print substr($0,51)}' >.decode_1_result
awk '{T+= $NF} END { printf "av. decode('$1'): %.8f sec/msg, %.2f secs, %d msgs\n", T/NR, T, NR }' .decode_1_result
cat $1 |grep encode |awk '{print substr($0,51)}' >.encode_1_result
awk '{T+= $NF} END { printf "av. encode('$1'): %.8f sec/msg, %.2f secs, %d msgs\n", T/NR, T, NR }' .encode_1_result
cat $2 |grep decode |awk '{print substr($0,51)}' >.decode_2_result
awk '{T+= $NF} END { printf "av. decode('$2'): %.8f sec/msg, %.2f secs, %d msgs\n", T/NR, T, NR }' .decode_2_result
cat $2 |grep encode |awk '{print substr($0,51)}' >.encode_2_result
awk '{T+= $NF} END { printf "av. encode('$2'): %.8f sec/msg, %.2f secs, %d msgs\n", T/NR, T, NR }' .encode_2_result
rm -rf .decode_1_result .encode_1_result .encode_2_result .decode_2_result

