var annotated =
[
    [ "FIX8", "namespaceFIX8.html", "namespaceFIX8" ],
    [ "check_session", "classcheck__session.html", "classcheck__session" ],
    [ "coroutine", "classcoroutine.html", "classcoroutine" ],
    [ "coroutine_ref", "classcoroutine__ref.html", "classcoroutine__ref" ],
    [ "filestdin", "classfilestdin.html", "classfilestdin" ],
    [ "gzstreambase", "classgzstreambase.html", "classgzstreambase" ],
    [ "gzstreambuf", "classgzstreambuf.html", "classgzstreambuf" ],
    [ "hf_session_client", "classhf__session__client.html", "classhf__session__client" ],
    [ "hf_session_server", "classhf__session__server.html", "classhf__session__server" ],
    [ "initiator_fixture", "classinitiator__fixture.html", "classinitiator__fixture" ],
    [ "log_fixture", "classlog__fixture.html", "classlog__fixture" ],
    [ "myfix_session_client", "classmyfix__session__client.html", "classmyfix__session__client" ],
    [ "myfix_session_server", "classmyfix__session__server.html", "classmyfix__session__server" ],
    [ "MyMenu", "classMyMenu.html", "classMyMenu" ],
    [ "ogzstream", "classogzstream.html", "classogzstream" ],
    [ "persist_fixture", "classpersist__fixture.html", "classpersist__fixture" ],
    [ "RandDev", "structRandDev.html", "structRandDev" ],
    [ "session_fixture", "classsession__fixture.html", "classsession__fixture" ],
    [ "sessionTest", "classsessionTest.html", "classsessionTest" ],
    [ "test_session", "classtest__session.html", "classtest__session" ],
    [ "tex_router_client", "classtex__router__client.html", "classtex__router__client" ],
    [ "tex_router_server", "classtex__router__server.html", "classtex__router__server" ],
    [ "UsageMan", "classUsageMan.html", "classUsageMan" ],
    [ "XmlElement", "classXmlElement.html", "classXmlElement" ]
];