fix8: ff::ff_thread Class Reference
ff::ff_thread Class Reference abstract
Defines FastFlow's threads.
#include <node.hpp>
Public Member Functions
virtual void * svc (void *task)=0
the svc method
virtual int svc_init ()
The svc_init method.
virtual void svc_end ()
The svc_end method.
virtual void svc_createOCL ()
The svc_createOCL method.
virtual void svc_releaseOCL ()
The svc_releaseOCL.
void set_barrier (BARRIER_T *const b)
Sets the barrier object.
int spawn (int cpuId=-1)
Creates a new thread.
int wait ()
Waits for thread termination.
int wait_freezing ()
Waits for thread freezing.
void stop ()
Forces the thread to stop.
void freeze ()
Forces the thread to freeze.
void thaw (bool _freeze=false)
Thaw the thread, if it is frozen.
bool isfrozen ()
Checks if the thread is frozen.
pthread_t get_handle () const
Gets the pthread handler.
int getTid () const
Gets the internal unique thread identifier.
Protected Member Functions
ff_thread (BARRIER_T *barrier=NULL)
Constructor.
virtual ~ff_thread ()
Destructor.
void thread_routine ()
The life cycle of FastFlow thread.
int disable_cancelability ()
Disable the cancelation of thread.
int enable_cancelability ()
Makes thread cancelable.
Protected Attributes
unsigned tid
Private Attributes
BARRIER_T * barrier
bool stp
A Barrier object.
bool spawned
int freezing
bool frozen
bool thawed
bool init_error
pthread_t th_handle
pthread_attr_t attr
pthread_mutex_t mutex
pthread_cond_t cond
pthread_cond_t cond_frozen
int old_cancelstate
Friends
void * proxy_thread_routine (void *arg)
Proxy thread routine.
Detailed Description
Defines FastFlow's threads.
It defines FastFlow's threads. This class manages all the low-level communications and synchronisations needed among threads. It is responsible for threads creation and destruction, suspension, freezing and thawing.
This class is defined in node.hpp
Definition at line 371 of file node.hpp.
Constructor & Destructor Documentation
ff::ff_thread::ff_thread (BARRIER_T * barrier = NULL) inline protected
Constructor.
It checks initializations of mutex and conditional variable and then create the FastFlow thread.
Parameters
barrier is a Barrier object (i.e a custom Mutex) as input paramenter.
Definition at line 389 of file node.hpp.
References cond, cond_frozen, ff::error(), mutex, pthread_cond_init(), and pthread_mutex_init().
virtual ff::ff_thread::~ff_thread () inline protected virtual
Destructor.
Definition at line 418 of file node.hpp.
Member Function Documentation
int ff::ff_thread::disable_cancelability () inline protected
Disable the cancelation of thread.
It makes thread to be not cancelable. If a cancellation request is received, it is blocked until cancelability is enabled.
Returns
0 if successful, otherwise a negative value.
Definition at line 486 of file node.hpp.
References old_cancelstate, PTHREAD_CANCEL_DISABLE, and pthread_setcancelstate().
Referenced by thread_routine().
int ff::ff_thread::enable_cancelability () inline protected
Makes thread cancelable.
It makes thread cancelable.
Returns
0 if successful, otherwise a negative value.
Definition at line 502 of file node.hpp.
References old_cancelstate, and pthread_setcancelstate().
Referenced by thread_routine().
void ff::ff_thread::freeze () inline
Forces the thread to freeze.
It forces the thread to freeze himself.
Definition at line 644 of file node.hpp.
References freezing, and stp.
Referenced by ff::ff_loadbalancer::freeze(), and ff::ff_node::thWorker::freeze().
pthread_t ff::ff_thread::get_handle () const inline
Gets the pthread handler.
It retrives the pthread handler.
Returns
The handle for pthread.
Definition at line 686 of file node.hpp.
References th_handle.
int ff::ff_thread::getTid () const inline
Gets the internal unique thread identifier.
Definition at line 692 of file node.hpp.
References tid.
Referenced by ff::ff_node::getTid().
bool ff::ff_thread::isfrozen () inline
Checks if the thread is frozen.
It checks whether the thread is frozen.
Returns
A booleon value shoing the status of freezing.
Definition at line 676 of file node.hpp.
References freezing.
Referenced by ff::ff_node::thWorker::isfrozen(), ff::ff_loadbalancer::run(), and wait().
void ff::ff_thread::set_barrier (BARRIER_T *const b) inline
Sets the barrier object.
It sets the Barrier object for the ff_thread.
Parameters
b is a barrier object.
Definition at line 559 of file node.hpp.
References barrier.
Referenced by ff::ff_minode::cardinality(), and ff::ff_monode::cardinality().
int ff::ff_thread::spawn (int cpuId = -1) inline
Creates a new thread.
It create a new FastFlow thread
cpuID is the identifier of the core.
Returns
the -2 in case of error, -1 in case the thread is not assigned to any CPU CPU-id if successful
Definition at line 572 of file node.hpp.
References barrier, ff::init_thread_affinity(), pthread_attr_init(), pthread_create(), spawned, th_handle, and tid.
Referenced by ff::ff_gatherer::run(), ff::ff_loadbalancer::run(), ff::ff_node::thWorker::run(), and ff::ff_loadbalancer::runlb().
void ff::ff_thread::stop () inline
Forces the thread to stop.
It forces the thread to stop at next EOS or next thawing.
Definition at line 637 of file node.hpp.
References stp.
Referenced by ff::ff_loadbalancer::stop(), and ff::ff_node::stop().
virtual void* ff::ff_thread::svc (void * task) pure virtual
the svc method
It defines the svc method as pure virtual function.
Implemented in ff::ff_node::thWorker, ff::ff_loadbalancer, and ff::ff_gatherer.
Referenced by thread_routine().
virtual void ff::ff_thread::svc_createOCL () inline virtual
The svc_createOCL method.
It defines the virtual function.
Reimplemented in ff::ff_node::thWorker.
Definition at line 542 of file node.hpp.
virtual void ff::ff_thread::svc_end () inline virtual
The svc_end method.
It defines the virtual (overridable) function.
Reimplemented in ff::ff_node::thWorker, ff::ff_loadbalancer, and ff::ff_gatherer.
Definition at line 535 of file node.hpp.
Referenced by thread_routine().
virtual int ff::ff_thread::svc_init () inline virtual
The svc_init method.
It defines the virtual (overridable) function.
Returns
0 is returned always.
Reimplemented in ff::ff_node::thWorker, ff::ff_loadbalancer, and ff::ff_gatherer.
Definition at line 527 of file node.hpp.
Referenced by thread_routine().
virtual void ff::ff_thread::svc_releaseOCL () inline virtual
The svc_releaseOCL.
It defines teh virtual function.
Reimplemented in ff::ff_node::thWorker.
Definition at line 549 of file node.hpp.
Referenced by thread_routine().
void ff::ff_thread::thaw (bool _freeze = false) inline
Thaw the thread, if it is frozen.
If the thread is frozen, then thaw it.
Definition at line 654 of file node.hpp.
References cond, freezing, mutex, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), and thawed.
Referenced by ff::ff_loadbalancer::thaw(), ff::ff_node::thaw(), and wait().
void ff::ff_thread::thread_routine () inline protected
The life cycle of FastFlow thread.
It defines the life cycle of the FastFlow thread.
Definition at line 426 of file node.hpp.
References barrier, cond, cond_frozen, disable_cancelability(), enable_cancelability(), ff::error(), ff::FF_EOS_NOFREEZE, freezing, frozen, init_error, mutex, pthread_cond_signal(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), stp, svc(), svc_end(), svc_init(), svc_releaseOCL(), thawed, and tid.
Referenced by ff::proxy_thread_routine().
int ff::ff_thread::wait () inline
Waits for thread termination.
It defines the wait for thread termination.
Returns
0 if successful.
Definition at line 600 of file node.hpp.
References barrier, ff::error(), isfrozen(), pthread_attr_destroy(), pthread_join(), spawned, stp, th_handle, thaw(), and wait_freezing().
Referenced by ff::ff_loadbalancer::wait(), ff::ff_minode::wait(), ff::ff_node::thWorker::wait(), and ff::ff_loadbalancer::waitlb().
int ff::ff_thread::wait_freezing () inline
Waits for thread freezing.
It waits for the thread to freeze (uses Mutex).
Returns
0 if successful, otherwise a negative value.
Definition at line 624 of file node.hpp.
References cond_frozen, frozen, init_error, mutex, pthread_cond_wait(), pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by wait(), ff::ff_loadbalancer::wait_freezing(), and ff::ff_node::thWorker::wait_freezing().
Friends And Related Function Documentation
void* proxy_thread_routine (void * arg) friend
Proxy thread routine.
Member Data Documentation
pthread_attr_t ff::ff_thread::attr private
Definition at line 705 of file node.hpp.
BARRIER_T* ff::ff_thread::barrier private
Definition at line 697 of file node.hpp.
Referenced by set_barrier(), spawn(), thread_routine(), and wait().
pthread_cond_t ff::ff_thread::cond private
Definition at line 707 of file node.hpp.
Referenced by ff_thread(), thaw(), and thread_routine().
pthread_cond_t ff::ff_thread::cond_frozen private
Definition at line 708 of file node.hpp.
Referenced by ff_thread(), thread_routine(), and wait_freezing().
int ff::ff_thread::freezing private
Definition at line 700 of file node.hpp.
Referenced by freeze(), isfrozen(), thaw(), and thread_routine().
bool ff::ff_thread::frozen private
Definition at line 701 of file node.hpp.
Referenced by thread_routine(), and wait_freezing().
bool ff::ff_thread::init_error private
Definition at line 703 of file node.hpp.
Referenced by thread_routine(), and wait_freezing().
pthread_mutex_t ff::ff_thread::mutex private
Definition at line 706 of file node.hpp.
Referenced by ff_thread(), thaw(), thread_routine(), and wait_freezing().
int ff::ff_thread::old_cancelstate private
Definition at line 709 of file node.hpp.
Referenced by disable_cancelability(), and enable_cancelability().
bool ff::ff_thread::spawned private
Definition at line 699 of file node.hpp.
Referenced by spawn(), and wait().
bool ff::ff_thread::stp private
A Barrier object.
Definition at line 698 of file node.hpp.
Referenced by freeze(), stop(), thread_routine(), and wait().
pthread_t ff::ff_thread::th_handle private
Definition at line 704 of file node.hpp.
Referenced by get_handle(), spawn(), and wait().
bool ff::ff_thread::thawed private
Definition at line 702 of file node.hpp.
Referenced by thaw(), and thread_routine().
unsigned ff::ff_thread::tid protected
Definition at line 695 of file node.hpp.
Referenced by getTid(), spawn(), ff::ff_node::thWorker::svc_init(), and thread_routine().
The documentation for this class was generated from the following file:
node.hpp