fix8: ff::ff_dnode< CommImpl > Class Template Reference
ff::ff_dnode< CommImpl > Class Template Reference
A class representing the distributed version of ff_node.
#include <dnode.hpp>
Public Types
enum { SENDER =true, RECEIVER =false }
typedef
CommImpl::TransportImpl::msg_t msg_t
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Public Member Functions
int init (const std::string &name, const std::string &address, const int peers, typename CommImpl::TransportImpl *const transp, const bool p, const int nodeId=-1, dnode_cbk_t cbk=0)
Initializes external communication channel.
virtual void prepare (svector< iovec > &v, void *ptr, const int sender=-1)
Prepares output message.
virtual void prepare (svector< msg_t * > *&v, size_t len, const int sender=-1)
Prepars a pool of messages.
virtual void unmarshalling (svector< msg_t * > *const v[], const int vlen, void *&task)
Unmarshalling.
void setCallbackArg (void *arg)
Sets call back arguments.
int run (bool=false)
Executes the FastFlow dnode.
int wait ()
Waits the FastFlow node.
void skipfirstpop (bool sk)
Skips first pop.
Public Member Functions inherited from ff::ff_node
virtual void * svc (void *task)=0
The svc method.
virtual int svc_init ()
The svc_init()
virtual void svc_end ()
The svc_end()
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Protected Member Functions
bool isEos (const char data[msg_t::HEADER_LENGTH]) const
Checks EOS.
ff_dnode ()
Constructor.
virtual ~ff_dnode ()
Destructor.
template<typename CI >
bool internal_push (void *ptr, CI &comm)
Defines internal push.
virtual bool push (void *ptr)
Pushes the data.
virtual bool pop (void **ptr)
Pops the data.
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual int cardinality (BARRIER_T *const b)
Counts how many threads there are in this node.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Static Protected Member Functions
static void freeMsg (void *data, void *arg)
Free the message.
static void freeHdr (void *data, void *)
Frees header.
Protected Attributes
bool skipdnode
bool P
int neos
svector< void * > callbackArg
CommImpl com
Static Protected Attributes
static dnode_cbk_t cb =0
Detailed Description
template<typename CommImpl>
class ff::ff_dnode< CommImpl >
A class representing the distributed version of ff_node.
Defines the distributed version of FastFlow node.
A ff_dnode is actually a ff_node with an extra communication channel (external channel), which connects the edge-node of the graph with one or more edge-nodes of other FastFlow application graphs running on the same host or on different host(s).
It is implemented as a template: the template type CommImpl refers to the communication pattern that the programmer wishes to use to connect different ff_dnodes (i.e. unicast, broadcast, scatter, ondemand, fromAll, fromAny).
This class represents the distributed version of ff_node. A ff_dnode is actually a ff_node with an extra communication channel (external channel), which connects the edge-node of the graph with one or more edge-nodes of other FastFlow application graphs running on the same host or on different host(s).
It is implemented as a template: the template type CommImpl refers to the communication pattern that the programmer wishes to use to connect different ff_dnodes (i.e. unicast, broadcast, scatter, ondemand, fromAll, fromAny).
This class is defined in dnode.hpp
Definition at line 95 of file dnode.hpp.
Member Typedef Documentation
template<typename CommImpl> typedef CommImpl::TransportImpl::msg_t ff::ff_dnode< CommImpl >::msg_t
Implements communication transport layer
Definition at line 100 of file dnode.hpp.
Member Enumeration Documentation
template<typename CommImpl> anonymous enum
Defines sender and receiver
Enumerator
SENDER
RECEIVER
Definition at line 105 of file dnode.hpp.
Constructor & Destructor Documentation
template<typename CommImpl> ff::ff_dnode< CommImpl >::ff_dnode () inline protected
Constructor.
It builds the FastFlow node.
Definition at line 155 of file dnode.hpp.
template<typename CommImpl> virtual ff::ff_dnode< CommImpl >::~ff_dnode () inline protected virtual
Destructor.
It closes all communication connections.
Reimplemented in ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 162 of file dnode.hpp.
Member Function Documentation
template<typename CommImpl> static void ff::ff_dnode< CommImpl >::freeHdr (void * data, void *) inline static protected
Frees header.
It frees the header of the message
data is pointer to the header
Definition at line 133 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push().
template<typename CommImpl> static void ff::ff_dnode< CommImpl >::freeMsg (void * data, void * arg) inline static protected
Free the message.
It frees the message.
data pointer to the data to be freed arg arguments to be passed to the callback function
Definition at line 121 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push().
template<typename CommImpl> int ff::ff_dnode< CommImpl >::init (const std::string & name, const std::string & address, const int peers, typename CommImpl::TransportImpl *const transp, const bool p, const int nodeId = -1, dnode_cbk_t cbk = 0) inline
Initializes external communication channel.
It initializes the external communication channel.
Parameters
name is the name of the channel
address is the address where to listen or connect to
peers is the number of peers
transp is the transport layer to be used
p is a flag saying whether the current dnode is the producer (p = true) or the consumer (p = false) w.r.t. the communication pattern used
nodeId is the ID of the node
cbk is the callback function that will be called once when a message just sent is no longer in use by the run-time
Returns
The status of com.init() as an integer value
Definition at line 317 of file dnode.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::initIn().
template<typename CommImpl> template<typename CI > bool ff::ff_dnode< CommImpl >::internal_push (void * ptr, CI & comm) inline protected
Defines internal push.
It sends the signal. TODO please write more here.
ptr is pointer to the message comm is communication signal
Returns
If successful true, otherwise false.
Definition at line 178 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::push(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename CommImpl> bool ff::ff_dnode< CommImpl >::isEos (const char data[msg_t::HEADER_LENGTH]) const inline protected
Checks EOS.
It checks if it is EOS of the message.
data is the array of messages
Returns
The EOS of the message
Definition at line 146 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::pop().
template<typename CommImpl> virtual bool ff::ff_dnode< CommImpl >::pop (void ** ptr) inline protected virtual
Pops the data.
It overrides ff_node 's pop method.
ptr points to the data
Returns
If successful true is returned, otherwise false.
Reimplemented from ff::ff_node.
Reimplemented in ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 250 of file dnode.hpp.
template<typename CommImpl> virtual void ff::ff_dnode< CommImpl >::prepare (svector< iovec > & v, void * ptr, const int sender = -1) inline virtual
Prepares output message.
It is used to prepare (non contiguous) output messages
Parameters
v is a vector containing the pool of messages
ptr is pointer to the data
sender is the sender of the message
Reimplemented in ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 350 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push(), and ff::ff_dnode< CommImplIn >::pop().
template<typename CommImpl> virtual void ff::ff_dnode< CommImpl >::prepare (svector< msg_t * > *& v, size_t len, const int sender = -1) inline virtual
Prepars a pool of messages.
It is used to give to the run-time a pool of messages on which input message frames will be received
Parameters
len is the number of input messages expected
sender is the sender of the message
v vector contains the pool of messages
Definition at line 374 of file dnode.hpp.
template<typename CommImpl> virtual bool ff::ff_dnode< CommImpl >::push (void * ptr) inline protected virtual
Pushes the data.
It overrides ff_node's push method
ptr points to the data
Returns
The status of internal_push() as Boolean value.
Reimplemented from ff::ff_node.
Reimplemented in ff::ff_dinout< CommImplIn, CommImplOut >, and ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 236 of file dnode.hpp.
template<typename CommImpl> int ff::ff_dnode< CommImpl >::run (bool = false) inline virtual
Executes the FastFlow dnode.
It runs the dnode as a stand-alone thread. Typically, it should not be called by application code unless you want to have just a sequential dnode .
Returns
The status of the run() method.
Reimplemented from ff::ff_node.
Definition at line 423 of file dnode.hpp.
template<typename CommImpl> void ff::ff_dnode< CommImpl >::setCallbackArg (void * arg) inline
Sets call back arguments.
It is used to pass an additional parameter (the 2nd one) to the callback function. Typically it is called in the prepare method of the producer.
arg points to the arguments to be pussed to the callback
Definition at line 412 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::prepare().
template<typename CommImpl> void ff::ff_dnode< CommImpl >::skipfirstpop (bool sk) inline virtual
Skips first pop.
It jumps the first pop from the input queue or from the input external channel. This is typically used in the first stage of a cyclic graph (e.g. the first stage of a torus pipeline).
sk is boolean value showing whether skifirstpop should be skipped or not
Reimplemented from ff::ff_node.
Definition at line 444 of file dnode.hpp.
template<typename CommImpl> virtual void ff::ff_dnode< CommImpl >::unmarshalling (svector< msg_t * > *const v[], const int vlen, void *& task) inline virtual
Unmarshalling.
It is called once, when all frames composing the message have been received by the run-time. Within that method, it is possible to convert or re-arrange all the frames back to their original data or object layout.
v is vector of messages vlen is the length of the vector task pointer to the task
Definition at line 397 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::pop().
template<typename CommImpl> int ff::ff_dnode< CommImpl >::wait () inline virtual
Waits the FastFlow node.
It waits the thread to finish.
Returns
The status of wait() method.
Reimplemented from ff::ff_node.
Definition at line 432 of file dnode.hpp.
Member Data Documentation
template<typename CommImpl> svector<void*> ff::ff_dnode< CommImpl >::callbackArg protected
Definition at line 450 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push(), and ff::ff_dnode< CommImplIn >::setCallbackArg().
template<typename CommImpl> dnode_cbk_t ff::ff_dnode< CommImpl >::cb =0 static protected
Definition at line 110 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::freeMsg(), and ff::ff_dnode< CommImplIn >::init().
template<typename CommImpl> CommImpl ff::ff_dnode< CommImpl >::com protected
Definition at line 451 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::init(), ff::ff_dnode< CommImplIn >::pop(), ff::ff_dnode< CommImplIn >::push(), and ff::ff_dnode< CommImplIn >::~ff_dnode().
template<typename CommImpl> int ff::ff_dnode< CommImpl >::neos protected
Definition at line 449 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::init(), and ff::ff_dnode< CommImplIn >::pop().
template<typename CommImpl> bool ff::ff_dnode< CommImpl >::P protected
Definition at line 448 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::init(), ff::ff_dnode< CommImplIn >::pop(), and ff::ff_dnode< CommImplIn >::push().
template<typename CommImpl> bool ff::ff_dnode< CommImpl >::skipdnode protected
Definition at line 447 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::init(), ff::ff_dnode< CommImplIn >::pop(), and ff::ff_dnode< CommImplIn >::push().
The documentation for this class was generated from the following files:
dnode.hpp
dinout.hpp