fix8: ff::ofarm_gt Class Reference
ff::ofarm_gt Class Reference
Ordered farm with gatherer.
#include <farm.hpp>
Public Member Functions
ofarm_gt (int max_num_workers)
Constructor.
bool set_victim (int v)
Sets the victim.
void set_dead (int v)
Sets the dead.
void reset ()
Resets.
Public Member Functions inherited from ff::ff_gatherer
ff_gatherer (int max_num_workers)
Constructor.
int set_filter (ff_node *f)
Sets the filer.
void set_out_buffer (FFBUFFER *const buff)
Sets output buffer.
int get_channel_id () const
Gets the channel id.
int getnworkers () const
Gets the number of worker threads currently running.
void skipfirstpop ()
Skips the first pop.
FFBUFFER * get_out_buffer () const
Gets the ouput buffer.
int register_worker (ff_node *w)
Register the given worker to the list of workers.
virtual int svc_init ()
Initializes the gatherer task.
virtual void * svc (void *)
The gatherer task.
virtual void svc_end ()
Finializes the gatherer.
int run (bool=false)
Execute the gatherer task.
virtual double ffTime ()
Start counting time.
virtual double wffTime ()
Complete counting time.
virtual struct timeval & getstarttime () const
virtual struct timeval & getstoptime () const
virtual struct timeval & getwstartime () const
virtual struct timeval & getwstoptime () const
Public Member Functions inherited from ff::ff_thread
virtual void svc_createOCL ()
The svc_createOCL method.
virtual void svc_releaseOCL ()
The svc_releaseOCL.
void set_barrier (BARRIER_T *const b)
Sets the barrier object.
int spawn (int cpuId=-1)
Creates a new thread.
int wait ()
Waits for thread termination.
int wait_freezing ()
Waits for thread freezing.
void stop ()
Forces the thread to stop.
void freeze ()
Forces the thread to freeze.
void thaw (bool _freeze=false)
Thaw the thread, if it is frozen.
bool isfrozen ()
Checks if the thread is frozen.
pthread_t get_handle () const
Gets the pthread handler.
int getTid () const
Gets the internal unique thread identifier.
Protected Member Functions
int selectworker ()
Selects worker.
Protected Member Functions inherited from ff::ff_gatherer
virtual void notifyeos (int id)
Notifies the EOS.
virtual unsigned int ntentative ()
Gets the number of tentatives.
virtual void losetime_out ()
Loses the time out.
virtual void losetime_in ()
Loses the time in.
virtual int gather_task (void **task)
It gathers the tasks.
virtual int all_gather (void *task, void **V)
It gathers all tasks.
void push (void *task)
Pushes the task in the tasks queue.
bool pop (void **task)
Pop a task out of the queue.
bool pop_nb (void **task)
Pop a tak from un unbounded queue.
Protected Member Functions inherited from ff::ff_thread
ff_thread (BARRIER_T *barrier=NULL)
Constructor.
virtual ~ff_thread ()
Destructor.
void thread_routine ()
The life cycle of FastFlow thread.
int disable_cancelability ()
Disable the cancelation of thread.
int enable_cancelability ()
Makes thread cancelable.
Private Attributes
int victim
svector< bool > dead
Additional Inherited Members
Public Types inherited from ff::ff_gatherer
enum { TICKS2WAIT =5000 }
Protected Attributes inherited from ff::ff_thread
unsigned tid
Detailed Description
Ordered farm with gatherer.
It defines an ordered farm with gatherer.
This class is defined in farm.hpp
Definition at line 1099 of file farm.hpp.
Constructor & Destructor Documentation
ff::ofarm_gt::ofarm_gt (int max_num_workers) inline
Constructor.
It build the ordered farm.
max_num_workers defines the maximum number of workers.
Definition at line 1118 of file farm.hpp.
References dead, reset(), and ff::svector< T >::resize().
Member Function Documentation
void ff::ofarm_gt::reset () inline
Resets.
It makes the element in the dead vector as false i.e. makes it alive.
Definition at line 1152 of file farm.hpp.
References dead, and ff::svector< T >::size().
Referenced by ofarm_gt(), and ff::ff_ofarm::ofarmC::svc_init().
int ff::ofarm_gt::selectworker () inline protected virtual
Selects worker.
It selects a worker
Returns
An integet value showing he id of the worker
Reimplemented from ff::ff_gatherer.
Definition at line 1108 of file farm.hpp.
References victim.
void ff::ofarm_gt::set_dead (int v) inline
Sets the dead.
It sets an element in the dead vector to true, to make it dead.
v is number in the dead vector.
Definition at line 1144 of file farm.hpp.
References dead.
Referenced by ff::ff_ofarm::ofarmC::eosnotify().
bool ff::ofarm_gt::set_victim (int v) inline
Sets the victim.
It sets the victim with the given worker
Returns
true if successful, otherwise false.
Definition at line 1131 of file farm.hpp.
References dead, and victim.
Referenced by ff::ff_ofarm::ofarmC::eosnotify(), ff::ff_ofarm::ofarmC::svc(), and ff::ff_ofarm::ofarmC::svc_init().
Member Data Documentation
svector<bool> ff::ofarm_gt::dead private
Definition at line 1157 of file farm.hpp.
Referenced by ofarm_gt(), reset(), set_dead(), and set_victim().
int ff::ofarm_gt::victim private
Definition at line 1156 of file farm.hpp.
Referenced by selectworker(), and set_victim().
The documentation for this class was generated from the following file:
farm.hpp