fix8: ff::ff_pipeline Class Reference
ff::ff_pipeline Class Reference
The Pipeline skeleton.
#include <pipeline.hpp>
Public Types
enum { DEF_IN_BUFF_ENTRIES =512, DEF_OUT_BUFF_ENTRIES =(DEF_IN_BUFF_ENTRIES+128) }
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Public Member Functions
ff_pipeline (bool input_ch=false, int in_buffer_entries=DEF_IN_BUFF_ENTRIES, int out_buffer_entries=DEF_OUT_BUFF_ENTRIES, bool fixedsize=true)
~ff_pipeline ()
int add_stage (ff_node *s)
int wrap_around ()
void cleanup_nodes ()
Delete nodes when the destructor is called.
int run (bool skip_init=false)
int run_and_wait_end ()
int run_then_freeze ()
int wait ()
int wait_freezing ()
void stop ()
void freeze ()
void thaw (bool _freeze=false)
bool isfrozen ()
bool offload (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=ff_node::TICKS2WAIT)
bool load_result (void **task, unsigned int retry=((unsigned int)-1), unsigned int ticks=ff_node::TICKS2WAIT)
bool load_result_nb (void **task)
int cardinality (BARRIER_T *const barrier)
double ffTime ()
Gets the time.
double ffwTime ()
void ffStats (std::ostream &out)
Public Member Functions inherited from ff::ff_node
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Protected Member Functions
int prepare ()
int freeze_and_run (bool=false)
void * svc (void *task)
int svc_init ()
void svc_end ()
void setAffinity (int)
int getCPUId ()
int create_input_buffer (int nentries, bool fixedsize)
int create_output_buffer (int nentries, bool fixedsize=false)
int set_output_buffer (FFBUFFER *const o)
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
virtual bool push (void *ptr)
Pushes to output buffer.
virtual bool pop (void **ptr)
Pops the data from input buffer.
virtual void skipfirstpop (bool sk)
Skips the first element popped.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Private Attributes
bool has_input_channel
bool prepared
bool node_cleanup
bool fixedsize
int in_buffer_entries
int out_buffer_entries
std::vector< ff_node * > nodes_list
Detailed Description
The Pipeline skeleton.
Pipelining is one of the simplest parallel patterns where data flows through a series of stages (or nodes) and each stage processes the input data in some ways, producing as output a modified version or new data. A pipeline's stage can operate sequentially or in parallel and may or may not have an internal state.
This class is defined in pipeline.hpp
Definition at line 120 of file pipeline.hpp.
Member Enumeration Documentation
anonymous enum
TODO
Enumerator
DEF_IN_BUFF_ENTRIES
DEF_OUT_BUFF_ENTRIES
Definition at line 192 of file pipeline.hpp.
Constructor & Destructor Documentation
ff::ff_pipeline::ff_pipeline (bool input_ch = false, int in_buffer_entries = DEF_IN_BUFF_ENTRIES, int out_buffer_entries = DEF_OUT_BUFF_ENTRIES, bool fixedsize = true) inline
Constructor
Parameters
input_ch = true to set accelerator mode
in_buffer_entries = input queue length
out_buffer_entries = output queue length
fixedsize = true uses only fixed size queue
Definition at line 202 of file pipeline.hpp.
ff::ff_pipeline::~ff_pipeline () inline
Destructor
Definition at line 215 of file pipeline.hpp.
References ff::ff_node::barrier, node_cleanup, and nodes_list.
Member Function Documentation
int ff::ff_pipeline::add_stage (ff_node * s) inline
It adds a stage to the Pipeline
Parameters
s a ff_node that is the stage to be added to the skeleton. The stage contains the task that has to be executed.
Definition at line 232 of file pipeline.hpp.
References nodes_list.
int ff::ff_pipeline::cardinality (BARRIER_T *const barrier) inline virtual
TODO
Returns
TODO
Reimplemented from ff::ff_node.
Definition at line 469 of file pipeline.hpp.
References nodes_list.
Referenced by run().
void ff::ff_pipeline::cleanup_nodes () inline
Delete nodes when the destructor is called.
Definition at line 264 of file pipeline.hpp.
References node_cleanup.
int ff::ff_pipeline::create_input_buffer (int nentries, bool fixedsize) inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 550 of file pipeline.hpp.
References ff::error(), ff::ff_node::get_in_buffer(), ff::ff_node::in, nodes_list, and ff::ff_node::set_input_buffer().
Referenced by prepare(), and wrap_around().
int ff::ff_pipeline::create_output_buffer (int nentries, bool fixedsize = false) inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 563 of file pipeline.hpp.
References ff::error(), fixedsize, ff::ff_node::get_out_buffer(), nodes_list, and ff::ff_node::set_output_buffer().
Referenced by prepare().
void ff::ff_pipeline::ffStats (std::ostream & out) inline
TODO
Definition at line 512 of file pipeline.hpp.
double ff::ff_pipeline::ffTime () inline virtual
Gets the time.
It retrives the tim spent in FastFlow pattern.
Returns
The difference in the time spent.
Reimplemented from ff::ff_node.
Definition at line 483 of file pipeline.hpp.
References ff::diffmsec(), and nodes_list.
double ff::ff_pipeline::ffwTime () inline
Definition at line 494 of file pipeline.hpp.
References ff::diffmsec(), and nodes_list.
void ff::ff_pipeline::freeze () inline virtual
It freeze all stages.
Reimplemented from ff::ff_node.
Definition at line 374 of file pipeline.hpp.
References nodes_list.
Referenced by freeze_and_run(), and run_then_freeze().
int ff::ff_pipeline::freeze_and_run (bool = false) inline protected virtual
This function is required when no manager threads are present in the pipeline, which would allow to freeze other threads before starting the computation.
Returns
TODO
Reimplemented from ff::ff_node.
Definition at line 174 of file pipeline.hpp.
References ff::error(), freeze(), nodes_list, prepare(), and prepared.
Referenced by run().
int ff::ff_pipeline::getCPUId () inline protected
TODO
Definition at line 545 of file pipeline.hpp.
bool ff::ff_pipeline::isfrozen () inline virtual
It checks if the pipeline is frozen
Reimplemented from ff::ff_node.
Definition at line 388 of file pipeline.hpp.
References nodes_list.
Referenced by run_and_wait_end(), and run_then_freeze().
bool ff::ff_pipeline::load_result (void ** task, unsigned int retry = ((unsigned int)-1), unsigned int ticks = ff_node::TICKS2WAIT) inline
It loads results. If false, EOS arrived or too many retries. If true, there is a new value
Definition at line 421 of file pipeline.hpp.
References ff::error(), ff::FF_EOS, FFBUFFER, ff::ff_node::get_out_buffer(), has_input_channel, and ff::ticks_wait().
bool ff::ff_pipeline::load_result_nb (void ** task) inline
TODO
Returns
values: false: no task present true : there is a new value, you should check if the task is an FF_EOS
Definition at line 450 of file pipeline.hpp.
References ff::error(), FFBUFFER, ff::ff_node::get_out_buffer(), and has_input_channel.
bool ff::ff_pipeline::offload (void * task, unsigned int retry = ((unsigned int)-1), unsigned int ticks = ff_node::TICKS2WAIT) inline
offfload the given task to the pipeline
Definition at line 398 of file pipeline.hpp.
References ff::error(), FFBUFFER, ff::ff_node::get_in_buffer(), has_input_channel, and ff::ticks_wait().
int ff::ff_pipeline::prepare () inline protected
It prepare the Pipeline skeleton for execution.
Returns
TODO
Definition at line 127 of file pipeline.hpp.
References create_input_buffer(), create_output_buffer(), ff::error(), fixedsize, ff::ff_node::get_in_buffer(), ff::ff_node::get_out_buffer(), has_input_channel, in_buffer_entries, nodes_list, out_buffer_entries, prepared, and set_output_buffer().
Referenced by freeze_and_run(), run(), and run_then_freeze().
int ff::ff_pipeline::run (bool skip_init = false) inline virtual
It run the Pipeline skeleton.
Reimplemented from ff::ff_node.
Definition at line 269 of file pipeline.hpp.
References ff::ff_node::barrier, BARRIER_T, cardinality(), ff::error(), freeze_and_run(), has_input_channel, MAX_NUM_THREADS, nodes_list, prepare(), and prepared.
Referenced by run_and_wait_end(), and run_then_freeze().
int ff::ff_pipeline::run_and_wait_end () inline
It run and wait all threads to finish.
Definition at line 313 of file pipeline.hpp.
References isfrozen(), run(), stop(), and wait().
int ff::ff_pipeline::run_then_freeze () inline
It run and then freeze.
Definition at line 324 of file pipeline.hpp.
References freeze(), isfrozen(), prepare(), prepared, run(), and thaw().
int ff::ff_pipeline::set_output_buffer (FFBUFFER *const o) inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 578 of file pipeline.hpp.
References ff::error(), and nodes_list.
Referenced by prepare(), and wrap_around().
void ff::ff_pipeline::setAffinity (int) inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 538 of file pipeline.hpp.
References ff::error().
void ff::ff_pipeline::stop () inline virtual
It stops all stages.
Reimplemented from ff::ff_node.
Definition at line 367 of file pipeline.hpp.
References nodes_list.
Referenced by run_and_wait_end().
void* ff::ff_pipeline::svc (void * task) inline protected virtual
TODO
Implements ff::ff_node.
Definition at line 522 of file pipeline.hpp.
void ff::ff_pipeline::svc_end () inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 532 of file pipeline.hpp.
int ff::ff_pipeline::svc_init () inline protected virtual
TODO
Reimplemented from ff::ff_node.
Definition at line 527 of file pipeline.hpp.
void ff::ff_pipeline::thaw (bool _freeze = false) inline virtual
It Thaws all frozen stages. if _freeze is true at next step all threads are frozen again
Reimplemented from ff::ff_node.
Definition at line 381 of file pipeline.hpp.
References nodes_list.
Referenced by run_then_freeze().
int ff::ff_pipeline::wait () inline virtual
It waits for a stage to complete its task
Reimplemented from ff::ff_node.
Definition at line 338 of file pipeline.hpp.
References ff::error(), ff::ff_node::get_my_id(), and nodes_list.
Referenced by run_and_wait_end().
int ff::ff_pipeline::wait_freezing () inline virtual
It waits for freezing.
Reimplemented from ff::ff_node.
Definition at line 352 of file pipeline.hpp.
References ff::error(), ff::ff_node::get_my_id(), and nodes_list.
int ff::ff_pipeline::wrap_around () inline
The last stage output queue will be connected to the first stage input queue (feedback channel).
Definition at line 241 of file pipeline.hpp.
References create_input_buffer(), ff::error(), fixedsize, ff::ff_node::get_in_buffer(), nodes_list, out_buffer_entries, and set_output_buffer().
Member Data Documentation
bool ff::ff_pipeline::fixedsize private
Definition at line 593 of file pipeline.hpp.
Referenced by create_output_buffer(), prepare(), and wrap_around().
bool ff::ff_pipeline::has_input_channel private
Definition at line 590 of file pipeline.hpp.
Referenced by load_result(), load_result_nb(), offload(), prepare(), and run().
int ff::ff_pipeline::in_buffer_entries private
Definition at line 594 of file pipeline.hpp.
Referenced by prepare().
bool ff::ff_pipeline::node_cleanup private
Definition at line 592 of file pipeline.hpp.
Referenced by cleanup_nodes(), and ~ff_pipeline().
std::vector<ff_node *> ff::ff_pipeline::nodes_list private
Definition at line 596 of file pipeline.hpp.
Referenced by add_stage(), cardinality(), create_input_buffer(), create_output_buffer(), ffTime(), ffwTime(), freeze(), freeze_and_run(), isfrozen(), prepare(), run(), set_output_buffer(), stop(), thaw(), wait(), wait_freezing(), wrap_around(), and ~ff_pipeline().
int ff::ff_pipeline::out_buffer_entries private
Definition at line 595 of file pipeline.hpp.
Referenced by prepare(), and wrap_around().
bool ff::ff_pipeline::prepared private
Definition at line 591 of file pipeline.hpp.
Referenced by freeze_and_run(), prepare(), run(), and run_then_freeze().
The documentation for this class was generated from the following file:
pipeline.hpp