fix8: ff::ff_ofarm::ofarmC Class Reference
ff::ff_ofarm::ofarmC Class Reference
Public Member Functions
ofarmC (ofarm_gt *const gt)
Constructor.
void setnworkers (int nw)
Sets worker.
void setfilter (ff_node *f)
Sets filter.
int svc_init ()
svc_init method
void * svc (void *task)
svc method
void eosnotify (int id)
Notifies EOS.
void svc_end ()
svc_end method
Public Member Functions inherited from ff::ff_node
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Private Attributes
int nworkers
int nextone
ofarm_gt * gt
ff_node * C_f
Additional Inherited Members
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
virtual bool push (void *ptr)
Pushes to output buffer.
virtual bool pop (void **ptr)
Pops the data from input buffer.
virtual void skipfirstpop (bool sk)
Skips the first element popped.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int run (bool=false)
Executes the FastFlow thread.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait ()
Waits for thread termination.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual int cardinality (BARRIER_T *const b)
Counts how many threads there are in this node.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Detailed Description
inline class collector for oredred farm
Definition at line 1260 of file farm.hpp.
Constructor & Destructor Documentation
ff::ff_ofarm::ofarmC::ofarmC (ofarm_gt *const gt) inline
Constructor.
it defines the collectors for the oredered farm.
Definition at line 1268 of file farm.hpp.
Member Function Documentation
void ff::ff_ofarm::ofarmC::eosnotify (int id) inline virtual
Notifies EOS.
notifies the EOS.
Reimplemented from ff::ff_node.
Definition at line 1326 of file farm.hpp.
References gt, nextone, ff::ofarm_gt::set_dead(), and ff::ofarm_gt::set_victim().
void ff::ff_ofarm::ofarmC::setfilter (ff_node * f) inline
Sets filter.
It sets the filter.
Definition at line 1286 of file farm.hpp.
References C_f.
Referenced by ff::ff_ofarm::run().
void ff::ff_ofarm::ofarmC::setnworkers (int nw) inline
Sets worker.
It sets the number of workers
nw is the number of workers
Definition at line 1278 of file farm.hpp.
Referenced by ff::ff_ofarm::run().
void* ff::ff_ofarm::ofarmC::svc (void * task) inline virtual
svc method
It defines the svc method.
Returns
GO_ON is always returned.
Implements ff::ff_node.
Definition at line 1312 of file farm.hpp.
References C_f, ff::ff_node::ff_send_out(), GO_ON, gt, nextone, ff::ofarm_gt::set_victim(), and ff::ff_node::svc().
void ff::ff_ofarm::ofarmC::svc_end () inline virtual
svc_end method
It defines the svc_end method.
Reimplemented from ff::ff_node.
Definition at line 1339 of file farm.hpp.
References C_f, and ff::ff_node::svc_end().
int ff::ff_ofarm::ofarmC::svc_init () inline virtual
svc_init method
It defines the svc_init method.
Returns
0 if successful, otherwise the status of set_victim
Reimplemented from ff::ff_node.
Definition at line 1295 of file farm.hpp.
References C_f, gt, nextone, ff::ofarm_gt::reset(), ff::ofarm_gt::set_victim(), and ff::ff_node::svc_init().
Member Data Documentation
ff_node* ff::ff_ofarm::ofarmC::C_f private
Definition at line 1346 of file farm.hpp.
Referenced by setfilter(), svc(), svc_end(), and svc_init().
ofarm_gt* ff::ff_ofarm::ofarmC::gt private
Definition at line 1345 of file farm.hpp.
Referenced by eosnotify(), svc(), and svc_init().
int ff::ff_ofarm::ofarmC::nextone private
Definition at line 1344 of file farm.hpp.
Referenced by eosnotify(), svc(), and svc_init().
int ff::ff_ofarm::ofarmC::nworkers private
Definition at line 1343 of file farm.hpp.
The documentation for this class was generated from the following file:
farm.hpp