fix8: ff::zmqBcast Class Reference
ff::zmqBcast Class Reference
It implements the broadcast communication pattern of FastFlow in ZeroMQ.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 0 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
a ØMQ message (extends zmq::message_t)
typedef msg_t tosend_t
to the transpoort layer
typedef msg_t torecv_t
ut supra
typedef descriptor1_N descriptor
ut supra
Public Member Functions
zmqBcast ()
zmqBcast (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const msg_t &msg, const int to)
bool putmore (const msg_t &msg, const int to)
bool gethdr (torecv_t &msg, int &peer)
bool get (torecv_t &msg, int=0)
int getToWait () const
int putToPerform () const
bool close ()
void done ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
It implements the broadcast communication pattern of FastFlow in ZeroMQ.
This class is defined in zmqImpl.hpp
Definition at line 989 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptor1_N ff::zmqBcast::descriptor
ut supra
      descriptor used in Unicast, Bcast, Scatter,
On-Demand, OneToMany
Definition at line 995 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmqBcast::msg_t
Definition at line 991 of file zmqImpl.hpp.
typedef msg_t ff::zmqBcast::torecv_t
ut supra
Definition at line 994 of file zmqImpl.hpp.
typedef msg_t ff::zmqBcast::tosend_t
to the transpoort layer
Definition at line 993 of file zmqImpl.hpp.
typedef zmqTransport ff::zmqBcast::TransportImpl
a ØMQ message (extends zmq::message_t)
Definition at line 992 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 998 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmqBcast::zmqBcast () inline
Constructor
Definition at line 1003 of file zmqImpl.hpp.
ff::zmqBcast::zmqBcast (descriptor * D) inline
Constructor (2)
Parameters
D pointer to a 1_N descriptor object.
Definition at line 1010 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmqBcast::close () inline
It closes the communication pattern.
Returns
TODO
Definition at line 1123 of file zmqImpl.hpp.
References active, ff::descriptor1_N::close(), and desc.
void ff::zmqBcast::done () inline
It finishes the communication.
Definition at line 1133 of file zmqImpl.hpp.
bool ff::zmqBcast::get (torecv_t & msg, int = 0) inline
It receives one message.
msg is the reference to the message.
Returns
TODO
Definition at line 1102 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recv().
descriptor* ff::zmqBcast::getDescriptor () inline
It returns the descriptor.
Returns
It returns the descriptor.
Definition at line 1027 of file zmqImpl.hpp.
References desc.
bool ff::zmqBcast::gethdr (torecv_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg is the reference to the message. peer is the number of peers.
Returns
TODO
Definition at line 1093 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recvhdr().
int ff::zmqBcast::getToWait () const inline
It puts the node in the waiting state.
Returns
TODO
Definition at line 1109 of file zmqImpl.hpp.
bool ff::zmqBcast::init (const std::string & address, const int nodeId = -1) inline
It initializes the communication pattern.
Parameters
addr is the IP address in the form 'ip/host:port'
nodeId is the node identifier in the range [0..inf[
Returns
TODO
Definition at line 1037 of file zmqImpl.hpp.
References active, desc, and ff::descriptor1_N::init().
bool ff::zmqBcast::put (const tosend_t & msg) inline
It sends one message.
Parameters
msg is a reference to the message to be sent.
Returns
TODO
Definition at line 1050 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmqBcast::put (const msg_t & msg, const int to) inline
It sens the message.
msg is the reference to the message. to is the address of the node where the message should be sent.
Returns
TODO
Definition at line 1069 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmqBcast::putmore (const tosend_t & msg) inline
It sends other parts of a multi-part message.
Parameters
msg is a reference to the message to be sent.
Returns
TODO
Definition at line 1059 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::sendmore().
bool ff::zmqBcast::putmore (const msg_t & msg, const int to) inline
It sen the message to more nodes.
msg is the reference to the message. to is the address of the node where the message should be sent.
Returns
TODO
Definition at line 1081 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::sendmore().
int ff::zmqBcast::putToPerform () const inline
It puts the node to peforming state.
Returns
TODO
Definition at line 1116 of file zmqImpl.hpp.
void ff::zmqBcast::setDescriptor (descriptor * D) inline
It sets the descriptor.
D is the descriptor.
Definition at line 1017 of file zmqImpl.hpp.
References ff::descriptor1_N::close(), and desc.
Member Data Documentation
bool ff::zmqBcast::active protected
Definition at line 1137 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmqBcast::desc protected
Definition at line 1136 of file zmqImpl.hpp.
Referenced by close(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp