fix8: FIX8::Field< MonthYear, field > Class Template Reference
FIX8::Field< MonthYear, field > Class Template Reference
Partial specialisation for MonthYear field type.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const f8String &from, const RealmBase *rlm=nullptr)
Field (const char *from, const RealmBase *rlm=nullptr)
Field (const tm &from, const RealmBase *rlm=nullptr)
~Field ()
Dtor.
Field & operator= (const Field &that)
Assignment operator.
bool operator== (const BaseField &that) const
Equivalence operator.
bool operator< (const BaseField &that) const
Less than operator.
virtual bool operator> (const BaseField &that) const
Greater than operator.
const Tickval & get () const
const Tickval & operator() () const
void set (const Tickval &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
virtual int get_rlm_idx () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Private Attributes
size_t _sz
Tickval _value
Static Private Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_string
Additional Inherited Members
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<unsigned short field>
class FIX8::Field< MonthYear, field >
Partial specialisation for MonthYear field type.
Template Parameters
field field number (fix tag)
Definition at line 1446 of file field.hpp.
Constructor & Destructor Documentation
template<unsigned short field> FIX8::Field< MonthYear, field >::Field () inline
Ctor.
Definition at line 1460 of file field.hpp.
 : BaseField(field) {}
template<unsigned short field> FIX8::Field< MonthYear, field >::Field (const Field< MonthYear, field > & from) inline
Copy Ctor.
Definition at line 1464 of file field.hpp.
 : BaseField(field), _sz(from._sz), _value(from._value) {}
template<unsigned short field> FIX8::Field< MonthYear, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 1469 of file field.hpp.
 : BaseField(field), _sz(from.size()), _value(date_parse(from.data(), _sz)) {}
template<unsigned short field> FIX8::Field< MonthYear, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 1474 of file field.hpp.
 : BaseField(field), _sz(from ? ::strlen(from) : 0), _value(date_parse(from, _sz)) {}
template<unsigned short field> FIX8::Field< MonthYear, field >::Field (const tm & from, const RealmBase * rlm = nullptr) inline
Construct from tm struct
Parameters
from string to construct field from
rlm tm struct with broken out values
Definition at line 1479 of file field.hpp.
 : BaseField(field), _sz(6), _value(time_to_epoch(from) * Tickval::billion) {}
template<unsigned short field> FIX8::Field< MonthYear, field >::~Field () inline
Dtor.
Definition at line 1482 of file field.hpp.
 {}
Member Function Documentation
template<unsigned short field> Field* FIX8::Field< MonthYear, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 1526 of file field.hpp.
References FIX8::Field< T, field >::Field().
 { return new Field(*this); }
template<unsigned short field> const Tickval& FIX8::Field< MonthYear, field >::get () const inline
Get field value.
Returns
value Tickval&
Definition at line 1514 of file field.hpp.
 { return _value; }
template<unsigned short field> static unsigned short FIX8::Field< MonthYear, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 1454 of file field.hpp.
 { return field; }
template<unsigned short field> FieldTrait::FieldType FIX8::Field< MonthYear, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 1457 of file field.hpp.
 { return _ftype; }
template<unsigned short field> const Tickval& FIX8::Field< MonthYear, field >::operator() () const inline
Get field value.
Returns
value Tickval&
Definition at line 1518 of file field.hpp.
 { return _value; }
template<unsigned short field> bool FIX8::Field< MonthYear, field >::operator< (const BaseField< MonthYear, field > & that) const inline virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implements FIX8::BaseField.
Definition at line 1503 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value < static_cast<const Field<MonthYear, field>&>(that)._value; }
template<unsigned short field> Field& FIX8::Field< MonthYear, field >::operator= (const Field< MonthYear, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 1487 of file field.hpp.
    {
       if (this != &that)
          _value = that._value;
       return *this;
    }
template<unsigned short field> bool FIX8::Field< MonthYear, field >::operator== (const BaseField< MonthYear, field > & that) const inline virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implements FIX8::BaseField.
Definition at line 1497 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && static_cast<const Field<MonthYear, field>&>(that)._value == _value; }
template<unsigned short field> virtual bool FIX8::Field< MonthYear, field >::operator> (const BaseField< MonthYear, field > & that) const inline virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implements FIX8::BaseField.
Definition at line 1509 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value > static_cast<const Field<MonthYear, field>&>(that)._value; }
template<unsigned short field> std::ostream& FIX8::Field< MonthYear, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 1531 of file field.hpp.
References FIX8::MAX_MSGTYPE_FIELD_LEN(), and FIX8::BaseField::print().
    {
       char buf[MAX_MSGTYPE_FIELD_LEN] {};
       print(buf);
       return os << buf;
    }
template<unsigned short field> size_t FIX8::Field< MonthYear, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 1541 of file field.hpp.
References FIX8::_date_only, FIX8::_short_date_only, and FIX8::date_time_format().
 { return date_time_format(_value, to, _sz == 6 ? _short_date_only : _date_only); }
template<unsigned short field> void FIX8::Field< MonthYear, field >::set (const Tickval & from) inline
Set field to the supplied value.
Parameters
from value to set
Definition at line 1522 of file field.hpp.
References FIX8::BaseField::from().
 { _value = from; }
Member Data Documentation
template<unsigned short field> const FieldTrait::FieldType FIX8::Field< MonthYear, field >::_ftype = FieldTrait::ft_string static private
Definition at line 1450 of file field.hpp.
template<unsigned short field> size_t FIX8::Field< MonthYear, field >::_sz private
Definition at line 1448 of file field.hpp.
template<unsigned short field> Tickval FIX8::Field< MonthYear, field >::_value private
Definition at line 1449 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp