fix8: tex_router_server Class Reference
tex_router_server Class Reference
Example server message router. Derives from fix8 generated router class.
#include <hftest.hpp>
Public Member Functions
tex_router_server (hf_session_server &session)
virtual bool operator() (const FIX8::TEX::NewOrderSingle *msg)
tex_router_server (myfix_session_server &session)
virtual bool operator() (const FIX8::TEX::NewOrderSingle *msg) const
Public Member Functions inherited from FIX8::TEX::Myfix_Router
Myfix_Router ()
virtual ~Myfix_Router ()
virtual bool operator() (const class Message *msg) const
virtual bool operator() (const class Heartbeat *msg) const
virtual bool operator() (const class TestRequest *msg) const
virtual bool operator() (const class ResendRequest *msg) const
virtual bool operator() (const class Reject *msg) const
virtual bool operator() (const class SequenceReset *msg) const
virtual bool operator() (const class Logout *msg) const
virtual bool operator() (const class IOI *msg) const
virtual bool operator() (const class Advertisement *msg) const
virtual bool operator() (const class ExecutionReport *msg) const
virtual bool operator() (const class OrderCancelReject *msg) const
virtual bool operator() (const class Logon *msg) const
virtual bool operator() (const class DerivativeSecurityList *msg) const
virtual bool operator() (const class NewOrderMultileg *msg) const
virtual bool operator() (const class MultilegOrderCancelReplace *msg) const
virtual bool operator() (const class TradeCaptureReportRequest *msg) const
virtual bool operator() (const class TradeCaptureReport *msg) const
virtual bool operator() (const class OrderMassStatusRequest *msg) const
virtual bool operator() (const class QuoteRequestReject *msg) const
virtual bool operator() (const class RFQRequest *msg) const
virtual bool operator() (const class QuoteStatusReport *msg) const
virtual bool operator() (const class QuoteResponse *msg) const
virtual bool operator() (const class Confirmation *msg) const
virtual bool operator() (const class PositionMaintenanceRequest *msg) const
virtual bool operator() (const class PositionMaintenanceReport *msg) const
virtual bool operator() (const class RequestForPositions *msg) const
virtual bool operator() (const class RequestForPositionsAck *msg) const
virtual bool operator() (const class PositionReport *msg) const
virtual bool operator() (const class TradeCaptureReportRequestAck *msg) const
virtual bool operator() (const class TradeCaptureReportAck *msg) const
virtual bool operator() (const class AllocationReport *msg) const
virtual bool operator() (const class AllocationReportAck *msg) const
virtual bool operator() (const class ConfirmationAck *msg) const
virtual bool operator() (const class SettlementInstructionRequest *msg) const
virtual bool operator() (const class AssignmentReport *msg) const
virtual bool operator() (const class CollateralRequest *msg) const
virtual bool operator() (const class CollateralAssignment *msg) const
virtual bool operator() (const class CollateralResponse *msg) const
virtual bool operator() (const class News *msg) const
virtual bool operator() (const class CollateralReport *msg) const
virtual bool operator() (const class CollateralInquiry *msg) const
virtual bool operator() (const class NetworkCounterpartySystemStatusRequest *msg) const
virtual bool operator() (const class NetworkCounterpartySystemStatusResponse *msg) const
virtual bool operator() (const class UserRequest *msg) const
virtual bool operator() (const class UserResponse *msg) const
virtual bool operator() (const class CollateralInquiryAck *msg) const
virtual bool operator() (const class ConfirmationRequest *msg) const
virtual bool operator() (const class TradingSessionListRequest *msg) const
virtual bool operator() (const class TradingSessionList *msg) const
virtual bool operator() (const class SecurityListUpdateReport *msg) const
virtual bool operator() (const class AdjustedPositionReport *msg) const
virtual bool operator() (const class AllocationInstructionAlert *msg) const
virtual bool operator() (const class ExecutionAcknowledgement *msg) const
virtual bool operator() (const class ContraryIntentionReport *msg) const
virtual bool operator() (const class SecurityDefinitionUpdateReport *msg) const
virtual bool operator() (const class SettlementObligationReport *msg) const
virtual bool operator() (const class DerivativeSecurityListUpdateReport *msg) const
virtual bool operator() (const class TradingSessionListUpdateReport *msg) const
virtual bool operator() (const class MarketDefinitionRequest *msg) const
virtual bool operator() (const class MarketDefinition *msg) const
virtual bool operator() (const class MarketDefinitionUpdateReport *msg) const
virtual bool operator() (const class ApplicationMessageRequest *msg) const
virtual bool operator() (const class ApplicationMessageRequestAck *msg) const
virtual bool operator() (const class ApplicationMessageReport *msg) const
virtual bool operator() (const class OrderMassActionReport *msg) const
virtual bool operator() (const class Email *msg) const
virtual bool operator() (const class OrderMassActionRequest *msg) const
virtual bool operator() (const class UserNotification *msg) const
virtual bool operator() (const class StreamAssignmentRequest *msg) const
virtual bool operator() (const class StreamAssignmentReport *msg) const
virtual bool operator() (const class StreamAssignmentReportACK *msg) const
virtual bool operator() (const class PartyDetailsListRequest *msg) const
virtual bool operator() (const class PartyDetailsListReport *msg) const
virtual bool operator() (const class NewOrderSingle *msg) const
virtual bool operator() (const class NewOrderList *msg) const
virtual bool operator() (const class OrderCancelRequest *msg) const
virtual bool operator() (const class OrderCancelReplaceRequest *msg) const
virtual bool operator() (const class OrderStatusRequest *msg) const
virtual bool operator() (const class AllocationInstruction *msg) const
virtual bool operator() (const class ListCancelRequest *msg) const
virtual bool operator() (const class ListExecute *msg) const
virtual bool operator() (const class ListStatusRequest *msg) const
virtual bool operator() (const class ListStatus *msg) const
virtual bool operator() (const class AllocationInstructionAck *msg) const
virtual bool operator() (const class DontKnowTrade *msg) const
virtual bool operator() (const class QuoteRequest *msg) const
virtual bool operator() (const class Quote *msg) const
virtual bool operator() (const class SettlementInstructions *msg) const
virtual bool operator() (const class MarketDataRequest *msg) const
virtual bool operator() (const class MarketDataSnapshotFullRefresh *msg) const
virtual bool operator() (const class MarketDataIncrementalRefresh *msg) const
virtual bool operator() (const class MarketDataRequestReject *msg) const
virtual bool operator() (const class QuoteCancel *msg) const
virtual bool operator() (const class QuoteStatusRequest *msg) const
virtual bool operator() (const class MassQuoteAcknowledgement *msg) const
virtual bool operator() (const class SecurityDefinitionRequest *msg) const
virtual bool operator() (const class SecurityDefinition *msg) const
virtual bool operator() (const class SecurityStatusRequest *msg) const
virtual bool operator() (const class SecurityStatus *msg) const
virtual bool operator() (const class TradingSessionStatusRequest *msg) const
virtual bool operator() (const class TradingSessionStatus *msg) const
virtual bool operator() (const class MassQuote *msg) const
virtual bool operator() (const class BusinessMessageReject *msg) const
virtual bool operator() (const class BidRequest *msg) const
virtual bool operator() (const class BidResponse *msg) const
virtual bool operator() (const class ListStrikePrice *msg) const
virtual bool operator() (const class RegistrationInstructions *msg) const
virtual bool operator() (const class RegistrationInstructionsResponse *msg) const
virtual bool operator() (const class OrderMassCancelRequest *msg) const
virtual bool operator() (const class OrderMassCancelReport *msg) const
virtual bool operator() (const class NewOrderCross *msg) const
virtual bool operator() (const class CrossOrderCancelReplaceRequest *msg) const
virtual bool operator() (const class CrossOrderCancelRequest *msg) const
virtual bool operator() (const class SecurityTypeRequest *msg) const
virtual bool operator() (const class SecurityTypes *msg) const
virtual bool operator() (const class SecurityListRequest *msg) const
virtual bool operator() (const class SecurityList *msg) const
virtual bool operator() (const class DerivativeSecurityListRequest *msg) const
Public Member Functions inherited from FIX8::Router
virtual ~Router ()
Dtor.
virtual bool operator() (const Message *msg) const
virtual bool operator() (const Message *msg)
Public Member Functions inherited from FIX8::TEX::Perf_Router
Perf_Router ()
virtual ~Perf_Router ()
virtual bool operator() (const class Message *msg)
virtual bool operator() (const class Heartbeat *msg)
virtual bool operator() (const class TestRequest *msg)
virtual bool operator() (const class ResendRequest *msg)
virtual bool operator() (const class Reject *msg)
virtual bool operator() (const class SequenceReset *msg)
virtual bool operator() (const class Logout *msg)
virtual bool operator() (const class ExecutionReport *msg)
virtual bool operator() (const class Logon *msg)
virtual bool operator() (const class NewOrderSingle *msg)
Private Attributes
hf_session_server & _session
myfix_session_server & _session
Detailed Description
Example server message router. Derives from fix8 generated router class.
Your application must define a class similar to this in order to receive the appropriate callback when Message::process is called.
Definition at line 108 of file hftest.hpp.
Constructor & Destructor Documentation
tex_router_server::tex_router_server (hf_session_server & session) inline
Ctor.
Parameters
session server session
Definition at line 115 of file hftest.hpp.
 : _session(session) {}
tex_router_server::tex_router_server (myfix_session_server & session) inline
Ctor.
Parameters
session server session
Definition at line 102 of file myfix.hpp.
 : _session(session) {}
Member Function Documentation
bool tex_router_server::operator() (const FIX8::TEX::NewOrderSingle * msg) const virtual
NewOrderSingle message handler. Here is where you provide your own methods for the messages you wish to handle. Only those messages that are of interest to you need to be implemented.
Parameters
msg NewOrderSingle message
Definition at line 387 of file harness.cpp.
 {
    return true;
 }
bool tex_router_server::operator() (const FIX8::TEX::NewOrderSingle * msg) virtual
NewOrderSingle message handler. Here is where you provide your own methods for the messages you wish to handle. Only those messages that are of interest to you need to be implemented.
Parameters
msg NewOrderSingle message
Definition at line 585 of file hftest.cpp.
References FIX8::MessageBase::copy_legal(), FIX8::TEX::ExecTransType_NEW(), FIX8::TEX::ExecType_NEW(), FIX8::MessageBase::get(), RandDev::getrandom(), FIX8::TEX::OrdStatus_CANCELED(), FIX8::TEX::OrdStatus_FILLED(), FIX8::TEX::OrdStatus_NEW(), FIX8::TEX::OrdStatus_PARTIALLY_FILLED(), and FIX8::TEX::OrdStatus_REJECTED().
 {
    static unsigned oid(0), eoid(0);
    FIX8::TEX::OrderQty qty;
    FIX8::TEX::Price price;
    msg->get(qty);
    msg->get(price);
    FIX8::TEX::ExecutionReport *er(new FIX8::TEX::ExecutionReport);
    msg->copy_legal(er);
    ostringstream oistr;
    oistr << "ord" << ++oid;
    *er << new FIX8::TEX::OrderID(oistr.str())
        << new FIX8::TEX::ExecType(FIX8::TEX::ExecType_NEW);
    unsigned ordResult(RandDev::getrandom(3));
    switch (ordResult)
    {
    default:
    case 0:
       *er << new FIX8::TEX::OrdStatus(FIX8::TEX::OrdStatus_NEW);
       break;
    case 1:
       *er << new FIX8::TEX::OrdStatus(FIX8::TEX::OrdStatus_CANCELED);
       break;
    case 2:
       *er << new FIX8::TEX::OrdStatus(FIX8::TEX::OrdStatus_REJECTED);
       break;
    }
    *er   << new FIX8::TEX::LeavesQty(qty())
          << new FIX8::TEX::CumQty(0.)
          << new FIX8::TEX::AvgPx(0.)
          << new FIX8::TEX::LastCapacity('5')
          << new FIX8::TEX::ReportToExch('Y')
          << new FIX8::TEX::ExecTransType(FIX8::TEX::ExecTransType_NEW)
          << new FIX8::TEX::ExecID(oistr.str());
    _session.send(er);
    if (ordResult == 0)
    {
       unsigned remaining_qty(qty()), cum_qty(0);
       while (remaining_qty > 0)
       {
          unsigned trdqty(1 + RandDev::getrandom(remaining_qty));
          remaining_qty -= trdqty;
          cum_qty += trdqty;
          FIX8::TEX::ExecutionReport *ner(new FIX8::TEX::ExecutionReport);
          msg->copy_legal(ner);
          ostringstream eistr;
          eistr << "exec" << ++eoid;
          *ner  << new FIX8::TEX::ExecID(eistr.str())
                << new FIX8::TEX::OrderID(oistr.str())
                << new FIX8::TEX::ExecType(FIX8::TEX::ExecType_NEW)
                << new FIX8::TEX::OrdStatus(remaining_qty == trdqty ? FIX8::TEX::OrdStatus_FILLED : FIX8::TEX::OrdStatus_PARTIALLY_FILLED)
                << new FIX8::TEX::LeavesQty(remaining_qty)
                << new FIX8::TEX::CumQty(cum_qty)
                << new FIX8::TEX::ExecTransType(FIX8::TEX::ExecTransType_NEW)
                << new FIX8::TEX::AvgPx(price());
          _session.send(ner);
       }
    }
    return true;
 }
Member Data Documentation
myfix_session_server& tex_router_server::_session private
Definition at line 97 of file myfix.hpp.
hf_session_server& tex_router_server::_session private
Definition at line 110 of file hftest.hpp.
The documentation for this class was generated from the following files:
hftest.hpp
myfix.hpp
harness.cpp
hftest.cpp
myfix.cpp