fix8: FIX8::MessageBase Class Reference
FIX8::MessageBase Class Reference
Base class for all fix messages.
#include <message.hpp>
Public Member Functions
template<typename InputIterator >
MessageBase (const struct F8MetaCntx &ctx, const f8String &msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array *ftha)
F8API MessageBase (const MessageBase &from)
Copy ctor.
F8API MessageBase & operator= (const MessageBase &that)
Assignment operator.
virtual ~MessageBase ()
Dtor.
virtual void clear (bool reuse=true)
void clear_positions ()
empty the positions map
size_t size () const
F8API unsigned decode (const f8String &from, unsigned offset, unsigned ignore=0, bool permissive_mode=false)
unsigned decode_group (GroupBase *grpbase, const unsigned short fnum, const f8String &from, unsigned s_offset, unsigned ignore)
F8API size_t encode (std::ostream &to) const
F8API size_t encode (char *to) const
F8API size_t encode_group (const unsigned short fnum, std::ostream &to) const
F8API size_t encode_group (const unsigned short fnum, char *to) const
virtual GroupBase * create_nested_group (unsigned short fnum) const
F8API unsigned check_positions ()
F8API unsigned copy_legal (MessageBase *to, bool force=false) const
F8API unsigned move_legal (MessageBase *to, bool force=false)
void push_unknown (MessageBase *to) const
void check_set_rlm (BaseField *where) const
const f8String & get_msgtype () const
void add_field_decoder (const unsigned short fnum, const unsigned pos, BaseField *what)
void add_field (const unsigned short fnum, Presence::const_iterator itr, const unsigned pos, BaseField *what, bool check)
void add_field (const unsigned short fnum, Fields::iterator fitr, const unsigned pos, BaseField *what, bool check=true)
void add_field (const unsigned short fnum, const unsigned pos, BaseField *what, bool check=true)
void set (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
template<typename T >
bool add_field (T *what)
bool add_field (BaseField *what)
Groups & get_groups ()
template<typename T >
bool operator+= (T *what)
template<typename T >
MessageBase & operator<< (T *what)
template<typename T >
bool get (T &to) const
template<typename T >
bool has () const
bool is_legal (unsigned short fnum) const
template<typename T >
bool is_legal () const
template<typename T >
const T * get () const
template<typename T >
bool operator() (T &to) const
template<typename T >
const T * operator() () const
bool have (const unsigned short fnum) const
Fields::const_iterator find_field (const unsigned short fnum) const
BaseField * get_field (const unsigned short fnum) const
BaseField * get_field_by_name (const char *tag) const
Fields::const_iterator fields_begin () const
Fields::const_iterator fields_end () const
F8API BaseField * replace (const unsigned short fnum, Presence::const_iterator itr, BaseField *with)
F8API BaseField * replace (const unsigned short fnum, BaseField *with)
F8API GroupBase * replace (const unsigned short fnum, GroupBase *with)
F8API BaseField * remove (const unsigned short fnum, Presence::const_iterator itr)
F8API BaseField * remove (const unsigned short fnum)
template<typename T >
GroupBase * find_group () const
GroupBase * find_group (const unsigned short fnum) const
template<typename T >
GroupBase * find_add_group (GroupBase *grpbase=nullptr)
GroupBase * find_add_group (const unsigned short fnum, GroupBase *grpbase=nullptr)
template<typename T >
void append_group (T *what)
void add_group (GroupBase *what)
MessageBase & operator<< (GroupBase *what)
void operator+= (GroupBase *what)
unsigned short getPos (const unsigned short field) const
bool add_trait (const FieldTrait &what)
template<typename InputIterator >
void add_trait (const InputIterator begin, const size_t cnt)
virtual F8API void print (std::ostream &os, int depth=0) const
virtual F8API void print_field (const unsigned short fnum, std::ostream &os) const
virtual F8API void print_group (const unsigned short fnum, std::ostream &os, int depth=0) const
const FieldTraits & get_fp () const
void print_fp (std::ostream &os)
virtual begin_string * get_begin_string ()
virtual body_length * get_body_length ()
virtual msg_type * get_msg_type ()
virtual check_sum * get_check_sum ()
const f8String & get_unknown () const
Static Public Member Functions
static unsigned extract_element (const char *from, const unsigned sz, char *tag, char *val)
static unsigned extract_element (const char *from, const unsigned sz, f8String &tag, f8String &val)
static void set_tabsize (unsigned tabsize)
static unsigned get_tabsize ()
static bool has_group_count (const BaseField *bf)
Static Protected Member Functions
static unsigned extract_header (const f8String &from, char *len, char *mtype)
static unsigned extract_trailer (const f8String &from, f8String &chksum)
Protected Attributes
Fields _fields
FieldTraits _fp
Positions _pos
Groups _groups
const f8String & _msgType
const F8MetaCntx & _ctx
Static Protected Attributes
static F8API unsigned _tabsize = defaults::tabsize
Private Attributes
f8String _unknown
pass through for permissive mode
Friends
class Message
std::ostream & operator<< (std::ostream &os, const MessageBase &what)
Detailed Description
Base class for all fix messages.
Definition at line 381 of file message.hpp.
Constructor & Destructor Documentation
template<typename InputIterator > FIX8::MessageBase::MessageBase (const struct F8MetaCntx & ctx, const f8String & msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array * ftha) inline
Ctor.
Template Parameters
InputIterator input iterator type
Parameters
ctx reference to generated metadata
msgType - reference to Fix message type
begin - InputIterator pointing to begining of field trait table
cnt - number of elements in field trait table
ftha - field trait hash array
Definition at line 419 of file message.hpp.
                                          : _fp(begin, cnt, ftha),
       _msgType(msgType), _ctx(ctx) {}
F8API FIX8::MessageBase::MessageBase (const MessageBase & from)
Copy ctor.
virtual FIX8::MessageBase::~MessageBase () inline virtual
Dtor.
Definition at line 429 of file message.hpp.
References clear().
 { clear(false); }
Member Function Documentation
void FIX8::MessageBase::add_field (const unsigned short fnum, Presence::const_iterator itr, const unsigned pos, BaseField * what, bool check) inline
Add fix field to this message.
Parameters
fnum field tag
itr hint iterator: set to itr of found element
pos position of field in message
what pointer to field
check if false, don't check for presence
Definition at line 556 of file message.hpp.
References FIX8::FieldTraits::get(), glout_debug, FIX8::FieldTrait::present, replace(), and FIX8::FieldTraits::set().
Referenced by add_field(), FIX8::TEX::header::add_preamble(), FIX8::TEX::trailer::add_preamble(), copy_legal(), FIX8::ConsoleMenu::EditMsg(), move_legal(), operator+=(), and operator<<().
    {
       if (check && _fp.get(fnum, itr, FieldTrait::present)) // for now, silently replace duplicate
       {
          glout_debug << _msgType << " replacing field:" << fnum;
          delete replace(fnum, itr, what);
          return;
       }
       _fields.insert({fnum, what});
       _pos.insert({pos, what});
       _fp.set(fnum, itr, FieldTrait::present);
    }
void FIX8::MessageBase::add_field (const unsigned short fnum, Fields::iterator fitr, const unsigned pos, BaseField * what, bool check = true) inline
Add fix field to this message.
Parameters
fnum field tag
fitr hint iterator: set to itr of found element
pos position of field in message
what pointer to field
check if false, don't check for presence
Definition at line 576 of file message.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::FieldTraits::get(), FIX8::FieldTraits::get_presence(), glout_debug, FIX8::FieldTrait::present, replace(), and FIX8::FieldTraits::set().
    {
       Presence::const_iterator itr(_fp.get_presence().end());
       if (check && _fp.get(fnum, itr, FieldTrait::present)) // for now, silently replace duplicate
       {
          glout_debug << _msgType << " replacing field:" << fnum;
          delete replace(fnum, itr, what);
          return;
       }
       _fields.insert(fitr, {fnum, what});
       _pos.insert({pos, what});
       _fp.set(fnum, itr, FieldTrait::present);
    }
void FIX8::MessageBase::add_field (const unsigned short fnum, const unsigned pos, BaseField * what, bool check = true) inline
Add fix field to this message.
Parameters
fnum field tag
pos position of field in message
what pointer to field
check if false, don't check for presence
Definition at line 596 of file message.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::FieldTraits::get(), FIX8::FieldTraits::get_presence(), glout_debug, FIX8::FieldTrait::present, replace(), and FIX8::FieldTraits::set().
    {
       Presence::const_iterator itr(_fp.get_presence().end());
       if (check && _fp.get(fnum, itr, FieldTrait::present)) // for now, silently replace duplicate
       {
          glout_debug << _msgType << " replacing field:" << fnum;
          delete replace(fnum, itr, what);
          return;
       }
       _fields.insert({fnum, what});
       _pos.insert({pos, what});
       _fp.set(fnum, itr, FieldTrait::present);
    }
template<typename T > bool FIX8::MessageBase::add_field (T * what) inline
Add fix field to this message.
Template Parameters
T field type
Parameters
what pointer to field
Returns
true on success; throws InvalidField if not valid
Definition at line 621 of file message.hpp.
References add_field(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::FieldTraits::get_presence(), FIX8::FieldTraits::getPos(), and FIX8::FieldTraits::has().
    {
       Presence::const_iterator itr(_fp.get_presence().end());
       if (_fp.has(T::get_field_id(), itr))
       {
          add_field(T::get_field_id(), itr, _fp.getPos(T::get_field_id(), itr), what, true);
          return true;
       }
       throw InvalidField(T::get_field_id());
       return false;
    }
bool FIX8::MessageBase::add_field (BaseField * what) inline
Add fix field to this message.
Template Parameters
T field type
Parameters
what pointer to field
Returns
true on success; throws InvalidField if not valid
Definition at line 637 of file message.hpp.
References FIX8::BaseField::_fnum, add_field(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::FieldTraits::get_presence(), FIX8::FieldTraits::getPos(), and FIX8::FieldTraits::has().
    {
       const unsigned short& fnum(what->_fnum);
       Presence::const_iterator itr(_fp.get_presence().end());
       if (_fp.has(fnum, itr))
       {
          add_field(fnum, itr, _fp.getPos(fnum, itr), what, true);
          return true;
       }
       throw InvalidField(fnum);
       return false;
    }
void FIX8::MessageBase::add_field_decoder (const unsigned short fnum, const unsigned pos, BaseField * what) inline
Add fix field to this message.
Parameters
fnum field tag
pos position of field in message
what pointer to field
Definition at line 544 of file message.hpp.
    {
       _fields.insert({fnum, what});
       _pos.insert({pos, what});
    }
void FIX8::MessageBase::add_group (GroupBase * what) inline
Add a repeating group to a message.
Parameters
what pointer to group to add
Definition at line 832 of file message.hpp.
References FIX8::GroupBase::_fnum.
Referenced by find_add_group(), operator+=(), and operator<<().
 { _groups.insert({what->_fnum, what}); }
bool FIX8::MessageBase::add_trait (const FieldTrait & what) inline
Add a fieldtrait to the message.
Parameters
what FieldTrait to add
Returns
true on success
Definition at line 851 of file message.hpp.
References FIX8::FieldTraits::add().
 { return _fp.add(what); }
template<typename InputIterator > void FIX8::MessageBase::add_trait (const InputIterator begin, const size_t cnt) inline
Add a range of fieldtraits to the message.
Template Parameters
InputIterator input iterator type
Parameters
begin first FieldTrait to add
cnt - number of elements in field trait table
Definition at line 858 of file message.hpp.
References FIX8::FieldTraits::add().
 { _fp.add(begin, cnt); }
template<typename T > void FIX8::MessageBase::append_group (T * what) inline
Add a repeating group at the end of a message group. Assume key is not < last.
Template Parameters
T type of grop being appended
Parameters
what pointer to group to add
Definition at line 828 of file message.hpp.
 { _groups.insert(_groups.end(), {T::_fnum, what}); }
unsigned MessageBase::check_positions ()
Check to see if positions of fields are as required.
Returns
field number of field not in order, 0 if all ok
Definition at line 199 of file message.cpp.
 {
    return 0; // TODO
 }
void FIX8::MessageBase::check_set_rlm (BaseField * where) const inline
Check that this field has the realm (domain) pointer set; if not then set.
Parameters
where field to check
Definition at line 526 of file message.hpp.
References FIX8::BaseField::_fnum, FIX8::BaseField::_rlm, and FIX8::F8MetaCntx::find_be().
Referenced by copy_legal().
    {
       if (!where->_rlm)
       {
          const BaseEntry *tbe(_ctx.find_be(where->_fnum));
          if (tbe && tbe->_rlm)
             where->_rlm = tbe->_rlm;   // populate realm;
       }
    }
virtual void FIX8::MessageBase::clear (bool reuse = true) inline virtual
Empty messages from container.
Parameters
reuse if true clear vector
Reimplemented in FIX8::Message.
Definition at line 433 of file message.hpp.
References FIX8::FieldTraits::clear_flag(), and FIX8::FieldTrait::present.
Referenced by FIX8::Message::clear(), and ~MessageBase().
    {
     std::for_each(_fields.begin(), _fields.end(), [](Fields::value_type& pp) { delete pp.second; pp.second = nullptr; });
     std::for_each(_groups.begin(), _groups.end(), [](Groups::value_type& pp) { delete pp.second; pp.second = nullptr; });
       if (reuse)
       {
          _fields.clear();
          //_groups.clear();
          _fp.clear_flag(FieldTrait::present);
          _pos.clear();
       }
    }
void FIX8::MessageBase::clear_positions () inline
empty the positions map
Definition at line 447 of file message.hpp.
 { _pos.clear(); }
unsigned MessageBase::copy_legal (MessageBase * to, bool force = false) const
Copy all fields from this message to 'to' where the field is legal for 'to' and it is not already present in 'to'; includes nested repeating groups.
Parameters
to target message
force if true copy all fields regardless, replacing any existing, adding any new
Returns
number of fields copied
Definition at line 256 of file message.cpp.
References _fp, FIX8::GroupBase::_msgs, add_field(), check_set_rlm(), copy_legal(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), find_group(), find_group(), FIX8::FieldTraits::get(), FIX8::FieldTraits::get_presence(), FIX8::FieldTrait::group, FIX8::FieldTraits::has(), FIX8::FieldTrait::present, and replace().
Referenced by copy_legal(), and tex_router_server::operator()().
 {
    unsigned copied{};
    for (const auto& pp : _fp.get_presence())
    {
       if (pp._field_traits & FieldTrait::present && (force || (to->_fp.has(pp._fnum) && !to->_fp.get(pp._fnum))))
       {
          GroupBase *gb;
          if (pp._field_traits & FieldTrait::group && (gb = find_group(pp._fnum)))
          {
             GroupBase *gb1(to->find_group(pp._fnum));
             for (const auto *qq : gb->_msgs)
             {
                MessageBase *grc(gb1->create_group(true));
                copied += qq->copy_legal(grc, force);
                *gb1 += grc;
             }
          }
          BaseField *nf(get_field(pp._fnum)->copy());
 #if defined FIX8_POPULATE_METADATA
          to->check_set_rlm(nf);
 #endif
          Presence::const_iterator fpitr(to->_fp.get_presence().end());
          if (force && to->_fp.get(pp._fnum, fpitr, FieldTrait::present))
             delete to->replace(pp._fnum, fpitr, nf);
          else
             to->add_field(nf);
          ++copied;
       }
    }
    return copied;
 }
virtual GroupBase* FIX8::MessageBase::create_nested_group (unsigned short fnum) const inline virtual
Instantiate a new nested group element.
Parameters
fnum field number of group to create
Returns
new message
Reimplemented in FIX8::TEX::DerivativeSecurityListRequest, FIX8::TEX::SecurityList, FIX8::TEX::SecurityListRequest, FIX8::TEX::SecurityTypes, FIX8::TEX::CrossOrderCancelRequest, FIX8::TEX::CrossOrderCancelReplaceRequest, FIX8::TEX::NewOrderCross, FIX8::TEX::OrderMassCancelReport, FIX8::TEX::OrderMassCancelRequest, FIX8::TEX::RegistrationInstructionsResponse, FIX8::TEX::RegistrationInstructions, FIX8::TEX::ListStrikePrice, FIX8::TEX::BidResponse, FIX8::TEX::BidRequest, FIX8::TEX::MassQuote, FIX8::TEX::header, FIX8::TEX::TradingSessionStatus, FIX8::TEX::SecurityStatus, FIX8::TEX::SecurityStatusRequest, FIX8::TEX::SecurityDefinition, FIX8::TEX::SecurityDefinitionRequest, FIX8::TEX::MassQuoteAcknowledgement, FIX8::TEX::QuoteStatusRequest, FIX8::TEX::QuoteCancel, FIX8::TEX::MarketDataRequestReject, FIX8::TEX::MarketDataIncrementalRefresh, FIX8::TEX::MarketDataSnapshotFullRefresh, FIX8::TEX::MarketDataRequest, FIX8::TEX::SettlementInstructions, FIX8::TEX::Quote, FIX8::TEX::QuoteRequest, FIX8::TEX::DontKnowTrade, FIX8::TEX::AllocationInstructionAck, FIX8::TEX::ListStatus, FIX8::TEX::ListCancelRequest, FIX8::TEX::AllocationInstruction, FIX8::TEX::OrderStatusRequest, FIX8::TEX::OrderCancelReplaceRequest, FIX8::TEX::OrderCancelRequest, FIX8::TEX::NewOrderList, FIX8::TEX::NewOrderSingle, FIX8::TEX::PartyDetailsListReport, FIX8::TEX::PartyDetailsListRequest, FIX8::TEX::StreamAssignmentReport, FIX8::TEX::StreamAssignmentRequest, FIX8::TEX::OrderMassActionRequest, FIX8::TEX::Email, FIX8::TEX::OrderMassActionReport, FIX8::TEX::ApplicationMessageReport, FIX8::TEX::ApplicationMessageRequestAck, FIX8::TEX::ApplicationMessageRequest, FIX8::TEX::MarketDefinitionUpdateReport, FIX8::TEX::MarketDefinition, FIX8::TEX::TradingSessionListUpdateReport, FIX8::TEX::DerivativeSecurityListUpdateReport, FIX8::TEX::SettlementObligationReport, FIX8::TEX::SecurityDefinitionUpdateReport, FIX8::TEX::ContraryIntentionReport, FIX8::TEX::ExecutionAcknowledgement, FIX8::TEX::AllocationInstructionAlert, FIX8::TEX::AdjustedPositionReport, FIX8::TEX::SecurityListUpdateReport, FIX8::TEX::TradingSessionList, FIX8::TEX::ConfirmationRequest, FIX8::TEX::CollateralInquiryAck, FIX8::TEX::NetworkCounterpartySystemStatusResponse, FIX8::TEX::NetworkCounterpartySystemStatusRequest, FIX8::TEX::CollateralInquiry, FIX8::TEX::CollateralReport, FIX8::TEX::News, FIX8::TEX::CollateralResponse, FIX8::TEX::CollateralAssignment, FIX8::TEX::CollateralRequest, FIX8::TEX::AssignmentReport, FIX8::TEX::SettlementInstructionRequest, FIX8::TEX::AllocationReportAck, FIX8::TEX::AllocationReport, FIX8::TEX::TradeCaptureReportAck, FIX8::TEX::TradeCaptureReportRequestAck, FIX8::TEX::PositionReport, FIX8::TEX::RequestForPositionsAck, FIX8::TEX::RequestForPositions, FIX8::TEX::PositionMaintenanceReport, FIX8::TEX::PositionMaintenanceRequest, FIX8::TEX::Confirmation, FIX8::TEX::QuoteResponse, FIX8::TEX::QuoteStatusReport, FIX8::TEX::RFQRequest, FIX8::TEX::QuoteRequestReject, FIX8::TEX::OrderMassStatusRequest, FIX8::TEX::TradeCaptureReport, FIX8::TEX::TradeCaptureReportRequest, FIX8::TEX::MultilegOrderCancelReplace, FIX8::TEX::NewOrderMultileg, FIX8::TEX::DerivativeSecurityList, FIX8::TEX::Logon, FIX8::TEX::ExecutionReport, FIX8::TEX::Advertisement, FIX8::TEX::Logon, and FIX8::TEX::IOI.
Definition at line 496 of file message.hpp.
Referenced by find_add_group().
 { return nullptr; }
unsigned MessageBase::decode (const f8String & from, unsigned offset, unsigned ignore = 0, bool permissive_mode = false)
Decode from string.
Parameters
from source string
offset in bytes to decode from
ignore bytes to ignore counting back from end of message
permissive_mode if true, ignore unknown fields
Returns
number of bytes consumed
Definition at line 87 of file message.cpp.
References FIX8::BaseEntry::_name, FIX8::FieldTrait::automatic, FIX8_MAX_FLD_LENGTH, FIX8::FieldTrait::group, and FIX8::FieldTrait::present.
Referenced by FIX8::Message::decode().
 {
    const unsigned fsize(static_cast<unsigned>(from.size()) - ignore), npos(0xffffffff);
    unsigned pos(static_cast<unsigned>(_pos.size())), last_valid_pos(npos);
    const char *dptr(from.data());
    char tag[FIX8_MAX_FLD_LENGTH], val[FIX8_MAX_FLD_LENGTH];
    size_t last_valid_offset(0);
    for (unsigned result; s_offset <= fsize && (result = extract_element(dptr + s_offset, fsize - s_offset, tag, val));)
    {
       const unsigned short tv(fast_atoi<unsigned short>(tag));
       Presence::const_iterator itr(_fp.get_presence().find(tv));
       if (itr == _fp.get_presence().end())
       {
          if (permissive_mode)
          {
             if (last_valid_pos == npos)
             {
                last_valid_pos = pos;
                last_valid_offset = s_offset;
             }
             _unknown.append(dptr + s_offset, result);
             s_offset += result;
             continue;
          }
          break;
       }
       s_offset += result;
       if (itr->_field_traits.has(FieldTrait::present))
       {
          if (!itr->_field_traits.has(FieldTrait::automatic))
             throw DuplicateField(tv);
       }
       else
       {
          const BaseEntry *be(_ctx.find_be(tv));
          if (!be)
             throw UnknownField(tv);
          BaseField *bf(be->_create._do(val, be->_rlm, -1));
          add_field_decoder(tv, ++pos, bf);
          itr->_field_traits.set(FieldTrait::present);
          // check if repeating group and num elements > 0
          if (itr->_field_traits.has(FieldTrait::group) && has_group_count(bf))
             s_offset = decode_group(nullptr, tv, from, s_offset, ignore);
       }
    }
    const unsigned short missing(_fp.find_missing());
    if (missing)
    {
       const BaseEntry *tbe(_ctx.find_be(missing));
       ostringstream ostr;
       ostr << tbe->_name << " (" << missing << ')';
       throw MissingMandatoryField(ostr.str());
    }
    return permissive_mode && last_valid_pos == pos ? static_cast<unsigned>(last_valid_offset) : s_offset;
 }
unsigned MessageBase::decode_group (GroupBase * grpbase, const unsigned short fnum, const f8String & from, unsigned s_offset, unsigned ignore)
Decode repeating group from string using nested group method
Parameters
grpbase pointer to groupbase of holding object
fnum repeating group fix field num (no...)
from source string
s_offset in bytes to decode from
ignore bytes to ignore counting back from end of message
Returns
number of bytes consumed
Definition at line 147 of file message.cpp.
References FIX8::BaseEntry::_name, FIX8::GroupBase::create_group(), FILE_LINE, FIX8_MAX_FLD_LENGTH, and FIX8::FieldTrait::present.
 {
    unsigned result;
    if (!(grpbase = find_add_group(fnum, grpbase)))
       throw InvalidRepeatingGroup(fnum, FILE_LINE);
    const unsigned fsize(static_cast<unsigned>(from.size()) - ignore);
    const char *dptr(from.data());
    char tag[FIX8_MAX_FLD_LENGTH], val[FIX8_MAX_FLD_LENGTH];
    for (bool ok(true); ok && s_offset < fsize; )
    {
       unique_ptr<MessageBase> grp(grpbase->create_group(false)); // shallow create
       for (unsigned pos(0); s_offset < fsize && (result = extract_element(dptr + s_offset, fsize - s_offset, tag, val));)
       {
          const unsigned tv(fast_atoi<unsigned>(tag));
          Presence::const_iterator itr(grp->_fp.get_presence().end());
          if (grp->_fp.get(tv, itr, FieldTrait::present)) // already present; next group?
             break;
          if (pos == 0 && grp->_fp.getPos(tv, itr) != 1)  // first field in group is mandatory
             throw MissingRepeatingGroupField(tv);
          const BaseEntry *be(_ctx.find_be(tv));
          if (!be || !grp->_fp.has(tv, itr))  // unknown field or field not found in sub-group - end of repeats?
          {
             ok = false;
             break;
          }
          s_offset += result;
          BaseField *bf(be->_create._do(val, be->_rlm, -1));
          grp->add_field(tv, itr, ++pos, bf, false);
          grp->_fp.set(tv, itr, FieldTrait::present);  // is present
          // nested group (check if not zero elements)
          if (grp->_fp.is_group(tv, itr) && has_group_count(bf))
             s_offset = grp->decode_group(grpbase, tv, from, s_offset, ignore);
       }
       const unsigned short missing(grp->_fp.find_missing());
       if (missing)
       {
          const BaseEntry *tbe(_ctx.find_be(missing));
          ostringstream ostr;
          ostr << tbe->_name << " (" << missing << ')';
          throw MissingMandatoryField(ostr.str());
       }
       *grpbase << grp.release();
    }
    return s_offset;
 }
size_t MessageBase::encode (std::ostream & to) const
Encode message to stream.
Parameters
to stream to encode to
Returns
number of bytes encoded
Definition at line 354 of file message.cpp.
References FIX8::FieldTrait::group, and FIX8::FieldTrait::suppress.
Referenced by FIX8::Message::encode().
 {
    const std::ios::pos_type where(to.tellp());
    for (const auto& pp : _pos)
    {
 #if defined FIX8_POPULATE_METADATA
       check_set_rlm(pp.second);
 #endif
       Presence::const_iterator fpitr(_fp.get_presence().end());
       if (!_fp.get(pp.second->_fnum, fpitr, FieldTrait::suppress))   // some fields are not encoded until unsuppressed (eg. checksum)
       {
          pp.second->encode(to);
          if (fpitr->_field_traits.has(FieldTrait::group) && has_group_count(pp.second))
             encode_group(pp.second->_fnum, to);
       }
    }
    if (_unknown.size())
       to << _unknown;
    return to.tellp() - where;
 }
size_t MessageBase::encode (char * to) const
Encode message to buffer.
Parameters
to buffer to encode to
Returns
number of bytes encoded
Definition at line 330 of file message.cpp.
References FIX8::FieldTrait::group, and FIX8::FieldTrait::suppress.
 {
    const char *where(to);
    for (const auto& pp : _pos)
    {
 #if defined FIX8_POPULATE_METADATA
       check_set_rlm(pp.second);
 #endif
       Presence::const_iterator fpitr(_fp.get_presence().end());
       if (!_fp.get(pp.second->_fnum, fpitr, FieldTrait::suppress))   // some fields are not encoded until unsuppressed (eg. checksum)
       {
          to += pp.second->encode(to);
          if (fpitr->_field_traits.has(FieldTrait::group) && has_group_count(pp.second))
             to += encode_group(pp.second->_fnum, to);
       }
    }
    if (_unknown.size())
       to += _unknown.copy(to, _unknown.size());
    return to - where;
 }
size_t MessageBase::encode_group (const unsigned short fnum, std::ostream & to) const
Encode group message to stream.
Parameters
fnum repeating group fix field num (no...)
to stream to encode to
Returns
number of bytes encoded
Definition at line 390 of file message.cpp.
References FILE_LINE, and find_group().
 {
    const std::ios::pos_type where(to.tellp());
    GroupBase *grpbase(find_group(fnum));
    if (!grpbase)
       throw InvalidRepeatingGroup(fnum, FILE_LINE);
    for (const auto *pp : grpbase->_msgs)
       pp->encode(to);
    return to.tellp() - where;
 }
size_t MessageBase::encode_group (const unsigned short fnum, char * to) const
Encode group message to buffer.
Parameters
fnum repeating group fix field num (no...)
to buffer to encode to
Returns
number of bytes encoded
Definition at line 378 of file message.cpp.
References FIX8::GroupBase::_msgs, FILE_LINE, and find_group().
 {
    const char *where(to);
    GroupBase *grpbase(find_group(fnum));
    if (!grpbase)
       throw InvalidRepeatingGroup(fnum, FILE_LINE);
    for (const auto *pp : grpbase->_msgs)
       to += pp->encode(to);
    return to - where;
 }
static unsigned FIX8::MessageBase::extract_element (const char * from, const unsigned sz, char * tag, char * val) inline static
Extract a tag/value element from a char buffer. ULL version.
Parameters
from source buffer
sz size of string
tag tag to extract to
val value to extract to
Returns
number of bytes consumed
Definition at line 886 of file message.hpp.
References FIX8::default_assignment_separator(), FIX8::default_field_separator(), and FIX8::get_value().
Referenced by FIX8::FIXReader::read().
    {
       enum { get_tag, get_value } state(get_tag);
       for (unsigned ii(0); ii < sz; ++ii)
       {
          switch (state)
          {
          case get_tag:
             if (!isdigit(from[ii]))
             {
                if (from[ii] != default_assignment_separator)
                   return *val = *tag = 0;
                state = get_value;
             }
             else
                *tag++ = from[ii];
             break;
          case get_value:
             if (from[ii] == default_field_separator)
             {
                *val = *tag = 0;
                return ++ii;
             }
             *val++ = from[ii];
             break;
          }
       }
       return *val = *tag = 0;
    }
static unsigned FIX8::MessageBase::extract_element (const char * from, const unsigned sz, f8String & tag, f8String & val) inline static
Extract a tag/value element from a char buffer.
Parameters
from source buffer
sz size of string
tag tag to extract to
val value to extract to
Returns
number of bytes consumed
Definition at line 923 of file message.hpp.
References FIX8::default_assignment_separator(), FIX8::default_field_separator(), and FIX8::get_value().
    {
       enum { get_tag, get_value } state(get_tag);
       tag.clear();
       val.clear();
       for (unsigned ii(0); ii < sz; ++ii)
       {
          switch (state)
          {
          case get_tag:
             if (!isdigit(from[ii]))
             {
                if (from[ii] != default_assignment_separator)
                   return 0;
                state = get_value;
             }
             else
                tag += from[ii];
             break;
          case get_value:
             if (from[ii] == default_field_separator)
                return ++ii;
             val += from[ii];
             break;
          }
       }
       return 0;
    }
unsigned MessageBase::extract_header (const f8String & from, char * len, char * mtype) static protected
Extract length and message type from a header buffer
Parameters
from source buffer
len length to extract to
mtype message type to extract to
Returns
number of bytes consumed
Definition at line 51 of file message.cpp.
References FIX8_MAX_FLD_LENGTH, and FIX8::MAX_MSGTYPE_FIELD_LEN().
 {
    const char *dptr(from.data());
    const unsigned flen(static_cast<unsigned>(from.size()));
    char tag[MAX_MSGTYPE_FIELD_LEN], val[FIX8_MAX_FLD_LENGTH];
    unsigned s_offset(0), result;
    if ((result = extract_element(dptr, flen, tag, val)))
    {
       if (*tag != '8')
          return 0;
       s_offset += result;
       if ((result = extract_element(dptr + s_offset, flen - s_offset, tag, len)))
       {
          if (*tag != '9')
             return 0;
          s_offset += result;
          if ((result = extract_element(dptr + s_offset, flen - s_offset, tag, mtype)))
          {
             if (*tag != '3' || *(tag + 1) != '5')
                return 0;
             s_offset += result;
          }
       }
    }
    return s_offset;
 }
unsigned MessageBase::extract_trailer (const f8String & from, f8String & chksum) static protected
Extract chksum from a trailer buffer
Parameters
from source buffer
chksum chksum to extract to
Returns
number of bytes consumed
Definition at line 80 of file message.cpp.
 {
    f8String tag;
    return extract_element(from.data() + from.size() - 7, 6, tag, chksum);
 }
Fields::const_iterator FIX8::MessageBase::fields_begin () const inline
Get an iterator to fields present in this message.
Returns
iterator to the first field or Fields::const_iterator::end
Definition at line 752 of file message.hpp.
 { return _fields.begin(); }
Fields::const_iterator FIX8::MessageBase::fields_end () const inline
Get an iterator to fields present in this message.
Returns
iterator to the last field + 1
Definition at line 756 of file message.hpp.
 { return _fields.end(); }
template<typename T > GroupBase* FIX8::MessageBase::find_add_group (GroupBase * grpbase = nullptr) inline
Find a group of a specified type. If not found attempt to add.
Template Parameters
T type of group to get
Parameters
grpbase parent group (if group nested) or nullptr if no parent
Returns
pointer to found group or 0 if not found
Definition at line 808 of file message.hpp.
References find_add_group().
Referenced by find_add_group(), and MyMenu::generate_new_order_single_alternate().
 { return find_add_group(T::_fnum, grpbase); }
GroupBase* FIX8::MessageBase::find_add_group (const unsigned short fnum, GroupBase * grpbase = nullptr) inline
Find a group of a specified type. If not found attempt to add.
Parameters
fnum field number
grpbase parent group (if group nested) or nullptr if no parent
Returns
pointer to found group or 0 if not found
Definition at line 814 of file message.hpp.
References add_group(), and create_nested_group().
    {
       auto gitr(_groups.find(fnum));
       if (gitr != _groups.end())
          return gitr->second;
       GroupBase *gb1(grpbase ? grpbase->create_nested_group(fnum) : create_nested_group(fnum));
       add_group(gb1);
       return gb1;
    }
Fields::const_iterator FIX8::MessageBase::find_field (const unsigned short fnum) const inline
Check if a field is present in this message.
Parameters
fnum field number
Returns
iterator to field or Fields::const_iterator::end
Definition at line 730 of file message.hpp.
 { return _fields.find(fnum); }
template<typename T > GroupBase* FIX8::MessageBase::find_group () const inline
Find a group of a specified type.
Template Parameters
T type of group to get
Returns
pointer to found group or 0 if not found
Definition at line 792 of file message.hpp.
References find_group().
Referenced by copy_legal(), FIX8::ConsoleMenu::EditMsg(), find_group(), MyMenu::generate_new_order_single(), and move_legal().
 { return find_group(T::_fnum); }
GroupBase* FIX8::MessageBase::find_group (const unsigned short fnum) const inline
Find a group of a specified type.
Parameters
fnum field number
Returns
pointer to found group or 0 if not found
Definition at line 797 of file message.hpp.
    {
       auto gitr(_groups.find(fnum));
       return gitr != _groups.cend() ? gitr->second : nullptr;
    }
template<typename T > bool FIX8::MessageBase::get (T & to) const inline
Populate supplied field with value from message.
Template Parameters
T type of field to get
Parameters
to field to populate
Returns
true on success
Definition at line 671 of file message.hpp.
Referenced by FIX8::Session::compid_check(), FIX8::Session::handle_logon(), FIX8::Session::handle_resend_request(), FIX8::Session::handle_sequence_reset(), FIX8::Session::handle_test_request(), MyMenu::load_msgs(), tex_router_server::operator()(), FIX8::Session::send_process(), and FIX8::Session::sequence_check().
    {
       Fields::const_iterator fitr(_fields.find(T::get_field_id()));
       if (fitr == _fields.end())
          return false;
       to.set(fitr->second->from<T>().get());
       if (fitr->second->_rlm)
          to._rlm = fitr->second->_rlm;
       return true;
    }
template<typename T > const T* FIX8::MessageBase::get () const inline
Get a pointer to a field. Inplace, 0 copy.
Template Parameters
T type of field to get
Returns
pointer to field or 0 if not present
Definition at line 703 of file message.hpp.
    {
       Fields::const_iterator fitr(_fields.find(T::get_field_id()));
       return fitr == _fields.cend() ? nullptr : &fitr->second->from<T>();
    }
virtual begin_string* FIX8::MessageBase::get_begin_string () inline virtual
Get pointer to begin_string Field; used by header/trailer.
Returns
Field
Reimplemented in FIX8::TEX::header, and FIX8::TEX::header.
Definition at line 979 of file message.hpp.
 { return nullptr; }
virtual body_length* FIX8::MessageBase::get_body_length () inline virtual
Get pointer to body_length Field; used by header/trailer.
Returns
Field
Reimplemented in FIX8::TEX::header, and FIX8::TEX::header.
Definition at line 983 of file message.hpp.
 { return nullptr; }
virtual check_sum* FIX8::MessageBase::get_check_sum () inline virtual
Get pointer to check_sum Field; used by header/trailer.
Returns
Field
Reimplemented in FIX8::TEX::trailer, and FIX8::TEX::trailer.
Definition at line 991 of file message.hpp.
 { return nullptr; }
BaseField* FIX8::MessageBase::get_field (const unsigned short fnum) const inline
Search for field in this message.
Parameters
fnum field number
Returns
pointer to field or 0 if not found
Definition at line 735 of file message.hpp.
    {
       auto itr(_fields.find(fnum));
       return itr != _fields.cend() ? itr->second : nullptr;
    }
BaseField* FIX8::MessageBase::get_field_by_name (const char * tag) const inline
Search for field by longname in this message.
Parameters
tag field longname
Returns
pointer to field or 0 if not found
Definition at line 744 of file message.hpp.
References FIX8::F8MetaCntx::reverse_find_fnum().
    {
       auto itr(_fields.find(_ctx.reverse_find_fnum(tag)));
       return itr != _fields.cend() ? itr->second : nullptr;
    }
const FieldTraits& FIX8::MessageBase::get_fp () const inline
Get the FieldTraits
Returns
reference to FieldTraits object
Definition at line 878 of file message.hpp.
References _fp.
Referenced by FIX8::ConsoleMenu::EditMsg(), and FIX8::ConsoleMenu::SelectField().
 { return _fp; }
Groups& FIX8::MessageBase::get_groups () inline
Definition at line 650 of file message.hpp.
References _groups.
Referenced by FIX8::TEX::IOI::NoPartyIDs::create_group(), FIX8::TEX::IOI::NoLegs::create_group(), FIX8::TEX::IOI::NoUnderlyings::create_group(), FIX8::TEX::IOI::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::IOI::NoInstrumentParties::create_group(), FIX8::TEX::IOI::NoComplexEvents::create_group(), FIX8::TEX::IOI::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::Advertisement::NoLegs::create_group(), FIX8::TEX::Advertisement::NoUnderlyings::create_group(), FIX8::TEX::Advertisement::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::Advertisement::NoInstrumentParties::create_group(), FIX8::TEX::Advertisement::NoComplexEvents::create_group(), FIX8::TEX::Advertisement::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::ExecutionReport::NoAllocs::create_group(), FIX8::TEX::ExecutionReport::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::ExecutionReport::NoPartyIDs::create_group(), FIX8::TEX::ExecutionReport::NoLegs::create_group(), FIX8::TEX::ExecutionReport::NoLegs::NoLegAllocs::create_group(), FIX8::TEX::ExecutionReport::NoLegs::NoLegAllocs::NoNested2PartyIDs::create_group(), FIX8::TEX::ExecutionReport::NoLegs::NoNested3PartyIDs::create_group(), FIX8::TEX::ExecutionReport::NoUnderlyings::create_group(), FIX8::TEX::ExecutionReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::ExecutionReport::NoInstrumentParties::create_group(), FIX8::TEX::ExecutionReport::NoFills::create_group(), FIX8::TEX::ExecutionReport::NoFills::NoNested4PartyIDs::create_group(), FIX8::TEX::ExecutionReport::NoComplexEvents::create_group(), FIX8::TEX::ExecutionReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::DerivativeSecurityList::NoRelatedSym::create_group(), FIX8::TEX::DerivativeSecurityList::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::DerivativeSecurityList::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityList::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::DerivativeSecurityList::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::DerivativeSecurityList::NoUndlyInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityList::NoDerivativeInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityList::NoMarketSegments::create_group(), FIX8::TEX::DerivativeSecurityList::NoMarketSegments::NoStrikeRules::create_group(), FIX8::TEX::DerivativeSecurityList::NoMarketSegments::NoTradingSessionRules::create_group(), FIX8::TEX::NewOrderMultileg::NoAllocs::create_group(), FIX8::TEX::NewOrderMultileg::NoAllocs::NoNested3PartyIDs::create_group(), FIX8::TEX::NewOrderMultileg::NoPartyIDs::create_group(), FIX8::TEX::NewOrderMultileg::NoLegs::create_group(), FIX8::TEX::NewOrderMultileg::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::NewOrderMultileg::NoLegs::NoLegAllocs::create_group(), FIX8::TEX::NewOrderMultileg::NoLegs::NoLegAllocs::NoNested2PartyIDs::create_group(), FIX8::TEX::NewOrderMultileg::NoUnderlyings::create_group(), FIX8::TEX::NewOrderMultileg::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::NewOrderMultileg::NoInstrumentParties::create_group(), FIX8::TEX::NewOrderMultileg::NoComplexEvents::create_group(), FIX8::TEX::NewOrderMultileg::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoAllocs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoAllocs::NoNested3PartyIDs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoPartyIDs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoLegs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoLegs::NoLegAllocs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoLegs::NoLegAllocs::NoNested2PartyIDs::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoUnderlyings::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoInstrumentParties::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoComplexEvents::create_group(), FIX8::TEX::MultilegOrderCancelReplace::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoPartyIDs::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoLegs::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoUnderlyings::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoComplexEvents::create_group(), FIX8::TEX::TradeCaptureReportRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::NoAllocs::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::NoAllocs::NoNested2PartyIDs::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::NoPartyIDs::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::NoSettlDetails::create_group(), FIX8::TEX::TradeCaptureReport::NoSides::NoSettlDetails::NoSettlPartyIDs::create_group(), FIX8::TEX::TradeCaptureReport::NoLegs::create_group(), FIX8::TEX::TradeCaptureReport::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::TradeCaptureReport::NoLegs::NoOfLegUnderlyings::create_group(), FIX8::TEX::TradeCaptureReport::NoUnderlyings::create_group(), FIX8::TEX::TradeCaptureReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReport::NoInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReport::NoRootPartyIDs::create_group(), FIX8::TEX::TradeCaptureReport::NoComplexEvents::create_group(), FIX8::TEX::TradeCaptureReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::OrderMassStatusRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderMassStatusRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderMassStatusRequest::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassStatusRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderMassStatusRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoPartyIDs::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::QuoteRequestReject::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteRequestReject::NoRootPartyIDs::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::RFQRequest::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::RFQRequest::NoPartyIDs::create_group(), FIX8::TEX::QuoteStatusReport::NoPartyIDs::create_group(), FIX8::TEX::QuoteStatusReport::NoLegs::create_group(), FIX8::TEX::QuoteStatusReport::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::QuoteStatusReport::NoUnderlyings::create_group(), FIX8::TEX::QuoteStatusReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteStatusReport::NoInstrumentParties::create_group(), FIX8::TEX::QuoteStatusReport::NoComplexEvents::create_group(), FIX8::TEX::QuoteStatusReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteResponse::NoPartyIDs::create_group(), FIX8::TEX::QuoteResponse::NoLegs::create_group(), FIX8::TEX::QuoteResponse::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::QuoteResponse::NoUnderlyings::create_group(), FIX8::TEX::QuoteResponse::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteResponse::NoInstrumentParties::create_group(), FIX8::TEX::QuoteResponse::NoComplexEvents::create_group(), FIX8::TEX::QuoteResponse::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::Confirmation::NoOrders::create_group(), FIX8::TEX::Confirmation::NoOrders::NoNested2PartyIDs::create_group(), FIX8::TEX::Confirmation::NoDlvyInst::create_group(), FIX8::TEX::Confirmation::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::Confirmation::NoPartyIDs::create_group(), FIX8::TEX::Confirmation::NoLegs::create_group(), FIX8::TEX::Confirmation::NoUnderlyings::create_group(), FIX8::TEX::Confirmation::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::Confirmation::NoInstrumentParties::create_group(), FIX8::TEX::Confirmation::NoComplexEvents::create_group(), FIX8::TEX::Confirmation::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoPartyIDs::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoLegs::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoPositions::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoPositions::NoNestedPartyIDs::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoUnderlyings::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoInstrumentParties::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoComplexEvents::create_group(), FIX8::TEX::PositionMaintenanceRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::PositionMaintenanceReport::NoPartyIDs::create_group(), FIX8::TEX::PositionMaintenanceReport::NoLegs::create_group(), FIX8::TEX::PositionMaintenanceReport::NoPositions::create_group(), FIX8::TEX::PositionMaintenanceReport::NoPositions::NoNestedPartyIDs::create_group(), FIX8::TEX::PositionMaintenanceReport::NoUnderlyings::create_group(), FIX8::TEX::PositionMaintenanceReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::PositionMaintenanceReport::NoInstrumentParties::create_group(), FIX8::TEX::PositionMaintenanceReport::NoComplexEvents::create_group(), FIX8::TEX::PositionMaintenanceReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::RequestForPositions::NoPartyIDs::create_group(), FIX8::TEX::RequestForPositions::NoLegs::create_group(), FIX8::TEX::RequestForPositions::NoUnderlyings::create_group(), FIX8::TEX::RequestForPositions::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::RequestForPositions::NoInstrumentParties::create_group(), FIX8::TEX::RequestForPositions::NoComplexEvents::create_group(), FIX8::TEX::RequestForPositions::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::RequestForPositionsAck::NoPartyIDs::create_group(), FIX8::TEX::RequestForPositionsAck::NoLegs::create_group(), FIX8::TEX::RequestForPositionsAck::NoUnderlyings::create_group(), FIX8::TEX::RequestForPositionsAck::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::RequestForPositionsAck::NoInstrumentParties::create_group(), FIX8::TEX::RequestForPositionsAck::NoComplexEvents::create_group(), FIX8::TEX::RequestForPositionsAck::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::PositionReport::NoPartyIDs::create_group(), FIX8::TEX::PositionReport::NoLegs::create_group(), FIX8::TEX::PositionReport::NoPositions::create_group(), FIX8::TEX::PositionReport::NoPositions::NoNestedPartyIDs::create_group(), FIX8::TEX::PositionReport::NoUnderlyings::create_group(), FIX8::TEX::PositionReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::PositionReport::NoInstrumentParties::create_group(), FIX8::TEX::PositionReport::NoComplexEvents::create_group(), FIX8::TEX::PositionReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoLegs::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoUnderlyings::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoComplexEvents::create_group(), FIX8::TEX::TradeCaptureReportRequestAck::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::NoAllocs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::NoAllocs::NoNested2PartyIDs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::NoPartyIDs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::NoSettlDetails::create_group(), FIX8::TEX::TradeCaptureReportAck::NoSides::NoSettlDetails::NoSettlPartyIDs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoLegs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoLegs::NoOfLegUnderlyings::create_group(), FIX8::TEX::TradeCaptureReportAck::NoUnderlyings::create_group(), FIX8::TEX::TradeCaptureReportAck::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportAck::NoInstrumentParties::create_group(), FIX8::TEX::TradeCaptureReportAck::NoRootPartyIDs::create_group(), FIX8::TEX::TradeCaptureReportAck::NoComplexEvents::create_group(), FIX8::TEX::TradeCaptureReportAck::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::AllocationReport::NoOrders::create_group(), FIX8::TEX::AllocationReport::NoOrders::NoNested2PartyIDs::create_group(), FIX8::TEX::AllocationReport::NoAllocs::create_group(), FIX8::TEX::AllocationReport::NoAllocs::NoDlvyInst::create_group(), FIX8::TEX::AllocationReport::NoAllocs::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::AllocationReport::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationReport::NoPartyIDs::create_group(), FIX8::TEX::AllocationReport::NoLegs::create_group(), FIX8::TEX::AllocationReport::NoUnderlyings::create_group(), FIX8::TEX::AllocationReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::AllocationReport::NoInstrumentParties::create_group(), FIX8::TEX::AllocationReport::NoComplexEvents::create_group(), FIX8::TEX::AllocationReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::AllocationReportAck::NoAllocs::create_group(), FIX8::TEX::AllocationReportAck::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationReportAck::NoPartyIDs::create_group(), FIX8::TEX::SettlementInstructionRequest::NoPartyIDs::create_group(), FIX8::TEX::AssignmentReport::NoPartyIDs::create_group(), FIX8::TEX::AssignmentReport::NoLegs::create_group(), FIX8::TEX::AssignmentReport::NoPositions::create_group(), FIX8::TEX::AssignmentReport::NoPositions::NoNestedPartyIDs::create_group(), FIX8::TEX::AssignmentReport::NoUnderlyings::create_group(), FIX8::TEX::AssignmentReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::AssignmentReport::NoInstrumentParties::create_group(), FIX8::TEX::AssignmentReport::NoComplexEvents::create_group(), FIX8::TEX::AssignmentReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CollateralRequest::NoPartyIDs::create_group(), FIX8::TEX::CollateralRequest::NoLegs::create_group(), FIX8::TEX::CollateralRequest::NoUnderlyings::create_group(), FIX8::TEX::CollateralRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralRequest::NoInstrumentParties::create_group(), FIX8::TEX::CollateralRequest::NoComplexEvents::create_group(), FIX8::TEX::CollateralRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CollateralAssignment::NoDlvyInst::create_group(), FIX8::TEX::CollateralAssignment::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::CollateralAssignment::NoPartyIDs::create_group(), FIX8::TEX::CollateralAssignment::NoLegs::create_group(), FIX8::TEX::CollateralAssignment::NoUnderlyings::create_group(), FIX8::TEX::CollateralAssignment::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralAssignment::NoInstrumentParties::create_group(), FIX8::TEX::CollateralAssignment::NoComplexEvents::create_group(), FIX8::TEX::CollateralAssignment::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CollateralResponse::NoPartyIDs::create_group(), FIX8::TEX::CollateralResponse::NoLegs::create_group(), FIX8::TEX::CollateralResponse::NoUnderlyings::create_group(), FIX8::TEX::CollateralResponse::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralResponse::NoInstrumentParties::create_group(), FIX8::TEX::CollateralResponse::NoComplexEvents::create_group(), FIX8::TEX::CollateralResponse::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::News::NoRelatedSym::create_group(), FIX8::TEX::News::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::News::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::News::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::News::NoLegs::create_group(), FIX8::TEX::News::NoUnderlyings::create_group(), FIX8::TEX::News::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralReport::NoDlvyInst::create_group(), FIX8::TEX::CollateralReport::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::CollateralReport::NoPartyIDs::create_group(), FIX8::TEX::CollateralReport::NoLegs::create_group(), FIX8::TEX::CollateralReport::NoUnderlyings::create_group(), FIX8::TEX::CollateralReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralReport::NoInstrumentParties::create_group(), FIX8::TEX::CollateralReport::NoComplexEvents::create_group(), FIX8::TEX::CollateralReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CollateralInquiry::NoDlvyInst::create_group(), FIX8::TEX::CollateralInquiry::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::CollateralInquiry::NoPartyIDs::create_group(), FIX8::TEX::CollateralInquiry::NoLegs::create_group(), FIX8::TEX::CollateralInquiry::NoUnderlyings::create_group(), FIX8::TEX::CollateralInquiry::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralInquiry::NoInstrumentParties::create_group(), FIX8::TEX::CollateralInquiry::NoComplexEvents::create_group(), FIX8::TEX::CollateralInquiry::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CollateralInquiryAck::NoPartyIDs::create_group(), FIX8::TEX::CollateralInquiryAck::NoLegs::create_group(), FIX8::TEX::CollateralInquiryAck::NoUnderlyings::create_group(), FIX8::TEX::CollateralInquiryAck::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CollateralInquiryAck::NoInstrumentParties::create_group(), FIX8::TEX::CollateralInquiryAck::NoComplexEvents::create_group(), FIX8::TEX::CollateralInquiryAck::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::ConfirmationRequest::NoOrders::create_group(), FIX8::TEX::ConfirmationRequest::NoOrders::NoNested2PartyIDs::create_group(), FIX8::TEX::TradingSessionList::NoTradingSessions::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoStrikeRules::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoTradingSessionRules::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::SecurityListUpdateReport::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::AdjustedPositionReport::NoRelatedSym::create_group(), FIX8::TEX::AdjustedPositionReport::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::AdjustedPositionReport::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::AdjustedPositionReport::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::AdjustedPositionReport::NoPartyIDs::create_group(), FIX8::TEX::AdjustedPositionReport::NoPositions::create_group(), FIX8::TEX::AdjustedPositionReport::NoPositions::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoOrders::create_group(), FIX8::TEX::AllocationInstructionAlert::NoOrders::NoNested2PartyIDs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoAllocs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoAllocs::NoDlvyInst::create_group(), FIX8::TEX::AllocationInstructionAlert::NoAllocs::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoLegs::create_group(), FIX8::TEX::AllocationInstructionAlert::NoUnderlyings::create_group(), FIX8::TEX::AllocationInstructionAlert::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::AllocationInstructionAlert::NoInstrumentParties::create_group(), FIX8::TEX::AllocationInstructionAlert::NoComplexEvents::create_group(), FIX8::TEX::AllocationInstructionAlert::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoLegs::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoUnderlyings::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoInstrumentParties::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoComplexEvents::create_group(), FIX8::TEX::ExecutionAcknowledgement::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::ContraryIntentionReport::NoPartyIDs::create_group(), FIX8::TEX::ContraryIntentionReport::NoUnderlyings::create_group(), FIX8::TEX::ContraryIntentionReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::ContraryIntentionReport::NoInstrumentParties::create_group(), FIX8::TEX::ContraryIntentionReport::NoComplexEvents::create_group(), FIX8::TEX::ContraryIntentionReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoLegs::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoUnderlyings::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoInstrumentParties::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoMarketSegments::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoMarketSegments::NoStrikeRules::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoMarketSegments::NoTradingSessionRules::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoComplexEvents::create_group(), FIX8::TEX::SecurityDefinitionUpdateReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoPartyIDs::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoInstrumentParties::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoSettlDetails::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoSettlDetails::NoSettlPartyIDs::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoComplexEvents::create_group(), FIX8::TEX::SettlementObligationReport::NoSettlOblig::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoRelatedSym::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoUndlyInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoDerivativeInstrumentParties::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoMarketSegments::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoMarketSegments::NoStrikeRules::create_group(), FIX8::TEX::DerivativeSecurityListUpdateReport::NoMarketSegments::NoTradingSessionRules::create_group(), FIX8::TEX::TradingSessionListUpdateReport::NoTradingSessions::create_group(), FIX8::TEX::ApplicationMessageRequest::NoPartyIDs::create_group(), FIX8::TEX::ApplicationMessageRequest::NoApplIDs::create_group(), FIX8::TEX::ApplicationMessageRequest::NoApplIDs::NoNestedPartyIDs::create_group(), FIX8::TEX::ApplicationMessageRequestAck::NoPartyIDs::create_group(), FIX8::TEX::ApplicationMessageRequestAck::NoApplIDs::create_group(), FIX8::TEX::ApplicationMessageRequestAck::NoApplIDs::NoNestedPartyIDs::create_group(), FIX8::TEX::OrderMassActionReport::NoPartyIDs::create_group(), FIX8::TEX::OrderMassActionReport::NoInstrumentParties::create_group(), FIX8::TEX::OrderMassActionReport::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassActionReport::NoComplexEvents::create_group(), FIX8::TEX::OrderMassActionReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::Email::NoRelatedSym::create_group(), FIX8::TEX::Email::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::Email::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::Email::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::Email::NoLegs::create_group(), FIX8::TEX::Email::NoUnderlyings::create_group(), FIX8::TEX::Email::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassActionRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderMassActionRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderMassActionRequest::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassActionRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderMassActionRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::NoRelatedSym::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::StreamAssignmentRequest::NoAsgnReqs::NoPartyIDs::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::NoRelatedSym::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::StreamAssignmentReport::NoAsgnReqs::NoPartyIDs::create_group(), FIX8::TEX::PartyDetailsListRequest::NoPartyIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoPartyAltIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoContextPartyIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRiskLimits::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRiskLimits::NoRiskInstruments::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRelatedPartyIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRelatedPartyIDs::NoRelatedPartyAltIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRelatedPartyIDs::NoRelatedContextPartyIDs::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRelatedPartyIDs::NoRelationshipRiskLimits::create_group(), FIX8::TEX::PartyDetailsListReport::NoPartyList::NoRelatedPartyIDs::NoRelationshipRiskLimits::NoRelationshipRiskInstruments::create_group(), FIX8::TEX::NewOrderSingle::NoAllocs::create_group(), FIX8::TEX::NewOrderSingle::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::NewOrderSingle::NoPartyIDs::create_group(), FIX8::TEX::NewOrderSingle::NoUnderlyings::create_group(), FIX8::TEX::NewOrderSingle::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::NewOrderSingle::NoInstrumentParties::create_group(), FIX8::TEX::NewOrderSingle::NoComplexEvents::create_group(), FIX8::TEX::NewOrderSingle::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::NewOrderList::NoOrders::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoAllocs::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoPartyIDs::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoUnderlyings::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoInstrumentParties::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoComplexEvents::create_group(), FIX8::TEX::NewOrderList::NoOrders::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::NewOrderList::NoRootPartyIDs::create_group(), FIX8::TEX::OrderCancelRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderCancelRequest::NoUnderlyings::create_group(), FIX8::TEX::OrderCancelRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderCancelRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderCancelRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderCancelRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoAllocs::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoUnderlyings::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderCancelReplaceRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::OrderStatusRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderStatusRequest::NoUnderlyings::create_group(), FIX8::TEX::OrderStatusRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderStatusRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderStatusRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderStatusRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::AllocationInstruction::NoOrders::create_group(), FIX8::TEX::AllocationInstruction::NoOrders::NoNested2PartyIDs::create_group(), FIX8::TEX::AllocationInstruction::NoAllocs::create_group(), FIX8::TEX::AllocationInstruction::NoAllocs::NoDlvyInst::create_group(), FIX8::TEX::AllocationInstruction::NoAllocs::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::AllocationInstruction::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationInstruction::NoPartyIDs::create_group(), FIX8::TEX::AllocationInstruction::NoLegs::create_group(), FIX8::TEX::AllocationInstruction::NoUnderlyings::create_group(), FIX8::TEX::AllocationInstruction::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::AllocationInstruction::NoInstrumentParties::create_group(), FIX8::TEX::AllocationInstruction::NoComplexEvents::create_group(), FIX8::TEX::AllocationInstruction::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::ListCancelRequest::NoPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAck::NoAllocs::create_group(), FIX8::TEX::AllocationInstructionAck::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::AllocationInstructionAck::NoPartyIDs::create_group(), FIX8::TEX::DontKnowTrade::NoLegs::create_group(), FIX8::TEX::DontKnowTrade::NoUnderlyings::create_group(), FIX8::TEX::DontKnowTrade::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::DontKnowTrade::NoInstrumentParties::create_group(), FIX8::TEX::DontKnowTrade::NoComplexEvents::create_group(), FIX8::TEX::DontKnowTrade::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoPartyIDs::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::QuoteRequest::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteRequest::NoRootPartyIDs::create_group(), FIX8::TEX::Quote::NoPartyIDs::create_group(), FIX8::TEX::Quote::NoLegs::create_group(), FIX8::TEX::Quote::NoLegs::NoNestedPartyIDs::create_group(), FIX8::TEX::Quote::NoUnderlyings::create_group(), FIX8::TEX::Quote::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::Quote::NoInstrumentParties::create_group(), FIX8::TEX::Quote::NoComplexEvents::create_group(), FIX8::TEX::Quote::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SettlementInstructions::NoSettlInst::create_group(), FIX8::TEX::SettlementInstructions::NoSettlInst::NoDlvyInst::create_group(), FIX8::TEX::SettlementInstructions::NoSettlInst::NoDlvyInst::NoSettlPartyIDs::create_group(), FIX8::TEX::SettlementInstructions::NoSettlInst::NoPartyIDs::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::MarketDataRequest::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MarketDataRequest::NoPartyIDs::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoMDEntries::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoMDEntries::NoPartyIDs::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoLegs::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoUnderlyings::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoInstrumentParties::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoComplexEvents::create_group(), FIX8::TEX::MarketDataSnapshotFullRefresh::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoPartyIDs::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoLegs::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoUnderlyings::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoInstrumentParties::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoComplexEvents::create_group(), FIX8::TEX::MarketDataIncrementalRefresh::NoMDEntries::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MarketDataRequestReject::NoPartyIDs::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoLegs::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoUnderlyings::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoInstrumentParties::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoComplexEvents::create_group(), FIX8::TEX::QuoteCancel::NoQuoteEntries::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::QuoteCancel::NoPartyIDs::create_group(), FIX8::TEX::QuoteStatusRequest::NoPartyIDs::create_group(), FIX8::TEX::QuoteStatusRequest::NoLegs::create_group(), FIX8::TEX::QuoteStatusRequest::NoUnderlyings::create_group(), FIX8::TEX::QuoteStatusRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::QuoteStatusRequest::NoInstrumentParties::create_group(), FIX8::TEX::QuoteStatusRequest::NoComplexEvents::create_group(), FIX8::TEX::QuoteStatusRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::NoLegs::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::NoInstrumentParties::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::NoComplexEvents::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoQuoteSets::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MassQuoteAcknowledgement::NoPartyIDs::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoLegs::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoUnderlyings::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoInstrumentParties::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoComplexEvents::create_group(), FIX8::TEX::SecurityDefinitionRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityDefinition::NoLegs::create_group(), FIX8::TEX::SecurityDefinition::NoUnderlyings::create_group(), FIX8::TEX::SecurityDefinition::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityDefinition::NoInstrumentParties::create_group(), FIX8::TEX::SecurityDefinition::NoMarketSegments::create_group(), FIX8::TEX::SecurityDefinition::NoMarketSegments::NoStrikeRules::create_group(), FIX8::TEX::SecurityDefinition::NoMarketSegments::NoTradingSessionRules::create_group(), FIX8::TEX::SecurityDefinition::NoComplexEvents::create_group(), FIX8::TEX::SecurityDefinition::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityStatusRequest::NoLegs::create_group(), FIX8::TEX::SecurityStatusRequest::NoUnderlyings::create_group(), FIX8::TEX::SecurityStatusRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityStatusRequest::NoInstrumentParties::create_group(), FIX8::TEX::SecurityStatusRequest::NoComplexEvents::create_group(), FIX8::TEX::SecurityStatusRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityStatus::NoLegs::create_group(), FIX8::TEX::SecurityStatus::NoUnderlyings::create_group(), FIX8::TEX::SecurityStatus::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityStatus::NoInstrumentParties::create_group(), FIX8::TEX::SecurityStatus::NoComplexEvents::create_group(), FIX8::TEX::SecurityStatus::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::TradingSessionStatus::NoInstrumentParties::create_group(), FIX8::TEX::TradingSessionStatus::NoComplexEvents::create_group(), FIX8::TEX::TradingSessionStatus::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoQuoteEntries::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoQuoteEntries::NoLegs::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoQuoteEntries::NoInstrumentParties::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoQuoteEntries::NoComplexEvents::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoQuoteEntries::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::MassQuote::NoQuoteSets::NoUndlyInstrumentParties::create_group(), FIX8::TEX::MassQuote::NoPartyIDs::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::NoUnderlyings::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::NoInstrumentParties::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::NoComplexEvents::create_group(), FIX8::TEX::ListStrikePrice::NoStrikes::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::RegistrationInstructions::NoPartyIDs::create_group(), FIX8::TEX::RegistrationInstructions::NoRegistDtls::create_group(), FIX8::TEX::RegistrationInstructions::NoRegistDtls::NoNestedPartyIDs::create_group(), FIX8::TEX::RegistrationInstructionsResponse::NoPartyIDs::create_group(), FIX8::TEX::OrderMassCancelRequest::NoPartyIDs::create_group(), FIX8::TEX::OrderMassCancelRequest::NoInstrumentParties::create_group(), FIX8::TEX::OrderMassCancelRequest::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassCancelRequest::NoComplexEvents::create_group(), FIX8::TEX::OrderMassCancelRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::OrderMassCancelReport::NoPartyIDs::create_group(), FIX8::TEX::OrderMassCancelReport::NoInstrumentParties::create_group(), FIX8::TEX::OrderMassCancelReport::NoUndlyInstrumentParties::create_group(), FIX8::TEX::OrderMassCancelReport::NoComplexEvents::create_group(), FIX8::TEX::OrderMassCancelReport::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::NewOrderCross::NoSides::create_group(), FIX8::TEX::NewOrderCross::NoSides::NoAllocs::create_group(), FIX8::TEX::NewOrderCross::NoSides::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::NewOrderCross::NoSides::NoPartyIDs::create_group(), FIX8::TEX::NewOrderCross::NoLegs::create_group(), FIX8::TEX::NewOrderCross::NoUnderlyings::create_group(), FIX8::TEX::NewOrderCross::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::NewOrderCross::NoInstrumentParties::create_group(), FIX8::TEX::NewOrderCross::NoRootPartyIDs::create_group(), FIX8::TEX::NewOrderCross::NoComplexEvents::create_group(), FIX8::TEX::NewOrderCross::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoSides::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoSides::NoAllocs::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoSides::NoAllocs::NoNestedPartyIDs::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoSides::NoPartyIDs::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoLegs::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoUnderlyings::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoInstrumentParties::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoRootPartyIDs::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoComplexEvents::create_group(), FIX8::TEX::CrossOrderCancelReplaceRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoSides::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoSides::NoPartyIDs::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoLegs::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoUnderlyings::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoInstrumentParties::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoRootPartyIDs::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoComplexEvents::create_group(), FIX8::TEX::CrossOrderCancelRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityListRequest::NoLegs::create_group(), FIX8::TEX::SecurityListRequest::NoUnderlyings::create_group(), FIX8::TEX::SecurityListRequest::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityListRequest::NoInstrumentParties::create_group(), FIX8::TEX::SecurityListRequest::NoComplexEvents::create_group(), FIX8::TEX::SecurityListRequest::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoLegs::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoUnderlyings::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoUnderlyings::NoUndlyInstrumentParties::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoInstrumentParties::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoStrikeRules::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoTradingSessionRules::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoComplexEvents::create_group(), FIX8::TEX::SecurityList::NoRelatedSym::NoComplexEvents::NoComplexEventDates::create_group(), FIX8::TEX::DerivativeSecurityListRequest::NoUndlyInstrumentParties::create_group(), and FIX8::TEX::DerivativeSecurityListRequest::NoDerivativeInstrumentParties::create_group().
 { return _groups; }
virtual msg_type* FIX8::MessageBase::get_msg_type () inline virtual
Get pointer to msg_type Field; used by header/trailer.
Returns
Field
Reimplemented in FIX8::TEX::header, and FIX8::TEX::header.
Definition at line 987 of file message.hpp.
 { return nullptr; }
const f8String& FIX8::MessageBase::get_msgtype () const inline
Get the message type as a string.
Returns
the Fix message type as a string
Definition at line 538 of file message.hpp.
References _msgType.
Referenced by FIX8::Session::enforce(), FIX8::Session::generate_business_reject(), FIX8::Session::handle_resend_request(), FIX8::Session::process(), and FIX8::ConsoleMenu::SelectField().
 { return _msgType; }
static unsigned FIX8::MessageBase::get_tabsize () inline static
get the tabsize used by the printer
Returns
tabsize of spaces in a tab
Definition at line 966 of file message.hpp.
References _tabsize.
 { return _tabsize; }
const f8String& FIX8::MessageBase::get_unknown () const inline
Get pass through fields (permissive mode only)
Returns
string of unknown pass through fields
Definition at line 995 of file message.hpp.
References _unknown.
 { return _unknown; }
unsigned short FIX8::MessageBase::getPos (const unsigned short field) const inline
Find the position of a field in a message.
Parameters
field field number
Returns
position of field
Definition at line 846 of file message.hpp.
References FIX8::FieldTraits::getPos().
 { return _fp.getPos(field); }
template<typename T > bool FIX8::MessageBase::has () const inline
Check if a field is present.
Template Parameters
T type of field to get
Returns
true if present
Definition at line 686 of file message.hpp.
References FIX8::FieldTraits::get().
 { return _fp.get(T::get_field_id()); }
static bool FIX8::MessageBase::has_group_count (const BaseField * bf) inline static
Determine if this repeating group count field has any elements (> 0)
Parameters
bf Basefield *
Returns
true if has count
Definition at line 971 of file message.hpp.
 { return static_cast<const Field<int, 0> *>(bf)->get() > 0; }
bool FIX8::MessageBase::have (const unsigned short fnum) const inline
Check if a field is present in this message.
Parameters
fnum field number
Returns
true is present
Definition at line 725 of file message.hpp.
References FIX8::FieldTraits::get(), and FIX8::FieldTrait::present.
Referenced by FIX8::Session::handle_logon(), FIX8::ConsoleMenu::SelectField(), and FIX8::Session::send_process().
 { return _fp.get(fnum, FieldTrait::present); }
bool FIX8::MessageBase::is_legal (unsigned short fnum) const inline
Check if a field is legal in a message.
Parameters
fnum field number
Returns
true if present
Definition at line 691 of file message.hpp.
References FIX8::FieldTraits::has().
Referenced by FIX8::Session::generate_logon().
 { return _fp.has(fnum); }
template<typename T > bool FIX8::MessageBase::is_legal () const inline
Check if a field is legal.
Template Parameters
T type of field to check
Returns
true if present
Definition at line 697 of file message.hpp.
References FIX8::FieldTraits::has().
 { return _fp.has(T::get_field_id()); }
unsigned MessageBase::move_legal (MessageBase * to, bool force = false)
Move all fields from this message to 'to' where the field is legal for 'to' and it is not already present in 'to'; includes nested repeating groups. Not thread safe. Source message must be heap based. Source message is invalidated (but can be deleted).
Parameters
to target message
force if true move all fields regardless, replacing any existing, adding any new
Returns
number of fields moved
Definition at line 296 of file message.cpp.
References _fp, add_field(), find_group(), FIX8::FieldTraits::get(), FIX8::FieldTrait::group, FIX8::FieldTraits::has(), FIX8::FieldTrait::present, and replace().
 {
    unsigned moved{};
    for (const auto& pp : _fp.get_presence())
    {
       if (pp._field_traits & FieldTrait::present && (force || (to->_fp.has(pp._fnum) && !to->_fp.get(pp._fnum))))
       {
          if (pp._field_traits & FieldTrait::group)
          {
             auto gitr(_groups.find(pp._fnum));
             GroupBase *gb1(to->find_group(pp._fnum));
             if (gb1)
                delete to->replace(pp._fnum, gitr->second);
             else
                *to += gitr->second;
             gitr->second = nullptr;
          }
          auto itr(_fields.find(pp._fnum));
          Presence::const_iterator fpitr(_fp.get_presence().end());
          if (force && to->_fp.get(pp._fnum, fpitr, FieldTrait::present))
             delete to->replace(pp._fnum, fpitr, itr->second);
          else
             to->add_field(itr->second);
          itr->second = nullptr;
          ++moved;
       }
    }
    clear_positions();
    return moved;
 }
template<typename T > bool FIX8::MessageBase::operator() (T & to) const inline
Populate supplied field with value from message.
Template Parameters
T type of field to get
Parameters
to field to populate
Returns
true on success
Definition at line 714 of file message.hpp.
 { return get(to); }
template<typename T > const T* FIX8::MessageBase::operator() () const inline
Get a pointer to a field. Inplace, 0 copy.
Template Parameters
T type of field to get
Returns
pointer to field or 0 if not present
Definition at line 720 of file message.hpp.
 { return get<T>(); }
template<typename T > bool FIX8::MessageBase::operator+= (T * what) inline
Add fix field to this message.
Template Parameters
T field type
Parameters
what pointer to field
Returns
true on success; throws InvalidField if not valid
Definition at line 657 of file message.hpp.
References add_field().
 { return add_field(what); }
void FIX8::MessageBase::operator+= (GroupBase * what) inline
Add a repeating group to a message.
Parameters
what pointer to group to add
Definition at line 841 of file message.hpp.
References add_group().
 { add_group(what); }
template<typename T > MessageBase& FIX8::MessageBase::operator<< (T * what) inline
Add fix field to this message.
Template Parameters
T field type
Parameters
what pointer to field
Returns
reference to MessageBase on success
Definition at line 664 of file message.hpp.
References add_field().
 { add_field(what); return *this; }
MessageBase& FIX8::MessageBase::operator<< (GroupBase * what) inline
Add a repeating group to a message.
Parameters
what pointer to field
Returns
reference to MessageBase on success
Definition at line 837 of file message.hpp.
References add_group().
 { add_group(what); return *this; }
F8API MessageBase& FIX8::MessageBase::operator= (const MessageBase & that)
Assignment operator.
void MessageBase::print (std::ostream & os, int depth = 0) const virtual
Print the message to the specified stream.
Parameters
os refererence to stream to print to
depth nesting depth
Reimplemented in FIX8::Message.
Definition at line 490 of file message.cpp.
References FIX8::BaseMsgEntry::_name.
Referenced by FIX8::Message::print().
 {
    const string dspacer((depth + 1) * _tabsize, ' ');
    const BaseMsgEntry *tbme(_ctx._bme.find_ptr(_msgType.c_str()));
    if (tbme)
       os << string(depth * _tabsize, ' ') << tbme->_name << " (\"" << _msgType << "\")" << endl;
    for (const auto& pp : _pos)
    {
       const BaseEntry *tbe(_ctx.find_be(pp.second->_fnum));
       if (!tbe)
          throw InvalidField(pp.second->_fnum);
       os << dspacer << tbe->_name;
       const unsigned short comp(_fp.getComp(pp.second->_fnum));
       if (comp)
          os << " [" << _ctx._cn[comp] << ']';
       os << " (" << pp.second->_fnum << "): ";
       int idx;
       if (pp.second->_rlm && (idx = (pp.second->get_rlm_idx())) >= 0)
          os << pp.second->_rlm->_descriptions[idx] << " (" << *pp.second << ')' << endl;
       else
          os << *pp.second << endl;
       if (_fp.is_group(pp.second->_fnum) && has_group_count(pp.second))
          print_group(pp.second->_fnum, os, depth);
    }
 }
void MessageBase::print_field (const unsigned short fnum, std::ostream & os) const virtual
Print the field specified by the field num from message to the specified stream.
Parameters
fnum field number
os refererence to stream to print to
Definition at line 535 of file message.cpp.
Referenced by FIX8::ConsoleMenu::SelectField().
 {
    Fields::const_iterator fitr(_fields.find(fnum));
    if (fitr != _fields.end())
    {
       const BaseEntry *tbe(_ctx.find_be(fnum));
       if (!tbe)
          throw InvalidField(fnum);
       os << tbe->_name << " (" << fnum << "): ";
       int idx;
       if (fitr->second->_rlm && (idx = (fitr->second->get_rlm_idx())) >= 0)
          os << fitr->second->_rlm->_descriptions[idx] << " (" << *fitr->second << ')';
       else
          os << *fitr->second;
       if (_fp.is_group(fnum) && has_group_count(fitr->second))
          print_group(fnum, os, 0);
    }
 }
void FIX8::MessageBase::print_fp (std::ostream & os) inline
Presence printer
Parameters
os stream to send to
Definition at line 975 of file message.hpp.
References _fp.
 { os << _fp; }
void MessageBase::print_group (const unsigned short fnum, std::ostream & os, int depth = 0) const virtual
Print the repeating group to the specified stream.
Parameters
fnum field number
os refererence to stream to print to
depth nesting depth
Definition at line 517 of file message.cpp.
References FIX8::GroupBase::_msgs, FILE_LINE, and find_group().
 {
    const GroupBase *grpbase(find_group(fnum));
    if (!grpbase)
       throw InvalidRepeatingGroup(fnum, FILE_LINE);
    ++depth;
    const string dspacer(depth * _tabsize, ' ');
    size_t cnt(1);
    for (const auto *pp : grpbase->_msgs)
    {
       os << dspacer << pp->_msgType << " (Repeating group " << cnt << '/' << grpbase->_msgs.size() << ')' << endl;
       pp->print(os, depth);
       ++cnt;
    }
 }
void FIX8::MessageBase::push_unknown (MessageBase * to) const inline
Copy _unknown string from this message to given message
Definition at line 518 of file message.hpp.
References _unknown.
Referenced by FIX8::Message::push_unknown().
    {
       if (_unknown.size() && to)
          to->_unknown = _unknown;
    }
BaseField * MessageBase::remove (const unsigned short fnum, Presence::const_iterator itr)
Remove a field from this message.
Parameters
fnum field number
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
Returns
pointer to original field or 0 if not found
Definition at line 627 of file message.cpp.
References FIX8::FieldTrait::present.
Referenced by MyMenu::load_msgs(), FIX8::Session::send_process(), and FIX8::Message::setup_reuse().
 {
    BaseField *old(nullptr);
    Fields::iterator itr(_fields.find(fnum));
    if (itr != _fields.end())
    {
       old = itr->second;
       for (Positions::iterator pitr(_pos.begin()); pitr != _pos.end(); ++pitr)
       {
          if (pitr->second == old)
          {
             _pos.erase(pitr);
             break;
          }
       }
       _fp.clear(fnum, fitr, FieldTrait::present);
       _fields.erase(itr);
    }
    return old;
 }
BaseField * MessageBase::remove (const unsigned short fnum)
Remove a field from this message.
Parameters
fnum field number
Returns
pointer to original field or 0 if not found
Definition at line 605 of file message.cpp.
References FIX8::FieldTrait::present.
 {
    BaseField *old(nullptr);
    Fields::iterator itr(_fields.find(fnum));
    if (itr != _fields.end())
    {
       old = itr->second;
       for (Positions::iterator pitr(_pos.begin()); pitr != _pos.end(); ++pitr)
       {
          if (pitr->second == old)
          {
             _pos.erase(pitr);
             break;
          }
       }
       _fp.clear(fnum, FieldTrait::present);
       _fields.erase(itr);
    }
    return old;
 }
BaseField * MessageBase::replace (const unsigned short fnum, Presence::const_iterator itr, BaseField * with)
Replace a field value with another field value.
Parameters
fnum field number
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
with field to replace with
Returns
pointer to original field or 0 if not found
Definition at line 580 of file message.cpp.
References FIX8::FieldTrait::present.
Referenced by add_field(), copy_legal(), and move_legal().
 {
    BaseField *old(nullptr);
    Fields::iterator itr(_fields.find(fnum));
    if (itr != _fields.end())
    {
       old = itr->second;
       unsigned pos(_fp.getPos(fnum, fitr));
       for (Positions::iterator pitr(_pos.begin()); pitr != _pos.end(); ++pitr)
       {
          if (pitr->second == old)
          {
             pos = pitr->first;
             _pos.erase(pitr);
             break;
          }
       }
       _pos.insert({pos, with});
       itr->second = with;
       _fp.set(fnum, fitr, FieldTrait::present);
    }
    return old;
 }
BaseField * MessageBase::replace (const unsigned short fnum, BaseField * with)
Replace a field value with another field value.
Parameters
fnum field number
with field to replace with
Returns
pointer to original field or 0 if not found
Definition at line 555 of file message.cpp.
References FIX8::FieldTrait::present.
 {
    BaseField *old(nullptr);
    Fields::iterator itr(_fields.find(fnum));
    if (itr != _fields.end())
    {
       old = itr->second;
       unsigned pos(_fp.getPos(fnum));
       for (Positions::iterator pitr(_pos.begin()); pitr != _pos.end(); ++pitr)
       {
          if (pitr->second == old)
          {
             pos = pitr->first;
             _pos.erase(pitr);
             break;
          }
       }
       _pos.insert({pos, with});
       itr->second = with;
       _fp.set(fnum, FieldTrait::present);
    }
    return old;
 }
GroupBase * MessageBase::replace (const unsigned short fnum, GroupBase * with)
Replace a group with another group.
Parameters
fnum group field number
with group to replace with
Returns
pointer to original group or 0 if not found
Definition at line 702 of file message.cpp.
 {
    GroupBase *old(nullptr);
    auto itr(_groups.find(fnum));
    if (itr != _groups.end())
    {
       old = itr->second;
       itr->second = with;
    }
    return old;
 }
void FIX8::MessageBase::set (const unsigned short field, FieldTrait::TraitTypes type = FieldTrait::present) inline
Set field attribute to given value.
Parameters
field tag number
type fieldtrait type
Definition at line 614 of file message.hpp.
References FIX8::FieldTraits::set().
 { _fp.set(field, type); }
static void FIX8::MessageBase::set_tabsize (unsigned tabsize) inline static
Set the tabsize used by the printer
Parameters
tabsize number of spaces in a tab
Definition at line 962 of file message.hpp.
References tabsize().
Referenced by FIX8::SessionConfig::SessionConfig().
 { _tabsize = tabsize; }
size_t FIX8::MessageBase::size () const inline
Get the number of possible fields in this message
Returns
number of fields
Definition at line 451 of file message.hpp.
References FIX8::FieldTraits::size().
Referenced by FIX8::GroupBase::get_element(), and MyMenu::preload_new_order_single().
 { return _fp.size(); }
Friends And Related Function Documentation
friend class Message friend
Definition at line 958 of file message.hpp.
std::ostream& operator<< (std::ostream & os, const MessageBase & what) friend
Inserter friend.
Parameters
os stream to send to
what messagebase
Returns
stream
Definition at line 957 of file message.hpp.
 { what.print(os); return os; }
Member Data Documentation
const F8MetaCntx& FIX8::MessageBase::_ctx protected
Definition at line 392 of file message.hpp.
Referenced by FIX8::Message::get_field_by_name_flattened().
Fields FIX8::MessageBase::_fields protected
Definition at line 387 of file message.hpp.
Referenced by FIX8::Message::get_field_flattened().
FieldTraits FIX8::MessageBase::_fp protected
Definition at line 388 of file message.hpp.
Referenced by copy_legal(), get_fp(), move_legal(), print_fp(), and FIX8::Message::setup_reuse().
Groups FIX8::MessageBase::_groups protected
Definition at line 390 of file message.hpp.
Referenced by FIX8::TEX::AdjustedPositionReport::AdjustedPositionReport(), FIX8::TEX::Advertisement::Advertisement(), FIX8::TEX::AllocationInstruction::AllocationInstruction(), FIX8::TEX::AllocationInstructionAck::AllocationInstructionAck(), FIX8::TEX::AllocationInstructionAlert::AllocationInstructionAlert(), FIX8::TEX::AllocationReport::AllocationReport(), FIX8::TEX::AllocationReportAck::AllocationReportAck(), FIX8::TEX::ApplicationMessageReport::ApplicationMessageReport(), FIX8::TEX::ApplicationMessageRequest::ApplicationMessageRequest(), FIX8::TEX::ApplicationMessageRequestAck::ApplicationMessageRequestAck(), FIX8::TEX::AssignmentReport::AssignmentReport(), FIX8::TEX::BidRequest::BidRequest(), FIX8::TEX::BidResponse::BidResponse(), FIX8::TEX::CollateralAssignment::CollateralAssignment(), FIX8::TEX::CollateralInquiry::CollateralInquiry(), FIX8::TEX::CollateralInquiryAck::CollateralInquiryAck(), FIX8::TEX::CollateralReport::CollateralReport(), FIX8::TEX::CollateralRequest::CollateralRequest(), FIX8::TEX::CollateralResponse::CollateralResponse(), FIX8::TEX::Confirmation::Confirmation(), FIX8::TEX::ConfirmationRequest::ConfirmationRequest(), FIX8::TEX::ContraryIntentionReport::ContraryIntentionReport(), FIX8::TEX::CrossOrderCancelReplaceRequest::CrossOrderCancelReplaceRequest(), FIX8::TEX::CrossOrderCancelRequest::CrossOrderCancelRequest(), FIX8::TEX::DerivativeSecurityList::DerivativeSecurityList(), FIX8::TEX::DerivativeSecurityListRequest::DerivativeSecurityListRequest(), FIX8::TEX::DerivativeSecurityListUpdateReport::DerivativeSecurityListUpdateReport(), FIX8::TEX::DontKnowTrade::DontKnowTrade(), FIX8::TEX::Email::Email(), FIX8::TEX::ExecutionAcknowledgement::ExecutionAcknowledgement(), FIX8::TEX::ExecutionReport::ExecutionReport(), get_groups(), FIX8::TEX::IOI::IOI(), FIX8::TEX::ListCancelRequest::ListCancelRequest(), FIX8::TEX::ListStatus::ListStatus(), FIX8::TEX::ListStrikePrice::ListStrikePrice(), FIX8::TEX::Logon::Logon(), FIX8::TEX::MarketDataIncrementalRefresh::MarketDataIncrementalRefresh(), FIX8::TEX::MarketDataRequest::MarketDataRequest(), FIX8::TEX::MarketDataRequestReject::MarketDataRequestReject(), FIX8::TEX::MarketDataSnapshotFullRefresh::MarketDataSnapshotFullRefresh(), FIX8::TEX::MarketDefinition::MarketDefinition(), FIX8::TEX::MarketDefinitionUpdateReport::MarketDefinitionUpdateReport(), FIX8::TEX::MassQuote::MassQuote(), FIX8::TEX::MassQuoteAcknowledgement::MassQuoteAcknowledgement(), FIX8::TEX::MultilegOrderCancelReplace::MultilegOrderCancelReplace(), FIX8::TEX::NetworkCounterpartySystemStatusRequest::NetworkCounterpartySystemStatusRequest(), FIX8::TEX::NetworkCounterpartySystemStatusResponse::NetworkCounterpartySystemStatusResponse(), FIX8::TEX::NewOrderCross::NewOrderCross(), FIX8::TEX::NewOrderList::NewOrderList(), FIX8::TEX::NewOrderMultileg::NewOrderMultileg(), FIX8::TEX::NewOrderSingle::NewOrderSingle(), FIX8::TEX::News::News(), FIX8::TEX::OrderCancelReplaceRequest::OrderCancelReplaceRequest(), FIX8::TEX::OrderCancelRequest::OrderCancelRequest(), FIX8::TEX::OrderMassActionReport::OrderMassActionReport(), FIX8::TEX::OrderMassActionRequest::OrderMassActionRequest(), FIX8::TEX::OrderMassCancelReport::OrderMassCancelReport(), FIX8::TEX::OrderMassCancelRequest::OrderMassCancelRequest(), FIX8::TEX::OrderMassStatusRequest::OrderMassStatusRequest(), FIX8::TEX::OrderStatusRequest::OrderStatusRequest(), FIX8::TEX::PartyDetailsListReport::PartyDetailsListReport(), FIX8::TEX::PartyDetailsListRequest::PartyDetailsListRequest(), FIX8::TEX::PositionMaintenanceReport::PositionMaintenanceReport(), FIX8::TEX::PositionMaintenanceRequest::PositionMaintenanceRequest(), FIX8::TEX::PositionReport::PositionReport(), FIX8::TEX::Quote::Quote(), FIX8::TEX::QuoteCancel::QuoteCancel(), FIX8::TEX::QuoteRequest::QuoteRequest(), FIX8::TEX::QuoteRequestReject::QuoteRequestReject(), FIX8::TEX::QuoteResponse::QuoteResponse(), FIX8::TEX::QuoteStatusReport::QuoteStatusReport(), FIX8::TEX::QuoteStatusRequest::QuoteStatusRequest(), FIX8::TEX::RegistrationInstructions::RegistrationInstructions(), FIX8::TEX::RegistrationInstructionsResponse::RegistrationInstructionsResponse(), FIX8::TEX::RequestForPositions::RequestForPositions(), FIX8::TEX::RequestForPositionsAck::RequestForPositionsAck(), FIX8::TEX::RFQRequest::RFQRequest(), FIX8::TEX::SecurityDefinition::SecurityDefinition(), FIX8::TEX::SecurityDefinitionRequest::SecurityDefinitionRequest(), FIX8::TEX::SecurityDefinitionUpdateReport::SecurityDefinitionUpdateReport(), FIX8::TEX::SecurityList::SecurityList(), FIX8::TEX::SecurityListRequest::SecurityListRequest(), FIX8::TEX::SecurityListUpdateReport::SecurityListUpdateReport(), FIX8::TEX::SecurityStatus::SecurityStatus(), FIX8::TEX::SecurityStatusRequest::SecurityStatusRequest(), FIX8::TEX::SecurityTypes::SecurityTypes(), FIX8::TEX::SettlementInstructionRequest::SettlementInstructionRequest(), FIX8::TEX::SettlementInstructions::SettlementInstructions(), FIX8::TEX::SettlementObligationReport::SettlementObligationReport(), FIX8::TEX::StreamAssignmentReport::StreamAssignmentReport(), FIX8::TEX::StreamAssignmentRequest::StreamAssignmentRequest(), FIX8::TEX::TradeCaptureReport::TradeCaptureReport(), FIX8::TEX::TradeCaptureReportAck::TradeCaptureReportAck(), FIX8::TEX::TradeCaptureReportRequest::TradeCaptureReportRequest(), FIX8::TEX::TradeCaptureReportRequestAck::TradeCaptureReportRequestAck(), FIX8::TEX::TradingSessionList::TradingSessionList(), FIX8::TEX::TradingSessionListUpdateReport::TradingSessionListUpdateReport(), and FIX8::TEX::TradingSessionStatus::TradingSessionStatus().
const f8String& FIX8::MessageBase::_msgType protected
Definition at line 391 of file message.hpp.
Referenced by get_msgtype().
Positions FIX8::MessageBase::_pos protected
Definition at line 389 of file message.hpp.
unsigned MessageBase::_tabsize = defaults::tabsize static protected
Definition at line 408 of file message.hpp.
Referenced by get_tabsize().
f8String FIX8::MessageBase::_unknown private
pass through for permissive mode
Definition at line 384 of file message.hpp.
Referenced by get_unknown(), and push_unknown().
The documentation for this class was generated from the following files:
message.hpp
message.cpp