fix8: ff::zmqTransportMsg_t Class Reference
ff::zmqTransportMsg_t Class Reference
It describes the sructure of 0MQ transport message.
#include <zmqTransport.hpp>
Public Types
enum { HEADER_LENGTH =4 }
typedef void(msg_callback_t)(void *, void *)
Public Member Functions
zmqTransportMsg_t ()
zmqTransportMsg_t (const void *data, size_t size, msg_callback_t cb=0, void *arg=0)
void init (const void *data, size_t size, msg_callback_t cb=0, void *arg=0)
void copy (zmq::message_t &msg)
void * getData ()
size_t size ()
Detailed Description
It describes the sructure of 0MQ transport message.
This class describes the layout of a message used for inter-thread communications, inter-process communications, TCP/IP and multicast sockets in a distrubuted system running on the FastFlow framework.
This class is defined in zmqTransport.hpp
Definition at line 74 of file zmqTransport.hpp.
Member Typedef Documentation
typedef void(ff::zmqTransportMsg_t::msg_callback_t)(void *, void *)
It provides the callback definition.
Definition at line 79 of file zmqTransport.hpp.
Member Enumeration Documentation
anonymous enum
HEADER_LENGTH is the enumberation of the number of bytes.
Enumerator
HEADER_LENGTH
Definition at line 84 of file zmqTransport.hpp.
Constructor & Destructor Documentation
ff::zmqTransportMsg_t::zmqTransportMsg_t () inline
Constructor (1)
It creates an empty ØMQ message.
Definition at line 92 of file zmqTransport.hpp.
ff::zmqTransportMsg_t::zmqTransportMsg_t (const void * data, size_t size, msg_callback_t cb = 0, void * arg = 0) inline
Constructor (2)
It creates a structured ØMQ message.
Parameters
data has the content of the message.
size is the amount of memory to be allocated for the message.
cb is the callback function.
arg has additional arguments.
Definition at line 104 of file zmqTransport.hpp.
Member Function Documentation
void ff::zmqTransportMsg_t::copy (zmq::message_t & msg) inline
It copies the message.
Parameters
msg is the reference to the 0MQ transport message.
Definition at line 127 of file zmqTransport.hpp.
Referenced by ff::zmqOnDemand::put(), ff::descriptor1_N::send(), ff::descriptor1_N::sendreply(), and ff::descriptorN_1::sendreply().
void* ff::zmqTransportMsg_t::getData () inline
It retrieves the content of the message object.
Returns
The contents of the message object.
Definition at line 136 of file zmqTransport.hpp.
References data.
Referenced by ff::descriptorN_1::recvHelloSendHi(), ff::descriptor1_N::recvreq(), ff::descriptor1_N::sendHelloRecvHi(), and ff::descriptorN_1::sendHelloRecvHi().
void ff::zmqTransportMsg_t::init (const void * data, size_t size, msg_callback_t cb = 0, void * arg = 0) inline
It initialises the message object (It is like the constructor but it rebuilds the object from scratch using new values).
Parameters
data has the content of the message.
size is the amount of memory to be allocated for the message.
cb is the callback function.
arg has additional arguments.
Definition at line 118 of file zmqTransport.hpp.
size_t ff::zmqTransportMsg_t::size () inline
It retrieves the size in bytes of the content of the message object.
Returns
The size of the contexts of the message in bytes.
Definition at line 145 of file zmqTransport.hpp.
The documentation for this class was generated from the following file:
zmqTransport.hpp