fix8: FIX8::Message Class Reference
FIX8::Message Class Reference
A complete Fix message with header, body and trailer.
#include <message.hpp>
Public Member Functions
template<typename InputIterator >
Message (const F8MetaCntx &ctx, const f8String &msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array *ftha)
virtual ~Message ()
Dtor.
MessageBase * Header () const
MessageBase * Trailer () const
unsigned decode (const f8String &from, unsigned offset=0, unsigned ignore=0, bool permissive_mode=false)
F8API size_t encode (f8String &to) const
F8API size_t encode (char **to) const
Encode message with minimal copying.
F8API Message * clone () const
virtual bool process (Router &rt) const
virtual bool is_admin () const
virtual void clear (bool reuse=true)
virtual void set_custom_seqnum (unsigned seqnum)
unsigned get_custom_seqnum () const
virtual void set_no_increment (bool flag=true)
virtual bool get_no_increment () const
bool get_end_of_batch () const
void set_end_of_batch (bool is_end_of_batch)
void setup_reuse ()
void push_unknown (Message *to) const
BaseField * get_field_flattened (const unsigned short fnum) const
BaseField * get_field_by_name_flattened (const char *tag) const
virtual F8API void print (std::ostream &os, int depth=0) const
Public Member Functions inherited from FIX8::MessageBase
template<typename InputIterator >
MessageBase (const struct F8MetaCntx &ctx, const f8String &msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array *ftha)
F8API MessageBase (const MessageBase &from)
Copy ctor.
F8API MessageBase & operator= (const MessageBase &that)
Assignment operator.
virtual ~MessageBase ()
Dtor.
void clear_positions ()
empty the positions map
size_t size () const
F8API unsigned decode (const f8String &from, unsigned offset, unsigned ignore=0, bool permissive_mode=false)
unsigned decode_group (GroupBase *grpbase, const unsigned short fnum, const f8String &from, unsigned s_offset, unsigned ignore)
F8API size_t encode (std::ostream &to) const
F8API size_t encode (char *to) const
F8API size_t encode_group (const unsigned short fnum, std::ostream &to) const
F8API size_t encode_group (const unsigned short fnum, char *to) const
virtual GroupBase * create_nested_group (unsigned short fnum) const
F8API unsigned check_positions ()
F8API unsigned copy_legal (MessageBase *to, bool force=false) const
F8API unsigned move_legal (MessageBase *to, bool force=false)
void push_unknown (MessageBase *to) const
void check_set_rlm (BaseField *where) const
const f8String & get_msgtype () const
void add_field_decoder (const unsigned short fnum, const unsigned pos, BaseField *what)
void add_field (const unsigned short fnum, Presence::const_iterator itr, const unsigned pos, BaseField *what, bool check)
void add_field (const unsigned short fnum, Fields::iterator fitr, const unsigned pos, BaseField *what, bool check=true)
void add_field (const unsigned short fnum, const unsigned pos, BaseField *what, bool check=true)
void set (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
template<typename T >
bool add_field (T *what)
bool add_field (BaseField *what)
Groups & get_groups ()
template<typename T >
bool operator+= (T *what)
template<typename T >
MessageBase & operator<< (T *what)
template<typename T >
bool get (T &to) const
template<typename T >
bool has () const
bool is_legal (unsigned short fnum) const
template<typename T >
bool is_legal () const
template<typename T >
const T * get () const
template<typename T >
bool operator() (T &to) const
template<typename T >
const T * operator() () const
bool have (const unsigned short fnum) const
Fields::const_iterator find_field (const unsigned short fnum) const
BaseField * get_field (const unsigned short fnum) const
BaseField * get_field_by_name (const char *tag) const
Fields::const_iterator fields_begin () const
Fields::const_iterator fields_end () const
F8API BaseField * replace (const unsigned short fnum, Presence::const_iterator itr, BaseField *with)
F8API BaseField * replace (const unsigned short fnum, BaseField *with)
F8API GroupBase * replace (const unsigned short fnum, GroupBase *with)
F8API BaseField * remove (const unsigned short fnum, Presence::const_iterator itr)
F8API BaseField * remove (const unsigned short fnum)
template<typename T >
GroupBase * find_group () const
GroupBase * find_group (const unsigned short fnum) const
template<typename T >
GroupBase * find_add_group (GroupBase *grpbase=nullptr)
GroupBase * find_add_group (const unsigned short fnum, GroupBase *grpbase=nullptr)
template<typename T >
void append_group (T *what)
void add_group (GroupBase *what)
MessageBase & operator<< (GroupBase *what)
void operator+= (GroupBase *what)
unsigned short getPos (const unsigned short field) const
bool add_trait (const FieldTrait &what)
template<typename InputIterator >
void add_trait (const InputIterator begin, const size_t cnt)
virtual F8API void print_field (const unsigned short fnum, std::ostream &os) const
virtual F8API void print_group (const unsigned short fnum, std::ostream &os, int depth=0) const
const FieldTraits & get_fp () const
void print_fp (std::ostream &os)
virtual begin_string * get_begin_string ()
virtual body_length * get_body_length ()
virtual msg_type * get_msg_type ()
virtual check_sum * get_check_sum ()
const f8String & get_unknown () const
Static Public Member Functions
static unsigned calc_chksum (const char *from, const size_t sz, const unsigned offset=0, const int len=-1)
static unsigned calc_chksum (const f8String &from, const unsigned offset=0, const int len=-1)
static f8String fmt_chksum (const unsigned val)
static Message * factory (const F8MetaCntx &ctx, const char *from, bool no_chksum=false, bool permissive_mode=false)
static F8API Message * factory (const F8MetaCntx &ctx, const f8String &from, bool no_chksum=false, bool permissive_mode=false)
Static Public Member Functions inherited from FIX8::MessageBase
static unsigned extract_element (const char *from, const unsigned sz, char *tag, char *val)
static unsigned extract_element (const char *from, const unsigned sz, f8String &tag, f8String &val)
static void set_tabsize (unsigned tabsize)
static unsigned get_tabsize ()
static bool has_group_count (const BaseField *bf)
Protected Attributes
MessageBase * _header
MessageBase * _trailer
unsigned _custom_seqnum
bool _no_increment
bool _end_of_batch
Protected Attributes inherited from FIX8::MessageBase
Fields _fields
FieldTraits _fp
Positions _pos
Groups _groups
const f8String & _msgType
const F8MetaCntx & _ctx
Friends
std::ostream & operator<< (std::ostream &os, const Message &what)
Additional Inherited Members
Static Protected Member Functions inherited from FIX8::MessageBase
static unsigned extract_header (const f8String &from, char *len, char *mtype)
static unsigned extract_trailer (const f8String &from, f8String &chksum)
Static Protected Attributes inherited from FIX8::MessageBase
static F8API unsigned _tabsize = defaults::tabsize
Detailed Description
A complete Fix message with header, body and trailer.
Definition at line 1016 of file message.hpp.
Constructor & Destructor Documentation
template<typename InputIterator > FIX8::Message::Message (const F8MetaCntx & ctx, const f8String & msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array * ftha) inline
Ctor.
Template Parameters
InputIterator input iterator type
Parameters
ctx - reference to generated metadata
msgType - reference to Fix message type
begin - InputIterator pointing to begining of field trait table
cnt - number of elements in field trait table
ftha field trait hash array
Definition at line 1045 of file message.hpp.
       : MessageBase(ctx, msgType, begin, cnt, ftha),_header(ctx._mk_hdr(true)),
         _trailer(ctx._mk_trl(true)), _custom_seqnum(), _no_increment(), _end_of_batch(true)
    {}
virtual FIX8::Message::~Message () inline virtual
Dtor.
Definition at line 1052 of file message.hpp.
References _header, and _trailer.
 { delete _header; delete _trailer; }
Member Function Documentation
static unsigned FIX8::Message::calc_chksum (const char * from, const size_t sz, const unsigned offset = 0, const int len = -1) inline static
Generate a checksum from an encoded buffer, ULL version.
Parameters
from char *buffer encoded Fix message
sz size of msg
offset starting offset
len maximum length
Returns
calculated checknum
Definition at line 1120 of file message.hpp.
Referenced by calc_chksum().
    {
       unsigned val(0);
       const char *eptr(from + (len != -1 ? len + offset : sz - offset));
       for (const char *ptr(from + offset); ptr < eptr; val += *ptr++);
       return val % 256;
    }
static unsigned FIX8::Message::calc_chksum (const f8String & from, const unsigned offset = 0, const int len = -1) inline static
Generate a checksum from an encoded buffer, string version.
Parameters
from source buffer encoded Fix message
offset starting offset
len maximum length
Returns
calculated checknum
Definition at line 1133 of file message.hpp.
References calc_chksum().
       { return calc_chksum(from.c_str(), from.size(), offset, len); }
virtual void FIX8::Message::clear (bool reuse = true) inline virtual
Empty messages from container
Parameters
reuse if true clear vector
Reimplemented from FIX8::MessageBase.
Definition at line 1105 of file message.hpp.
References _header, _trailer, and FIX8::MessageBase::clear().
    {
       if (_header)
          _header->clear(reuse);
       if (_trailer)
          _trailer->clear(reuse);
       MessageBase::clear(reuse);
    }
Message * Message::clone () const
Clone this message. Performs a deep copy.
Returns
pointer to copy of this message
Definition at line 649 of file message.cpp.
References FIX8::BaseMsgEntry::_create, and FIX8::Minst::_do.
 {
    const BaseMsgEntry& bme(_ctx._bme.find_ref(_msgType.c_str()));
    Message *msg(bme._create._do(true));
    copy_legal(msg, true);
    _header->copy_legal(msg->_header, true);
    _trailer->copy_legal(msg->_trailer, true);
    return msg;
 }
unsigned FIX8::Message::decode (const f8String & from, unsigned offset = 0, unsigned ignore = 0, bool permissive_mode = false) inline
Decode from string.
Parameters
from source string
offset in bytes to decode from
ignore bytes to ignore counting back from end of message
permissive_mode if true, ignore unknown fields
Returns
number of bytes consumed
Definition at line 1068 of file message.hpp.
References _header, _trailer, and FIX8::MessageBase::decode().
    {
       const unsigned hlen(_header->decode(from, offset, 0, permissive_mode));
       const unsigned blen(MessageBase::decode(from, hlen, 0, permissive_mode));
 #if defined RAW_MSG_SUPPORT
       _begin_payload = hlen;
       _payload_len = blen;
       _rawmsg = from;
 #endif
       return _trailer->decode(from, blen, ignore, permissive_mode);
    }
size_t Message::encode (f8String & to) const
Encode message to stream.
Parameters
to stream to encode to
Returns
number of bytes encoded
Definition at line 481 of file message.cpp.
References FIX8::HEADER_CALC_OFFSET(), and MAX_MSG_LENGTH.
 {
    char output[MAX_MSG_LENGTH + HEADER_CALC_OFFSET], *ptr(output);
    const size_t msgLen(encode(&ptr));
    to.assign(ptr, msgLen);
    return to.size();
 }
size_t Message::encode (char ** to) const
Encode message with minimal copying.
Encode message to stream. Perform absolutely minimal copying of output buffer.
Parameters
to pointer to pointer to buffer
Returns
number of bytes encoded; to ptr is updated with address of start of encoded message string
Definition at line 403 of file message.cpp.
References FIX8::IntervalTimer::AsDouble(), FIX8::IntervalTimer::Calculate(), FIX8::Common_BeginString(), FIX8::Common_BodyLength(), FIX8::Common_CheckSum(), FIX8::MessageBase::encode(), FIX8::HEADER_CALC_OFFSET(), and FIX8::FieldTrait::suppress.
 {
    char *moffs(*hmsg_store + HEADER_CALC_OFFSET), *msg(moffs);
 #if defined CODECTIMING
    IntervalTimer itm;
 #endif
    if (!_header)
       throw MissingMessageComponent("header");
    _header->get_msg_type()->set(_msgType);
 #if defined RAW_MSG_SUPPORT
    msg += (_begin_payload = _header->encode(msg)); // start
 #if defined PREENCODE_MSG_SUPPORT
    if (_preencode_len)
    {
       ::memcpy(msg, _preencode.data(), _payload_len =_preencode_len);
       msg += _preencode_len;
    }
    else
 #endif
       msg += (_payload_len = MessageBase::encode(msg));
 #else
    msg += _header->encode(msg); // start
 #if defined PREENCODE_MSG_SUPPORT
    if (_preencode_len)
    {
       ::memcpy(msg, _preencode.data(), _preencode_len);
       msg += _preencode_len;
    }
    else
 #endif
       msg += MessageBase::encode(msg);
 #endif
    if (!_trailer)
       throw MissingMessageComponent("trailer");
    msg += _trailer->encode(msg);
    const size_t msgLen(msg - moffs); // checksummable msglength
    const size_t hlen(_ctx._preamble_sz +
       (msgLen < 10 ? 1 : msgLen < 100 ? 2 : msgLen < 1000 ? 3 : msgLen < 10000 ? 4 :
        msgLen < 100000 ? 5 : msgLen < 1000000 ? 6 : 7));
    char *hmsg(moffs - hlen);
    *hmsg_store = hmsg;
    if (!_header->get_begin_string())
       throw MissingMandatoryField(Common_BeginString);
    _header->_fp.clear(Common_BeginString, FieldTrait::suppress);
    hmsg += _header->get_begin_string()->encode(hmsg);
    if (!_header->get_body_length())
       throw MissingMandatoryField(Common_BodyLength);
    _header->_fp.clear(Common_BodyLength, FieldTrait::suppress);
    _header->get_body_length()->set(static_cast<int>(msgLen));
    hmsg += _header->get_body_length()->encode(hmsg);
    if (!_trailer->get_check_sum())
       throw MissingMandatoryField(Common_CheckSum);
    _trailer->get_check_sum()->set(fmt_chksum(calc_chksum(moffs - hlen, msgLen + hlen)));
    _trailer->_fp.clear(Common_CheckSum, FieldTrait::suppress);
    msg += _trailer->get_check_sum()->encode(msg);
 #if defined CODECTIMING
    _encode_timings._cpu_used += itm.Calculate().AsDouble();
    ++_encode_timings._msg_count;
 #endif
    *msg = 0;
    const size_t rlen(msg - *hmsg_store);
 #if defined RAW_MSG_SUPPORT
    _rawmsg.assign(*hmsg_store, rlen);
 #endif
    return rlen;
 }
static Message* FIX8::Message::factory (const F8MetaCntx & ctx, const char * from, bool no_chksum = false, bool permissive_mode = false) inline static
Using supplied metatdata context and raw input buffer, decode and create appropriate Fix message
Parameters
ctx reference to metadata object
from pointer to raw buffer containing one complete FIX message string only, no trailing or leading characters
no_chksum if true, do not perform chksum verification
permissive_mode if true, ignore unknown fields
Returns
pointer to newly created Message (which will be a super class of the generated type)
Definition at line 1153 of file message.hpp.
Referenced by FIX8::Session::process(), and FIX8::Session::retrans_callback().
    {
       const f8String to(from);
       return factory(ctx, to, no_chksum, permissive_mode);
    }
Message * Message::factory (const F8MetaCntx & ctx, const f8String & from, bool no_chksum = false, bool permissive_mode = false) static
Using supplied metatdata context and raw input buffer, decode and create appropriate Fix message
Parameters
ctx reference to metadata object
from reference to string raw buffer containing one complete FIX message string only, no trailing or leading characters
no_chksum if true, do not perform chksum verification
permissive_mode if true, ignore unknown fields
Returns
pointer to newly created Message (which will be a super class of the generated type)
Definition at line 205 of file message.cpp.
References FIX8::F8MetaCntx::_bme, FIX8::IntervalTimer::AsDouble(), FIX8::IntervalTimer::Calculate(), FILE_LINE, FIX8::GeneratedTable< Key, Val >::find_ptr(), glout_debug, and FIX8::MAX_MSGTYPE_FIELD_LEN().
 {
    char mtype[MAX_MSGTYPE_FIELD_LEN] {}, len[MAX_MSGTYPE_FIELD_LEN] {};
    const unsigned hlen(extract_header(from, len, mtype));
    if (!hlen)
    {
       glout_debug << "Message::factory throwing";
       throw InvalidMessage(from, FILE_LINE);
    }
    const unsigned mlen(fast_atoi<unsigned>(len));
    const BaseMsgEntry *bme(ctx._bme.find_ptr(mtype));
    if (!bme)
       throw InvalidMessage(mtype, FILE_LINE);
    Message *msg(bme->_create._do(false)); // shallow create
 #if defined CODECTIMING
    IntervalTimer itm;
 #endif
    msg->decode(from, hlen, 7, permissive_mode); // skip already decoded mandatory 8, 9, 35 and 10
 #if defined CODECTIMING
    _decode_timings._cpu_used += itm.Calculate().AsDouble();
    ++_decode_timings._msg_count;
 #endif
    msg->_header->get_body_length()->set(mlen);
    msg->_header->get_msg_type()->set(mtype);
 #if defined POPULATE_METADATA
    msg->check_set_rlm(fitr->second);
 #endif
    const char *pp(from.data() + from.size() - 7);   // FIXME: assumes supplied string is one complete message only
    if (*pp != '1' || *(pp + 1) != '0') // 10=XXX^A
       throw InvalidMessage(from, FILE_LINE);
    if (!no_chksum) // permit chksum calculation to be skipped
    {
       const f8String chksum(pp + 3, 3);
       msg->_trailer->get_check_sum()->set(chksum);
       const unsigned chkval(fast_atoi<unsigned>(chksum.c_str())), mchkval(calc_chksum(from, 0, static_cast<unsigned>(from.size()) - 7));
       if (chkval != mchkval)
          throw BadCheckSum(mchkval);
    }
    return msg;
 }
static f8String FIX8::Message::fmt_chksum (const unsigned val) inline static
Format a checksum into the required 3 digit, 0 padded string.
Parameters
val checksum value
Returns
string containing formatted value
Definition at line 1139 of file message.hpp.
    {
       char buf[4] { '0', '0', '0', 0 };
       itoa<unsigned>(val, buf + (val > 99 ? 0 : val > 9 ? 1 : 2), 10);
       return f8String(buf);
    }
unsigned FIX8::Message::get_custom_seqnum () const inline
Get the custom sequence number.
Returns
seqnum the outbound sequence number to use for this message.
Definition at line 1174 of file message.hpp.
References _custom_seqnum.
Referenced by FIX8::Session::send_process().
 { return _custom_seqnum; }
bool FIX8::Message::get_end_of_batch () const inline
Get the end of batch flag
Returns
true or false
Definition at line 1186 of file message.hpp.
References _end_of_batch.
 { return _end_of_batch; }
BaseField* FIX8::Message::get_field_by_name_flattened (const char * tag) const inline
Search for field by longname in this message (either header, body or trailer).
Parameters
tag field longname
Returns
pointer to field or 0 if not found
Definition at line 1230 of file message.hpp.
References FIX8::MessageBase::_ctx, get_field_flattened(), and FIX8::F8MetaCntx::reverse_find_fnum().
    {
       return get_field_flattened(_ctx.reverse_find_fnum(tag));
    }
BaseField* FIX8::Message::get_field_flattened (const unsigned short fnum) const inline
Search for field in this message (either header, body or trailer).
Parameters
fnum field number
Returns
pointer to field or 0 if not found
Definition at line 1219 of file message.hpp.
References FIX8::MessageBase::_fields, _header, and _trailer.
Referenced by get_field_by_name_flattened().
    {
       auto itr (_fields.find(fnum));
       return  itr != _fields.end() ? itr->second
             : (itr = _header->_fields.find(fnum)) != _header->_fields.end() ? itr->second
             : (itr = _trailer->_fields.find(fnum)) != _trailer->_fields.end() ? itr->second : nullptr;
    }
virtual bool FIX8::Message::get_no_increment () const inline virtual
Get the no increment flag.
Returns
value of _no_increment flag
Definition at line 1182 of file message.hpp.
References _no_increment.
 { return _no_increment; }
MessageBase* FIX8::Message::Header () const inline
Get a pointer to the message header.
Returns
pointer to header
Definition at line 1056 of file message.hpp.
References _header.
Referenced by FIX8::Session::compid_check(), FIX8::Session::handle_logon(), MyMenu::load_msgs(), FIX8::Session::send_process(), and FIX8::Session::sequence_check().
 { return _header; }
virtual bool FIX8::Message::is_admin () const inline virtual
Test whether this message is administrative.
Returns
true if administrative
Reimplemented in FIX8::TEX::Logon, FIX8::TEX::Logon, FIX8::TEX::Logout, FIX8::TEX::Logout, FIX8::TEX::SequenceReset, FIX8::TEX::SequenceReset, FIX8::TEX::Reject, FIX8::TEX::Reject, FIX8::TEX::ResendRequest, FIX8::TEX::ResendRequest, FIX8::TEX::TestRequest, FIX8::TEX::TestRequest, FIX8::TEX::Heartbeat, and FIX8::TEX::Heartbeat.
Definition at line 1101 of file message.hpp.
Referenced by MyMenu::load_msgs(), and FIX8::Session::process().
 { return false; }
void Message::print (std::ostream & os, int depth = 0) const virtual
Print the message to the specified stream.
Parameters
os refererence to stream to print to
depth not used
Reimplemented from FIX8::MessageBase.
Definition at line 660 of file message.cpp.
References FIX8::MessageBase::print().
 {
    if (_header)
       os << *_header;
    else
       os << "Null Header" << endl;
    MessageBase::print(os);
    if (_trailer)
       os << *_trailer;
    else
       os << "Null Trailer" << endl;
 }
virtual bool FIX8::Message::process (Router & rt) const inline virtual
Initiate callback to appropriate process method from metadata.
Parameters
rt reference to router instance
Returns
true if correctly processed
Reimplemented in FIX8::TEX::DerivativeSecurityListRequest, FIX8::TEX::SecurityList, FIX8::TEX::SecurityListRequest, FIX8::TEX::SecurityTypes, FIX8::TEX::SecurityTypeRequest, FIX8::TEX::CrossOrderCancelRequest, FIX8::TEX::CrossOrderCancelReplaceRequest, FIX8::TEX::NewOrderCross, FIX8::TEX::OrderMassCancelReport, FIX8::TEX::OrderMassCancelRequest, FIX8::TEX::RegistrationInstructionsResponse, FIX8::TEX::RegistrationInstructions, FIX8::TEX::ListStrikePrice, FIX8::TEX::BidResponse, FIX8::TEX::BidRequest, FIX8::TEX::BusinessMessageReject, FIX8::TEX::MassQuote, FIX8::TEX::TradingSessionStatus, FIX8::TEX::TradingSessionStatusRequest, FIX8::TEX::SecurityStatus, FIX8::TEX::SecurityStatusRequest, FIX8::TEX::SecurityDefinition, FIX8::TEX::SecurityDefinitionRequest, FIX8::TEX::MassQuoteAcknowledgement, FIX8::TEX::QuoteStatusRequest, FIX8::TEX::QuoteCancel, FIX8::TEX::MarketDataRequestReject, FIX8::TEX::MarketDataIncrementalRefresh, FIX8::TEX::MarketDataSnapshotFullRefresh, FIX8::TEX::MarketDataRequest, FIX8::TEX::SettlementInstructions, FIX8::TEX::Quote, FIX8::TEX::QuoteRequest, FIX8::TEX::DontKnowTrade, FIX8::TEX::AllocationInstructionAck, FIX8::TEX::ListStatus, FIX8::TEX::ListStatusRequest, FIX8::TEX::ListExecute, FIX8::TEX::ListCancelRequest, FIX8::TEX::AllocationInstruction, FIX8::TEX::OrderStatusRequest, FIX8::TEX::OrderCancelReplaceRequest, FIX8::TEX::OrderCancelRequest, FIX8::TEX::NewOrderList, FIX8::TEX::NewOrderSingle, FIX8::TEX::PartyDetailsListReport, FIX8::TEX::PartyDetailsListRequest, FIX8::TEX::StreamAssignmentReportACK, FIX8::TEX::StreamAssignmentReport, FIX8::TEX::StreamAssignmentRequest, FIX8::TEX::UserNotification, FIX8::TEX::OrderMassActionRequest, FIX8::TEX::Email, FIX8::TEX::OrderMassActionReport, FIX8::TEX::ApplicationMessageReport, FIX8::TEX::ApplicationMessageRequestAck, FIX8::TEX::ApplicationMessageRequest, FIX8::TEX::MarketDefinitionUpdateReport, FIX8::TEX::MarketDefinition, FIX8::TEX::MarketDefinitionRequest, FIX8::TEX::TradingSessionListUpdateReport, FIX8::TEX::DerivativeSecurityListUpdateReport, FIX8::TEX::SettlementObligationReport, FIX8::TEX::SecurityDefinitionUpdateReport, FIX8::TEX::ContraryIntentionReport, FIX8::TEX::ExecutionAcknowledgement, FIX8::TEX::AllocationInstructionAlert, FIX8::TEX::AdjustedPositionReport, FIX8::TEX::SecurityListUpdateReport, FIX8::TEX::TradingSessionList, FIX8::TEX::TradingSessionListRequest, FIX8::TEX::ConfirmationRequest, FIX8::TEX::CollateralInquiryAck, FIX8::TEX::UserResponse, FIX8::TEX::UserRequest, FIX8::TEX::NetworkCounterpartySystemStatusResponse, FIX8::TEX::NetworkCounterpartySystemStatusRequest, FIX8::TEX::CollateralInquiry, FIX8::TEX::CollateralReport, FIX8::TEX::News, FIX8::TEX::CollateralResponse, FIX8::TEX::CollateralAssignment, FIX8::TEX::CollateralRequest, FIX8::TEX::AssignmentReport, FIX8::TEX::SettlementInstructionRequest, FIX8::TEX::ConfirmationAck, FIX8::TEX::AllocationReportAck, FIX8::TEX::AllocationReport, FIX8::TEX::TradeCaptureReportAck, FIX8::TEX::TradeCaptureReportRequestAck, FIX8::TEX::PositionReport, FIX8::TEX::RequestForPositionsAck, FIX8::TEX::RequestForPositions, FIX8::TEX::PositionMaintenanceReport, FIX8::TEX::PositionMaintenanceRequest, FIX8::TEX::Confirmation, FIX8::TEX::QuoteResponse, FIX8::TEX::QuoteStatusReport, FIX8::TEX::RFQRequest, FIX8::TEX::QuoteRequestReject, FIX8::TEX::OrderMassStatusRequest, FIX8::TEX::TradeCaptureReport, FIX8::TEX::TradeCaptureReportRequest, FIX8::TEX::MultilegOrderCancelReplace, FIX8::TEX::NewOrderMultileg, FIX8::TEX::DerivativeSecurityList, FIX8::TEX::Logon, FIX8::TEX::OrderCancelReject, FIX8::TEX::ExecutionReport, FIX8::TEX::Advertisement, FIX8::TEX::NewOrderSingle, FIX8::TEX::Logon, FIX8::TEX::IOI, FIX8::TEX::ExecutionReport, FIX8::TEX::Logout, FIX8::TEX::Logout, FIX8::TEX::SequenceReset, FIX8::TEX::SequenceReset, FIX8::TEX::Reject, FIX8::TEX::Reject, FIX8::TEX::ResendRequest, FIX8::TEX::ResendRequest, FIX8::TEX::TestRequest, FIX8::TEX::TestRequest, FIX8::TEX::Heartbeat, and FIX8::TEX::Heartbeat.
Definition at line 1097 of file message.hpp.
Referenced by myfix_session_client::handle_application(), hf_session_client::handle_application(), myfix_session_server::handle_application(), and hf_session_server::handle_application().
 { return (rt)(this); }
void FIX8::Message::push_unknown (Message * to) const inline
Copy _unknown string from this message to given message
Definition at line 1207 of file message.hpp.
References _header, _trailer, and FIX8::MessageBase::push_unknown().
    {
       if (_header)
          _header->push_unknown(to->_header);
       MessageBase::push_unknown(to);
       if (_trailer)
          _trailer->push_unknown(to->_trailer);
    }
virtual void FIX8::Message::set_custom_seqnum (unsigned seqnum) inline virtual
Set the custom sequence number. Used to override and suppress automatic seqnum assignment.
Parameters
seqnum the outbound sequence number to use for this message.
Definition at line 1170 of file message.hpp.
References _custom_seqnum.
Referenced by FIX8::Session::send().
 { _custom_seqnum = seqnum; }
void FIX8::Message::set_end_of_batch (bool is_end_of_batch) inline
Set the end of batch flag
Parameters
is_end_of_batch true or false
Definition at line 1190 of file message.hpp.
References _end_of_batch.
Referenced by FIX8::FIXWriter::write_batch().
 { _end_of_batch = is_end_of_batch; }
virtual void FIX8::Message::set_no_increment (bool flag = true) inline virtual
Set the no increment flag.
Parameters
flag true means don't increment the seqnum after sending
Definition at line 1178 of file message.hpp.
References _no_increment.
Referenced by FIX8::Session::send().
 { _no_increment = flag; }
void FIX8::Message::setup_reuse () inline
Setup this message to allow it to be resused This feature is experimental; do not use with pipelined mode
Definition at line 1194 of file message.hpp.
References FIX8::MessageBase::_fp, _header, _trailer, FIX8::Common_BeginString(), FIX8::Common_BodyLength(), FIX8::Common_CheckSum(), FIX8::Common_MsgSeqNum(), FIX8::MessageBase::remove(), FIX8::FieldTraits::set(), and FIX8::FieldTrait::suppress.
Referenced by MyMenu::new_order_single_recycled().
    {
       if (_header)
       {
          _header->_fp.set(Common_BeginString, FieldTrait::suppress);
          _header->_fp.set(Common_BodyLength, FieldTrait::suppress);
          delete _header->remove(Common_MsgSeqNum);
       }
       if (_trailer)
          _trailer->_fp.set(Common_CheckSum, FieldTrait::suppress);
    }
MessageBase* FIX8::Message::Trailer () const inline
Get a pointer to the message trailer.
Returns
pointer to trailer
Definition at line 1060 of file message.hpp.
References _trailer.
 { return _trailer; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Message & what) friend
Inserter friend.
Parameters
os stream to send to
what message
Returns
stream
Definition at line 1279 of file message.hpp.
 { what.print(os); return os; }
Member Data Documentation
unsigned FIX8::Message::_custom_seqnum protected
Definition at line 1024 of file message.hpp.
Referenced by get_custom_seqnum(), and set_custom_seqnum().
bool FIX8::Message::_end_of_batch protected
Definition at line 1025 of file message.hpp.
Referenced by get_end_of_batch(), and set_end_of_batch().
MessageBase* FIX8::Message::_header protected
Definition at line 1023 of file message.hpp.
Referenced by clear(), decode(), get_field_flattened(), Header(), push_unknown(), setup_reuse(), and ~Message().
bool FIX8::Message::_no_increment protected
Definition at line 1025 of file message.hpp.
Referenced by get_no_increment(), and set_no_increment().
MessageBase * FIX8::Message::_trailer protected
Definition at line 1023 of file message.hpp.
Referenced by clear(), decode(), get_field_flattened(), push_unknown(), setup_reuse(), Trailer(), and ~Message().
The documentation for this class was generated from the following files:
message.hpp
message.cpp