fix8: ff::ff_dinout< CommImplIn, CommImplOut > Class Template Reference
ff::ff_dinout< CommImplIn, CommImplOut > Class Template Reference
A ff_dnode with both input and output channels.
#include <dinout.hpp>
Public Types
enum { SENDER =true, RECEIVER =false }
typedef
CommImpl::TransportImpl::msg_t msg_t
Public Types inherited from ff::ff_dnode< CommImplIn >
enum
typedef
CommImplIn::TransportImpl::msg_t msg_t
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Public Member Functions
int initIn (const std::string &name, const std::string &address, const int peers, typename CommImpl::TransportImpl *const transp, const int nodeId=-1)
virtual void prepare (svector< iovec > &v, void *ptr, const int sender=-1)
virtual void prepare (svector< msg_t * > *&v, size_t len, const int sender=-1)
virtual void unmarshalling (svector< msg_t * > *const v[], const int vlen, void *&task)
void setCallbackArg (void *arg)
int run (bool=false)
int wait ()
Waits the thread to finish.
void skipfirstpop (bool sk)
int initIn (const std::string &name, const std::string &address, const int peers, typename CommImplIn::TransportImpl *const transp, const int nodeId=-1)
Initializes input communication channels.
int initOut (const std::string &name, const std::string &address, const int peers, typename CommImplOut::TransportImpl *const transp, const int nodeId=-1, dnode_cbk_t cbk=0)
Initializes the output communicaiton channels.
Public Member Functions inherited from ff::ff_dnode< CommImplIn >
int init (const std::string &name, const std::string &address, const int peers, typename CommImplIn::TransportImpl *const transp, const bool p, const int nodeId=-1, dnode_cbk_t cbk=0)
Initializes external communication channel.
virtual void prepare (svector< msg_t * > *&v, size_t len, const int sender=-1)
Prepars a pool of messages.
virtual void unmarshalling (svector< msg_t * > *const v[], const int vlen, void *&task)
Unmarshalling.
void setCallbackArg (void *arg)
Sets call back arguments.
int run (bool=false)
Executes the FastFlow dnode.
int wait ()
Waits the FastFlow node.
void skipfirstpop (bool sk)
Skips first pop.
Public Member Functions inherited from ff::ff_node
virtual void * svc (void *task)=0
The svc method.
virtual int svc_init ()
The svc_init()
virtual void svc_end ()
The svc_end()
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Protected Types
typedef
CommImplOut::TransportImpl::msg_t msg_t
Protected Member Functions
bool isEos (const char data[msg_t::HEADER_LENGHT]) const
ff_dnode ()
Default constructor.
virtual ~ff_dnode ()
Destructor: closes all connections.
virtual bool push (void *ptr)
virtual bool pop (void **ptr)
virtual ~ff_dinout ()
Destructor.
virtual bool push (void *ptr)
Pushes the task.
Protected Member Functions inherited from ff::ff_dnode< CommImplIn >
bool isEos (const char data[msg_t::HEADER_LENGTH]) const
Checks EOS.
ff_dnode ()
Constructor.
bool internal_push (void *ptr, CI &comm)
Defines internal push.
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual int cardinality (BARRIER_T *const b)
Counts how many threads there are in this node.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Static Protected Member Functions
static void freeMsg (void *data, void *arg)
static void freeHdr (void *data, void *)
Static Protected Member Functions inherited from ff::ff_dnode< CommImplIn >
static void freeMsg (void *data, void *arg)
Free the message.
static void freeHdr (void *data, void *)
Frees header.
Protected Attributes
bool skipdnode
bool P
int neos
svector< void * > callbackArg
CommImpl com
CommImplOut comOut
Protected Attributes inherited from ff::ff_dnode< CommImplIn >
bool skipdnode
bool P
int neos
svector< void * > callbackArg
CommImplIn com
Static Protected Attributes
static dnode_cbk_t cb
Static Protected Attributes inherited from ff::ff_dnode< CommImplIn >
static dnode_cbk_t cb
Detailed Description
template<typename CommImplIn, typename CommImplOut>
class ff::ff_dinout< CommImplIn, CommImplOut >
A ff_dnode with both input and output channels.
A ff_dinout is actually a ff_dnode with an extra communication channel (external channel), so that the dinout node is connected with the "external world" both with input and output channels.
It is implemented as a template class: the template type CommImplIn refers to the input communication pattern, the type CommImplOut refers to the output communication pattern.
This class is defined in dnode.hpp
Definition at line 59 of file dinout.hpp.
Member Typedef Documentation
template<typename CommImplIn , typename CommImplOut > typedef CommImpl::TransportImpl::msg_t ff::ff_dinout< CommImplIn, CommImplOut >::msg_t
Definition at line 61 of file dinout.hpp.
template<typename CommImplIn , typename CommImplOut > typedef CommImplOut::TransportImpl::msg_t ff::ff_dinout< CommImplIn, CommImplOut >::msg_t protected
Defines the output communication
Definition at line 480 of file dnode.hpp.
Member Enumeration Documentation
template<typename CommImplIn , typename CommImplOut > anonymous enum
Enumerator
SENDER
RECEIVER
Definition at line 63 of file dinout.hpp.
Constructor & Destructor Documentation
template<typename CommImplIn , typename CommImplOut > virtual ff::ff_dinout< CommImplIn, CommImplOut >::~ff_dnode () inline protected virtual
Destructor: closes all connections.
Reimplemented from ff::ff_dnode< CommImplIn >.
Definition at line 85 of file dinout.hpp.
References ff::ff_dinout< CommImplIn, CommImplOut >::com.
template<typename CommImplIn , typename CommImplOut > virtual ff::ff_dinout< CommImplIn, CommImplOut >::~ff_dinout () inline protected virtual
Destructor.
It closes all connections.
Definition at line 487 of file dnode.hpp.
Member Function Documentation
template<typename CommImplIn , typename CommImplOut > ff::ff_dinout< CommImplIn, CommImplOut >::ff_dnode () inline protected
Default constructor.
Definition at line 82 of file dinout.hpp.
template<typename CommImplIn , typename CommImplOut > static void ff::ff_dinout< CommImplIn, CommImplOut >::freeHdr (void * data, void *) inline static protected
Definition at line 73 of file dinout.hpp.
References data.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename CommImplIn , typename CommImplOut > static void ff::ff_dinout< CommImplIn, CommImplOut >::freeMsg (void * data, void * arg) inline static protected
Definition at line 70 of file dinout.hpp.
References ff::ff_dinout< CommImplIn, CommImplOut >::cb.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::initIn (const std::string & name, const std::string & address, const int peers, typename CommImpl::TransportImpl *const transp, const int nodeId = -1) inline
The ff_dnode::init method initializes the external channel.
Parameters
name name of the channel
address the address where to listen or connect to
peers the number of peers
transp the transport layer to be used
p a flag saying whether the current dnode is the producer (p = true) or the consumer (p = false) w.r.t. the communication pattern used
nodeId the ID of the node
cbk the callback function that will be called once when a message just sent is no longer in use by the run-time
Definition at line 200 of file dinout.hpp.
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::initIn (const std::string & name, const std::string & address, const int peers, typename CommImplIn::TransportImpl *const transp, const int nodeId = -1) inline
Initializes input communication channels.
It initializes all the input communication channels.
name is the string to be passed through the communication channel address is the address of the destination peers are the number of peers involved in the communication transp is the transport for the communication nodeID is the identifer of the node
Returns
The status of com.init() method.
Definition at line 519 of file dnode.hpp.
References ff::ff_dnode< CommImpl >::init().
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::initOut (const std::string & name, const std::string & address, const int peers, typename CommImplOut::TransportImpl *const transp, const int nodeId = -1, dnode_cbk_t cbk = 0) inline
Initializes the output communicaiton channels.
It initializes all the output communication channels.
name is the string to be sent address is the address of the destination peers are the number of peers involve in the communication transp is the transport address nodeId is the identifier of the node cbk is the callback
Returns
The status of comOut.init() method.
Definition at line 545 of file dnode.hpp.
template<typename CommImplIn , typename CommImplOut > bool ff::ff_dinout< CommImplIn, CommImplOut >::isEos (const char data[msg_t::HEADER_LENGHT]) const inline protected
Definition at line 77 of file dinout.hpp.
References data.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop().
template<typename CommImplIn , typename CommImplOut > virtual bool ff::ff_dinout< CommImplIn, CommImplOut >::pop (void ** ptr) inline protected virtual
Override ff_node 's pop method
Reimplemented from ff::ff_dnode< CommImplIn >.
Definition at line 143 of file dinout.hpp.
References ff::ff_dinout< CommImplIn, CommImplOut >::com, ff::error(), ff::FF_EOS, ff::ff_dinout< CommImplIn, CommImplOut >::isEos(), ff::ff_dinout< CommImplIn, CommImplOut >::neos, ff::ff_dinout< CommImplIn, CommImplOut >::P, ff::ff_node::pop(), ff::ff_dinout< CommImplIn, CommImplOut >::prepare(), ff::ff_dinout< CommImplIn, CommImplOut >::skipdnode, and ff::ff_dinout< CommImplIn, CommImplOut >::unmarshalling().
template<typename CommImplIn , typename CommImplOut > virtual void ff::ff_dinout< CommImplIn, CommImplOut >::prepare (svector< iovec > & v, void * ptr, const int sender = -1) inline virtual
Used to prepare (non contiguous) output messages
Parameters
v is ...
ptr is ...
sender the message sender
Reimplemented from ff::ff_dnode< CommImplIn >.
Definition at line 216 of file dinout.hpp.
References ptr, ff::svector< T >::push_back(), and ff::ff_dinout< CommImplIn, CommImplOut >::setCallbackArg().
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename CommImplIn , typename CommImplOut > virtual void ff::ff_dinout< CommImplIn, CommImplOut >::prepare (svector< msg_t * > *& v, size_t len, const int sender = -1) inline virtual
Used to give to the run-time a pool of messages on which input message frames will be received
Parameters
len the number of input messages expected
sender the message sender
v vector containing the pool of messages
Definition at line 237 of file dinout.hpp.
References ff::svector< T >::push_back().
template<typename CommImplIn , typename CommImplOut > virtual bool ff::ff_dinout< CommImplIn, CommImplOut >::push (void * ptr) inline protected virtual
Override ff_node's push method
Reimplemented from ff::ff_dnode< CommImplIn >.
Definition at line 91 of file dinout.hpp.
References ff::ff_dinout< CommImplIn, CommImplOut >::callbackArg, ff::svector< T >::clear(), ff::ff_dinout< CommImplIn, CommImplOut >::com, ff::FF_DEOS, ff::FF_EOS, ff::ff_dinout< CommImplIn, CommImplOut >::freeHdr(), ff::ff_dinout< CommImplIn, CommImplOut >::freeMsg(), ff::ff_dinout< CommImplIn, CommImplOut >::P, ff::ff_dinout< CommImplIn, CommImplOut >::prepare(), ff::ff_node::push(), ff::svector< T >::resize(), ff::svector< T >::size(), and ff::ff_dinout< CommImplIn, CommImplOut >::skipdnode.
template<typename CommImplIn , typename CommImplOut > virtual bool ff::ff_dinout< CommImplIn, CommImplOut >::push (void * ptr) inline protected virtual
Pushes the task.
It overrides ff_dnode's push method.
ptr points to the task
Returns
The status of internal_push() method.
Reimplemented from ff::ff_dnode< CommImplIn >.
Definition at line 501 of file dnode.hpp.
References ff::ff_dnode< CommImpl >::internal_push().
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::run (bool = false) inline virtual
Runs the dnode as a stand-alone thread.
Typically, it should not be called by application code unless you want to have just a sequential dnode
Reimplemented from ff::ff_node.
Definition at line 271 of file dinout.hpp.
References ff::ff_node::run().
template<typename CommImplIn , typename CommImplOut > void ff::ff_dinout< CommImplIn, CommImplOut >::setCallbackArg (void * arg) inline
This methed can be used to pass an additional parameter (the 2nd one) to the callback function. Typically it is called in the prepare method of the producer.
Definition at line 264 of file dinout.hpp.
References ff::ff_dinout< CommImplIn, CommImplOut >::callbackArg, and ff::svector< T >::push_back().
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::prepare().
template<typename CommImplIn , typename CommImplOut > void ff::ff_dinout< CommImplIn, CommImplOut >::skipfirstpop (bool sk) inline virtual
jumps the first pop from the input queue or from the input external channel. This is typically used in the first stage of a cyclic graph (e.g. the first stage of a torus pipeline)
Reimplemented from ff::ff_node.
Definition at line 280 of file dinout.hpp.
References ff::ff_node::skipfirstpop().
template<typename CommImplIn , typename CommImplOut > virtual void ff::ff_dinout< CommImplIn, CommImplOut >::unmarshalling (svector< msg_t * > *const v[], const int vlen, void *& task) inline virtual
This method is called once, when all frames composing the message have been received by the run-time. Within that method, it is possible to convert or re-arrange all the frames back to their original data or object layout.
Definition at line 253 of file dinout.hpp.
References getData().
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop().
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::wait () inline virtual
Waits the thread to finish.
Reimplemented from ff::ff_node.
Definition at line 274 of file dinout.hpp.
References ff::ff_node::wait().
Member Data Documentation
template<typename CommImplIn , typename CommImplOut > svector<void*> ff::ff_dinout< CommImplIn, CommImplOut >::callbackArg protected
Definition at line 286 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::push(), and ff::ff_dinout< CommImplIn, CommImplOut >::setCallbackArg().
template<typename CommImplIn , typename CommImplOut > dnode_cbk_t ff::ff_dinout< CommImplIn, CommImplOut >::cb static protected
Definition at line 68 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::freeMsg().
template<typename CommImplIn , typename CommImplOut > CommImpl ff::ff_dinout< CommImplIn, CommImplOut >::com protected
Definition at line 287 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop(), ff::ff_dinout< CommImplIn, CommImplOut >::push(), and ff::ff_dinout< CommImplIn, CommImplOut >::~ff_dnode().
template<typename CommImplIn , typename CommImplOut > CommImplOut ff::ff_dinout< CommImplIn, CommImplOut >::comOut protected
Definition at line 558 of file dnode.hpp.
template<typename CommImplIn , typename CommImplOut > int ff::ff_dinout< CommImplIn, CommImplOut >::neos protected
Definition at line 285 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop().
template<typename CommImplIn , typename CommImplOut > bool ff::ff_dinout< CommImplIn, CommImplOut >::P protected
Definition at line 284 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename CommImplIn , typename CommImplOut > bool ff::ff_dinout< CommImplIn, CommImplOut >::skipdnode protected
Definition at line 283 of file dinout.hpp.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
The documentation for this class was generated from the following files:
dinout.hpp
dnode.hpp