fix8: FIX8::SessionManager< T > Class Template Reference
FIX8::SessionManager< T > Class Template Reference
Session Manager.
#include <multisession.hpp>
Public Member Functions
SessionManager ()=default
Ctor.
virtual ~SessionManager ()
Dtor.
bool add (const f8String &name, T *what)
T * for_each_if (std::function< bool(T *)> func)
bool remove (const f8String &name)
T * find (const f8String &name)
T * operator[] (const f8String &name) const
unsigned size () const
Private Attributes
f8_mutex _mutex
std::map< f8String, T * > _sessionmap
Detailed Description
template<typename T>
class FIX8::SessionManager< T >
Session Manager.
Definition at line 106 of file multisession.hpp.
Constructor & Destructor Documentation
template<typename T > FIX8::SessionManager< T >::SessionManager () default
Ctor.
template<typename T > virtual FIX8::SessionManager< T >::~SessionManager () inline virtual
Dtor.
Definition at line 116 of file multisession.hpp.
    {
       f8_scoped_lock guard(_mutex);
       std::for_each (_sessionmap.begin(), _sessionmap.end(), [](typename decltype(_sessionmap)::value_type& pp){ delete pp.second; });
    }
Member Function Documentation
template<typename T > bool FIX8::SessionManager< T >::add (const f8String & name, T * what) inline
Add a T* to the manager; takes ownership of the object
Parameters
name unique name for this session
what T* to add
Returns
true if successful
Definition at line 126 of file multisession.hpp.
Referenced by main().
    {
       if (!what)
          throw f8Exception("bad or missing session");
       f8_scoped_lock guard(_mutex);
       return _sessionmap.insert({name, what}).second;
    }
template<typename T > T* FIX8::SessionManager< T >::find (const f8String & name) inline
Find a session by session name
Parameters
name session name
Returns
T* or nullptr if not found
Definition at line 165 of file multisession.hpp.
Referenced by FIX8::SessionManager< T >::operator[]().
    {
       f8_scoped_lock guard(_mutex);
       const auto itr(_sessionmap.find(name));
       return itr == _sessionmap.cend() ? nullptr : itr->second;
    }
template<typename T > T* FIX8::SessionManager< T >::for_each_if (std::function< bool(T *)> func) inline
Call supplied function on each T* in the manager
Parameters
func std::function to call, which returns true on success
Returns
nullptr if all sessions executed successfully, or ptr to session that failed
Definition at line 137 of file multisession.hpp.
Referenced by main().
    {
       for (auto& pp : _sessionmap)
       {
          f8_scoped_lock guard(_mutex);
          if (!func(pp.second))
             return pp.second;
       }
       return nullptr;
    }
template<typename T > T* FIX8::SessionManager< T >::operator[] (const f8String & name) const inline
Find a session by session name, subscript operator version
Parameters
name session name
Returns
T* or nullptr if not found
Definition at line 175 of file multisession.hpp.
References FIX8::SessionManager< T >::find().
 { return find(name); }
template<typename T > bool FIX8::SessionManager< T >::remove (const f8String & name) inline
Remove a T* from the manager; destroys the object
Parameters
name session name
Returns
true if successful
Definition at line 151 of file multisession.hpp.
    {
       f8_scoped_lock guard(_mutex);
       auto itr(_sessionmap.find(name));
       if (itr == _sessionmap.end())
          return false;
       delete itr->second;
       _sessionmap.erase(itr);
       return true;
    }
template<typename T > unsigned FIX8::SessionManager< T >::size () const inline
Get the number of sessions being manager by this object
Returns
count of sessions
Definition at line 179 of file multisession.hpp.
 { return static_cast<unsigned>(_sessionmap.size()); }
Member Data Documentation
template<typename T > f8_mutex FIX8::SessionManager< T >::_mutex private
Definition at line 108 of file multisession.hpp.
template<typename T > std::map<f8String, T*> FIX8::SessionManager< T >::_sessionmap private
Definition at line 109 of file multisession.hpp.
The documentation for this class was generated from the following file:
multisession.hpp