fix8: FIX8::RegMatch Class Reference
FIX8::RegMatch Class Reference
A class to contain regex matches using RegExp.
#include <f8utils.hpp>
Public Member Functions
RegMatch ()
Ctor.
virtual ~RegMatch ()
Ctor.
unsigned SubCnt () const
size_t SubSize (const int which=0) const
unsigned SubPos (const int which=0) const
Private Types
enum { SubLimit_ = 32 }
Maximum number of sub-expressions.
Private Attributes
regmatch_t subexprs_ [SubLimit_]
int subCnt_
Friends
class RegExp
Detailed Description
A class to contain regex matches using RegExp.
Definition at line 308 of file f8utils.hpp.
Member Enumeration Documentation
anonymous enum private
Maximum number of sub-expressions.
Enumerator
SubLimit_
Definition at line 312 of file f8utils.hpp.
 { SubLimit_ = 32 };
Constructor & Destructor Documentation
FIX8::RegMatch::RegMatch () inline
Ctor.
Definition at line 321 of file f8utils.hpp.
       : subexprs_(), subCnt_()
 #endif
     {}
virtual FIX8::RegMatch::~RegMatch () inline virtual
Ctor.
Definition at line 328 of file f8utils.hpp.
 {}
Member Function Documentation
unsigned FIX8::RegMatch::SubCnt () const inline
Get the number of sub-expressions found.
Returns
number of sub-expression
Definition at line 332 of file f8utils.hpp.
References subCnt_.
Referenced by FIX8::RegExp::Erase(), FIX8::RegExp::Replace(), and FIX8::RegExp::SubExpr().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       return subCnt_;
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       return static_cast<unsigned>(_matchVec.size());
 #endif
    }
unsigned FIX8::RegMatch::SubPos (const int which = 0) const inline
Get the starting offset of the specified sub-expression.
Parameters
which sub-expression index (0 based)
Returns
offset of the sub-expression, -1 if not found
Definition at line 356 of file f8utils.hpp.
Referenced by FIX8::RegExp::Erase(), FIX8::RegExp::Replace(), and FIX8::RegExp::SubExpr().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       return which < subCnt_ ? subexprs_[which].rm_so : -1;
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       return which < static_cast<int>(_matchVec.size()) ? static_cast<int>(_matchVec[which].offset) : -1;
 #endif
    }
size_t FIX8::RegMatch::SubSize (const int which = 0) const inline
Get the size (length) of the specified sub-expression.
Parameters
which sub-expression index (0 based)
Returns
size of sub-expression, -1 if not found
Definition at line 344 of file f8utils.hpp.
Referenced by FIX8::RegExp::Erase(), FIX8::RegExp::Replace(), and FIX8::RegExp::SubExpr().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       return which < subCnt_ ? subexprs_[which].rm_eo - subexprs_[which].rm_so : -1;
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       return which < static_cast<int>(_matchVec.size()) ? _matchVec[which].length : -1;
 #endif
    }
Friends And Related Function Documentation
friend class RegExp friend
Definition at line 365 of file f8utils.hpp.
Member Data Documentation
int FIX8::RegMatch::subCnt_ private
Definition at line 314 of file f8utils.hpp.
Referenced by FIX8::RegExp::Erase(), FIX8::RegExp::Replace(), FIX8::RegExp::SearchString(), SubCnt(), and FIX8::RegExp::SubExpr().
regmatch_t FIX8::RegMatch::subexprs_[SubLimit_] private
Definition at line 313 of file f8utils.hpp.
Referenced by FIX8::RegExp::Erase(), FIX8::RegExp::Replace(), FIX8::RegExp::SearchString(), and FIX8::RegExp::SubExpr().
The documentation for this class was generated from the following file:
f8utils.hpp