fix8: ff::zmqFromAny Class Reference
ff::zmqFromAny Class Reference
It provides implementation of the collect from ANY communication pattern.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 0 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
typedef msg_t tosend_t
typedef msg_t torecv_t
typedef descriptorN_1 descriptor
Public Member Functions
zmqFromAny ()
zmqFromAny (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const msg_t &msg, const int)
bool putmore (const tosend_t &msg, const int)
bool gethdr (msg_t &msg, int &peer)
bool get (msg_t &msg, int &peer)
bool get (msg_t &msg)
int getToWait () const
int putToPerform () const
void done ()
bool close ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
It provides implementation of the collect from ANY communication pattern.
This class is defined in zmqImpl.hpp
Definition at line 1338 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptorN_1 ff::zmqFromAny::descriptor
Definition at line 1344 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmqFromAny::msg_t
Definition at line 1340 of file zmqImpl.hpp.
typedef msg_t ff::zmqFromAny::torecv_t
Definition at line 1343 of file zmqImpl.hpp.
typedef msg_t ff::zmqFromAny::tosend_t
Definition at line 1342 of file zmqImpl.hpp.
typedef zmqTransport ff::zmqFromAny::TransportImpl
Definition at line 1341 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 1346 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmqFromAny::zmqFromAny () inline
Definition at line 1348 of file zmqImpl.hpp.
ff::zmqFromAny::zmqFromAny (descriptor * D) inline
Definition at line 1349 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmqFromAny::close () inline
It closes communication pattern.
Returns
TODO
Definition at line 1486 of file zmqImpl.hpp.
References active, ff::descriptorN_1::close(), and desc.
void ff::zmqFromAny::done () inline
It performs the completion operation.
Definition at line 1479 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::done().
bool ff::zmqFromAny::get (msg_t & msg, int & peer) inline
It receives one message.
msg is the reference to the message. peer is the number of peers.
Returns
TODO
Definition at line 1446 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::recv().
bool ff::zmqFromAny::get (msg_t & msg) inline
It receives one message.
Parameters
msg is the reference to the message.
Returns
TODO
Definition at line 1457 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::recv().
descriptor* ff::zmqFromAny::getDescriptor () inline
It returns the descriptor.
Returns
TODO
Definition at line 1366 of file zmqImpl.hpp.
References desc.
bool ff::zmqFromAny::gethdr (msg_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg is the reference to the message. peer is the number of peers.
Returns
TODO
Definition at line 1434 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::recvhdr().
int ff::zmqFromAny::getToWait () const inline
It places the node in the waiting state.
Returns
TODO
Definition at line 1467 of file zmqImpl.hpp.
bool ff::zmqFromAny::init (const std::string & address, const int nodeId = -1) inline
It initializes communication pattern.
address
Parameters
nodeID
Returns
TODO
Definition at line 1376 of file zmqImpl.hpp.
References active, desc, and ff::descriptorN_1::init().
bool ff::zmqFromAny::put (const tosend_t & msg) inline
It sends one message.
msg is the reference to the message.
Returns
TODO
Definition at line 1389 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::send().
bool ff::zmqFromAny::put (const msg_t & msg, const int) inline
It places a message in the node.
msg is the reference to the message.
Returns
TODO
Definition at line 1411 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::send().
bool ff::zmqFromAny::putmore (const tosend_t & msg) inline
It put more messages.
msg is the reference to the message.
Returns
TODO
Definition at line 1400 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::send().
bool ff::zmqFromAny::putmore (const tosend_t & msg, const int) inline
It places more messages in the node.
msg is the reference to the message.
Returns
TODO
Definition at line 1422 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::send().
int ff::zmqFromAny::putToPerform () const inline
It places the node in the waiting state.
Returns
TODO
Definition at line 1474 of file zmqImpl.hpp.
void ff::zmqFromAny::setDescriptor (descriptor * D) inline
It sets the descriptor.
D is the descriptor.
Definition at line 1356 of file zmqImpl.hpp.
References ff::descriptorN_1::close(), and desc.
Member Data Documentation
bool ff::zmqFromAny::active protected
Definition at line 1495 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmqFromAny::desc protected
Definition at line 1494 of file zmqImpl.hpp.
Referenced by close(), done(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp