fix8: FIX8::f8Exception Class Reference
FIX8::f8Exception Class Reference
Base exception class.
#include <f8exception.hpp>
Public Member Functions
f8Exception (bool force_logoff=false)
f8Exception (const std::string &msg, bool force_logoff=false)
f8Exception (const char *msg, bool force_logoff=false)
template<typename T >
f8Exception (const std::string &msg, const T &val, bool force_logoff=false)
virtual ~f8Exception () throw ()
Dtor.
const char * what () const throw ()
const bool force_logoff () const
Protected Member Functions
template<typename T >
void format (const std::string &msg, const T what)
template<typename T , typename S >
void format (const std::string &msg, const T what, const std::string &msg2, const S what2)
Private Attributes
std::string _reason
bool _force_logoff
Detailed Description
Base exception class.
Definition at line 49 of file f8exception.hpp.
Constructor & Destructor Documentation
FIX8::f8Exception::f8Exception (bool force_logoff = false) inline
Ctor.
Parameters
force_logoff if true, logoff when thrown
Definition at line 57 of file f8exception.hpp.
FIX8::f8Exception::f8Exception (const std::string & msg, bool force_logoff = false) inline
Ctor.
Parameters
msg message associated with this exception
force_logoff if true, logoff when thrown
Definition at line 62 of file f8exception.hpp.
FIX8::f8Exception::f8Exception (const char * msg, bool force_logoff = false) inline
Ctor.
Parameters
msg message associated with this exception
force_logoff if true, logoff when thrown
Definition at line 68 of file f8exception.hpp.
template<typename T > FIX8::f8Exception::f8Exception (const std::string & msg, const T & val, bool force_logoff = false) inline
Ctor.
Template Parameters
T type of value to format
Parameters
msg message associated with this exception
val value to display with this exception
force_logoff if true, logoff when thrown
Definition at line 77 of file f8exception.hpp.
References format().
virtual FIX8::f8Exception::~f8Exception () throw () inline virtual
Dtor.
Definition at line 81 of file f8exception.hpp.
Member Function Documentation
const bool FIX8::f8Exception::force_logoff () const inline
Get the force logoff setting.
Returns
true if force logoff is set
Definition at line 89 of file f8exception.hpp.
References _force_logoff.
Referenced by FIX8::Session::process().
template<typename T > void FIX8::f8Exception::format (const std::string & msg, const T what) inline protected
Format a message to associate with this exception.
Template Parameters
T type of value to format
Parameters
msg message associated with this exception
what to display with this exception
Definition at line 97 of file f8exception.hpp.
References _reason, and what().
Referenced by FIX8::BadCheckSum::BadCheckSum(), FIX8::BadCompidId::BadCompidId(), FIX8::BadSendingTime::BadSendingTime(), FIX8::dthreadException::dthreadException(), FIX8::DuplicateField::DuplicateField(), f8Exception(), FIX8::IllegalMessage::IllegalMessage(), FIX8::InvalidBodyLength::InvalidBodyLength(), FIX8::InvalidConfiguration::InvalidConfiguration(), FIX8::InvalidDomainValue< T >::InvalidDomainValue(), FIX8::InvalidField::InvalidField(), FIX8::InvalidMessage::InvalidMessage(), FIX8::InvalidMetadata::InvalidMetadata(), FIX8::InvalidMsgSequence::InvalidMsgSequence(), FIX8::InvalidRepeatingGroup::InvalidRepeatingGroup(), FIX8::InvalidVersion::InvalidVersion(), FIX8::MissingMandatoryField::MissingMandatoryField(), FIX8::MissingMessageComponent::MissingMessageComponent(), FIX8::MissingRepeatingGroupField::MissingRepeatingGroupField(), FIX8::MsgSequenceTooLow::MsgSequenceTooLow(), FIX8::PeerResetConnection::PeerResetConnection(), and FIX8::XMLError::XMLError().
template<typename T , typename S > void FIX8::f8Exception::format (const std::string & msg, const T what, const std::string & msg2, const S what2) inline protected
Format a message to associate with this exception.
Template Parameters
T type of value to format
S type of 2nd value to format
Parameters
msg message associated with this exception
what to display with this exception
msg2 message associated with this exception
what2 to display with this exception
Definition at line 112 of file f8exception.hpp.
References _reason.
const char* FIX8::f8Exception::what () const throw () inline
Get message associated with this exception.
Returns
text message
Definition at line 85 of file f8exception.hpp.
References _reason.
Referenced by format(), main(), FIX8::FIXReader::operator()(), FIX8::ReliableClientSession< T >::operator()(), FIX8::FIXWriter::operator()(), FIX8::Session::process(), and FIX8::Session::send_process().
Member Data Documentation
bool FIX8::f8Exception::_force_logoff private
Definition at line 52 of file f8exception.hpp.
Referenced by force_logoff().
std::string FIX8::f8Exception::_reason private
Definition at line 51 of file f8exception.hpp.
Referenced by format(), and what().
The documentation for this class was generated from the following file:
f8exception.hpp