fix8: MyMenu Class Reference
MyMenu Class Reference
Simple menu system that will work with most term types.
#include <hftest.hpp>
Classes
struct MenuItem
Individual menu item.
Public Member Functions
MyMenu (FIX8::Session &session, int infd, std::ostream &ostr)
virtual ~MyMenu ()
std::istream & get_istr ()
std::ostream & get_ostr ()
bool process (char ch)
bool new_order_single ()
bool preload_new_order_single ()
bool batch_preload_new_order_single ()
bool multi_new_order_single ()
bool send_all_preloaded ()
bool send_all_preloaded (coroutine &coro, FIX8::Session *ses)
bool help ()
bool do_exit ()
bool do_logout ()
FIX8::tty_save_state & get_tty ()
MyMenu (FIX8::Session &session, int infd, std::ostream &ostr, FIX8::ConsoleMenu *cm=nullptr)
virtual ~MyMenu ()
std::istream & get_istr ()
std::ostream & get_ostr ()
bool process (char ch)
bool new_order_single ()
bool new_order_single_50 ()
bool new_order_single_1000 ()
bool resend_request ()
bool help ()
bool do_exit ()
bool do_logout ()
bool create_msgs ()
bool version_info ()
bool edit_msgs ()
bool delete_msg ()
bool delete_msgs ()
bool print_msgs ()
bool send_msgs ()
bool send_msg ()
bool write_msgs ()
bool read_msgs ()
bool set_lpp ()
bool toggle_heartbeats ()
bool static_probe ()
bool new_order_single_alternate ()
bool new_order_single_recycled ()
bool load_msgs (const std::string &fname)
FIX8::Message * generate_new_order_single ()
FIX8::Message * generate_new_order_single_alternate ()
void send_lst ()
bool save_msg (const std::string &fname, FIX8::Message *msg)
unsigned get_msg_cnt () const
FIX8::tty_save_state & get_tty ()
FIX8::f8String & get_string (FIX8::f8String &to)
Private Types
using Handlers = std::map< const MenuItem, bool(MyMenu::*)(), MenuItem >
using Handlers = std::map< const MenuItem, bool(MyMenu::*)(), MenuItem >
Private Attributes
FIX8::tty_save_state _tty
hf_session_client & _session
std::istream _istr
std::ostream & _ostr
FIX8::MsgList _lst
FIX8::ConsoleMenu * _cm
myfix_session_client & _session
Static Private Attributes
static const Handlers _handlers
Detailed Description
Simple menu system that will work with most term types.
Definition at line 151 of file hftest.hpp.
Member Typedef Documentation
using MyMenu::Handlers = std::map<const MenuItem, bool (MyMenu::*)(), MenuItem> private
Definition at line 170 of file hftest.hpp.
using MyMenu::Handlers = std::map<const MenuItem, bool (MyMenu::*)(), MenuItem> private
Definition at line 171 of file myfix.hpp.
Constructor & Destructor Documentation
MyMenu::MyMenu (FIX8::Session & session, int infd, std::ostream & ostr) inline
Definition at line 174 of file hftest.hpp.
       : _tty(infd), _session(static_cast<hf_session_client&>(session)),
       _istr(new FIX8::fdinbuf(infd)), _ostr(ostr) {}
virtual MyMenu::~MyMenu () inline virtual
Definition at line 177 of file hftest.hpp.
 {}
MyMenu::MyMenu (FIX8::Session & session, int infd, std::ostream & ostr, FIX8::ConsoleMenu * cm = nullptr) inline
Definition at line 175 of file myfix.hpp.
       : _tty(infd), _cm(cm), _session(static_cast<myfix_session_client&>(session)),
       _istr(new FIX8::fdinbuf(infd)), _ostr(ostr) {}
virtual MyMenu::~MyMenu () inline virtual
Definition at line 178 of file myfix.hpp.
 {}
Member Function Documentation
bool MyMenu::batch_preload_new_order_single ()
Definition at line 358 of file hftest.cpp.
References batch_size(), RandDev::getrandom(), FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION(), FIX8::TEX::OrdType_LIMIT(), preload_count(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_FILL_OR_KILL().
 {
    unsigned num(preload_count);
    if (!num)
    {
       cout << "Enter number of NewOrderSingle msgs to batch preload:";
       cout.flush();
       _tty.unset_raw_mode();
       cin >> num;
       _tty.set_raw_mode();
    }
    while (num > 0)
    {
       unsigned cnt(0);
       for (; cnt < num && cnt < batch_size; ++cnt)
       {
          static unsigned oid(10000);
          ostringstream oistr;
          oistr << "ord" << ++oid << '-' << num;
          FIX8::TEX::NewOrderSingle *ptr(new FIX8::TEX::NewOrderSingle);
          *ptr << new FIX8::TEX::Symbol("BHP")
               << new FIX8::TEX::HandlInst(FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION)
               << new FIX8::TEX::OrdType(FIX8::TEX::OrdType_LIMIT)
               << new FIX8::TEX::Side(FIX8::TEX::Side_BUY)
               << new FIX8::TEX::TimeInForce(FIX8::TEX::TimeInForce_FILL_OR_KILL)
               << new FIX8::TEX::TransactTime
               << new FIX8::TEX::ClOrdID(oistr.str())
               << new FIX8::TEX::Price(1. + RandDev::getrandom(500.), 3)
               << new FIX8::TEX::OrderQty(1 + RandDev::getrandom(10000));
 #if defined FIX8_PREENCODE_MSG_SUPPORT
          ptr->preencode();
 #endif
          _session.push(ptr);
       }
       cout << _session.cached() << " NewOrderSingle msgs preloaded." << endl;
       num -= cnt;
       send_all_preloaded();
    }
    return true;
 }
bool MyMenu::create_msgs ()
Definition at line 410 of file harness.cpp.
 {
    _cm->CreateMsgs(_tty, _lst);
    return true;
 }
bool MyMenu::delete_msg ()
Definition at line 433 of file harness.cpp.
 {
    _cm->DeleteMsgs(_tty, _lst);
    return true;
 }
bool MyMenu::delete_msgs ()
Definition at line 440 of file harness.cpp.
 {
    _cm->DeleteAllMsgs(_tty, _lst);
    return true;
 }
bool MyMenu::do_exit () inline
Definition at line 194 of file hftest.hpp.
 { return false; }
bool MyMenu::do_exit () inline
Definition at line 198 of file myfix.hpp.
 { return false; }
bool MyMenu::do_logout ()
Definition at line 367 of file harness.cpp.
References FIX8::hypersleep< h_seconds >().
 {
    if (!_session.is_shutdown())
    {
       _session.send(new TEX::Logout);
       get_ostr() << "logout..." << endl;
    }
    hypersleep<h_seconds>(1);
    return false; // will exit
 }
bool MyMenu::do_logout ()
bool MyMenu::edit_msgs ()
Definition at line 426 of file harness.cpp.
 {
    _cm->EditMsgs(_tty, _lst);
    return true;
 }
Message * MyMenu::generate_new_order_single ()
Definition at line 527 of file myfix.cpp.
References FIX8::GroupBase::create_group(), FIX8::MessageBase::find_group(), RandDev::getrandom(), FIX8::TEX::OrdType_LIMIT(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_FILL_OR_KILL().
 {
    static unsigned oid(0);
    ostringstream oistr;
    oistr << "ord" << ++oid;
    TEX::NewOrderSingle *nos(new TEX::NewOrderSingle);
    *nos << new TEX::TransactTime
         << new TEX::OrderQty(1 + RandDev::getrandom(9999))
         << new TEX::Price(RandDev::getrandom(500.), 5)   // 5 decimal places if necessary
         << new TEX::ClOrdID(oistr.str())
         << new TEX::Symbol("BHP")
         << new TEX::OrdType(TEX::OrdType_LIMIT)
         << new TEX::Side(TEX::Side_BUY)
         << new TEX::TimeInForce(TEX::TimeInForce_FILL_OR_KILL);
    *nos << new TEX::NoPartyIDs(unsigned(0));
    *nos << new TEX::NoUnderlyings(3);
    GroupBase *noul(nos->find_group<TEX::NewOrderSingle::NoUnderlyings>());
    // repeating groups
    MessageBase *gr1(noul->create_group());
    *gr1 << new TEX::UnderlyingSymbol("BLAH")
         << new TEX::UnderlyingQty(1 + RandDev::getrandom(999));
    *noul << gr1;
    MessageBase *gr2(noul->create_group());
    // nested repeating groups
    *gr2 << new TEX::UnderlyingSymbol("FOO")
         << new TEX::NoUnderlyingSecurityAltID(2);
    *noul << gr2;
    GroupBase *nosai(gr2->find_group<TEX::NewOrderSingle::NoUnderlyings::NoUnderlyingSecurityAltID>());
    MessageBase *gr3(nosai->create_group());
    *gr3 << new TEX::UnderlyingSecurityAltID("UnderBlah");
    *nosai << gr3;
    MessageBase *gr4(nosai->create_group());
    *gr4 << new TEX::UnderlyingSecurityAltID("OverFoo");
    *nosai << gr4;
    MessageBase *gr5(noul->create_group());
    *gr5 << new TEX::UnderlyingSymbol("BOOM");
    // nested repeating groups
    GroupBase *nus(gr5->find_group<TEX::NewOrderSingle::NoUnderlyings::NoUnderlyingStips>());
    static const char *secIDs[] { "Reverera", "Orlanda", "Withroon", "Longweed", "Blechnod" };
    *gr5 << new TEX::NoUnderlyingStips(sizeof(secIDs)/sizeof(char *));
    for (size_t ii(0); ii < sizeof(secIDs)/sizeof(char *); ++ii)
    {
       MessageBase *gr(nus->create_group());
       *gr << new TEX::UnderlyingStipType(secIDs[ii]);
       *nus << gr;
    }
    *noul << gr5;
    // multiply nested repeating groups
    *nos << new TEX::NoAllocs(1);
    GroupBase *noall(nos->find_group<TEX::NewOrderSingle::NoAllocs>());
    MessageBase *gr9(noall->create_group());
    *gr9 << new TEX::AllocAccount("Account1")
         << new TEX::NoNestedPartyIDs(1);
    *noall << gr9;
    GroupBase *nonp(gr9->find_group<TEX::NewOrderSingle::NoAllocs::NoNestedPartyIDs>());
    MessageBase *gr10(nonp->create_group());
    *gr10 << new TEX::NestedPartyID("nestedpartyID1")
          << new TEX::NoNestedPartySubIDs(1);
    *nonp << gr10;
    GroupBase *nonpsid(gr10->find_group<TEX::NewOrderSingle::NoAllocs::NoNestedPartyIDs::NoNestedPartySubIDs>());
    MessageBase *gr11(nonpsid->create_group());
    *gr11 << new TEX::NestedPartySubID("subnestedpartyID1");
    *nonpsid << gr11;
    return nos;
 }
Message * MyMenu::generate_new_order_single_alternate ()
Definition at line 454 of file myfix.cpp.
References FIX8::GroupBase::create_group(), FIX8::MessageBase::find_add_group(), RandDev::getrandom(), FIX8::TEX::OrdType_LIMIT(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_FILL_OR_KILL().
 {
    static unsigned oid(0);
    ostringstream oistr;
    oistr << "ord" << ++oid;
    TEX::NewOrderSingle *nos(new TEX::NewOrderSingle(false)); // shallow construction
    *nos << new TEX::TransactTime
         << new TEX::OrderQty(1 + RandDev::getrandom(9999))
         << new TEX::Price(RandDev::getrandom(500.), 5)   // 5 decimal places if necessary
         << new TEX::ClOrdID(oistr.str())
         << new TEX::Symbol("BHP")
         << new TEX::OrdType(TEX::OrdType_LIMIT)
         << new TEX::Side(TEX::Side_BUY)
         << new TEX::TimeInForce(TEX::TimeInForce_FILL_OR_KILL);
    *nos << new TEX::NoPartyIDs(unsigned(0));
    *nos << new TEX::NoUnderlyings(3);
    GroupBase *noul(nos->find_add_group<TEX::NewOrderSingle::NoUnderlyings>(nullptr)); // no parent group
    // repeating groups
    MessageBase *gr1(noul->create_group(false)); // shallow construction
    *gr1 << new TEX::UnderlyingSymbol("BLAH")
         << new TEX::UnderlyingQty(1 + RandDev::getrandom(999));
    *noul << gr1;
    MessageBase *gr2(noul->create_group(false)); // shallow construction
    // nested repeating groups
    *gr2 << new TEX::UnderlyingSymbol("FOO")
         << new TEX::NoUnderlyingSecurityAltID(2);
    *noul << gr2;
    GroupBase *nosai(gr2->find_add_group<TEX::NewOrderSingle::NoUnderlyings::NoUnderlyingSecurityAltID>(noul)); // parent is noul
    MessageBase *gr3(nosai->create_group(false)); // shallow construction
    *gr3 << new TEX::UnderlyingSecurityAltID("UnderBlah");
    *nosai << gr3;
    MessageBase *gr4(nosai->create_group(false)); // shallow construction
    *gr4 << new TEX::UnderlyingSecurityAltID("OverFoo");
    *nosai << gr4;
    MessageBase *gr5(noul->create_group(false)); // shallow construction
    *gr5 << new TEX::UnderlyingSymbol("BOOM");
    // nested repeating groups
    GroupBase *nus(gr5->find_add_group<TEX::NewOrderSingle::NoUnderlyings::NoUnderlyingStips>(noul)); // parent is noul
    static const char *secIDs[] { "Reverera", "Orlanda", "Withroon", "Longweed", "Blechnod" };
    *gr5 << new TEX::NoUnderlyingStips(sizeof(secIDs)/sizeof(char *));
    for (size_t ii(0); ii < sizeof(secIDs)/sizeof(char *); ++ii)
    {
       MessageBase *gr(nus->create_group(false)); // shallow construction
       *gr << new TEX::UnderlyingStipType(secIDs[ii]);
       *nus << gr;
    }
    *noul << gr5;
    // multiply nested repeating groups
    *nos << new TEX::NoAllocs(1);
    GroupBase *noall(nos->find_add_group<TEX::NewOrderSingle::NoAllocs>(nullptr)); // no parent group
    MessageBase *gr9(noall->create_group(false)); // shallow construction
    *gr9 << new TEX::AllocAccount("Account1")
         << new TEX::NoNestedPartyIDs(1);
    *noall << gr9;
    GroupBase *nonp(gr9->find_add_group<TEX::NewOrderSingle::NoAllocs::NoNestedPartyIDs>(noall)); // parent is noall
    MessageBase *gr10(nonp->create_group(false)); // shallow construction
    *gr10 << new TEX::NestedPartyID("nestedpartyID1")
          << new TEX::NoNestedPartySubIDs(1);
    *nonp << gr10;
    GroupBase *nonpsid(gr10->find_add_group<TEX::NewOrderSingle::NoAllocs::NoNestedPartyIDs::NoNestedPartySubIDs>(nonp)); // parent is nonp
    MessageBase *gr11(nonpsid->create_group(false)); // shallow construction
    *gr11 << new TEX::NestedPartySubID("subnestedpartyID1");
    *nonpsid << gr11;
    return nos;
 }
std::istream& MyMenu::get_istr () inline
Definition at line 179 of file hftest.hpp.
References _istr.
 { return _istr; }
std::istream& MyMenu::get_istr () inline
Definition at line 180 of file myfix.hpp.
References _istr.
 { return _istr; }
unsigned MyMenu::get_msg_cnt () const inline
Definition at line 221 of file myfix.hpp.
 { return _lst.size(); }
std::ostream& MyMenu::get_ostr () inline
Definition at line 180 of file hftest.hpp.
References _ostr.
 { return _ostr; }
std::ostream& MyMenu::get_ostr () inline
Definition at line 181 of file myfix.hpp.
References _ostr.
 { return _ostr; }
FIX8::f8String& MyMenu::get_string (FIX8::f8String & to) inline
Definition at line 225 of file myfix.hpp.
References FIX8::tty_save_state::set_raw_mode(), and FIX8::tty_save_state::unset_raw_mode().
    {
       char buff[128] {};
       _tty.unset_raw_mode();
       _istr.getline(buff, sizeof(buff));
       _tty.set_raw_mode();
       return to = buff;
    }
FIX8::tty_save_state& MyMenu::get_tty () inline
Definition at line 197 of file hftest.hpp.
References _tty.
Referenced by main().
 { return _tty; }
FIX8::tty_save_state& MyMenu::get_tty () inline
Definition at line 223 of file myfix.hpp.
References _tty.
 { return _tty; }
bool MyMenu::help ()
Definition at line 345 of file harness.cpp.
 {
    get_ostr() << endl;
    get_ostr() << "Key\tCommand" << endl;
    get_ostr() << "===\t=======" << endl;
    for (const auto& pp : _handlers)
       get_ostr() << pp.first._key << '\t' << pp.first._help << endl;
    get_ostr() << endl;
    return true;
 }
bool MyMenu::help ()
bool MyMenu::load_msgs (const std::string & fname)
Definition at line 533 of file harness.cpp.
References FIX8::Common_SendingTime(), FIX8::TEX::ctx(), FIX8_MAX_MSG_LENGTH, FIX8::MessageBase::get(), FIX8::Message::Header(), FIX8::Message::is_admin(), FIX8::MessageBase::remove(), FIX8::Message::setup_reuse(), and FIX8::Str_error().
 {
    ifstream ifs(fname.c_str());
    if (!ifs)
    {
       cerr << Str_error(errno, "Could not open file");
       return false;
    }
    char buffer[FIX8_MAX_MSG_LENGTH];
    unsigned loaded(0), skipped(0);
    while (!ifs.eof())
    {
       ifs.getline(buffer, FIX8_MAX_MSG_LENGTH - 1);
       if (!buffer[0])
          continue;
       Message *msg(Message::factory(TEX::ctx(), buffer));
       if (msg->is_admin())
       {
          ++skipped;
          continue;
       }
       sender_comp_id sci;
       msg->Header()->get(sci);
       target_comp_id tci;
       msg->Header()->get(tci);
       if (_session.get_sid().same_side_sender_comp_id(sci) && _session.get_sid().same_side_target_comp_id(tci))
       {
          ++loaded;
          delete msg->Header()->remove(Common_SendingTime); // will re-add on send
          msg->setup_reuse();
          _lst.push_back(msg);
       }
       else
          ++skipped;
    }
    _ostr << loaded << " msgs loaded, " << skipped << " msgs skipped" << endl;
    return true;
 }
bool MyMenu::multi_new_order_single ()
Definition at line 403 of file hftest.cpp.
 {
    cout << "Enter number of NewOrderSingle msgs to send:";
    cout.flush();
    unsigned num(0);
    _tty.unset_raw_mode();
    cin >> num;
    _tty.set_raw_mode();
    for (unsigned ii(0); ii < num; ++ii)
       new_order_single();
    cout << endl << num << " NewOrderSingle msgs sent" << endl;
    return true;
 }
bool MyMenu::new_order_single ()
Definition at line 419 of file hftest.cpp.
References RandDev::getrandom(), FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION(), FIX8::TEX::OrdType_LIMIT(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_FILL_OR_KILL().
 {
    static unsigned oid(0);
    ostringstream oistr;
    oistr << "ord" << ++oid;
    FIX8::TEX::NewOrderSingle *nos(new FIX8::TEX::NewOrderSingle);
    *nos  << new FIX8::TEX::TransactTime
          << new FIX8::TEX::OrderQty(1 + RandDev::getrandom(10000))
          << new FIX8::TEX::Price(1. + RandDev::getrandom(500.))
          << new FIX8::TEX::ClOrdID(oistr.str())
          << new FIX8::TEX::Symbol("BHP")
          << new FIX8::TEX::HandlInst(FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION)
          << new FIX8::TEX::OrdType(FIX8::TEX::OrdType_LIMIT)
          << new FIX8::TEX::Side(FIX8::TEX::Side_BUY)
          << new FIX8::TEX::TimeInForce(FIX8::TEX::TimeInForce_FILL_OR_KILL);
    _session.send(nos);
    return true;
 }
bool MyMenu::new_order_single ()
bool MyMenu::new_order_single_1000 ()
Definition at line 692 of file myfix.cpp.
 {
    vector<Message *> msgs;
    for (auto ii(0); ii < 1000; ++ii)
       msgs.push_back(generate_new_order_single());
    _session.send_batch(msgs);
    return true;
 }
bool MyMenu::new_order_single_50 ()
Definition at line 681 of file myfix.cpp.
 {
    vector<Message *> msgs;
    for (auto ii(0); ii < 50; ++ii)
       msgs.push_back(generate_new_order_single());
    _session.send_batch(msgs);
    return true;
 }
bool MyMenu::new_order_single_alternate ()
Definition at line 600 of file myfix.cpp.
 {
    _session.send(generate_new_order_single_alternate());
    return true;
 }
bool MyMenu::new_order_single_recycled ()
Definition at line 614 of file myfix.cpp.
References FIX8::Message::setup_reuse().
 {
    // create a message; first time through we just send it as normal. Note the we pass the no-destroy flag;
    // second and subsequent times we just recyle the old message
    static bool first(true);
    static Message *msg(0);
    if (first)
    {
       cout << "Sending new new_order_single" << endl;
       _session.send(msg = generate_new_order_single(), first = false);
    }
    else
    {
       msg->setup_reuse();
       cout << "Sending recycled new_order_single" << endl;
       _session.send(msg, false);
    }
 #if defined FIX8_RAW_MSG_SUPPORT
    // demonstrate access to outbound raw fix message and payload
    cout << msg->get_rawmsg() << endl;
    copy(msg->begin_payload(), msg->end_payload(), ostream_iterator<char>(cout, ""));
    cout << endl;
    cout << "payload begin=" << msg->get_payload_begin() << " payload len=" << msg->get_payload_len() << endl;
 #endif
    return true;
 }
bool MyMenu::preload_new_order_single ()
Definition at line 491 of file hftest.cpp.
References RandDev::getrandom(), FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION(), FIX8::TEX::OrdType_LIMIT(), preload_count(), FIX8::TEX::Side_BUY(), FIX8::MessageBase::size(), and FIX8::TEX::TimeInForce_FILL_OR_KILL().
Referenced by main().
 {
    cout << endl;
    if (_session.size())
       cout << _session.size() << " NewOrderSingle msgs currently preloaded." << endl;
    unsigned num(preload_count);
    if (!num)
    {
       cout << "Enter number of NewOrderSingle msgs to preload:";
       cout.flush();
       _tty.unset_raw_mode();
       cin >> num;
       _tty.set_raw_mode();
    }
    else
       cout << "loading..." << endl;
    for (unsigned ii(0); ii < num; ++ii)
    {
       static unsigned oid(10000);
       ostringstream oistr;
       oistr << "ord" << ++oid << '-' << num;
       FIX8::TEX::NewOrderSingle *ptr(new FIX8::TEX::NewOrderSingle);
       *ptr  << new FIX8::TEX::Symbol("BHP")
             << new FIX8::TEX::HandlInst(FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION)
             << new FIX8::TEX::OrdType(FIX8::TEX::OrdType_LIMIT)
             << new FIX8::TEX::Side(FIX8::TEX::Side_BUY)
             << new FIX8::TEX::TimeInForce(FIX8::TEX::TimeInForce_FILL_OR_KILL)
             << new FIX8::TEX::TransactTime
             << new FIX8::TEX::Price(1. + RandDev::getrandom(500.), 3) // precision=3
             << new FIX8::TEX::ClOrdID(oistr.str())
             << new FIX8::TEX::OrderQty(1 + RandDev::getrandom(10000));
 #if defined FIX8_PREENCODE_MSG_SUPPORT
       ptr->preencode(); // pre-encode message payload (not header or trailer)
 #endif
       _session.push(ptr);
    }
    cout << _session.size() << " NewOrderSingle msgs preloaded." << endl;
    return true;
 }
bool MyMenu::print_msgs ()
Definition at line 463 of file harness.cpp.
 {
    for (const auto *pp : _lst)
       _ostr << *pp << endl;
    return true;
 }
bool MyMenu::process (char ch) inline
Definition at line 181 of file hftest.hpp.
    {
       auto itr(_handlers.find({ch}));
       return itr == _handlers.end() ? true : (this->*itr->second)();
    }
bool MyMenu::process (char ch) inline
Definition at line 182 of file myfix.hpp.
    {
       auto itr(_handlers.find({ch}));
       if (itr == _handlers.end())
       {
          _ostr << "Command not found";
          return true;
       }
       return (this->*itr->second)();
    }
bool MyMenu::read_msgs ()
Definition at line 576 of file harness.cpp.
References FIX8_MAX_FLD_LENGTH.
 {
    char cwd[FIX8_MAX_FLD_LENGTH];
    _ostr << "Playback (*.playback) files in ";
 #ifdef _MSC_VER
    _ostr << _getcwd(cwd, sizeof(cwd)) << endl;
    if (system("dir *.playback"));
 #else
    _ostr << getcwd(cwd, sizeof(cwd)) << endl;
    if (system("ls -l *.playback"));
 #endif
    _ostr << endl;
    _ostr << "Enter filename: " << flush;
    string fname;
    if (!_cm->GetString(_tty, fname).empty())
       load_msgs(fname);
    return true;
 }
bool MyMenu::resend_request ()
Definition at line 727 of file myfix.cpp.
 {
    if (!_session.is_shutdown())
    {
       unsigned bnum(0), bend(0);
       cout << "Enter BeginSeqNo:" << flush;
       _tty.unset_raw_mode();
       cin >> bnum;
       cout << "Enter EndSeqNo(0=all):" << flush;
       cin >> bend;
       _tty.set_raw_mode();
       _session.send(_session.generate_resend_request(bnum, bend));
    }
    return true;
 }
bool MyMenu::save_msg (const std::string & fname, FIX8::Message * msg)
Definition at line 496 of file harness.cpp.
References FIX8::exist(), and FIX8::Str_error().
 {
 #if !defined FIX8_RAW_MSG_SUPPORT
    cerr << endl << "RAW_MSG_SUPPORT support not enabled. Run configure with --enable-rawmsgsupport" << endl;
 #else
    if (exist(fname))
       _ostr << endl << fname << " exists, will append message" << endl;
    ofstream ofs(fname.c_str(), ios::app);
    if (!ofs)
    {
       cerr << Str_error(errno, "Could not open file");
       return false;
    }
    ofs << msg->get_rawmsg() << endl; // requires fix8 built with --enable-rawmsgsupport
 #endif
    return true;
 }
bool MyMenu::send_all_preloaded ()
Definition at line 442 of file hftest.cpp.
References update_count().
 {
    const unsigned tosend(_session.size());
    cout << "Sending " << tosend << " NewOrderSingle msgs ..." << flush;
    unsigned snt(0);
    while (_session.cached())
    {
       FIX8::TEX::NewOrderSingle *ptr(_session.pop());
       if (!ptr)
          break;
       _session.send(ptr);
       if (++snt % update_count == 0)
       {
          cout << '\r' << snt << " NewOrderSingle msgs sent       ";
          cout.flush();
       }
    }
    cout << endl << snt << " NewOrderSingle msgs sent." << endl;
    return true;
 }
bool MyMenu::send_all_preloaded (coroutine & coro, FIX8::Session * ses)
Definition at line 464 of file hftest.cpp.
References batch_size(), coro_yield, FIX8::Session::get_connection(), reenter, FIX8::Connection::set_tcp_cork_flag(), and FIX8::Connection::writer_poll().
 {
    unsigned snt(0);
    FIX8::TEX::NewOrderSingle *ptr;
    reenter(coro)
    {
       ses->get_connection()->set_tcp_cork_flag(true);
       while (_session.cached())
       {
          if (ses->get_connection()->writer_poll())
          {
             if (!(ptr = _session.pop()))
                break;
             _session.send(ptr);
             if (++snt % batch_size)
                continue;
          }
          ses->get_connection()->set_tcp_cork_flag(false);
          coro_yield;
       }
    }
    ses->get_connection()->set_tcp_cork_flag(false);
    return _session.cached();
 }
void MyMenu::send_lst ()
Definition at line 447 of file harness.cpp.
 {
    for (auto *pp : _lst)
       _session.send(pp);
    _lst.clear();
 }
bool MyMenu::send_msg ()
Definition at line 471 of file harness.cpp.
 {
    unique_ptr<Message> msg(_cm->RemoveMsg(_tty, _lst));
    if (msg.get())
    {
       string fname;
       _ostr << endl;
       bool save(_cm->get_yn("Save message after send? (y/n):", true));
       _ostr << endl;
       if (save)
       {
          _ostr << "Enter filename: " << flush;
          _cm->GetString(_tty, fname);
       }
       if (_cm->get_yn("Send message? (y/n):", true))
       {
          _session.send(msg.get(), false);
          if (save && !fname.empty())
             save_msg(fname, msg.get());
       }
    }
    return true;
 }
bool MyMenu::send_msgs ()
Definition at line 455 of file harness.cpp.
 {
    if (_lst.size() && _cm->get_yn("Send messages? (y/n):", true))
       send_lst();
    return true;
 }
bool MyMenu::set_lpp ()
Definition at line 357 of file harness.cpp.
 {
    _ostr << "Enter number of lines per page (currently=" << _cm->get_lpp() << "): " << flush;
    f8String str;
    if (!_cm->GetString(_tty, str).empty())
       _cm->set_lpp(stoi(str));
    return true;
 }
bool MyMenu::static_probe ()
Definition at line 643 of file myfix.cpp.
References FIX8::BaseMsgEntry::_create, FIX8::BaseMsgEntry::_name, FIX8::BaseEntry::_name, and spacer.
 {
 #if defined FIX8_HAVE_EXTENDED_METADATA
    (cout << "Enter message tag:").flush();
    f8String result;
    const BaseMsgEntry *tbme;
    if (!get_string(result).empty() && (tbme = _session.get_ctx()._bme.find_ptr(result.c_str())))
    {
         function<void( const TraitHelper&, int )> print_traits;
       print_traits = ([&print_traits, this](const TraitHelper& tr, int depth)
       {
          const string spacer(depth * MessageBase::get_tabsize(), ' ');
          for (F8MetaCntx::const_iterator itr(F8MetaCntx::begin(tr)); itr != F8MetaCntx::end(tr); ++itr)
          {
             const BaseEntry *be(_session.get_ctx().find_be(itr->_fnum));
             cout << spacer << be->_name;
             if (be->_rlm)
                cout << " Realm:" << (be->_rlm->_dtype == RealmBase::dt_range ? "range" : "set")
                   << '(' << be->_rlm->_sz << ") ";
             cout << *itr << endl;
             if (itr->_field_traits.has(FieldTrait::group))
                print_traits(itr->_group, depth + 1);
          }
       });
       cout << tbme->_name << endl;
       print_traits(tbme->_create._get_traits(), 1);
    }
    else
       cout << "Unknown message tag: " << result << endl;
 #else
    cout << "Extended metadata not available (try ./configure --enable-extended-metadata=yes)." << endl;
 #endif
    return true;
 }
bool MyMenu::toggle_heartbeats ()
Definition at line 515 of file harness.cpp.
 {
    if (_session.control() & Session::printnohb)
    {
       _session.control().clear(Session::printnohb);
       _session.control().set(Session::print);
       get_ostr() << "Heartbeat display on";
    }
    else
    {
       _session.control().clear(Session::print);
       _session.control().set(Session::printnohb);
       get_ostr() << "Heartbeat display off";
    }
    return true;
 }
bool MyMenu::version_info ()
Definition at line 417 of file harness.cpp.
References FIX8::package_info().
 {
    _ostr << endl;
    for (const auto& pp : package_info())
       _ostr << pp.first << ": " << pp.second << endl;
    return true;
 }
bool MyMenu::write_msgs ()
Member Data Documentation
FIX8::ConsoleMenu* MyMenu::_cm private
Definition at line 154 of file myfix.hpp.
static const Handlers MyMenu::_handlers static private
Initial value:
{
   { { 'c', "Create messages" }, &MyMenu::create_msgs },
   { { 'e', "Edit messages" }, &MyMenu::edit_msgs },
   { { 'd', "Delete one message" }, &MyMenu::delete_msg },
   { { 'D', "Delete all messages" }, &MyMenu::delete_msgs },
   { { 'p', "Print messages" }, &MyMenu::print_msgs },
   { { 's', "Send messages" }, &MyMenu::send_msgs },
   { { 'r', "Read messages from disk" }, &MyMenu::read_msgs },
   { { 'S', "Send one message, optionally save before send" }, &MyMenu::send_msg },
   { { 't', "Toggle heartbeat message display" }, &MyMenu::toggle_heartbeats },
   { { '?', "Help" }, &MyMenu::help },
   { { 'l', "Logout" }, &MyMenu::do_logout },
   { { 'L', "Set Lines per page" }, &MyMenu::set_lpp },
   { { 'v', "Show version info" }, &MyMenu::version_info },
   { { 'x', "Exit" }, &MyMenu::do_exit },
}
Definition at line 171 of file hftest.hpp.
std::istream MyMenu::_istr private
Definition at line 167 of file hftest.hpp.
Referenced by get_istr().
FIX8::MsgList MyMenu::_lst private
Definition at line 153 of file myfix.hpp.
std::ostream & MyMenu::_ostr private
Definition at line 168 of file hftest.hpp.
Referenced by get_ostr().
hf_session_client& MyMenu::_session private
Definition at line 166 of file hftest.hpp.
myfix_session_client& MyMenu::_session private
Definition at line 167 of file myfix.hpp.
FIX8::tty_save_state MyMenu::_tty private
Definition at line 153 of file hftest.hpp.
Referenced by get_tty().
The documentation for this class was generated from the following files:
hftest.hpp
myfix.hpp
harness.cpp
hftest.cpp
myfix.cpp