fix8: ff::uMPMC_Ptr_Queue Class Reference
ff::uMPMC_Ptr_Queue Class Reference
An implementation of the unbounded Multi-Producer/Multi-Consumer queue.
#include <MPMCqueues.hpp>
Public Member Functions
uMPMC_Ptr_Queue ()
~uMPMC_Ptr_Queue ()
bool init (unsigned long nqueues=DEFAULT_NUM_QUEUES, size_t size=DEFAULT_uSPSC_SIZE)
bool push (void *const data)
bool pop (void **data)
Protected Types
enum { DEFAULT_NUM_QUEUES =4, DEFAULT_uSPSC_SIZE =2048 }
typedef void * data_element_t
typedef atomic_long_t sequenceP_t
typedef atomic_long_t sequenceC_t
Protected Attributes
data_element_t * buf
sequenceP_t * seqP
sequenceC_t * seqC
unsigned long mask
Private Attributes
atomic_long_t preadP
long padding1 [longxCacheLine-1]
atomic_long_t preadC
long padding2 [longxCacheLine-1]
Detailed Description
An implementation of the unbounded Multi-Producer/Multi-Consumer queue.
This class implements an unbounded MPMC queue which does not require any special memory allocator to avoid dangling pointers. The implementation blends together the MPMC_Ptr_Queue and the uSWSR_Ptr_Buffer.
It uses internal atomic operations.
This class is defined in MPMCqueues.hpp
Definition at line 421 of file MPMCqueues.hpp.
Member Typedef Documentation
typedef void* ff::uMPMC_Ptr_Queue::data_element_t protected
Definition at line 425 of file MPMCqueues.hpp.
typedef atomic_long_t ff::uMPMC_Ptr_Queue::sequenceC_t protected
Definition at line 427 of file MPMCqueues.hpp.
typedef atomic_long_t ff::uMPMC_Ptr_Queue::sequenceP_t protected
Definition at line 426 of file MPMCqueues.hpp.
Member Enumeration Documentation
anonymous enum protected
Enumerator
DEFAULT_NUM_QUEUES
DEFAULT_uSPSC_SIZE
Definition at line 423 of file MPMCqueues.hpp.
Constructor & Destructor Documentation
ff::uMPMC_Ptr_Queue::uMPMC_Ptr_Queue () inline
Constructor
Definition at line 433 of file MPMCqueues.hpp.
ff::uMPMC_Ptr_Queue::~uMPMC_Ptr_Queue () inline
Destructor
Definition at line 438 of file MPMCqueues.hpp.
References buf, freeAlignedMemory(), mask, seqC, and seqP.
Member Function Documentation
bool ff::uMPMC_Ptr_Queue::init (unsigned long nqueues = DEFAULT_NUM_QUEUES, size_t size = DEFAULT_uSPSC_SIZE) inline
TODO
Definition at line 453 of file MPMCqueues.hpp.
References buf, getAlignedMemory(), ff::isPowerOf2(), ff::longxCacheLine, mask, ff::nextPowerOf2(), preadC, preadP, seqC, and seqP.
Referenced by FIX8::ff_unbounded_queue< T >::ff_unbounded_queue(), and FIX8::ff_unbounded_queue< T * >::ff_unbounded_queue().
bool ff::uMPMC_Ptr_Queue::pop (void ** data) inline
non-blocking pop
Returns
TODO
Definition at line 505 of file MPMCqueues.hpp.
References BACKOFF_MAX, BACKOFF_MIN, buf, mask, preadC, seqC, and seqP.
Referenced by FIX8::ff_unbounded_queue< T >::try_pop(), and FIX8::ff_unbounded_queue< T * >::try_pop().
bool ff::uMPMC_Ptr_Queue::push (void *const data) inline
TODO
Returns
It always returns true
Definition at line 478 of file MPMCqueues.hpp.
References BACKOFF_MAX, BACKOFF_MIN, buf, mask, preadP, and seqP.
Referenced by FIX8::ff_unbounded_queue< T >::try_push(), and FIX8::ff_unbounded_queue< T * >::try_push().
Member Data Documentation
data_element_t* ff::uMPMC_Ptr_Queue::buf protected
Definition at line 536 of file MPMCqueues.hpp.
Referenced by init(), pop(), push(), and ~uMPMC_Ptr_Queue().
unsigned long ff::uMPMC_Ptr_Queue::mask protected
Definition at line 539 of file MPMCqueues.hpp.
Referenced by init(), pop(), push(), and ~uMPMC_Ptr_Queue().
long ff::uMPMC_Ptr_Queue::padding1[longxCacheLine-1] private
Definition at line 532 of file MPMCqueues.hpp.
long ff::uMPMC_Ptr_Queue::padding2[longxCacheLine-1] private
Definition at line 534 of file MPMCqueues.hpp.
atomic_long_t ff::uMPMC_Ptr_Queue::preadC private
Definition at line 533 of file MPMCqueues.hpp.
Referenced by init(), and pop().
atomic_long_t ff::uMPMC_Ptr_Queue::preadP private
Definition at line 531 of file MPMCqueues.hpp.
Referenced by init(), and push().
sequenceC_t* ff::uMPMC_Ptr_Queue::seqC protected
Definition at line 538 of file MPMCqueues.hpp.
Referenced by init(), pop(), and ~uMPMC_Ptr_Queue().
sequenceP_t* ff::uMPMC_Ptr_Queue::seqP protected
Definition at line 537 of file MPMCqueues.hpp.
Referenced by init(), pop(), push(), and ~uMPMC_Ptr_Queue().
The documentation for this class was generated from the following file:
MPMCqueues.hpp