fix8: ff::ff_oclNode Class Reference
ff::ff_oclNode Class Reference abstract
OpenCL implementation of FastFlow node.
#include <oclnode.hpp>
Public Member Functions
virtual void svc_SetUpOclObjects (cl_device_id id)=0
Setup OCL object.
virtual void svc_releaseOclObjects ()=0
Releases OCL object.
Public Member Functions inherited from ff::ff_node
virtual void * svc (void *task)=0
The svc method.
virtual int svc_init ()
The svc_init()
virtual void svc_end ()
The svc_end()
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
void reset ()
Resets input/output queues.
Public Member Functions inherited from Ocl_Utilities
Ocl_Utilities ()
void printStatus (std::string label, cl_int status)
void printErrorString (cl_int error)
Protected Member Functions
bool initOCLInstance ()
Intializes OpenCL instance.
ff_oclNode ()
Constructor.
bool device_rules (cl_device_id id)
Device rules.
void svc_createOCL ()
Creates OpenCL.
void svc_releaseOCL ()
Releases OpenCL.
bool evaluation ()
Evaluation.
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
virtual bool push (void *ptr)
Pushes to output buffer.
virtual bool pop (void **ptr)
Pops the data from input buffer.
virtual void skipfirstpop (bool sk)
Skips the first element popped.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int run (bool=false)
Executes the FastFlow thread.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait ()
Waits for thread termination.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual int cardinality (BARRIER_T *const b)
Counts how many threads there are in this node.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Private Attributes
int tId
cl_device_id baseclass_ocl_node_deviceId
Additional Inherited Members
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Detailed Description
OpenCL implementation of FastFlow node.
This class defines the OpenCL implementation of FastFlow node.
This class is defined in ff_oclnode.hpp
Definition at line 67 of file oclnode.hpp.
Constructor & Destructor Documentation
ff::ff_oclNode::ff_oclNode () inline protected
Constructor.
It construct the OpenCL node for the device.
Definition at line 113 of file oclnode.hpp.
Member Function Documentation
bool ff::ff_oclNode::device_rules (cl_device_id id) inline protected virtual
Device rules.
It defines the ruls for the device.
id is the identifier of the device
Returns
true is always returned
Implements Ocl_Utilities.
Definition at line 124 of file oclnode.hpp.
bool ff::ff_oclNode::evaluation () inline protected
Evaluation.
it evalautes the OpenCL node on the device.
Returns
If successful true, otherwise false
Definition at line 162 of file oclnode.hpp.
References baseclass_ocl_node_deviceId, Environment::instance(), Environment::reallocation(), and tId.
Referenced by svc_createOCL().
bool ff::ff_oclNode::initOCLInstance () inline protected
Intializes OpenCL instance.
It initializes the OpenCL instance.
Returns
If successful true is returned, otherwise false is returned.
Definition at line 98 of file oclnode.hpp.
References baseclass_ocl_node_deviceId, Environment::createEntry(), Environment::getDeviceId(), Environment::instance(), and tId.
Referenced by svc_createOCL().
void ff::ff_oclNode::svc_createOCL () inline protected virtual
Creates OpenCL.
It initializes OpenCL instance,
Reimplemented from ff::ff_node.
Definition at line 131 of file oclnode.hpp.
References baseclass_ocl_node_deviceId, ff::error(), evaluation(), initOCLInstance(), svc_releaseOclObjects(), and svc_SetUpOclObjects().
void ff::ff_oclNode::svc_releaseOCL () inline protected virtual
Releases OpenCL.
It releases OpenCL instance.
Reimplemented from ff::ff_node.
Definition at line 151 of file oclnode.hpp.
References svc_releaseOclObjects().
virtual void ff::ff_oclNode::svc_releaseOclObjects () pure virtual
Releases OCL object.
It is a pure virtual function, and releases the OpenCL object of the FastFlow node.
Referenced by svc_createOCL(), and svc_releaseOCL().
virtual void ff::ff_oclNode::svc_SetUpOclObjects (cl_device_id id) pure virtual
Setup OCL object.
It is a pure virtual function. It sets up the OpenCL object of the FastFlow node.
id is the identifier of the opencl device
Referenced by svc_createOCL().
Member Data Documentation
cl_device_id ff::ff_oclNode::baseclass_ocl_node_deviceId private
Definition at line 173 of file oclnode.hpp.
Referenced by evaluation(), initOCLInstance(), and svc_createOCL().
int ff::ff_oclNode::tId private
Definition at line 172 of file oclnode.hpp.
Referenced by evaluation(), and initOCLInstance().
The documentation for this class was generated from the following file:
oclnode.hpp