fix8: ff::zmqOnDemand Class Reference
ff::zmqOnDemand Class Reference
ZeroMQ implementation of the ON-DEMAND communication pattern.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 0 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
typedef msg_t tosend_t
typedef msg_t torecv_t
typedef descriptor1_N descriptor
Public Member Functions
zmqOnDemand ()
zmqOnDemand (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const tosend_t &msg, const int dest, int flag=0)
bool putmore (const tosend_t &msg, const int dest)
bool gethdr (torecv_t &msg, int &peer)
bool get (torecv_t &msg)
bool get (torecv_t &msg, int &peer)
bool close ()
int getToWait () const
void done ()
Protected Member Functions
bool sendReq ()
Protected Attributes
descriptor * desc
bool active
int to
int requestsToWait
bool requestSent
svector< bool > To
Detailed Description
ZeroMQ implementation of the ON-DEMAND communication pattern.
This class is defined in zmqImpl.hpp
Definition at line 1703 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptor1_N ff::zmqOnDemand::descriptor
Definition at line 1724 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmqOnDemand::msg_t
Definition at line 1720 of file zmqImpl.hpp.
typedef msg_t ff::zmqOnDemand::torecv_t
Definition at line 1723 of file zmqImpl.hpp.
typedef msg_t ff::zmqOnDemand::tosend_t
Definition at line 1722 of file zmqImpl.hpp.
typedef zmqTransport ff::zmqOnDemand::TransportImpl
Definition at line 1721 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 1725 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmqOnDemand::zmqOnDemand () inline
Constructur (1)
Definition at line 1731 of file zmqImpl.hpp.
ff::zmqOnDemand::zmqOnDemand (descriptor * D) inline
Constructor (2)
Definition at line 1737 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmqOnDemand::close () inline
It closes communication pattern.
Returns
TODO
Definition at line 1904 of file zmqImpl.hpp.
References active, ff::descriptor1_N::close(), desc, ff::descriptor1_N::getPeers(), ff::descriptor1_N::P, ff::descriptor1_N::recvReq(), requestsToWait, and To.
void ff::zmqOnDemand::done () inline
It completes the communication.
Definition at line 1930 of file zmqImpl.hpp.
References requestSent.
bool ff::zmqOnDemand::get (torecv_t & msg) inline
It receives one message part.
msg is the reference of the message.
Returns
TODO
Definition at line 1880 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::recv(), requestSent, and sendReq().
bool ff::zmqOnDemand::get (torecv_t & msg, int & peer) inline
It receives one message part.
msg is the reference of the message. peer is the number of peer.
Returns
TODO
Definition at line 1894 of file zmqImpl.hpp.
descriptor* ff::zmqOnDemand::getDescriptor () inline
It returns the descriptor.
Returns
TODO
Definition at line 1754 of file zmqImpl.hpp.
References desc.
bool ff::zmqOnDemand::gethdr (torecv_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg is the reference of the message. peer is the number of peers.
Returns
TODO
Definition at line 1866 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::recvhdr(), and sendReq().
int ff::zmqOnDemand::getToWait () const inline
It returns the number of distinct messages for one single communication.
Returns
1 is always returned.
Definition at line 1925 of file zmqImpl.hpp.
bool ff::zmqOnDemand::init (const std::string & address, const int nodeId = -1) inline
It initializes communication pattern.
address if the address of the node. nodeID is the addrecess of the receiving node.
Returns
TODO
Definition at line 1764 of file zmqImpl.hpp.
References active, desc, ff::descriptor1_N::getPeers(), ff::descriptor1_N::init(), ff::descriptor1_N::P, ff::svector< T >::resize(), sendReq(), and To.
bool ff::zmqOnDemand::put (const tosend_t & msg) inline
It sends one message.
msg is the reference of the message.
Returns
TODO
Definition at line 1784 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::recvReq(), ff::descriptor1_N::send(), and to.
Referenced by putmore().
bool ff::zmqOnDemand::put (const tosend_t & msg, const int dest, int flag = 0) inline
It places a message.
msg is the reference of the message. dest is the destination node. flag TODO
Returns
TODO
Definition at line 1816 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::copy(), desc, ff::descriptor1_N::getPeers(), ff::descriptor1_N::recvReq(), requestsToWait, ff::descriptor1_N::send(), to, and To.
bool ff::zmqOnDemand::putmore (const tosend_t & msg) inline
It sends one message, more messages have to come.
msg is the reference of the message.
Returns
TODO
Definition at line 1801 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::recvReq(), ff::descriptor1_N::sendmore(), and to.
bool ff::zmqOnDemand::putmore (const tosend_t & msg, const int dest) inline
It places many messages.
msg is the reference of the message. dest is the address of the destination.
Returns
TODO
Definition at line 1854 of file zmqImpl.hpp.
References put().
bool ff::zmqOnDemand::sendReq () inline protected
It defines the sending request.
Returns
TODO
Definition at line 1711 of file zmqImpl.hpp.
References desc, requestSent, and ff::descriptor1_N::sendReq().
Referenced by get(), gethdr(), and init().
void ff::zmqOnDemand::setDescriptor (descriptor * D) inline
Definition at line 1744 of file zmqImpl.hpp.
References ff::descriptor1_N::close(), and desc.
Member Data Documentation
bool ff::zmqOnDemand::active protected
Definition at line 1934 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmqOnDemand::desc protected
Definition at line 1933 of file zmqImpl.hpp.
Referenced by close(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), sendReq(), and setDescriptor().
bool ff::zmqOnDemand::requestSent protected
Definition at line 1937 of file zmqImpl.hpp.
Referenced by done(), get(), and sendReq().
int ff::zmqOnDemand::requestsToWait protected
Definition at line 1936 of file zmqImpl.hpp.
Referenced by close(), and put().
int ff::zmqOnDemand::to protected
Definition at line 1935 of file zmqImpl.hpp.
Referenced by put(), and putmore().
svector<bool> ff::zmqOnDemand::To protected
Definition at line 1938 of file zmqImpl.hpp.
Referenced by close(), init(), and put().
The documentation for this class was generated from the following file:
zmqImpl.hpp