fix8: ff::zmq1_N Class Reference
ff::zmq1_N Class Reference
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT =0 }
typedef zmqTransportMsg_t msg_t
typedef svector< msg_t > tosend_t
typedef msg_t torecv_t
typedef descriptor1_N descriptor
Public Member Functions
zmq1_N ()
zmq1_N (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool put (const msg_t &msg, const int to)
bool putmore (const msg_t &msg, const int to)
bool gethdr (torecv_t &msg, int &peer)
bool get (torecv_t &msg, int=0)
bool close ()
void done ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
Definition at line 1956 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptor1_N ff::zmq1_N::descriptor
Definition at line 1961 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmq1_N::msg_t
Definition at line 1958 of file zmqImpl.hpp.
typedef msg_t ff::zmq1_N::torecv_t
Definition at line 1960 of file zmqImpl.hpp.
typedef svector<msg_t> ff::zmq1_N::tosend_t
Definition at line 1959 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 1963 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmq1_N::zmq1_N () inline
Definition at line 1965 of file zmqImpl.hpp.
ff::zmq1_N::zmq1_N (descriptor * D) inline
Definition at line 1966 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmq1_N::close () inline
It closes communication pattern.
Returns
TODO
Definition at line 2063 of file zmqImpl.hpp.
References active, ff::descriptor1_N::close(), and desc.
void ff::zmq1_N::done () inline
It finishes the communicaiton.
Definition at line 2073 of file zmqImpl.hpp.
bool ff::zmq1_N::get (torecv_t & msg, int = 0) inline
It receives one message.
msg is the reference to the message
Returns
TODO
Definition at line 2056 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recv().
descriptor* ff::zmq1_N::getDescriptor () inline
It returns the descriptor.
Returns
Descriptor of the file is returned.
Definition at line 1983 of file zmqImpl.hpp.
References desc.
bool ff::zmq1_N::gethdr (torecv_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg is the reference to the message. peer is the number of peer.
Returns
TODO
Definition at line 2047 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recvhdr().
bool ff::zmq1_N::init (const std::string & address, const int nodeId = -1) inline
It initializes communication pattern.
address if the IP address nodeId is the address of the node
Returns
TODO
Definition at line 1993 of file zmqImpl.hpp.
References active, desc, and ff::descriptor1_N::init().
bool ff::zmq1_N::put (const tosend_t & msg) inline
It sends one message.
msg is the reference to the message.
Returns
TODO
Definition at line 2006 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::getPeers(), ff::descriptor1_N::send(), and ff::svector< T >::size().
bool ff::zmq1_N::put (const msg_t & msg, const int to) inline
It sends one message.
msgs is the reference to the message. to is the address of the receiving node.
Returns
TODO
Definition at line 2023 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmq1_N::putmore (const msg_t & msg, const int to) inline
It sends message to many nodes.
msg is the reference to the message. to is the address of the receiving node.
Returns
TODO
Definition at line 2035 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::sendmore().
void ff::zmq1_N::setDescriptor (descriptor * D) inline
It sets the descriptor.
D is the descriptor.
Definition at line 1973 of file zmqImpl.hpp.
References ff::descriptor1_N::close(), and desc.
Member Data Documentation
bool ff::zmq1_N::active protected
Definition at line 2077 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmq1_N::desc protected
Definition at line 2076 of file zmqImpl.hpp.
Referenced by close(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp