fix8: ff::SlabCache Class Reference
ff::SlabCache Class Reference
Cache of slab segments.
#include <allocator.hpp>
Public Member Functions
SlabCache (ff_allocator *const mainalloc, const int delayedReclaim, SegmentAllocator *const alloc, size_t sz, int ns)
~SlabCache ()
int init (bool prealloc=true)
xThreadData * register4free (const bool allocator=false)
void deregisterAllocator (const bool reclaim)
void * getitem ()
bool putitem (Buf_ctl *buf)
size_t getsize () const
Get the size of the SlabCache.
size_t getnslabs () const
Get the number of slabs in the cache.
size_t allocatedsize () const
Protected Attributes
size_t size
size_t nslabs
xThreadData ** fb
size_t fb_capacity
size_t fb_size
lock_t lock
Buf_ctl * buffptr
size_t availbuffers
Private Types
enum { TICKS_TO_WAIT =500, TICKS_CNT =3 }
enum { BUFFER_OVERHEAD =sizeof(Buf_ctl) }
enum { MIN_FB_CAPACITY =32 }
Private Member Functions
Seg_ctl * getsegctl (Buf_ctl *buf)
int newslab ()
void freeslab (void *ptr, bool seglist_rem=true)
bool checkReclaim (Seg_ctl *seg)
void checkReclaimD (Seg_ctl *seg)
void * getfrom_fb_delayed ()
void * getfrom_fb ()
int searchfb (const pthread_t key)
Private Attributes
atomic_long_t nomoremalloc
SegmentAllocator *const alloc
ff_allocator *const mainalloc
const int delayedReclaim
unsigned lastqueue
svector< void * > seglist
Detailed Description
Cache of slab segments.
A SlabCache is meant to keep commonly used object in an initialised state, available for use by kernel. Each cache contains blocks of contiguous pages in memory (i.e. slab segments).
Each slab segment consists of contiguous memory blocks, carved up into equal-size chunks, with a reference count to indicate the number of allocated chunks.
The SlabCache is used to implement the efficient lock-free allocator used in FastFlow (ff_allocator), which is based on the
Slab allocator
At the beginning of each segment there is a Seg_ctl structure, that is responsible for maintaining the linkage with other slabs in the cache, keeps track of the number of buffers in use and the number of available buffers.
Each buffer in the segment is managed by a Buf_ctl structure, that holds a back-pointer to the controlling slab.
This class is defined in file allocator.hpp
Definition at line 433 of file allocator.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
TICKS_TO_WAIT
TICKS_CNT
Definition at line 435 of file allocator.hpp.
anonymous enum private
Enumerator
BUFFER_OVERHEAD
Definition at line 436 of file allocator.hpp.
anonymous enum private
Enumerator
MIN_FB_CAPACITY
Definition at line 437 of file allocator.hpp.
Constructor & Destructor Documentation
ff::SlabCache::SlabCache (ff_allocator *const mainalloc, const int delayedReclaim, SegmentAllocator *const alloc, size_t sz, int ns) inline
Default Constructor
Parameters
mainalloc a pointer to the allocator used (must be of type ff_allocator).
delayedReclaim a flag to... REW
alloc a pointer to a SegmentAllocator object, used to obtain large (and possibly aligned) chunks of memory from the operating system.
sz the size of each buffer in a segment of the slab cache.
ns number of buffers (slabs) in each segment (note that, as the size of each buffer increases, the number of buffers in each segment decreases).
Definition at line 634 of file allocator.hpp.
Referenced by ff::ff_allocator::init().
ff::SlabCache::~SlabCache () inline
Destructor
Returns
TODO
Definition at line 645 of file allocator.hpp.
References ff::svector< T >::begin(), ff::svector< T >::clear(), ff::svector< T >::end(), fb, fb_size, freeslab(), nslabs, seglist, and ff::xThreadData::~xThreadData().
Member Function Documentation
size_t ff::SlabCache::allocatedsize () const inline
Definition at line 853 of file allocator.hpp.
References alloc, and ff::SegmentAllocator::getallocated().
Referenced by ff::ff_allocator::allocatedsize(), and ff::ffa_wrapper::free().
bool ff::SlabCache::checkReclaim (Seg_ctl * seg) inline private
This function is called when freeing a slab and the allocator has been deregistered. It checks whether the memory occupied by the slab segment given as argument can actually be deallocated. And this is possible when none of the slab buffers are in use. In this case, the memory occupied by the slab segment can be deallocated and the segment removed from the list of segments.
Returns
true if the operation suceeds; false otherwise.
Definition at line 531 of file allocator.hpp.
References ff::Seg_ctl::availbuffers, DBG, freeslab(), lock, nslabs, spin_lock(), and spin_unlock().
Referenced by deregisterAllocator(), and putitem().
void ff::SlabCache::checkReclaimD (Seg_ctl * seg) inline private
like the above, but No mutex here.
seg TODO
Definition at line 550 of file allocator.hpp.
References ff::Seg_ctl::availbuffers, freeslab(), and nslabs.
Referenced by getfrom_fb_delayed().
void ff::SlabCache::deregisterAllocator (const bool reclaim) inline
Deregister the allocator thread and reclaim memory
Definition at line 745 of file allocator.hpp.
References checkReclaim(), DBG, delayedReclaim, fb, fb_size, getsegctl(), nomoremalloc, nslabs, and ptr.
Referenced by ff::ff_allocator::deregisterAllocator().
void ff::SlabCache::freeslab (void * ptr, bool seglist_rem = true) inline private
Free a slab of memory previously allocated. This method frees the memory segment pointed by 'ptr'. The size of the freed memory is exactly the same size of the allocated segment: the size of the slab buffer times the num of slubs in the segment plus the segment overhead.
By default, the 'seglist_rem'' is set to true. It means that it has to remove the given pointer from the list of pointers that point to active memory chunks.
ptr TODO seglist_rem TODO
Returns
TODO
Definition at line 507 of file allocator.hpp.
References alloc, ff::svector< T >::begin(), BUFFER_OVERHEAD, DBG, ff::svector< T >::end(), ff::svector< T >::erase(), ff::SegmentAllocator::freesegment(), nslabs, ptr, seglist, and size.
Referenced by checkReclaim(), checkReclaimD(), and ~SlabCache().
void* ff::SlabCache::getfrom_fb () inline private
It tries to pop something out from the leak queue of one thread
Returns
TODO
Definition at line 592 of file allocator.hpp.
References ALLSTATS, fb, fb_size, and lastqueue.
Referenced by getitem().
void* ff::SlabCache::getfrom_fb_delayed () inline private
TOO
Returns
TODO
Definition at line 566 of file allocator.hpp.
References ALLSTATS, checkReclaimD(), DBG, delayedReclaim, fb, fb_size, getsegctl(), ff::xThreadData::leak, ff::uSWSR_Ptr_Buffer::pop(), and ptr.
Referenced by getitem().
void* ff::SlabCache::getitem () inline
Get an item from a Slab segment.
Returns
a pointer to the item obtained
Definition at line 771 of file allocator.hpp.
References ALLSTATS, ff::Seg_ctl::availbuffers, availbuffers, BUFFER_OVERHEAD, buffptr, DBG, delayedReclaim, getfrom_fb(), getfrom_fb_delayed(), getsegctl(), newslab(), nslabs, and size.
size_t ff::SlabCache::getnslabs () const inline
Get the number of slabs in the cache.
Definition at line 852 of file allocator.hpp.
References nslabs.
Referenced by ff::ff_allocator::malloc(), and ff::ff_allocator::posix_memalign().
Seg_ctl* ff::SlabCache::getsegctl (Buf_ctl * buf) inline private
Casts a Buffer controller to a Segment controller and return a pointer to it.
Returns
A pointer to the segment controller.
Definition at line 445 of file allocator.hpp.
Referenced by deregisterAllocator(), ff::FFAllocator::free(), getfrom_fb_delayed(), getitem(), and ff::ff_allocator::getslabs().
size_t ff::SlabCache::getsize () const inline
Get the size of the SlabCache.
Definition at line 850 of file allocator.hpp.
References size.
Referenced by ff::ff_allocator::growsup(), and ff::ff_allocator::realloc().
int ff::SlabCache::init (bool prealloc = true) inline
Initialise a new SlabCache.
This method creates a new slab, that is, it allocates space for an unbounded buffer built upon the uSWSR_Ptr_Buffer. Then it creates a new segment of large and (possibly) aligned memory. The initial size of the buffer - set to a minimum value equal to 32 - can be later increased, if necessary.
Parameters
prealloc flag that act as a mask against the creation of a new Slab. By default it is set to true.
Returns
0 if the creation of a new Slab succeedes and the prealloc mask is set to true OR if the creation of a new Slab fails and the prealloc mask is set to false. Gives a negative value otherwise.
Definition at line 679 of file allocator.hpp.
References fb, fb_capacity, init_unlocked(), lock, MIN_FB_CAPACITY, newslab(), nomoremalloc, and nslabs.
Referenced by ff::ff_allocator::init().
int ff::SlabCache::newslab () inline private
This method creates a new slab, that is, it allocates a new segment of large and possibly aligned memory.
Returns
0 if the creation of a new Slab succeedes; a negative value otherwise.
Allocate a large chunk of memory. The size of each chunk is equal to the size of the slab buffer times the num of slubs in the segment plus the segment overhead.
'alloc' is of type SegmentAllocator
If the allocation of the new segment succeedes, the pointer to the newly allocated segment of memory becomes the new Segment controller and all its embedded data are reset.
Definition at line 456 of file allocator.hpp.
References alloc, ff::Seg_ctl::allocator, ff::Seg_ctl::availbuffers, availbuffers, BUFFER_OVERHEAD, buffptr, ff::Seg_ctl::cacheentry, DBG, mainalloc, ff::SegmentAllocator::newsegment(), nslabs, ptr, ff::svector< T >::push_back(), seglist, and size.
Referenced by getitem(), and init().
bool ff::SlabCache::putitem (Buf_ctl * buf) inline
Push an item into the slab
Returns
false if the operation succedes; true if some memory has been reclaimed
If nomoremalloc is set to 1, it means the allocator has been deregistered and the memory in segment 'seg' could have been reclaimed.
If nomorealloc is 0,
Definition at line 821 of file allocator.hpp.
References checkReclaim(), DBG, delayedReclaim, fb, ff::xThreadData::leak, nomoremalloc, nslabs, pthread_self(), ff::uSWSR_Ptr_Buffer::push(), register4free(), and searchfb().
Referenced by ff::ff_allocator::free(), ff::ff_allocator::growsup(), and ff::ff_allocator::realloc().
xThreadData* ff::SlabCache::register4free (const bool allocator = false) inline
Register the calling thread into the shared buffer (leak queue).
In case the thread (ID) is already registered in the buffer, it returns a pointer to its position in the buffer. If it is not registered, then allocates space for a new thread's buffer and initialise the new buffer with the key of the new thread. The allocator flag is set to false.
Parameters
allocator true if the calling thread is the allocator thread; false by default.
Returns
a pointer to the allocated thread in the buffer.
Definition at line 706 of file allocator.hpp.
References DBG, fb, fb_capacity, fb_size, lock, MIN_FB_CAPACITY, nslabs, pthread_self(), searchfb(), spin_lock(), and spin_unlock().
Referenced by putitem().
int ff::SlabCache::searchfb (const pthread_t key) inline private
It search for a thread (ID) in the leak queue Returns a negative value if not found
Returns
TODO
Definition at line 613 of file allocator.hpp.
References fb, and fb_size.
Referenced by putitem(), and register4free().
Member Data Documentation
SegmentAllocator* const ff::SlabCache::alloc private
Definition at line 872 of file allocator.hpp.
Referenced by allocatedsize(), freeslab(), ff::ff_allocator::init(), newslab(), and ff::ff_allocator::~ff_allocator().
size_t ff::SlabCache::availbuffers protected
Definition at line 867 of file allocator.hpp.
Referenced by getitem(), and newslab().
Buf_ctl* ff::SlabCache::buffptr protected
Definition at line 866 of file allocator.hpp.
Referenced by getitem(), and newslab().
const int ff::SlabCache::delayedReclaim private
Definition at line 874 of file allocator.hpp.
Referenced by deregisterAllocator(), ff::FFAllocator::FFAllocator(), getfrom_fb_delayed(), getitem(), ff::ff_allocator::init(), ff::FFAllocator::newAllocator(), putitem(), and ff::FFAllocator::~FFAllocator().
xThreadData** ff::SlabCache::fb protected
Definition at line 861 of file allocator.hpp.
Referenced by deregisterAllocator(), getfrom_fb(), getfrom_fb_delayed(), init(), putitem(), register4free(), searchfb(), and ~SlabCache().
size_t ff::SlabCache::fb_capacity protected
Definition at line 862 of file allocator.hpp.
Referenced by init(), and register4free().
size_t ff::SlabCache::fb_size protected
Definition at line 863 of file allocator.hpp.
Referenced by deregisterAllocator(), getfrom_fb(), getfrom_fb_delayed(), register4free(), searchfb(), and ~SlabCache().
unsigned ff::SlabCache::lastqueue private
Definition at line 875 of file allocator.hpp.
Referenced by getfrom_fb().
lock_t ff::SlabCache::lock protected
Definition at line 864 of file allocator.hpp.
Referenced by checkReclaim(), ff::FFAllocator::deleteAllocator(), ff::FFAllocator::FFAllocator(), init(), ff::FFAllocator::malloc(), ff::FFAllocator::newAllocator(), ff::FFAllocator::posix_memalign(), and register4free().
ff_allocator* const ff::SlabCache::mainalloc private
Definition at line 873 of file allocator.hpp.
Referenced by newslab().
atomic_long_t ff::SlabCache::nomoremalloc private
Definition at line 870 of file allocator.hpp.
Referenced by deregisterAllocator(), init(), and putitem().
size_t ff::SlabCache::nslabs protected
Definition at line 859 of file allocator.hpp.
Referenced by checkReclaim(), checkReclaimD(), deregisterAllocator(), freeslab(), getitem(), getnslabs(), init(), ff::ff_allocator::init(), newslab(), putitem(), register4free(), and ~SlabCache().
svector<void *> ff::SlabCache::seglist private
Definition at line 876 of file allocator.hpp.
Referenced by freeslab(), newslab(), and ~SlabCache().
size_t ff::SlabCache::size protected
Definition at line 858 of file allocator.hpp.
Referenced by freeslab(), getitem(), getsize(), ff::ff_allocator::getslabs(), and newslab().
The documentation for this class was generated from the following file:
allocator.hpp