fix8: FIX8::Field< T, field > Class Template Reference
FIX8::Field< T, field > Class Template Reference
Field template. There will ONLY be partial template specialisations of this template.
#include <field.hpp>
Private Member Functions
Field ()=delete
Field (const Field &)=delete
Field & operator= (const Field &)=delete
Field (const f8String &, const RealmBase *)=delete
Additional Inherited Members
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
virtual std::ostream & print (std::ostream &os) const =0
virtual size_t print (char *to) const =0
virtual FieldTrait::FieldType get_underlying_type () const =0
virtual BaseField * copy ()=0
virtual int get_rlm_idx () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
virtual bool operator== (const BaseField &that) const =0
Equivalence operator.
virtual bool operator< (const BaseField &that) const =0
Less than operator.
virtual bool operator> (const BaseField &that) const =0
Greater than operator.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<typename T, unsigned short field>
class FIX8::Field< T, field >
Field template. There will ONLY be partial template specialisations of this template.
Template Parameters
T field type
field field number (fix tag)
Definition at line 256 of file field.hpp.
Constructor & Destructor Documentation
template<typename T, unsigned short field> FIX8::Field< T, field >::Field () private delete
Referenced by FIX8::Field< int, field >::copy(), FIX8::Field< f8String, field >::copy(), FIX8::Field< fp_type, field >::copy(), FIX8::Field< char, field >::copy(), FIX8::Field< UTCTimestamp, field >::copy(), FIX8::Field< UTCTimeOnly, field >::copy(), FIX8::Field< UTCDateOnly, field >::copy(), FIX8::Field< LocalMktDate, field >::copy(), FIX8::Field< MonthYear, field >::copy(), FIX8::Field< TZTimeOnly, field >::copy(), FIX8::Field< TZTimestamp, field >::copy(), and FIX8::Field< Boolean, field >::copy().
template<typename T, unsigned short field> FIX8::Field< T, field >::Field (const Field< T, field > &) private delete
template<typename T, unsigned short field> FIX8::Field< T, field >::Field (const f8String & , const RealmBase *) private delete
Member Function Documentation
template<typename T, unsigned short field> Field& FIX8::Field< T, field >::operator= (const Field< T, field > &) private delete
The documentation for this class was generated from the following file:
field.hpp