fix8: FIX8::ReliableClientSession< T > Class Template Reference
FIX8::ReliableClientSession< T > Class Template Reference
Reliable Client wrapper. This client attempts to recover from disconnects and login rejects.
#include <sessionwrapper.hpp>
Public Types
typedef scoped_ptr
< ReliableClientSession< T > > ReliableClient_ptr
Convenient scoped pointer for your session.
Public Types inherited from FIX8::ClientSession< T >
typedef scoped_ptr
< ClientSession< T > > Client_ptr
Convenient scoped pointer for your session.
Public Member Functions
ReliableClientSession (const F8MetaCntx &ctx, const std::string &conf_file, const std::string &session_name)
Ctor. Prepares session for connection as an initiator.
virtual ~ReliableClientSession ()
Dtor.
virtual void start (bool wait, const unsigned send_seqnum=0, const unsigned recv_seqnum=0, const f8String davi=f8String())
int operator() ()
Public Member Functions inherited from FIX8::ClientSession< T >
ClientSession (const F8MetaCntx &ctx, const std::string &conf_file, const std::string &session_name, bool init_con_later=false)
Ctor. Prepares session for connection as an initiator.
virtual ~ClientSession ()
Dtor.
T * session_ptr ()
Public Member Functions inherited from FIX8::SessionConfig
SessionConfig (const F8MetaCntx &ctx, const std::string &conf_file, const std::string &session_name)
Ctor. Loads configuration, obtains session details, sets up logfile flags.
virtual ~SessionConfig ()
Dtor.
const XmlElement * get_session_element () const
Public Member Functions inherited from FIX8::Configuration
Configuration (const std::string &xmlfile, bool do_process=false)
virtual ~Configuration ()
Dtor.
int process ()
const XmlElement * get_session (const unsigned num) const
const XmlElement * find_session (const std::string &tag) const
Connection::Role get_role (const XmlElement *from) const
Poco::Net::SocketAddress get_address (const XmlElement *from) const
Logger::LogFlags get_logflags (const XmlElement *from) const
std::string & get_logname (const XmlElement *from, std::string &to) const
unsigned get_retry_interval (const XmlElement *from, const unsigned def=5000) const
unsigned get_retry_count (const XmlElement *from, const unsigned def=10) const
unsigned get_version (const XmlElement *from) const
unsigned get_logfile_rotation (const XmlElement *from, const unsigned def=5) const
unsigned get_heartbeat_interval (const XmlElement *from) const
bool get_tcp_nodelay (const XmlElement *from)
bool get_reset_sequence_number_flag (const XmlElement *from)
default_appl_ver_id get_default_appl_ver_id (const XmlElement *from) const
sender_comp_id get_sender_comp_id (const XmlElement *from) const
target_comp_id get_target_comp_id (const XmlElement *from) const
Persister * create_persister (const XmlElement *from) const
Logger * create_logger (const XmlElement *from, const Logtype ltype) const
unsigned get_all_sessions (std::vector< const XmlElement * > &target, const Connection::Role role=Connection::cn_unknown) const
Private Attributes
Thread< ReliableClientSession
< T > > _thread
unsigned _send_seqnum
unsigned _recv_seqnum
Additional Inherited Members
Public Attributes inherited from FIX8::SessionConfig
const F8MetaCntx & _ctx
const XmlElement * _ses
Protected Attributes inherited from FIX8::ClientSession< T >
Logger * _log
Logger * _plog
sender_comp_id _sci
target_comp_id _tci
const SessionID _id
Persister * _persist
T * _session
Poco::Net::StreamSocket * _sock
Poco::Net::SocketAddress _addr
ClientConnection * _cc
Detailed Description
template<typename T>
class FIX8::ReliableClientSession< T >
Reliable Client wrapper. This client attempts to recover from disconnects and login rejects.
Template Parameters
T your derived session class
Definition at line 136 of file sessionwrapper.hpp.
Member Typedef Documentation
template<typename T> typedef scoped_ptr<ReliableClientSession<T> > FIX8::ReliableClientSession< T >::ReliableClient_ptr
Convenient scoped pointer for your session.
Definition at line 203 of file sessionwrapper.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::ReliableClientSession< T >::ReliableClientSession (const F8MetaCntx & ctx, const std::string & conf_file, const std::string & session_name) inline
Ctor. Prepares session for connection as an initiator.
Definition at line 143 of file sessionwrapper.hpp.
template<typename T> virtual FIX8::ReliableClientSession< T >::~ReliableClientSession () inline virtual
Dtor.
Definition at line 149 of file sessionwrapper.hpp.
Member Function Documentation
template<typename T> int FIX8::ReliableClientSession< T >::operator() () inline
The reliability thread entry point.
Returns
0 on success
Definition at line 168 of file sessionwrapper.hpp.
References FIX8::ClientSession< T >::_addr, FIX8::ClientSession< T >::_cc, FIX8::ReliableClientSession< T >::_recv_seqnum, FIX8::ReliableClientSession< T >::_send_seqnum, FIX8::ClientSession< T >::_session, FIX8::ClientSession< T >::_sock, FIX8::millisleep(), and FIX8::f8Exception::what().
template<typename T> virtual void FIX8::ReliableClientSession< T >::start (bool wait, const unsigned send_seqnum = 0, const unsigned recv_seqnum = 0, const f8String davi = f8String()) inline virtual
Start the session - initiate the connection, logon and start heartbeating.
Parameters
wait if true wait till session finishes before returning
send_seqnum next send seqnum (not used here)
recv_seqnum next recv seqnum (not used here)
davi default appl version id (FIXT)
Reimplemented from FIX8::ClientSession< T >.
Definition at line 156 of file sessionwrapper.hpp.
References FIX8::ReliableClientSession< T >::_recv_seqnum, FIX8::ReliableClientSession< T >::_send_seqnum, FIX8::ReliableClientSession< T >::_thread, and FIX8::Thread< T >::Start().
Referenced by main().
Member Data Documentation
template<typename T> unsigned FIX8::ReliableClientSession< T >::_recv_seqnum private
Definition at line 139 of file sessionwrapper.hpp.
Referenced by FIX8::ReliableClientSession< T >::operator()(), and FIX8::ReliableClientSession< T >::start().
template<typename T> unsigned FIX8::ReliableClientSession< T >::_send_seqnum private
Definition at line 139 of file sessionwrapper.hpp.
Referenced by FIX8::ReliableClientSession< T >::operator()(), and FIX8::ReliableClientSession< T >::start().
template<typename T> Thread<ReliableClientSession<T> > FIX8::ReliableClientSession< T >::_thread private
Definition at line 138 of file sessionwrapper.hpp.
Referenced by FIX8::ReliableClientSession< T >::start().
The documentation for this class was generated from the following file:
sessionwrapper.hpp