fix8: ff::MSqueue Class Reference
ff::MSqueue Class Reference
An implementation of the lock-free FIFO MPMC queue by Michael and Scott, described in the paper: "Simple, Fast, and Practical Non-Blocking and Blocking Concurrent Queue Algorithms", PODC 1996.
#include <MPMCqueues.hpp>
Classes
struct Node
struct Pointer
Public Member Functions
MSqueue ()
~MSqueue ()
MSqueue & operator= (const MSqueue &v)
int init ()
bool push (void *const data)
bool pop (void **data)
bool empty ()
Private Types
enum { MSQUEUE_PTR =0 }
Private Member Functions
struct ff::MSqueue::Pointer ALIGN_TO_POST (ALIGN_SINGLE_POINTER)
struct ff::MSqueue::Node ALIGN_TO_POST (ALIGN_DOUBLE_POINTER)
void allocnode (Pointer &p, void *data)
void deallocnode (Node *n)
Private Attributes
Pointer head
long padding1 [longxCacheLine-(sizeof(Pointer)/sizeof(long))]
Pointer tail
long padding2 [longxCacheLine-(sizeof(Pointer)/sizeof(long))]
FFAllocator * delayedAllocator
Detailed Description
An implementation of the lock-free FIFO MPMC queue by Michael and Scott, described in the paper: "Simple, Fast, and Practical Non-Blocking and Blocking Concurrent Queue Algorithms", PODC 1996.
The MSqueue implementation is inspired to the one in the liblfds libraly that is a portable, license-free, lock-free data structure library written in C. The liblfds implementation uses double-word CAS (aka DCAS) whereas this implementation uses only single-word CAS since it relies on a implementation of a memory allocator (used to allocate internal queue nodes) which implements a deferred reclamation algorithm able to solve both the ABA problem and the dangling pointer problem.
More info about liblfds can be found at http://www.liblfds.org
Definition at line 572 of file MPMCqueues.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
MSQUEUE_PTR
Definition at line 574 of file MPMCqueues.hpp.
Constructor & Destructor Documentation
ff::MSqueue::MSqueue () inline
Definition at line 668 of file MPMCqueues.hpp.
ff::MSqueue::~MSqueue () inline
Definition at line 670 of file MPMCqueues.hpp.
Member Function Documentation
struct ff::MSqueue::Pointer ff::MSqueue::ALIGN_TO_POST (ALIGN_SINGLE_POINTER) private
Referenced by push().
struct ff::MSqueue::Node ff::MSqueue::ALIGN_TO_POST (ALIGN_DOUBLE_POINTER) private
void ff::MSqueue::allocnode (Pointer & p, void * data) inline private
Definition at line 652 of file MPMCqueues.hpp.
Referenced by init(), and push().
void ff::MSqueue::deallocnode (Node * n) inline private
Definition at line 662 of file MPMCqueues.hpp.
Referenced by pop().
bool ff::MSqueue::empty () inline
Definition at line 758 of file MPMCqueues.hpp.
References ff::MSqueue::Pointer::getNode(), ff::MSqueue::Pointer::getNodeNext(), head, and tail.
int ff::MSqueue::init () inline
initialize the MSqueue
Definition at line 684 of file MPMCqueues.hpp.
References allocnode(), delayedAllocator, head, and tail.
MSqueue& ff::MSqueue::operator= (const MSqueue & v) inline
Definition at line 677 of file MPMCqueues.hpp.
References head, and tail.
bool ff::MSqueue::pop (void ** data) inline
Definition at line 730 of file MPMCqueues.hpp.
References CAS, deallocnode(), ff::MSqueue::Pointer::getData(), ff::MSqueue::Pointer::getNode(), ff::MSqueue::Pointer::getNodeNext(), head, next, and tail.
bool ff::MSqueue::push (void *const data) inline
Definition at line 703 of file MPMCqueues.hpp.
References ALIGN_TO_POST(), allocnode(), CAS, ff::MSqueue::Pointer::getNodeNext(), next, and tail.
Member Data Documentation
FFAllocator* ff::MSqueue::delayedAllocator private
Definition at line 649 of file MPMCqueues.hpp.
Referenced by init(), and set().
Pointer ff::MSqueue::head private
Definition at line 645 of file MPMCqueues.hpp.
Referenced by empty(), init(), operator=(), and pop().
long ff::MSqueue::padding1[longxCacheLine-(sizeof(Pointer)/sizeof(long))] private
Definition at line 646 of file MPMCqueues.hpp.
long ff::MSqueue::padding2[longxCacheLine-(sizeof(Pointer)/sizeof(long))] private
Definition at line 648 of file MPMCqueues.hpp.
Pointer ff::MSqueue::tail private
Definition at line 647 of file MPMCqueues.hpp.
Referenced by empty(), init(), operator=(), pop(), and push().
The documentation for this class was generated from the following file:
MPMCqueues.hpp