fix8: FIX8::Minst Class Reference
FIX8::Minst Class Reference
Structures for framework generated message creation table.
#include <message.hpp>
Classes
struct _gen
struct _gen< void * >
Public Member Functions
Minst ()
template<typename T >
Minst (Type2Type< T >)
template<typename T , typename R >
Minst (Type2Types< T, R >)
Public Attributes
Message *(&) _do ()
Static Private Member Functions
static Message * dummy ()
Detailed Description
Structures for framework generated message creation table.
Definition at line 131 of file message.hpp.
Constructor & Destructor Documentation
FIX8::Minst::Minst () inline
Definition at line 143 of file message.hpp.
template<typename T > FIX8::Minst::Minst (Type2Type< T >) inline
Definition at line 148 of file message.hpp.
template<typename T , typename R > FIX8::Minst::Minst (Type2Types< T, R >) inline
Definition at line 151 of file message.hpp.
Member Function Documentation
static Message* FIX8::Minst::dummy () inline static private
Definition at line 140 of file message.hpp.
Member Data Documentation
Message*(&) FIX8::Minst::_do()
Definition at line 145 of file message.hpp.
Referenced by FIX8::Message::clone(), FIX8::Session::create_msg(), and FIX8::ConsoleMenu::CreateMsgs().
The documentation for this class was generated from the following file:
message.hpp