fix8: ff::zmq1_1 Class Reference
ff::zmq1_1 Class Reference
This class provides ZeroMQ implementation of the 1 to 1 communication pattern.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 0 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
a ØMQ message (extends zmq::message_t)
typedef msg_t tosend_t
to the transpoort layer
typedef msg_t torecv_t
ut supra
typedef descriptor1_N descriptor
ut supra
Public Member Functions
zmq1_1 ()
zmq1_1 (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const msg_t &msg, const int)
bool putmore (const msg_t &msg, const int)
bool gethdr (torecv_t &msg, int &peer)
bool get (torecv_t &msg, int=0)
int getToWait () const
int putToPerform () const
void done ()
bool close ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
This class provides ZeroMQ implementation of the 1 to 1 communication pattern.
This class is defined in zmqImpl.hpp
Definition at line 830 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptor1_N ff::zmq1_1::descriptor
ut supra
      descriptor used in Unicast, Bcast, Scatter,
On-Demand, OneToMany
Definition at line 836 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmq1_1::msg_t
Definition at line 832 of file zmqImpl.hpp.
typedef msg_t ff::zmq1_1::torecv_t
ut supra
Definition at line 835 of file zmqImpl.hpp.
typedef msg_t ff::zmq1_1::tosend_t
to the transpoort layer
Definition at line 834 of file zmqImpl.hpp.
typedef zmqTransport ff::zmq1_1::TransportImpl
a ØMQ message (extends zmq::message_t)
Definition at line 833 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 839 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmq1_1::zmq1_1 () inline
Constructor
Definition at line 844 of file zmqImpl.hpp.
ff::zmq1_1::zmq1_1 (descriptor * D) inline
Constructor (2)
Parameters
D is a pointer to a 1_N descriptor object.
Definition at line 851 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmq1_1::close () inline
Definition at line 964 of file zmqImpl.hpp.
References active, ff::descriptor1_N::close(), and desc.
void ff::zmq1_1::done () inline
Definition at line 957 of file zmqImpl.hpp.
bool ff::zmq1_1::get (torecv_t & msg, int = 0) inline
Definition at line 938 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recv().
descriptor* ff::zmq1_1::getDescriptor () inline
It gets the descriptor.
Returns
It returns the descriptor.
Definition at line 868 of file zmqImpl.hpp.
References desc.
bool ff::zmq1_1::gethdr (torecv_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg TODO peer TODO
Returns
TODO
Definition at line 928 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recvhdr().
int ff::zmq1_1::getToWait () const inline
Definition at line 945 of file zmqImpl.hpp.
bool ff::zmq1_1::init (const std::string & address, const int nodeId = -1) inline
It initializes the communication pattern.
Returns
TODO
Definition at line 875 of file zmqImpl.hpp.
References active, desc, ff::descriptor1_N::init(), and ff::descriptor1_N::P.
bool ff::zmq1_1::put (const tosend_t & msg) inline
It sends one message.
Parameters
msg is a reference to the message to be sent.
Returns
TODO
Definition at line 889 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmq1_1::put (const msg_t & msg, const int) inline
TODO
Parameters
msg TODO x TODO
Returns
TODO
Definition at line 908 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmq1_1::putmore (const tosend_t & msg) inline
It sends other parts of a multi-part message.
Parameters
msg is a reference to the message to be sent.
Returns
TODO
Definition at line 898 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::sendmore().
bool ff::zmq1_1::putmore (const msg_t & msg, const int) inline
TODO
msg TODO x TODO
Returns
TODO
Definition at line 918 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
int ff::zmq1_1::putToPerform () const inline
Definition at line 952 of file zmqImpl.hpp.
void ff::zmq1_1::setDescriptor (descriptor * D) inline
Definition at line 858 of file zmqImpl.hpp.
References ff::descriptor1_N::close(), and desc.
Member Data Documentation
bool ff::zmq1_1::active protected
Definition at line 973 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmq1_1::desc protected
Definition at line 972 of file zmqImpl.hpp.
Referenced by close(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp