fix8: FIX8::ff_unbounded_queue< T > Class Template Reference
FIX8::ff_unbounded_queue< T > Class Template Reference
#include <ff_wrapper.hpp>
Public Types
using value_type = T
using reference = T &
Reference type.
using const_reference = const T &
Const reference type.
Public Member Functions
ff_unbounded_queue ()
~ff_unbounded_queue ()
bool try_push (const T &source)
void push (const T &source)
bool try_pop (T *&target)
bool pop (T *&target)
void release (T *source) const
Private Attributes
ff::uMPMC_Ptr_Queue _queue
Detailed Description
template<typename T>
class FIX8::ff_unbounded_queue< T >
Definition at line 44 of file ff_wrapper.hpp.
Member Typedef Documentation
template<typename T > using FIX8::ff_unbounded_queue< T >::const_reference = const T&
Const reference type.
Definition at line 56 of file ff_wrapper.hpp.
template<typename T > using FIX8::ff_unbounded_queue< T >::reference = T&
Reference type.
Definition at line 53 of file ff_wrapper.hpp.
template<typename T > using FIX8::ff_unbounded_queue< T >::value_type = T
Definition at line 50 of file ff_wrapper.hpp.
Constructor & Destructor Documentation
template<typename T > FIX8::ff_unbounded_queue< T >::ff_unbounded_queue () inline explicit
Definition at line 58 of file ff_wrapper.hpp.
References FIX8::ff_unbounded_queue< T >::_queue.
 { _queue.init(); }
template<typename T > FIX8::ff_unbounded_queue< T >::~ff_unbounded_queue () inline
Definition at line 59 of file ff_wrapper.hpp.
 {}
Member Function Documentation
template<typename T > bool FIX8::ff_unbounded_queue< T >::pop (T *& target) inline
Definition at line 65 of file ff_wrapper.hpp.
References FIX8::hypersleep< h_nanoseconds >(), and FIX8::ff_unbounded_queue< T >::try_pop().
    {
 #if defined SLEEP_NO_YIELD
       const unsigned cnt_rnd(3);
       unsigned cnt(0);
 #endif
       for(;;)
       {
          if (try_pop(target))
             return true;
 #if defined SLEEP_NO_YIELD
          if ((++cnt %= cnt_rnd) == 0)
             hypersleep<h_nanoseconds>(SLEEP_NO_YIELD);
          else
 #endif
             sched_yield();
       }
       return false;
    }
template<typename T > void FIX8::ff_unbounded_queue< T >::push (const T & source) inline
Definition at line 63 of file ff_wrapper.hpp.
References FIX8::ff_unbounded_queue< T >::try_push().
 { try_push(source); }
template<typename T > void FIX8::ff_unbounded_queue< T >::release (T * source) const inline
Definition at line 85 of file ff_wrapper.hpp.
 { ::ff::ff_free(source); }
template<typename T > bool FIX8::ff_unbounded_queue< T >::try_pop (T *& target) inline
Definition at line 64 of file ff_wrapper.hpp.
References FIX8::ff_unbounded_queue< T >::_queue.
Referenced by FIX8::ff_unbounded_queue< T >::pop().
 { return _queue.pop(reinterpret_cast<void**>(&target)); }
template<typename T > bool FIX8::ff_unbounded_queue< T >::try_push (const T & source) inline
Definition at line 61 of file ff_wrapper.hpp.
References FIX8::ff_unbounded_queue< T >::_queue.
Referenced by FIX8::ff_unbounded_queue< T >::push().
       { return _queue.push(new (::ff::ff_malloc(sizeof(T))) T(source)); }
Member Data Documentation
template<typename T > ff::uMPMC_Ptr_Queue FIX8::ff_unbounded_queue< T >::_queue private
Definition at line 47 of file ff_wrapper.hpp.
Referenced by FIX8::ff_unbounded_queue< T >::ff_unbounded_queue(), FIX8::ff_unbounded_queue< T >::try_pop(), and FIX8::ff_unbounded_queue< T >::try_push().
The documentation for this class was generated from the following file:
ff_wrapper.hpp