fix8: FIX8::TEX::trailer Class Reference
FIX8::TEX::trailer Class Reference
trailer (trailer), application, 3 fields, 0 groups.
#include <Myfix_classes.hpp>
Public Member Functions
trailer ()
virtual ~trailer ()
void add_preamble ()
trailer ()
virtual ~trailer ()
void add_preamble ()
Public Member Functions inherited from FIX8::MessageBase
template<typename InputIterator >
MessageBase (const struct F8MetaCntx &ctx, const f8String &msgType, const InputIterator begin, const size_t cnt)
MessageBase (const MessageBase &from)
Copy ctor.
MessageBase & operator= (const MessageBase &that)
Assignment operator.
virtual ~MessageBase ()
Dtor.
virtual void clear (bool reuse=true)
size_t size () const
unsigned decode (const f8String &from, const unsigned offset)
unsigned decode_group (const unsigned short fnum, const f8String &from, const unsigned offset)
unsigned encode (std::ostream &to) const
unsigned encode (char *to, size_t &sz) const
unsigned encode_group (const unsigned short fnum, std::ostream &to) const
unsigned encode_group (const unsigned short fnum, char *to, size_t &sz) const
unsigned check_positions ()
unsigned copy_legal (MessageBase *to, bool force=false) const
void check_set_rlm (BaseField *where) const
const f8String & get_msgtype () const
void add_field (const unsigned short fnum, Presence::const_iterator itr, const unsigned pos, BaseField *what, bool check)
void add_field (const unsigned short fnum, const unsigned pos, BaseField *what, bool check=true)
void set (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
bool add_field (BaseField *what)
bool operator+= (BaseField *what)
MessageBase & operator<< (BaseField *what)
template<typename T >
bool get (T &to) const
template<typename T >
bool has () const
template<typename T >
const T * get () const
template<typename T >
bool operator() (T &to) const
template<typename T >
const T * operator() () const
bool have (const unsigned short fnum) const
Fields::const_iterator find_field (const unsigned short fnum) const
BaseField * get_field (const unsigned short fnum) const
Fields::const_iterator fields_begin () const
Fields::const_iterator fields_end () const
BaseField * replace (const unsigned short fnum, Presence::const_iterator itr, BaseField *with)
BaseField * replace (const unsigned short fnum, BaseField *with)
BaseField * remove (const unsigned short fnum, Presence::const_iterator itr)
BaseField * remove (const unsigned short fnum)
template<typename T >
GroupBase * find_group () const
GroupBase * find_group (const unsigned short fnum) const
void append_group (GroupBase *what)
void add_group (GroupBase *what)
MessageBase & operator<< (GroupBase *what)
void operator+= (GroupBase *what)
unsigned short getPos (const unsigned short field) const
bool add_trait (const FieldTrait &what)
template<typename InputIterator >
void add_trait (const InputIterator begin, const size_t cnt)
virtual void print (std::ostream &os, int depth=0) const
virtual void print_field (const unsigned short fnum, std::ostream &os) const
virtual void print_group (const unsigned short fnum, std::ostream &os, int depth=0) const
const FieldTraits & get_fp () const
void print_fp (std::ostream &os)
Static Public Member Functions
static const MsgType & get_msgtype ()
static const MsgType & get_msgtype ()
Static Public Member Functions inherited from FIX8::MessageBase
static unsigned extract_element (const char *from, const unsigned sz, char *tag, char *val)
static unsigned extract_element (const char *from, const unsigned sz, f8String &tag, f8String &val)
Static Private Attributes
static const FieldTrait _traits []
static const FieldTrait_Hash_Array _ftha
static const MsgType _msgtype
Additional Inherited Members
Static Protected Member Functions inherited from FIX8::MessageBase
static unsigned extract_header (const f8String &from, f8String &len, f8String &mtype)
static unsigned extract_trailer (const f8String &from, f8String &chksum)
Protected Attributes inherited from FIX8::MessageBase
Fields _fields
FieldTraits _fp
Positions _pos
Groups _groups
const f8String & _msgType
const F8MetaCntx & _ctx
Detailed Description
trailer (trailer), application, 3 fields, 0 groups.
Definition at line 33368 of file Myfix_classes.hpp.
Constructor & Destructor Documentation
FIX8::TEX::trailer::trailer () inline
Definition at line 33375 of file Myfix_classes.hpp.
References add_preamble().
virtual FIX8::TEX::trailer::~trailer () inline virtual
Definition at line 33376 of file Myfix_classes.hpp.
FIX8::TEX::trailer::trailer () inline
Definition at line 400 of file Perf_classes.hpp.
References add_preamble().
virtual FIX8::TEX::trailer::~trailer () inline virtual
Definition at line 401 of file Perf_classes.hpp.
Member Function Documentation
void FIX8::TEX::trailer::add_preamble () inline
Definition at line 405 of file Perf_classes.hpp.
References FIX8::MessageBase::add_field(), and FIX8::Common_CheckSum().
void FIX8::TEX::trailer::add_preamble () inline
Definition at line 33380 of file Myfix_classes.hpp.
References FIX8::MessageBase::add_field(), and FIX8::Common_CheckSum().
Referenced by trailer().
static const MsgType& FIX8::TEX::trailer::get_msgtype () inline static
Definition at line 403 of file Perf_classes.hpp.
References _msgtype.
static const MsgType& FIX8::TEX::trailer::get_msgtype () inline static
Definition at line 33378 of file Myfix_classes.hpp.
References _msgtype.
Member Data Documentation
const FieldTrait_Hash_Array FIX8::TEX::trailer::_ftha static private
Definition at line 33371 of file Myfix_classes.hpp.
const MsgType FIX8::TEX::trailer::_msgtype static private
Definition at line 33372 of file Myfix_classes.hpp.
Referenced by get_msgtype().
const FieldTrait FIX8::TEX::trailer::_traits static private
Initial value:
{
   FieldTrait(  10,  15,   3, 0x65), FieldTrait(  89,  28,   2, 0x4), FieldTrait(  93,   2,   1, 0x4)
}
Definition at line 33370 of file Myfix_classes.hpp.
The documentation for this class was generated from the following files:
Myfix_classes.hpp
Perf_classes.hpp
Myfix_traits.cpp
Perf_traits.cpp