fix8: FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare > Class Template Reference
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare > Class Template Reference
#include <traits.hpp>
Public Types
using iterator = FieldTrait *
using const_iterator = const FieldTrait *
using result = std::pair< iterator, bool >
Public Member Functions
presorted_set (const_iterator arr_start, const size_t sz, const FieldTrait_Hash_Array *ftha)
presorted_set (const_iterator arr_start, const size_t sz, const size_t reserve=RESERVE_PERCENT)
presorted_set (const presorted_set &from)
presorted_set (const size_t sz=0, const size_t reserve=RESERVE_PERCENT)
~presorted_set ()
dtor
iterator find (const FieldTrait what, bool &answer)
iterator find (const unsigned short key, bool &answer)
const_iterator find (const unsigned short key) const
const_iterator find (const FieldTrait what) const
iterator find (const unsigned short key)
iterator find (const FieldTrait what)
const_iterator at (const size_t idx) const
result insert (const_iterator what)
void insert (const_iterator what_begin, const_iterator what_end)
void clear ()
size_t size () const
bool empty () const
size_t rsize () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Static Public Member Functions
static size_t calc_reserve (size_t sz, size_t res)
static size_t distance (const_iterator what_begin, const_iterator what_end)
Private Types
using internal_result = std::pair< iterator, iterator >
using const_internal_result = std::pair< const_iterator, const_iterator >
Private Attributes
size_t _reserve
size_t _sz
size_t _rsz
FieldTrait * _arr
const FieldTrait_Hash_Array * _ftha
Detailed Description
template<>
class FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >
Specialisation of Presorted set using hash array lookup Search complexity is O(1), ctor complexity approaches O(1), no insert
Definition at line 218 of file traits.hpp.
Member Typedef Documentation
using FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::const_internal_result = std::pair<const_iterator, const_iterator> private
Definition at line 244 of file traits.hpp.
using FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::const_iterator = const FieldTrait*
Definition at line 222 of file traits.hpp.
using FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::internal_result = std::pair<iterator, iterator> private
Definition at line 243 of file traits.hpp.
using FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::iterator = FieldTrait*
Definition at line 221 of file traits.hpp.
using FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::result = std::pair<iterator, bool>
Definition at line 223 of file traits.hpp.
Constructor & Destructor Documentation
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::presorted_set (const_iterator arr_start, const size_t sz, const FieldTrait_Hash_Array * ftha) inline
ctor - initialise from static sorted set. Used by Message encoder/decoder.
Parameters
arr_start pointer to start of static array to copy elements from
sz number of elements in set to copy
ftha pointer to field hash array
Definition at line 251 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, and FIX8::presorted_set< K, T, Comp >::_sz.
       : _reserve(), _sz(sz), _arr(new FieldTrait[_sz]), _ftha(ftha)
          { memcpy(_arr, arr_start, _sz * sizeof(FieldTrait)); }
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::presorted_set (const_iterator arr_start, const size_t sz, const size_t reserve = RESERVE_PERCENT) inline
ctor - initialise an empty set; defer memory allocation;
Parameters
arr_start pointer to start of static array to copy elements from
sz number of elements to initially allocate
reserve percentage of sz to keep in reserve
Definition at line 259 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, and FIX8::presorted_set< K, T, Comp >::_sz.
                                                                                                   : _reserve(reserve),
       _sz(sz), _rsz(_sz + calc_reserve(_sz, _reserve)), _arr(new FieldTrait[_rsz]), _ftha()
          { memcpy(_arr, arr_start, _sz * sizeof(FieldTrait)); }
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::presorted_set (const presorted_set< unsigned short, FieldTrait, FieldTrait::Compare > & from) inline
copy ctor
Parameters
from presorted_set object to copy
Definition at line 265 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, and FIX8::presorted_set< K, T, Comp >::_sz.
                                             : _reserve(from._reserve),
       _sz(from._sz), _rsz(from._rsz), _arr(new FieldTrait[_rsz]), _ftha(from._ftha)
          { memcpy(_arr, from._arr, _sz * sizeof(FieldTrait)); }
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::presorted_set (const size_t sz = 0, const size_t reserve = RESERVE_PERCENT) inline explicit
ctor - initialise an empty set; defer memory allocation;
Parameters
sz number of elements to initially allocate
reserve percentage of sz to keep in reserve
Definition at line 272 of file traits.hpp.
                                                                                    : _reserve(reserve),
       _sz(sz), _rsz(_sz + calc_reserve(_sz, _reserve)), _arr(), _ftha() {}
FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::~presorted_set () inline
dtor
Definition at line 276 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr.
 { delete[] _arr; }
Member Function Documentation
const_iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::at (const size_t idx) const inline
Get the element at index location
Parameters
idx of the pair to retrieve
Returns
const_iterator to element or end() if not found
Definition at line 344 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::presorted_set< K, T, Comp >::_sz, and FIX8::presorted_set< K, T, Comp >::end().
Referenced by FIX8::ConsoleMenu::SelectField().
 { return idx < _sz ? _arr + idx : end(); }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin () inline
Get a pointer to the first element
Returns
the first element
Definition at line 418 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr.
Referenced by FIX8::FieldTraits::clear_flag(), FIX8::FieldTraits::find_missing(), generate_group_traits(), FIX8::operator<<(), and FIX8::ConsoleMenu::SelectField().
 { return _arr; }
const_iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin () const inline
Get a const pointer to the first element
Returns
the first element
Definition at line 426 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr.
 { return _arr; }
static size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::calc_reserve (size_t sz, size_t res) inline static
Calculate the amount of space to reserve in set
Parameters
sz number of elements currently in set; if 0 retun reserve elements as size to reserve
res percentage of sz to keep in reserve
Returns
number of elements to additionally reserve (at least 1)
Definition at line 229 of file traits.hpp.
    {
       if (!sz)  // special case - reserve means number to reserve, not %
          return res;
       const size_t val(sz * res / 100);
       return val ? val : 1;
    }
void FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::clear () inline
Clear the set (does not delete)
Definition at line 402 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_sz.
 { _sz = 0; }
static size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::distance (const_iterator what_begin, const_iterator what_end) inline static
Find the distance between two iterators
Parameters
what_begin start iterator
what_end end iterator (must be >= to what_begin
Returns
distance in elements
Definition at line 388 of file traits.hpp.
       { return what_end - what_begin; }
bool FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::empty () const inline
Check if the set is empty
Returns
true if empty
Definition at line 410 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_sz.
 { return _sz == 0; }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end () inline
Get a pointer to the last element + 1
Returns
the last element + 1
Definition at line 422 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, and FIX8::presorted_set< K, T, Comp >::_sz.
Referenced by FIX8::MessageBase::add_field(), FIX8::FieldTraits::clear(), FIX8::FieldTraits::clear_flag(), FIX8::MessageBase::copy_legal(), FIX8::ConsoleMenu::EditMsg(), FIX8::FieldTraits::find_missing(), generate_group_traits(), FIX8::FieldTraits::get(), FIX8::FieldTraits::getComp(), FIX8::FieldTraits::getPos(), FIX8::FieldTraits::getval(), FIX8::FieldTraits::has(), FIX8::operator<<(), FIX8::ConsoleMenu::SelectField(), and FIX8::FieldTraits::set().
 { return _arr + _sz; }
const_iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end () const inline
Get a const pointer to the last element + 1
Returns
the last element + 1
Definition at line 430 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, and FIX8::presorted_set< K, T, Comp >::_sz.
 { return _arr + _sz; }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const FieldTrait what, bool & answer) inline
Find an element with the given value
Parameters
what element to find
answer true if element is found
Returns
pointer to found element or pointer to location where element would be inserted
Definition at line 282 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::FieldTrait::_fnum, and FIX8::presorted_set< K, T, Comp >::_sz.
Referenced by FIX8::FieldTraits::clear(), FIX8::FieldTraits::get(), FIX8::FieldTraits::getComp(), FIX8::FieldTraits::getPos(), FIX8::FieldTraits::getval(), FIX8::FieldTraits::has(), and FIX8::FieldTraits::set().
    {
       if (_ftha)
          return (answer = what._fnum < _ftha->_sz && (_arr + _ftha->_arr[what._fnum])->_fnum == what._fnum) ? _arr + _ftha->_arr[what._fnum] : 0;
       const internal_result res(std::equal_range (_arr, _arr + _sz, what, FieldTrait::Compare()));
       answer = res.first != res.second;
       return res.first;
    }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const unsigned short key, bool & answer) inline
Find an element with the given key
Parameters
key to find
answer true if element is found
Returns
pointer to found element or pointer to location where element would be inserted
Definition at line 295 of file traits.hpp.
References find().
Referenced by find().
 { return find(FieldTrait(key), answer); }
const_iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const unsigned short key) const inline
Find an element with the given key (const version)
Parameters
key to find
Returns
pointer to found element or end()
Definition at line 300 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::presorted_set< K, T, Comp >::_sz, and FIX8::presorted_set< K, T, Comp >::end().
    {
       if (_ftha)
          return key < _ftha->_sz && (_arr + _ftha->_arr[key])->_fnum == key ? _arr + _ftha->_arr[key] : end();
       const FieldTrait what(key);
       const const_internal_result res(std::equal_range (_arr, _arr + _sz, what, FieldTrait::Compare()));
       return res.first != res.second ? res.first : end();
    }
const_iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const FieldTrait what) const inline
Find an element with the given value (const version)
Parameters
what element to find
Returns
pointer to found element or end()
Definition at line 312 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::FieldTrait::_fnum, FIX8::presorted_set< K, T, Comp >::_sz, and FIX8::presorted_set< K, T, Comp >::end().
    {
       if (_ftha)
          return what._fnum < _ftha->_sz && (_arr + _ftha->_arr[what._fnum])->_fnum == what._fnum ? _arr + _ftha->_arr[what._fnum] : end();
       const const_internal_result res(std::equal_range (_arr, _arr + _sz, what, FieldTrait::Compare()));
       return res.first != res.second ? res.first : end();
    }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const unsigned short key) inline
Find an element with the given key
Parameters
key to find
Returns
pointer to found element or end()
Definition at line 323 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::presorted_set< K, T, Comp >::_sz, and FIX8::presorted_set< K, T, Comp >::end().
    {
       if (_ftha)
          return key < _ftha->_sz && (_arr + _ftha->_arr[key])->_fnum == key ? _arr + _ftha->_arr[key] : end();
       const FieldTrait what(key);
       internal_result res(std::equal_range (_arr, _arr + _sz, what, FieldTrait::Compare()));
       return res.first != res.second ? res.first : end();
    }
iterator FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find (const FieldTrait what) inline
Find an element with the given value
Parameters
what value to find
Returns
pointer to found element or end()
Definition at line 335 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::presorted_set< K, T, Comp >::_sz, and FIX8::presorted_set< K, T, Comp >::end().
    {
       internal_result res(std::equal_range (_arr, _arr + _sz, what, FieldTrait::Compare()));
       return res.first != res.second ? res.first : end();
    }
result FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::insert (const_iterator what) inline
Insert an element into the set
Parameters
what pointer to element to insert
Returns
result with iterator to insert location and true or end() and false
Definition at line 349 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_arr, FIX8::presorted_set< K, T, Comp >::_reserve, FIX8::presorted_set< K, T, Comp >::_rsz, FIX8::presorted_set< K, T, Comp >::_sz, FIX8::presorted_set< K, T, Comp >::calc_reserve(), FIX8::presorted_set< K, T, Comp >::end(), and FIX8::presorted_set< K, T, Comp >::find().
Referenced by FIX8::FieldTraits::add().
    {
       if (!_sz)
       {
          _arr = new FieldTrait[_rsz];
          memcpy(_arr, what, sizeof(FieldTrait));
          ++_sz;
          return std::make_pair(_arr, true);
       }
       bool answer;
       iterator where(find(*what, answer));
       if (answer) // sorry already here
          return std::make_pair(end(), false);
       if (_sz < _rsz) // we have space
       {
          memmove(where + 1, where, (end() - where) * sizeof(FieldTrait));
          memcpy(where, what, sizeof(FieldTrait));
       }
       else // we have to make space
       {
          iterator new_arr(new FieldTrait[_rsz = _sz + calc_reserve(_sz, _reserve)]);
          const size_t wptr(where - _arr);
          if (wptr > 0)
             memcpy(new_arr, _arr, sizeof(FieldTrait) * wptr);
          memcpy(new_arr + wptr, what, sizeof(FieldTrait));
          memcpy(new_arr + wptr + 1, where, (end() - where) * sizeof(FieldTrait));
          delete[] _arr;
          _arr = new_arr;
       }
       ++_sz;
       return std::make_pair(where, true);
    }
void FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::insert (const_iterator what_begin, const_iterator what_end) inline
Insert a range of elements into the set
Parameters
what_begin pointer to 1st element to insert
what_end pointer to nth element + 1 to insert
Definition at line 394 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::insert().
    {
       for (const_iterator ptr(what_begin); ptr < what_end; ++ptr)
          if (!insert(ptr).second)
             break;
    }
size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::rsize () const inline
Obtain the number of elements that can be inserted before reallocating
Returns
reserved + sz
Definition at line 414 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_rsz.
 { return _rsz; }
size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::size () const inline
Obtain the number of elements in the set
Returns
the number of elements
Definition at line 406 of file traits.hpp.
References FIX8::presorted_set< K, T, Comp >::_sz.
Referenced by generate_group_bodies(), generate_group_traits(), FIX8::ConsoleMenu::SelectField(), and FIX8::FieldTraits::size().
 { return _sz; }
Member Data Documentation
FieldTrait* FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::_arr private
Definition at line 240 of file traits.hpp.
const FieldTrait_Hash_Array* FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::_ftha private
Definition at line 241 of file traits.hpp.
size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::_reserve private
Definition at line 238 of file traits.hpp.
size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::_rsz private
Definition at line 239 of file traits.hpp.
size_t FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::_sz private
Definition at line 239 of file traits.hpp.
The documentation for this class was generated from the following file:
traits.hpp