fix8: FIX8::TEX::header Class Reference
FIX8::TEX::header Class Reference
header (header), application, 29 fields, 1 group.
#include <Myfix_classes.hpp>
Classes
class NoHops
NoHops (627), application, 3 fields, 0 groups, is unique, hash: 0x7f240fc4.
Public Member Functions
header (bool deepctor=true)
~header ()=default
begin_string * get_begin_string ()
body_length * get_body_length ()
msg_type * get_msg_type ()
void add_preamble ()
GroupBase * create_nested_group (unsigned short fnum) const
header (bool deepctor=true)
~header ()=default
begin_string * get_begin_string ()
body_length * get_body_length ()
msg_type * get_msg_type ()
void add_preamble ()
Public Member Functions inherited from FIX8::MessageBase
template<typename InputIterator >
MessageBase (const struct F8MetaCntx &ctx, const f8String &msgType, const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array *ftha)
F8API MessageBase (const MessageBase &from)
Copy ctor.
F8API MessageBase & operator= (const MessageBase &that)
Assignment operator.
virtual ~MessageBase ()
Dtor.
virtual void clear (bool reuse=true)
void clear_positions ()
empty the positions map
size_t size () const
F8API unsigned decode (const f8String &from, unsigned offset, unsigned ignore=0, bool permissive_mode=false)
unsigned decode_group (GroupBase *grpbase, const unsigned short fnum, const f8String &from, unsigned s_offset, unsigned ignore)
F8API size_t encode (std::ostream &to) const
F8API size_t encode (char *to) const
F8API size_t encode_group (const unsigned short fnum, std::ostream &to) const
F8API size_t encode_group (const unsigned short fnum, char *to) const
F8API unsigned check_positions ()
F8API unsigned copy_legal (MessageBase *to, bool force=false) const
F8API unsigned move_legal (MessageBase *to, bool force=false)
void push_unknown (MessageBase *to) const
void check_set_rlm (BaseField *where) const
const f8String & get_msgtype () const
void add_field_decoder (const unsigned short fnum, const unsigned pos, BaseField *what)
void add_field (const unsigned short fnum, Presence::const_iterator itr, const unsigned pos, BaseField *what, bool check)
void add_field (const unsigned short fnum, Fields::iterator fitr, const unsigned pos, BaseField *what, bool check=true)
void add_field (const unsigned short fnum, const unsigned pos, BaseField *what, bool check=true)
void set (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
template<typename T >
bool add_field (T *what)
bool add_field (BaseField *what)
Groups & get_groups ()
template<typename T >
bool operator+= (T *what)
template<typename T >
MessageBase & operator<< (T *what)
template<typename T >
bool get (T &to) const
template<typename T >
bool has () const
bool is_legal (unsigned short fnum) const
template<typename T >
bool is_legal () const
template<typename T >
const T * get () const
template<typename T >
bool operator() (T &to) const
template<typename T >
const T * operator() () const
bool have (const unsigned short fnum) const
Fields::const_iterator find_field (const unsigned short fnum) const
BaseField * get_field (const unsigned short fnum) const
BaseField * get_field_by_name (const char *tag) const
Fields::const_iterator fields_begin () const
Fields::const_iterator fields_end () const
F8API BaseField * replace (const unsigned short fnum, Presence::const_iterator itr, BaseField *with)
F8API BaseField * replace (const unsigned short fnum, BaseField *with)
F8API GroupBase * replace (const unsigned short fnum, GroupBase *with)
F8API BaseField * remove (const unsigned short fnum, Presence::const_iterator itr)
F8API BaseField * remove (const unsigned short fnum)
template<typename T >
GroupBase * find_group () const
GroupBase * find_group (const unsigned short fnum) const
template<typename T >
GroupBase * find_add_group (GroupBase *grpbase=nullptr)
GroupBase * find_add_group (const unsigned short fnum, GroupBase *grpbase=nullptr)
template<typename T >
void append_group (T *what)
void add_group (GroupBase *what)
MessageBase & operator<< (GroupBase *what)
void operator+= (GroupBase *what)
unsigned short getPos (const unsigned short field) const
bool add_trait (const FieldTrait &what)
template<typename InputIterator >
void add_trait (const InputIterator begin, const size_t cnt)
virtual F8API void print (std::ostream &os, int depth=0) const
virtual F8API void print_field (const unsigned short fnum, std::ostream &os) const
virtual F8API void print_group (const unsigned short fnum, std::ostream &os, int depth=0) const
const FieldTraits & get_fp () const
void print_fp (std::ostream &os)
virtual check_sum * get_check_sum ()
const f8String & get_unknown () const
Static Public Member Functions
static const MsgType & get_msgtype ()
static const MsgType & get_msgtype ()
Static Public Member Functions inherited from FIX8::MessageBase
static unsigned extract_element (const char *from, const unsigned sz, char *tag, char *val)
static unsigned extract_element (const char *from, const unsigned sz, f8String &tag, f8String &val)
static void set_tabsize (unsigned tabsize)
static unsigned get_tabsize ()
static bool has_group_count (const BaseField *bf)
Private Attributes
begin_string * _begin_string
body_length * _body_length
msg_type * _msg_type
Static Private Attributes
static F8_TEX_API const FieldTrait _traits []
static F8_TEX_API const FieldTrait_Hash_Array _ftha
static F8_TEX_API const MsgType _msgtype
static F8_TEX_API const unsigned _fieldcnt = 29
Additional Inherited Members
Static Protected Member Functions inherited from FIX8::MessageBase
static unsigned extract_header (const f8String &from, char *len, char *mtype)
static unsigned extract_trailer (const f8String &from, f8String &chksum)
Protected Attributes inherited from FIX8::MessageBase
Fields _fields
FieldTraits _fp
Positions _pos
Groups _groups
const f8String & _msgType
const F8MetaCntx & _ctx
Static Protected Attributes inherited from FIX8::MessageBase
static F8API unsigned _tabsize = defaults::tabsize
Detailed Description
header (header), application, 29 fields, 1 group.
header (header), application, 14 fields, 0 groups.
Definition at line 36766 of file Myfix_classes.hpp.
Constructor & Destructor Documentation
FIX8::TEX::header::header (bool deepctor = true) inline explicit
Definition at line 36778 of file Myfix_classes.hpp.
References add_preamble().
                                        : MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha),
       _begin_string(new begin_string(ctx()._beginStr)), _body_length(new body_length), _msg_type(new msg_type) { add_preamble(); }
FIX8::TEX::header::~header () default
FIX8::TEX::header::header (bool deepctor = true) inline explicit
Definition at line 283 of file Perf_classes.hpp.
References add_preamble().
                                        : MessageBase(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha),
       _begin_string(new begin_string(ctx()._beginStr)), _body_length(new body_length), _msg_type(new msg_type) { add_preamble(); }
FIX8::TEX::header::~header () default
Member Function Documentation
void FIX8::TEX::header::add_preamble () inline
Definition at line 293 of file Perf_classes.hpp.
References FIX8::MessageBase::add_field(), FIX8::Common_BeginString(), FIX8::Common_BodyLength(), and FIX8::Common_MsgType().
    {
       add_field(Common_BeginString, 1, _begin_string, false);
       add_field(Common_BodyLength, 2, _body_length, false);
       add_field(Common_MsgType, 3, _msg_type, false);
    }
void FIX8::TEX::header::add_preamble () inline
Definition at line 36788 of file Myfix_classes.hpp.
References FIX8::MessageBase::add_field(), FIX8::Common_BeginString(), FIX8::Common_BodyLength(), and FIX8::Common_MsgType().
Referenced by header().
    {
       add_field(Common_BeginString, 1, _begin_string, false);
       add_field(Common_BodyLength, 2, _body_length, false);
       add_field(Common_MsgType, 3, _msg_type, false);
    }
GroupBase* FIX8::TEX::header::create_nested_group (unsigned short fnum) const inline virtual
Instantiate a new nested group element.
Parameters
fnum field number of group to create
Returns
new message
Reimplemented from FIX8::MessageBase.
Definition at line 36794 of file Myfix_classes.hpp.
       { return fnum == 627 ? new NoHops : nullptr; }
begin_string* FIX8::TEX::header::get_begin_string () inline virtual
Get pointer to begin_string Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 289 of file Perf_classes.hpp.
References _begin_string.
 { return _begin_string; };
begin_string* FIX8::TEX::header::get_begin_string () inline virtual
Get pointer to begin_string Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 36784 of file Myfix_classes.hpp.
References _begin_string.
 { return _begin_string; };
body_length* FIX8::TEX::header::get_body_length () inline virtual
Get pointer to body_length Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 290 of file Perf_classes.hpp.
References _body_length.
 { return _body_length; };
body_length* FIX8::TEX::header::get_body_length () inline virtual
Get pointer to body_length Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 36785 of file Myfix_classes.hpp.
References _body_length.
 { return _body_length; };
msg_type* FIX8::TEX::header::get_msg_type () inline virtual
Get pointer to msg_type Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 291 of file Perf_classes.hpp.
References _msg_type.
 { return _msg_type; };
msg_type* FIX8::TEX::header::get_msg_type () inline virtual
Get pointer to msg_type Field; used by header/trailer.
Returns
Field
Reimplemented from FIX8::MessageBase.
Definition at line 36786 of file Myfix_classes.hpp.
References _msg_type.
 { return _msg_type; };
static const MsgType& FIX8::TEX::header::get_msgtype () inline static
Definition at line 287 of file Perf_classes.hpp.
References _msgtype.
 { return _msgtype; }
static const MsgType& FIX8::TEX::header::get_msgtype () inline static
Definition at line 36782 of file Myfix_classes.hpp.
References _msgtype.
 { return _msgtype; }
Member Data Documentation
begin_string * FIX8::TEX::header::_begin_string private
Definition at line 36773 of file Myfix_classes.hpp.
Referenced by get_begin_string().
body_length * FIX8::TEX::header::_body_length private
Definition at line 36774 of file Myfix_classes.hpp.
Referenced by get_body_length().
static F8_TEX_API const unsigned FIX8::TEX::header::_fieldcnt = 29 static private
Definition at line 36771 of file Myfix_classes.hpp.
const FieldTrait_Hash_Array FIX8::TEX::header::_ftha static private
Definition at line 36769 of file Myfix_classes.hpp.
msg_type * FIX8::TEX::header::_msg_type private
Definition at line 36775 of file Myfix_classes.hpp.
Referenced by get_msg_type().
const MsgType FIX8::TEX::header::_msgtype static private
Definition at line 36770 of file Myfix_classes.hpp.
Referenced by get_msgtype().
const FieldTrait FIX8::TEX::header::_traits static private
Initial value:
{
   {   8,15,  1,  0,0x64}, {   9, 2,  2,  0,0x64}, {  34, 4, 10,  0,0x05}, {  35,15,  3,  0,0x44},
   {  43, 8, 19,  0,0x04}, {  49,15,  4,  0,0x05}, {  50,15, 11,  0,0x04}, {  52,22, 21,  0,0x05},
   {  56,15,  5,  0,0x05}, {  57,15, 13,  0,0x04}, {  90, 2,  8,  0,0x04}, {  91,28,  9,  0,0x04},
   {  97, 8, 20,  0,0x04}, { 115,15,  6,  0,0x04}, { 116,15, 15,  0,0x04}, { 122,22, 22,  0,0x04},
   { 128,15,  7,  0,0x04}, { 129,15, 17,  0,0x04}, { 142,15, 12,  0,0x04}, { 143,15, 14,  0,0x04},
   { 144,15, 16,  0,0x04}, { 145,15, 18,  0,0x04}, { 212, 2, 23,  0,0x04}, { 213,28, 24,  0,0x04},
   { 347,15, 25,  0,0x04}, { 369, 4, 26,  0,0x04}, { 627, 1, 27, 45,0x1c}, {1128,15, 28,  0,0x04},
   {1129,15, 29,  0,0x04}
}
Definition at line 36768 of file Myfix_classes.hpp.
The documentation for this class was generated from the following files:
Myfix_classes.hpp
Perf_classes.hpp
Myfix_traits.cpp
Perf_traits.cpp