fix8: ff::BufferPool Class Reference
ff::BufferPool Class Reference
#include <ubuffer.hpp>
Public Member Functions
BufferPool (int cachesize, const bool fillcache=false, unsigned long size=-1)
~BufferPool ()
INTERNAL_BUFFER_T * next_w (unsigned long size)
INTERNAL_BUFFER_T * next_r ()
void release (INTERNAL_BUFFER_T *const buf)
void reset ()
Private Attributes
dynqueue inuse
INTERNAL_BUFFER_T bufcache
Detailed Description
It defines a pool of buffers used to create and unbounded SWSR buffer.
This class is defined in ubuffer.hpp
Definition at line 99 of file ubuffer.hpp.
Constructor & Destructor Documentation
ff::BufferPool::BufferPool (int cachesize, const bool fillcache = false, unsigned long size = -1) inline
Definition at line 101 of file ubuffer.hpp.
References bufcache, and INTERNAL_BUFFER_T.
ff::BufferPool::~BufferPool () inline
TODO
Definition at line 129 of file ubuffer.hpp.
References bufcache, INTERNAL_BUFFER_T, inuse, and ff::dynqueue::pop().
Member Function Documentation
INTERNAL_BUFFER_T* ff::BufferPool::next_r () inline
It returns a pointer to the next internal buffer to read
Definition at line 169 of file ubuffer.hpp.
References INTERNAL_BUFFER_T, inuse, and ff::dynqueue::pop().
Referenced by ff::uSWSR_Ptr_Buffer::pop().
INTERNAL_BUFFER_T* ff::BufferPool::next_w (unsigned long size) inline
It returns a pointer to the next internal buffer to write
Definition at line 145 of file ubuffer.hpp.
References bufcache, INTERNAL_BUFFER_T, inuse, and ff::dynqueue::push().
Referenced by ff::uSWSR_Ptr_Buffer::push().
void ff::BufferPool::release (INTERNAL_BUFFER_T *const buf) inline
TODO
Definition at line 177 of file ubuffer.hpp.
References bufcache.
Referenced by ff::uSWSR_Ptr_Buffer::pop(), and reset().
void ff::BufferPool::reset () inline
Definition at line 206 of file ubuffer.hpp.
References INTERNAL_BUFFER_T, inuse, ff::dynqueue::pop(), and release().
Referenced by ff::uSWSR_Ptr_Buffer::reset().
Member Data Documentation
INTERNAL_BUFFER_T ff::BufferPool::bufcache private
Definition at line 220 of file ubuffer.hpp.
Referenced by BufferPool(), next_w(), release(), and ~BufferPool().
dynqueue ff::BufferPool::inuse private
Definition at line 217 of file ubuffer.hpp.
Referenced by next_r(), next_w(), reset(), and ~BufferPool().
The documentation for this class was generated from the following file:
ubuffer.hpp