fix8: FIX8::f8_scoped_lock Class Reference
FIX8::f8_scoped_lock Class Reference
#include <ff_wrapper.hpp>
Public Member Functions
f8_scoped_lock ()
f8_scoped_lock (f8_mutex &f8_mutex)
~f8_scoped_lock ()
void acquire (f8_mutex &f8_mutex)
bool try_acquire (f8_mutex &f8_mutex)
void release ()
Private Member Functions
f8_scoped_lock (const f8_scoped_lock &)
f8_scoped_lock & operator= (const f8_scoped_lock &)
Private Attributes
f8_mutex * _local_mutex
Friends
class f8_mutex
Detailed Description
Definition at line 213 of file ff_wrapper.hpp.
Constructor & Destructor Documentation
FIX8::f8_scoped_lock::f8_scoped_lock (const f8_scoped_lock &) private
FIX8::f8_scoped_lock::f8_scoped_lock () inline
Definition at line 221 of file ff_wrapper.hpp.
FIX8::f8_scoped_lock::f8_scoped_lock (f8_mutex & f8_mutex) inline
Definition at line 222 of file ff_wrapper.hpp.
References acquire().
FIX8::f8_scoped_lock::~f8_scoped_lock () inline
Definition at line 223 of file ff_wrapper.hpp.
References _local_mutex, and release().
Member Function Documentation
void FIX8::f8_scoped_lock::acquire (f8_mutex & f8_mutex) inline
Definition at line 229 of file ff_wrapper.hpp.
References _local_mutex, f8_mutex, and FIX8::f8_mutex::lock().
Referenced by f8_scoped_lock().
f8_scoped_lock& FIX8::f8_scoped_lock::operator= (const f8_scoped_lock &) private
void FIX8::f8_scoped_lock::release () inline
Definition at line 243 of file ff_wrapper.hpp.
References _local_mutex, and FIX8::f8_mutex::unlock().
Referenced by FIX8::Timer< T >::operator()(), and ~f8_scoped_lock().
bool FIX8::f8_scoped_lock::try_acquire (f8_mutex & f8_mutex) inline
Definition at line 235 of file ff_wrapper.hpp.
References _local_mutex, f8_mutex, and FIX8::f8_mutex::try_lock().
Friends And Related Function Documentation
friend class f8_mutex friend
Definition at line 249 of file ff_wrapper.hpp.
Referenced by acquire(), and try_acquire().
Member Data Documentation
f8_mutex* FIX8::f8_scoped_lock::_local_mutex private
Definition at line 215 of file ff_wrapper.hpp.
Referenced by acquire(), release(), try_acquire(), and ~f8_scoped_lock().
The documentation for this class was generated from the following file:
ff_wrapper.hpp