fix8: FIX8::dthread< T >::_helper Class Reference
FIX8::dthread< T >::_helper Class Reference
Public Member Functions
_helper (T &what, int(T::*method)(), dthread_cancellation_token &(T::*cancellation_token_method)())
int operator() ()
dthread_cancellation_token & cancellation_token ()
Private Attributes
T & _what
int(T::* _method)()
dthread_cancellation_token &(T::* _cancellation_token_method)()
Detailed Description
template<typename T>
class FIX8::dthread< T >::_helper
Definition at line 293 of file thread.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::dthread< T >::_helper::_helper (T & what, int(T::*)() method, dthread_cancellation_token &(T::*)() cancellation_token_method) inline
Definition at line 300 of file thread.hpp.
Member Function Documentation
template<typename T> dthread_cancellation_token& FIX8::dthread< T >::_helper::cancellation_token () inline
Definition at line 317 of file thread.hpp.
References FIX8::dthread< T >::_helper::_cancellation_token_method, and FIX8::dthread< T >::_helper::_what.
Referenced by FIX8::dthread< FIX8::Timer >::join(), FIX8::dthread< T >::_helper::operator()(), and FIX8::dthread< FIX8::Timer >::request_stop().
template<typename T> int FIX8::dthread< T >::_helper::operator() () inline
Definition at line 302 of file thread.hpp.
References FIX8::dthread< T >::_helper::_method, FIX8::dthread< T >::_helper::_what, FIX8::dthread< T >::_helper::cancellation_token(), FIX8::dthread_cancellation_token::Running, FIX8::dthread_cancellation_token::Stopped, and FIX8::dthread_cancellation_token::thread_state().
Member Data Documentation
template<typename T> dthread_cancellation_token&(T::* FIX8::dthread< T >::_helper::_cancellation_token_method)() private
Definition at line 297 of file thread.hpp.
Referenced by FIX8::dthread< T >::_helper::cancellation_token().
template<typename T> int(T::* FIX8::dthread< T >::_helper::_method)() private
Definition at line 296 of file thread.hpp.
Referenced by FIX8::dthread< T >::_helper::operator()().
template<typename T> T& FIX8::dthread< T >::_helper::_what private
Definition at line 295 of file thread.hpp.
Referenced by FIX8::dthread< T >::_helper::cancellation_token(), and FIX8::dthread< T >::_helper::operator()().
The documentation for this class was generated from the following file:
thread.hpp