fix8: FIX8::Thread< T > Class Template Reference
FIX8::Thread< T > Class Template Reference
Modern POSIX pthread wrapper. Thread by pointer to member function. Ctor provides T instance and specifies ptr to member to call or defaults to operator()
#include <thread.hpp>
Classes
class _helper
Public Member Functions
Thread (T what, int(T::*method)()=&T::operator(), const bool detach=false, const size_t stacksize=0) throw (ThreadException)
Thread (reference_wrapper< T > what, int(T::*method)()=&T::operator(), const bool detach=false, const size_t stacksize=0) throw (ThreadException)
virtual ~Thread ()
Dtor.
int Start ()
Public Member Functions inherited from FIX8::_threadbase
_threadbase (const bool detach, const size_t stacksize) throw (ThreadException)
virtual ~_threadbase ()
Dtor.
int Join ()
void Exit (int exitvalue) const
int GetExitVal () const
void Kill (int signum) const
pthread_t GetThreadID () const
bool operator== (const _threadbase &that) const
bool operator!= (const _threadbase &that) const
Private Attributes
class FIX8::Thread::_helper _sub
Additional Inherited Members
Static Public Member Functions inherited from FIX8::_threadbase
static bool Kill (_threadbase &ctxt, const int signal=SIGTERM)
static pthread_t GetID ()
static bool SetSignalMask (const int how, const sigset_t *newmask, sigset_t *oldmask)
static bool SignalWait (const sigset_t *set, int *sig)
Protected Member Functions inherited from FIX8::_threadbase
template<typename T >
int _Start (void *sub)
Detailed Description
template<typename T = void *>
class FIX8::Thread< T >
Modern POSIX pthread wrapper. Thread by pointer to member function. Ctor provides T instance and specifies ptr to member to call or defaults to operator()
Template Parameters
T class call thread entry functor
Definition at line 188 of file thread.hpp.
Constructor & Destructor Documentation
template<typename T = void *> FIX8::Thread< T >::Thread (T what, int(T::*)() method = &T::operator(), const bool detach = false, const size_t stacksize = 0) throw (ThreadException) inline
Ctor. Pointer to object, functor version.
Parameters
what instance of class with entry point
method pointer to entry point method
detach detach thread if true
stacksize default thread stacksize
Definition at line 207 of file thread.hpp.
template<typename T = void *> FIX8::Thread< T >::Thread (reference_wrapper< T > what, int(T::*)() method = &T::operator(), const bool detach = false, const size_t stacksize = 0) throw (ThreadException) inline
Ctor. Reference to object, functor version.
Parameters
what reference wrapper of class with entry point
method reference to entry point method
detach detach thread if true
stacksize default thread stacksize
Definition at line 215 of file thread.hpp.
template<typename T = void *> virtual FIX8::Thread< T >::~Thread () inline virtual
Dtor.
Definition at line 219 of file thread.hpp.
Member Function Documentation
template<typename T = void *> int FIX8::Thread< T >::Start () inline virtual
Start thread.
Returns
function result
Implements FIX8::_threadbase.
Definition at line 223 of file thread.hpp.
Referenced by FIX8::Logger::Logger(), FIX8::AsyncSocket< f8String >::start(), FIX8::Timer< Session >::start(), FIX8::FIXReader::start(), and FIX8::ReliableClientSession< T >::start().
Member Data Documentation
template<typename T = void *> class FIX8::Thread::_helper FIX8::Thread< T >::_sub private
Referenced by FIX8::Thread< FIXReader >::Start(), and FIX8::Thread<>::Start().
The documentation for this class was generated from the following file:
thread.hpp