fix8: FIX8::_dthreadcore Class Reference
FIX8::_dthreadcore Class Reference
pthread wrapper abstract base
#include <thread.hpp>
Public Member Functions
_dthreadcore (const bool detach, const size_t stacksize) throw (dthreadException)
virtual ~_dthreadcore ()
Dtor.
virtual int start ()=0
int join ()
void exit (int exitvalue) const
int getexitval () const
int yield () const
void kill (int signum) const
pthread_t getdthreadid () const
bool operator== (const _dthreadcore &that) const
bool operator!= (const _dthreadcore &that) const
Static Public Member Functions
static bool kill (_dthreadcore &ctxt, const int signal=SIGTERM)
static pthread_t getid ()
static bool setsignalmask (const int how, const sigset_t *newmask, sigset_t *oldmask)
static bool signalwait (const sigset_t *set, int *sig)
Protected Member Functions
template<typename T >
int _start (void *sub)
Private Member Functions
_dthreadcore & operator= (const _dthreadcore &)
Static Private Member Functions
template<typename T >
static void * _run (void *what)
Private Attributes
pthread_attr_t _attr
pthread_t _tid
int _exitval
Detailed Description
pthread wrapper abstract base
Definition at line 86 of file thread.hpp.
Constructor & Destructor Documentation
FIX8::_dthreadcore::_dthreadcore (const bool detach, const size_t stacksize) throw (dthreadException) inline
Ctor.
Parameters
detach detach thread if true
stacksize default thread stacksize
Definition at line 107 of file thread.hpp.
References _attr.
virtual FIX8::_dthreadcore::~_dthreadcore () inline virtual
Dtor.
Definition at line 118 of file thread.hpp.
References _attr.
Member Function Documentation
template<typename T > static void* FIX8::_dthreadcore::_run (void * what) inline static private
Definition at line 93 of file thread.hpp.
template<typename T > int FIX8::_dthreadcore::_start (void * sub) inline protected
Definition at line 101 of file thread.hpp.
References _attr, and _tid.
void FIX8::_dthreadcore::exit (int exitvalue) const inline
Cause the thread to exit.
Parameters
exitvalue value to return to calling process
Definition at line 131 of file thread.hpp.
pthread_t FIX8::_dthreadcore::getdthreadid () const inline
Get the thread's thread ID.
Returns
the thread id
Definition at line 154 of file thread.hpp.
References _tid.
int FIX8::_dthreadcore::getexitval () const inline
Recover the thread's exit value.
Returns
exit value from to calling process
Definition at line 135 of file thread.hpp.
References _exitval.
static pthread_t FIX8::_dthreadcore::getid () inline static
Get the thread's thread ID. Static version.
Returns
the thread id
Definition at line 158 of file thread.hpp.
int FIX8::_dthreadcore::join () inline
Join the thread.
Returns
result of join
Definition at line 126 of file thread.hpp.
References _exitval, and _tid.
Referenced by FIX8::AsyncSocket< f8String >::join(), FIX8::Timer< Session >::join(), FIX8::Logger::stop(), and FIX8::BDBPersister::stop().
void FIX8::_dthreadcore::kill (int signum) const inline
Kill the thread.
Parameters
signum signal number to send
Definition at line 143 of file thread.hpp.
References _tid.
Referenced by FIX8::Timer< Session >::kill(), FIX8::AsyncSocket< f8String >::quit(), and FIX8::FIXReader::quit().
static bool FIX8::_dthreadcore::kill (_dthreadcore & ctxt, const int signal = SIGTERM) inline static
Kill the thread. Static version.
Parameters
ctxt thread context to kill
signal signal number to send
Returns
true on success
Definition at line 149 of file thread.hpp.
References _tid.
bool FIX8::_dthreadcore::operator!= (const _dthreadcore & that) const inline
dthread inequivalence operator.
Parameters
that the other thread id
Returns
true if the threads are unequal
Definition at line 168 of file thread.hpp.
References _tid.
_dthreadcore& FIX8::_dthreadcore::operator= (const _dthreadcore &) private
bool FIX8::_dthreadcore::operator== (const _dthreadcore & that) const inline
dthread equivalence operator.
Parameters
that the other thread id
Returns
true if the threads are equal
Definition at line 163 of file thread.hpp.
References _tid.
static bool FIX8::_dthreadcore::setsignalmask (const int how, const sigset_t * newmask, sigset_t * oldmask) inline static
Set the thread signal mask.
Parameters
how block, unblock or mask
newmask new mask
oldmask old mask
Returns
true on success
Definition at line 175 of file thread.hpp.
static bool FIX8::_dthreadcore::signalwait (const sigset_t * set, int * sig) inline static
Wait for a specified signal.
Parameters
set signal set
sig new mask
Returns
true on success
Definition at line 182 of file thread.hpp.
virtual int FIX8::_dthreadcore::start () pure virtual
start thread.
Returns
function result
Implemented in FIX8::dthread<>, FIX8::dthread< T >, FIX8::dthread< Timer >, FIX8::dthread< BDBPersister >, FIX8::dthread< AsyncSocket >, FIX8::dthread< Logger >, FIX8::dthread< ReliableClientSession< T > >, and FIX8::dthread< FIXReader >.
int FIX8::_dthreadcore::yield () const inline
Yield CPU.
Returns
result of yield
Definition at line 139 of file thread.hpp.
Member Data Documentation
pthread_attr_t FIX8::_dthreadcore::_attr private
Definition at line 88 of file thread.hpp.
Referenced by _dthreadcore(), _start(), and ~_dthreadcore().
int FIX8::_dthreadcore::_exitval private
Definition at line 90 of file thread.hpp.
Referenced by getexitval(), and join().
pthread_t FIX8::_dthreadcore::_tid private
Definition at line 89 of file thread.hpp.
Referenced by _start(), getdthreadid(), join(), kill(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
thread.hpp