fix8: ff::ff_node::thWorker Class Reference
ff::ff_node::thWorker Class Reference
An inner class for FastFlow's thread.
Public Member Functions
thWorker (ff_node *const filter)
Constructor.
bool push (void *task)
Pushes the task.
bool pop (void **task)
Pops the task.
bool put (void *ptr)
Puts the task in buffer.
bool get (void **ptr)
Gets the task from the buffer.
void svc_createOCL ()
Creates OCL.
void svc_releaseOCL ()
Releases OCL.
void * svc (void *)
The svc method.
int svc_init ()
The svc_init method.
virtual void svc_end ()
The svc_end method.
int run ()
Executes FastFlow thread.
int wait ()
Waits the thread.
int wait_freezing ()
Waits for freezing.
void freeze ()
Freezes the thread.
bool isfrozen ()
Checks if the thread is frozen.
int get_my_id () const
Gets the ID of the thread.
Public Member Functions inherited from ff::ff_thread
void set_barrier (BARRIER_T *const b)
Sets the barrier object.
int spawn (int cpuId=-1)
Creates a new thread.
int wait ()
Waits for thread termination.
int wait_freezing ()
Waits for thread freezing.
void stop ()
Forces the thread to stop.
void freeze ()
Forces the thread to freeze.
void thaw (bool _freeze=false)
Thaw the thread, if it is frozen.
bool isfrozen ()
Checks if the thread is frozen.
pthread_t get_handle () const
Gets the pthread handler.
int getTid () const
Gets the internal unique thread identifier.
Protected Attributes
ff_node *const filter
Protected Attributes inherited from ff::ff_thread
unsigned tid
Additional Inherited Members
Protected Member Functions inherited from ff::ff_thread
ff_thread (BARRIER_T *barrier=NULL)
Constructor.
virtual ~ff_thread ()
Destructor.
void thread_routine ()
The life cycle of FastFlow thread.
int disable_cancelability ()
Disable the cancelation of thread.
int enable_cancelability ()
Makes thread cancelable.
Detailed Description
An inner class for FastFlow's thread.
It is an inner class that wraps ff_thread functions and adds push and pop methods.
Definition at line 1344 of file node.hpp.
Constructor & Destructor Documentation
ff::ff_node::thWorker::thWorker (ff_node *const filter) inline
Constructor.
It is contructor to create FastFlow thread.
filter is a pointer to FastFlow's node
Definition at line 1354 of file node.hpp.
Member Function Documentation
void ff::ff_node::thWorker::freeze () inline
Freezes the thread.
It freezes the thread.
Definition at line 1562 of file node.hpp.
References ff::ff_thread::freeze().
Referenced by ff::ff_node::freeze().
bool ff::ff_node::thWorker::get (void ** ptr) inline
Gets the task from the buffer.
It gets the task from the buffer.
Returns
The status of get function as Boolean value.
Definition at line 1426 of file node.hpp.
References filter, and ff::ff_node::get().
int ff::ff_node::thWorker::get_my_id () const inline
Gets the ID of the thread.
It returns the ID of the thread.
Returns
An integer value showing the identifier of the thread.
Definition at line 1580 of file node.hpp.
References filter, and ff::ff_node::get_my_id().
bool ff::ff_node::thWorker::isfrozen () inline
Checks if the thread is frozen.
It checks if the thread is frozen.
Returns
the status of the isfrozen() method.
Definition at line 1571 of file node.hpp.
References ff::ff_thread::isfrozen().
Referenced by ff::ff_node::isfrozen().
bool ff::ff_node::thWorker::pop (void ** task) inline
Pops the task.
It pops the task from the buffer of the filter.
is a pointer to the task
Returns
true is always returned.
Definition at line 1391 of file node.hpp.
References FFTRACE, filter, ff::ff_node::in_active, ff::ff_node::pop(), ff::ff_node::TICKS2WAIT, and ff::ticks_wait().
Referenced by svc().
bool ff::ff_node::thWorker::push (void * task) inline
Pushes the task.
It pushes the task to the filter
task is a pointer to the task.
Returns
true is always returned.
Definition at line 1366 of file node.hpp.
References FFTRACE, filter, ff::ff_node::push(), ff::ff_node::TICKS2WAIT, and ff::ticks_wait().
Referenced by svc().
bool ff::ff_node::thWorker::put (void * ptr) inline
Puts the task in buffer.
It pushes the task in the filter.
ptr is a pointer to the task.
Definition at line 1417 of file node.hpp.
References filter, and ff::ff_node::put().
int ff::ff_node::thWorker::run () inline
Executes FastFlow thread.
It executs the FastFlow thread.
Returns
The status of spawn method.
Definition at line 1533 of file node.hpp.
References ff::ff_node::CPUId, filter, ff::ff_node::getCPUId(), ff::ff_node::setCPUId(), and ff::ff_thread::spawn().
Referenced by ff::ff_node::freeze_and_run(), and ff::ff_node::run().
void* ff::ff_node::thWorker::svc (void *) inline virtual
The svc method.
It defines the svc method of the FastFlow.
Implements ff::ff_thread.
Definition at line 1448 of file node.hpp.
References ff::diffmsec(), ff::ff_node::eosnotify(), ff::FF_EOS, ff::FF_EOS_NOFREEZE, FFTRACE, filter, ff::ff_node::get_in_buffer(), ff::ff_node::get_out_buffer(), GO_ON, pop(), push(), ff::ff_node::skipfirstpop(), ff::ff_node::svc(), svc_createOCL(), ff::ff_node::wtstart, ff::ff_node::wtstop, and ff::ff_node::wttime.
void ff::ff_node::thWorker::svc_createOCL () inline virtual
Creates OCL.
It creates OCL.
Reimplemented from ff::ff_thread.
Definition at line 1433 of file node.hpp.
References filter, and svc_createOCL().
Referenced by svc(), and svc_createOCL().
virtual void ff::ff_node::thWorker::svc_end () inline virtual
The svc_end method.
It defines the svc_end method of the FastFlow.
Reimplemented from ff::ff_thread.
Definition at line 1521 of file node.hpp.
References filter, ff::ff_node::svc_end(), and ff::ff_node::tstop.
int ff::ff_node::thWorker::svc_init () inline virtual
The svc_init method.
It defines the svc_init method of FastFlow.
Returns
The status of svc_init() method.
Reimplemented from ff::ff_thread.
Definition at line 1505 of file node.hpp.
References ff::error(), ff_mapThreadToCpu(), filter, ff::ff_node::getCPUId(), ff::threadMapper::instance(), ff::ff_node::setCPUId(), ff::ff_node::svc_init(), ff::ff_thread::tid, and ff::ff_node::tstart.
void ff::ff_node::thWorker::svc_releaseOCL () inline virtual
Releases OCL.
It releases OCL.
Reimplemented from ff::ff_thread.
Definition at line 1440 of file node.hpp.
References filter, and svc_releaseOCL().
Referenced by svc_releaseOCL().
int ff::ff_node::thWorker::wait () inline
Waits the thread.
It waits for the thread.
Returns
The staus of wait() method.
Definition at line 1546 of file node.hpp.
References ff::ff_thread::wait().
Referenced by ff::ff_node::wait().
int ff::ff_node::thWorker::wait_freezing () inline
Waits for freezing.
It waits the thread to freeze.
Returns
The status of wait_freezing() method.
Definition at line 1555 of file node.hpp.
References ff::ff_thread::wait_freezing().
Referenced by ff::ff_node::wait_freezing().
Member Data Documentation
ff_node* const ff::ff_node::thWorker::filter protected
Definition at line 1580 of file node.hpp.
Referenced by get(), get_my_id(), pop(), push(), put(), run(), svc(), svc_createOCL(), svc_end(), svc_init(), and svc_releaseOCL().
The documentation for this class was generated from the following file:
node.hpp