fix8: FIX8::Field< double, field > Class Template Reference
FIX8::Field< double, field > Class Template Reference
Partial specialisation for double field type.
#include <field.hpp>
Public Member Functions
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const double &val, const RealmBase *rlm=0)
Field (const double &val, const int prec, const RealmBase *rlm=0)
Field (const f8String &from, const RealmBase *rlm=0)
Field & operator= (const Field &that)
Assignment operator.
void set_precision (const int prec)
virtual ~Field ()
Dtor.
virtual bool is_valid () const
virtual int get_rlm_idx () const
virtual const double & get () const
virtual const double & operator() () const
virtual const double & set (const double &from)
virtual const double & set_from_raw (const f8String &from)
virtual Field * copy ()
virtual std::ostream & print (std::ostream &os) const
virtual void print (char *to, size_t &sz) const
Public Member Functions inherited from FIX8::BaseField
BaseField (const unsigned short fnum, const RealmBase *rlm=0)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
template<typename T >
T & from ()
size_t encode (std::ostream &os) const
size_t encode (char *to, size_t &sz) const
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
The FIX fieldID (tag number).
Protected Attributes
double _value
int _precision
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<const unsigned short field>
class FIX8::Field< double, field >
Partial specialisation for double field type.
Template Parameters
field field number (fix tag)
Definition at line 397 of file field.hpp.
Constructor & Destructor Documentation
template<const unsigned short field> FIX8::Field< double, field >::Field () inline
Ctor.
Reimplemented in FIX8::Field< Qty, field >.
Definition at line 408 of file field.hpp.
template<const unsigned short field> FIX8::Field< double, field >::Field (const Field< double, field > & from) inline
Copy Ctor.
Definition at line 412 of file field.hpp.
template<const unsigned short field> FIX8::Field< double, field >::Field (const double & val, const RealmBase * rlm = 0) inline
Value ctor.
Parameters
val value to set
rlm pointer to the realmbase for this field (if available)
Reimplemented in FIX8::Field< Qty, field >.
Definition at line 417 of file field.hpp.
template<const unsigned short field> FIX8::Field< double, field >::Field (const double & val, const int prec, const RealmBase * rlm = 0) inline
Value ctor.
Parameters
val value to set
prec precision digits
rlm pointer to the realmbase for this field (if available)
Definition at line 423 of file field.hpp.
template<const unsigned short field> FIX8::Field< double, field >::Field (const f8String & from, const RealmBase * rlm = 0) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Reimplemented in FIX8::Field< Qty, field >.
Definition at line 428 of file field.hpp.
template<const unsigned short field> virtual FIX8::Field< double, field >::~Field () inline virtual
Dtor.
Reimplemented in FIX8::Field< Qty, field >.
Definition at line 445 of file field.hpp.
Member Function Documentation
template<const unsigned short field> virtual Field* FIX8::Field< double, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 475 of file field.hpp.
References FIX8::Field< T, field >::Field().
template<const unsigned short field> virtual const double& FIX8::Field< double, field >::get () const inline virtual
Get field value.
Returns
value (double)
Definition at line 457 of file field.hpp.
template<const unsigned short field> static unsigned short FIX8::Field< double, field >::get_field_id () inline static
The FIX fieldID (tag number).
Reimplemented in FIX8::Field< Qty, field >.
Definition at line 405 of file field.hpp.
template<const unsigned short field> virtual int FIX8::Field< double, field >::get_rlm_idx () const inline virtual
Get the realm index of this value in the domain set.
Returns
the index in the domain set of this value
Reimplemented from FIX8::BaseField.
Definition at line 453 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::get_rlm_idx().
template<const unsigned short field> virtual bool FIX8::Field< double, field >::is_valid () const inline virtual
Check if this value is a member/in range of the domain set.
Returns
true if in the set or no domain available
Definition at line 449 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::is_valid().
template<const unsigned short field> virtual const double& FIX8::Field< double, field >::operator() () const inline virtual
Get field value.
Returns
value (double)
Definition at line 461 of file field.hpp.
template<const unsigned short field> Field& FIX8::Field< double, field >::operator= (const Field< double, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 433 of file field.hpp.
template<const unsigned short field> virtual std::ostream& FIX8::Field< double, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 480 of file field.hpp.
template<const unsigned short field> virtual void FIX8::Field< double, field >::print (char * to, size_t & sz) const inline virtual
Print this field to the supplied buffer, update size written.
Parameters
to buffer to print to
sz current size of buffer payload stream
Implements FIX8::BaseField.
Definition at line 485 of file field.hpp.
template<const unsigned short field> virtual const double& FIX8::Field< double, field >::set (const double & from) inline virtual
Get field value.
Parameters
from value to set
Returns
original value (int)
Definition at line 466 of file field.hpp.
References FIX8::BaseField::from().
template<const unsigned short field> virtual const double& FIX8::Field< double, field >::set_from_raw (const f8String & from) inline virtual
Set the value from a string.
Parameters
from value to set
Returns
original value (double)
Definition at line 471 of file field.hpp.
References FIX8::fast_atof().
template<const unsigned short field> void FIX8::Field< double, field >::set_precision (const int prec) inline
Set the output precision
Parameters
prec precision digits
Definition at line 442 of file field.hpp.
Member Data Documentation
template<const unsigned short field> int FIX8::Field< double, field >::_precision protected
Definition at line 401 of file field.hpp.
template<const unsigned short field> double FIX8::Field< double, field >::_value protected
Definition at line 400 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp