fix8: FIX8::Field< UTCTimeOnly, field > Class Template Reference
FIX8::Field< UTCTimeOnly, field > Class Template Reference
Partial specialisation for UTCTimeOnly field type.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const f8String &from, const RealmBase *rlm=nullptr)
Field (const char *from, const RealmBase *rlm=nullptr)
Field (const tm &from, const RealmBase *rlm=nullptr)
Field & operator= (const Field &that)
Assignment operator.
~Field ()
Dtor.
const Tickval & get () const
const Tickval & operator() () const
void set (const Tickval &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (const unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
virtual int get_rlm_idx () const
template<typename T >
T & from ()
size_t encode (std::ostream &os) const
size_t encode (char *to) const
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Private Attributes
Tickval _value
Static Private Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_string
Additional Inherited Members
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<const unsigned short field>
class FIX8::Field< UTCTimeOnly, field >
Partial specialisation for UTCTimeOnly field type.
Template Parameters
field field number (fix tag)
Definition at line 986 of file field.hpp.
Constructor & Destructor Documentation
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::Field () inline
Ctor.
Definition at line 999 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::Field (const Field< UTCTimeOnly, field > & from) inline
Copy Ctor.
Definition at line 1003 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 1008 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 1013 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::Field (const tm & from, const RealmBase * rlm = nullptr) inline
Construct from tm struct
Parameters
from string to construct field from
rlm tm struct with broken out values
Definition at line 1018 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimeOnly, field >::~Field () inline
Dtor.
Definition at line 1031 of file field.hpp.
Member Function Documentation
template<const unsigned short field> Field* FIX8::Field< UTCTimeOnly, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 1047 of file field.hpp.
References FIX8::Field< T, field >::Field().
template<const unsigned short field> const Tickval& FIX8::Field< UTCTimeOnly, field >::get () const inline
Get field value.
Returns
value Tickval&
Definition at line 1035 of file field.hpp.
template<const unsigned short field> static unsigned short FIX8::Field< UTCTimeOnly, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 993 of file field.hpp.
template<const unsigned short field> FieldTrait::FieldType FIX8::Field< UTCTimeOnly, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 996 of file field.hpp.
template<const unsigned short field> const Tickval& FIX8::Field< UTCTimeOnly, field >::operator() () const inline
Get field value.
Returns
value Tickval&
Definition at line 1039 of file field.hpp.
template<const unsigned short field> Field& FIX8::Field< UTCTimeOnly, field >::operator= (const Field< UTCTimeOnly, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 1023 of file field.hpp.
template<const unsigned short field> std::ostream& FIX8::Field< UTCTimeOnly, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 1052 of file field.hpp.
References FIX8::MAX_MSGTYPE_FIELD_LEN(), and FIX8::BaseField::print().
template<const unsigned short field> size_t FIX8::Field< UTCTimeOnly, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 1062 of file field.hpp.
References FIX8::_time_with_ms, and FIX8::date_time_format().
template<const unsigned short field> void FIX8::Field< UTCTimeOnly, field >::set (const Tickval & from) inline
Set field to the supplied value.
Parameters
from value to set
Definition at line 1043 of file field.hpp.
References FIX8::BaseField::from().
Member Data Documentation
template<const unsigned short field> const FieldTrait::FieldType FIX8::Field< UTCTimeOnly, field >::_ftype = FieldTrait::ft_string static private
Definition at line 989 of file field.hpp.
template<const unsigned short field> Tickval FIX8::Field< UTCTimeOnly, field >::_value private
Definition at line 988 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp