fix8: UsageMan Class Reference
UsageMan Class Reference
Convenient program help/usage wrapper. Generates a standardised usage message.
#include <usage.hpp>
Public Member Functions
UsageMan (const std::string &prognm, const std::string &argstr, const std::string &params, int splen=3, int argoptlen=23)
virtual ~UsageMan ()
Dtor.
bool add (const char sw, const std::string &lsw, const std::string &help)
void add (const std::string &xtr)
void setdesc (const std::string &desc)
void print (std::ostream &os) const
Private Types
using OPTEL = std::map< const char, const std::pair< const std::string, const std::string >>
Private Attributes
const std::string prognm_
const std::string params_
std::string argstr_
std::string description_
OPTEL optels_
std::list< std::string > xtrlines_
const int splen_
const int argoptlen_
Detailed Description
Convenient program help/usage wrapper. Generates a standardised usage message.
Definition at line 42 of file usage.hpp.
Member Typedef Documentation
using UsageMan::OPTEL = std::map<const char, const std::pair<const std::string, const std::string>> private
Definition at line 46 of file usage.hpp.
Constructor & Destructor Documentation
UsageMan::UsageMan (const std::string & prognm, const std::string & argstr, const std::string & params, int splen = 3, int argoptlen = 23) inline
Ctor.
Parameters
prognm program name
argstr program arguments string
params program non-switched arguments string
splen tab width
argoptlen option argument width
Definition at line 58 of file usage.hpp.
       : prognm_(prognm), params_(params), argstr_(argstr), splen_(splen), argoptlen_(argoptlen)
    {
       std::sort(argstr_.begin(), argstr_.end());
    }
virtual UsageMan::~UsageMan () inline virtual
Dtor.
Definition at line 66 of file usage.hpp.
 {}
Member Function Documentation
bool UsageMan::add (const char sw, const std::string & lsw, const std::string & help) inline
Add a command line option.
Parameters
sw the single character switch
lsw the string switch (long version)
help the associated help string
Returns
true on success
Definition at line 73 of file usage.hpp.
Referenced by print_usage().
    {
       return optels_.insert({sw, std::pair<const std::string, const std::string>(lsw, help)}).second;
    }
void UsageMan::add (const std::string & xtr) inline
Add an extra help line. Lines prefixed with '@' are indented one tabstop.
Parameters
xtr the extra help line
Definition at line 80 of file usage.hpp.
    {
       std::string topush(xtr);
       std::string::size_type spos;
       while ((spos = topush.find_first_of('@')) != std::string::npos)
          topush.replace(spos, 1, std::string(splen_, ' '));
       xtrlines_.push_back(topush);
    }
void UsageMan::print (std::ostream & os) const inline
Insert the formatted usage into the given output stream.
Parameters
os the stream to insert to
Definition at line 95 of file usage.hpp.
References spacer.
Referenced by print_usage().
    {
       if (!description_.empty())
          os << description_ << std::endl << std::endl;
       os << "Usage: " << prognm_ << " [-";
       for (std::string::const_iterator itr(argstr_.begin()); itr != argstr_.end(); ++itr)
          if (*itr != ':')
             os << *itr;
       os << "] " << params_ << std::endl;
       const std::string spacer(splen_, ' ');
       for (OPTEL::const_iterator itr(optels_.begin()); itr != optels_.end(); ++itr)
       {
          std::ostringstream ostr;
          ostr << '-' << itr->first << ",--" << itr->second.first;
          os << spacer << std::left << std::setw(argoptlen_) << ostr.str()
             << ' ' << itr->second.second << std::endl;
       }
       for (std::list<std::string>::const_iterator itr(xtrlines_.begin()); itr != xtrlines_.end(); ++itr)
          os << *itr << std::endl;
    }
void UsageMan::setdesc (const std::string & desc) inline
Set the usage description string.
Parameters
desc the description string
Definition at line 91 of file usage.hpp.
Referenced by print_usage().
 { description_ = desc; }
Member Data Documentation
const int UsageMan::argoptlen_ private
Definition at line 49 of file usage.hpp.
std::string UsageMan::argstr_ private
Definition at line 45 of file usage.hpp.
std::string UsageMan::description_ private
Definition at line 45 of file usage.hpp.
OPTEL UsageMan::optels_ private
Definition at line 47 of file usage.hpp.
const std::string UsageMan::params_ private
Definition at line 44 of file usage.hpp.
const std::string UsageMan::prognm_ private
Definition at line 44 of file usage.hpp.
const int UsageMan::splen_ private
Definition at line 49 of file usage.hpp.
std::list<std::string> UsageMan::xtrlines_ private
Definition at line 48 of file usage.hpp.
The documentation for this class was generated from the following file:
usage.hpp