fix8: FIX8::BaseField Class Reference
FIX8::BaseField Class Reference abstract
The base field class (ABC) for all fields.
#include <field.hpp>
Public Member Functions
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
virtual std::ostream & print (std::ostream &os) const =0
virtual size_t print (char *to) const =0
virtual FieldTrait::FieldType get_underlying_type () const =0
virtual BaseField * copy ()=0
virtual int get_rlm_idx () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
virtual bool operator== (const BaseField &that) const =0
Equivalence operator.
virtual bool operator< (const BaseField &that) const =0
Less than operator.
virtual bool operator> (const BaseField &that) const =0
Greater than operator.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Protected Attributes
const RealmBase * _rlm
Private Attributes
const unsigned short _fnum
Friends
class MessageBase
std::ostream & operator<< (std::ostream &os, const BaseField &what)
Detailed Description
The base field class (ABC) for all fields.
Definition at line 127 of file field.hpp.
Constructor & Destructor Documentation
FIX8::BaseField::BaseField (unsigned short fnum, const RealmBase * rlm = nullptr) inline
Ctor.
Parameters
fnum field num for this field
rlm pointer to the realmbase for this field (if available)
Definition at line 138 of file field.hpp.
 : _fnum(fnum), _rlm(rlm) {}
virtual FIX8::BaseField::~BaseField () inline virtual
Dtor.
Definition at line 141 of file field.hpp.
 {}
Member Function Documentation
template<typename T > const T* FIX8::BaseField::as () const inline
Cast this field to the supplied type.
Template Parameters
T target type
Returns
pointer to the cast field
Definition at line 179 of file field.hpp.
 { return static_cast<T*>(this); }
virtual BaseField* FIX8::BaseField::copy () pure virtual
Copy this field.
Returns
the copy
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
size_t FIX8::BaseField::encode (std::ostream & os) const inline
Encode this field to the supplied stream.
Parameters
os stream to encode to
Returns
the number of bytes encoded
Definition at line 184 of file field.hpp.
References _fnum, FIX8::default_assignment_separator(), and FIX8::default_field_separator().
    {
       const std::ios::pos_type where(os.tellp());
       os << _fnum << default_assignment_separator << *this << default_field_separator;
       return os.tellp() - where;
    }
size_t FIX8::BaseField::encode (char * to) const inline
Encode this field to the supplied stream. ULL version.
Parameters
to buffer to encode to
Returns
the number of bytes encoded
Definition at line 194 of file field.hpp.
References _fnum, FIX8::default_assignment_separator(), FIX8::default_field_separator(), FIX8::itoa(), and print().
    {
       const char *cur_ptr(to);
       to += itoa(_fnum, to, 10);
       *to++ = default_assignment_separator;
       to += print(to);
       *to++ = default_field_separator;
       return to - cur_ptr;
    }
template<typename T > T& FIX8::BaseField::from () inline
Cast this field to the supplied type.
Template Parameters
T target type
Returns
reference to the cast field
Definition at line 173 of file field.hpp.
Referenced by FIX8::Field< int, field >::set(), FIX8::Field< f8String, field >::set(), FIX8::Field< fp_type, field >::set(), FIX8::Field< char, field >::set(), FIX8::Field< UTCTimestamp, field >::set(), FIX8::Field< UTCTimeOnly, field >::set(), FIX8::Field< UTCDateOnly, field >::set(), FIX8::Field< LocalMktDate, field >::set(), FIX8::Field< MonthYear, field >::set(), FIX8::Field< TZTimeOnly, field >::set(), FIX8::Field< TZTimestamp, field >::set(), FIX8::Field< Boolean, field >::set(), and FIX8::Field< f8String, field >::set_from_raw().
 { return *static_cast<T*>(this); }
const RealmBase* FIX8::BaseField::get_realm () const inline
Get the realm pointer for this field.
Returns
the realm pointer
Definition at line 241 of file field.hpp.
References _rlm.
 { return _rlm; }
virtual int FIX8::BaseField::get_rlm_idx () const inline virtual
Get the realm index of this field.
Returns
the realm index
Reimplemented in FIX8::Field< Boolean, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
Definition at line 167 of file field.hpp.
 { return -1; }
unsigned short FIX8::BaseField::get_tag () const inline
Get the fix tag id of this field.
Returns
fix tag id (field num)
Definition at line 145 of file field.hpp.
References _fnum.
Referenced by FIX8::ConsoleMenu::EditMsg().
 { return _fnum; }
virtual FieldTrait::FieldType FIX8::BaseField::get_underlying_type () const pure virtual
Get the underlying FieldType for this field
Returns
field type
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
bool FIX8::BaseField::operator!= (const BaseField & that) const inline
Inequivalence operator.
Parameters
that field to compare
Returns
true if not the same
Definition at line 227 of file field.hpp.
 { return !(*this == that); }
virtual bool FIX8::BaseField::operator< (const BaseField & that) const pure virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
bool FIX8::BaseField::operator<= (const BaseField & that) const inline
Less or equal to operator.
Parameters
that field to compare
Returns
true if less than or equal to
Definition at line 232 of file field.hpp.
 { return *this < that || *this == that; }
virtual bool FIX8::BaseField::operator== (const BaseField & that) const pure virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
virtual bool FIX8::BaseField::operator> (const BaseField & that) const pure virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
bool FIX8::BaseField::operator>= (const BaseField & that) const inline
Greater or equal to operator.
Parameters
that field to compare
Returns
true if greater than or equal to
Definition at line 237 of file field.hpp.
 { return *this > that || *this == that; }
virtual std::ostream& FIX8::BaseField::print (std::ostream & os) const pure virtual
Print this field to the supplied stream. Used by the Fix8 printer.
Parameters
os stream to print to
Returns
the stream
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
Referenced by encode(), FIX8::Field< UTCTimestamp, field >::print(), FIX8::Field< UTCTimeOnly, field >::print(), FIX8::Field< UTCDateOnly, field >::print(), FIX8::Field< LocalMktDate, field >::print(), FIX8::Field< MonthYear, field >::print(), and FIX8::Session::sequence_check().
virtual size_t FIX8::BaseField::print (char * to) const pure virtual
Print this field to the supplied buffer. Used for encoding.
Parameters
to buffer to print to
Returns
number bytes encoded
Implemented in FIX8::Field< Boolean, field >, FIX8::Field< TZTimestamp, field >, FIX8::Field< TZTimeOnly, field >, FIX8::Field< MonthYear, field >, FIX8::Field< LocalMktDate, field >, FIX8::Field< UTCDateOnly, field >, FIX8::Field< UTCTimeOnly, field >, FIX8::Field< UTCTimestamp, field >, FIX8::Field< char, field >, FIX8::Field< fp_type, field >, FIX8::Field< f8String, field >, FIX8::Field< char *, field >, and FIX8::Field< int, field >.
bool FIX8::BaseField::same_base (const BaseField & that) const inline
BaseField Equivalence test.
Parameters
that field to compare
Returns
true if same
Definition at line 207 of file field.hpp.
References _fnum.
Referenced by FIX8::Field< int, field >::operator<(), FIX8::Field< f8String, field >::operator<(), FIX8::Field< fp_type, field >::operator<(), FIX8::Field< char, field >::operator<(), FIX8::Field< UTCTimestamp, field >::operator<(), FIX8::Field< UTCTimeOnly, field >::operator<(), FIX8::Field< UTCDateOnly, field >::operator<(), FIX8::Field< LocalMktDate, field >::operator<(), FIX8::Field< MonthYear, field >::operator<(), FIX8::Field< TZTimeOnly, field >::operator<(), FIX8::Field< TZTimestamp, field >::operator<(), FIX8::Field< Boolean, field >::operator<(), FIX8::Field< int, field >::operator==(), FIX8::Field< f8String, field >::operator==(), FIX8::Field< fp_type, field >::operator==(), FIX8::Field< char, field >::operator==(), FIX8::Field< UTCTimestamp, field >::operator==(), FIX8::Field< UTCTimeOnly, field >::operator==(), FIX8::Field< UTCDateOnly, field >::operator==(), FIX8::Field< LocalMktDate, field >::operator==(), FIX8::Field< MonthYear, field >::operator==(), FIX8::Field< TZTimeOnly, field >::operator==(), FIX8::Field< TZTimestamp, field >::operator==(), FIX8::Field< Boolean, field >::operator==(), FIX8::Field< int, field >::operator>(), FIX8::Field< f8String, field >::operator>(), FIX8::Field< fp_type, field >::operator>(), FIX8::Field< char, field >::operator>(), FIX8::Field< UTCTimestamp, field >::operator>(), FIX8::Field< UTCTimeOnly, field >::operator>(), FIX8::Field< UTCDateOnly, field >::operator>(), FIX8::Field< LocalMktDate, field >::operator>(), FIX8::Field< MonthYear, field >::operator>(), FIX8::Field< TZTimeOnly, field >::operator>(), FIX8::Field< TZTimestamp, field >::operator>(), and FIX8::Field< Boolean, field >::operator>().
 { return that._fnum == _fnum; }
Friends And Related Function Documentation
friend class MessageBase friend
Definition at line 248 of file field.hpp.
std::ostream& operator<< (std::ostream & os, const BaseField & what) friend
Inserter friend.
Parameters
os stream to send to
what BaseField reference
Returns
stream
Definition at line 247 of file field.hpp.
 { return what.print(os); }
Member Data Documentation
const unsigned short FIX8::BaseField::_fnum private
Definition at line 129 of file field.hpp.
Referenced by FIX8::MessageBase::add_field(), FIX8::MessageBase::check_set_rlm(), encode(), get_tag(), and same_base().
const RealmBase* FIX8::BaseField::_rlm protected
Definition at line 132 of file field.hpp.
Referenced by FIX8::MessageBase::check_set_rlm(), get_realm(), FIX8::Field< int, field >::get_rlm_idx(), FIX8::Field< f8String, field >::get_rlm_idx(), FIX8::Field< fp_type, field >::get_rlm_idx(), FIX8::Field< char, field >::get_rlm_idx(), FIX8::Field< Boolean, field >::get_rlm_idx(), FIX8::Field< int, field >::is_valid(), FIX8::Field< f8String, field >::is_valid(), FIX8::Field< fp_type, field >::is_valid(), and FIX8::Field< char, field >::is_valid().
The documentation for this class was generated from the following file:
field.hpp