fix8: ff::ffa_wrapper Class Reference
ff::ffa_wrapper Class Reference
#include <allocator.hpp>
Public Member Functions
ffa_wrapper (size_t max_size=0, const int delayedReclaim=0)
virtual ~ffa_wrapper ()
void * malloc (size_t size)
int posix_memalign (void **memptr, size_t alignment, size_t size)
void free (void *ptr)
void * realloc (void *ptr, size_t newsize)
void * growsup (void *ptr, size_t newsize)
Public Member Functions inherited from ff::ff_allocator
int getslabs (size_t size)
ff_allocator (size_t max_size=0, const int delayedReclaim=0)
Default Constructor.
virtual ~ff_allocator ()
int init (const int _nslabs[N_SLABBUFFER]=0, bool prealloc=true)
int registerAllocator ()
void deregisterAllocator (bool reclaimMemory=true)
int register4free ()
void * malloc (size_t size)
int posix_memalign (void **memptr, size_t alignment, size_t size)
void free (void *ptr)
void * realloc (void *ptr, size_t newsize)
void * growsup (void *ptr, size_t newsize)
Protected Member Functions
virtual bool free (Buf_ctl *buf)
Protected Member Functions inherited from ff::ff_allocator
size_t allocatedsize ()
Private Member Functions
void nomoremalloc ()
Private Attributes
atomic_long_t nomorealloc
Friends
void FFAkeyDestructorHandler (void *kv)
Additional Inherited Members
Public Attributes inherited from ff::ff_allocator
ALLSTATS(void printstats(std::ostream
&out){all_stats::instance() ->
print(out);}) private
SegmentAllocator * alloc
const size_t max_size
const int delayedReclaim
Detailed Description
Definition at line 1339 of file allocator.hpp.
Constructor & Destructor Documentation
ff::ffa_wrapper::ffa_wrapper (size_t max_size = 0, const int delayedReclaim = 0) inline
Constructor
TODO
Definition at line 1368 of file allocator.hpp.
virtual ff::ffa_wrapper::~ffa_wrapper () inline virtual
Destructor
Definition at line 1376 of file allocator.hpp.
Referenced by ff::FFAllocator::deleteAllocator().
Member Function Documentation
virtual bool ff::ffa_wrapper::free (Buf_ctl * buf) inline protected virtual
TODO
buf TODO
Returns
TODO
Reimplemented from ff::ff_allocator.
Definition at line 1348 of file allocator.hpp.
References ff::SlabCache::allocatedsize(), ff::ff_allocator::free(), and ff::killMyself().
void ff::ffa_wrapper::free (void * ptr) inline
It is used to be safe.... - better not to call this one.
Definition at line 1401 of file allocator.hpp.
void* ff::ffa_wrapper::growsup (void * ptr, size_t newsize) inline
It is like realloc but it doesn't copy data
Definition at line 1415 of file allocator.hpp.
References ff::ff_allocator::growsup().
Referenced by ff::FFAllocator::growsup().
void* ff::ffa_wrapper::malloc (size_t size) inline
Malloc
Returns
TODO
Definition at line 1383 of file allocator.hpp.
References ff::ff_allocator::malloc().
Referenced by ff::FFAllocator::malloc().
void ff::ffa_wrapper::nomoremalloc () inline private
TODO
Definition at line 1422 of file allocator.hpp.
Referenced by ff::FFAkeyDestructorHandler().
int ff::ffa_wrapper::posix_memalign (void ** memptr, size_t alignment, size_t size) inline
posix_memalign
memptr TODO
Returns
TODO
Definition at line 1394 of file allocator.hpp.
References ff::ff_allocator::posix_memalign().
Referenced by ff::FFAllocator::posix_memalign().
void* ff::ffa_wrapper::realloc (void * ptr, size_t newsize) inline
realloc
Returns
TODO
Definition at line 1408 of file allocator.hpp.
References ff::ff_allocator::realloc().
Referenced by ff::FFAllocator::realloc().
Friends And Related Function Documentation
void FFAkeyDestructorHandler (void * kv) friend
Member Data Documentation
atomic_long_t ff::ffa_wrapper::nomorealloc private
Definition at line 1427 of file allocator.hpp.
The documentation for this class was generated from the following file:
allocator.hpp