fix8: FIX8::FileLogger Class Reference
FIX8::FileLogger Class Reference
A file logger.
#include <logger.hpp>
Public Member Functions
F8API FileLogger (const std::string &pathname, const LogFlags flags, const Levels levels, const std::string delim=" ", const LogPositions positions=LogPositions(), const unsigned rotnum=rotation_default)
virtual ~FileLogger ()
Dtor.
virtual F8API bool rotate (bool force=false)
Public Member Functions inherited from FIX8::Logger
Logger (const LogFlags flags, const Levels levels=Levels(All), const std::string delim=" ", const LogPositions positions=LogPositions())
virtual ~Logger ()
Dtor.
bool is_loggable (Level level) const
void set_levels (Levels levels)
void set_flags (LogFlags flags)
void set_delimiter (const std::string &delim)
void set_positions (const std::vector< int > &positions)
virtual std::ostream & get_stream () const
bool enqueue (const std::string &what, Level lev=Logger::Info, const char *fl=nullptr, const unsigned val=0)
bool send (const std::string &what, Level lev=Logger::Info, const char *fl=nullptr, const unsigned val=0)
void stop ()
Stop the logging thread.
F8API int operator() ()
virtual F8API void process_logline (LogElement *le)
bool has_flag (const Flags flg) const
F8API char get_thread_code (thread_id_t tid)
F8API void purge_thread_codes ()
Remove dead threads from the thread code cache.
virtual F8API void flush ()
Flush the buffer.
f8_thread_cancellation_token & cancellation_token ()
Protected Attributes
std::string _pathname
unsigned _rotnum
Protected Attributes inherited from FIX8::Logger
f8_mutex _mutex
f8_spin_lock _log_spl
LogFlags _flags
Levels _levels
std::string _delim
std::ostream * _ofs = nullptr
size_t _lines = 0
f8_thread_cancellation_token _stopping
f8_concurrent_queue< LogElement > _msg_queue
unsigned _sequence = 0
unsigned _osequence = 0
ThreadCodes _thread_codes
RevThreadCodes _rev_thread_codes
LogPositions _positions
Additional Inherited Members
Public Types inherited from FIX8::Logger
enum Level {
Debug, Info, Warn, Error,
Fatal
}
enum Flags {
mstart, sstart, sequence, thread,
timestamp, minitimestamp, direction, level,
location, start_controls, append =start_controls, buffer,
compress, pipe, broadcast, nolf,
inbound, outbound, xml, num_flags
}
using LogFlags = ebitset< Flags >
using Levels = ebitset< Level >
using LogPositions = std::vector< int >
Static Public Member Functions inherited from FIX8::Logger
static const Tickval & get_time_started ()
Static Public Attributes inherited from FIX8::Logger
static const int Errors = bitsum(Warn,Error,Fatal)
static const int All = bitsum(Debug,Info,Warn,Error,Fatal)
static const int None = 0
static const int StdFlags = bitsum(sequence,thread,timestamp,level)
static const int rotation_default = 5
static const int max_rotation = 1024
static const std::vector< std::string > _bit_names
string representation of logflags
static const std::vector< std::string > _level_names { "Debug", "Info ", "Warn ", "Error", "Fatal" }
string representation of levels
Protected Types inherited from FIX8::Logger
using ThreadCodes = std::map< thread_id_t, char >
using RevThreadCodes = std::map< char, thread_id_t >
Static Protected Attributes inherited from FIX8::Logger
static const Tickval _started { true }
The time the entire logging system was start.
Detailed Description
A file logger.
Definition at line 357 of file logger.hpp.
Constructor & Destructor Documentation
FileLogger::FileLogger (const std::string & pathname, const LogFlags flags, const Levels levels, const std::string delim = " ", const LogPositions positions = LogPositions(), const unsigned rotnum = rotation_default)
Ctor.
Parameters
pathname pathname to log to
flags ebitset flags
levels ebitset levels
delim field delimiter
positions field positions
rotnum number of logfile rotations to retain (default=5)
Definition at line 255 of file logger.cpp.
References _pathname, and rotate().
    : Logger(flags, levels, delim, positions), _rotnum(rotnum)
 {
    if (!fname.empty())
    {
       _pathname = fname;
       rotate();
    }
 }
virtual FIX8::FileLogger::~FileLogger () inline virtual
Dtor.
Definition at line 375 of file logger.hpp.
 {}
Member Function Documentation
bool FileLogger::rotate (bool force = false) virtual
Perform logfile rotation
Parameters
force force the rotation (even if the file is set ti append)
Returns
true on success
Reimplemented from FIX8::Logger.
Definition at line 267 of file logger.cpp.
References FIX8::Logger::_flags, FIX8::Logger::_mutex, FIX8::Logger::_ofs, _pathname, _rotnum, FIX8::Logger::append, FIX8::Logger::compress, FIX8::create_path(), FIX8::exist(), filepart(), FIX8::ebitset< T, B >::has(), FIX8::Logger::max_rotation, and FIX8::split_path().
Referenced by FileLogger().
 {
    f8_scoped_lock guard(_mutex);
    delete _ofs;
    string thislFile(_pathname), filepart, dirpart;
    split_path(thislFile, filepart, dirpart);
    if (!dirpart.empty() && !exist(dirpart))
       create_path(dirpart);
 #ifdef HAVE_COMPRESSION
    if (_flags & compress)
       thislFile += ".gz";
 #endif
    if (_rotnum > 0 && (!_flags.has(append) || force))
    {
       vector<string> rlst;
       rlst.push_back(thislFile);
       for (unsigned ii(0); ii < _rotnum && ii < max_rotation; ++ii)
       {
          ostringstream ostr;
          ostr << _pathname << '.' << (ii + 1);
          if (_flags & compress)
             ostr << ".gz";
          rlst.push_back(ostr.str());
       }
       for (unsigned ii(_rotnum); ii; --ii)
          rename (rlst[ii - 1].c_str(), rlst[ii].c_str());
    }
    const ios_base::openmode mode (_flags & append ? ios_base::out | ios_base::app : ios_base::out);
 #ifdef HAVE_COMPRESSION
    if (_flags & compress)
       _ofs = new ogzstream(thislFile.c_str(), mode);
    else
 #endif
       _ofs = new ofstream(thislFile.c_str(), mode);
    if (!_ofs || !*_ofs)
       throw LogfileException(thislFile);
    return true;
 }
Member Data Documentation
std::string FIX8::FileLogger::_pathname protected
Definition at line 360 of file logger.hpp.
Referenced by FileLogger(), and rotate().
unsigned FIX8::FileLogger::_rotnum protected
Definition at line 361 of file logger.hpp.
Referenced by rotate().
The documentation for this class was generated from the following files:
logger.hpp
logger.cpp