fix8: FIX8::ConsoleMenu Class Reference
FIX8::ConsoleMenu Class Reference
Console test harness menu.
#include <consolemenu.hpp>
Public Member Functions
ConsoleMenu (const F8MetaCntx &ctx, std::istream &is=std::cin, std::ostream &os=std::cout, int lpp=20)
virtual ~ConsoleMenu ()
Dtor.
virtual F8API const BaseMsgEntry * SelectMsg () const
virtual F8API const
FieldTable::Pair * SelectField (const Message *msg, int groupid=0) const
virtual F8API int SelectRealm (const unsigned short fnum, const RealmBase *rb) const
F8API Message * SelectFromMsg (MsgList &lst) const
virtual F8API int CreateMsgs (tty_save_state &tty, MsgList &lst) const
F8API void EditMsg (tty_save_state &tty, const FieldTable::Pair *fld, Message *msg) const
virtual F8API int EditMsgs (tty_save_state &tty, MsgList &lst) const
virtual F8API int DeleteMsgs (tty_save_state &tty, MsgList &lst) const
int get_lpp () const
void set_lpp (int lpp)
bool get_yn (const f8String &prompt, bool echo=false) const
char get_key (const f8String &prompt=std::string(), bool echo=false) const
F8API f8String & GetString (tty_save_state &tty, f8String &to) const
Private Attributes
const F8MetaCntx & _ctx
std::istream & _is
std::ostream & _os
int _lpp
Static Private Attributes
static const f8String _opt_keys
static const f8String _fld_prompt
Detailed Description
Console test harness menu.
Definition at line 48 of file consolemenu.hpp.
Constructor & Destructor Documentation
FIX8::ConsoleMenu::ConsoleMenu (const F8MetaCntx & ctx, std::istream & is = std::cin, std::ostream & os = std::cout, int lpp = 20) inline
Ctor
Parameters
ctx - reference to generated metadata
is - reference to input stream
os - reference to output stream
lpp - lines to print per page
Definition at line 62 of file consolemenu.hpp.
virtual FIX8::ConsoleMenu::~ConsoleMenu () inline virtual
Dtor.
Definition at line 66 of file consolemenu.hpp.
Member Function Documentation
int ConsoleMenu::CreateMsgs (tty_save_state & tty, MsgList & lst) const virtual
Definition at line 269 of file consolemenu.cpp.
References FIX8::BaseMsgEntry::_create, and FIX8::Minst::_do.
int ConsoleMenu::DeleteMsgs (tty_save_state & tty, MsgList & lst) const virtual
Definition at line 351 of file consolemenu.cpp.
void ConsoleMenu::EditMsg (tty_save_state & tty, const FieldTable::Pair * fld, Message * msg) const
Definition at line 299 of file consolemenu.cpp.
References FIX8::_pair< Key, Val >::_key, FIX8::_pair< Key, Val >::_value, FIX8::MessageBase::add_field(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::MessageBase::find_group(), FIX8::MessageBase::get_fp(), FIX8::FieldTraits::get_presence(), FIX8::BaseField::get_tag(), and FIX8::FieldTraits::is_group().
int ConsoleMenu::EditMsgs (tty_save_state & tty, MsgList & lst) const virtual
Definition at line 334 of file consolemenu.cpp.
char FIX8::ConsoleMenu::get_key (const f8String & prompt = std::string(), bool echo = false) const inline
Definition at line 81 of file consolemenu.hpp.
References _is, and _os.
Referenced by get_yn().
int FIX8::ConsoleMenu::get_lpp () const inline
Definition at line 77 of file consolemenu.hpp.
References _lpp.
bool FIX8::ConsoleMenu::get_yn (const f8String & prompt, bool echo = false) const inline
Definition at line 80 of file consolemenu.hpp.
References get_key().
f8String & ConsoleMenu::GetString (tty_save_state & tty, f8String & to) const
Definition at line 289 of file consolemenu.cpp.
References FIX8::tty_save_state::set_raw_mode(), and FIX8::tty_save_state::unset_raw_mode().
const FieldTable::Pair * ConsoleMenu::SelectField (const Message * msg, int groupid = 0) const virtual
Definition at line 101 of file consolemenu.cpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::at(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::MessageBase::get_fp(), FIX8::MessageBase::get_msgtype(), FIX8::FieldTraits::get_presence(), FIX8::MessageBase::have(), FIX8::FieldTraits::is_mandatory(), FIX8::MessageBase::print_field(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::size().
Message * ConsoleMenu::SelectFromMsg (MsgList & lst) const
Definition at line 218 of file consolemenu.cpp.
References FIX8::_pair< Key, Val >::_key, and FIX8::_pair< Key, Val >::_value.
const BaseMsgEntry * ConsoleMenu::SelectMsg () const virtual
Definition at line 50 of file consolemenu.cpp.
References FIX8::_pair< Key, Val >::_value.
int ConsoleMenu::SelectRealm (const unsigned short fnum, const RealmBase * rb) const virtual
Definition at line 166 of file consolemenu.cpp.
References FIX8::RealmBase::_descriptions, FIX8::RealmBase::_sz, and FIX8::RealmBase::print().
void FIX8::ConsoleMenu::set_lpp (int lpp) inline
Definition at line 78 of file consolemenu.hpp.
References _lpp.
Member Data Documentation
const F8MetaCntx& FIX8::ConsoleMenu::_ctx private
Definition at line 50 of file consolemenu.hpp.
const f8String ConsoleMenu::_fld_prompt static private
Definition at line 54 of file consolemenu.hpp.
std::istream& FIX8::ConsoleMenu::_is private
Definition at line 51 of file consolemenu.hpp.
Referenced by get_key().
int FIX8::ConsoleMenu::_lpp private
Definition at line 53 of file consolemenu.hpp.
Referenced by get_lpp(), and set_lpp().
const f8String ConsoleMenu::_opt_keys static private
Definition at line 54 of file consolemenu.hpp.
std::ostream& FIX8::ConsoleMenu::_os private
Definition at line 52 of file consolemenu.hpp.
Referenced by get_key().
The documentation for this class was generated from the following files:
consolemenu.hpp
consolemenu.cpp