fix8: FIX8::Field< UTCTimestamp, field > Class Template Reference
FIX8::Field< UTCTimestamp, field > Class Template Reference
Partial specialisation for UTCTimestamp field type.
#include <field.hpp>
Public Member Functions
Field ()
Ctor.
Field (const Field &from)
Field (const Tickval &val, const RealmBase *rlm=0)
Field (const f8String &from, const RealmBase *rlm=0)
Field (const char *from, const RealmBase *rlm=0)
Field (const tm &from, const RealmBase *rlm=0)
Field & operator= (const Field &that)
Assignment operator.
~Field ()
Dtor.
const Tickval & get () const
const Tickval & operator() () const
void set (const Tickval &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (const unsigned short fnum, const RealmBase *rlm=0)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
virtual int get_rlm_idx () const
template<typename T >
T & from ()
size_t encode (std::ostream &os) const
size_t encode (char *to) const
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
The FIX fieldID (tag number).
Private Attributes
Tickval _value
Additional Inherited Members
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<const unsigned short field>
class FIX8::Field< UTCTimestamp, field >
Partial specialisation for UTCTimestamp field type.
Template Parameters
field field number (fix tag)
Definition at line 851 of file field.hpp.
Constructor & Destructor Documentation
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field () inline
Ctor.
Definition at line 860 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field (const Field< UTCTimestamp, field > & from) inline
Copy Ctor.
Parameters
from field to copy
Definition at line 864 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field (const Tickval & val, const RealmBase * rlm = 0) inline
Value ctor.
Parameters
val value to set
rlm pointer to the realmbase for this field (if available)
Definition at line 869 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field (const f8String & from, const RealmBase * rlm = 0) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 874 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field (const char * from, const RealmBase * rlm = 0) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 879 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::Field (const tm & from, const RealmBase * rlm = 0) inline
Construct from tm struct
Parameters
from string to construct field from
rlm tm struct with broken out values
Definition at line 884 of file field.hpp.
template<const unsigned short field> FIX8::Field< UTCTimestamp, field >::~Field () inline
Dtor.
Definition at line 899 of file field.hpp.
Member Function Documentation
template<const unsigned short field> Field* FIX8::Field< UTCTimestamp, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 915 of file field.hpp.
template<const unsigned short field> const Tickval& FIX8::Field< UTCTimestamp, field >::get () const inline
Get field value.
Returns
value Tickval&
Definition at line 903 of file field.hpp.
template<const unsigned short field> static unsigned short FIX8::Field< UTCTimestamp, field >::get_field_id () inline static
The FIX fieldID (tag number).
Definition at line 857 of file field.hpp.
template<const unsigned short field> const Tickval& FIX8::Field< UTCTimestamp, field >::operator() () const inline
Get field value.
Returns
value Tickval&
Definition at line 907 of file field.hpp.
template<const unsigned short field> Field& FIX8::Field< UTCTimestamp, field >::operator= (const Field< UTCTimestamp, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 889 of file field.hpp.
template<const unsigned short field> std::ostream& FIX8::Field< UTCTimestamp, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 920 of file field.hpp.
References FIX8::MAX_MSGTYPE_FIELD_LEN(), and FIX8::BaseField::print().
template<const unsigned short field> size_t FIX8::Field< UTCTimestamp, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 930 of file field.hpp.
References FIX8::_with_ms, and FIX8::date_time_format().
template<const unsigned short field> void FIX8::Field< UTCTimestamp, field >::set (const Tickval & from) inline
Set field to the supplied value.
Parameters
from value to set
Definition at line 911 of file field.hpp.
References FIX8::BaseField::from().
Member Data Documentation
template<const unsigned short field> Tickval FIX8::Field< UTCTimestamp, field >::_value private
Definition at line 853 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp