fix8: ff_queue Class Reference
ff_queue Class Reference
#include <ff_queue.hpp>
Classes
struct bucket_t
Public Member Functions
ff_queue (size_t bucket_size, size_t max_bucket_count)
~ff_queue ()
char * enqueue_prepare (size_t sz)
void enqueue_commit ()
char * dequeue_prepare ()
void dequeue_commit ()
Private Member Functions
bucket_t * alloc_bucket (size_t sz)
NOINLINE char * enqueue_prepare_slow (size_t sz)
ff_queue (ff_queue const &)
void operator= (ff_queue const &)
Private Attributes
char *volatile head_pos_
char pad_ [CACHE_LINE_SIZE]
char * tail_pos_
char * tail_end_
char * tail_next_
bucket_t * tail_bucket_
bucket_t * last_bucket_
size_t const bucket_size_
size_t const max_bucket_count_
size_t bucket_count_
Detailed Description
TODO
This class is defined in ff_queue.hpp
Definition at line 106 of file ff_queue.hpp.
Constructor & Destructor Documentation
ff_queue::ff_queue (size_t bucket_size, size_t max_bucket_count) inline
Constructor
Definition at line 112 of file ff_queue.hpp.
References alloc_bucket(), bucket_count_, bucket_size_, ff_queue::bucket_t::data, head_pos_, last_bucket_, pad_, tail_bucket_, tail_end_, tail_next_, and tail_pos_.
ff_queue::~ff_queue () inline
Destructor
Definition at line 131 of file ff_queue.hpp.
References aligned_free(), last_bucket_, and ff_queue::bucket_t::next.
ff_queue::ff_queue (ff_queue const &) private
Member Function Documentation
bucket_t* ff_queue::alloc_bucket (size_t sz) inline private
TODO
Definition at line 234 of file ff_queue.hpp.
References aligned_malloc(), bucket_count_, ff_queue::bucket_t::next, and ff_queue::bucket_t::size.
Referenced by enqueue_prepare_slow(), and ff_queue().
void ff_queue::dequeue_commit () inline
TODO
Definition at line 203 of file ff_queue.hpp.
References atomic_addr_store_release(), head_pos_, and next.
char* ff_queue::dequeue_prepare () inline
TODO
Returns
TODO
Definition at line 179 of file ff_queue.hpp.
References atomic_addr_load_acquire(), atomic_addr_store_release(), head_pos_, and next.
void ff_queue::enqueue_commit () inline
TODO
Definition at line 167 of file ff_queue.hpp.
References atomic_addr_store_release(), tail_next_, and tail_pos_.
char* ff_queue::enqueue_prepare (size_t sz) inline
TODO
Returns
TODO
Definition at line 147 of file ff_queue.hpp.
References enqueue_prepare_slow(), tail_end_, tail_next_, and tail_pos_.
Referenced by enqueue_prepare_slow().
NOINLINE char* ff_queue::enqueue_prepare_slow (size_t sz) inline private
TODO
Definition at line 250 of file ff_queue.hpp.
References aligned_free(), alloc_bucket(), atomic_addr_load_acquire(), atomic_addr_store_release(), bucket_count_, bucket_size_, ff_queue::bucket_t::data, data, enqueue_prepare(), head_pos_, last_bucket_, max_bucket_count_, ff_queue::bucket_t::next, ff_queue::bucket_t::size, tail_bucket_, tail_end_, and tail_pos_.
Referenced by enqueue_prepare().
void ff_queue::operator= (ff_queue const &) private
Member Data Documentation
size_t ff_queue::bucket_count_ private
Definition at line 229 of file ff_queue.hpp.
Referenced by alloc_bucket(), enqueue_prepare_slow(), and ff_queue().
size_t const ff_queue::bucket_size_ private
Definition at line 227 of file ff_queue.hpp.
Referenced by enqueue_prepare_slow(), and ff_queue().
char* volatile ff_queue::head_pos_ private
Definition at line 218 of file ff_queue.hpp.
Referenced by dequeue_commit(), dequeue_prepare(), enqueue_prepare_slow(), and ff_queue().
bucket_t* ff_queue::last_bucket_ private
Definition at line 226 of file ff_queue.hpp.
Referenced by enqueue_prepare_slow(), ff_queue(), and ~ff_queue().
size_t const ff_queue::max_bucket_count_ private
Definition at line 228 of file ff_queue.hpp.
Referenced by enqueue_prepare_slow().
char ff_queue::pad_[CACHE_LINE_SIZE] private
Definition at line 220 of file ff_queue.hpp.
Referenced by ff_queue().
bucket_t* ff_queue::tail_bucket_ private
Definition at line 225 of file ff_queue.hpp.
Referenced by enqueue_prepare_slow(), and ff_queue().
char* ff_queue::tail_end_ private
Definition at line 223 of file ff_queue.hpp.
Referenced by enqueue_prepare(), enqueue_prepare_slow(), and ff_queue().
char* ff_queue::tail_next_ private
Definition at line 224 of file ff_queue.hpp.
Referenced by enqueue_commit(), enqueue_prepare(), and ff_queue().
char* ff_queue::tail_pos_ private
Definition at line 222 of file ff_queue.hpp.
Referenced by enqueue_commit(), enqueue_prepare(), enqueue_prepare_slow(), and ff_queue().
The documentation for this class was generated from the following file:
ff_queue.hpp