fix8: FIX8::Field< char, field > Class Template Reference
FIX8::Field< char, field > Class Template Reference
Partial specialisation for unsigned short field type.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Field (const char &val, const RealmBase *rlm=nullptr)
Field (const f8String &from, const RealmBase *rlm=nullptr)
Field (const char *from, const RealmBase *rlm=nullptr)
~Field ()
Dtor.
Field & operator= (const Field &that)
Assignment operator.
bool operator== (const BaseField &that) const
Equivalence operator.
bool operator< (const BaseField &that) const
Less than operator.
bool operator> (const BaseField &that) const
Greater than operator.
bool is_valid () const
int get_rlm_idx () const
const char & get () const
const char & operator() () const
const char & set (const char &from)
const char & set_from_raw (const f8String &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Private Attributes
char _value
Static Private Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_char
Additional Inherited Members
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Detailed Description
template<unsigned short field>
class FIX8::Field< char, field >
Partial specialisation for unsigned short field type.
Template Parameters
field field number (fix tag)
Definition at line 718 of file field.hpp.
Constructor & Destructor Documentation
template<unsigned short field> FIX8::Field< char, field >::Field () inline
Ctor.
Definition at line 731 of file field.hpp.
 : BaseField(field), _value() {}
template<unsigned short field> FIX8::Field< char, field >::Field (const Field< char, field > & from) inline
Copy Ctor.
Parameters
from field to copy
Definition at line 735 of file field.hpp.
 : BaseField(field, from._rlm), _value(from._value) {}
template<unsigned short field> FIX8::Field< char, field >::Field (const char & val, const RealmBase * rlm = nullptr) inline
Value ctor.
Parameters
val value to set
rlm pointer to the realmbase for this field (if available)
Definition at line 740 of file field.hpp.
 : BaseField(field, rlm), _value(val) {}
template<unsigned short field> FIX8::Field< char, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 745 of file field.hpp.
 : BaseField(field, rlm), _value(from[0]) {}
template<unsigned short field> FIX8::Field< char, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 750 of file field.hpp.
 : BaseField(field, rlm), _value(*from) {}
template<unsigned short field> FIX8::Field< char, field >::~Field () inline
Dtor.
Definition at line 753 of file field.hpp.
 {}
Member Function Documentation
template<unsigned short field> Field* FIX8::Field< char, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 811 of file field.hpp.
References FIX8::Field< T, field >::Field().
 { return new Field(*this); }
template<unsigned short field> const char& FIX8::Field< char, field >::get () const inline
Get field value.
Returns
value (char)
Definition at line 793 of file field.hpp.
 { return _value; }
template<unsigned short field> static unsigned short FIX8::Field< char, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 725 of file field.hpp.
 { return field; }
template<unsigned short field> int FIX8::Field< char, field >::get_rlm_idx () const inline virtual
Get the realm index of this value in the domain set.
Returns
the index in the domain set of this value
Reimplemented from FIX8::BaseField.
Definition at line 789 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::get_rlm_idx().
 { return _rlm ? _rlm->get_rlm_idx(_value) : -1; }
template<unsigned short field> FieldTrait::FieldType FIX8::Field< char, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 728 of file field.hpp.
 { return _ftype; }
template<unsigned short field> bool FIX8::Field< char, field >::is_valid () const inline
Check if this value is a member/in range of the domain set.
Returns
true if in the set or no domain available
Definition at line 785 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::is_valid().
 { return _rlm ? _rlm->is_valid(_value) : true; }
template<unsigned short field> const char& FIX8::Field< char, field >::operator() () const inline
Get field value.
Returns
value (char)
Definition at line 797 of file field.hpp.
 { return _value; }
template<unsigned short field> bool FIX8::Field< char, field >::operator< (const BaseField< char, field > & that) const inline virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implements FIX8::BaseField.
Definition at line 774 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value < static_cast<const Field<char, field>&>(that)._value; }
template<unsigned short field> Field& FIX8::Field< char, field >::operator= (const Field< char, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 758 of file field.hpp.
    {
       if (this != &that)
          _value = that._value;
       return *this;
    }
template<unsigned short field> bool FIX8::Field< char, field >::operator== (const BaseField< char, field > & that) const inline virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implements FIX8::BaseField.
Definition at line 768 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && static_cast<const Field<char, field>&>(that)._value == _value; }
template<unsigned short field> bool FIX8::Field< char, field >::operator> (const BaseField< char, field > & that) const inline virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implements FIX8::BaseField.
Definition at line 780 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value > static_cast<const Field<char, field>&>(that)._value; }
template<unsigned short field> std::ostream& FIX8::Field< char, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 816 of file field.hpp.
 { return os << _value; }
template<unsigned short field> size_t FIX8::Field< char, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 821 of file field.hpp.
 { *to = _value; return 1; }
template<unsigned short field> const char& FIX8::Field< char, field >::set (const char & from) inline
Get field value.
Parameters
from value to set
Returns
original value (int)
Definition at line 802 of file field.hpp.
References FIX8::BaseField::from().
 { return _value = from; }
template<unsigned short field> const char& FIX8::Field< char, field >::set_from_raw (const f8String & from) inline
Set the value from a string.
Parameters
from value to set
Returns
original value (char`)
Definition at line 807 of file field.hpp.
 { return _value = from[0]; }
Member Data Documentation
template<unsigned short field> const FieldTrait::FieldType FIX8::Field< char, field >::_ftype = FieldTrait::ft_char static private
Definition at line 721 of file field.hpp.
template<unsigned short field> char FIX8::Field< char, field >::_value private
Definition at line 720 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp