fix8: ff::Barrier Class Reference
ff::Barrier Class Reference
Models a classical mutex.
#include <node.hpp>
Public Member Functions
Barrier ()
Constructor.
void barrierSetup (int init)
Setup barrier.
void doBarrier (int)
Performs barrier operation.
unsigned getCounter () const
Get the thread counter.
void incCounter ()
Increments the counter.
void decCounter ()
Decrements the counter.
Static Public Member Functions
static Barrier * instance ()
Creates instance of barrier.
Private Attributes
int _barrier
unsigned threadCounter
pthread_mutex_t bLock
pthread_cond_t bCond
Detailed Description
Models a classical mutex.
This class models a classical Mutex. This class provides the methods necessary to implement a low-level pthread mutex.
This class is defined in node.hpp
Definition at line 65 of file node.hpp.
Constructor & Destructor Documentation
ff::Barrier::Barrier () inline
Constructor.
It checks whether the mutex variable(s) and the conditional variable(s) can be properly initialised. In case initialization fails, the program is aborted.
Definition at line 87 of file node.hpp.
References bCond, bLock, ff::error(), pthread_cond_init(), and pthread_mutex_init().
Member Function Documentation
void ff::Barrier::barrierSetup (int init) inline
Setup barrier.
It initialize barrier.
init determine the barrier
Definition at line 106 of file node.hpp.
References _barrier.
void ff::Barrier::decCounter () inline
Decrements the counter.
It decremetns the counter of the pthread.
Definition at line 148 of file node.hpp.
References threadCounter.
void ff::Barrier::doBarrier (int) inline
Performs barrier operation.
It performs the barrier operation and waits on the condition variable.
Definition at line 117 of file node.hpp.
References _barrier, bCond, bLock, pthread_cond_broadcast(), pthread_cond_wait(), pthread_mutex_lock(), and pthread_mutex_unlock().
unsigned ff::Barrier::getCounter () const inline
Get the thread counter.
It gets the counter of the pthread.
Returns
An integet value, showing the counter of the pthread.
Definition at line 134 of file node.hpp.
References threadCounter.
void ff::Barrier::incCounter () inline
Increments the counter.
It increaments the counter of the pthread.
Definition at line 141 of file node.hpp.
References threadCounter.
static Barrier* ff::Barrier::instance () inline static
Creates instance of barrier.
It creates an instance of barrier.
Returns
A pointer to the barrier.
Definition at line 74 of file node.hpp.
Member Data Documentation
int ff::Barrier::_barrier private
Definition at line 151 of file node.hpp.
Referenced by barrierSetup(), and doBarrier().
pthread_cond_t ff::Barrier::bCond private
Definition at line 156 of file node.hpp.
Referenced by Barrier(), and doBarrier().
pthread_mutex_t ff::Barrier::bLock private
Definition at line 155 of file node.hpp.
Referenced by Barrier(), and doBarrier().
unsigned ff::Barrier::threadCounter private
Definition at line 154 of file node.hpp.
Referenced by decCounter(), getCounter(), and incCounter().
The documentation for this class was generated from the following file:
node.hpp