fix8: FIX8::Field< fp_type, field > Class Template Reference
FIX8::Field< fp_type, field > Class Template Reference
Partial specialisation for fp_type field type. fp_type is singe or double.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const fp_type &val, const RealmBase *rlm=nullptr)
Field (const fp_type &val, const int prec, const RealmBase *rlm=nullptr)
Field (const f8String &from, const RealmBase *rlm=nullptr)
Field (const char *from, const RealmBase *rlm=nullptr)
virtual ~Field ()
Dtor.
Field & operator= (const Field &that)
Assignment operator.
bool operator== (const BaseField &that) const
Equivalence operator.
bool operator< (const BaseField &that) const
Less than operator.
bool operator> (const BaseField &that) const
Greater than operator.
void set_precision (const int prec)
bool is_valid () const
int get_rlm_idx () const
const fp_type & get () const
const fp_type & operator() () const
const fp_type & set (const fp_type &from)
const fp_type & set_from_raw (const f8String &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
template<typename T >
T & from ()
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Protected Attributes
fp_type _value
int _precision
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Static Protected Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_float
Detailed Description
template<unsigned short field>
class FIX8::Field< fp_type, field >
Partial specialisation for fp_type field type. fp_type is singe or double.
Template Parameters
field field number (fix tag)
Definition at line 590 of file field.hpp.
Constructor & Destructor Documentation
template<unsigned short field> FIX8::Field< fp_type, field >::Field () inline
Ctor.
Definition at line 605 of file field.hpp.
template<unsigned short field> FIX8::Field< fp_type, field >::Field (const Field< fp_type, field > & from) inline
Copy Ctor.
Definition at line 609 of file field.hpp.
template<unsigned short field> FIX8::Field< fp_type, field >::Field (const fp_type & val, const RealmBase * rlm = nullptr) inline
Value ctor.
Parameters
val value to set
rlm pointer to the realmbase for this field (if available)
Definition at line 614 of file field.hpp.
template<unsigned short field> FIX8::Field< fp_type, field >::Field (const fp_type & val, const int prec, const RealmBase * rlm = nullptr) inline
Value ctor.
Parameters
val value to set
prec precision digits
rlm pointer to the realmbase for this field (if available)
Definition at line 620 of file field.hpp.
template<unsigned short field> FIX8::Field< fp_type, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 625 of file field.hpp.
template<unsigned short field> FIX8::Field< fp_type, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 630 of file field.hpp.
template<unsigned short field> virtual FIX8::Field< fp_type, field >::~Field () inline virtual
Dtor.
Definition at line 633 of file field.hpp.
Member Function Documentation
template<unsigned short field> Field* FIX8::Field< fp_type, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 695 of file field.hpp.
References FIX8::Field< T, field >::Field().
template<unsigned short field> const fp_type& FIX8::Field< fp_type, field >::get () const inline
Get field value.
Returns
value (fp_type)
Definition at line 677 of file field.hpp.
template<unsigned short field> static unsigned short FIX8::Field< fp_type, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 599 of file field.hpp.
template<unsigned short field> int FIX8::Field< fp_type, field >::get_rlm_idx () const inline virtual
Get the realm index of this value in the domain set.
Returns
the index in the domain set of this value
Reimplemented from FIX8::BaseField.
Definition at line 673 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::get_rlm_idx().
template<unsigned short field> FieldTrait::FieldType FIX8::Field< fp_type, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 602 of file field.hpp.
template<unsigned short field> bool FIX8::Field< fp_type, field >::is_valid () const inline
Check if this value is a member/in range of the domain set.
Returns
true if in the set or no domain available
Definition at line 669 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::is_valid().
template<unsigned short field> const fp_type& FIX8::Field< fp_type, field >::operator() () const inline
Get field value.
Returns
value (fp_type)
Definition at line 681 of file field.hpp.
template<unsigned short field> bool FIX8::Field< fp_type, field >::operator< (const BaseField< fp_type, field > & that) const inline virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implements FIX8::BaseField.
Definition at line 654 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> Field& FIX8::Field< fp_type, field >::operator= (const Field< fp_type, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 638 of file field.hpp.
template<unsigned short field> bool FIX8::Field< fp_type, field >::operator== (const BaseField< fp_type, field > & that) const inline virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implements FIX8::BaseField.
Definition at line 648 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> bool FIX8::Field< fp_type, field >::operator> (const BaseField< fp_type, field > & that) const inline virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implements FIX8::BaseField.
Definition at line 660 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> std::ostream& FIX8::Field< fp_type, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 700 of file field.hpp.
template<unsigned short field> size_t FIX8::Field< fp_type, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 705 of file field.hpp.
References FIX8::modp_dtoa().
template<unsigned short field> const fp_type& FIX8::Field< fp_type, field >::set (const fp_type & from) inline
Get field value.
Parameters
from value to set
Returns
original value (int)
Definition at line 686 of file field.hpp.
References FIX8::BaseField::from().
template<unsigned short field> const fp_type& FIX8::Field< fp_type, field >::set_from_raw (const f8String & from) inline
Set the value from a string.
Parameters
from value to set
Returns
original value (fp_type)
Definition at line 691 of file field.hpp.
References FIX8::fast_atof().
template<unsigned short field> void FIX8::Field< fp_type, field >::set_precision (const int prec) inline
Set the output precision
Parameters
prec precision digits
Definition at line 665 of file field.hpp.
Member Data Documentation
template<unsigned short field> const FieldTrait::FieldType FIX8::Field< fp_type, field >::_ftype = FieldTrait::ft_float static protected
Definition at line 595 of file field.hpp.
template<unsigned short field> int FIX8::Field< fp_type, field >::_precision protected
Definition at line 594 of file field.hpp.
template<unsigned short field> fp_type FIX8::Field< fp_type, field >::_value protected
Definition at line 593 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp