fix8: FIX8::IntervalTimer Class Reference
FIX8::IntervalTimer Class Reference
High resolution interval timer.
#include <timer.hpp>
Public Member Functions
IntervalTimer ()
Ctor. RAII.
virtual ~IntervalTimer ()
Dtor.
const IntervalTimer & Calculate ()
double AsDouble () const
double Reset ()
Private Attributes
Tickval startTime_
Tickval delta_
Friends
std::ostream & operator<< (std::ostream &os, const IntervalTimer &what)
Detailed Description
High resolution interval timer.
Definition at line 190 of file timer.hpp.
Constructor & Destructor Documentation
FIX8::IntervalTimer::IntervalTimer () [inline]
Ctor. RAII.
Definition at line 196 of file timer.hpp.
virtual FIX8::IntervalTimer::~IntervalTimer () [inline, virtual]
Dtor.
Definition at line 199 of file timer.hpp.
Member Function Documentation
double FIX8::IntervalTimer::AsDouble () const [inline]
Get delta as a double.
Returns:
delta as double
Definition at line 212 of file timer.hpp.
References delta_, and FIX8::Tickval::todouble().
Referenced by Reset().
const IntervalTimer& FIX8::IntervalTimer::Calculate () [inline]
Calculate elapsed time (delta).
Returns:
reference to this object
Definition at line 203 of file timer.hpp.
References delta_, and startTime_.
Referenced by FIX8::Message::encode(), FIX8::Message::factory(), FIX8::FIXWriter::operator()(), and FIX8::Session::process().
double FIX8::IntervalTimer::Reset () [inline]
Reset the interval start time.
Returns:
the old delta as double
Definition at line 216 of file timer.hpp.
References AsDouble(), FIX8::Tickval::now(), and startTime_.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const IntervalTimer & what) [friend]
Format the interval to 9 decimal places, insert into stream.
Parameters:
os the stream to insert into
what the IntervalTimer object
Returns:
the stream, os
Definition at line 227 of file timer.hpp.
Member Data Documentation
Tickval FIX8::IntervalTimer::delta_ [private]
Definition at line 192 of file timer.hpp.
Referenced by AsDouble(), and Calculate().
Tickval FIX8::IntervalTimer::startTime_ [private]
Definition at line 192 of file timer.hpp.
Referenced by Calculate(), and Reset().
The documentation for this class was generated from the following file:
timer.hpp