fix8: FIX8::Field< int, field > Class Template Reference
FIX8::Field< int, field > Class Template Reference
Partial specialisation for int field type.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const int val, const RealmBase *rlm=nullptr)
Field (const f8String &from, const RealmBase *rlm=nullptr)
Field (const char *from, const RealmBase *rlm=nullptr)
Field & operator= (const Field &that)
Assignment operator.
virtual ~Field ()
Dtor.
bool operator== (const BaseField &that) const
Equivalence operator.
bool operator< (const BaseField &that) const
Less than operator.
bool operator> (const BaseField &that) const
Greater than operator.
bool is_valid () const
int get_rlm_idx () const
const int & get () const
const int & operator() () const
const int & set (const int &from)
const int & set_from_raw (const f8String &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Protected Attributes
int _value
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Static Protected Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_int
Detailed Description
template<unsigned short field>
class FIX8::Field< int, field >
Partial specialisation for int field type.
Template Parameters
field field number (fix tag)
Definition at line 268 of file field.hpp.
Constructor & Destructor Documentation
template<unsigned short field> FIX8::Field< int, field >::Field () inline
Ctor.
Definition at line 282 of file field.hpp.
template<unsigned short field> FIX8::Field< int, field >::Field (const Field< int, field > & from) inline
Copy Ctor.
Definition at line 286 of file field.hpp.
template<unsigned short field> FIX8::Field< int, field >::Field (const int val, const RealmBase * rlm = nullptr) inline
Value ctor.
Parameters
val value to set
rlm pointer to the realmbase for this field (if available)
Definition at line 291 of file field.hpp.
template<unsigned short field> FIX8::Field< int, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 296 of file field.hpp.
template<unsigned short field> FIX8::Field< int, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 301 of file field.hpp.
template<unsigned short field> virtual FIX8::Field< int, field >::~Field () inline virtual
Dtor.
Reimplemented in FIX8::Field< DayOfMonth, field >, FIX8::Field< NumInGroup, field >, FIX8::Field< SeqNum, field >, FIX8::Field< TagNum, field >, and FIX8::Field< Length, field >.
Definition at line 314 of file field.hpp.
Member Function Documentation
template<unsigned short field> Field* FIX8::Field< int, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 362 of file field.hpp.
References FIX8::Field< T, field >::Field().
template<unsigned short field> const int& FIX8::Field< int, field >::get () const inline
Get field value.
Returns
value (int)
Definition at line 344 of file field.hpp.
template<unsigned short field> static unsigned short FIX8::Field< int, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 276 of file field.hpp.
template<unsigned short field> int FIX8::Field< int, field >::get_rlm_idx () const inline virtual
Get the realm index of this value in the domain set.
Returns
the index in the domain set of this value
Reimplemented from FIX8::BaseField.
Definition at line 340 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::get_rlm_idx().
template<unsigned short field> FieldTrait::FieldType FIX8::Field< int, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 279 of file field.hpp.
template<unsigned short field> bool FIX8::Field< int, field >::is_valid () const inline
Check if this value is a member/in range of the domain set.
Returns
true if in the set or no domain available
Definition at line 336 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::is_valid().
template<unsigned short field> const int& FIX8::Field< int, field >::operator() () const inline
Get field value.
Returns
value (int)
Definition at line 348 of file field.hpp.
template<unsigned short field> bool FIX8::Field< int, field >::operator< (const BaseField< int, field > & that) const inline virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implements FIX8::BaseField.
Definition at line 325 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> Field& FIX8::Field< int, field >::operator= (const Field< int, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 306 of file field.hpp.
template<unsigned short field> bool FIX8::Field< int, field >::operator== (const BaseField< int, field > & that) const inline virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implements FIX8::BaseField.
Definition at line 319 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> bool FIX8::Field< int, field >::operator> (const BaseField< int, field > & that) const inline virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implements FIX8::BaseField.
Definition at line 331 of file field.hpp.
References FIX8::BaseField::same_base().
template<unsigned short field> std::ostream& FIX8::Field< int, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 367 of file field.hpp.
template<unsigned short field> size_t FIX8::Field< int, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 372 of file field.hpp.
References FIX8::itoa().
template<unsigned short field> const int& FIX8::Field< int, field >::set (const int & from) inline
Get field value.
Parameters
from value to set
Returns
original value (int)
Definition at line 353 of file field.hpp.
References FIX8::BaseField::from().
template<unsigned short field> const int& FIX8::Field< int, field >::set_from_raw (const f8String & from) inline
Set the value from a string.
Parameters
from value to set
Returns
original value (int)
Definition at line 358 of file field.hpp.
Member Data Documentation
template<unsigned short field> const FieldTrait::FieldType FIX8::Field< int, field >::_ftype = FieldTrait::ft_int static protected
Definition at line 272 of file field.hpp.
template<unsigned short field> int FIX8::Field< int, field >::_value protected
Definition at line 271 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp