fix8: FIX8::GeneratedTable< Key, Val > Class Template Reference
FIX8::GeneratedTable< Key, Val > Class Template Reference
Fast map for statically generated data types. Assumes table is sorted. Complexity is O(logN).
#include <f8types.hpp>
Public Types
typedef _Pair< Key, Val > Pair
Public Member Functions
GeneratedTable ()
Ctor.
Static Public Member Functions
static const Pair * begin ()
static const Pair * end ()
static const Val & find_ref (const Key &key)
static const Val find_val (const Key &key)
static const Val * find_ptr (const Key &key)
static const Pair * find_pair_ptr (const Key &key)
static const Pair * at (const size_t idx)
static size_t size ()
Private Types
typedef Val NotFoundType
Private Member Functions
template<>
const size_t _pairsz (0)
template<>
const GeneratedTable< unsigned
int, BaseEntry >::Pair _pairs []
template<>
const size_t _pairsz (0)
template<>
const GeneratedTable< const
char *, BaseMsgEntry >::Pair _pairs []
Static Private Attributes
static const Pair _pairs []
The actual data set.
static const size_t _pairsz
The number of elements in the data set.
static const NotFoundType _noval = {0, 0}
The value to return when the key is not found.
Detailed Description
template<typename Key, typename Val>
class FIX8::GeneratedTable< Key, Val >
Fast map for statically generated data types. Assumes table is sorted. Complexity is O(logN).
Template Parameters
Key the key
Val the value
Definition at line 89 of file f8types.hpp.
Member Typedef Documentation
template<typename Key , typename Val > typedef Val FIX8::GeneratedTable< Key, Val >::NotFoundType private
Definition at line 101 of file f8types.hpp.
template<typename Key , typename Val > typedef _Pair<Key, Val> FIX8::GeneratedTable< Key, Val >::Pair
Definition at line 92 of file f8types.hpp.
Constructor & Destructor Documentation
template<typename Key , typename Val > FIX8::GeneratedTable< Key, Val >::GeneratedTable () inline
Ctor.
Definition at line 107 of file f8types.hpp.
Member Function Documentation
template<> const GeneratedTable< unsigned int, BaseEntry >::Pair FIX8::GeneratedTable< unsigned int, BaseEntry >::_pairs () private
Definition at line 103 of file f8c.cpp.
Referenced by FIX8::GeneratedTable< Key, Val >::at(), FIX8::GeneratedTable< Key, Val >::begin(), FIX8::GeneratedTable< Key, Val >::end(), FIX8::GeneratedTable< Key, Val >::find_pair_ptr(), FIX8::GeneratedTable< Key, Val >::find_ptr(), FIX8::GeneratedTable< Key, Val >::find_ref(), and FIX8::GeneratedTable< Key, Val >::find_val().
template<> const GeneratedTable< const char *, BaseMsgEntry >::Pair FIX8::GeneratedTable< const char *, BaseMsgEntry >::_pairs () private
Definition at line 107 of file f8c.cpp.
template<> const size_t FIX8::GeneratedTable< unsigned int, BaseEntry >::_pairsz (0) private
template<> const size_t FIX8::GeneratedTable< const char *, BaseMsgEntry >::_pairsz (0) private
template<typename Key , typename Val > static const Pair* FIX8::GeneratedTable< Key, Val >::at (const size_t idx) inline static
Get the pair at index location
Parameters
idx of the pair to retrieve
Returns
reference to pair or _noval if not found
Definition at line 164 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs(), and FIX8::GeneratedTable< Key, Val >::_pairsz.
Referenced by FIX8::F8MetaCntx::F8MetaCntx().
template<typename Key , typename Val > static const Pair* FIX8::GeneratedTable< Key, Val >::begin () inline static
Get iterator to start of Pairs
Returns
pointer to first pair
Definition at line 111 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs().
template<typename Key , typename Val > static const Pair* FIX8::GeneratedTable< Key, Val >::end () inline static
Get iterator to last + 1 of Pairs
Returns
pointer to last + 1 pair
Definition at line 115 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs(), and FIX8::GeneratedTable< Key, Val >::_pairsz.
Referenced by FIX8::GeneratedTable< Key, Val >::find_pair_ptr(), FIX8::GeneratedTable< Key, Val >::find_ptr(), FIX8::GeneratedTable< Key, Val >::find_ref(), and FIX8::GeneratedTable< Key, Val >::find_val().
template<typename Key , typename Val > static const Pair* FIX8::GeneratedTable< Key, Val >::find_pair_ptr (const Key & key) inline static
Find a key pair record (pointer).
Parameters
key the key to find
Returns
key/value pair (pointer) or 0 if not found
Definition at line 154 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs(), FIX8::GeneratedTable< Key, Val >::_pairsz, and FIX8::GeneratedTable< Key, Val >::end().
template<typename Key , typename Val > static const Val* FIX8::GeneratedTable< Key, Val >::find_ptr (const Key & key) inline static
Find a key (pointer).
Parameters
key the key to find
Returns
value found (pointer) or 0 if not found
Definition at line 144 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs(), FIX8::GeneratedTable< Key, Val >::_pairsz, FIX8::_Pair< Key, Val >::_value, and FIX8::GeneratedTable< Key, Val >::end().
Referenced by FIX8::Session::create_msg(), and FIX8::Message::factory().
template<typename Key , typename Val > static const Val& FIX8::GeneratedTable< Key, Val >::find_ref (const Key & key) inline static
Find a key (reference). If not found, throw InvalidMetadata. Ye Olde Binary Chop
Parameters
key the key to find
Returns
value found (reference)
Definition at line 121 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairs(), FIX8::GeneratedTable< Key, Val >::_pairsz, FIX8::_Pair< Key, Val >::_value, and FIX8::GeneratedTable< Key, Val >::end().
template<typename Key , typename Val > static const Val FIX8::GeneratedTable< Key, Val >::find_val (const Key & key) inline static
Find a key (value).
Parameters
key the key to find
Returns
value found (value) or _noval if not found
Definition at line 134 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_noval, FIX8::GeneratedTable< Key, Val >::_pairs(), FIX8::GeneratedTable< Key, Val >::_pairsz, FIX8::_Pair< Key, Val >::_value, and FIX8::GeneratedTable< Key, Val >::end().
template<typename Key , typename Val > static size_t FIX8::GeneratedTable< Key, Val >::size () inline static
Get the number of elements in the data set.
Returns
number of elements
Definition at line 168 of file f8types.hpp.
References FIX8::GeneratedTable< Key, Val >::_pairsz.
Referenced by FIX8::F8MetaCntx::F8MetaCntx().
Member Data Documentation
template<typename Key , typename Val > const TEX::Perf_BaseEntry::NotFoundType FIX8::TEX::Perf_BaseEntry::_noval = {0, 0} static private
The value to return when the key is not found.
Definition at line 103 of file f8types.hpp.
Referenced by FIX8::GeneratedTable< Key, Val >::find_val().
template<typename Key , typename Val > const TEX::Perf_BaseEntry::Pair FIX8::TEX::Perf_BaseEntry::_pairs static private
The actual data set.
Definition at line 96 of file f8types.hpp.
template<typename Key , typename Val > const size_t FIX8::TEX::Perf_BaseEntry::_pairsz static private
The number of elements in the data set.
Definition at line 99 of file f8types.hpp.
Referenced by FIX8::GeneratedTable< Key, Val >::at(), FIX8::GeneratedTable< Key, Val >::end(), FIX8::GeneratedTable< Key, Val >::find_pair_ptr(), FIX8::GeneratedTable< Key, Val >::find_ptr(), FIX8::GeneratedTable< Key, Val >::find_ref(), FIX8::GeneratedTable< Key, Val >::find_val(), and FIX8::GeneratedTable< Key, Val >::size().
The documentation for this class was generated from the following files:
f8types.hpp
Myfix_classes.cpp
Myfix_types.cpp
Perf_classes.cpp
Perf_types.cpp