fix8: FIX8::f8_thread< T > Class Template Reference
FIX8::f8_thread< T > Class Template Reference
Thread wrapper. Ctor provides T instance and specifies ptr to member to call or defaults to operator()
#include <thread.hpp>
Classes
class _helper
Public Member Functions
f8_thread (std::reference_wrapper< T > what, int(T::*method)()=&T::operator(), f8_thread_cancellation_token &(T::*cancellation_token_method)()=&T::cancellation_token)
virtual ~f8_thread ()
Dtor.
int start ()
void request_stop ()
Public Member Functions inherited from FIX8::_f8_threadcore
_f8_threadcore ()
virtual ~_f8_threadcore ()
Dtor.
virtual int join (int timeoutInMs=0)
int yield () const
thread_id_t get_threadid () const
bool operator== (const _f8_threadcore &that) const
bool operator!= (const _f8_threadcore &that) const
_f8_threadcore & operator= (const _f8_threadcore &)=delete
Private Attributes
class FIX8::f8_thread::_helper _sub
Additional Inherited Members
Static Public Member Functions inherited from FIX8::_f8_threadcore
static thread_id_t getid ()
Protected Member Functions inherited from FIX8::_f8_threadcore
template<typename T >
int _start (void *sub)
Detailed Description
template<typename T>
class FIX8::f8_thread< T >
Thread wrapper. Ctor provides T instance and specifies ptr to member to call or defaults to operator()
Template Parameters
T class call thread entry functor
Definition at line 245 of file thread.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::f8_thread< T >::f8_thread (std::reference_wrapper< T > what, int(T::*)() method = &T::operator(), f8_thread_cancellation_token &(T::*)() cancellation_token_method = &T::cancellation_token) inline
Ctor. Reference to object, functor version.
Parameters
what reference wrapper of class with entry point
method reference to entry point method
cancellation_token_method pointer to cancellation_token
Definition at line 280 of file thread.hpp.
          : _sub(what, method, cancellation_token_method) {}
template<typename T> virtual FIX8::f8_thread< T >::~f8_thread () inline virtual
Dtor.
Definition at line 285 of file thread.hpp.
 {}
Member Function Documentation
template<typename T> void FIX8::f8_thread< T >::request_stop () inline virtual
request thread stop.
Returns
function result
Implements FIX8::_f8_threadcore.
Definition at line 293 of file thread.hpp.
Referenced by FIX8::AsyncSocket< f8String >::quit(), FIX8::FIXReader::quit(), FIX8::AsyncSocket< f8String >::request_stop(), FIX8::Timer< FIX8::Session >::stop(), FIX8::FIXReader::stop(), and FIX8::ReliableClientSession< T >::~ReliableClientSession().
 { _sub.cancellation_token().request_stop(); }
template<typename T> int FIX8::f8_thread< T >::start () inline virtual
start thread.
Returns
function result
Implements FIX8::_f8_threadcore.
Definition at line 289 of file thread.hpp.
Referenced by FIX8::Logger::Logger(), FIX8::AsyncSocket< f8String >::start(), FIX8::Timer< FIX8::Session >::start(), FIX8::FIXReader::start(), and FIX8::ReliableClientSession< T >::start().
 { return _start<_helper>(static_cast<void *>(&_sub)); }
Member Data Documentation
template<typename T> class FIX8::f8_thread::_helper FIX8::f8_thread< T >::_sub private
The documentation for this class was generated from the following file:
thread.hpp