fix8: FIX8::_f8_threadcore Class Reference
FIX8::_f8_threadcore Class Reference abstract
pthread wrapper abstract base
#include <thread.hpp>
Public Member Functions
_f8_threadcore ()
virtual ~_f8_threadcore ()
Dtor.
virtual int start ()=0
virtual void request_stop ()=0
virtual int join (int timeoutInMs=0)
int yield () const
thread_id_t get_threadid () const
bool operator== (const _f8_threadcore &that) const
bool operator!= (const _f8_threadcore &that) const
_f8_threadcore & operator= (const _f8_threadcore &)=delete
Static Public Member Functions
static thread_id_t getid ()
Protected Member Functions
template<typename T >
int _start (void *sub)
Static Private Member Functions
template<typename T >
static void * _run (void *what)
Private Attributes
pthread_attr_t _attr
pthread_t _tid
Detailed Description
pthread wrapper abstract base
Definition at line 65 of file thread.hpp.
Constructor & Destructor Documentation
FIX8::_f8_threadcore::_f8_threadcore () inline
Ctor.
Definition at line 96 of file thread.hpp.
       : _attr(), _tid()
    {
       if (pthread_attr_init(&_attr))
          throw f8_threadException("pthread_attr_init failure");
 #else
    {
 #endif
    }
virtual FIX8::_f8_threadcore::~_f8_threadcore () inline virtual
Dtor.
Definition at line 108 of file thread.hpp.
References join().
    {
      join();
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       pthread_attr_destroy(&_attr);
 #endif
    }
Member Function Documentation
template<typename T > static void* FIX8::_f8_threadcore::_run (void * what) inline static private
Definition at line 76 of file thread.hpp.
 { return reinterpret_cast<void *>((*static_cast<T *>(what))()); }
template<typename T > int FIX8::_f8_threadcore::_start (void * sub) inline protected
Definition at line 84 of file thread.hpp.
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return pthread_create(&_tid, &_attr, _run<T>, sub);
 #elif (FIX8_THREAD_SYSTEM == FIX8_THREAD_STDTHREAD)
       _thread.reset(new std::thread(_run<T>, sub));
 #endif
       return 0;
    }
thread_id_t FIX8::_f8_threadcore::get_threadid () const inline
Get the thread's thread ID.
Returns
the thread id
Definition at line 157 of file thread.hpp.
References _tid.
Referenced by join(), operator!=(), and operator==().
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return _tid;
 #elif (FIX8_THREAD_SYSTEM == FIX8_THREAD_STDTHREAD)
       return _thread.get() ? _thread->get_id() : std::thread::id();
 #endif
    }
static thread_id_t FIX8::_f8_threadcore::getid () inline static
Get the thread's thread ID. Static version.
Returns
the thread id
Definition at line 168 of file thread.hpp.
Referenced by join().
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return pthread_self();
 #elif (FIX8_THREAD_SYSTEM == FIX8_THREAD_STDTHREAD)
       return std::this_thread::get_id();
 #endif
    }
virtual int FIX8::_f8_threadcore::join (int timeoutInMs = 0) inline virtual
Join the thread.
Returns
result of join
Definition at line 126 of file thread.hpp.
References get_threadid(), and getid().
Referenced by FIX8::AsyncSocket< f8String >::join(), FIX8::Timer< FIX8::Session >::join(), FIX8::FIXReader::quit(), FIX8::Logger::stop(), ~_f8_threadcore(), and FIX8::ReliableClientSession< T >::~ReliableClientSession().
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return getid() != get_threadid() ? pthread_join(_tid, nullptr) ? -1 : 0 : -1; // prevent self-join
 #elif (FIX8_THREAD_SYSTEM == FIX8_THREAD_STDTHREAD)
       if (_thread.get() && _thread->joinable() && getid() != get_threadid())
          _thread->join();
       return 0;
 #endif
    }
bool FIX8::_f8_threadcore::operator!= (const _f8_threadcore & that) const inline
f8_thread inequivalence operator.
Parameters
that the other thread id
Returns
true if the threads are unequal
Definition at line 192 of file thread.hpp.
References _tid, and get_threadid().
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return !pthread_equal(_tid, that._tid);
 #else
       return get_threadid() != that.get_threadid();
 #endif
    }
_f8_threadcore& FIX8::_f8_threadcore::operator= (const _f8_threadcore &) delete
bool FIX8::_f8_threadcore::operator== (const _f8_threadcore & that) const inline
f8_thread equivalence operator.
Parameters
that the other thread id
Returns
true if the threads are equal
Definition at line 180 of file thread.hpp.
References _tid, and get_threadid().
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return pthread_equal(_tid, that._tid);
 #else
       return get_threadid() == that.get_threadid();
 #endif
    }
virtual void FIX8::_f8_threadcore::request_stop () pure virtual
request thread stop.
Returns
function result
Implemented in FIX8::f8_thread< T >, FIX8::f8_thread< FIX8::AsyncSocket >, FIX8::f8_thread< FIX8::ReliableClientSession< T > >, FIX8::f8_thread< FIX8::FIXReader >, FIX8::f8_thread< FIX8::Logger >, and FIX8::f8_thread< FIX8::Timer >.
virtual int FIX8::_f8_threadcore::start () pure virtual
start thread.
Returns
function result
Implemented in FIX8::f8_thread< T >, FIX8::f8_thread< FIX8::AsyncSocket >, FIX8::f8_thread< FIX8::ReliableClientSession< T > >, FIX8::f8_thread< FIX8::FIXReader >, FIX8::f8_thread< FIX8::Logger >, and FIX8::f8_thread< FIX8::Timer >.
int FIX8::_f8_threadcore::yield () const inline
Yield CPU.
Returns
result of yield
Definition at line 143 of file thread.hpp.
    {
 #if (FIX8_THREAD_SYSTEM == FIX8_THREAD_PTHREAD)
       return pthread_yield();
 #elif (FIX8_THREAD_SYSTEM == FIX8_THREAD_STDTHREAD)
       std::this_thread::yield();
 #endif
       return 0;
    }
Member Data Documentation
pthread_attr_t FIX8::_f8_threadcore::_attr private
Definition at line 68 of file thread.hpp.
pthread_t FIX8::_f8_threadcore::_tid private
Definition at line 69 of file thread.hpp.
Referenced by get_threadid(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
thread.hpp