fix8: ff::ff_node Class Reference
ff::ff_node Class Reference abstract
Describes the FastFlow node.
#include <node.hpp>
Classes
class thWorker
An inner class for FastFlow's thread.
Public Types
enum { TICKS2WAIT =1000 }
Public Member Functions
virtual void * svc (void *task)=0
The svc method.
virtual int svc_init ()
The svc_init()
virtual void svc_end ()
The svc_end()
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Protected Member Functions
void set_id (int id)
Sets the node identifer.
virtual bool push (void *ptr)
Pushes to output buffer.
virtual bool pop (void **ptr)
Pops the data from input buffer.
virtual void skipfirstpop (bool sk)
Skips the first element popped.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int run (bool=false)
Executes the FastFlow thread.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait ()
Waits for thread termination.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual int cardinality (BARRIER_T *const b)
Counts how many threads there are in this node.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Private Member Functions
void registerCallback (bool(*cb)(void *, unsigned int, unsigned int, void *), void *arg)
Registers the call back.
void setCPUId (int id)
int getTid () const
Private Attributes
FFBUFFER * in
FFBUFFER * out
int myid
This is the node id, it is valid only for farm's workers.
int CPUId
bool myoutbuffer
bool myinbuffer
bool skip1pop
bool in_active
thWorker * thread
bool(* callback)(void *, unsigned int, unsigned int, void *)
A thWorker object, which extends the ff_thread class.
void * callback_arg
BARRIER_T * barrier
struct timeval tstart
A Barrier object.
struct timeval tstop
struct timeval wtstart
struct timeval wtstop
double wttime
Friends
template<typename lb_t , typename gt_t >
class ff_farm
class ff_pipeline
class ff_loadbalancer
class ff_gatherer
Detailed Description
Describes the FastFlow node.
This class describes the ff_node, which is the basic building block of every skeleton in stream programming. It is used to encapsulate sequential portions of code implementing functions. ff_node defines 3 methods; two optional and one mandatory. The optional methods are (1) svc_init and (2) svc_end. The mandatory method is svc (pure virtual method). The svc_init method is called once at node initialization, while the svn_end method is called once when the end-of-stream (EOS) is received in input or when the svc method returns NULL. the svc method is called each time an input task is ready to be procedded.
This class is defined in node.hpp
Definition at line 738 of file node.hpp.
Member Enumeration Documentation
anonymous enum
Defines the number of ticks to wait.
Enumerator
TICKS2WAIT
Definition at line 1026 of file node.hpp.
Constructor & Destructor Documentation
ff::ff_node::ff_node () inline protected
Protected constructor.
It is the protected constructor. It initializes the FastFlow node.
Definition at line 1257 of file node.hpp.
References FFTRACE, init_unlocked(), pushwait(), ff::time_setzero(), tstart, tstop, wtstart, wtstop, and wttime.
virtual ff::ff_node::~ff_node () inline protected virtual
Destructor.
It is a desctructor and it deletes input buffers and output buffers and the working thread.
Definition at line 1275 of file node.hpp.
References in, myinbuffer, myoutbuffer, out, and thread.
Member Function Documentation
virtual int ff::ff_node::cardinality (BARRIER_T *const b) inline protected virtual
Counts how many threads there are in this node.
Counts the n. of threads that should block in the barrier.
b is the barrier.
Returns
always 1
Reimplemented in ff::ff_monode, ff::ff_minode, ff::ff_pipeline, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 983 of file node.hpp.
References barrier.
virtual int ff::ff_node::create_input_buffer (int nentries, bool fixedsize = true) inline protected virtual
Creates the input buffer.
It create an input buffer for the ff_node.
Parameters
nentries the size of the buffer
fixedsize flag to decide whether the buffer is resizable. Default is true
Returns
0 if successful, otherwise a negative value.
Reimplemented in ff::ff_minode, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 811 of file node.hpp.
References FFBUFFER, in, and myinbuffer.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::create_input_buffer(), and ff::ff_dnode< CommImplIn >::init().
virtual int ff::ff_node::create_output_buffer (int nentries, bool fixedsize = false) inline protected virtual
Creates the output buffer.
It creates an output buffer for the ff_node.
Parameters
nentries the size of the buffer
fixedsize flag to decide whether the buffer is resizable. Default is false .
Returns
0 if successful, otherwise a negative value.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 830 of file node.hpp.
References FFBUFFER, myoutbuffer, and out.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::create_output_buffer(), and ff::ff_dnode< CommImplIn >::init().
virtual void ff::ff_node::eosnotify (int id = -1) inline virtual
Notifies EOS.
It is a virtual function. It is called once just after the EOS has arrived.
Parameters
id is the ID of the input channel, it makes sense only for N-to-1 input channels.
Reimplemented in ff::ff_ofarm::ofarmC.
Definition at line 1065 of file node.hpp.
Referenced by ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), and ff::ff_node::thWorker::svc().
virtual bool ff::ff_node::ff_send_out (void * task, unsigned int retry = ((unsigned int)-1), unsigned int ticks = (TICKS2WAIT)) inline protected virtual
Sends out the task.
It allows to queue tasks without returning from the svc method
task a pointer to the task retry number of tries to push the task to the buffer ticks number of ticks to wait
Returns
If call back is defined, then returns the status of callback function. Otherwise, if tries to push an element with the number of and if succesfful true is returned, and if after the number of the push is not successful false is returned.
Definition at line 1295 of file node.hpp.
References callback, callback_arg, push(), and ff::ticks_wait().
Referenced by ff::ff_ofarm::ofarmE::svc(), and ff::ff_ofarm::ofarmC::svc().
virtual double ff::ff_node::ffTime () inline protected virtual
Gets the time.
It retrives the tim spent in FastFlow pattern.
Returns
The difference in the time spent.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 1006 of file node.hpp.
References ff::diffmsec(), tstart, and tstop.
virtual void ff::ff_node::freeze () inline protected virtual
Freezes the thread.
It freezes the thread.
Returns
If thread does not exist, then the method returns.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 942 of file node.hpp.
References ff::ff_node::thWorker::freeze(), and thread.
Referenced by freeze_and_run().
virtual int ff::ff_node::freeze_and_run (bool = false) inline protected virtual
Freezes the thread and then run.
It freezes the thread and then run.
Returns
It returns the state of the run method if successful, otherwise a negative value is returned.
Reimplemented in ff::ff_pipeline, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 890 of file node.hpp.
References freeze(), ff::ff_node::thWorker::run(), and thread.
virtual bool ff::ff_node::get (void ** ptr) inline virtual
Pops the task.
It pops the task without acquiring the lock.
ptr is a pointer to the task
Returns
The status of pop operation as Boolean value
Definition at line 1155 of file node.hpp.
References out.
Referenced by ff::ff_node::thWorker::get().
virtual FFBUFFER* ff::ff_node::get_in_buffer () const inline virtual
Gets input buffer.
It returns a pointer to the input buffer.
Returns
A pointer to the input buffer
Definition at line 1165 of file node.hpp.
References in.
Referenced by ff::ff_pipeline::create_input_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::create_input_buffer(), ff::ff_pipeline::offload(), ff::ff_farm< ofarm_lb, ofarm_gt >::offload(), ff::ff_pipeline::prepare(), ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), ff::ff_node::thWorker::svc(), ff::ff_pipeline::wrap_around(), and ff::ff_farm< ofarm_lb, ofarm_gt >::wrap_around().
virtual int ff::ff_node::get_my_id () const inline virtual
Gets the ID of the ff_node.
Returns
The ID of the ff_node
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_map.
Definition at line 1072 of file node.hpp.
References myid.
Referenced by ff::ff_node::thWorker::get_my_id(), ff::ff_map::mapW::svc(), ff::forallreduce_W< Tres >::svc(), ff::ff_pipeline::wait(), and ff::ff_pipeline::wait_freezing().
virtual FFBUFFER* ff::ff_node::get_out_buffer () const inline virtual
Gets pointer to the output buffer.
It returns a pointer to the output buffer.
Returns
A pointer to the output buffer.
Definition at line 1174 of file node.hpp.
References out.
Referenced by ff::ff_pipeline::create_output_buffer(), ff::ff_pipeline::load_result(), ff::ff_pipeline::load_result_nb(), ff::ff_pipeline::prepare(), ff::ff_gatherer::svc(), and ff::ff_node::thWorker::svc().
virtual int ff::ff_node::getCPUId () const inline virtual
Gets the CPU id (if set) of this node is pinned.
It gets the ID of the CPU where the thread is running.
Returns
The identifier of the CPU.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_map.
Definition at line 1096 of file node.hpp.
References CPUId.
Referenced by ff::ff_map::getCPUId(), ff::ff_gatherer::run(), ff::ff_loadbalancer::run(), ff::ff_node::thWorker::run(), ff::ff_loadbalancer::runlb(), and ff::ff_node::thWorker::svc_init().
virtual struct timeval ff::ff_node::getstarttime () const inline read virtual
Gets start time.
It resturns the starting time.
Returns
Starting time.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 1183 of file node.hpp.
References tstart.
virtual struct timeval ff::ff_node::getstoptime () const inline read virtual
Gets stop time.
It returns the stopping time.
Returns
Stopping time.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 1192 of file node.hpp.
References tstop.
int ff::ff_node::getTid () const inline private
Returns the internal thread identifier.
Definition at line 1337 of file node.hpp.
References ff::ff_thread::getTid(), and thread.
Referenced by ff::ff_loadbalancer::getTid().
virtual struct timeval ff::ff_node::getwstartime () const inline read virtual
Gets start time.
It returns the starting time.
Returns
Starting time.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 1201 of file node.hpp.
References wtstart.
virtual struct timeval ff::ff_node::getwstoptime () const inline read virtual
Gets the stop time.
It returns the stopping time.
Returns
Stopping time.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, and ff::ff_farm< ofarm_lb, ofarm_gt >.
Definition at line 1210 of file node.hpp.
References wtstop.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::getwstoptime().
virtual void ff::ff_node::input_active (const bool onoff) inline protected virtual
Definition at line 1307 of file node.hpp.
References in_active.
virtual bool ff::ff_node::isfrozen () inline protected virtual
Checks if the thread is frozen.
It checks whether the thread is frozen.
Returns
If the thread does not exists then false is returned, otherwise the status of isfrozen() is returned.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 968 of file node.hpp.
References ff::ff_node::thWorker::isfrozen(), and thread.
virtual bool ff::ff_node::pop (void ** ptr) inline protected virtual
Pops the data from input buffer.
It is a virtual method. It pops data from the input buffer.
Parameters
ptr pointer to the location where the data is located
Returns
A boolean value showing the status of the pop operation.
Reimplemented in ff::ff_dnode< CommImpl >, ff::ff_dnode< CommImplIn >, and ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 777 of file node.hpp.
References in, and in_active.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::pop(), ff::ff_dnode< CommImplIn >::pop(), ff::ff_loadbalancer::pop(), and ff::ff_node::thWorker::pop().
virtual bool ff::ff_node::push (void * ptr) inline protected virtual
Pushes to output buffer.
It is a virtual method. It pushes data into the output buffer.
Parameters
ptr pointer to the data to be pushed out.
Returns
Boolean value showing the status of push operation.
Reimplemented in ff::ff_dinout< CommImplIn, CommImplOut >, ff::ff_dnode< CommImpl >, ff::ff_dnode< CommImplIn >, and ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 766 of file node.hpp.
References out.
Referenced by ff_send_out(), ff::ff_dinout< CommImplIn, CommImplOut >::push(), ff::ff_gatherer::push(), ff::ff_dnode< CommImplIn >::push(), and ff::ff_node::thWorker::push().
virtual bool ff::ff_node::put (void * ptr) inline virtual
Pushes the task.
It pushes task without using locks.
ptr is a pointer to the task
Returns
The status of push as Boolean value
Definition at line 1142 of file node.hpp.
References in.
Referenced by ff::ff_loadbalancer::broadcast_task(), ff::ff_loadbalancer::push_task(), and ff::ff_node::thWorker::put().
void ff::ff_node::registerCallback (bool(*)(void *, unsigned int, unsigned int, void *) cb, void * arg) inline private
Registers the call back.
It registers the call back method and arguments.
cb is the callback function arg is a pointer to arguments
Definition at line 1322 of file node.hpp.
References callback, and callback_arg.
Referenced by ff::ff_loadbalancer::set_filter().
void ff::ff_node::reset () inline
Resets input/output queues.
Warning resetting queues while the node is running may produce to unexpected results.
Definition at line 1246 of file node.hpp.
References in, and out.
Referenced by ff::ff_forall_farm< Tres >::resetqueues().
virtual int ff::ff_node::run (bool = false) inline protected virtual
Executes the FastFlow thread.
It executes the FastFlow thread.
Returns
The state of the run method if successful, otherwise a negative value is returned.
Reimplemented in ff::ff_monode, ff::ff_minode, ff::ff_ofarm, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, ff::ff_dnode< CommImpl >, ff::ff_dnode< CommImplIn >, ff::ff_dinout< CommImplIn, CommImplOut >, and ff::ff_pipeline.
Definition at line 876 of file node.hpp.
References ff::ff_node::thWorker::run(), and thread.
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::run(), and ff::ff_dnode< CommImplIn >::run().
virtual void ff::ff_node::set_barrier (BARRIER_T *const b) inline protected virtual
Sets the barrier.
It sets the barrier.
b is the barrier.
Definition at line 995 of file node.hpp.
References barrier.
void ff::ff_node::set_id (int id) inline protected
Sets the node identifer.
It sets node identifier.
id is the identifier of the node.
Definition at line 755 of file node.hpp.
References myid.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::add_workers().
virtual int ff::ff_node::set_input_buffer (FFBUFFER *const i) inline protected virtual
Sets the input buffer.
It sets the input buffer for the ff_node.
Parameters
i a buffer object of type FFBUFFER
Returns
0 if successful otherwise a negative value is returned.
Definition at line 862 of file node.hpp.
References in, and myinbuffer.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::add_emitter(), and ff::ff_pipeline::create_input_buffer().
virtual int ff::ff_node::set_output_buffer (FFBUFFER *const o) inline protected virtual
Sets the output buffer.
It sets the output buffer for the ff_node.
Parameters
o a buffer object of type FFBUFFER
Returns
0 if successful, otherwise a negative value is returned.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 847 of file node.hpp.
References myoutbuffer, and out.
Referenced by ff::ff_pipeline::create_output_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::create_output_buffer(), and ff::ff_farm< ofarm_lb, ofarm_gt >::set_output_buffer().
virtual void ff::ff_node::setAffinity (int cpuID) inline virtual
Sets threads affinity.
It is a virtual function. It maps the working thread to the chosen CPU.
Parameters
cpuID is the ID of the CPU to which the thread will be pinned.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, ff::ff_pipeline, and ff::ff_map.
Definition at line 1082 of file node.hpp.
References CPUId, ff::error(), and ff::threadMapper::instance().
Referenced by ff::ff_map::setAffinity().
void ff::ff_node::setCPUId (int id) inline private
Sets the CPU id for this node (used only in the run-time)
Definition at line 1331 of file node.hpp.
References CPUId.
Referenced by ff::ff_node::thWorker::run(), and ff::ff_node::thWorker::svc_init().
virtual void ff::ff_node::skipfirstpop (bool sk) inline protected virtual
Skips the first element popped.
It skips the first element popped.
sk Boolean value showing if the first element should be skipped.
Reimplemented in ff::ff_monode, ff::ff_minode, ff::ff_dnode< CommImpl >, ff::ff_dnode< CommImplIn >, and ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 789 of file node.hpp.
References skip1pop.
Referenced by ff::ff_node::thWorker::svc().
bool ff::ff_node::skipfirstpop () const inline protected
Gets the status of skipfirstpop.
It returns the status of ski1pop
Returns
A booleon value showing the status of ski1pop
Definition at line 798 of file node.hpp.
References skip1pop.
Referenced by ff::ff_minode::create_input_buffer(), ff::ff_dinout< CommImplIn, CommImplOut >::skipfirstpop(), ff::ff_dnode< CommImplIn >::skipfirstpop(), ff::ff_minode::skipfirstpop(), and ff::ff_node::thWorker::svc().
virtual void ff::ff_node::stop () inline protected virtual
Stops the thread.
It stops thread.
Returns
If the thread does not exist, then the method is returned.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 930 of file node.hpp.
References ff::ff_thread::stop(), and thread.
Referenced by ff::forall_Scheduler::init_data().
virtual void* ff::ff_node::svc (void * task) pure virtual
The svc method.
It is a pure virtual function. If svc returns a NULL value then End-Of-Stream (EOS) is produced on the output channel.
task is the input data stream.
Implemented in ff::ff_ofarm::ofarmC, ff::ff_ofarm::ofarmE, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, ff::Fstage< T >, ff::ff_pipeline, ff::forall_Scheduler, ff::forallreduce_W< Tres >, ff::ff_map::mapW, ff::ff_map::mapC, ff::ff_map::mapE, and ff::ff_farm< lb_t, gt_t >::ff_node_F< T >.
Referenced by ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), ff::ff_ofarm::ofarmE::svc(), ff::ff_ofarm::ofarmC::svc(), and ff::ff_node::thWorker::svc().
virtual void ff::ff_node::svc_createOCL () inline virtual
Create OCL.
It creates OCL. FIXME: How it creates?
Reimplemented in ff::ff_oclNode.
Definition at line 1217 of file node.hpp.
virtual void ff::ff_node::svc_end () inline virtual
The svc_end()
It is a virtual function. This is called only once for each thread, right after the svc method.
Reimplemented in ff::ff_ofarm::ofarmC, ff::ff_ofarm::ofarmE, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 1054 of file node.hpp.
Referenced by ff::ff_gatherer::svc_end(), ff::ff_loadbalancer::svc_end(), ff::ff_ofarm::ofarmE::svc_end(), ff::ff_ofarm::ofarmC::svc_end(), and ff::ff_node::thWorker::svc_end().
virtual int ff::ff_node::svc_init () inline virtual
The svc_init()
It is a virtual function. This is called only once for each thread, right before the svc method.
Returns
0 is always returned.
Reimplemented in ff::ff_ofarm::ofarmC, ff::ff_ofarm::ofarmE, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 1046 of file node.hpp.
Referenced by ff::ff_gatherer::svc_init(), ff::ff_loadbalancer::svc_init(), ff::ff_ofarm::ofarmE::svc_init(), ff::ff_ofarm::ofarmC::svc_init(), and ff::ff_node::thWorker::svc_init().
virtual void ff::ff_node::svc_releaseOCL () inline virtual
Releases OCL.
It releases OCL. FIXME: How it releases?
Reimplemented in ff::ff_oclNode.
Definition at line 1224 of file node.hpp.
virtual void ff::ff_node::thaw (bool _freeze = false) inline protected virtual
Checks to thaw a thread.
It checks if the thread is created then thaw it.
Returns
If the thread does not exist then the method is returned, otherwise the thread is thawed.
Reimplemented in ff::ff_pipeline.
Definition at line 955 of file node.hpp.
References ff::ff_thread::thaw(), and thread.
virtual int ff::ff_node::wait () inline protected virtual
Waits for thread termination.
It lets the thread to wait until termination.
Returns
If successful the state of the wait method otherwise a negative value.
Reimplemented in ff::ff_monode, ff::ff_minode, ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, ff::ff_dnode< CommImpl >, ff::ff_dnode< CommImplIn >, ff::ff_pipeline, and ff::ff_dinout< CommImplIn, CommImplOut >.
Definition at line 905 of file node.hpp.
References thread, and ff::ff_node::thWorker::wait().
Referenced by ff::ff_dinout< CommImplIn, CommImplOut >::wait(), and ff::ff_dnode< CommImplIn >::wait().
virtual int ff::ff_node::wait_freezing () inline protected virtual
Waits for thread to thaw.
It wait for thread to thaw.
Returns
If successful the state of the wait_freezing method, otherwise a negative value.
Reimplemented in ff::ff_farm< lb_t, gt_t >, ff::ff_farm<>, ff::ff_farm< map_lb, map_gt >, ff::ff_farm< ofarm_lb, ofarm_gt >, and ff::ff_pipeline.
Definition at line 918 of file node.hpp.
References thread, and ff::ff_node::thWorker::wait_freezing().
virtual double ff::ff_node::wffTime () inline protected virtual
Gets the time.
It retrieves the time spend in FastFlow skeleton.
Returns
The difference in the time spent.
Definition at line 1017 of file node.hpp.
References ff::diffmsec(), wtstart, and wtstop.
Friends And Related Function Documentation
template<typename lb_t , typename gt_t > friend class ff_farm friend
Definition at line 742 of file node.hpp.
friend class ff_gatherer friend
Definition at line 745 of file node.hpp.
friend class ff_loadbalancer friend
Definition at line 744 of file node.hpp.
friend class ff_pipeline friend
Definition at line 743 of file node.hpp.
Member Data Documentation
BARRIER_T* ff::ff_node::barrier private
Definition at line 1600 of file node.hpp.
Referenced by cardinality(), ff::ff_pipeline::run(), ff::ff_farm< ofarm_lb, ofarm_gt >::run(), set_barrier(), ff::ff_farm< ofarm_lb, ofarm_gt >::~ff_farm(), and ff::ff_pipeline::~ff_pipeline().
bool(* ff::ff_node::callback)(void *, unsigned int, unsigned int, void *) private
A thWorker object, which extends the ff_thread class.
Definition at line 1598 of file node.hpp.
Referenced by ff_send_out(), and registerCallback().
void* ff::ff_node::callback_arg private
Definition at line 1599 of file node.hpp.
Referenced by ff_send_out(), and registerCallback().
int ff::ff_node::CPUId private
Definition at line 1592 of file node.hpp.
Referenced by getCPUId(), ff::ff_node::thWorker::run(), setAffinity(), and setCPUId().
FFBUFFER* ff::ff_node::in private
          Input buffer, built upon SWSR lock-free (wait-free)
(un)bounded FIFO queue
Definition at line 1587 of file node.hpp.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::add_emitter(), ff::ff_pipeline::create_input_buffer(), create_input_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::create_input_buffer(), get_in_buffer(), pop(), put(), reset(), set_input_buffer(), and ~ff_node().
bool ff::ff_node::in_active private
Definition at line 1596 of file node.hpp.
Referenced by ff::ff_loadbalancer::collect_task(), input_active(), pop(), and ff::ff_node::thWorker::pop().
int ff::ff_node::myid private
This is the node id, it is valid only for farm's workers.
Definition at line 1591 of file node.hpp.
Referenced by get_my_id(), and set_id().
bool ff::ff_node::myinbuffer private
Definition at line 1594 of file node.hpp.
Referenced by create_input_buffer(), set_input_buffer(), and ~ff_node().
bool ff::ff_node::myoutbuffer private
Definition at line 1593 of file node.hpp.
Referenced by create_output_buffer(), set_output_buffer(), and ~ff_node().
FFBUFFER* ff::ff_node::out private
         Output buffer, built upon SWSR lock-free (wait-free)
(un)bounded FIFO queue
Definition at line 1589 of file node.hpp.
Referenced by create_output_buffer(), get(), get_out_buffer(), push(), reset(), set_output_buffer(), and ~ff_node().
bool ff::ff_node::skip1pop private
Definition at line 1595 of file node.hpp.
Referenced by skipfirstpop().
thWorker* ff::ff_node::thread private
Definition at line 1597 of file node.hpp.
Referenced by freeze(), freeze_and_run(), getTid(), isfrozen(), run(), stop(), thaw(), wait(), wait_freezing(), and ~ff_node().
struct timeval ff::ff_node::tstart private
A Barrier object.
Definition at line 1601 of file node.hpp.
Referenced by ff_node(), ffTime(), getstarttime(), and ff::ff_node::thWorker::svc_init().
struct timeval ff::ff_node::tstop private
Definition at line 1602 of file node.hpp.
Referenced by ff_node(), ffTime(), getstoptime(), and ff::ff_node::thWorker::svc_end().
struct timeval ff::ff_node::wtstart private
Definition at line 1603 of file node.hpp.
Referenced by ff_node(), getwstartime(), ff::ff_node::thWorker::svc(), and wffTime().
struct timeval ff::ff_node::wtstop private
Definition at line 1604 of file node.hpp.
Referenced by ff_node(), getwstoptime(), ff::ff_node::thWorker::svc(), and wffTime().
double ff::ff_node::wttime private
Definition at line 1605 of file node.hpp.
Referenced by ff_node(), and ff::ff_node::thWorker::svc().
The documentation for this class was generated from the following file:
node.hpp