fix8: ff::zmqAllGather Class Reference
ff::zmqAllGather Class Reference
It provides implementation of the ALL_GATHER communication pattern.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 0 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
typedef msg_t tosend_t
typedef svector< msg_t > torecv_t
typedef descriptorN_1 descriptor
Public Member Functions
zmqAllGather ()
zmqAllGather (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const msg_t &msg, const int)
bool putmore (const tosend_t &msg, const int)
bool gethdr (msg_t &msg, int &peer)
bool get (msg_t &msg, int &peer)
bool get (torecv_t &msg)
int getToWait () const
int putToPerform () const
void done ()
bool close ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
It provides implementation of the ALL_GATHER communication pattern.
This class is defined in zmqImpl.hpp
Definition at line 1156 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptorN_1 ff::zmqAllGather::descriptor
Definition at line 1162 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmqAllGather::msg_t
Definition at line 1158 of file zmqImpl.hpp.
typedef svector<msg_t> ff::zmqAllGather::torecv_t
Definition at line 1161 of file zmqImpl.hpp.
typedef msg_t ff::zmqAllGather::tosend_t
Definition at line 1160 of file zmqImpl.hpp.
typedef zmqTransport ff::zmqAllGather::TransportImpl
Definition at line 1159 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 1164 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmqAllGather::zmqAllGather () inline
Constructor (1)
Definition at line 1169 of file zmqImpl.hpp.
ff::zmqAllGather::zmqAllGather (descriptor * D) inline
Constructor (2)
D is the descriptor.
Definition at line 1176 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmqAllGather::close () inline
It closes communication pattern.
Returns
TODO
Definition at line 1311 of file zmqImpl.hpp.
References active, ff::descriptorN_1::close(), desc, ff::descriptorN_1::P, and ff::descriptorN_1::recvreq().
void ff::zmqAllGather::done () inline
It finishes the communication process.
Definition at line 1304 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::done().
Referenced by get(), and init().
bool ff::zmqAllGather::get (msg_t & msg, int & peer) inline
It receives one message ONLY from one peer (gethdr should be called before).
Parameters
msg is the reference to the message.
peer is the number of peers.
Returns
TODO
Definition at line 1268 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::recv().
bool ff::zmqAllGather::get (torecv_t & msg) inline
It receives one message.
Returns
TODO
Definition at line 1277 of file zmqImpl.hpp.
References desc, done(), ff::descriptorN_1::getPeers(), and ff::descriptorN_1::recv().
descriptor* ff::zmqAllGather::getDescriptor () inline
It returns the descriptor.
Returns
It returns the descriptor.
Definition at line 1191 of file zmqImpl.hpp.
References desc.
bool ff::zmqAllGather::gethdr (msg_t & msg, int & peer) inline
It receives the message header ONLY from one peer (should be called before get).
msg is the reference to the message.
Parameters
peer is the number of peers.
Returns
TODO
Definition at line 1256 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::recvhdr().
int ff::zmqAllGather::getToWait () const inline
It returns the number of distinct messages for one single communication.
Returns
TODO
Definition at line 1292 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::getPeers().
bool ff::zmqAllGather::init (const std::string & address, const int nodeId = -1) inline
It initializes communication pattern.
Returns
TODO
Definition at line 1198 of file zmqImpl.hpp.
References active, desc, done(), ff::descriptorN_1::init(), and ff::descriptorN_1::P.
bool ff::zmqAllGather::put (const tosend_t & msg) inline
It sends one message.
msg is the reference of the message.
Returns
TODO
Definition at line 1212 of file zmqImpl.hpp.
References desc, ff::descriptorN_1::recvreq(), and ff::descriptorN_1::send().
Referenced by put().
bool ff::zmqAllGather::put (const msg_t & msg, const int) inline
It puts single message.
msg is the reference to the message.
Returns
TODO
Definition at line 1233 of file zmqImpl.hpp.
References put().
bool ff::zmqAllGather::putmore (const tosend_t & msg) inline
It puts more messages in the sening queue.
msg is the reference to the message.
Returns
TODO
Definition at line 1224 of file zmqImpl.hpp.
References desc, and ff::descriptorN_1::send().
Referenced by putmore().
bool ff::zmqAllGather::putmore (const tosend_t & msg, const int) inline
It put more messages.
msg is the reference to the message.
Returns
TODO
Definition at line 1244 of file zmqImpl.hpp.
References putmore().
int ff::zmqAllGather::putToPerform () const inline
It puts the node in performing state.
Returns
TODO
Definition at line 1299 of file zmqImpl.hpp.
void ff::zmqAllGather::setDescriptor (descriptor * D) inline
It sets the descriptor.
Definition at line 1181 of file zmqImpl.hpp.
References ff::descriptorN_1::close(), and desc.
Member Data Documentation
bool ff::zmqAllGather::active protected
Definition at line 1321 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmqAllGather::desc protected
Definition at line 1320 of file zmqImpl.hpp.
Referenced by close(), done(), get(), getDescriptor(), gethdr(), getToWait(), init(), put(), putmore(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp