fix8: FIX8::SessionID Class Reference
FIX8::SessionID Class Reference
Quickfix style sessionid.
#include <session.hpp>
Public Member Functions
SessionID (const f8String &beginString, const f8String &senderCompID, const f8String &targetCompID)
SessionID (const begin_string &beginString, const sender_comp_id &senderCompID, const target_comp_id &targetCompID)
SessionID (const f8String &from)
SessionID (const SessionID &from)
SessionID ()
virtual ~SessionID ()
Dtor.
F8API void make_id ()
F8API SessionID make_reverse_id () const
F8API void from_string (const f8String &from)
Create a sessionid string.
const begin_string & get_beginString () const
const sender_comp_id & get_senderCompID () const
const target_comp_id & get_targetCompID () const
const f8String & get_id () const
bool same_sender_comp_id (const target_comp_id &targetCompID) const
bool same_target_comp_id (const sender_comp_id &senderCompID) const
bool same_side_target_comp_id (const target_comp_id &targetCompID) const
bool same_side_sender_comp_id (const sender_comp_id &senderCompID) const
bool operator== (const SessionID &that)
bool operator!= (const SessionID &that)
Private Attributes
begin_string _beginString
sender_comp_id _senderCompID
target_comp_id _targetCompID
f8String _id
f8String _rid
Static Private Attributes
static RegExp _sid
Friends
std::ostream & operator<< (std::ostream &os, const SessionID &what)
Detailed Description
Quickfix style sessionid.
Definition at line 46 of file session.hpp.
Constructor & Destructor Documentation
FIX8::SessionID::SessionID (const f8String & beginString, const f8String & senderCompID, const f8String & targetCompID) inline
Ctor.
Parameters
beginString Fix begin string
senderCompID Fix senderCompID string
targetCompID Fix targetCompID string
Definition at line 61 of file session.hpp.
References make_id().
       : _beginString(beginString), _senderCompID(senderCompID), _targetCompID(targetCompID) { make_id(); }
FIX8::SessionID::SessionID (const begin_string & beginString, const sender_comp_id & senderCompID, const target_comp_id & targetCompID) inline
Ctor.
Parameters
beginString Fix begin string field
senderCompID Fix senderCompID string field
targetCompID Fix targetCompID string field
Definition at line 68 of file session.hpp.
References make_id().
       : _beginString(beginString), _senderCompID(senderCompID), _targetCompID(targetCompID) { make_id(); }
FIX8::SessionID::SessionID (const f8String & from) inline
Ctor.
Parameters
from SessionID string
Definition at line 73 of file session.hpp.
References from_string().
 { from_string(from); }
FIX8::SessionID::SessionID (const SessionID & from) inline
Ctor.
Parameters
from SessionID field
Definition at line 77 of file session.hpp.
                                     : _beginString(from._beginString), _senderCompID(from._senderCompID),
       _targetCompID(from._targetCompID), _id(from._id) {}
FIX8::SessionID::SessionID () inline
Definition at line 80 of file session.hpp.
 {}
virtual FIX8::SessionID::~SessionID () inline virtual
Dtor.
Definition at line 83 of file session.hpp.
 {}
Member Function Documentation
void SessionID::from_string (const f8String & from)
Create a sessionid string.
Definition at line 87 of file session.cpp.
Referenced by SessionID().
 {
    RegMatch match;
    if (_sid.SearchString(match, from, 4) == 4)
    {
       f8String bstr, scid, tcid;
       _sid.SubExpr(match, from, bstr, 0, 1);
       _beginString.set(bstr);
       _sid.SubExpr(match, from, scid, 0, 2);
       _senderCompID.set(scid);
       _sid.SubExpr(match, from, tcid, 0, 3);
       _targetCompID.set(tcid);
       make_id();
    }
 }
const begin_string& FIX8::SessionID::get_beginString () const inline
Get the beginstring field.
Returns
beginstring
Definition at line 97 of file session.hpp.
References _beginString.
 { return _beginString; }
const f8String& FIX8::SessionID::get_id () const inline
Get the target_comp_id field.
Returns
target_comp_id
Definition at line 109 of file session.hpp.
References _id.
 { return _id; }
const sender_comp_id& FIX8::SessionID::get_senderCompID () const inline
Get the sender_comp_id field.
Returns
sender_comp_id
Definition at line 101 of file session.hpp.
References _senderCompID.
Referenced by FIX8::Configuration::create_persister(), FIX8::Configuration::get_logname(), FIX8::Session::handle_logon(), and FIX8::Session::send_process().
 { return _senderCompID; }
const target_comp_id& FIX8::SessionID::get_targetCompID () const inline
Get the target_comp_id field.
Returns
target_comp_id
Definition at line 105 of file session.hpp.
References _targetCompID.
Referenced by FIX8::Configuration::create_persister(), FIX8::Configuration::get_logname(), and FIX8::Session::send_process().
 { return _targetCompID; }
void SessionID::make_id ()
Create a sessionid and reverse sessionid strings.
Definition at line 73 of file session.cpp.
Referenced by SessionID().
 {
    ostringstream ostr;
    ostr << _beginString << ':' << _senderCompID << "->" << _targetCompID;
    _id = ostr.str();
 }
SessionID SessionID::make_reverse_id () const
Create a reverse SessionID from the current SessionID
Returns
reverse SessionID
Definition at line 81 of file session.cpp.
 {
    return SessionID(_beginString(), _targetCompID(), _senderCompID());
 }
bool FIX8::SessionID::operator!= (const SessionID & that) inline
SessionID inequivalence operator
Parameters
that SessionID to check
Returns
true if SessionIDS are not equal
Definition at line 142 of file session.hpp.
References _senderCompID, and _targetCompID.
    {
       return this != &that ? that._senderCompID() != _senderCompID() && that._targetCompID() != _targetCompID() : false;
    }
bool FIX8::SessionID::operator== (const SessionID & that) inline
SessionID equivalence operator
Parameters
that SessionID to check
Returns
true if SessionIDS are equal
Definition at line 134 of file session.hpp.
References _senderCompID, and _targetCompID.
    {
       return this != &that ? that._senderCompID() == _senderCompID() && that._targetCompID() == _targetCompID() : true;
    }
bool FIX8::SessionID::same_sender_comp_id (const target_comp_id & targetCompID) const inline
Sendercompid equivalence function..
Parameters
targetCompID compid to check
Returns
true if both Targetcompids are the same
Definition at line 114 of file session.hpp.
References _senderCompID.
 { return targetCompID() == _senderCompID(); }
bool FIX8::SessionID::same_side_sender_comp_id (const sender_comp_id & senderCompID) const inline
Targetcompid equivalence function..
Parameters
senderCompID compid to check
Returns
true if both Targetcompids are the same, on the same session side
Definition at line 129 of file session.hpp.
References _senderCompID.
 { return senderCompID() == _senderCompID(); }
bool FIX8::SessionID::same_side_target_comp_id (const target_comp_id & targetCompID) const inline
targetcompid equivalence function..
Parameters
targetCompID compid to check
Returns
true if both Sendercompids are the same, on the same session side
Definition at line 124 of file session.hpp.
References _targetCompID.
 { return targetCompID() == _targetCompID(); }
bool FIX8::SessionID::same_target_comp_id (const sender_comp_id & senderCompID) const inline
Sendercompid equivalence function..
Parameters
senderCompID compid to check
Returns
true if both Sendercompids are the same
Definition at line 119 of file session.hpp.
References _targetCompID.
 { return senderCompID() == _targetCompID(); }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SessionID & what) friend
Inserter friend.
Parameters
os stream to send to
what SessionID
Returns
stream
Definition at line 151 of file session.hpp.
 { return os << what._id; }
Member Data Documentation
begin_string FIX8::SessionID::_beginString private
Definition at line 50 of file session.hpp.
Referenced by get_beginString().
f8String FIX8::SessionID::_id private
Definition at line 54 of file session.hpp.
Referenced by get_id().
f8String FIX8::SessionID::_rid private
Definition at line 54 of file session.hpp.
sender_comp_id FIX8::SessionID::_senderCompID private
Definition at line 51 of file session.hpp.
Referenced by get_senderCompID(), operator!=(), operator==(), same_sender_comp_id(), and same_side_sender_comp_id().
RegExp SessionID::_sid static private
Definition at line 48 of file session.hpp.
target_comp_id FIX8::SessionID::_targetCompID private
Definition at line 52 of file session.hpp.
Referenced by get_targetCompID(), operator!=(), operator==(), same_side_target_comp_id(), and same_target_comp_id().
The documentation for this class was generated from the following files:
session.hpp
session.cpp