fix8: ff::ff_allocator Class Reference
ff::ff_allocator Class Reference
The ff_allocator, based on the idea of the Slab allocator
#include <allocator.hpp>
Public Member Functions
int getslabs (size_t size)
ff_allocator (size_t max_size=0, const int delayedReclaim=0)
Default Constructor.
virtual ~ff_allocator ()
int init (const int _nslabs[N_SLABBUFFER]=0, bool prealloc=true)
int registerAllocator ()
void deregisterAllocator (bool reclaimMemory=true)
int register4free ()
void * malloc (size_t size)
int posix_memalign (void **memptr, size_t alignment, size_t size)
void free (void *ptr)
void * realloc (void *ptr, size_t newsize)
void * growsup (void *ptr, size_t newsize)
Public Attributes
ALLSTATS(void printstats(std::ostream
&out){all_stats::instance() ->
print(out);}) private
SegmentAllocator * alloc
const size_t max_size
const int delayedReclaim
Protected Member Functions
virtual bool free (Buf_ctl *buf)
size_t allocatedsize ()
Private Member Functions
Seg_ctl * getsegctl (Buf_ctl *buf)
SlabCache * getslabs (Buf_ctl *buf)
Friends
class FFAllocator
Detailed Description
The ff_allocator, based on the idea of the Slab allocator
The ff_allocator works over the SlabCache and is tuned to outperform standard allocators' performance in a multi-threaded envirnoment. When it is initialised, it creates a (predefined) number of SlabCaches, each one containing a (predefined) number of buffers of different sizes, from 32 to 8192 bytes. The thread that calls first the allocator object and wants to allocate memory has to register itself to the shared leak queue. Only one thread can perform this operation. The allocator obtains memory from the pre-allocated SlabCache: if there is a slab (i.e. a buffer) big enough to contain an object of the requested size, the pointer to that buffer is passed to the thread that requested the memory. This latter thread has to register as well to the same shared leak queue, so that when it has finished its operations, it can return memory to the allocator thread.
Definition at line 899 of file allocator.hpp.
Constructor & Destructor Documentation
ff::ff_allocator::ff_allocator (size_t max_size = 0, const int delayedReclaim = 0) inline
Default Constructor.
TODO
Definition at line 988 of file allocator.hpp.
virtual ff::ff_allocator::~ff_allocator () inline virtual
Destructor
Definition at line 994 of file allocator.hpp.
References ff::SlabCache::alloc, and ff::SegmentAllocator::~SegmentAllocator().
Member Function Documentation
size_t ff::ff_allocator::allocatedsize () inline protected
TODO
Definition at line 972 of file allocator.hpp.
References ff::SlabCache::allocatedsize().
void ff::ff_allocator::deregisterAllocator (bool reclaimMemory = true) inline
Deregister the allocator (i.e. stop asking for memory) and reclaim allocated memory back to the allocator. Every thread can perform this action.
Parameters
reclaimMemory true if reclaim; false if deregister only
Definition at line 1090 of file allocator.hpp.
References ff::SlabCache::deregisterAllocator().
Referenced by ff::FFAllocator::deleteAllocator(), and ff::FFAkeyDestructorHandler().
virtual bool ff::ff_allocator::free (Buf_ctl * buf) inline protected virtual
Buf_ctl type is a pointer to SlabCache Frees the buffer buf and returns it to its slab segment
Returns
true if some memory has been reclaimed
Reimplemented in ff::ffa_wrapper.
Definition at line 962 of file allocator.hpp.
References ALLSTATS, DBG, and ff::SlabCache::putitem().
Referenced by ff::ffa_wrapper::free().
void ff::ff_allocator::free (void * ptr) inline
Custom ff free.
It frees a buffer (slab) of the SlabCache pointed by ptr. Not only it frees the memory but also takes care of the correct positioning of pointers within the SlabCache structures, in order to maintain the integrity of the cache and avoid fragmentation.
WARNING: this function might fail if memory has been previously allocated using the posix_memalign method with a size grater than MAX_SLABBUFFER_SIZE
Parameters
ptr a pointer to the buffer.
Returns
TODO
Definition at line 1226 of file allocator.hpp.
References ALLSTATS, and ff::Buf_ctl::ptr.
Seg_ctl* ff::ff_allocator::getsegctl (Buf_ctl * buf) inline private
TODO
Definition at line 940 of file allocator.hpp.
int ff::ff_allocator::getslabs (size_t size) inline
Check if there is a slab big enough to contain an object as big as size.
Since there is a limited number of possible slab sizes, and these predefined dimensions are all powers of 2, it is easy to find which slub can contain the object of the given size.
Parameters
size the size of the object that must be contained in a slab.
Returns
0 if the object can be contained in the slab of the smallest size
the index of the suitable slab size in the array of possible sizes, if one exists
-1 if the object is too big to be contained in one of the slabs.
Definition at line 919 of file allocator.hpp.
References ff::POW2_MAX, ff::POW2_MIN, and ff::SlabCache::size.
SlabCache* ff::ff_allocator::getslabs (Buf_ctl * buf) inline private
TODO
Definition at line 947 of file allocator.hpp.
References ff::SlabCache::getsegctl().
void* ff::ff_allocator::growsup (void * ptr, size_t newsize) inline
It is like realloc but it doesn't copy data
ptr TODO newsize TODO
Returns
TODO
Definition at line 1288 of file allocator.hpp.
References ALLSTATS, ff::SlabCache::getsize(), ff::Buf_ctl::ptr, ptr, and ff::SlabCache::putitem().
Referenced by ff::ffa_wrapper::growsup().
int ff::ff_allocator::init (const int _nslabs[N_SLABBUFFER] = 0, bool prealloc = true) inline
Initialise the allocator. This method is called by one thread for each data-path. (e.g. the Emitter in a Farm skeleton).
It creates a number of SlabCaches objects, a number specified by the N_SLABBUFFER constant. The size of each created segment goes from 32 (the first one created) to 8192 (the last).
Note that, unless otherwise specified, the number of buffers in a slab segment decreases as the size of the slab increases.
Parameters
_nslabs an array specifying the allowed numbers of buffers in a SlabCache. By default it is initialised to 0s
prealloc flag used when creating new SlabCaches. Default is true
Returns
0 if initialisation succedes; a negative value otherwise
Allocate space for a SegmenAllocator object and initialise it.
Allocate space for 'N_SLABBUFFER' caches and create SlabCache objects. Buffers size within a cache size grows from 32 to 8192. if not otherwise specified, the number of slab buffers in a segment decreases as the size of the slab increases.
Definition at line 1025 of file allocator.hpp.
References ff::SlabCache::alloc, ff::buffersize, ff::SlabCache::delayedReclaim, ff::error(), ff::SlabCache::init(), ff::N_SLABBUFFER, ff::SlabCache::nslabs, ff::nslabs_default, ff::svector< T >::push_back(), and ff::SlabCache::SlabCache().
Referenced by ff::FFAllocator::newAllocator().
void* ff::ff_allocator::malloc (size_t size) inline
Custom ff malloc.
Requests to allocate size bytes of dynamic memory. If the requested size is bigger than the maximum size for a buffer OR there are no more free buffers in the existing SlabCaches, a new chunk of dynamic memory is allocated. The size of the allocated chunk is equal to the size requested.
Otherwise it returns a pointer to an available buffer in the slabs cache that fits the requested size.
Parameters
size the size of memory requested
Returns
TODO
use standard allocator if the size is too big or we don't want to use the ff_allocator for that size
Definition at line 1135 of file allocator.hpp.
References ALLSTATS, DBG, ff::SlabCache::getnslabs(), ff::MAX_SLABBUFFER_SIZE, and ptr.
Referenced by ff::ffa_wrapper::malloc().
int ff::ff_allocator::posix_memalign (void ** memptr, size_t alignment, size_t size) inline
Custom ff posix_memalign.
Like the custom malloc, but it returns a pointer to an aligned chunk of memory.
, **memptr pointer to a chunk of memory where the aligned memory will be returned. alignment the returned memory will be a multiple of alignment, which must be a power of two and a multiple of sizeof(void *).
Parameters
size the size of memory requested.
Returns
TODO
Definition at line 1170 of file allocator.hpp.
References ALLSTATS, DBG, ff::SlabCache::getnslabs(), ff::isPowerOfTwoMultiple(), ff::MAX_SLABBUFFER_SIZE, ff::Buf_ctl::ptr, and ptr.
Referenced by ff::ffa_wrapper::posix_memalign().
void* ff::ff_allocator::realloc (void * ptr, size_t newsize) inline
Custom ff realloc.
It changes the size of the memory block pointed to by ptr to newsize bytes.
Parameters
ptr pointer to the buffer.
newsize the new size.
Returns
TODO
Definition at line 1253 of file allocator.hpp.
References ALLSTATS, ff::SlabCache::getsize(), ff::Buf_ctl::ptr, ptr, and ff::SlabCache::putitem().
Referenced by ff::ffa_wrapper::realloc().
int ff::ff_allocator::register4free () inline
Threads different from the allocator (i.e. those threads that do not allocate memory) have to register themselves to the shared buffer by calling this method. In this way they are provided with a chunk of memory. Since they are registered, once their taks terminates they free the memory assigned and that memory returns back to the allocator thread's buffer, so that it can be reused.
Returns
TODO
Definition at line 1109 of file allocator.hpp.
int ff::ff_allocator::registerAllocator () inline
The thread that allocates memory have to call this method in order to register itself to the shared buffer. With this method, a thread is allowed to allocate memory. Only one thread can allocate memory.
Returns
0 if operation succedes, -1 otherwise
Definition at line 1074 of file allocator.hpp.
Referenced by ff::FFAllocator::newAllocator().
Friends And Related Function Documentation
friend class FFAllocator friend
Definition at line 900 of file allocator.hpp.
Member Data Documentation
ALLSTATS (void printstats(std::ostream & out) { all_stats::instance()->print(out); }) private SegmentAllocator* ff::ff_allocator::alloc
Definition at line 1311 of file allocator.hpp.
const int ff::ff_allocator::delayedReclaim
Definition at line 1319 of file allocator.hpp.
const size_t ff::ff_allocator::max_size
Definition at line 1318 of file allocator.hpp.
The documentation for this class was generated from the following file:
allocator.hpp