fix8: ff::SWSR_Ptr_Buffer Class Reference
ff::SWSR_Ptr_Buffer Class Reference
Single-Writer/Single-Reader circular buffer.
#include <buffer.hpp>
Public Member Functions
SWSR_Ptr_Buffer (unsigned long n, const bool=true)
~SWSR_Ptr_Buffer ()
bool init (const bool startatlineend=false)
bool empty ()
bool available ()
unsigned long buffersize () const
bool push (void *const data)
bool multipush (void *const data[], int len)
bool pop (void **data)
bool inc ()
void * top () const
void reset (const bool startatlineend=false)
unsigned long length () const
Private Types
enum { MULTIPUSH_BUFFER_SIZE =16 }
Private Attributes
volatile unsigned long pread
long padding1 [longxCacheLine-1]
volatile unsigned long pwrite
long padding2 [longxCacheLine-1]
const unsigned long size
void ** buf
Detailed Description
Single-Writer/Single-Reader circular buffer.
This class describes the SWSR circular buffer, used in FastFlow to implement a lock-free (wait-free) bounded FIFO queue. No lock is needed around pop and push methods.
A single NULL value is used to indicate buffer full and buffer empty conditions.
This class is defined in buffer.hpp
Definition at line 86 of file buffer.hpp.
Member Enumeration Documentation
anonymous enum private
experimentally we found that a good value is between 2 and 6 cache lines (16 to 48 entries respectively)
Enumerator
MULTIPUSH_BUFFER_SIZE
Definition at line 91 of file buffer.hpp.
Constructor & Destructor Documentation
ff::SWSR_Ptr_Buffer::SWSR_Ptr_Buffer (unsigned long n, const bool = true) inline
Constructor.
Parameters
n the size of the buffer
Definition at line 126 of file buffer.hpp.
ff::SWSR_Ptr_Buffer::~SWSR_Ptr_Buffer () inline
Default destructor
Definition at line 133 of file buffer.hpp.
References buf, and freeAlignedMemory().
Member Function Documentation
bool ff::SWSR_Ptr_Buffer::available () inline
It returns true if there is at least one room in the buffer.
Definition at line 173 of file buffer.hpp.
References buf, and pwrite.
Referenced by push().
unsigned long ff::SWSR_Ptr_Buffer::buffersize () const inline
It returns the size of the buffer.
Returns
The size of the buffer.
Definition at line 186 of file buffer.hpp.
References size.
Referenced by ff::dynqueue::~dynqueue().
bool ff::SWSR_Ptr_Buffer::empty () inline
It returns true if the buffer is empty.
Definition at line 162 of file buffer.hpp.
References buf, and pread.
Referenced by pop().
bool ff::SWSR_Ptr_Buffer::inc () inline
It is like pop but doesn't copy any data.
Returns
true is alway returned.
Definition at line 303 of file buffer.hpp.
References buf, pread, and size.
Referenced by pop().
bool ff::SWSR_Ptr_Buffer::init (const bool startatlineend = false) inline
It initialise the buffer. Allocate space (size) of possibly aligned memory and reset the pointers (read pointer and write pointer) by placing them at the beginning of the buffer.
Returns
TODO
Definition at line 145 of file buffer.hpp.
References buf, getAlignedMemory(), ff::longxCacheLine, MULTIPUSH_BUFFER_SIZE, reset(), and size.
Referenced by ff::dynqueue::dynqueue().
unsigned long ff::SWSR_Ptr_Buffer::length () const inline
It returns the length of the buffer (i.e. the actual number of elements it contains)
Definition at line 344 of file buffer.hpp.
References pread, pwrite, and size.
bool ff::SWSR_Ptr_Buffer::multipush (void *const data[], int len) inline
The multipush method, which pushes a batch of elements (array) in the queue. NOTE: len should be a multiple of longxCacheLine/sizeof(void*)
Definition at line 225 of file buffer.hpp.
References buf, pwrite, and size.
bool ff::SWSR_Ptr_Buffer::pop (void ** data) inline
Pop method: get the next value from the FIFO buffer.
Parameters
data Pointer to the location where to store the data popped from the buffer.
Definition at line 291 of file buffer.hpp.
References buf, empty(), inc(), and pread.
Referenced by ff::dynqueue::allocnode(), ff::dynqueue::mp_allocnode(), and ff::dynqueue::~dynqueue().
bool ff::SWSR_Ptr_Buffer::push (void *const data) inline
Push method: push the input value into the queue. A Write Memory Barrier (WMB) ensures that all previous memory writes are visible to the other processors before any later write is executed. This is an "expensive" memory fence operation needed in all the architectures with a weak-ordering memory model, where stores can be executed out-of-order (e.g. PowerPc). This is a no-op on Intel x86/x86-64 CPUs.
Parameters
data Element to be pushed in the buffer
Returns
TODO
Write Memory Barrier: ensure all previous memory write are visible to the other processors before any later writes are executed. This is an "expensive" memory fence operation needed in all the architectures with a weak-ordering memory model where stores can be executed out-or-order (e.g. Powerpc). This is a no-op on Intel x86/x86-64 CPUs.
Definition at line 200 of file buffer.hpp.
References available(), buf, data, pwrite, and size.
Referenced by ff::dynqueue::dynqueue(), ff::dynqueue::mp_pop(), and ff::dynqueue::pop().
void ff::SWSR_Ptr_Buffer::reset (const bool startatlineend = false) inline
Reset the buffer and move read and write pointers to the beginning of the buffer (i.e. position 0). Also, the entire buffer is cleaned and set to 0
This is a good starting point if the multipush method will be used in order to reduce cache trashing.
Definition at line 323 of file buffer.hpp.
References buf, ff::longxCacheLine, pread, pwrite, and size.
Referenced by init().
void* ff::SWSR_Ptr_Buffer::top () const inline
It returns the "head" of the buffer, i.e. the element pointed by the read pointer (it is a FIFO queue, so push on the tail and pop from the head).
Returns
The head of the buffer.
Definition at line 316 of file buffer.hpp.
References buf, and pread.
Member Data Documentation
void** ff::SWSR_Ptr_Buffer::buf private
Definition at line 108 of file buffer.hpp.
Referenced by available(), empty(), inc(), init(), multipush(), pop(), push(), reset(), top(), and ~SWSR_Ptr_Buffer().
long ff::SWSR_Ptr_Buffer::padding1[longxCacheLine-1] private
Definition at line 103 of file buffer.hpp.
long ff::SWSR_Ptr_Buffer::padding2[longxCacheLine-1] private
Definition at line 105 of file buffer.hpp.
volatile unsigned long ff::SWSR_Ptr_Buffer::pread private
Definition at line 102 of file buffer.hpp.
Referenced by empty(), inc(), length(), pop(), reset(), and top().
volatile unsigned long ff::SWSR_Ptr_Buffer::pwrite private
Definition at line 104 of file buffer.hpp.
Referenced by available(), length(), multipush(), push(), and reset().
const unsigned long ff::SWSR_Ptr_Buffer::size private
Definition at line 107 of file buffer.hpp.
Referenced by buffersize(), inc(), init(), length(), multipush(), push(), and reset().
The documentation for this class was generated from the following file:
buffer.hpp