fix8: ff::SegmentAllocator Class Reference
ff::SegmentAllocator Class Reference
Uses standard libc allocator to allocate chunks of (possibly aligned) memory. It also keeps track of the amount of allocated memory.
#include <allocator.hpp>
Public Member Functions
SegmentAllocator ()
~SegmentAllocator ()
void * newsegment (size_t segment_size)
void freesegment (void *ptr, size_t segment_size)
size_t getallocated () const
Private Attributes
size_t memory_allocated
Detailed Description
Uses standard libc allocator to allocate chunks of (possibly aligned) memory. It also keeps track of the amount of allocated memory.
This class is defined in allocator.hpp
Definition at line 215 of file allocator.hpp.
Constructor & Destructor Documentation
ff::SegmentAllocator::SegmentAllocator () inline
Definition at line 217 of file allocator.hpp.
ff::SegmentAllocator::~SegmentAllocator () inline
Definition at line 218 of file allocator.hpp.
Referenced by ff::ff_allocator::~ff_allocator().
Member Function Documentation
void ff::SegmentAllocator::freesegment (void * ptr, size_t segment_size) inline
Free segment_size amount of memory from the memory chunk pointed by ptr.
First, it checks that the total allocated memory is at least as big as segment_size. Then, it frees memory and updates the counter of the total allocated memory.
Parameters
ptr pointer to the memory chunk to be freed
segment_size quantity of memory to free from the chunk requested.
Definition at line 264 of file allocator.hpp.
References ALLSTATS, DBG, freeAlignedMemory(), and memory_allocated.
Referenced by ff::SlabCache::freeslab().
size_t ff::SegmentAllocator::getallocated () const inline
Returns
Returns the amount of memry allocated
Definition at line 277 of file allocator.hpp.
References memory_allocated.
Referenced by ff::SlabCache::allocatedsize().
void* ff::SegmentAllocator::newsegment (size_t segment_size) inline
Allocates a new segment of (possibly aligned) memory.
This method uses standard malloc to allocate memory (or posix_memalign when possible). malloc should guarantee a sufficiently well aligned memory for any purpose, while posix_memalign is used to effectively allocate memory aligned in a defined way (i.e. the address of the allocated memory will be a multiple of a specific value).
Parameters
segment_size the quantity of memory to be allocated.
Returns
a pointer to the chunk of memory allocated.
Definition at line 232 of file allocator.hpp.
References ALLSTATS, getAlignedMemory(), memory_allocated, and ptr.
Referenced by ff::SlabCache::newslab().
Member Data Documentation
size_t ff::SegmentAllocator::memory_allocated private
Definition at line 280 of file allocator.hpp.
Referenced by freesegment(), getallocated(), and newsegment().
The documentation for this class was generated from the following file:
allocator.hpp