fix8: FIX8::Field< f8String, field > Class Template Reference
FIX8::Field< f8String, field > Class Template Reference
Partial specialisation for f8String field type.
#include <field.hpp>
Public Member Functions
FieldTrait::FieldType get_underlying_type () const
The FieldType.
Field ()
Ctor.
Field (const Field &from)
Copy Ctor.
Field (const char *from, const RealmBase *rlm=nullptr)
Field (const f8String &from, const RealmBase *rlm=nullptr)
virtual ~Field ()
Dtor.
Field & operator= (const Field &that)
Assignment operator.
bool operator== (const BaseField &that) const
Equivalence operator.
virtual bool operator< (const BaseField &that) const
Less than operator.
virtual bool operator> (const BaseField &that) const
Greater than operator.
bool is_valid () const
int get_rlm_idx () const
const f8String & get () const
const f8String & operator() () const
const f8String & set (const f8String &from)
const f8String & set_from_raw (const f8String &from)
Field * copy ()
std::ostream & print (std::ostream &os) const
size_t print (char *to) const
Public Member Functions inherited from FIX8::BaseField
BaseField (unsigned short fnum, const RealmBase *rlm=nullptr)
virtual ~BaseField ()
Dtor.
unsigned short get_tag () const
template<typename T >
T & from ()
template<typename T >
const T * as () const
size_t encode (std::ostream &os) const
size_t encode (char *to) const
bool same_base (const BaseField &that) const
BaseField Equivalence test.
bool operator!= (const BaseField &that) const
Inequivalence operator.
bool operator<= (const BaseField &that) const
Less or equal to operator.
bool operator>= (const BaseField &that) const
Greater or equal to operator.
const RealmBase * get_realm () const
Static Public Member Functions
static unsigned short get_field_id ()
Get the FIX fieldID (tag number).
Protected Attributes
f8String _value
Protected Attributes inherited from FIX8::BaseField
const RealmBase * _rlm
Static Protected Attributes
static const FieldTrait::FieldType _ftype = FieldTrait::ft_data
Detailed Description
template<unsigned short field>
class FIX8::Field< f8String, field >
Partial specialisation for f8String field type.
Template Parameters
field field number (fix tag)
Definition at line 490 of file field.hpp.
Constructor & Destructor Documentation
template<unsigned short field> FIX8::Field< f8String, field >::Field () inline
Ctor.
Definition at line 504 of file field.hpp.
 : BaseField(field) {}
template<unsigned short field> FIX8::Field< f8String, field >::Field (const Field< f8String, field > & from) inline
Copy Ctor.
Definition at line 508 of file field.hpp.
 : BaseField(field), _value(from._value) {}
template<unsigned short field> FIX8::Field< f8String, field >::Field (const char * from, const RealmBase * rlm = nullptr) inline
Construct from char * ctor.
Parameters
from char * to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 513 of file field.hpp.
 : BaseField(field, rlm), _value(from) {}
template<unsigned short field> FIX8::Field< f8String, field >::Field (const f8String & from, const RealmBase * rlm = nullptr) inline
Construct from string ctor.
Parameters
from string to construct field from
rlm pointer to the realmbase for this field (if available)
Definition at line 518 of file field.hpp.
 : BaseField(field, rlm), _value(from) {}
template<unsigned short field> virtual FIX8::Field< f8String, field >::~Field () inline virtual
Dtor.
Definition at line 521 of file field.hpp.
 {}
Member Function Documentation
template<unsigned short field> Field* FIX8::Field< f8String, field >::copy () inline virtual
Copy (clone) this field.
Returns
copy of field
Implements FIX8::BaseField.
Definition at line 579 of file field.hpp.
References FIX8::Field< T, field >::Field().
 { return new Field(*this); }
template<unsigned short field> const f8String& FIX8::Field< f8String, field >::get () const inline
Get field value.
Returns
value (f8String)
Definition at line 561 of file field.hpp.
 { return _value; }
template<unsigned short field> static unsigned short FIX8::Field< f8String, field >::get_field_id () inline static
Get the FIX fieldID (tag number).
Definition at line 498 of file field.hpp.
 { return field; }
template<unsigned short field> int FIX8::Field< f8String, field >::get_rlm_idx () const inline virtual
Get the realm index of this value in the domain set.
Returns
the index in the domain set of this value
Reimplemented from FIX8::BaseField.
Definition at line 557 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::get_rlm_idx().
 { return _rlm ? _rlm->get_rlm_idx(_value) : -1; }
template<unsigned short field> FieldTrait::FieldType FIX8::Field< f8String, field >::get_underlying_type () const inline virtual
The FieldType.
Implements FIX8::BaseField.
Definition at line 501 of file field.hpp.
 { return _ftype; }
template<unsigned short field> bool FIX8::Field< f8String, field >::is_valid () const inline
Check if this value is a member/in range of the domain set.
Returns
true if in the set or no domain available
Definition at line 553 of file field.hpp.
References FIX8::BaseField::_rlm, and FIX8::RealmBase::is_valid().
 { return _rlm ? _rlm->is_valid(_value) : true; }
template<unsigned short field> const f8String& FIX8::Field< f8String, field >::operator() () const inline
Get field value.
Returns
value (f8String)
Definition at line 565 of file field.hpp.
 { return _value; }
template<unsigned short field> virtual bool FIX8::Field< f8String, field >::operator< (const BaseField< f8String, field > & that) const inline virtual
Less than operator.
Parameters
that field to compare
Returns
true if less than
Implements FIX8::BaseField.
Definition at line 542 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value < static_cast<const Field<f8String, field>&>(that)._value; }
template<unsigned short field> Field& FIX8::Field< f8String, field >::operator= (const Field< f8String, field > & that) inline
Assignment operator.
Parameters
that field to assign from
Returns
field
Definition at line 526 of file field.hpp.
    {
       if (this != &that)
          _value = that._value;
       return *this;
    }
template<unsigned short field> bool FIX8::Field< f8String, field >::operator== (const BaseField< f8String, field > & that) const inline virtual
Equivalence operator.
Parameters
that field to compare
Returns
true if same
Implements FIX8::BaseField.
Definition at line 536 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && static_cast<const Field<f8String, field>&>(that)._value == _value; }
template<unsigned short field> virtual bool FIX8::Field< f8String, field >::operator> (const BaseField< f8String, field > & that) const inline virtual
Greater than operator.
Parameters
that field to compare
Returns
true if greater than
Implements FIX8::BaseField.
Definition at line 548 of file field.hpp.
References FIX8::BaseField::same_base().
       { return same_base(that) && _value > static_cast<const Field<f8String, field>&>(that)._value; }
template<unsigned short field> std::ostream& FIX8::Field< f8String, field >::print (std::ostream & os) const inline virtual
Print this field to the supplied stream. Used to format for FIX output.
Parameters
os stream to insert to
Returns
stream
Implements FIX8::BaseField.
Definition at line 584 of file field.hpp.
 { return os << _value; }
template<unsigned short field> size_t FIX8::Field< f8String, field >::print (char * to) const inline virtual
Print this field to the supplied buffer.
Parameters
to buffer to print to
Returns
number bytes encoded
Implements FIX8::BaseField.
Definition at line 589 of file field.hpp.
 { return _value.copy(to, _value.size()); }
template<unsigned short field> const f8String& FIX8::Field< f8String, field >::set (const f8String & from) inline
Get field value.
Parameters
from value to set
Returns
original value (f8String)
Definition at line 570 of file field.hpp.
References FIX8::BaseField::from().
 { return _value = from; }
template<unsigned short field> const f8String& FIX8::Field< f8String, field >::set_from_raw (const f8String & from) inline
Set the value from a string.
Parameters
from value to set
Returns
original value (f8String)
Definition at line 575 of file field.hpp.
References FIX8::BaseField::from().
 { return _value = from; }
Member Data Documentation
template<unsigned short field> const FieldTrait::FieldType FIX8::Field< f8String, field >::_ftype = FieldTrait::ft_data static protected
Definition at line 494 of file field.hpp.
template<unsigned short field> f8String FIX8::Field< f8String, field >::_value protected
Definition at line 493 of file field.hpp.
The documentation for this class was generated from the following file:
field.hpp