fix8: FIX8::Singleton< T > Class Template Reference
FIX8::Singleton< T > Class Template Reference
A lockfree Singleton.
#include <f8utils.hpp>
Public Member Functions
Singleton ()
Ctor.
virtual ~Singleton ()
Dtor.
T * operator-> () const
Static Public Member Functions
static T * instance ()
static T * reset (T *what)
static T * release ()
Private Member Functions
Singleton (const Singleton &)
Singleton & operator= (const Singleton &)
template<>
tbb::atomic< SingleLogger
< glob_log0 > * > _instance
template<>
tbb::mutex _mutex
Static Private Attributes
static tbb::atomic< T * > _instance
static tbb::mutex _mutex
Detailed Description
template<typename T>
class FIX8::Singleton< T >
A lockfree Singleton.
Template Parameters
T the instance object type
Definition at line 933 of file f8utils.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::Singleton< T >::Singleton (const Singleton< T > &) private
template<typename T> FIX8::Singleton< T >::Singleton () inline
Ctor.
Definition at line 943 of file f8utils.hpp.
template<typename T> virtual FIX8::Singleton< T >::~Singleton () inline virtual
Dtor.
Definition at line 946 of file f8utils.hpp.
Member Function Documentation
template<> tbb::atomic< SingleLogger< glob_log0 > * > FIX8::Singleton< SingleLogger< glob_log0 > >::_instance () private
Definition at line 65 of file logger.cpp.
Referenced by FIX8::Singleton< SingleLogger< fn > >::instance(), FIX8::Singleton< SingleLogger< fn > >::release(), FIX8::Singleton< SingleLogger< fn > >::reset(), and FIX8::Singleton< SingleLogger< fn > >::~Singleton().
template<> tbb::mutex FIX8::Singleton< SingleLogger< glob_log0 > >::_mutex () private
Definition at line 67 of file logger.cpp.
Referenced by FIX8::Singleton< SingleLogger< fn > >::instance().
template<typename T> static T* FIX8::Singleton< T >::instance () inline static
Get the instance of the underlying object. If not created, create.
Returns
the instance
Definition at line 950 of file f8utils.hpp.
Referenced by FIX8::Singleton< SingleLogger< fn > >::operator->().
template<typename T> T* FIX8::Singleton< T >::operator-> () const inline
Get the instance of the underlying object. If not created, create.
Returns
the instance
Definition at line 964 of file f8utils.hpp.
template<typename T> Singleton& FIX8::Singleton< T >::operator= (const Singleton< T > &) private
template<typename T> static T* FIX8::Singleton< T >::release () inline static
Get the instance of the underlying object removing it from the singleton.
Returns
the instance
Definition at line 973 of file f8utils.hpp.
template<typename T> static T* FIX8::Singleton< T >::reset (T * what) inline static
Replace the instance object with a new instance.
Parameters
what the new instance
Returns
the original instance
Definition at line 969 of file f8utils.hpp.
Member Data Documentation
template<typename T> tbb::atomic<T*> FIX8::Singleton< T >::_instance static private
Definition at line 935 of file f8utils.hpp.
template<typename T> tbb::mutex FIX8::Singleton< T >::_mutex static private
Definition at line 936 of file f8utils.hpp.
The documentation for this class was generated from the following file:
f8utils.hpp