Fix8: FIX8::_threadbase Class Reference
FIX8::_threadbase Class Reference
Modern POSIX pthread wrapper ABC.
#include <thread.hpp>
Public Member Functions
_threadbase (const bool detach, const size_t stacksize) throw (ThreadException)
virtual ~_threadbase ()
Dtor.
virtual int Start ()=0
int Join ()
void Exit (int exitvalue) const
int GetExitVal () const
void Kill (int signum) const
pthread_t GetThreadID () const
bool operator== (const _threadbase &that) const
bool operator!= (const _threadbase &that) const
Static Public Member Functions
static bool Kill (_threadbase &ctxt, const int signal=SIGTERM)
static pthread_t GetID ()
static bool SetSignalMask (const int how, const sigset_t *newmask, sigset_t *oldmask)
static bool SignalWait (const sigset_t *set, int *sig)
Protected Member Functions
template<typename T >
int _Start (void *sub)
Private Member Functions
_threadbase & operator= (const _threadbase &)
Static Private Member Functions
template<typename T >
static void * _Run (void *what)
Private Attributes
pthread_attr_t _attr
pthread_t _tid
int _exitval
Detailed Description
Modern POSIX pthread wrapper ABC.
Definition at line 84 of file thread.hpp.
Constructor & Destructor Documentation
FIX8::_threadbase::_threadbase (const bool detach, const size_t stacksize) throw (ThreadException) [inline]
Ctor.
Parameters:
detach detach thread if true
stacksize default thread stacksize
Definition at line 106 of file thread.hpp.
References _attr.
virtual FIX8::_threadbase::~_threadbase () [inline, virtual]
Dtor.
Definition at line 117 of file thread.hpp.
References _attr.
Member Function Documentation
template<typename T > static void* FIX8::_threadbase::_Run (void * what) [inline, static, private]
Definition at line 91 of file thread.hpp.
template<typename T > int FIX8::_threadbase::_Start (void * sub) [inline, protected]
Definition at line 99 of file thread.hpp.
References _attr, and _tid.
void FIX8::_threadbase::Exit (int exitvalue) const [inline]
Cause the thread to exit.
Parameters:
exitvalue value to return to calling process
Definition at line 130 of file thread.hpp.
int FIX8::_threadbase::GetExitVal () const [inline]
Recover the thread's exit value.
Returns:
exit value from to calling process
Definition at line 134 of file thread.hpp.
References _exitval.
static pthread_t FIX8::_threadbase::GetID () [inline, static]
Get the thread's thread ID. Static version.
Returns:
the thread id
Definition at line 153 of file thread.hpp.
pthread_t FIX8::_threadbase::GetThreadID () const [inline]
Get the thread's thread ID.
Returns:
the thread id
Definition at line 149 of file thread.hpp.
References _tid.
int FIX8::_threadbase::Join () [inline]
Join the thread.
Returns:
result of join
Definition at line 125 of file thread.hpp.
References _exitval, and _tid.
Referenced by FIX8::AsyncSocket< f8String >::join(), FIX8::Timer< Session >::join(), FIX8::Logger::stop(), and FIX8::BDBPersister::stop().
void FIX8::_threadbase::Kill (int signum) const [inline]
Kill the thread.
Parameters:
signum signal number to send
Definition at line 138 of file thread.hpp.
References _tid.
Referenced by FIX8::AsyncSocket< f8String >::quit(), and FIX8::FIXReader::quit().
static bool FIX8::_threadbase::Kill (_threadbase & ctxt, const int signal = SIGTERM) [inline, static]
Kill the thread. Static version.
Parameters:
ctxt thread context to kill
signal signal number to send
Returns:
true on success
Definition at line 144 of file thread.hpp.
References _tid.
bool FIX8::_threadbase::operator!= (const _threadbase & that) const [inline]
Thread inequivalence operator.
Parameters:
that the other thread id
Returns:
true if the threads are unequal
Definition at line 163 of file thread.hpp.
References _tid.
_threadbase& FIX8::_threadbase::operator= (const _threadbase &) [private]
bool FIX8::_threadbase::operator== (const _threadbase & that) const [inline]
Thread equivalence operator.
Parameters:
that the other thread id
Returns:
true if the threads are equal
Definition at line 158 of file thread.hpp.
References _tid.
static bool FIX8::_threadbase::SetSignalMask (const int how, const sigset_t * newmask, sigset_t * oldmask) [inline, static]
Set the thread signal mask.
Parameters:
how block, unblock or mask
newmask new mask
oldmask old mask
Returns:
true on success
Definition at line 170 of file thread.hpp.
static bool FIX8::_threadbase::SignalWait (const sigset_t * set, int * sig) [inline, static]
Wait for a specified signal.
Parameters:
set signal set
sig new mask
Returns:
true on success
Definition at line 177 of file thread.hpp.
virtual int FIX8::_threadbase::Start () [pure virtual]
Start thread.
Returns:
function result
Implemented in FIX8::Thread<>, FIX8::Thread< T >, FIX8::Thread< Timer >, FIX8::Thread< BDBPersister >, FIX8::Thread< AsyncSocket >, FIX8::Thread< Logger >, FIX8::Thread< ReliableClientSession< T > >, and FIX8::Thread< FIXReader >.
Member Data Documentation
pthread_attr_t FIX8::_threadbase::_attr [private]
Definition at line 86 of file thread.hpp.
Referenced by _Start(), _threadbase(), and ~_threadbase().
int FIX8::_threadbase::_exitval [private]
Definition at line 88 of file thread.hpp.
Referenced by GetExitVal(), and Join().
pthread_t FIX8::_threadbase::_tid [private]
Definition at line 87 of file thread.hpp.
Referenced by _Start(), GetThreadID(), Join(), Kill(), operator!=(), and operator==().
The documentation for this class was generated from the following file:
thread.hpp