fix8: FIX8::RegExp Class Reference
FIX8::RegExp Class Reference
POSIX regex wrapper class.
#include <f8utils.hpp>
Public Member Functions
RegExp (const char *pattern, const int flags=0)
virtual ~RegExp ()
Dtor. Destroys internal compiled expression.
int SearchString (RegMatch &match, const std::string &source, const int subExpr, const int offset=0) const
const std::string & GetPattern () const
const std::string & ErrString () const
bool operator! () const
operator void * ()
Static Public Member Functions
static std::string & SubExpr (RegMatch &match, const std::string &source, std::string &target, const int offset=0, const int num=0)
static std::string & Erase (RegMatch &match, std::string &source, const int num=0)
static std::string & Replace (RegMatch &match, std::string &source, const std::string &with, const int num=0)
static std::string & Replace (RegMatch &match, std::string &source, const char with, const int num=0)
Private Types
enum { MaxErrLen_ = 256 }
Maximum length of an error message.
Private Attributes
const std::string pattern_
regex_t reg_
std::string errString
int errCode_
Detailed Description
POSIX regex wrapper class.
Definition at line 370 of file f8utils.hpp.
Member Enumeration Documentation
anonymous enum private
Maximum length of an error message.
Enumerator
MaxErrLen_
Definition at line 375 of file f8utils.hpp.
 { MaxErrLen_ = 256 };
Constructor & Destructor Documentation
FIX8::RegExp::RegExp (const char * pattern, const int flags = 0) inline
Ctor.
Parameters
pattern regular expression to compile. errCode and errString set on error.
flags POSIX regcomp flags
Definition at line 388 of file f8utils.hpp.
References MaxErrLen_.
       : pattern_(pattern)
    {
       if ((errCode_ = regcomp(&reg_, pattern_.c_str(), REG_EXTENDED|flags)) != 0)
       {
          char rbuf[MaxErrLen_];
          regerror(errCode_, &reg_, rbuf, MaxErrLen_);
          errString = rbuf;
       }
    }
virtual FIX8::RegExp::~RegExp () inline virtual
Dtor. Destroys internal compiled expression.
Definition at line 415 of file f8utils.hpp.
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       if (errCode_ == 0)
          regfree(&reg_);
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       delete _regexp;
 #endif
    }
Member Function Documentation
static std::string& FIX8::RegExp::Erase (RegMatch & match, std::string & source, const int num = 0) inline static
Erase a sub-expression from a string.
Parameters
match reference to a RegMatch object
source source string
num desired sub-expression
Returns
the source string
Definition at line 471 of file f8utils.hpp.
References FIX8::RegMatch::SubCnt(), FIX8::RegMatch::subCnt_, FIX8::RegMatch::subexprs_, FIX8::RegMatch::SubPos(), and FIX8::RegMatch::SubSize().
Referenced by main().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       if (num < match.subCnt_)
          source.erase(match.subexprs_[num].rm_so, match.subexprs_[num].rm_eo - match.subexprs_[num].rm_so);
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       if (num < static_cast<int>(match.SubCnt()))
          source.erase(match.SubPos(num), match.SubSize(num));
 #endif
       return source;
    }
const std::string& FIX8::RegExp::ErrString () const inline
Get the error string (set when Ctor fails to compile).
Returns
the error string
Definition at line 525 of file f8utils.hpp.
References errString.
 { return errString; }
const std::string& FIX8::RegExp::GetPattern () const inline
Get the regular expression pattern.
Returns
the pattern string
Definition at line 521 of file f8utils.hpp.
References pattern_.
 { return pattern_; }
FIX8::RegExp::operator void * () inline
Check if a pattern compiled ok.
Returns
true onsuccess
Definition at line 533 of file f8utils.hpp.
 { return errCode_ ? 0 : this; }
bool FIX8::RegExp::operator! () const inline
Check if a pattern did not compile ok.
Returns
true on failure
Definition at line 529 of file f8utils.hpp.
References errCode_.
 { return errCode_; }
static std::string& FIX8::RegExp::Replace (RegMatch & match, std::string & source, const std::string & with, const int num = 0) inline static
Replace a sub-expression with a string.
Parameters
match reference to a RegMatch object
source source string
with replacement string
num desired sub-expression
Returns
the source string
Definition at line 489 of file f8utils.hpp.
References FIX8::RegMatch::SubCnt(), FIX8::RegMatch::subCnt_, FIX8::RegMatch::subexprs_, FIX8::RegMatch::SubPos(), and FIX8::RegMatch::SubSize().
Referenced by XmlElement::InplaceXlate().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       if (num < match.subCnt_)
          source.replace(match.subexprs_[num].rm_so, match.subexprs_[num].rm_eo - match.subexprs_[num].rm_so, with);
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       if (num < static_cast<int>(match.SubCnt()))
          source.replace(match.SubPos(num), match.SubSize(num), with);
 #endif
       return source;
    }
static std::string& FIX8::RegExp::Replace (RegMatch & match, std::string & source, const char with, const int num = 0) inline static
Replace a sub-expression with a character.
Parameters
match reference to a RegMatch object
source source string
with replacement character
num desired sub-expression
Returns
the source string
Definition at line 507 of file f8utils.hpp.
References FIX8::RegMatch::SubCnt(), FIX8::RegMatch::subCnt_, FIX8::RegMatch::subexprs_, FIX8::RegMatch::SubPos(), and FIX8::RegMatch::SubSize().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       if (num < match.subCnt_)
          source.replace(match.subexprs_[num].rm_so, match.subexprs_[num].rm_eo - match.subexprs_[num].rm_so, 1, with);
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       if (num < static_cast<int>(match.SubCnt()))
          source.replace(match.SubPos(num), match.SubSize(num), 1, with);
 #endif
       return source;
    }
int FIX8::RegExp::SearchString (RegMatch & match, const std::string & source, const int subExpr, const int offset = 0) const inline
Search a string.
Parameters
match reference to a RegMatch object
source string to search
subExpr number of sub-expression
offset to start searching
Returns
number of sub-expressions found (0=none)
Definition at line 431 of file f8utils.hpp.
References FIX8::RegMatch::subCnt_, FIX8::RegMatch::subexprs_, and FIX8::RegMatch::SubLimit_.
Referenced by XmlElement::InplaceXlate(), and main().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       match.subCnt_ = 0;
       if (regexec(&reg_, source.c_str() + offset, subExpr <= RegMatch::SubLimit_ ? subExpr : RegMatch::SubLimit_, match.subexprs_, 0) == 0)
          while (match.subCnt_ < subExpr && match.subexprs_[match.subCnt_].rm_so != -1)
             ++match.subCnt_;
       return match.subCnt_;
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       match._matchVec.clear();
       return _regexp ? _regexp->match(source, offset, match._matchVec) : 0;
 #endif
    }
static std::string& FIX8::RegExp::SubExpr (RegMatch & match, const std::string & source, std::string & target, const int offset = 0, const int num = 0) inline static
Extract a sub-expression.
Parameters
match reference to a RegMatch object
source source string
target location to place sub-experssion
offset to start searching
num desired sub-expression
Returns
the target string
Definition at line 452 of file f8utils.hpp.
References FIX8::RegMatch::SubCnt(), FIX8::RegMatch::subCnt_, FIX8::RegMatch::subexprs_, FIX8::RegMatch::SubPos(), and FIX8::RegMatch::SubSize().
Referenced by XmlElement::InplaceXlate(), and main().
    {
 #if FIX8_REGEX_SYSTEM == FIX8_REGEX_REGEX_H
       if (num < match.subCnt_)
          target = source.substr(offset + match.subexprs_[num].rm_so, match.subexprs_[num].rm_eo - match.subexprs_[num].rm_so);
 #elif FIX8_REGEX_SYSTEM == FIX8_REGEX_POCO
       if (num < static_cast<int>(match.SubCnt()))
          target = source.substr(offset + match.SubPos(num), match.SubSize(num));
 #endif
       else
          target.empty();
       return target;
    }
Member Data Documentation
int FIX8::RegExp::errCode_ private
Definition at line 382 of file f8utils.hpp.
Referenced by operator!().
std::string FIX8::RegExp::errString private
Definition at line 381 of file f8utils.hpp.
Referenced by ErrString().
const std::string FIX8::RegExp::pattern_ private
Definition at line 372 of file f8utils.hpp.
Referenced by GetPattern().
regex_t FIX8::RegExp::reg_ private
Definition at line 377 of file f8utils.hpp.
The documentation for this class was generated from the following file:
f8utils.hpp