fix8: FIX8::f8_scoped_lock_impl< T > Class Template Reference
FIX8::f8_scoped_lock_impl< T > Class Template Reference
#include <mpmc.hpp>
Public Member Functions
f8_scoped_lock_impl ()
f8_scoped_lock_impl (T &mutex)
f8_scoped_lock_impl (T &mutex, bool disable)
~f8_scoped_lock_impl ()
void acquire (T &mutex)
bool try_acquire (T &mutex)
void release ()
Private Member Functions
f8_scoped_lock_impl (const f8_scoped_lock_impl &)
f8_scoped_lock_impl & operator= (const f8_scoped_lock_impl &)
Private Attributes
T * _local_mutex
bool _disabled
Detailed Description
template<typename T>
class FIX8::f8_scoped_lock_impl< T >
Definition at line 81 of file mpmc.hpp.
Constructor & Destructor Documentation
template<typename T > FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl (const f8_scoped_lock_impl< T > &) private
template<typename T > FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl () inline
Definition at line 90 of file mpmc.hpp.
template<typename T > FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl (T & mutex) inline
Definition at line 91 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::acquire().
template<typename T > FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl (T & mutex, bool disable) inline
Definition at line 92 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::_disabled, and FIX8::f8_scoped_lock_impl< T >::acquire().
template<typename T > FIX8::f8_scoped_lock_impl< T >::~f8_scoped_lock_impl () inline
Definition at line 97 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::_disabled, FIX8::f8_scoped_lock_impl< T >::_local_mutex, and FIX8::f8_scoped_lock_impl< T >::release().
Member Function Documentation
template<typename T > void FIX8::f8_scoped_lock_impl< T >::acquire (T & mutex) inline
Definition at line 103 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::_local_mutex.
Referenced by FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl().
template<typename T > f8_scoped_lock_impl& FIX8::f8_scoped_lock_impl< T >::operator= (const f8_scoped_lock_impl< T > &) private
template<typename T > void FIX8::f8_scoped_lock_impl< T >::release () inline
Definition at line 117 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::_local_mutex.
Referenced by FIX8::Timer< T >::operator()(), and FIX8::f8_scoped_lock_impl< T >::~f8_scoped_lock_impl().
template<typename T > bool FIX8::f8_scoped_lock_impl< T >::try_acquire (T & mutex) inline
Definition at line 109 of file mpmc.hpp.
References FIX8::f8_scoped_lock_impl< T >::_local_mutex.
Member Data Documentation
template<typename T > bool FIX8::f8_scoped_lock_impl< T >::_disabled private
Definition at line 84 of file mpmc.hpp.
Referenced by FIX8::f8_scoped_lock_impl< T >::f8_scoped_lock_impl(), and FIX8::f8_scoped_lock_impl< T >::~f8_scoped_lock_impl().
template<typename T > T* FIX8::f8_scoped_lock_impl< T >::_local_mutex private
Definition at line 83 of file mpmc.hpp.
Referenced by FIX8::f8_scoped_lock_impl< T >::acquire(), FIX8::f8_scoped_lock_impl< T >::release(), FIX8::f8_scoped_lock_impl< T >::try_acquire(), and FIX8::f8_scoped_lock_impl< T >::~f8_scoped_lock_impl().
The documentation for this class was generated from the following file:
mpmc.hpp