fix8: FIX8::ebitset< T, B > Class Template Reference
FIX8::ebitset< T, B > Class Template Reference
Bitset for enums.
#include <f8utils.hpp>
Public Member Functions
ebitset ()
Ctor.
ebitset (const ebitset< T, B > &from)
ebitset (const integral_type a)
ebitset (const T sbit)
ebitset< T, B > & operator= (const ebitset< T, B > &that)
integral_type has (const T sbit) const
integral_type operator& (const T sbit) const
void set (const T sbit, bool on=true)
void set (const integral_type bset)
bool set (const std::vector< std::string > &sset, const std::string &what, bool on=true)
void clear (const T sbit)
void clearall ()
Clear all bits.
void setall (const T sbit)
integral_type get () const
void operator|= (const T sbit)
ebitset & operator<< (const T sbit)
Private Types
using integral_type = B
Private Attributes
integral_type a_
Detailed Description
template<typename T, typename B = unsigned int>
class FIX8::ebitset< T, B >
Bitset for enums.
Template Parameters
T the enum type
B the integral type of the enumeration
Definition at line 754 of file f8utils.hpp.
Member Typedef Documentation
template<typename T, typename B = unsigned int> using FIX8::ebitset< T, B >::integral_type = B private
Definition at line 756 of file f8utils.hpp.
Constructor & Destructor Documentation
template<typename T, typename B = unsigned int> FIX8::ebitset< T, B >::ebitset () inline
Ctor.
Definition at line 761 of file f8utils.hpp.
template<typename T, typename B = unsigned int> FIX8::ebitset< T, B >::ebitset (const ebitset< T, B > & from) inline
Ctor.
Parameters
from ebitset_r to copy
Definition at line 765 of file f8utils.hpp.
template<typename T, typename B = unsigned int> FIX8::ebitset< T, B >::ebitset (const integral_type a) inline explicit
Ctor.
Parameters
a integral type to construct from
Definition at line 769 of file f8utils.hpp.
template<typename T, typename B = unsigned int> FIX8::ebitset< T, B >::ebitset (const T sbit) inline explicit
Ctor.
Parameters
sbit enum to construct from
Definition at line 773 of file f8utils.hpp.
Member Function Documentation
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::clear (const T sbit) inline
Clear a bit on or off.
Parameters
sbit enum to set
Definition at line 820 of file f8utils.hpp.
Referenced by FIX8::FieldTraits::clear(), and FIX8::FieldTraits::clear_flag().
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::clearall () inline
Clear all bits.
Definition at line 823 of file f8utils.hpp.
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset< T, B >::get () const inline
Get the enum integral_type.
Returns
integral_type of enum
Definition at line 831 of file f8utils.hpp.
Referenced by FIX8::FieldTraits::getval(), and FIX8::operator<<().
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset< T, B >::has (const T sbit) const inline
Check if an enum is in the set.
Parameters
sbit enum to check
Returns
integral_type of bits if found
Definition at line 788 of file f8utils.hpp.
Referenced by FIX8::FieldTraits::get(), FIX8::FieldTraits::getPos(), FIX8::Logger::has_flag(), and FIX8::FileLogger::rotate().
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset< T, B >::operator& (const T sbit) const inline
Check if an enum is in the set.
Parameters
sbit enum to check
Returns
integral_type of bits if found
Definition at line 793 of file f8utils.hpp.
template<typename T, typename B = unsigned int> ebitset& FIX8::ebitset< T, B >::operator<< (const T sbit) inline
Or a bit value with the current set.
Parameters
sbit to set
Returns
ebitset
Definition at line 840 of file f8utils.hpp.
template<typename T, typename B = unsigned int> ebitset<T, B>& FIX8::ebitset< T, B >::operator= (const ebitset< T, B > & that) inline
Assignment operator.
Parameters
that ebitset_r to assign from
Returns
this
Definition at line 778 of file f8utils.hpp.
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::operator|= (const T sbit) inline
Or a bit value with the current set.
Parameters
sbit to set
Definition at line 835 of file f8utils.hpp.
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::set (const T sbit, bool on = true) inline
Set a bit on or off.
Parameters
sbit enum to set
on set on or off
Definition at line 798 of file f8utils.hpp.
Referenced by FIX8::Configuration::get_logflags(), FIX8::FieldTraits::set(), and FIX8::ebitset< TraitTypes, unsigned short >::set().
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::set (const integral_type bset) inline
Set a bit on or off.
Parameters
bset integral_type to set
Definition at line 802 of file f8utils.hpp.
template<typename T, typename B = unsigned int> bool FIX8::ebitset< T, B >::set (const std::vector< std::string > & sset, const std::string & what, bool on = true) inline
From a set of strings representing the names of each bit in order, set the named bit on.
Parameters
sset the set of strings
what the string to find and set
on set or clear the found bit
Returns
true if found and set
Definition at line 809 of file f8utils.hpp.
template<typename T, typename B = unsigned int> void FIX8::ebitset< T, B >::setall (const T sbit) inline
Set all bits to a value.
Parameters
sbit value to set to
Definition at line 827 of file f8utils.hpp.
Member Data Documentation
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset< T, B >::a_ private
Definition at line 757 of file f8utils.hpp.
Referenced by FIX8::ebitset< TraitTypes, unsigned short >::clear(), FIX8::ebitset< TraitTypes, unsigned short >::clearall(), FIX8::ebitset< TraitTypes, unsigned short >::get(), FIX8::ebitset< TraitTypes, unsigned short >::has(), FIX8::ebitset< TraitTypes, unsigned short >::operator&(), FIX8::ebitset< TraitTypes, unsigned short >::operator<<(), FIX8::ebitset< TraitTypes, unsigned short >::operator=(), FIX8::ebitset< TraitTypes, unsigned short >::operator|=(), FIX8::ebitset< TraitTypes, unsigned short >::set(), and FIX8::ebitset< TraitTypes, unsigned short >::setall().
The documentation for this class was generated from the following file:
f8utils.hpp