fix8: ff::ff_map Class Reference
ff::ff_map Class Reference
The map skeleton.
#include <map.hpp>
Classes
class mapC
class mapE
class mapW
Public Types
typedef void *(* map_worker_F_t)(basePartitioner *const, int tid)
typedef void *(* reduce_F_t)(void **V, int vsize)
Public Types inherited from ff::ff_farm< map_lb, map_gt >
enum
typedef map_lb LoadBalancer_t
typedef map_gt Gatherer_t
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Public Member Functions
ff_map (map_worker_F_t mapF, basePartitioner *mapP, reduce_F_t reduceF=NULL, bool input_ch=false)
ff_map (map_worker_F_t mapF, basePartitioner *mapP, void *task, reduce_F_t reduceF=NULL)
~ff_map ()
int get_my_id () const
Gets the ID of the ff_node.
void setAffinity (int cpuID)
int getCPUId () const
int wrap_around ()
Public Member Functions inherited from ff::ff_farm< map_lb, map_gt >
ff_farm (T *(*F)(T *), int nw, bool input_ch=false)
Constructor.
ff_farm (std::vector< ff_node * > &W, bool input_ch=false)
ff_farm (bool input_ch=false, int in_buffer_entries=DEF_IN_BUFF_ENTRIES, int out_buffer_entries=DEF_OUT_BUFF_ENTRIES, bool worker_cleanup=false, int max_num_workers=DEF_MAX_NUM_WORKERS, bool fixedsize=false)
Constructor.
~ff_farm ()
Destructor.
int add_emitter (ff_node *e)
Adds the emitter.
void set_scheduling_ondemand (const int inbufferentries=1)
Set scheduling with on demand polity.
int add_workers (std::vector< ff_node * > &w)
Adds workers to the form.
int add_collector (ff_node *c, bool outpresent=false)
Adds the collector.
int wrap_around ()
Sets the feedback channel from the collector to the emitter.
int remove_collector ()
Removes the collector.
int set_multi_input (ff_node **mi, int misize)
Sets multiple input.
void cleanup_workers ()
Delete workers when the destructor is called.
int run (bool skip_init=false)
Execute the Farm.
virtual int run_and_wait_end ()
Executs the farm and wait for workers to complete.
virtual int run_then_freeze (int nw=-1)
Executes the farm and then freeze.
int wait ()
Puts the thread in waiting state.
int wait_freezing ()
Waits for freezing.
void stop ()
Forces a thread to Stop.
void freeze ()
Forces the thread to freeze at next FF_EOS.
void thaw (bool _freeze=false, int nw=-1)
Thaws the thread.
bool isfrozen ()
Checks if the Farm is frozen.
bool offload (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=ff_loadbalancer::TICKS2WAIT)
bool load_result (void **task, unsigned int retry=((unsigned int)-1), unsigned int ticks=ff_gatherer::TICKS2WAIT)
Loads results into gatherer.
bool load_result_nb (void **task)
Loads result with non-blocking.
map_lb * getlb () const
Gets Emitter node.
map_gt * getgt () const
ff_node ** getWorkers () const
Gets workers list.
int getNWorkers () const
Gets the number of workers.
struct timeval getstarttime () const
Gets the starting time.
struct timeval getstoptime () const
Gets the stoping time.
struct timeval getwstartime () const
Gets the starting time.
struct timeval getwstoptime () const
Gets the finishing time.
double ffTime ()
Gets the time spent in svc_init.
double ffwTime ()
Gets the time spent in svc.
void ffStats (std::ostream &out)
Prints FastFlow message.
Public Member Functions inherited from ff::ff_node
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Private Attributes
basePartitioner * mapP
Additional Inherited Members
Protected Member Functions inherited from ff::ff_farm< map_lb, map_gt >
int cardinality (BARRIER_T *const barrier)
Cardinality of the Farm.
int prepare ()
Prepares the Farm skeleton.
int freeze_and_run (bool=false)
Frezes the thread and then execute.
void * svc (void *task)
svc method
int svc_init ()
The svc_init method.
void svc_end ()
The svc_end method.
int get_my_id () const
Gets the thread id.
void setAffinity (int)
Sets the affinity.
int getCPUId () const
Gets the id of the core.
int create_input_buffer (int nentries, bool fixedsize)
Creates the input buffer for the emitter node.
int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer for the collector.
int set_output_buffer (FFBUFFER *const o)
Sets the output buffer of the collector.
ff_node * getEmitter ()
Gets emitter.
ff_node * getCollector ()
Gets collector.
Protected Attributes inherited from ff::ff_farm< map_lb, map_gt >
bool has_input_channel
bool prepared
bool collector_removed
int ondemand
int nworkers
int in_buffer_entries
int out_buffer_entries
bool worker_cleanup
int max_nworkers
ff_node * emitter
ff_node * collector
map_lb * lb
map_gt * gt
ff_node ** workers
bool fixedsize
Detailed Description
The map skeleton.
The map skeleton, that extends the farm skeleton.
This class is defined in map.hpp
Definition at line 163 of file map.hpp.
Member Typedef Documentation
typedef void*(* ff::ff_map::map_worker_F_t)(basePartitioner *const, int tid)
worker function type Function called by each worker thread as soon as an input task is received. The first parameter is the partitioner (that can be user-defined or one of those provided in the partitioners.hpp file) used the get a task partition for the worker. tid is the worker/thread id (from 0 to mapWorkers-1).
Definition at line 174 of file map.hpp.
typedef void*(* ff::ff_map::reduce_F_t)(void **V, int vsize)
reduce function type It gets in input the array of tasks sent by each worker (one for each worker). vsize is the size of the V array.
Definition at line 182 of file map.hpp.
Constructor & Destructor Documentation
ff::ff_map::ff_map (map_worker_F_t mapF, basePartitioner * mapP, reduce_F_t reduceF = NULL, bool input_ch = false) inline
Public Constructor (1).
This constructor allows to activate the map for working on a stream of tasks or as a software accelerator by setting input_ch = true.
Parameters
mapF Specifies the Worker object that will execute the operations.
mapP It is the partitioner that is responsible to partition the problem.
reduceF The Reduce object. This parameter is optional and is to be specified when using a MapReduce skeleton. Defult is NULL.
input_ch Specifies whether the map skeleton is used as an accelerator. Default is false.
Definition at line 264 of file map.hpp.
References ff::ff_farm< map_lb, map_gt >::add_collector(), ff::ff_farm< map_lb, map_gt >::add_emitter(), ff::ff_farm< map_lb, map_gt >::add_workers(), ff::ff_farm< map_lb, map_gt >::getgt(), ff::ff_farm< map_lb, map_gt >::getlb(), and ff::basePartitioner::getParts().
ff::ff_map::ff_map (map_worker_F_t mapF, basePartitioner * mapP, void * task, reduce_F_t reduceF = NULL) inline
Public Constructor (2).
This constructor allows to activate the map for the computation of just one task
Parameters
mapF Specifies the Worker object that will execute the operations.
mapP It is the partitioner that is responsible to partition the problem.
task The task to be executed.
reduceF The Reduce object. This parameter is optional and is to be specified when using a MapReduce skeleton. Defult is NULL.
Definition at line 290 of file map.hpp.
References ff::ff_farm< map_lb, map_gt >::add_collector(), ff::ff_farm< map_lb, map_gt >::add_emitter(), ff::ff_farm< map_lb, map_gt >::add_workers(), ff::ff_farm< map_lb, map_gt >::getgt(), ff::ff_farm< map_lb, map_gt >::getlb(), and ff::basePartitioner::getParts().
ff::ff_map::~ff_map () inline
Destructor
Returns
TODO
Definition at line 309 of file map.hpp.
References ff::ff_farm< map_lb, map_gt >::getCollector(), ff::ff_farm< map_lb, map_gt >::getEmitter(), ff::ff_farm< map_lb, map_gt >::getNWorkers(), and ff::ff_farm< map_lb, map_gt >::getWorkers().
Member Function Documentation
int ff::ff_map::get_my_id () const inline virtual
Gets the ID of the ff_node.
Returns
The ID of the ff_node
Reimplemented from ff::ff_node.
Definition at line 318 of file map.hpp.
int ff::ff_map::getCPUId () const inline virtual
Retrivies the id of the cpu
Returns
the core id
Reimplemented from ff::ff_node.
Definition at line 342 of file map.hpp.
References ff::ff_node::getCPUId().
void ff::ff_map::setAffinity (int cpuID) inline virtual
This method sets the affinity for the emitter and collector threads, both are pinned on the same core.
Parameters
cpuID the ID of the cpu to which the threads will be pinned
Reimplemented from ff::ff_node.
Definition at line 326 of file map.hpp.
References ff::error(), ff::ff_farm< map_lb, map_gt >::getCollector(), ff::ff_farm< map_lb, map_gt >::getEmitter(), ff::threadMapper::instance(), and ff::ff_node::setAffinity().
int ff::ff_map::wrap_around () inline
TODO
Definition at line 347 of file map.hpp.
References ff::error().
Member Data Documentation
basePartitioner* ff::ff_map::mapP private
Definition at line 353 of file map.hpp.
The documentation for this class was generated from the following file:
map.hpp