fix8: ff::svector< T > Class Template Reference
ff::svector< T > Class Template Reference
TODO.
#include <svector.hpp>
Public Types
typedef T * iterator
typedef const T * const_iterator
typedef T vector_type
Public Member Functions
svector (size_t chunk=SVECTOR_CHUNK)
svector (const svector &v)
svector (const_iterator i1, const_iterator i2)
~svector ()
svector & operator= (const svector &v)
void reserve (size_t newcapacity)
void resize (size_t newsize)
void push_back (const vector_type &elem)
void pop_back ()
vector_type & back ()
iterator erase (iterator where)
size_t size () const
bool empty () const
size_t capacity () const
void clear ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
vector_type & operator[] (size_t n)
const vector_type & operator[] (size_t n) const
Private Types
enum { SVECTOR_CHUNK =1024 }
Private Attributes
vector_type * first
size_t len
size_t cap
size_t chunk
Detailed Description
template<typename T>
class ff::svector< T >
TODO.
This class is defined in svector.hpp
Definition at line 59 of file svector.hpp.
Member Typedef Documentation
template<typename T> typedef const T* ff::svector< T >::const_iterator
Definition at line 67 of file svector.hpp.
template<typename T> typedef T* ff::svector< T >::iterator
Definition at line 66 of file svector.hpp.
template<typename T> typedef T ff::svector< T >::vector_type
Definition at line 68 of file svector.hpp.
Member Enumeration Documentation
template<typename T> anonymous enum private
TODO
Enumerator
SVECTOR_CHUNK
Definition at line 64 of file svector.hpp.
Constructor & Destructor Documentation
template<typename T> ff::svector< T >::svector (size_t chunk = SVECTOR_CHUNK) inline
NOTE:
Parameters
chunk is the allocation chunk and not the svector size.
Definition at line 74 of file svector.hpp.
template<typename T> ff::svector< T >::svector (const svector< T > & v) inline
Constructor (1)
TODO
Definition at line 83 of file svector.hpp.
template<typename T> ff::svector< T >::svector (const_iterator i1, const_iterator i2) inline
Constructor (2)
TODO
Definition at line 97 of file svector.hpp.
template<typename T> ff::svector< T >::~svector () inline
Destructor
Definition at line 105 of file svector.hpp.
Member Function Documentation
template<typename T> vector_type& ff::svector< T >::back () inline
TODO
Definition at line 170 of file svector.hpp.
Referenced by ff::ff_gatherer::all_gather().
template<typename T> iterator ff::svector< T >::begin () inline
TODO
Definition at line 215 of file svector.hpp.
Referenced by ff::svector< bool >::erase(), ff::SlabCache::freeslab(), ff::svector< bool >::operator=(), ff::ff_map::mapC::svc(), ff::svector< bool >::svector(), and ff::SlabCache::~SlabCache().
template<typename T> const_iterator ff::svector< T >::begin () const inline
TODO
Definition at line 225 of file svector.hpp.
template<typename T> size_t ff::svector< T >::capacity () const inline
TODO
Definition at line 205 of file svector.hpp.
template<typename T> void ff::svector< T >::clear () inline
TODO
Definition at line 210 of file svector.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push(), ff::svector< bool >::operator=(), ff::ff_dinout< CommImplIn, CommImplOut >::push(), ff::SlabCache::~SlabCache(), and ff::svector< bool >::~svector().
template<typename T> bool ff::svector< T >::empty () const inline
TODO
Definition at line 200 of file svector.hpp.
template<typename T> iterator ff::svector< T >::end () inline
TODO
Definition at line 220 of file svector.hpp.
Referenced by ff::svector< bool >::erase(), ff::SlabCache::freeslab(), ff::svector< bool >::operator=(), ff::svector< bool >::svector(), and ff::SlabCache::~SlabCache().
template<typename T> const_iterator ff::svector< T >::end () const inline
TODO
Definition at line 230 of file svector.hpp.
template<typename T> iterator ff::svector< T >::erase (iterator where) inline
TODO
Definition at line 178 of file svector.hpp.
Referenced by ff::SlabCache::freeslab().
template<typename T> svector& ff::svector< T >::operator= (const svector< T > & v) inline
Overloading of operator =
Definition at line 116 of file svector.hpp.
template<typename T> vector_type& ff::svector< T >::operator[] (size_t n) inline
Overloading of operator []
Definition at line 235 of file svector.hpp.
template<typename T> const vector_type& ff::svector< T >::operator[] (size_t n) const inline
TODO
Definition at line 243 of file svector.hpp.
template<typename T> void ff::svector< T >::pop_back () inline
TODO
Definition at line 165 of file svector.hpp.
Referenced by ff::ff_gatherer::all_gather(), ff::svector< bool >::clear(), and ff::svector< bool >::resize().
template<typename T> void ff::svector< T >::push_back (const vector_type & elem) inline
TODO
Definition at line 157 of file svector.hpp.
Referenced by ff::ff_gatherer::all_gather(), ff::ff_allocator::init(), ff::SlabCache::newslab(), ff::svector< bool >::operator=(), ff::ff_dinout< CommImplIn, CommImplOut >::prepare(), ff::ff_dnode< CommImplIn >::prepare(), ff::ff_dinout< CommImplIn, CommImplOut >::setCallbackArg(), ff::ff_dnode< CommImplIn >::setCallbackArg(), ff::threadMapper::setMappingList(), ff::svector< bool >::svector(), and ff::threadMapper::threadMapper().
template<typename T> void ff::svector< T >::reserve (size_t newcapacity) inline
TODO
Definition at line 132 of file svector.hpp.
Referenced by ff::svector< bool >::operator[](), ff::svector< bool >::push_back(), ff::svector< bool >::resize(), ff::threadMapper::setMappingList(), ff::svector< bool >::svector(), and ff::threadMapper::threadMapper().
template<typename T> void ff::svector< T >::resize (size_t newsize) inline
TODO
Definition at line 144 of file svector.hpp.
Referenced by ff::zmqOnDemand::init(), ff::ff_dnode< CommImplIn >::internal_push(), ff::ofarm_gt::ofarm_gt(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
template<typename T> size_t ff::svector< T >::size () const inline
TODO
Definition at line 195 of file svector.hpp.
Referenced by ff::ff_gatherer::all_gather(), ff::svector< bool >::clear(), ff::threadMapper::getCListSize(), ff::ff_dnode< CommImplIn >::internal_push(), ff::ff_dinout< CommImplIn, CommImplOut >::push(), ff::zmqScatter::put(), ff::zmq1_N::put(), ff::ofarm_gt::reset(), and ff::threadMapper::setMappingList().
Member Data Documentation
template<typename T> size_t ff::svector< T >::cap private
Definition at line 248 of file svector.hpp.
Referenced by ff::svector< bool >::capacity(), ff::svector< bool >::push_back(), and ff::svector< bool >::reserve().
template<typename T> size_t ff::svector< T >::chunk private
Definition at line 249 of file svector.hpp.
Referenced by ff::svector< bool >::push_back(), and ff::svector< bool >::svector().
template<typename T> vector_type* ff::svector< T >::first private
Definition at line 246 of file svector.hpp.
Referenced by ff::svector< bool >::back(), ff::svector< bool >::begin(), ff::svector< bool >::end(), ff::svector< bool >::operator=(), ff::svector< bool >::operator[](), ff::svector< bool >::pop_back(), ff::svector< bool >::push_back(), ff::svector< bool >::reserve(), ff::svector< bool >::resize(), ff::svector< bool >::svector(), and ff::svector< bool >::~svector().
template<typename T> size_t ff::svector< T >::len private
Definition at line 247 of file svector.hpp.
Referenced by ff::svector< bool >::back(), ff::svector< bool >::empty(), ff::svector< bool >::end(), ff::svector< bool >::erase(), ff::svector< bool >::operator=(), ff::svector< bool >::pop_back(), ff::svector< bool >::push_back(), ff::svector< bool >::resize(), ff::svector< bool >::size(), and ff::svector< bool >::svector().
The documentation for this class was generated from the following file:
svector.hpp