fix8: FIX8::SingleLogger< fn > Class Template Reference
FIX8::SingleLogger< fn > Class Template Reference
A global singleton logger.
#include <logger.hpp>
Static Public Member Functions
static void set_global_filename (const std::string &from)
static bool log (const std::string &what, Logger::Level lev=Logger::Info, const char *fl=nullptr, unsigned int val=0)
static bool enqueue (const std::string &what, Logger::Level lev=Logger::Info, const char *fl=nullptr, unsigned int val=0)
static void flush_log ()
static void set_flags (Logger::LogFlags flags)
static void set_levels (Logger::Levels levels)
static void set_delimiter (const std::string &delim)
static void set_positions (Logger::LogPositions positions)
static void stop ()
static bool is_loggable (Logger::Level lev)
Static Private Member Functions
static FileLogger & instance ()
Detailed Description
template<char * fn>
class FIX8::SingleLogger< fn >
A global singleton logger.
Template Parameters
fn actual pathname of logfile
Create a static instance of this template and set the template parameter to the desired logfile pathname
Definition at line 475 of file logger.hpp.
Member Function Documentation
template<char * fn> static bool FIX8::SingleLogger< fn >::enqueue (const std::string & what, Logger::Level lev = Logger::Info, const char * fl = nullptr, unsigned int val = 0) inline static
Enqueue a message to the logger. Will not check log level.
Parameters
what message to log
lev level to log
fl pointer to fileline
val extra value to log
Returns
true on success
Definition at line 510 of file logger.hpp.
References FIX8::Logger::enqueue(), and FIX8::SingleLogger< fn >::instance().
       { return instance().enqueue(what, lev, fl, val); }
template<char * fn> static void FIX8::SingleLogger< fn >::flush_log () inline static
Flush the logger
Definition at line 514 of file logger.hpp.
References FIX8::Logger::flush(), and FIX8::SingleLogger< fn >::instance().
 { instance().flush(); }
template<char * fn> static FileLogger& FIX8::SingleLogger< fn >::instance () inline static private
Definition at line 477 of file logger.hpp.
References FIX8::Logger::All, FIX8::Logger::buffer, FIX8::Logger::level, FIX8::Logger::location, FIX8::Logger::sequence, FIX8::Logger::thread, and FIX8::Logger::timestamp.
Referenced by FIX8::SingleLogger< fn >::enqueue(), FIX8::SingleLogger< fn >::flush_log(), FIX8::SingleLogger< fn >::is_loggable(), FIX8::SingleLogger< fn >::log(), FIX8::SingleLogger< fn >::set_delimiter(), FIX8::SingleLogger< fn >::set_flags(), FIX8::SingleLogger< fn >::set_levels(), FIX8::SingleLogger< fn >::set_positions(), and FIX8::SingleLogger< fn >::stop().
    {
       static FileLogger _fl(fn, Logger::LogFlags() << Logger::timestamp << Logger::sequence << Logger::thread
             << Logger::level << Logger::location
 #if defined BUFFERED_GLOBAL_LOGGING
          << Logger::buffer
 #endif
          ,Logger::Levels(Logger::All));
       return _fl;
    }
template<char * fn> static bool FIX8::SingleLogger< fn >::is_loggable (Logger::Level lev) inline static
Check if the given log level is set for this logger
Parameters
lev level to test
Returns
true if available
Definition at line 538 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::is_loggable().
 { return instance().is_loggable(lev); }
template<char * fn> static bool FIX8::SingleLogger< fn >::log (const std::string & what, Logger::Level lev = Logger::Info, const char * fl = nullptr, unsigned int val = 0) inline static
Send a message to the logger.
Parameters
what message to log
lev level to log
fl pointer to fileline
val extra value to log
Returns
true on success
Definition at line 501 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::send().
Referenced by main().
       { return instance().send(what, lev, fl, val); }
template<char * fn> static void FIX8::SingleLogger< fn >::set_delimiter (const std::string & delim) inline static
Set the field delimiter
Parameters
delim delimiter value to set
Definition at line 526 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::set_delimiter().
 { instance().set_delimiter(delim); }
template<char * fn> static void FIX8::SingleLogger< fn >::set_flags (Logger::LogFlags flags) inline static
Set the logflags
Parameters
flags flags to set
Definition at line 518 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::set_flags().
 { instance().set_flags(flags); }
template<char * fn> static void FIX8::SingleLogger< fn >::set_global_filename (const std::string & from) inline static
Set the global logfile name.
Parameters
from name to set to
Definition at line 492 of file logger.hpp.
References FIX8::CopyString(), and FIX8::max_global_filename_length().
Referenced by main().
       { CopyString(from, fn, max_global_filename_length); }
template<char * fn> static void FIX8::SingleLogger< fn >::set_levels (Logger::Levels levels) inline static
Set the log levels
Parameters
levels levels to set
Definition at line 522 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::set_levels().
 { instance().set_levels(levels); }
template<char * fn> static void FIX8::SingleLogger< fn >::set_positions (Logger::LogPositions positions) inline static
Set the log positions
Parameters
positions positions to set
Definition at line 530 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::set_positions().
 { instance().set_positions(positions); }
template<char * fn> static void FIX8::SingleLogger< fn >::stop () inline static
Stop the logger
Definition at line 533 of file logger.hpp.
References FIX8::SingleLogger< fn >::instance(), and FIX8::Logger::stop().
 { instance().stop(); }
The documentation for this class was generated from the following file:
logger.hpp