fix8: FIX8::scoped_ptr< T > Class Template Reference
FIX8::scoped_ptr< T > Class Template Reference
C++11 inspired scoped pointer.
#include <f8utils.hpp>
Public Member Functions
scoped_ptr (T *p=0)
~scoped_ptr ()
Dtor. Destroys object.
template<typename U >
bool operator== (const scoped_ptr< U > &that) const
template<typename U >
bool operator== (const scoped_ptr< U > *that) const
template<typename U >
bool operator!= (const scoped_ptr< U > &that) const
template<typename U >
bool operator!= (const scoped_ptr< U > *that) const
bool operator== (const scoped_ptr< T > &that) const
bool operator== (const T *that) const
bool operator!= (const scoped_ptr< T > &that) const
bool operator!= (const T *that) const
T * operator-> () const
T & operator* () const
T * release ()
T * Reset (T *p=0)
T * get () const
Private Member Functions
scoped_ptr (const scoped_ptr &)
Copy Ctor. Non-copyable.
void operator= (const scoped_ptr &)
Assignment operator. Non-copyable.
Private Attributes
T * ptr_
Detailed Description
template<typename T>
class FIX8::scoped_ptr< T >
C++11 inspired scoped pointer.
Template Parameters
T typename
Definition at line 156 of file f8utils.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::scoped_ptr< T >::scoped_ptr (const scoped_ptr< T > &) private
Copy Ctor. Non-copyable.
template<typename T> FIX8::scoped_ptr< T >::scoped_ptr (T * p = 0) inline explicit
Ctor.
Parameters
p pointer to T
Definition at line 169 of file f8utils.hpp.
template<typename T> FIX8::scoped_ptr< T >::~scoped_ptr () inline
Dtor. Destroys object.
Definition at line 172 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
Member Function Documentation
template<typename T> T* FIX8::scoped_ptr< T >::get () const inline
Get the object pointer.
Returns
object
Definition at line 232 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
Referenced by main(), FIX8::scoped_ptr< T >::operator!=(), FIX8::FIXWriter::operator()(), FIX8::scoped_ptr< T >::operator==(), and FIX8::Session::process().
template<typename T> template<typename U > bool FIX8::scoped_ptr< T >::operator!= (const scoped_ptr< U > & that) const inline
Non-equivalence operator (other is scoped_ptr)
Template Parameters
U type of that object
Returns
true if objects are not equal
Definition at line 190 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::get(), and FIX8::scoped_ptr< T >::ptr_.
template<typename T> template<typename U > bool FIX8::scoped_ptr< T >::operator!= (const scoped_ptr< U > * that) const inline
Non-equivalence operator (other is scoped_ptr)
Template Parameters
U type of that object
Returns
true if objects are not equal
Definition at line 196 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> bool FIX8::scoped_ptr< T >::operator!= (const scoped_ptr< T > & that) const inline
Non-equivalence operator (other is scoped_ptr)
Returns
true if objects are not equal
Definition at line 208 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::get(), and FIX8::scoped_ptr< T >::ptr_.
template<typename T> bool FIX8::scoped_ptr< T >::operator!= (const T * that) const inline
Non-equivalence operator (other is ptr)
Returns
true if objects are not equal
Definition at line 212 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> T& FIX8::scoped_ptr< T >::operator* () const inline
Member dereference operator.
Returns
object
Definition at line 220 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> T* FIX8::scoped_ptr< T >::operator-> () const inline
Member selection operator.
Returns
pointer to object
Definition at line 216 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> void FIX8::scoped_ptr< T >::operator= (const scoped_ptr< T > &) private
Assignment operator. Non-copyable.
template<typename T> template<typename U > bool FIX8::scoped_ptr< T >::operator== (const scoped_ptr< U > & that) const inline
Equivalence operator (other is scoped_ptr)
Template Parameters
U type of that object
Returns
true if objects are equivalent
Definition at line 178 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::get(), and FIX8::scoped_ptr< T >::ptr_.
template<typename T> template<typename U > bool FIX8::scoped_ptr< T >::operator== (const scoped_ptr< U > * that) const inline
Equivalence operator (other is ptr)
Template Parameters
U type of that object
Returns
true if objects are equivalent
Definition at line 184 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> bool FIX8::scoped_ptr< T >::operator== (const scoped_ptr< T > & that) const inline
Equivalence operator (other is scoped_ptr)
Returns
true if objects are equivalent
Definition at line 200 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::get(), and FIX8::scoped_ptr< T >::ptr_.
template<typename T> bool FIX8::scoped_ptr< T >::operator== (const T * that) const inline
Equivalence operator (other is ptr)
Returns
true if objects are equivalent
Definition at line 204 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
template<typename T> T* FIX8::scoped_ptr< T >::release () inline
Member dereference operator.
Returns
object
Definition at line 224 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
Referenced by FIX8::Configuration::create_persister(), and open_ofile().
template<typename T> T* FIX8::scoped_ptr< T >::Reset (T * p = 0) inline
Replace the pointer with the supplied pointer.
Returns
the original pointer
Definition at line 228 of file f8utils.hpp.
References FIX8::scoped_ptr< T >::ptr_.
Referenced by main().
Member Data Documentation
template<typename T> T* FIX8::scoped_ptr< T >::ptr_ private
Definition at line 158 of file f8utils.hpp.
Referenced by FIX8::scoped_ptr< T >::get(), FIX8::scoped_ptr< T >::operator!=(), FIX8::scoped_ptr< T >::operator*(), FIX8::scoped_ptr< T >::operator->(), FIX8::scoped_ptr< T >::operator==(), FIX8::scoped_ptr< T >::release(), FIX8::scoped_ptr< T >::Reset(), and FIX8::scoped_ptr< T >::~scoped_ptr().
The documentation for this class was generated from the following file:
f8utils.hpp