fix8: FIX8::CustomFields Class Reference
FIX8::CustomFields Class Reference
Custom field wrapper.
#include <message.hpp>
Public Member Functions
CustomFields (bool cleanup=true)
virtual ~CustomFields ()
Dtor.
bool add (unsigned fnum, BaseEntry *be)
BaseEntry * find_ptr (unsigned fnum)
virtual bool post_msg_ctor (Message *msg)
Private Types
typedef std::map< unsigned,
BaseEntry * > CustFields
Private Attributes
CustFields _custFields
bool _cleanup
Detailed Description
Custom field wrapper.
Definition at line 146 of file message.hpp.
Member Typedef Documentation
typedef std:: map<unsigned, BaseEntry *> FIX8::CustomFields::CustFields private
Definition at line 154 of file message.hpp.
Constructor & Destructor Documentation
FIX8::CustomFields::CustomFields (bool cleanup = true) inline explicit
Ctor.
Parameters
cleanup if true, delete BaseEntries on destruction
Definition at line 161 of file message.hpp.
virtual FIX8::CustomFields::~CustomFields () inline virtual
Dtor.
Definition at line 164 of file message.hpp.
References _cleanup, and _custFields.
Member Function Documentation
bool FIX8::CustomFields::add (unsigned fnum, BaseEntry * be) inline
Add a new field.
Parameters
fnum field number (tag)
be BaseEntry of field
Returns
true on success
Definition at line 174 of file message.hpp.
References _custFields.
Referenced by FIX8::TEX::myfix_custom::myfix_custom().
BaseEntry* FIX8::CustomFields::find_ptr (unsigned fnum) inline
Find a field.
Parameters
fnum field number (tag)
Returns
pointer to BaseEntry or 0 if not found
Definition at line 180 of file message.hpp.
References _custFields.
virtual bool FIX8::CustomFields::post_msg_ctor (Message * msg) inline virtual
Post message ctor. Called by framework when a message has been constructed, permitting addition of custom fields.
Parameters
msg Message
Returns
true on success
Reimplemented in FIX8::TEX::myfix_custom.
Definition at line 189 of file message.hpp.
Referenced by FIX8::Message::factory(), and FIX8::Message::Message().
Member Data Documentation
bool FIX8::CustomFields::_cleanup private
Definition at line 156 of file message.hpp.
Referenced by ~CustomFields().
CustFields FIX8::CustomFields::_custFields private
Definition at line 155 of file message.hpp.
Referenced by add(), find_ptr(), and ~CustomFields().
The documentation for this class was generated from the following file:
message.hpp