fix8: ff::uSWSR_Ptr_Buffer Class Reference
ff::uSWSR_Ptr_Buffer Class Reference
Unbounded Single-Writer/Single-Reader circular buffer.
#include <ubuffer.hpp>
Public Member Functions
uSWSR_Ptr_Buffer (unsigned long n, const bool fixedsize=false, const bool fillcache=false)
~uSWSR_Ptr_Buffer ()
bool init ()
bool empty ()
bool available ()
bool push (void *const data)
bool mp_push (void *const data)
bool pop (void **data)
bool mc_pop (void **data)
unsigned long length () const
void reset ()
Private Types
enum { CACHE_SIZE =32 }
Private Attributes
INTERNAL_BUFFER_T * buf_r
long padding1 [longxCacheLine-1]
INTERNAL_BUFFER_T * buf_w
long padding2 [longxCacheLine-1]
lock_t P_lock
long padding3 [longxCacheLine-sizeof(lock_t)]
lock_t C_lock
long padding4 [longxCacheLine-sizeof(lock_t)]
const unsigned long size
const bool fixedsize
BufferPool pool
Detailed Description
Unbounded Single-Writer/Single-Reader circular buffer.
The unbounded SWSR circular buffer is based on a pool of wait-free SWSR circular buffers (see buffer.hpp). The pool of buffers automatically grows and shrinks on demand. The implementation of the pool of buffers carefully tries to minimize the impact of dynamic memory allocation/deallocation by using caching strategies. The unbounded buffer is based on the INTERNAL_BUFFER_T.
This class is defined in ubuffer.hpp
Definition at line 246 of file ubuffer.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
CACHE_SIZE
Definition at line 248 of file ubuffer.hpp.
Constructor & Destructor Documentation
ff::uSWSR_Ptr_Buffer::uSWSR_Ptr_Buffer (unsigned long n, const bool fixedsize = false, const bool fillcache = false) inline
Constructor
Parameters
n the size of the buffer
fixedsize a boolean flag that asserts whether the buffer can be resized. Default is false.
fillcache a flag.
Definition at line 283 of file ubuffer.hpp.
References C_lock, init_unlocked(), and P_lock.
ff::uSWSR_Ptr_Buffer::~uSWSR_Ptr_Buffer () inline
Destructor
Definition at line 293 of file ubuffer.hpp.
References buf_r.
Referenced by ff::xThreadData::~xThreadData().
Member Function Documentation
bool ff::uSWSR_Ptr_Buffer::available () inline
It returns true if there is at least one room in the buffer.
Returns
If available true is returned, otherwise false is returned.
Definition at line 341 of file ubuffer.hpp.
References buf_w.
Referenced by push().
bool ff::uSWSR_Ptr_Buffer::empty () inline
It returns true if the buffer is empty.
Returns
If successful true is returned, otherwise false is returned.
Definition at line 327 of file ubuffer.hpp.
References buf_r, and buf_w.
bool ff::uSWSR_Ptr_Buffer::init () inline
Initialise the unbounded buffer.
Definition at line 304 of file ubuffer.hpp.
References buf_r, buf_w, INTERNAL_BUFFER_T, and size.
Referenced by ff::multiSWSR::init(), and ff::xThreadData::xThreadData().
unsigned long ff::uSWSR_Ptr_Buffer::length () const inline
It returns the length of the queue. Note that this is not the real queue length but just a rough estimation.
Returns
TODO
Definition at line 492 of file ubuffer.hpp.
References buf_r, and buf_w.
bool ff::uSWSR_Ptr_Buffer::mc_pop (void ** data) inline
It defines multi-consumers pop method. lock protected.
Returns
TODO
Definition at line 479 of file ubuffer.hpp.
References C_lock, pop(), spin_lock(), and spin_unlock().
bool ff::uSWSR_Ptr_Buffer::mp_push (void *const data) inline
Multi-producers push method (lock protected)
Returns
TODO
Definition at line 386 of file ubuffer.hpp.
References P_lock, push(), spin_lock(), and spin_unlock().
bool ff::uSWSR_Ptr_Buffer::pop (void ** data) inline
Pop method: get the next data from the buffer
Parameters
data Double pointer to the location where to store the data popped from the buffer
Definition at line 429 of file ubuffer.hpp.
References buf_r, buf_w, INTERNAL_BUFFER_T, ff::BufferPool::next_r(), pool, and ff::BufferPool::release().
Referenced by ff::SlabCache::getfrom_fb_delayed(), mc_pop(), and ff::multiSWSR::pop().
bool ff::uSWSR_Ptr_Buffer::push (void *const data) inline
Push Method: push the input value into the queue.
If fixedsize has been set to true, this method may return false. This means EWOULDBLOCK and the call should be retried.
Parameters
data Data to be pushed in the buffer
Returns
false if fixedsize is set to true OR if data is NULL OR if there is not a buffer to write to.
true if the push succedes.
Definition at line 357 of file ubuffer.hpp.
References available(), buf_w, fixedsize, INTERNAL_BUFFER_T, ff::BufferPool::next_w(), pool, and size.
Referenced by mp_push(), ff::multiSWSR::push(), and ff::SlabCache::putitem().
void ff::uSWSR_Ptr_Buffer::reset () inline
Resets the buffer
Definition at line 501 of file ubuffer.hpp.
References buf_r, buf_w, pool, and ff::BufferPool::reset().
Member Data Documentation
INTERNAL_BUFFER_T* ff::uSWSR_Ptr_Buffer::buf_r private
Definition at line 511 of file ubuffer.hpp.
Referenced by empty(), init(), length(), pop(), reset(), and ~uSWSR_Ptr_Buffer().
INTERNAL_BUFFER_T* ff::uSWSR_Ptr_Buffer::buf_w private
Definition at line 513 of file ubuffer.hpp.
Referenced by available(), empty(), init(), length(), pop(), push(), and reset().
lock_t ff::uSWSR_Ptr_Buffer::C_lock private
Definition at line 519 of file ubuffer.hpp.
Referenced by mc_pop(), and uSWSR_Ptr_Buffer().
const bool ff::uSWSR_Ptr_Buffer::fixedsize private
Definition at line 535 of file ubuffer.hpp.
Referenced by push().
lock_t ff::uSWSR_Ptr_Buffer::P_lock private
Definition at line 517 of file ubuffer.hpp.
Referenced by mp_push(), and uSWSR_Ptr_Buffer().
long ff::uSWSR_Ptr_Buffer::padding1[longxCacheLine-1] private
Definition at line 512 of file ubuffer.hpp.
long ff::uSWSR_Ptr_Buffer::padding2[longxCacheLine-1] private
Definition at line 514 of file ubuffer.hpp.
long ff::uSWSR_Ptr_Buffer::padding3[longxCacheLine-sizeof(lock_t)] private
Definition at line 518 of file ubuffer.hpp.
long ff::uSWSR_Ptr_Buffer::padding4[longxCacheLine-sizeof(lock_t)] private
Definition at line 520 of file ubuffer.hpp.
BufferPool ff::uSWSR_Ptr_Buffer::pool private
Definition at line 536 of file ubuffer.hpp.
Referenced by pop(), push(), and reset().
const unsigned long ff::uSWSR_Ptr_Buffer::size private
Definition at line 534 of file ubuffer.hpp.
Referenced by init(), and push().
The documentation for this class was generated from the following file:
ubuffer.hpp