fix8: FIX8::TEX::myfix_custom Class Reference
FIX8::TEX::myfix_custom Class Reference
#include <myfix_custom.hpp>
Public Member Functions
virtual ~myfix_custom ()
virtual bool post_msg_ctor (Message *msg)
Public Member Functions inherited from FIX8::CustomFields
CustomFields (bool cleanup=true)
virtual ~CustomFields ()
Dtor.
bool add (unsigned fnum, BaseEntry *be)
BaseEntry * find_ptr (unsigned fnum)
Static Public Member Functions
myfix_custom (bool cleanup=true)
Detailed Description
Definition at line 87 of file myfix_custom.hpp.
Constructor & Destructor Documentation
FIX8::TEX::myfix_custom::myfix_custom (bool cleanup = true) inline static
Definition at line 90 of file myfix_custom.hpp.
References FIX8::CustomFields::add(), and FIX8::BaseEntry_ctor().
virtual FIX8::TEX::myfix_custom::~myfix_custom () inline virtual
Definition at line 100 of file myfix_custom.hpp.
Member Function Documentation
virtual bool FIX8::TEX::myfix_custom::post_msg_ctor (Message * msg) inline virtual
Post message ctor. Called by framework when a message has been constructed, permitting addition of custom fields.
Parameters
msg Message
Returns
true on success
Reimplemented from FIX8::CustomFields.
Definition at line 102 of file myfix_custom.hpp.
References FIX8::MessageBase::add_trait(), FIX8::MessageBase::get_msgtype(), and FIX8::TEX::ExecutionReport::get_msgtype().
The documentation for this class was generated from the following file:
myfix_custom.hpp