fix8: FIX8::ebitset_r< T, B > Class Template Reference
FIX8::ebitset_r< T, B > Class Template Reference
Atomic bitset for enums.
#include <f8utils.hpp>
Public Member Functions
ebitset_r ()
Ctor.
ebitset_r (const ebitset_r< T, B > &from)
ebitset_r (const integral_type a)
ebitset_r (const T sbit)
ebitset_r< T, B > & operator= (const ebitset_r< T, B > &that)
integral_type has (const T sbit) const
integral_type operator& (const T sbit) const
void set (const T sbit, bool on=true)
bool set (const std::vector< std::string > &sset, const std::string &what, bool ignorecase=false, bool on=true)
void set (const integral_type bset)
void clear (const T sbit)
void clearall ()
Clear all bits.
void setall (const T sbit)
integral_type get () const
void operator|= (const T sbit)
void operator&= (const T sbit)
ebitset_r & operator<< (const T sbit)
Private Types
using integral_type = B
Private Attributes
f8_atomic< integral_type > a_
Detailed Description
template<typename T, typename B = unsigned int>
class FIX8::ebitset_r< T, B >
Atomic bitset for enums.
Template Parameters
T the enum type
B the integral type of the enumeration
Definition at line 941 of file f8utils.hpp.
Member Typedef Documentation
template<typename T, typename B = unsigned int> using FIX8::ebitset_r< T, B >::integral_type = B private
Definition at line 943 of file f8utils.hpp.
Constructor & Destructor Documentation
template<typename T, typename B = unsigned int> FIX8::ebitset_r< T, B >::ebitset_r () inline
Ctor.
Definition at line 948 of file f8utils.hpp.
 { a_ = 0; }
template<typename T, typename B = unsigned int> FIX8::ebitset_r< T, B >::ebitset_r (const ebitset_r< T, B > & from) inline
Ctor.
Parameters
from ebitset_r to copy
Definition at line 952 of file f8utils.hpp.
 { a_ = from.a_; }
template<typename T, typename B = unsigned int> FIX8::ebitset_r< T, B >::ebitset_r (const integral_type a) inline explicit
Ctor.
Parameters
a integral type to construct from
Definition at line 956 of file f8utils.hpp.
 { a_ = a; }
template<typename T, typename B = unsigned int> FIX8::ebitset_r< T, B >::ebitset_r (const T sbit) inline explicit
Ctor.
Parameters
sbit enum to construct from
Definition at line 960 of file f8utils.hpp.
 { a_ = (1 << sbit) - 1; }
Member Function Documentation
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::clear (const T sbit) inline
Clear a bit on or off.
Parameters
sbit enum to set
Definition at line 1011 of file f8utils.hpp.
Referenced by FIX8::Session::start().
 { integral_type a = a_; a &= ~(1 << sbit); a_ = a; }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::clearall () inline
Clear all bits.
Definition at line 1014 of file f8utils.hpp.
 { a_ = 0; }
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset_r< T, B >::get () const inline
Get the enum integral_type.
Returns
integral_type of enum
Definition at line 1022 of file f8utils.hpp.
 { return a_; }
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset_r< T, B >::has (const T sbit) const inline
Check if an enum is in the set.
Parameters
sbit enum to check
Returns
integral_type of bits if found
Definition at line 975 of file f8utils.hpp.
Referenced by FIX8::Session::is_shutdown().
 { return a_ & 1 << sbit; }
template<typename T, typename B = unsigned int> integral_type FIX8::ebitset_r< T, B >::operator& (const T sbit) const inline
Check if an enum is in the set.
Parameters
sbit enum to check
Returns
integral_type of bits if found
Definition at line 980 of file f8utils.hpp.
 { return a_ & 1 << sbit; }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::operator&= (const T sbit) inline
And a bit value with the current set.
Parameters
sbit to set
Definition at line 1030 of file f8utils.hpp.
 { integral_type a = a_; a &= 1 << sbit; a_ = a; }
template<typename T, typename B = unsigned int> ebitset_r& FIX8::ebitset_r< T, B >::operator<< (const T sbit) inline
Or a bit value with the current set.
Parameters
sbit to set
Returns
ebitset_r
Definition at line 1035 of file f8utils.hpp.
 { a_ |= 1 << sbit; return *this; }
template<typename T, typename B = unsigned int> ebitset_r<T, B>& FIX8::ebitset_r< T, B >::operator= (const ebitset_r< T, B > & that) inline
Assignment operator.
Parameters
that ebitset_r to assign from
Returns
this
Definition at line 965 of file f8utils.hpp.
    {
       if (this != &that)
          a_ = that.a_;
       return *this;
    }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::operator|= (const T sbit) inline
Or a bit value with the current set.
Parameters
sbit to set
Definition at line 1026 of file f8utils.hpp.
 { integral_type a = a_; a |= 1 << sbit; a_ = a; }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::set (const T sbit, bool on = true) inline
Set a bit on or off.
Parameters
sbit enum to set
on set on or off
Definition at line 985 of file f8utils.hpp.
Referenced by FIX8::ebitset_r< SessionControl >::set().
 { if (on) a_ |= 1 << sbit; else a_ &= ~(1 << sbit); }
template<typename T, typename B = unsigned int> bool FIX8::ebitset_r< T, B >::set (const std::vector< std::string > & sset, const std::string & what, bool ignorecase = false, bool on = true) inline
From a set of strings representing the names of each bit in order, set the named bit on.
Parameters
sset the set of strings
what the string to find and set
ignorecase if true, ignore case
on set or clear the found bit
Returns
true if found and set
Definition at line 993 of file f8utils.hpp.
    {
       auto itr(sset.cbegin());
       for (; itr != sset.cend(); ++itr)
          if (ignorecase ? trim(*itr) % what : trim(*itr) == what)
             break;
       if (itr == sset.cend())
          return false;
       set(static_cast<T>(std::distance(sset.cbegin(), itr)), on);
       return true;
    }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::set (const integral_type bset) inline
Set a bit on or off.
Parameters
bset integral_type to set
Definition at line 1007 of file f8utils.hpp.
 { a_ = bset; }
template<typename T, typename B = unsigned int> void FIX8::ebitset_r< T, B >::setall (const T sbit) inline
Set all bits to a value.
Parameters
sbit value to set to
Definition at line 1018 of file f8utils.hpp.
 { a_ = (1 << sbit) - 1; }
Member Data Documentation
template<typename T, typename B = unsigned int> f8_atomic<integral_type> FIX8::ebitset_r< T, B >::a_ private
Definition at line 944 of file f8utils.hpp.
Referenced by FIX8::ebitset_r< SessionControl >::clear(), FIX8::ebitset_r< SessionControl >::ebitset_r(), FIX8::ebitset_r< SessionControl >::get(), FIX8::ebitset_r< SessionControl >::operator&=(), FIX8::ebitset_r< SessionControl >::operator=(), and FIX8::ebitset_r< SessionControl >::operator|=().
The documentation for this class was generated from the following file:
f8utils.hpp