fix8: ff::threadMapper Class Reference
ff::threadMapper Class Reference
The thread mapper allows to map threads to specific core using a predefined mapping policy.
#include <mapper.hpp>
Public Member Functions
threadMapper ()
void setMappingList (const char *str)
int getCoreId ()
unsigned int getMask ()
unsigned int getCListSize ()
int getCoreId (unsigned int tid)
bool checkCPUId (const int cpuId) const
Static Public Member Functions
static threadMapper * instance ()
Protected Attributes
long rrcnt
unsigned int mask
unsigned int num_cores
svector< int > CList
Detailed Description
The thread mapper allows to map threads to specific core using a predefined mapping policy.
The threadMapper stores a list of CPU ids. By default the list is simply a linear sequence of core ids of the system, for example in a quad-core system the default list is 0 1 2 3. It is possible to change the default list using the method setMappingList by passing a string of space-serated (or comma-separated) CPU ids. The policy implemented in the threadManager is to pick up a CPU id from the list using a round-robin policy.
This class is defined in mapper.hpp
Definition at line 62 of file mapper.hpp.
Constructor & Destructor Documentation
ff::threadMapper::threadMapper () inline
Default constructor.
Definition at line 77 of file mapper.hpp.
References CList, ff::error(), ff_numCores(), ff::isPowerOf2(), mask, ff::nextPowerOf2(), num_cores, ff::svector< T >::push_back(), ff::svector< T >::reserve(), and rrcnt.
Member Function Documentation
bool ff::threadMapper::checkCPUId (const int cpuId) const inline
It checks whether the taken core is within the range of the cores available on the machine.
Returns
It will return either true of false.
Definition at line 194 of file mapper.hpp.
References num_cores.
unsigned int ff::threadMapper::getCListSize () inline
It is used for debugging.
Returns
TODO
Definition at line 172 of file mapper.hpp.
References CList, and ff::svector< T >::size().
int ff::threadMapper::getCoreId () inline
Returns the next CPU id using a round-robin mapping access on the mapping list. This is clearly a raound robind scheduling!
Returns
The identifier of the core.
Definition at line 151 of file mapper.hpp.
References CList, mask, and rrcnt.
int ff::threadMapper::getCoreId (unsigned int tid) inline
It is used to get the identifier of the core.
Returns
The identifier of the core.
Definition at line 181 of file mapper.hpp.
References CList, and mask.
unsigned int ff::threadMapper::getMask () inline
It is used for debugging.
Returns
TODO
Definition at line 163 of file mapper.hpp.
References mask.
static threadMapper* ff::threadMapper::instance () inline static
Get a static instance of the threadMapper object
Returns
TODO
Definition at line 69 of file mapper.hpp.
Referenced by ff::init_thread_affinity(), ff::ff_map::setAffinity(), ff::ff_node::setAffinity(), and ff::ff_node::thWorker::svc_init().
void ff::threadMapper::setMappingList (const char * str) inline
It allows to set a new list of CPU ids.
The str variable should contain a space-separated or a comma-separated list of CPU ids. For example if the string str is "0 1 1 2 3", then the first thread will be bind to CPU 0, the second to CPU 1, the third to CPU 1, the fourth to CPU 2, the fifth to CPU 3. Then it follows the same rule for the subsequent threads.
Returns
TODO
Definition at line 111 of file mapper.hpp.
References CList, ff::error(), ff::isPowerOf2(), mask, ff::nextPowerOf2(), num_cores, ff::svector< T >::push_back(), ff::svector< T >::reserve(), rrcnt, and ff::svector< T >::size().
Member Data Documentation
svector<int> ff::threadMapper::CList protected
Definition at line 202 of file mapper.hpp.
Referenced by getCListSize(), getCoreId(), setMappingList(), and threadMapper().
unsigned int ff::threadMapper::mask protected
Definition at line 200 of file mapper.hpp.
Referenced by getCoreId(), getMask(), setMappingList(), and threadMapper().
unsigned int ff::threadMapper::num_cores protected
Definition at line 201 of file mapper.hpp.
Referenced by checkCPUId(), setMappingList(), and threadMapper().
long ff::threadMapper::rrcnt protected
Definition at line 199 of file mapper.hpp.
Referenced by getCoreId(), setMappingList(), and threadMapper().
The documentation for this class was generated from the following file:
mapper.hpp