fix8: ff::ff_gatherer Class Reference
ff::ff_gatherer Class Reference
A class representing the Collector node in a Farm skeleton.
#include <gt.hpp>
Public Types
enum { TICKS2WAIT =5000 }
Public Member Functions
ff_gatherer (int max_num_workers)
Constructor.
int set_filter (ff_node *f)
Sets the filer.
void set_out_buffer (FFBUFFER *const buff)
Sets output buffer.
int get_channel_id () const
Gets the channel id.
int getnworkers () const
Gets the number of worker threads currently running.
void skipfirstpop ()
Skips the first pop.
FFBUFFER * get_out_buffer () const
Gets the ouput buffer.
int register_worker (ff_node *w)
Register the given worker to the list of workers.
virtual int svc_init ()
Initializes the gatherer task.
virtual void * svc (void *)
The gatherer task.
virtual void svc_end ()
Finializes the gatherer.
int run (bool=false)
Execute the gatherer task.
virtual double ffTime ()
Start counting time.
virtual double wffTime ()
Complete counting time.
virtual struct timeval & getstarttime () const
virtual struct timeval & getstoptime () const
virtual struct timeval & getwstartime () const
virtual struct timeval & getwstoptime () const
Public Member Functions inherited from ff::ff_thread
virtual void svc_createOCL ()
The svc_createOCL method.
virtual void svc_releaseOCL ()
The svc_releaseOCL.
void set_barrier (BARRIER_T *const b)
Sets the barrier object.
int spawn (int cpuId=-1)
Creates a new thread.
int wait ()
Waits for thread termination.
int wait_freezing ()
Waits for thread freezing.
void stop ()
Forces the thread to stop.
void freeze ()
Forces the thread to freeze.
void thaw (bool _freeze=false)
Thaw the thread, if it is frozen.
bool isfrozen ()
Checks if the thread is frozen.
pthread_t get_handle () const
Gets the pthread handler.
int getTid () const
Gets the internal unique thread identifier.
Protected Member Functions
virtual int selectworker ()
Selects a worker.
virtual void notifyeos (int id)
Notifies the EOS.
virtual unsigned int ntentative ()
Gets the number of tentatives.
virtual void losetime_out ()
Loses the time out.
virtual void losetime_in ()
Loses the time in.
virtual int gather_task (void **task)
It gathers the tasks.
virtual int all_gather (void *task, void **V)
It gathers all tasks.
void push (void *task)
Pushes the task in the tasks queue.
bool pop (void **task)
Pop a task out of the queue.
bool pop_nb (void **task)
Pop a tak from un unbounded queue.
Protected Member Functions inherited from ff::ff_thread
ff_thread (BARRIER_T *barrier=NULL)
Constructor.
virtual ~ff_thread ()
Destructor.
void thread_routine ()
The life cycle of FastFlow thread.
int disable_cancelability ()
Disable the cancelation of thread.
int enable_cancelability ()
Makes thread cancelable.
Private Attributes
int max_nworkers
int nworkers
int nextr
int neos
int neosnofreeze
int channelid
ff_node * filter
svector< ff_node * > workers
svector< bool > offline
FFBUFFER * buffer
bool skip1pop
struct timeval tstart
struct timeval tstop
struct timeval wtstart
struct timeval wtstop
double wttime
Friends
template<typename T1 , typename T2 >
class ff_farm
class ff_pipeline
Additional Inherited Members
Protected Attributes inherited from ff::ff_thread
unsigned tid
Detailed Description
A class representing the Collector node in a Farm skeleton.
This class models the gatherer, which wraps all the methods and structures used by the Collector node in a Farm skeleton. The farm can be seen as a three-stages pipeline, the stages being a ff_loadbalancer called emitter, a pool of ff_node called workers and - optionally - a ff_gatherer called collector. The Collector node can be used to gather the results coming from the computations executed by the pool of workers. The collector can also be connected to the emitter node via a feedback channel, in order to create a farm-with-feedback skeleton.
This class is defined in gt.hpp
Definition at line 67 of file gt.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
TICKS2WAIT
Definition at line 72 of file gt.hpp.
Constructor & Destructor Documentation
ff::ff_gatherer::ff_gatherer (int max_num_workers) inline
Constructor.
It creates max_num_workers and NULL pointers to worker objects.
Definition at line 254 of file gt.hpp.
References FFTRACE, pushwait(), ff::time_setzero(), tstart, tstop, wtstart, wtstop, and wttime.
Member Function Documentation
virtual int ff::ff_gatherer::all_gather (void * task, void ** V) inline protected virtual
It gathers all tasks.
It is a virtual function, and gathers results from the workers.
Returns
It returns 0 if the tasks from all the workers are collected. Otherwise a negative value is returned.
Reimplemented in ff::map_gt.
Definition at line 165 of file gt.hpp.
References ff::svector< T >::back(), channelid, ff::FF_EOS, ff::FF_EOS_NOFREEZE, FFTRACE, getnworkers(), losetime_in(), nworkers, offline, ff::svector< T >::pop_back(), ff::svector< T >::push_back(), ff::svector< T >::size(), and workers.
Referenced by ff::map_gt::all_gather().
virtual double ff::ff_gatherer::ffTime () inline virtual
Start counting time.
It defines the counting of start time.
Returns
Difference in milli seconds.
Definition at line 473 of file gt.hpp.
References ff::diffmsec(), tstart, and tstop.
virtual int ff::ff_gatherer::gather_task (void ** task) inline protected virtual
It gathers the tasks.
It keeps selecting the worker. If a worker has task, then the worker is returned. Otherwise a tick is wasted and then keep looking for the worker with the task.
Returns
It returns the workers with a taks if successful. Otherwise -1 is returned.
Definition at line 137 of file gt.hpp.
References losetime_in(), nextr, ntentative(), offline, selectworker(), and workers.
Referenced by svc().
int ff::ff_gatherer::get_channel_id () const inline
Gets the channel id.
It gets the channelid.
Returns
The channelid is returned.
Definition at line 295 of file gt.hpp.
References channelid.
FFBUFFER* ff::ff_gatherer::get_out_buffer () const inline
Gets the ouput buffer.
It gets the output buffer
Returns
buffer is returned.
Definition at line 322 of file gt.hpp.
References buffer.
Referenced by pop(), pop_nb(), and svc().
int ff::ff_gatherer::getnworkers () const inline
Gets the number of worker threads currently running.
It gets the number of threads currently running.
Returns
Number of worker threads
Definition at line 304 of file gt.hpp.
References neos, neosnofreeze, and workers.
Referenced by all_gather(), and ff::ff_map::mapC::svc().
virtual struct timeval& ff::ff_gatherer::getstarttime () const inline read virtual
Definition at line 488 of file gt.hpp.
References tstart.
virtual struct timeval& ff::ff_gatherer::getstoptime () const inline read virtual
Definition at line 489 of file gt.hpp.
References tstop.
virtual struct timeval& ff::ff_gatherer::getwstartime () const inline read virtual
Definition at line 490 of file gt.hpp.
References wtstart.
virtual struct timeval& ff::ff_gatherer::getwstoptime () const inline read virtual
Definition at line 491 of file gt.hpp.
References wtstop.
virtual void ff::ff_gatherer::losetime_in () inline protected virtual
Loses the time in.
It is a virutal function which defines the number of ticks to be waited.
Definition at line 122 of file gt.hpp.
References FFTRACE, TICKS2WAIT, and ff::ticks_wait().
Referenced by all_gather(), gather_task(), and pop().
virtual void ff::ff_gatherer::losetime_out () inline protected virtual
Loses the time out.
It is a virutal function which defines the number of ticks to be waited.
Definition at line 111 of file gt.hpp.
References FFTRACE, pushwait(), TICKS2WAIT, and ff::ticks_wait().
Referenced by push().
virtual void ff::ff_gatherer::notifyeos (int id) inline protected virtual
Notifies the EOS.
It is a virtual function and is used to notify EOS
Definition at line 96 of file gt.hpp.
virtual unsigned int ff::ff_gatherer::ntentative () inline protected virtual
Gets the number of tentatives.
The number of tentative before wasting some times and than retry
Definition at line 103 of file gt.hpp.
References nworkers.
Referenced by gather_task().
bool ff::ff_gatherer::pop (void ** task) inline protected
Pop a task out of the queue.
It pops the task out of the queue.
Returns
false if not successful, otherwise true is returned.
Definition at line 226 of file gt.hpp.
References buffer, get_out_buffer(), and losetime_in().
bool ff::ff_gatherer::pop_nb (void ** task) inline protected
Pop a tak from un unbounded queue.
It pops the task from an unbounded queue.
Returns
The task popped from the buffer.
Definition at line 242 of file gt.hpp.
References buffer, and get_out_buffer().
void ff::ff_gatherer::push (void * task) inline protected
Pushes the task in the tasks queue.
It pushes the tasks in a queue.
Definition at line 196 of file gt.hpp.
References buffer, filter, losetime_out(), and ff::ff_node::push().
Referenced by svc().
int ff::ff_gatherer::register_worker (ff_node * w) inline
Register the given worker to the list of workers.
It registers the given worker to the list of workers.
Returns
0 if successful, or -1 if not successful.
Definition at line 331 of file gt.hpp.
References ff::error(), max_nworkers, nworkers, and workers.
Referenced by ff::ff_minode::create_input_buffer().
int ff::ff_gatherer::run (bool = false) inline
Execute the gatherer task.
It executes the gatherer task.
Returns
0 if successful, otherwise -1 is returned.
Definition at line 458 of file gt.hpp.
References ff::error(), filter, ff::ff_node::getCPUId(), and ff::ff_thread::spawn().
Referenced by ff::ff_minode::run().
virtual int ff::ff_gatherer::selectworker () inline protected virtual
Selects a worker.
It gets the next worker using the Round Robin policy. The selected worker has to be alive (and kicking).
Returns
The next worker to be selected.
Reimplemented in ff::ofarm_gt.
Definition at line 85 of file gt.hpp.
References nextr, nworkers, and offline.
Referenced by gather_task().
int ff::ff_gatherer::set_filter (ff_node * f) inline
Sets the filer.
It sents the ff_node to the filter.
Returns
0 if successful, otherwise a negative value is returned.
Definition at line 272 of file gt.hpp.
References ff::error(), and filter.
Referenced by ff::ff_minode::run().
void ff::ff_gatherer::set_out_buffer (FFBUFFER *const buff) inline
Sets output buffer.
It sets the output buffer.
Definition at line 286 of file gt.hpp.
References buffer.
Referenced by svc().
void ff::ff_gatherer::skipfirstpop () inline
Skips the first pop.
It determine whether the first pop should be skipped or not.
Returns
Always is returned.
Definition at line 313 of file gt.hpp.
References skip1pop.
Referenced by ff::ff_minode::create_input_buffer(), and svc().
virtual void* ff::ff_gatherer::svc (void *) inline virtual
The gatherer task.
It is a virtual function to be used as the gatherer task.
Returns
It returns the task.
Implements ff::ff_thread.
Definition at line 362 of file gt.hpp.
References channelid, ff::diffmsec(), ff::ff_node::eosnotify(), ff::FF_EOS, ff::FF_EOS_NOFREEZE, FFTRACE, filter, gather_task(), ff::ff_node::get_in_buffer(), get_out_buffer(), ff::ff_node::get_out_buffer(), GO_ON, neos, neosnofreeze, nextr, nworkers, offline, push(), set_out_buffer(), skip1pop, skipfirstpop(), ff::ff_node::svc(), workers, wtstart, wtstop, and wttime.
virtual void ff::ff_gatherer::svc_end () inline virtual
Finializes the gatherer.
It is a virtual function used to finalise the gatherer task.
Reimplemented from ff::ff_thread.
Definition at line 446 of file gt.hpp.
References filter, ff::ff_node::svc_end(), and tstop.
virtual int ff::ff_gatherer::svc_init () inline virtual
Initializes the gatherer task.
It is a virtual function to initialise the gatherer task.
Returns
It returns the task if successful, otherwise 0 is returned.
Reimplemented from ff::ff_thread.
Definition at line 348 of file gt.hpp.
References filter, offline, ff::ff_node::svc_init(), tstart, and workers.
virtual double ff::ff_gatherer::wffTime () inline virtual
Complete counting time.
It defines the counting of finished time.
Returns
Difference in milli seconds.
Definition at line 484 of file gt.hpp.
References ff::diffmsec(), wtstart, and wtstop.
Friends And Related Function Documentation
template<typename T1 , typename T2 > friend class ff_farm friend
Definition at line 69 of file gt.hpp.
friend class ff_pipeline friend
Definition at line 70 of file gt.hpp.
Member Data Documentation
FFBUFFER* ff::ff_gatherer::buffer private
Definition at line 522 of file gt.hpp.
Referenced by get_out_buffer(), pop(), pop_nb(), push(), and set_out_buffer().
int ff::ff_gatherer::channelid private
Definition at line 517 of file gt.hpp.
Referenced by all_gather(), get_channel_id(), and svc().
ff_node* ff::ff_gatherer::filter private
Definition at line 519 of file gt.hpp.
Referenced by push(), run(), set_filter(), svc(), svc_end(), and svc_init().
int ff::ff_gatherer::max_nworkers private
Definition at line 511 of file gt.hpp.
Referenced by register_worker().
int ff::ff_gatherer::neos private
Definition at line 515 of file gt.hpp.
Referenced by getnworkers(), and svc().
int ff::ff_gatherer::neosnofreeze private
Definition at line 516 of file gt.hpp.
Referenced by getnworkers(), and svc().
int ff::ff_gatherer::nextr private
Definition at line 513 of file gt.hpp.
Referenced by gather_task(), selectworker(), and svc().
int ff::ff_gatherer::nworkers private
Definition at line 512 of file gt.hpp.
Referenced by all_gather(), ntentative(), register_worker(), selectworker(), and svc().
svector<bool> ff::ff_gatherer::offline private
Definition at line 521 of file gt.hpp.
Referenced by all_gather(), gather_task(), selectworker(), svc(), and svc_init().
bool ff::ff_gatherer::skip1pop private
Definition at line 523 of file gt.hpp.
Referenced by skipfirstpop(), and svc().
struct timeval ff::ff_gatherer::tstart private
Definition at line 525 of file gt.hpp.
Referenced by ff_gatherer(), ffTime(), getstarttime(), and svc_init().
struct timeval ff::ff_gatherer::tstop private
Definition at line 526 of file gt.hpp.
Referenced by ff_gatherer(), ffTime(), getstoptime(), and svc_end().
svector<ff_node*> ff::ff_gatherer::workers private
Definition at line 520 of file gt.hpp.
Referenced by all_gather(), gather_task(), getnworkers(), register_worker(), svc(), and svc_init().
struct timeval ff::ff_gatherer::wtstart private
Definition at line 527 of file gt.hpp.
Referenced by ff_gatherer(), getwstartime(), svc(), and wffTime().
struct timeval ff::ff_gatherer::wtstop private
Definition at line 528 of file gt.hpp.
Referenced by ff_gatherer(), getwstoptime(), svc(), and wffTime().
double ff::ff_gatherer::wttime private
Definition at line 529 of file gt.hpp.
Referenced by ff_gatherer(), and svc().
The documentation for this class was generated from the following file:
gt.hpp