fix8: FIX8::Timer< T > Class Template Reference
FIX8::Timer< T > Class Template Reference
High resolution timer.
#include <timer.hpp>
Public Member Functions
Timer (T &monitor, int granularity=10)
virtual ~Timer ()
Dtor.
bool schedule (TimerEvent< T > what, unsigned timeToWaitMS)
size_t clear ()
void join ()
Join timer thread. Wait till exits.
void start ()
Start the timer thread.
void stop ()
Stop the timer thread.
int operator() ()
f8_thread_cancellation_token & cancellation_token ()
Private Attributes
T & _monitor
f8_thread< Timer > _thread
f8_spin_lock _spin_lock
unsigned _granularity
std::priority_queue< TimerEvent< T > > _event_queue
f8_thread_cancellation_token _cancellation_token
Detailed Description
template<typename T>
class FIX8::Timer< T >
High resolution timer.
Template Parameters
T callback context class
Definition at line 55 of file timer.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::Timer< T >::Timer (T & monitor, int granularity = 10) inline explicit
Ctor.
Parameters
monitor reference to callback class
granularity timer recheck interval in ms
Definition at line 107 of file timer.hpp.
 : _monitor(monitor), _thread(std::ref(*this)), _granularity(granularity) {}
template<typename T> virtual FIX8::Timer< T >::~Timer () inline virtual
Dtor.
Definition at line 110 of file timer.hpp.
    {
       stop();
       join();
    }
Member Function Documentation
template<typename T> f8_thread_cancellation_token& FIX8::Timer< T >::cancellation_token () inline
Definition at line 139 of file timer.hpp.
 { return _cancellation_token;}
template<typename T > size_t FIX8::Timer< T >::clear ()
Empty the scheduler of any pending timer events.
Returns
number of timer events that were waiting on the queue
Definition at line 195 of file timer.hpp.
 {
    size_t result(0);
    f8_scoped_spin_lock guard(_spin_lock);
    while (_event_queue.size())
    {
       ++result;
       _event_queue.pop(); // remove from queue
    }
    return result;
 }
template<typename T> void FIX8::Timer< T >::join () inline
Join timer thread. Wait till exits.
Definition at line 127 of file timer.hpp.
Referenced by FIX8::Timer< FIX8::Session >::~Timer().
 { _thread.join(); }
template<typename T > int FIX8::Timer< T >::operator() ()
Timer thread entry point.
Returns
result at timer thread exit
Definition at line 144 of file timer.hpp.
References FIX8::f8_scoped_lock_impl< T >::acquire(), FIX8::Tickval::get_ticks(), FIX8::Tickval::get_tickval(), glout_info, FIX8::hypersleep< h_milliseconds >(), FIX8::Tickval::million, and FIX8::f8_scoped_lock_impl< T >::release().
 {
    unsigned elapsed(0);
    while(!_cancellation_token)
    {
       bool shouldsleep(false);
       {
          f8_scoped_spin_lock guard(_spin_lock);
          if (_event_queue.size())
          {
             TimerEvent<T> op(_event_queue.top());
             if (!op._t) // ignore empty timeval
             {
                _event_queue.pop(); // remove from queue
                continue;
             }
             const Tickval now(Tickval::get_tickval());
             if (op._t <= now)  // has elapsed
             {
                TimerEvent<T> rop(_event_queue.top()); // take a copy
                _event_queue.pop(); // remove from queue
                guard.release();
                ++elapsed;
                const bool result((_monitor.*rop._callback)());
                if (result && op._repeat) // don't repeat if callback returned false
                {
                   op._t = now.get_ticks() + op._intervalMS * Tickval::million;
                   guard.acquire(_spin_lock);
                   _event_queue.push(std::move(op)); // push back on queue
                }
             }
             else
                shouldsleep = true;
          }
          else
             shouldsleep = true;
       }  // we want the lock to go out of scope before we sleep
       if (shouldsleep)
          hypersleep<h_milliseconds>(_granularity);
    }
    glout_info << "Terminating Timer thread (" << elapsed << " elapsed, " << _event_queue.size() << " queued).";
    return 0;
 }
template<typename T> bool FIX8::Timer< T >::schedule (TimerEvent< T > what, unsigned timeToWaitMS)
Schedule a timer event. Callback method in event called on timer expiry.
Parameters
what TimeEvent to schedule
timeToWaitMS interval to wait in ms
Returns
true on success
Definition at line 211 of file timer.hpp.
References FIX8::TimerEvent< T >::_intervalMS, FIX8::Tickval::get_tickval(), FIX8::Tickval::million, and FIX8::TimerEvent< T >::set().
 {
    Tickval tofire;
    if (timeToWait)
    {
       // Calculate time to fire
       Tickval::get_tickval(tofire);
       tofire += timeToWait * Tickval::million;
       what._intervalMS = timeToWait;
    }
    what.set(tofire);
    f8_scoped_spin_lock guard(_spin_lock);
    _event_queue.push(std::move(what));
    return true;
 }
template<typename T> void FIX8::Timer< T >::start () inline
Start the timer thread.
Definition at line 130 of file timer.hpp.
 { _thread.start(); }
template<typename T> void FIX8::Timer< T >::stop () inline
Stop the timer thread.
Definition at line 133 of file timer.hpp.
Referenced by FIX8::Timer< FIX8::Session >::~Timer().
 { _thread.request_stop(); }
Member Data Documentation
template<typename T> f8_thread_cancellation_token FIX8::Timer< T >::_cancellation_token private
Definition at line 101 of file timer.hpp.
Referenced by FIX8::Timer< FIX8::Session >::cancellation_token().
template<typename T> std::priority_queue<TimerEvent<T> > FIX8::Timer< T >::_event_queue private
Definition at line 100 of file timer.hpp.
template<typename T> unsigned FIX8::Timer< T >::_granularity private
Definition at line 98 of file timer.hpp.
template<typename T> T& FIX8::Timer< T >::_monitor private
Definition at line 95 of file timer.hpp.
template<typename T> f8_spin_lock FIX8::Timer< T >::_spin_lock private
Definition at line 97 of file timer.hpp.
template<typename T> f8_thread<Timer> FIX8::Timer< T >::_thread private
Definition at line 96 of file timer.hpp.
The documentation for this class was generated from the following file:
timer.hpp