fix8: FIX8::BDBPersister Class Reference
FIX8::BDBPersister Class Reference
BerkeleyDB backed message persister.
#include <persist.hpp>
Classes
struct KeyDataBuffer
struct KeyDataPair
Public Member Functions
BDBPersister ()
Ctor.
virtual ~BDBPersister ()
Dtor.
virtual F8API bool initialise (const f8String &dbDir, const f8String &dbFname, bool purge=false)
virtual F8API unsigned find_nearest_highest_seqnum (const unsigned requested, const unsigned last) const
virtual F8API bool put (const unsigned seqnum, const f8String &what)
virtual F8API bool put (const unsigned sender_seqnum, const unsigned target_seqnum)
virtual F8API bool get (const unsigned seqnum, f8String &to) const
virtual unsigned get (const unsigned from, const unsigned to, Session &session, bool(Session::*)(const Session::SequencePair &with, Session::RetransmissionContext &rctx)) const
virtual F8API unsigned get_last_seqnum (unsigned &to) const
virtual F8API bool get (unsigned &sender_seqnum, unsigned &target_seqnum) const
void stop ()
Stop the persister thread.
F8API int operator() ()
f8_thread_cancellation_token & cancellation_token ()
Public Member Functions inherited from FIX8::Persister
Persister ()=default
Ctor.
virtual ~Persister ()
Dtor.
Persister (const Persister &)=delete
Persister & operator= (const Persister &)=delete
virtual bool put (const f8String &key, const f8String &what)
virtual bool get (const f8String &key, f8String &to) const
virtual bool del (const f8String &key)
virtual bool purge ()
Private Member Functions
bool write (const KeyDataBuffer &what)
Static Private Member Functions
static int bt_compare_fcn (Db *db, const Dbt *p1, const Dbt *p2)
Private Attributes
f8_thread< BDBPersister > _thread
DbEnv _dbEnv
Db * _db
f8String _dbDir
f8String _dbFname
bool _wasCreated
f8_concurrent_queue
< KeyDataBuffer > _persist_queue
f8_thread_cancellation_token _cancellation_token
Additional Inherited Members
Public Types inherited from FIX8::Persister
enum { MaxMsgLen = MAX_MSG_LENGTH }
Maximum length of persisted FIX message.
Protected Attributes inherited from FIX8::Persister
bool _opened = false
Detailed Description
BerkeleyDB backed message persister.
Definition at line 149 of file persist.hpp.
Constructor & Destructor Documentation
FIX8::BDBPersister::BDBPersister () inline
Ctor.
Definition at line 223 of file persist.hpp.
 : _thread(std::ref(*this)), _dbEnv(0), _db(new Db(&_dbEnv, 0)), _wasCreated() {}
BDBPersister::~BDBPersister () virtual
Dtor.
Definition at line 114 of file persist.cpp.
 {
    stop();
    if (_opened)
       _db->close(0);
    delete _db;
    _dbEnv.close(0);
    //cout << "BDBPersister::~BDBPersister()" << endl;
 }
Member Function Documentation
static int FIX8::BDBPersister::bt_compare_fcn (Db * db, const Dbt * p1, const Dbt * p2) inline static private
Definition at line 202 of file persist.hpp.
    {
       // Returns: < 0 if a < b; = 0 if a = b; > 0 if a > b
       const unsigned& a((*reinterpret_cast<KeyDataBuffer *>(p1->get_data())).keyBuf_.int_);
       const unsigned& b((*reinterpret_cast<KeyDataBuffer *>(p2->get_data())).keyBuf_.int_);
       return a < b ? -1 : a > b ? 1 : 0;
    }
f8_thread_cancellation_token& FIX8::BDBPersister::cancellation_token () inline
Definition at line 285 of file persist.hpp.
References _cancellation_token.
 { return _cancellation_token; }
unsigned BDBPersister::find_nearest_highest_seqnum (const unsigned requested, const unsigned last) const virtual
Find the nearest highest sequence number from the sequence to last provided.
Parameters
requested sequence number to start
last highest sequence
Returns
the nearest sequence number or 0 if not found
Implements FIX8::Persister.
Definition at line 246 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, and FIX8::BDBPersister::KeyDataPair::_key.
 {
    if (_opened && last)
    {
       for (unsigned startseqnum(requested); startseqnum <= last; ++startseqnum)
       {
          KeyDataBuffer buffer(startseqnum);
          KeyDataPair keyPair(buffer);
          if (_db->get(0, &keyPair._key, &keyPair._data, 0) == 0)
             return startseqnum;
       }
    }
    return 0;
 }
bool BDBPersister::get (const unsigned seqnum, f8String & to) const virtual
Retrieve a persisted message.
Parameters
seqnum sequence number of message
to target message string
Returns
true on success
Implements FIX8::Persister.
Definition at line 229 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, FIX8::BDBPersister::KeyDataPair::_key, FIX8::BDBPersister::KeyDataBuffer::dataBuf_, and glout_error.
 {
    if (!_opened || !seqnum)
       return false;
    KeyDataBuffer buffer(seqnum);
    KeyDataPair keyPair(buffer);
    int retval(_db->get(0, &keyPair._key, &keyPair._data, 0));
    if (retval)
    {
       glout_error << "Could not get " << seqnum << '(' << db_strerror(retval) << ')';
       return false;
    }
    to.assign(buffer.dataBuf_);
    return true;
 }
unsigned BDBPersister::get (const unsigned from, const unsigned to, Session & session, bool(Session::*)(const Session::SequencePair &with, Session::RetransmissionContext &rctx) callback) const virtual
Retrieve a range of persisted messages.
Parameters
from start at sequence number
to end sequence number
session session containing callback method
callback method to call with each retrieved message
Returns
number of messages retrieved
Implements FIX8::Persister.
Definition at line 144 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, FIX8::BDBPersister::KeyDataPair::_key, FIX8::Session::RetransmissionContext::_no_more_records, FIX8::BDBPersister::KeyDataBuffer::dataBuf_, FIX8::Session::get_next_send_seq(), glout_warn, FIX8::BDBPersister::KeyDataBuffer::Ubuf::int_, and FIX8::BDBPersister::KeyDataBuffer::keyBuf_.
 {
    unsigned last_seq(0);
    get_last_seqnum(last_seq);
    unsigned recs_sent(0), startSeqNum(find_nearest_highest_seqnum (from, last_seq));
    const unsigned finish(to == 0 ? last_seq : to);
    Session::RetransmissionContext rctx(from, to, session.get_next_send_seq());
    if (!startSeqNum || from > finish)
    {
       glout_warn << "No records found";
       rctx._no_more_records = true;
       (session.*callback)(Session::SequencePair(0, ""), rctx);
       return 0;
    }
    KeyDataBuffer buffer(startSeqNum);
    KeyDataPair keyPair(buffer);
    Dbc *cursorp;
    _db->cursor (0, &cursorp, 0);
    int retval;
    if ((retval = cursorp->get(&keyPair._key, &keyPair._data, DB_SET)) == 0)
    {
       do
       {
          const unsigned seqnum(buffer.keyBuf_.int_);
          if (!seqnum || seqnum > finish)
             break;
          Session::SequencePair result(seqnum, buffer.dataBuf_);
          ++recs_sent;
          if (!(session.*callback)(result, rctx))
             break;
       }
       while(cursorp->get(&keyPair._key, &keyPair._data, DB_NEXT) == 0);
       rctx._no_more_records = true;
       (session.*callback)(Session::SequencePair(0, ""), rctx);
    }
    else
       glout_warn << "record not found (" << db_strerror(retval) << ')';
    cursorp->close();
    return recs_sent;
 }
bool BDBPersister::get (unsigned & sender_seqnum, unsigned & target_seqnum) const virtual
Retrieve a sequence control record.
Parameters
sender_seqnum sequence number of last sent message
target_seqnum sequence number of last received message
Returns
true on success
Implements FIX8::Persister.
Definition at line 210 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, FIX8::BDBPersister::KeyDataPair::_key, FIX8::BDBPersister::KeyDataBuffer::dataBuf_, and glout_error.
 {
    if (!_opened)
       return false;
    KeyDataBuffer buffer(0, 0);
    KeyDataPair keyPair(buffer);
    int retval(_db->get(0, &keyPair._key, &keyPair._data, 0));
    if (retval)
    {
       glout_error << "Could not get control 0 " << '(' << db_strerror(retval) << ')';
       return false;
    }
    unsigned *loc(reinterpret_cast<unsigned *>(buffer.dataBuf_));
    sender_seqnum = *loc++;
    target_seqnum = *loc;
    return true;
 }
unsigned BDBPersister::get_last_seqnum (unsigned & to) const virtual
Retrieve sequence number of last peristed message.
Parameters
to target sequence number
Returns
sequence number of last peristed message on success
Implements FIX8::Persister.
Definition at line 126 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, FIX8::BDBPersister::KeyDataPair::_key, glout_warn, FIX8::BDBPersister::KeyDataBuffer::Ubuf::int_, and FIX8::BDBPersister::KeyDataBuffer::keyBuf_.
 {
    Dbc *cursorp;
    _db->cursor (0, &cursorp, 0);
    KeyDataBuffer buffer;
    KeyDataPair keyPair(buffer);
    int retval(cursorp->get(&keyPair._key, &keyPair._data, DB_LAST));
    cursorp->close();
    if (retval)
    {
       glout_warn << "last record not found (" << db_strerror(retval) << ')';
       return 0;
    }
    return sequence = buffer.keyBuf_.int_;
 }
bool BDBPersister::initialise (const f8String & dbDir, const f8String & dbFname, bool purge = false) virtual
Open existing database or create new database.
Parameters
dbDir database environment directory
dbFname database name
purge if true, empty database if found
Returns
true on success
Definition at line 50 of file persist.cpp.
References glout_error, and glout_info.
 {
    if (_opened)
       return true;
    _dbDir = dbDir;
    _dbFname = dbFname;
    // Use concurrent db and default shared memory pool
    _dbEnv.open(_dbDir.c_str(), DB_CREATE | DB_INIT_MPOOL | DB_INIT_CDB | DB_THREAD, 0);
    bool notFound(false);
    if (!purge)
    {
       try
       {
          _db->set_bt_compare(bt_compare_fcn);
          _db->open(0, _dbFname.c_str(), 0, DB_BTREE, DB_THREAD, 0); // try and open existing if possible
          unsigned last;
          if (get_last_seqnum(last))
             glout_info << _dbFname << ": Last sequence is " << last;
       }
       catch(DbException& dbe)
       {
          switch (dbe.get_errno())
          {
          case ENOENT:
          case EACCES:
             notFound = true;
             break;
          default:
             glout_error << "Error: opening existing database: " << dbe.what() << " (" << dbe.get_errno() << ')';
             return false;
          }
       }
    }
    if (notFound || purge)  // create a new one
    {
       try
       {
          _db->open(0, _dbFname.c_str(), 0, DB_BTREE, DB_CREATE | DB_THREAD, 0);
          if (purge)
          {
             _db->truncate(0, 0, 0);
             glout_info << "Purged perist db";
          }
       }
       catch(DbException& dbe)
       {
          glout_error << "Error: creating new database: " << dbe.what() << " (" << dbe.get_errno() << ')';
          return false;
       }
       _wasCreated = true;
    }
    _thread.start();
    return _opened = true;
 }
int BDBPersister::operator() ()
Persister thread entry point.
Returns
0 on success
Definition at line 263 of file persist.cpp.
References FIX8::BDBPersister::KeyDataPair::_data, FIX8::BDBPersister::KeyDataPair::_key, FIX8::BDBPersister::KeyDataBuffer::empty(), glout_error, and glout_info.
 {
    unsigned received(0), persisted(0);
    bool stopping(false);
    for (;!_cancellation_token;)
    {
       KeyDataBuffer *msg_ptr(0);
 #if (MPMC_SYSTEM == MPMC_TBB)
       KeyDataBuffer buffer;
       if (stopping)  // make sure we dequeue any pending msgs before exiting
       {
          if (!_persist_queue.try_pop(buffer))
             break;
       }
       else
          _persist_queue.pop (buffer); // will block
       msg_ptr = &buffer;
       if (buffer.empty())  // means exit
       {
          stopping = true;
          continue;
       }
 #else
       _persist_queue.pop(msg_ptr); // will block
       if (msg_ptr->empty())  // means exit
          break;
 #endif
       //cout << "persisted..." << endl;
       ++received;
       if (msg_ptr)
       {
          KeyDataPair keyPair(*msg_ptr);
          int retval(_db->put(0, &keyPair._key, &keyPair._data, 0));  // will overwrite if found
          if (retval)
             glout_error << "Could not add" << '(' << db_strerror(retval) << ')';
          else
             ++persisted;
       }
 #if (MPMC_SYSTEM == MPMC_FF)
       _persist_queue.release(msg_ptr);
 #endif
    }
    //cout << "persister()() exited..." << endl;
    glout_info << received << " messages received, " << persisted << " messages persisted";
    return 0;
 }
bool BDBPersister::put (const unsigned seqnum, const f8String & what) virtual
Persist a message.
Parameters
seqnum sequence number of message
what message string
Returns
true on success
Implements FIX8::Persister.
Definition at line 201 of file persist.cpp.
 {
    if (!_opened || !seqnum)
       return false;
    KeyDataBuffer buffer(seqnum, what);
    return write(buffer);
 }
bool BDBPersister::put (const unsigned sender_seqnum, const unsigned target_seqnum) virtual
Persist a sequence control record.
Parameters
sender_seqnum sequence number of last sent message
target_seqnum sequence number of last received message
Returns
true on success
Implements FIX8::Persister.
Definition at line 192 of file persist.cpp.
 {
    if (!_opened)
       return false;
    KeyDataBuffer buffer(sender_seqnum, target_seqnum);
    return write(buffer);
 }
void FIX8::BDBPersister::stop () inline virtual
Stop the persister thread.
Reimplemented from FIX8::Persister.
Definition at line 279 of file persist.hpp.
References _thread, and write().
 { write(KeyDataBuffer()); _thread.join(); }
bool FIX8::BDBPersister::write (const KeyDataBuffer & what) inline private
Definition at line 214 of file persist.hpp.
References _persist_queue.
Referenced by stop().
    {
       return _persist_queue.try_push(what);
    }
Member Data Documentation
f8_thread_cancellation_token FIX8::BDBPersister::_cancellation_token private
Definition at line 219 of file persist.hpp.
Referenced by cancellation_token().
Db* FIX8::BDBPersister::_db private
Definition at line 154 of file persist.hpp.
f8String FIX8::BDBPersister::_dbDir private
Definition at line 155 of file persist.hpp.
DbEnv FIX8::BDBPersister::_dbEnv private
Definition at line 153 of file persist.hpp.
f8String FIX8::BDBPersister::_dbFname private
Definition at line 155 of file persist.hpp.
f8_concurrent_queue<KeyDataBuffer> FIX8::BDBPersister::_persist_queue private
Definition at line 212 of file persist.hpp.
Referenced by write().
f8_thread<BDBPersister> FIX8::BDBPersister::_thread private
Definition at line 151 of file persist.hpp.
Referenced by stop().
bool FIX8::BDBPersister::_wasCreated private
Definition at line 156 of file persist.hpp.
The documentation for this class was generated from the following files:
persist.hpp
persist.cpp