fix8: FIX8::FieldTraits Class Reference
FIX8::FieldTraits Class Reference
A collection of FieldTraits for a message. Which fields are required, which are present.
#include <traits.hpp>
Public Member Functions
template<typename InputIterator >
FieldTraits (const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array *ftha)
FieldTraits ()
Ctor.
bool has (const unsigned short field, Presence::const_iterator &itr) const
bool has (const unsigned short field) const
unsigned getval (const unsigned short field)
size_t size () const
bool get (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present) const
bool get (const unsigned short field, Presence::const_iterator &itr, FieldTrait::TraitTypes type) const
unsigned short find_missing (FieldTrait::TraitTypes type=FieldTrait::mandatory) const
void set (const unsigned short field, Presence::const_iterator &itr, FieldTrait::TraitTypes type)
void set (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
void clear (const unsigned short field, Presence::const_iterator &itr, FieldTrait::TraitTypes type=FieldTrait::present)
void clear (const unsigned short field, FieldTrait::TraitTypes type=FieldTrait::present)
bool add (const FieldTrait &what)
template<typename InputIterator >
void add (const InputIterator begin, const size_t cnt)
void clear_flag (FieldTrait::TraitTypes type=FieldTrait::present)
bool is_present (const unsigned short field) const
bool is_mandatory (const unsigned short field) const
bool is_group (const unsigned short field, Presence::const_iterator &itr) const
bool is_group (const unsigned short field) const
bool is_component (const unsigned short field) const
unsigned short getComp (const unsigned short field, Presence::const_iterator &itr) const
unsigned short getComp (const unsigned short field) const
unsigned short getPos (const unsigned short field, Presence::const_iterator &itr) const
unsigned short getPos (const unsigned short field) const
const Presence & get_presence () const
Private Attributes
Presence _presence
Friends
F8API std::ostream & operator<< (std::ostream &os, const FieldTraits &what)
Detailed Description
A collection of FieldTraits for a message. Which fields are required, which are present.
Definition at line 437 of file traits.hpp.
Constructor & Destructor Documentation
template<typename InputIterator > FIX8::FieldTraits::FieldTraits (const InputIterator begin, const size_t cnt, const FieldTrait_Hash_Array * ftha) inline
Ctor.
Template Parameters
InputIterator input iterator to construct from
Parameters
begin start iterator to input
cnt number of elements to input
ftha field trait hash array
Definition at line 448 of file traits.hpp.
                                          : _presence(begin, cnt, ftha) {}
FIX8::FieldTraits::FieldTraits () inline
Ctor.
Definition at line 451 of file traits.hpp.
 {}
Member Function Documentation
bool FIX8::FieldTraits::add (const FieldTrait & what) inline
Add a FieldTrait.
Parameters
what TraitType to add
Returns
true on success (false already present)
Definition at line 575 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::insert().
Referenced by FIX8::MessageBase::add_trait(), parse_groups(), and process_message_fields().
 { return _presence.insert(&what).second; }
template<typename InputIterator > void FIX8::FieldTraits::add (const InputIterator begin, const size_t cnt) inline
Add from a range of traits.
Parameters
begin start iterator to input
cnt number of elements to input
Definition at line 581 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::insert().
 { _presence.insert(begin, begin + cnt); }
void FIX8::FieldTraits::clear (const unsigned short field, Presence::const_iterator & itr, FieldTrait::TraitTypes type = FieldTrait::present) inline
Clear a trait for a specified field.
Parameters
field to set
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
type TraitType to set (default present)
Definition at line 550 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::ebitset< T, B >::clear(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
Referenced by process_special_traits().
    {
       if (itr == _presence.end())
       {
          itr = _presence.find(field);
          if (itr != _presence.end())
             itr->_field_traits.clear(type);
       }
       else
          itr->_field_traits.clear(type);
    }
void FIX8::FieldTraits::clear (const unsigned short field, FieldTrait::TraitTypes type = FieldTrait::present) inline
Clear a trait for a specified field.
Parameters
field to set
type TraitType to set (default present)
Definition at line 565 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::ebitset< T, B >::clear(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
    {
       Presence::iterator itr(_presence.find(field));
       if (itr != _presence.end())
          itr->_field_traits.clear(type);
    }
void FIX8::FieldTraits::clear_flag (FieldTrait::TraitTypes type = FieldTrait::present) inline
Clear a trait from all traits.
Parameters
type TraitType to clear
Definition at line 585 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin(), FIX8::ebitset< T, B >::clear(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end().
Referenced by FIX8::MessageBase::clear().
       { for (Presence::const_iterator itr(_presence.begin()); itr != _presence.end(); itr++->_field_traits.clear(type)); }
unsigned short FIX8::FieldTraits::find_missing (FieldTrait::TraitTypes type = FieldTrait::mandatory) const inline
Find the first field that does not have the specified trait.
Parameters
type TraitType to check (default mandatory)
Returns
field number of field, 0 if none
Definition at line 512 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::FieldTrait::present.
    {
       for (Presence::const_iterator itr(_presence.begin()); itr != _presence.end(); ++itr)
          if ((itr->_field_traits & type) && (itr->_field_traits & FieldTrait::present) == 0)
             return itr->_fnum;
       return 0;
    }
bool FIX8::FieldTraits::get (const unsigned short field, FieldTrait::TraitTypes type = FieldTrait::present) const inline
Check if a field has a specified trait.
Parameters
field to check
type TraitType to check (default present)
Returns
true if field has trait
Definition at line 490 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), and FIX8::ebitset< T, B >::has().
Referenced by FIX8::MessageBase::add_field(), FIX8::MessageBase::copy_legal(), FIX8::MessageBase::has(), FIX8::MessageBase::have(), and FIX8::MessageBase::move_legal().
    {
       Presence::const_iterator itr(_presence.find(field));
       return itr != _presence.end() ? itr->_field_traits.has(type) : false;
    }
bool FIX8::FieldTraits::get (const unsigned short field, Presence::const_iterator & itr, FieldTrait::TraitTypes type) const inline
Check if a field has a specified trait.
Parameters
field to check
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
type TraitType to check (default present)
Returns
true if field has trait
Definition at line 501 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), and FIX8::ebitset< T, B >::has().
    {
       if (itr != _presence.end())
          return itr->_field_traits.has(type);
       itr = _presence.find(field);
       return itr != _presence.end() ? itr->_field_traits.has(type) : false;
    }
const Presence& FIX8::FieldTraits::get_presence () const inline
Get the Presence set
Returns
the Presence set
Definition at line 658 of file traits.hpp.
References _presence.
Referenced by FIX8::MessageBase::add_field(), FIX8::MessageBase::copy_legal(), FIX8::ConsoleMenu::EditMsg(), generate_group_bodies(), generate_group_traits(), group_hash(), FIX8::operator<<(), and FIX8::ConsoleMenu::SelectField().
 { return _presence; }
unsigned short FIX8::FieldTraits::getComp (const unsigned short field, Presence::const_iterator & itr) const inline
Get the field component index of a specified field.
Parameters
field field to get
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
Returns
index of component of field, 0 if not found
Definition at line 618 of file traits.hpp.
References FIX8::FieldTrait::_component, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
    {
       if (itr != _presence.end())
          return itr->_component;
       itr = _presence.find(field);
       return itr != _presence.end() ? itr->_component : 0;
    }
unsigned short FIX8::FieldTraits::getComp (const unsigned short field) const inline
Get the field component index of a specified field.
Parameters
field field to get
Returns
index of component of field, 0 if not found
Definition at line 629 of file traits.hpp.
References FIX8::FieldTrait::_component, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
    {
       Presence::const_iterator itr(_presence.find(field));
       return itr != _presence.end() ? itr->_component : 0;
    }
unsigned short FIX8::FieldTraits::getPos (const unsigned short field, Presence::const_iterator & itr) const inline
Get the field position of a specified field.
Parameters
field field to get
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
Returns
position of field, 0 if no pos or not found
Definition at line 639 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::FieldTrait::_pos, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), FIX8::ebitset< T, B >::has(), and FIX8::FieldTrait::position.
Referenced by FIX8::MessageBase::add_field(), and FIX8::MessageBase::getPos().
    {
       if (itr != _presence.end())
          return itr->_field_traits.has(FieldTrait::position) ? itr->_pos : 0;
       itr = _presence.find(field);
       return itr != _presence.end() && itr->_field_traits.has(FieldTrait::position) ? itr->_pos : 0;
    }
unsigned short FIX8::FieldTraits::getPos (const unsigned short field) const inline
Get the field position of a specified field.
Parameters
field field to get
Returns
position of field, 0 if no pos or not found
Definition at line 650 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), FIX8::ebitset< T, B >::has(), and FIX8::FieldTrait::position.
    {
       Presence::const_iterator itr(_presence.find(field));
       return itr != _presence.end() && itr->_field_traits.has(FieldTrait::position) ? itr->_pos : 0;
    }
unsigned FIX8::FieldTraits::getval (const unsigned short field) inline
Get the traits for a field.
Parameters
field to get
Returns
traits as an unsigned short
Definition at line 476 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), and FIX8::ebitset< T, B >::get().
    {
       Presence::const_iterator itr(_presence.find(field));
       return itr != _presence.end() ? itr->_field_traits.get() : 0;
    }
bool FIX8::FieldTraits::has (const unsigned short field, Presence::const_iterator & itr) const inline
Check if a field is present
Parameters
field to check
itr hint iterator: set to itr of found element
Returns
true if present
Definition at line 457 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
Referenced by FIX8::MessageBase::add_field(), FIX8::MessageBase::copy_legal(), FIX8::MessageBase::is_legal(), and FIX8::MessageBase::move_legal().
    {
       if (itr == _presence.end())
          itr = _presence.find(field);
       return itr != _presence.end();
    }
bool FIX8::FieldTraits::has (const unsigned short field) const inline
Check if a field is present
Parameters
field to check
Returns
true if present
Definition at line 467 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find().
    {
       Presence::const_iterator itr(_presence.find(field));
       return itr != _presence.end();
    }
bool FIX8::FieldTraits::is_component (const unsigned short field) const inline
Check if a specified field has the component bit set (is a component).
Parameters
field field to check
Returns
true if a component
Definition at line 612 of file traits.hpp.
References FIX8::FieldTrait::component.
 { return get(field, FieldTrait::component); }
bool FIX8::FieldTraits::is_group (const unsigned short field, Presence::const_iterator & itr) const inline
Check if a specified field has the group bit set (is a group).
Parameters
field field to check
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
Returns
true if a group
Definition at line 602 of file traits.hpp.
References FIX8::FieldTrait::group.
Referenced by FIX8::ConsoleMenu::EditMsg().
 { return get(field, itr, FieldTrait::group); }
bool FIX8::FieldTraits::is_group (const unsigned short field) const inline
Check if a specified field has the group bit set (is a group).
Parameters
field field to check
Returns
true if a group
Definition at line 607 of file traits.hpp.
References FIX8::FieldTrait::group.
 { return get(field, FieldTrait::group); }
bool FIX8::FieldTraits::is_mandatory (const unsigned short field) const inline
Check if a specified field has the mandator bit set.
Parameters
field field to check
Returns
true if mandatory set
Definition at line 596 of file traits.hpp.
References FIX8::FieldTrait::mandatory.
Referenced by FIX8::ConsoleMenu::SelectField().
 { return get(field, FieldTrait::mandatory); }
bool FIX8::FieldTraits::is_present (const unsigned short field) const inline
Check if a specified field has the present bit set (is present).
Parameters
field field to check
Returns
true if present
Definition at line 591 of file traits.hpp.
References FIX8::FieldTrait::present.
 { return get(field, FieldTrait::present); }
void FIX8::FieldTraits::set (const unsigned short field, Presence::const_iterator & itr, FieldTrait::TraitTypes type) inline
Set a trait for a specified field.
Parameters
field to set
itr hint iterator: if end, set to itr of found element, if not end use it to locate element
type TraitType to set (default present)
Definition at line 524 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), and FIX8::ebitset< T, B >::set().
Referenced by FIX8::MessageBase::add_field(), process_special_traits(), FIX8::MessageBase::set(), and FIX8::Message::setup_reuse().
    {
       if (itr == _presence.end())
       {
          itr = _presence.find(field);
          if (itr != _presence.end())
             itr->_field_traits.set(type);
       }
       else
          itr->_field_traits.set(type);
    }
void FIX8::FieldTraits::set (const unsigned short field, FieldTrait::TraitTypes type = FieldTrait::present) inline
Set a trait for a specified field.
Parameters
field to set
type TraitType to set (default present)
Definition at line 539 of file traits.hpp.
References FIX8::FieldTrait::_field_traits, FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::find(), and FIX8::ebitset< T, B >::set().
    {
       Presence::iterator itr(_presence.find(field));
       if (itr != _presence.end())
          itr->_field_traits.set(type);
    }
size_t FIX8::FieldTraits::size () const inline
Get the number of possible fields
Returns
number of fields
Definition at line 484 of file traits.hpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::size().
Referenced by FIX8::MessageBase::size().
 { return _presence.size(); }
Friends And Related Function Documentation
F8API std::ostream& operator<< (std::ostream & os, const FieldTraits & what) friend
Inserter friend.
Parameters
os stream to send to
what FieldTraits
Returns
stream
Member Data Documentation
Presence FIX8::FieldTraits::_presence private
Definition at line 439 of file traits.hpp.
Referenced by get_presence().
The documentation for this class was generated from the following file:
traits.hpp