fix8: FIX8::Tickval Class Reference
FIX8::Tickval Class Reference
#include <tickval.hpp>
Public Types
using f8_time_point = std::chrono::time_point< std::chrono::high_resolution_clock >
using ticks = decltype(f8_time_point::min().time_since_epoch().count())
using duration = f8_time_point::duration
Public Member Functions
Tickval (bool settonow=false)
Tickval (const Tickval &from)
Tickval (ticks from)
Tickval (f8_time_point from)
Tickval (time_t secs, long nsecs)
Tickval & operator= (const Tickval &that)
Tickval & operator= (ticks that)
ticks get_ticks () const
Tickval & now ()
time_t secs () const
unsigned msecs () const
unsigned usecs () const
unsigned nsecs () const
double todouble () const
bool is_errorval () const
bool in_range (const Tickval &a, const Tickval &b) const
Tickval & adjust (ticks by)
struct tm * as_tm (struct tm &result) const
struct tm get_tm () const
void set (time_t secs, long nsecs)
bool operator! () const
operator void * ()
operator Tickval::ticks ()
operator double ()
Static Public Member Functions
static Tickval get_tickval ()
static Tickval & get_tickval (Tickval &to)
Static Public Attributes
static const ticks noticks = 0
static const ticks errorticks = f8_time_point::max().time_since_epoch().count()
static const ticks thousand = 1000
static const ticks million = thousand * thousand
static const ticks billion = thousand * million
static const ticks second = billion
static const ticks minute = 60 * second
static const ticks hour = 60 * minute
static const ticks day = 24 * hour
static const ticks week = 7 * day
Private Attributes
f8_time_point _value
Friends
Tickval operator- (const Tickval &newtime, const Tickval &oldtime)
Tickval & operator-= (Tickval &oldtime, const Tickval &newtime)
Tickval operator+ (const Tickval &newtime, const Tickval &oldtime)
Tickval & operator+= (Tickval &oldtime, const Tickval &newtime)
bool operator== (const Tickval &a, const Tickval &b)
bool operator!= (const Tickval &a, const Tickval &b)
bool operator> (const Tickval &a, const Tickval &b)
bool operator< (const Tickval &a, const Tickval &b)
bool operator>= (const Tickval &a, const Tickval &b)
bool operator<= (const Tickval &a, const Tickval &b)
Tickval & operator+= (Tickval &oldtime, ticks ns)
Tickval & operator-= (Tickval &oldtime, ticks ns)
std::ostream & operator<< (std::ostream &os, const Tickval &what)
std::ostream & operator>> (std::ostream &os, const Tickval &what)
Detailed Description
High resolution time in nanosecond ticks. Thread safe. Portable, based on std::chrono Assumes we support nanosecond resolution. For implementations that don't, there will be inaccuracies: Windows 7 supports up to 15ms resolution only; for Windows 8 it is 100ns. Linux x86_64 is 1ns.
Definition at line 55 of file tickval.hpp.
Member Typedef Documentation
using FIX8::Tickval::duration = f8_time_point::duration
Definition at line 60 of file tickval.hpp.
using FIX8::Tickval::f8_time_point = std::chrono::time_point<std::chrono::high_resolution_clock>
Definition at line 58 of file tickval.hpp.
using FIX8::Tickval::ticks = decltype(f8_time_point::min().time_since_epoch().count())
Definition at line 59 of file tickval.hpp.
Constructor & Destructor Documentation
FIX8::Tickval::Tickval (bool settonow = false) inline explicit
Ctor.
Parameters
settonow if true, construct with current time
Definition at line 84 of file tickval.hpp.
Referenced by get_tickval(), and set().
       : _value(settonow ? std::chrono::high_resolution_clock::now() : f8_time_point(f8_time_point::duration::zero())) {}
FIX8::Tickval::Tickval (const Tickval & from) inline
Copy Ctor.
Definition at line 88 of file tickval.hpp.
 : _value(from._value) {}
FIX8::Tickval::Tickval (ticks from) inline explicit
Ctor.
Parameters
from construct from raw ticks value (nanoseconds)
Definition at line 92 of file tickval.hpp.
 : _value(std::chrono::duration_cast<duration>(std::chrono::nanoseconds(from))) {}
FIX8::Tickval::Tickval (f8_time_point from) inline explicit
Ctor.
Parameters
from construct from time_point value
Definition at line 96 of file tickval.hpp.
 : _value(from) {}
FIX8::Tickval::Tickval (time_t secs, long nsecs) inline
Ctor.
Parameters
secs seconds
nsecs nanoseconds
Definition at line 101 of file tickval.hpp.
       : _value(std::chrono::high_resolution_clock::from_time_t(secs) + std::chrono::duration_cast<duration>(std::chrono::nanoseconds(nsecs))) {}
Member Function Documentation
Tickval& FIX8::Tickval::adjust (ticks by) inline
Adjust Tickval by given value
Parameters
by amount to adjust; if +ve add, if -ve sub
Returns
adjusted Tickval
Definition at line 181 of file tickval.hpp.
Referenced by FIX8::Schedule::test().
 { return *this += by; }
struct tm* FIX8::Tickval::as_tm (struct tm & result) const inline
Get tickval as struct tm
Parameters
result ref to struct tm to fill
Returns
ptr to result
Definition at line 194 of file tickval.hpp.
References _value.
Referenced by get_tm().
    {
       const time_t insecs(std::chrono::system_clock::to_time_t(_value));
 #ifdef _MSC_VER
       gmtime_s(&result, &insecs);
 #else
       gmtime_r(&insecs, &result);
 #endif
       return &result;
    }
ticks FIX8::Tickval::get_ticks () const inline
Get the raw tick value (nanosecs).
Returns
raw ticks
Definition at line 123 of file tickval.hpp.
References _value.
Referenced by FIX8::Configuration::create_schedule(), FIX8::date_parse(), FIX8::date_time_parse(), is_errorval(), FIX8::Timer< T >::operator()(), FIX8::Schedule::test(), and FIX8::time_parse().
 { return std::chrono::duration_cast<std::chrono::nanoseconds>(_value.time_since_epoch()).count(); }
static Tickval FIX8::Tickval::get_tickval () inline static
Generate a Tickval object, constructed with the current time.
Returns
Tickval
Definition at line 185 of file tickval.hpp.
References Tickval().
Referenced by FIX8::Timer< T >::operator()(), and FIX8::Timer< T >::schedule().
 { return Tickval(true); }
static Tickval& FIX8::Tickval::get_tickval (Tickval & to) inline static
Assign current time to a given Tickval object.
Returns
target Tickval object
Definition at line 189 of file tickval.hpp.
References Tickval().
 { return to = Tickval(true); }
struct tm FIX8::Tickval::get_tm () const inline
Get tickval as struct tm
Returns
tm structure
Definition at line 207 of file tickval.hpp.
References as_tm().
Referenced by FIX8::date_time_format(), and FIX8::Schedule::test().
    {
       struct tm result;
       return *as_tm(result);
    }
bool FIX8::Tickval::in_range (const Tickval & a, const Tickval & b) const inline
See if this Tickval is within the range given
Parameters
a lower boundary
b upper boundary; if an error value, ignore upper range
Returns
true if in range
Definition at line 173 of file tickval.hpp.
References is_errorval().
Referenced by FIX8::Schedule::test().
    {
       return !b.is_errorval() ? a <= *this && *this <= b : a <= *this;
    }
bool FIX8::Tickval::is_errorval () const inline
See if this Tickval holds an error value
Returns
true if an error value
Definition at line 167 of file tickval.hpp.
References errorticks, and get_ticks().
Referenced by FIX8::Configuration::create_schedule(), in_range(), and FIX8::Schedule::is_valid().
 { return get_ticks() == errorticks; }
unsigned FIX8::Tickval::msecs () const inline
Get the current number of elapsed milliseconds (excluding secs)
Returns
value in milliseconds
Definition at line 139 of file tickval.hpp.
References _value.
Referenced by FIX8::date_time_format(), FIX8::Logger::process_logline(), and FIX8::XmlFileLogger::process_logline().
    {
       return std::chrono::duration_cast<std::chrono::milliseconds>(_value.time_since_epoch()).count() % std::milli::den;
    }
Tickval& FIX8::Tickval::now () inline
Assign the current time to this object.
Returns
current object
Definition at line 127 of file tickval.hpp.
References _value.
Referenced by FIX8::GetTimeAsStringMini(), FIX8::GetTimeAsStringMS(), FIX8::Session::heartbeat_service(), FIX8::IntervalTimer::Reset(), FIX8::Session::send_process(), FIX8::Session::update_received(), and FIX8::Session::update_sent().
    {
       _value = std::chrono::high_resolution_clock::now();
       return *this;
    }
unsigned FIX8::Tickval::nsecs () const inline
Get the current number of elapsed nanoseconds (excluding secs)
Returns
value in nanoseconds
Definition at line 153 of file tickval.hpp.
References _value.
Referenced by FIX8::GetTimeAsStringMS().
    {
       return std::chrono::duration_cast<std::chrono::nanoseconds>(_value.time_since_epoch()).count() % std::nano::den;
    }
FIX8::Tickval::operator double () inline
Cast to double.
Returns
ticks as double
Definition at line 232 of file tickval.hpp.
References todouble().
 { return todouble(); }
FIX8::Tickval::operator Tickval::ticks () inline
Cast to unsigned long long.
Returns
ticks as unsigned long long
Definition at line 228 of file tickval.hpp.
References _value.
 { return _value.time_since_epoch().count(); }
FIX8::Tickval::operator void * () inline
Not 0 operator
Returns
true if ticks
Definition at line 224 of file tickval.hpp.
References _value.
 { return _value.time_since_epoch() == std::chrono::nanoseconds::zero() ? nullptr : this; }
bool FIX8::Tickval::operator! () const inline
Not operator
Returns
true if no ticks (0)
Definition at line 220 of file tickval.hpp.
References _value.
 { return _value.time_since_epoch() == std::chrono::nanoseconds::zero(); }
Tickval& FIX8::Tickval::operator= (const Tickval & that) inline
Assignment operator.
Definition at line 105 of file tickval.hpp.
References _value.
    {
       if (this != &that)
          _value = that._value;
       return *this;
    }
Tickval& FIX8::Tickval::operator= (ticks that) inline
Assignment operator from ticks
Parameters
that ticks to assign from
Returns
*this
Definition at line 115 of file tickval.hpp.
References _value.
    {
       _value = f8_time_point(std::chrono::duration_cast<duration>(std::chrono::nanoseconds(that)));
       return *this;
    }
time_t FIX8::Tickval::secs () const inline
Get the current number of elapsed seconds
Returns
value in seconds
Definition at line 135 of file tickval.hpp.
References _value.
Referenced by FIX8::GetTimeAsStringMini(), FIX8::GetTimeAsStringMS(), FIX8::Session::heartbeat_service(), FIX8::Logger::process_logline(), and FIX8::XmlFileLogger::process_logline().
 { return std::chrono::duration_cast<std::chrono::seconds>(_value.time_since_epoch()).count(); }
void FIX8::Tickval::set (time_t secs, long nsecs) inline
Set from secs/nsecs
Parameters
secs seconds
nsecs nanoseconds
Definition at line 216 of file tickval.hpp.
References _value, and Tickval().
 { _value = Tickval(secs, nsecs)._value; }
double FIX8::Tickval::todouble () const inline
Get the current tickval as a double.
Returns
value as a double
Definition at line 160 of file tickval.hpp.
References _value.
Referenced by FIX8::IntervalTimer::AsDouble(), and operator double().
    {
       return static_cast<double>(std::chrono::duration_cast<std::chrono::nanoseconds>(_value.time_since_epoch()).count()) / std::nano::den;
    }
unsigned FIX8::Tickval::usecs () const inline
Get the current number of elapsed microseconds (excluding secs)
Returns
value in microseconds
Definition at line 146 of file tickval.hpp.
References _value.
    {
       return std::chrono::duration_cast<std::chrono::microseconds>(_value.time_since_epoch()).count() % std::micro::den;
    }
Friends And Related Function Documentation
bool operator!= (const Tickval & a, const Tickval & b) friend
Inequivalence operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if not equal
Definition at line 278 of file tickval.hpp.
 { return a._value != b._value; }
Tickval operator+ (const Tickval & newtime, const Tickval & oldtime) friend
Binary addition operator.
Parameters
newtime Tickval to add to
oldtime Tickval to add
Returns
Result as Tickval
Definition at line 255 of file tickval.hpp.
       { return Tickval(newtime._value + oldtime._value.time_since_epoch()); }
Tickval& operator+= (Tickval & oldtime, const Tickval & newtime) friend
Binary addition operator.
Parameters
newtime Tickval to add to
oldtime Tickval to add
Returns
resulting oldtime
Definition at line 262 of file tickval.hpp.
    {
       oldtime._value += newtime._value.time_since_epoch();
       return oldtime;
    }
Tickval& operator+= (Tickval & oldtime, ticks ns) friend
Binary addition operator.
Parameters
oldtime Tickval to add to
ns ticks to add
Returns
oldtime as Tickval
Definition at line 308 of file tickval.hpp.
    {
       oldtime._value += std::chrono::duration_cast<duration>(std::chrono::nanoseconds(ns));
       return oldtime;
    }
Tickval operator- (const Tickval & newtime, const Tickval & oldtime) friend
Binary negate operator.
Parameters
newtime Tickval to subtract from
oldtime Tickval to subtract
Returns
Result as Tickval
Definition at line 238 of file tickval.hpp.
       { return Tickval(newtime._value - oldtime._value.time_since_epoch()); }
Tickval& operator-= (Tickval & oldtime, const Tickval & newtime) friend
Binary negate operator.
Parameters
newtime Tickval to subtract from
oldtime Tickval to subtract
Returns
resulting oldtime
Definition at line 245 of file tickval.hpp.
    {
       oldtime._value -= newtime._value.time_since_epoch();
       return oldtime;
    }
Tickval& operator-= (Tickval & oldtime, ticks ns) friend
Binary negate operator.
Parameters
oldtime Tickval to subtract from
ns Tickval to subtract
Returns
oldtime as Tickval
Definition at line 318 of file tickval.hpp.
    {
       oldtime._value -= std::chrono::duration_cast<duration>(std::chrono::nanoseconds(ns));
       return oldtime;
    }
bool operator< (const Tickval & a, const Tickval & b) friend
Less than operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if a is less than b
Definition at line 290 of file tickval.hpp.
 { return a._value < b._value; }
std::ostream& operator<< (std::ostream & os, const Tickval & what) friend
ostream inserter friend; Tickval printer, localtime
Parameters
os stream to insert into
what Tickval to insert
Returns
ostream object
Definition at line 328 of file tickval.hpp.
    {
       std::string result;
       return os << GetTimeAsStringMS(result, &what, 9, false);
    }
bool operator<= (const Tickval & a, const Tickval & b) friend
Less than or equal to operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if a is less than or equal to b
Definition at line 302 of file tickval.hpp.
 { return a._value <= b._value; }
bool operator== (const Tickval & a, const Tickval & b) friend
Equivalence operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if equal
Definition at line 272 of file tickval.hpp.
 { return a._value == b._value; }
bool operator> (const Tickval & a, const Tickval & b) friend
Greater than operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if a is greater than b
Definition at line 284 of file tickval.hpp.
 { return a._value > b._value; }
bool operator>= (const Tickval & a, const Tickval & b) friend
Greater than or equal to operator.
Parameters
a lhs Tickval
b rhs Tickval
Returns
true if a is greater than or equal to b
Definition at line 296 of file tickval.hpp.
 { return a._value >= b._value; }
std::ostream& operator>> (std::ostream & os, const Tickval & what) friend
ostream inserter friend; Tickval printer, gmtime
Parameters
os stream to insert into
what Tickval to insert
Returns
ostream object
Definition at line 338 of file tickval.hpp.
    {
       std::string result;
       return os << GetTimeAsStringMS(result, &what, 9, true);
    }
Member Data Documentation
f8_time_point FIX8::Tickval::_value private
Definition at line 79 of file tickval.hpp.
Referenced by as_tm(), get_ticks(), msecs(), now(), nsecs(), operator Tickval::ticks(), operator void *(), operator!(), operator=(), secs(), set(), todouble(), and usecs().
const ticks FIX8::Tickval::billion = thousand * million static
Definition at line 71 of file tickval.hpp.
Referenced by FIX8::date_parse(), FIX8::date_time_parse(), and FIX8::time_parse().
const ticks FIX8::Tickval::day = 24 * hour static
Definition at line 75 of file tickval.hpp.
Referenced by FIX8::Schedule::test().
const ticks FIX8::Tickval::errorticks = f8_time_point::max().time_since_epoch().count() static
Definition at line 67 of file tickval.hpp.
Referenced by FIX8::Configuration::get_time_field(), and is_errorval().
const ticks FIX8::Tickval::hour = 60 * minute static
Definition at line 74 of file tickval.hpp.
const ticks FIX8::Tickval::million = thousand * thousand static
Definition at line 70 of file tickval.hpp.
Referenced by FIX8::date_time_parse(), FIX8::Timer< T >::operator()(), FIX8::Timer< T >::schedule(), and FIX8::time_parse().
const ticks FIX8::Tickval::minute = 60 * second static
Definition at line 73 of file tickval.hpp.
Referenced by FIX8::Configuration::create_schedule().
const ticks FIX8::Tickval::noticks = 0 static
Definition at line 61 of file tickval.hpp.
Referenced by FIX8::date_time_parse(), and FIX8::time_parse().
const ticks FIX8::Tickval::second = billion static
Definition at line 72 of file tickval.hpp.
const ticks FIX8::Tickval::thousand = 1000 static
Definition at line 69 of file tickval.hpp.
const ticks FIX8::Tickval::week = 7 * day static
Definition at line 76 of file tickval.hpp.
The documentation for this class was generated from the following file:
tickval.hpp