fix8: ff::zmqTransport Class Reference
ff::zmqTransport Class Reference
This class describes the transport layer used in a distributed FastFlow environment.
#include <zmqTransport.hpp>
Public Types
typedef zmq::socket_t endpoint_t
typedef zmqTransportMsg_t msg_t
Public Member Functions
zmqTransport (const int procId)
~zmqTransport ()
int initTransport ()
int closeTransport ()
endpoint_t * newEndPoint (const bool P)
int deleteEndPoint (endpoint_t *s)
int getProcId () const
Protected Member Functions
int closeConnections ()
Protected Attributes
const int procId
zmq::context_t * context
std::deque< endpoint_t * > Socks
Private Types
enum { NUM_IO_THREADS =1 }
Detailed Description
This class describes the transport layer used in a distributed FastFlow environment.
This class is defined in zmqTransport.hpp
Definition at line 160 of file zmqTransport.hpp.
Member Typedef Documentation
typedef zmq::socket_t ff::zmqTransport::endpoint_t
It defines zmq::socket_t.
Definition at line 195 of file zmqTransport.hpp.
typedef zmqTransportMsg_t ff::zmqTransport::msg_t
It defines zmqTransportMsg_t.
Definition at line 200 of file zmqTransport.hpp.
Member Enumeration Documentation
anonymous enum private
NUM_IO_THREADS is the enumberation of the number of IO threads.
Enumerator
NUM_IO_THREADS
Definition at line 165 of file zmqTransport.hpp.
Constructor & Destructor Documentation
ff::zmqTransport::zmqTransport (const int procId) inline
It constructs a transport connection.
Parameters
procId is the process (or thread) ID.
Definition at line 207 of file zmqTransport.hpp.
ff::zmqTransport::~zmqTransport () inline
It closes the transport connection.
Definition at line 214 of file zmqTransport.hpp.
References closeTransport().
Member Function Documentation
int ff::zmqTransport::closeConnections () inline protected
It closes all existing connections.
Returns
It returns 0 to show the successful closing of connection.
Definition at line 174 of file zmqTransport.hpp.
References Socks.
Referenced by closeTransport(), and initTransport().
int ff::zmqTransport::closeTransport () inline
It closes the transport layer, close all connections to any active end-point and delete the existing context.
Returns
0 is returned to show the successful closing of transport connection.
Definition at line 237 of file zmqTransport.hpp.
References closeConnections(), and context.
Referenced by ~zmqTransport().
int ff::zmqTransport::deleteEndPoint (endpoint_t * s) inline
It deletes the socket pointed by s. It removes the socket from the list of active sockets and destroys the socket.
Parameters
s is a pointer to the socket to be deleted.
Returns
0 if successful; otherwise a negative value is returned.
Definition at line 270 of file zmqTransport.hpp.
References Socks.
Referenced by ff::descriptor1_N::close(), and ff::descriptorN_1::close().
int ff::zmqTransport::getProcId () const inline
It retrieves the process (or thread) ID.
Returns
the process (or thread) ID
Definition at line 293 of file zmqTransport.hpp.
References procId.
Referenced by ff::descriptor1_N::init(), and ff::descriptorN_1::init().
int ff::zmqTransport::initTransport () inline
It initializes the transport layer: creates a new ØMQ context and cleans the list of active end-points.
Returns
If successful 0, otherwise a negative value is returned.
Definition at line 222 of file zmqTransport.hpp.
References closeConnections(), context, NUM_IO_THREADS, and Socks.
endpoint_t* ff::zmqTransport::newEndPoint (const bool P) inline
It creates a new socket and pushes it into the active sockets list.
Parameters
P is a flag to specify the role of the socket: if false, the new socket acts as a ROUTER (allows routing of messages to specific connections); if true the new socket acts as a DEALER (used for fair-queuing on input and for performing load-balancing on output toward a pool of collections).
Returns
If successful a pointer s to the newly created endpoint is reutned otherwise NULL is returned.
Definition at line 255 of file zmqTransport.hpp.
References context, and Socks.
Referenced by ff::descriptor1_N::descriptor1_N(), and ff::descriptorN_1::descriptorN_1().
Member Data Documentation
zmq::context_t* ff::zmqTransport::context protected
Definition at line 297 of file zmqTransport.hpp.
Referenced by closeTransport(), initTransport(), and newEndPoint().
const int ff::zmqTransport::procId protected
Definition at line 296 of file zmqTransport.hpp.
Referenced by getProcId().
std::deque<endpoint_t *> ff::zmqTransport::Socks protected
Definition at line 300 of file zmqTransport.hpp.
Referenced by closeConnections(), deleteEndPoint(), initTransport(), and newEndPoint().
The documentation for this class was generated from the following file:
zmqTransport.hpp