fix8: Environment Class Reference
Environment Class Reference
TODO.
#include <clEnvironment.hpp>
Private Member Functions
Environment (Environment const &)
Environment & operator= (Environment const &)
Private Attributes
std::vector< int > clNodesDevice
std::vector< CLDevice * > clDevices
pthread_mutex_t mutex_set_policy
int nodeId
static Environment * m_Environment = NULL
Environment ()
int staticSelectionPolicy (cl_device_type, Ocl_Utilities *)
cl_device_id getDeviceId (int)
void createEntry (int &, Ocl_Utilities *)
cl_device_id reallocation (int)
static Environment * instance ()
Detailed Description
TODO.
This class is defined in clEnvironment.hpp
Definition at line 65 of file clEnvironment.hpp.
Constructor & Destructor Documentation
Environment::Environment () private
TODO
Definition at line 51 of file clEnvironment.cpp.
References clDevices, CLDevice::d_type, CLDevice::deviceId, CLDevice::maxNum, mutex_set_policy, nodeId, pthread_mutex_init(), CLDevice::runningApp, and THRESHOLD.
Referenced by instance().
Environment::Environment (Environment const &) inline private
Definition at line 76 of file clEnvironment.hpp.
Member Function Documentation
void Environment::createEntry (int & t_id, Ocl_Utilities * ocl_utilities)
TODO
Definition at line 150 of file clEnvironment.cpp.
References clDevices, clNodesDevice, instance(), mutex_set_policy, nodeId, pthread_mutex_lock(), pthread_mutex_unlock(), and staticSelectionPolicy().
Referenced by ff::ff_oclNode::initOCLInstance().
cl_device_id Environment::getDeviceId (int t_id)
TODO
Definition at line 143 of file clEnvironment.cpp.
References clDevices, clNodesDevice, and instance().
Referenced by ff::ff_oclNode::initOCLInstance().
Environment * Environment::instance () static
TODO
Definition at line 130 of file clEnvironment.cpp.
References Environment(), instanceMutex, m_Environment, pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by createEntry(), ff::ff_oclNode::evaluation(), getDeviceId(), ff::ff_oclNode::initOCLInstance(), reallocation(), and staticSelectionPolicy().
Environment& Environment::operator= (Environment const &) inline private
Definition at line 77 of file clEnvironment.hpp.
cl_device_id Environment::reallocation (int t_id)
TODO
Definition at line 122 of file clEnvironment.cpp.
References clDevices, clNodesDevice, and instance().
Referenced by ff::ff_oclNode::evaluation().
int Environment::staticSelectionPolicy (cl_device_type d, Ocl_Utilities * ocl_utilities) private
TODO
Definition at line 104 of file clEnvironment.cpp.
References clDevices, Ocl_Utilities::device_rules(), and instance().
Referenced by createEntry().
Member Data Documentation
std::vector<CLDevice*> Environment::clDevices private
Definition at line 71 of file clEnvironment.hpp.
Referenced by createEntry(), Environment(), getDeviceId(), reallocation(), and staticSelectionPolicy().
std::vector<int> Environment::clNodesDevice private
Definition at line 70 of file clEnvironment.hpp.
Referenced by createEntry(), getDeviceId(), and reallocation().
Environment * Environment::m_Environment = NULL static private
Definition at line 69 of file clEnvironment.hpp.
Referenced by instance().
pthread_mutex_t Environment::mutex_set_policy private
Definition at line 72 of file clEnvironment.hpp.
Referenced by createEntry(), and Environment().
int Environment::nodeId private
Definition at line 73 of file clEnvironment.hpp.
Referenced by createEntry(), and Environment().
The documentation for this class was generated from the following files:
clEnvironment.hpp
clEnvironment.cpp