fix8: FIX8::Configuration Class Reference
FIX8::Configuration Class Reference
Class to encapsulate a Fix8 configuration.
#include <configuration.hpp>
Public Types
enum group_types {
g_sessions, g_persisters, g_loggers, g_server_group,
g_ssl_context, g_schedules, g_logins, g_client_group,
g_count
}
enum Logtype { session_log, protocol_log }
Public Member Functions
const XmlElement * find_group (group_types type, const std::string &tag) const
Configuration (const std::string &xmlfile, bool do_process=false)
Configuration (std::istream &istr, bool do_process=false)
virtual ~Configuration ()
Dtor.
F8API int process ()
const XmlElement * get_session (const unsigned num) const
F8API Connection::Role get_role (const XmlElement *from) const
F8API size_t get_addresses (const XmlElement *from, std::vector< Server > &target) const
F8API Poco::Net::SocketAddress get_address (const XmlElement *from) const
F8API Poco::Net::IPAddress get_ip (const XmlElement *from) const
template<typename T >
T get_logflags (const std::string &tag, const std::vector< std::string > &names, const XmlElement *from, Logger::LogPositions *positions=nullptr) const
F8API std::string & get_logname (const XmlElement *from, std::string &to, const SessionID *sid=nullptr) const
unsigned get_connect_timeout (const XmlElement *from, const unsigned def=defaults::connect_timeout) const
unsigned get_retry_interval (const XmlElement *from, const unsigned def=defaults::retry_interval) const
unsigned get_retry_count (const XmlElement *from, const unsigned def=defaults::login_retries) const
unsigned get_tcp_recvbuf_sz (const XmlElement *from, const unsigned def=0) const
unsigned get_tcp_sendbuf_sz (const XmlElement *from, const unsigned def=0) const
unsigned get_version (const XmlElement *from, const unsigned def=0) const
unsigned get_tabsize (const XmlElement *from, const unsigned def=defaults::tabsize) const
unsigned get_logfile_rotation (const XmlElement *from, const unsigned def=defaults::log_rotation) const
unsigned get_heartbeat_interval (const XmlElement *from, const unsigned def=defaults::hb_interval) const
bool get_tcp_nodelay (const XmlElement *from, const bool def=true) const
bool get_tcp_keepalive (const XmlElement *from, const bool def=false) const
bool get_tcp_reuseaddr (const XmlElement *from, const bool def=false) const
int get_tcp_linger (const XmlElement *from, const int def=-1) const
bool get_silent_disconnect (const XmlElement *from, const bool def=false) const
bool get_enforce_compids_flag (const XmlElement *from, const bool def=true) const
bool get_ignore_logon_sequence_check_flag (const XmlElement *from, const bool def=false) const
bool get_no_chksum_flag (const XmlElement *from, const bool def=false) const
bool get_permissive_mode_flag (const XmlElement *from, const bool def=false) const
bool get_reset_sequence_number_flag (const XmlElement *from, const bool def=false) const
bool get_always_seqnum_assign (const XmlElement *from, const bool def=false) const
F8API ProcessModel get_process_model (const XmlElement *from) const
default_appl_ver_id get_default_appl_ver_id (const XmlElement *from) const
sender_comp_id get_sender_comp_id (const XmlElement *from) const
target_comp_id get_target_comp_id (const XmlElement *from) const
F8API Persister * create_persister (const XmlElement *from, const SessionID *sid=nullptr, bool flag=false) const
F8API Logger * create_logger (const XmlElement *from, const Logtype ltype, const SessionID *sid=nullptr) const
F8API Schedule create_schedule (const XmlElement *from) const
F8API Clients create_clients (const XmlElement *from) const
F8API Schedule create_login_schedule (const XmlElement *from) const
F8API Session_Schedule * create_session_schedule (const XmlElement *from) const
F8API unsigned get_all_sessions (std::vector< const XmlElement * > &target, const Connection::Role role=Connection::cn_unknown) const
const XmlElement * get_root () const
template<typename T >
T get_logflags (const string &tag, const vector< string > &names, const XmlElement *from, Logger::LogPositions *positions) const
Protected Member Functions
bool from_or_default (const XmlElement *from, const f8String &tag, f8String &target) const
template<typename T >
T & get_string_field (const XmlElement *from, const std::string &tag, T &to) const
Tickval::ticks get_time_field (const XmlElement *from, const std::string &tag, bool timeonly=false) const
template<typename T >
T find_or_default (const XmlElement *from, const std::string &tag, const T def) const
Private Types
using ConfigMap = std::map< const std::string, const XmlElement * >
Private Member Functions
const XmlElement * find_element (const std::string &tag, const ConfigMap &from) const
unsigned load_map (const std::string &tag, ConfigMap &map_name, const bool is_session=false)
Private Attributes
const XmlElement * _root
const XmlElement * _default
std::vector< ConfigMap > _groups
std::vector< const XmlElement * > _allsessions
Static Private Attributes
static RegExp _ipexp
Detailed Description
Class to encapsulate a Fix8 configuration.
Definition at line 92 of file configuration.hpp.
Member Typedef Documentation
using FIX8::Configuration::ConfigMap = std::map<const std::string, const XmlElement *> private
Definition at line 97 of file configuration.hpp.
Member Enumeration Documentation
enum FIX8::Configuration::group_types
Enumerator
g_sessions
g_persisters
g_loggers
g_server_group
g_ssl_context
g_schedules
g_logins
g_client_group
g_count
Definition at line 109 of file configuration.hpp.
    {
       g_sessions, g_persisters, g_loggers, g_server_group,
       g_ssl_context, g_schedules, g_logins, g_client_group,
       g_count
    };
enum FIX8::Configuration::Logtype
Enumerator
session_log
protocol_log
Definition at line 205 of file configuration.hpp.
 { session_log, protocol_log };
Constructor & Destructor Documentation
FIX8::Configuration::Configuration (const std::string & xmlfile, bool do_process = false) inline
Ctor.
Parameters
xmlfile xml config filename.
do_process if true, process the file on construction
Definition at line 210 of file configuration.hpp.
References FIX8::exist(), and process().
       : _root(XmlElement::Factory(xmlfile)),
       _default(_root ? _root->find("fix8/default") : nullptr),
       _groups(g_count)
    {
       if (!exist(xmlfile))
          throw ConfigurationError("config file not found", xmlfile);
       if (do_process)
          process();
    }
FIX8::Configuration::Configuration (std::istream & istr, bool do_process = false) inline
Ctor.
Parameters
istr xml stream
do_process if true, process the stream on construction
Definition at line 224 of file configuration.hpp.
References process().
       : _root(XmlElement::Factory(istr, "stream")),
       _default(_root ? _root->find("fix8/default") : nullptr),
       _groups(g_count)
    {
       if (do_process)
          process();
    }
virtual FIX8::Configuration::~Configuration () inline virtual
Dtor.
Definition at line 234 of file configuration.hpp.
 {}
Member Function Documentation
Clients Configuration::create_clients (const XmlElement * from) const
Create clients object from a session entity.
Parameters
from xml entity to search
Returns
Clients
Definition at line 313 of file configuration.cpp.
References XmlElement::find(), and find_group().
Referenced by FIX8::SessionConfig::SessionConfig().
 {
    string name;
    const XmlElement *which;
    Clients clients;
    if (from_or_default(from, "target_comp_id", name) && (which = find_group(g_client_group, name)))
    {
       XmlElement::XmlSet slist;
       if (which->find("client_group/client", slist))
       {
          // <client name="Goldsteins" target_comp_id="DLD_TEX" ip="192.168.0.17" active="true" />
          for(const auto *pp : slist)
          {
             string name, tci;
             const Poco::Net::IPAddress addr(get_ip(pp));
             if (pp->GetAttr("name", name) && pp->GetAttr("target_comp_id", tci) && pp->FindAttr("active", true))
                if (!clients.insert({tci, Client(name, addr)}).second)
                   throw ConfigurationError("Failed to add client from client_group", tci);
          }
       }
    }
    return clients;
 }
Logger * Configuration::create_logger (const XmlElement * from, const Logtype ltype, const SessionID * sid = nullptr) const
Create a new logger object from a session entity.
Parameters
from xml entity to search
ltype log type
sid optional session id to build name from
Returns
new logger or 0 if unable to create
Definition at line 256 of file configuration.cpp.
References FIX8::Logger::_bit_names, FIX8::Logger::_level_names, FIX8::Logger::All, find_group(), XmlElement::FindAttrRef(), XmlElement::GetAttr(), XmlElement::HasAttr(), FIX8::Logger::None, FIX8::Logger::StdFlags, FIX8::trim(), and FIX8::Logger::xml.
Referenced by FIX8::Session::handle_logon().
 {
    string name;
    if (from_or_default(from, ltype == session_log ? "session_log" : "protocol_log", name))
    {
       const XmlElement *which(find_group(g_loggers, name));
       if (which)
       {
          Logger::LogPositions positions;
          string type;
          if (which->GetAttr("type", type)
             && ((type % "session" && ltype == session_log) || (type % "protocol" && ltype == protocol_log)))
          {
             string logname("logname_not_set.log"), levstr, delim(" ");
             which->FindAttrRef("filename", logname);
             trim(logname);
             if (which->GetAttr("delimiter", delim) && delim.size() > 2) // "|" or "<>" or "{}" etc
                throw ConfigurationError("invalid logging field delimiter");
             which->GetAttr("levels", levstr);
             const Logger::Levels levels(levstr.empty() || levstr % "All"
                   ? Logger::Levels(Logger::All) : levstr % "None"
                   ? Logger::Levels(Logger::None) : get_logflags<Logger::Levels>("levels", Logger::_level_names, which));
             const Logger::LogFlags flags(which->HasAttr("flags")
                ? get_logflags<Logger::LogFlags>("flags", Logger::_bit_names, which, &positions) : Logger::LogFlags(Logger::StdFlags));
             if (logname[0] == '|')
             {
 #ifndef FIX8_HAVE_POPEN
                throw ConfigurationError("popen not supported on your platform");
 #endif
                return new PipeLogger(logname, flags, levels, delim, positions);
             }
             RegMatch match;
             if (_ipexp.SearchString(match, logname, 3) == 3)
             {
                f8String ip, port;
                _ipexp.SubExpr(match, logname, ip, 0, 1);
                _ipexp.SubExpr(match, logname, port, 0, 2);
                return new BCLogger(ip, stoul(port), flags, levels, delim, positions);
             }
             get_logname(which, logname, sid); // only applies to file loggers
             if (flags & Logger::xml)
                return new XmlFileLogger(logname, flags, levels, delim, positions, get_logfile_rotation(which));
             return new FileLogger(logname, flags, levels, delim, positions, get_logfile_rotation(which));
          }
       }
    }
    return nullptr;
 }
Schedule Configuration::create_login_schedule (const XmlElement * from) const
Create login schedule object from a session entity.
Parameters
from xml entity to search
Returns
login Schedule
Definition at line 177 of file configuration.cpp.
References find_group().
Referenced by FIX8::SessionConfig::SessionConfig().
 {
    string name;
    const XmlElement *which;
    return from_or_default(from, "login", name) && (which = find_group(g_logins, name))
       ? create_schedule(which) : Schedule();
 }
Persister * Configuration::create_persister (const XmlElement * from, const SessionID * sid = nullptr, bool flag = false) const
Create a new persister object from a session entity.
Parameters
from xml entity to search
sid optional session id to build name from
flag additional flag for persister use
Returns
new persister or 0 if unable to create
Definition at line 186 of file configuration.cpp.
References FIX8::defaults::connect_timeout, find_group(), XmlElement::FindAttr(), FIX8::SessionID::get_senderCompID(), FIX8::SessionID::get_targetCompID(), and XmlElement::GetAttr().
Referenced by FIX8::Session::handle_logon().
 {
    string name, type;
    const XmlElement *which;
    if (from_or_default(from, "persist", name) && (which = find_group(g_persisters, name)) && which->GetAttr("type", type))
    {
       if (type == "mem")
          return new MemoryPersister;
       string dir("./"), db("persist_db");
       which->GetAttr("dir", dir);
       which->GetAttr("db", db) || which->GetAttr("session_prefix", db);
       if (sid)
          db += ('.' + sid->get_senderCompID()() + '.' + sid->get_targetCompID()());
       else if (which->FindAttr("use_session_id", false))
          db += ('.' + get_sender_comp_id(from)() + '.' + get_target_comp_id(from)());
 #if defined FIX8_HAVE_LIBMEMCACHED
       if (type == "memcached")
       {
          string config_str;
          if (which->GetAttr("config_string", config_str))
          {
             unique_ptr<MemcachedPersister> result(new MemcachedPersister);
             if (result->initialise(config_str, db, flag))
                return result.release();
          }
          else
             throw ConfigurationError("memcached: config_string attribute must be given when using memcached");
       }
       else
 #endif
 #if defined FIX8_HAVE_LIBHIREDIS
       if (type == "redis")
       {
          string host_str;
          if (which->GetAttr("host", host_str))
          {
             unique_ptr<HiredisPersister> result(new HiredisPersister);
             if (result->initialise(host_str, which->FindAttr("port", 6379),
                which->FindAttr("connect_timeout", static_cast<unsigned>(defaults::connect_timeout)), db, flag))
                   return result.release();
          }
          else
             throw ConfigurationError("redis: host attribute must be given when using redis");
       }
       else
 #endif
 #if defined FIX8_HAVE_BDB
       if (type == "bdb")
       {
          unique_ptr<BDBPersister> result(new BDBPersister);
          if (result->initialise(dir, db, flag))
             return result.release();
       }
       else
 #endif
       if (type == "file")
       {
          unique_ptr<FilePersister> result(new FilePersister(which->FindAttr("rotation", 0)));
          if (result->initialise(dir, db, flag))
             return result.release();
       }
    }
    return nullptr;
 }
Schedule Configuration::create_schedule (const XmlElement * from) const
Create schedule object from a session entity.
Parameters
from xml entity to search
Returns
Schedule
Definition at line 131 of file configuration.cpp.
References FIX8::decode_dow(), XmlElement::FindAttr(), FIX8::Tickval::get_ticks(), XmlElement::GetAttr(), FIX8::Tickval::is_errorval(), and FIX8::Tickval::minute.
 {
    Tickval start(get_time_field(which, "start_time", true));
    if (!start.is_errorval())
    {
       const int utc_offset(which->FindAttr("utc_offset_mins", 0)); // utc_offset is in minutes
       const unsigned duration(which->FindAttr("duration", 0));
       Tickval end(get_time_field(which, "end_time", true));
       if (end.is_errorval())
       {
          if (duration) // duration is in minutes
             end = start.get_ticks() + duration * Tickval::minute;
       }
       else
       {
          if (end <= start)
             throw ConfigurationError("Schedule end time cannot be equal to or before session start time");
       }
       string daytmp;
       const int start_day(which->GetAttr("start_day", daytmp) ? decode_dow(daytmp) : -1);
       const int end_day(which->GetAttr("end_day", daytmp) ? decode_dow(daytmp) : start_day < 0 ? -1 : start_day);
       return {start, end, Tickval(static_cast<Tickval::ticks>(duration)), utc_offset, start_day, end_day};
    }
    return {};
 }
Session_Schedule * Configuration::create_session_schedule (const XmlElement * from) const
Create a new session schedule object from a session entity.
Parameters
from xml entity to search
Returns
new Session_Schedule or 0 if unable to create
Definition at line 160 of file configuration.cpp.
References find_group(), XmlElement::FindAttr(), and XmlElement::GetAttr().
Referenced by FIX8::Session::start().
 {
    string name;
    const XmlElement *which(0);
    if (from_or_default(from, "schedule", name) && (which = find_group(g_schedules, name)))
    {
       Schedule sch(create_schedule(which));
       f8String reject_text("Business messages are not accepted now.");
       which->GetAttr("reject_text", reject_text); // can't use FindAttr since istream is delimeter sensitive
       const int reject_code(which->FindAttr("reject_code", 0));
       return new Session_Schedule(sch, reject_code, reject_text);
    }
    return nullptr;
 }
const XmlElement* FIX8::Configuration::find_element (const std::string & tag, const ConfigMap & from) const inline private
Find an xml entity by tag in the supplied map.
Parameters
tag the tag to find
from the map to search
Returns
the found entity or 0 if not found
Definition at line 105 of file configuration.hpp.
References XmlElement::end().
Referenced by find_group().
       { ConfigMap::const_iterator itr(from.find(tag)); return itr != from.end() ? itr->second : nullptr; }
const XmlElement* FIX8::Configuration::find_group (group_types type, const std::string & tag) const inline
Find an element in a specified group.
Parameters
type group type enum
tag the tag to find
Returns
the found entity or 0 if not found
Definition at line 120 of file configuration.hpp.
References find_element().
       { return find_element(tag, _groups[type]); }
template<typename T > T FIX8::Configuration::find_or_default (const XmlElement * from, const std::string & tag, const T def) const inline protected
Find an attribute in the given XmlElement
Template Parameters
default type
Parameters
from the xml entity to search
tag the tag to find
def the default value if not found
Returns
the found attribute value or the default value if not found
Definition at line 166 of file configuration.hpp.
References XmlElement::FindAttr(), and XmlElement::HasAttr().
Referenced by get_always_seqnum_assign(), get_connect_timeout(), get_enforce_compids_flag(), get_heartbeat_interval(), get_ignore_logon_sequence_check_flag(), get_logfile_rotation(), get_no_chksum_flag(), get_permissive_mode_flag(), get_reset_sequence_number_flag(), get_retry_count(), get_retry_interval(), get_silent_disconnect(), get_tabsize(), get_tcp_keepalive(), get_tcp_linger(), get_tcp_nodelay(), get_tcp_recvbuf_sz(), get_tcp_reuseaddr(), get_tcp_sendbuf_sz(), and get_version().
    {
       if (from)
       {
          if (from->HasAttr(tag))
             return from->FindAttr(tag, def);
          if (_default)
             return _default->FindAttr(tag, def);
       }
       return def;
    }
bool FIX8::Configuration::from_or_default (const XmlElement * from, const f8String & tag, f8String & target) const inline protected
Search the given element for a tag or look in the default element
Parameters
from the xml entity to search
tag the tag to find
target place to put the resul
Returns
true if found and stored
Definition at line 129 of file configuration.hpp.
References XmlElement::GetAttr().
Referenced by get_string_field().
       { return (from && from->GetAttr(tag, target)) || (_default && _default->GetAttr(tag, target)); }
Poco::Net::SocketAddress Configuration::get_address (const XmlElement * from) const
Extract the ip address and port from a session entity.
Parameters
from xml entity to search
Returns
Poco::Net::SocketAddress
Definition at line 83 of file configuration.cpp.
 {
    Poco::Net::SocketAddress to;
    string ip, port;
    if (from_or_default(from, "ip", ip) && from_or_default(from, "port", port))
       to = Poco::Net::SocketAddress(ip, port);
    return to;
 }
size_t Configuration::get_addresses (const XmlElement * from, std::vector< Server > & target) const
Extract the ip addresses from a server_group entity.
Parameters
from xml entity to search
target target vector of Server to store addresses
Returns
number of addresses stored
Definition at line 105 of file configuration.cpp.
References XmlElement::find(), find_group(), and FIX8::defaults::login_retries.
 {
    string name;
    const XmlElement *which;
    if (from_or_default(from, "server_group", name) && (which = find_group(g_server_group, name)))
    {
       XmlElement::XmlSet slist;
       if (which->find("server_group/server", slist))
       {
          const Poco::Net::SocketAddress empty_addr;
          for(const auto *pp : slist)
          {
             string name;
             Poco::Net::SocketAddress addr(get_address(pp));
             if (pp->GetAttr("name", name) && addr != empty_addr && pp->FindAttr("active", true))
                target.push_back(Server(name, pp->FindAttr("max_retries", static_cast<int>(defaults::login_retries)), addr,
                   pp->FindAttr("reset_sequence_numbers", false)));
          }
       }
       return target.size();
    }
    return 0;
 }
unsigned Configuration::get_all_sessions (std::vector< const XmlElement * > & target, const Connection::Role role = Connection::cn_unknown) const
Get all active sessions that have been read; filter by role if desired.
Parameters
target vector to place results
role role to filter (cn_unknown means all)
Returns
number of sessions found
Definition at line 372 of file configuration.cpp.
References FIX8::Connection::cn_unknown.
 {
    for (const auto *pp : _allsessions)
       if (role == Connection::cn_unknown || get_role(pp) == role)
          target.push_back(pp);
    return static_cast<unsigned>(target.size());
 }
bool FIX8::Configuration::get_always_seqnum_assign (const XmlElement * from, const bool def = false) const inline
Extract the always_seqnum_assign flag from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
true if always_seqnum_assign flag was passed and was true
Definition at line 422 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "always_seqnum_assign", def); }
unsigned FIX8::Configuration::get_connect_timeout (const XmlElement * from, const unsigned def = defaults::connect_timeout) const inline
Extract the connect_timeout interval (sec) from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the connect_timeout wait 10 if not found
Definition at line 289 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "connect_timeout", def); }
default_appl_ver_id FIX8::Configuration::get_default_appl_ver_id (const XmlElement * from) const inline
Extract default_appl_ver_id from a session entity.
Parameters
from xml entity to search
Returns
target default_appl_ver_id
Definition at line 433 of file configuration.hpp.
References get_string_field().
Referenced by FIX8::SessionConfig::SessionConfig().
       { default_appl_ver_id to; return get_string_field(from, "default_appl_ver_id", to); }
bool FIX8::Configuration::get_enforce_compids_flag (const XmlElement * from, const bool def = true) const inline
Extract the enforce_compids flag. When false, compids are not checked.
Parameters
from xml entity to search
def default value if not found
Returns
true if enforce_compids flag was passed and was true
Definition at line 387 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "enforce_compids", def); }
unsigned FIX8::Configuration::get_heartbeat_interval (const XmlElement * from, const unsigned def = defaults::hb_interval) const inline
Extract the heartbeat interval from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the heartbeat interval version or 0 if not found
Definition at line 345 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "heartbeat_interval", def); }
bool FIX8::Configuration::get_ignore_logon_sequence_check_flag (const XmlElement * from, const bool def = false) const inline
Extract the ignore_logon_sequence_check flag from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
true if ignore_logon_sequence_check flag was passed and was true
Definition at line 394 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::Session::sequence_check().
       { return find_or_default(from, "ignore_logon_sequence_check", def); }
Poco::Net::IPAddress Configuration::get_ip (const XmlElement * from) const
Extract the ip address from a session entity.
Parameters
from xml entity to search
Returns
Poco::Net::IPAddress
Definition at line 94 of file configuration.cpp.
 {
    Poco::Net::IPAddress to;
    string ip;
    if (from_or_default(from, "ip", ip))
       to = Poco::Net::IPAddress(ip);
    return to;
 }
unsigned FIX8::Configuration::get_logfile_rotation (const XmlElement * from, const unsigned def = defaults::log_rotation) const inline
Extract the logfile rotation count.
Parameters
from xml entity to search
def default value if not found
Returns
the logfile rotation value or 5 if not found
Definition at line 338 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "rotation", def); }
template<typename T > T FIX8::Configuration::get_logflags (const std::string & tag, const std::vector< std::string > & names, const XmlElement * from, Logger::LogPositions * positions = nullptr) const
Extract the logflags from the flags attribute in a log entity.
Template Parameters
T ebitset type
Parameters
tag attribute tag to search for
names vector of names for each enumeration
from xml entity to search
positions vector to place enumeration position in
Returns
LogFLags object
template<typename T > T FIX8::Configuration::get_logflags (const string & tag, const vector< string > & names, const XmlElement * from, Logger::LogPositions * positions) const
Definition at line 351 of file configuration.cpp.
References XmlElement::GetAttr(), and FIX8::trim().
 {
    T flags;
    string flags_str;
    if (from && from->GetAttr(tag, flags_str))
    {
       istringstream istr(flags_str);
       for(char extr[32]; !istr.get(extr, sizeof(extr), '|').fail(); istr.ignore(1))
       {
          string result(extr);
          const int evalue(flags.set(names, trim(result), true, true));
          if (positions && evalue >= 0)
             positions->push_back(evalue);
       }
    }
    return flags;
 }
string & Configuration::get_logname (const XmlElement * from, std::string & to, const SessionID * sid = nullptr) const
Extract the session log filename address from a session entity.
Parameters
from xml entity to search
to target logfile string
sid optional session id to build name from
Returns
target string
Definition at line 339 of file configuration.cpp.
References XmlElement::FindAttr(), FIX8::SessionID::get_senderCompID(), and FIX8::SessionID::get_targetCompID().
 {
    if (sid)
       to += ('.' + sid->get_senderCompID()() + '.' + sid->get_targetCompID()());
    else if (from && from->FindAttr("use_session_id", false))
       to += ('.' + get_sender_comp_id(from)() + '.' + get_target_comp_id(from)());
    return to;
 }
bool FIX8::Configuration::get_no_chksum_flag (const XmlElement * from, const bool def = false) const inline
Extract the get_no_chksum_flag flag from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
true if get_no_chksum_flag flag was passed and was true
Definition at line 401 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "no_chksum", def); }
bool FIX8::Configuration::get_permissive_mode_flag (const XmlElement * from, const bool def = false) const inline
Extract the get_permissive_mode_flag flag from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
true if get_permissive_mode_flag flag was passed and was true
Definition at line 408 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "permissive_mode", def); }
ProcessModel Configuration::get_process_model (const XmlElement * from) const
Extract process model.
Parameters
from xml entity to search
Returns
pm_thread, pm_pipeline or pm_coro
Definition at line 381 of file configuration.cpp.
References FIX8::enum_str_get(), FIX8::pm_pipeline, and FIX8::pm_thread.
Referenced by FIX8::ClientSession< T >::ClientSession(), and server_process().
 {
    static const vector<f8String> process_strings { "threaded", "pipelined", "coroutine" };
    string pm;
    return from_or_default(from, "process_model", pm)
       ? enum_str_get(process_strings, pm, pm_thread) : pm_pipeline; // default to pipelined
 }
bool FIX8::Configuration::get_reset_sequence_number_flag (const XmlElement * from, const bool def = false) const inline
Extract the reset_sequence_number flag from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
true if reset_sequence_number flag was passed and was true
Definition at line 415 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "reset_sequence_numbers", def); }
unsigned FIX8::Configuration::get_retry_count (const XmlElement * from, const unsigned def = defaults::login_retries) const inline
Extract the login retry count from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the retry count or 10 if not found
Definition at line 303 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "login_retries", def); }
unsigned FIX8::Configuration::get_retry_interval (const XmlElement * from, const unsigned def = defaults::retry_interval) const inline
Extract the login retry wait interval (ms) from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the retry wait interval or 5000 if not found
Definition at line 296 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "login_retry_interval", def); }
Connection::Role Configuration::get_role (const XmlElement * from) const
Extract the role from a session entity.
Parameters
from xml entity to search
Returns
the connection role or Connection::cn_unknown if not found
Definition at line 74 of file configuration.cpp.
References FIX8::Connection::cn_acceptor, FIX8::Connection::cn_initiator, and FIX8::Connection::cn_unknown.
 {
    string role;
    return from_or_default(from, "role", role)
       ? role % "initiator" ? Connection::cn_initiator
       : role % "acceptor" ? Connection::cn_acceptor : Connection::cn_unknown : Connection::cn_unknown;
 }
const XmlElement* FIX8::Configuration::get_root () const inline
Return ptr to the root XmlElement
Returns
root element
Definition at line 497 of file configuration.hpp.
References _root.
 { return _root; }
sender_comp_id FIX8::Configuration::get_sender_comp_id (const XmlElement * from) const inline
Extract sendercompid from a session entity.
Parameters
from xml entity to search
Returns
target sender_comp_id
Definition at line 439 of file configuration.hpp.
References get_string_field().
       { sender_comp_id to; return get_string_field(from, "sender_comp_id", to); }
const XmlElement* FIX8::Configuration::get_session (const unsigned num) const inline
Find a session entity by index.
Parameters
num index of session
Returns
the session entity or 0 if not found
Definition at line 243 of file configuration.hpp.
       { return num < _allsessions.size() ? _allsessions[num] : nullptr; }
bool FIX8::Configuration::get_silent_disconnect (const XmlElement * from, const bool def = false) const inline
Extract the silent disconnect flag.
Parameters
from xml entity to search
def default value if not found
Returns
true if silent_disconnect flag was passed and was true
Definition at line 380 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "silent_disconnect", def); }
template<typename T > T& FIX8::Configuration::get_string_field (const XmlElement * from, const std::string & tag, T & to) const inline protected
Find a fix8 field typed value by tag from an xml entity.
Template Parameters
location type
Parameters
from the xml entity to search
tag the tag to find
to location to store target
Returns
the target
Definition at line 139 of file configuration.hpp.
References from_or_default().
Referenced by get_default_appl_ver_id(), get_sender_comp_id(), and get_target_comp_id().
    {
       std::string val;
       if (from_or_default(from, tag, val))
          to.set(val);
       return to;
    }
unsigned FIX8::Configuration::get_tabsize (const XmlElement * from, const unsigned def = defaults::tabsize) const inline
Extract the Message printer tabsize from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the tabsize version or defaults::tabsize if not found
Definition at line 331 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "tabsize", def); }
target_comp_id FIX8::Configuration::get_target_comp_id (const XmlElement * from) const inline
Extract targetcompid from a session entity.
Parameters
from xml entity to search
Returns
target target_comp_id
Definition at line 445 of file configuration.hpp.
References get_string_field().
       { target_comp_id to; return get_string_field(from, "target_comp_id", to); }
bool FIX8::Configuration::get_tcp_keepalive (const XmlElement * from, const bool def = false) const inline
Extract the tcp keepalive flag.
Parameters
from xml entity to search
def default value if not found
Returns
false if keepalive flag was passed and was false
Definition at line 359 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "tcp_keepalive", def); }
int FIX8::Configuration::get_tcp_linger (const XmlElement * from, const int def = -1) const inline
Extract the socket linger setting from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the socket linger value (secs)
Definition at line 373 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "tcp_linger", def); }
bool FIX8::Configuration::get_tcp_nodelay (const XmlElement * from, const bool def = true) const inline
Extract the tcp nodelay flag.
Parameters
from xml entity to search
def default value if not found
Returns
false if nodelay flag was passed and was false
Definition at line 352 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "tcp_nodelay", def); }
unsigned FIX8::Configuration::get_tcp_recvbuf_sz (const XmlElement * from, const unsigned def = 0) const inline
Extract the tcp recv buffer size
Parameters
from xml entity to search
def default value if not found
Returns
the recv buffer size count or 0 if the default should be used
Definition at line 310 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "tcp_recv_buffer", def); }
bool FIX8::Configuration::get_tcp_reuseaddr (const XmlElement * from, const bool def = false) const inline
Extract the tcp reuseaddr flag.
Parameters
from xml entity to search
def default value if not found
Returns
false if reuseaddr flag was passed and was false
Definition at line 366 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "tcp_reuseaddr", def); }
unsigned FIX8::Configuration::get_tcp_sendbuf_sz (const XmlElement * from, const unsigned def = 0) const inline
Extract the tcp send buffer size
Parameters
from xml entity to search
def default value if not found
Returns
the send buffer size count or 0 if the default should be used
Definition at line 317 of file configuration.hpp.
References find_or_default().
Referenced by FIX8::SessionConfig::SessionConfig().
       { return find_or_default(from, "tcp_send_buffer", def); }
Tickval::ticks FIX8::Configuration::get_time_field (const XmlElement * from, const std::string & tag, bool timeonly = false) const inline protected
Find a session time field by tag from an xml entity.
Parameters
from the xml entity to search
tag the tag to find
timeonly if true, only use the time part
Returns
Tickval::ticks time or errorticks if not found
Definition at line 152 of file configuration.hpp.
References FIX8::Tickval::errorticks(), XmlElement::GetAttr(), and FIX8::time_parse().
    {
       std::string time_str;
       return from && from->GetAttr(tag, time_str) && time_str.size() == 8
          ? time_parse(time_str.c_str(), 8, timeonly) : Tickval::errorticks();
    }
unsigned FIX8::Configuration::get_version (const XmlElement * from, const unsigned def = 0) const inline
Extract the FIX version from a session entity.
Parameters
from xml entity to search
def default value if not found
Returns
the FIX version or 0 if not found
Definition at line 324 of file configuration.hpp.
References find_or_default().
       { return find_or_default(from, "fix_version", def); }
unsigned FIX8::Configuration::load_map (const std::string & tag, ConfigMap & map_name, const bool is_session = false) inline private
Load a repeating group into a supplied map.
Parameters
tag the tag to find
map_name the target map
is_session if true, special case for session map
Returns
the number of elements inserted
Definition at line 184 of file configuration.hpp.
References XmlElement::find().
    {
       XmlElement::XmlSet slist;
       if (_root->find(tag, slist))
       {
          for(const auto *pp : slist)
          {
             std::string name;
             if (pp->GetAttr("name", name) && is_session ? pp->FindAttr("active", false) : true)
             {
                map_name.insert({name, pp});
                if (is_session)
                   _allsessions.push_back(pp);
             }
          }
       }
       return static_cast<unsigned>(map_name.size());
    }
int Configuration::process ()
Process the config file.
Returns
the number of sessions processed (found)
Definition at line 52 of file configuration.cpp.
Referenced by Configuration().
 {
    if (!_root)
       throw ConfigurationError("could not create root xml entity");
    using item = tuple<f8String, group_types, bool>;
    static const item items[]
    {
       { item("session", g_sessions, true) },             { item("log", g_loggers, false) },
       { item("server_group", g_server_group, false) },   { item("client_group", g_client_group, false) },
       { item("ssl_context", g_ssl_context, false) },     { item("schedule", g_schedules, false) },
       { item("login", g_logins, false) },                { item("persist", g_persisters, false) }
    };
    for (auto &pp : items)
       if (!load_map("fix8/" + get<0>(pp), _groups[get<1>(pp)], get<2>(pp)) && get<2>(pp))
          throw ConfigurationError("could not locate server session in configuration", get<0>(pp));
    return static_cast<int>(_groups[g_sessions].size());
 }
Member Data Documentation
std::vector<const XmlElement *> FIX8::Configuration::_allsessions private
Definition at line 99 of file configuration.hpp.
const XmlElement * FIX8::Configuration::_default private
Definition at line 96 of file configuration.hpp.
std::vector<ConfigMap> FIX8::Configuration::_groups private
Definition at line 98 of file configuration.hpp.
RegExp Configuration::_ipexp static private
Definition at line 94 of file configuration.hpp.
const XmlElement* FIX8::Configuration::_root private
Definition at line 96 of file configuration.hpp.
Referenced by get_root().
The documentation for this class was generated from the following files:
configuration.hpp
configuration.cpp