fix8: ff::ff_loadbalancer Class Reference
ff::ff_loadbalancer Class Reference
A class representing the Emitter node in a typical Farm skeleton.
#include <lb.hpp>
Public Types
enum { TICKS2WAIT =1000 }
Public Member Functions
ff_loadbalancer (int max_num_workers)
Default constructor.
~ff_loadbalancer ()
Destructor.
int set_filter (ff_node *f)
Sets filter node.
void set_in_buffer (FFBUFFER *const buff)
Sets input buffer.
FFBUFFER * get_in_buffer () const
Gets input buffer.
int get_channel_id () const
Gets channel id.
void reset_channel_id ()
Resets the channel id.
int getnworkers () const
Get the number of workers.
void skipfirstpop ()
Skips first pop.
int set_masterworker ()
Decides master-worker schema.
int getTid (ff_node *node) const
int set_multi_input (ff_node **mi, int misize)
Sets multiple input buffers.
bool ff_send_out_to (void *task, int id, unsigned int retry=(unsigned)-1, unsigned int ticks=0)
bool masterworker () const
Gets master worker.
int register_worker (ff_node *w)
Registers the given node into the workers' list.
int deregister_worker ()
Deregister worker.
virtual void * svc (void *)
Load balances task.
virtual int svc_init ()
Initializes the load balancer task.
virtual void svc_end ()
Finalizes the loadbalancer task.
int runlb (bool=false)
Runs the loadbalancer.
int run (bool=false)
Spawns workers threads.
int waitlb ()
Waits for load balancer.
int wait ()
Waits for workers to finish their task.
int wait_freezing ()
Waits for freezing.
void stop ()
Stops the thread.
void freeze ()
Freezes the thread.
void thaw (bool _freeze=false, int nw=-1)
Thaws the thread.
virtual double ffTime ()
FastFlow start timing.
virtual double wffTime ()
FastFlow finish timing.
virtual struct timeval & getstarttime () const
virtual struct timeval & getstoptime () const
virtual struct timeval & getwstartime () const
virtual struct timeval & getwstoptime () const
Public Member Functions inherited from ff::ff_thread
virtual void svc_createOCL ()
The svc_createOCL method.
virtual void svc_releaseOCL ()
The svc_releaseOCL.
void set_barrier (BARRIER_T *const b)
Sets the barrier object.
int spawn (int cpuId=-1)
Creates a new thread.
int wait ()
Waits for thread termination.
int wait_freezing ()
Waits for thread freezing.
void stop ()
Forces the thread to stop.
void freeze ()
Forces the thread to freeze.
void thaw (bool _freeze=false)
Thaw the thread, if it is frozen.
bool isfrozen ()
Checks if the thread is frozen.
pthread_t get_handle () const
Gets the pthread handler.
int getTid () const
Gets the internal unique thread identifier.
Protected Member Functions
bool push_task (void *task, int idx)
Sends a task to a worker.
void push_eos (bool nofreeze=false)
Pushes EOS to the worker.
void push_goon ()
virtual int selectworker ()
Virtual function that can be redefined to implement a new scheduling policy.
virtual unsigned int ntentative ()
Gets the number of tentatives before wasting some times.
virtual void losetime_out ()
Loses some time before sending the message to output buffer.
virtual void losetime_in ()
Losses time before sending the message to input buffer.
virtual bool schedule_task (void *task, unsigned int retry=(unsigned)-1, unsigned int ticks=0)
Scheduling of tasks.
virtual std::deque< ff_node * >
::iterator collect_task (void **task, std::deque< ff_node * > &availworkers, std::deque< ff_node * >::iterator &start)
Collects tasks.
virtual void broadcast_task (void *task)
Send the same task to all workers.
bool pop (void **task)
Pop a task from buffer.
Protected Member Functions inherited from ff::ff_thread
ff_thread (BARRIER_T *barrier=NULL)
Constructor.
virtual ~ff_thread ()
Destructor.
void thread_routine ()
The life cycle of FastFlow thread.
int disable_cancelability ()
Disable the cancelation of thread.
int enable_cancelability ()
Makes thread cancelable.
Static Protected Member Functions
static bool ff_send_out_emitter (void *task, unsigned int retry, unsigned int ticks, void *obj)
Task scheduler.
Private Attributes
int nworkers
int running
Number of workers.
int max_nworkers
Number of workers running.
int nextw
Max number of workers allowed.
int nextINw
int channelid
ff_node * filter
ff_node ** workers
FFBUFFER * buffer
bool skip1pop
bool master_worker
ff_node ** multi_input
int multi_input_size
int multi_input_start
struct timeval tstart
struct timeval tstop
struct timeval wtstart
struct timeval wtstop
double wttime
Additional Inherited Members
Protected Attributes inherited from ff::ff_thread
unsigned tid
Detailed Description
A class representing the Emitter node in a typical Farm skeleton.
This class models the loadbalancer, which wraps all the methods and structures used by the Emitter node in a Farm skeleton. The emitter node is used to generate the stream of tasks for the pool of workers. The emitter can also be used as sequential preprocessor if the stream is coming from outside the farm, as is the case when the stream is coming from a previous node of a pipeline chain or from an external device.
The Farm skeleton must have the emitter node defined: if the user does not add it to the farm, the run-time support adds a default emitter, which acts as a stream filter and schedules tasks in a round-robin fashion towards the workers.
This class is defined in lb.hpp
Definition at line 68 of file lb.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
TICKS2WAIT
Definition at line 75 of file lb.hpp.
Constructor & Destructor Documentation
ff::ff_loadbalancer::ff_loadbalancer (int max_num_workers) inline
Default constructor.
It is the defauls constructor
Parameters
max_num_workers The max number of workers allowed
Definition at line 340 of file lb.hpp.
References FFTRACE, pushwait(), ff::time_setzero(), tstart, tstop, wtstart, wtstop, and wttime.
ff::ff_loadbalancer::~ff_loadbalancer () inline
Destructor.
It deallocates dynamic memory spaces previoulsy allocated for workers.
Definition at line 356 of file lb.hpp.
References workers.
Member Function Documentation
virtual void ff::ff_loadbalancer::broadcast_task (void * task) inline protected virtual
Send the same task to all workers.
task is a void pointer
It sends the same task to all workers.
Definition at line 274 of file lb.hpp.
References losetime_out(), ff::ff_node::put(), running, and workers.
Referenced by ff::map_lb::broadcast().
virtual std::deque<ff_node *>::iterator ff::ff_loadbalancer::collect_task (void ** task, std::deque< ff_node * > & availworkers, std::deque< ff_node * >::iterator & start) inline protected virtual
Collects tasks.
It collects tasks from the worker and returns in the form of deque.
task is a void pointer availworkers is a queue of available workers start is a queue of TODO
Returns
The deque of the tasks.
Definition at line 238 of file lb.hpp.
References buffer, channelid, filter, ff::ff_node::in_active, losetime_in(), and multi_input_start.
Referenced by svc().
int ff::ff_loadbalancer::deregister_worker () inline
Deregister worker.
It deregister worker.
Returns
-1 ia always returned.
Definition at line 523 of file lb.hpp.
static bool ff::ff_loadbalancer::ff_send_out_emitter (void * task, unsigned int retry, unsigned int ticks, void * obj) inline static protected
Task scheduler.
It defines the static version of the task scheduler.
Returns
The status of scheduled task, which can be either true or false.
Definition at line 328 of file lb.hpp.
Referenced by set_filter().
bool ff::ff_loadbalancer::ff_send_out_to (void * task, int id, unsigned int retry = (unsigned)-1, unsigned int ticks = 0) inline
Definition at line 482 of file lb.hpp.
References nextw, and schedule_task().
Referenced by ff::forall_Scheduler::svc().
virtual double ff::ff_loadbalancer::ffTime () inline virtual
FastFlow start timing.
It returns the starting of FastFlow timing.
Returns
The difference in FastFlow timing.
Definition at line 840 of file lb.hpp.
References ff::diffmsec(), tstart, and tstop.
void ff::ff_loadbalancer::freeze () inline
Freezes the thread.
It freezes all workers and the emitter.
Definition at line 815 of file lb.hpp.
References ff::ff_thread::freeze(), nworkers, and workers.
Referenced by run().
int ff::ff_loadbalancer::get_channel_id () const inline
Gets channel id.
It returns the identifier of the channel.
Returns
the channel id
Definition at line 409 of file lb.hpp.
References channelid.
Referenced by ff::forall_Scheduler::svc().
FFBUFFER* ff::ff_loadbalancer::get_in_buffer () const inline
Gets input buffer.
It gets the input buffer
Returns
The buffer
Definition at line 399 of file lb.hpp.
References buffer.
Referenced by svc().
int ff::ff_loadbalancer::getnworkers () const inline
Get the number of workers.
It returns the number of workers running
Returns
Number of worker
Definition at line 426 of file lb.hpp.
References running.
virtual struct timeval& ff::ff_loadbalancer::getstarttime () const inline read virtual
Definition at line 855 of file lb.hpp.
References tstart.
virtual struct timeval& ff::ff_loadbalancer::getstoptime () const inline read virtual
Definition at line 856 of file lb.hpp.
References tstop.
int ff::ff_loadbalancer::getTid (ff_node * node) const inline
Definition at line 453 of file lb.hpp.
References ff::ff_node::getTid().
virtual struct timeval& ff::ff_loadbalancer::getwstartime () const inline read virtual
Definition at line 857 of file lb.hpp.
References wtstart.
virtual struct timeval& ff::ff_loadbalancer::getwstoptime () const inline read virtual
Definition at line 858 of file lb.hpp.
References wtstop.
virtual void ff::ff_loadbalancer::losetime_in () inline protected virtual
Losses time before sending the message to input buffer.
It looses time before the message is sent to the input buffer.
Definition at line 182 of file lb.hpp.
References FFTRACE, TICKS2WAIT, and ff::ticks_wait().
Referenced by collect_task(), and pop().
virtual void ff::ff_loadbalancer::losetime_out () inline protected virtual
Loses some time before sending the message to output buffer.
It looses some time before the message is sent to the output buffer.
Definition at line 172 of file lb.hpp.
References FFTRACE, pushwait(), TICKS2WAIT, and ff::ticks_wait().
Referenced by broadcast_task(), push_eos(), push_goon(), and schedule_task().
bool ff::ff_loadbalancer::masterworker () const inline
Gets master worker.
It returns master worker
Returns
The master worker
Definition at line 496 of file lb.hpp.
References master_worker.
virtual unsigned int ff::ff_loadbalancer::ntentative () inline protected virtual
Gets the number of tentatives before wasting some times.
The number of tentative before wasting some times and than retry.
Returns
The number of workers.
Definition at line 164 of file lb.hpp.
References nworkers.
Referenced by schedule_task().
bool ff::ff_loadbalancer::pop (void ** task) inline protected
Pop a task from buffer.
It pops the task from buffer.
task is a void pointer
Returns
true if successful
Definition at line 297 of file lb.hpp.
References buffer, filter, losetime_in(), and ff::ff_node::pop().
Referenced by svc().
void ff::ff_loadbalancer::push_eos (bool nofreeze = false) inline protected
Pushes EOS to the worker.
It pushes the EOS to the queue of the worker.
nofreeze is a booleon value to determine if the EOS should be freezed or not
Definition at line 100 of file lb.hpp.
References ff::FF_EOS, ff::FF_EOS_NOFREEZE, losetime_out(), running, and workers.
Referenced by svc().
void ff::ff_loadbalancer::push_goon () inline protected
Definition at line 112 of file lb.hpp.
References GO_ON, losetime_out(), running, and workers.
Referenced by svc().
bool ff::ff_loadbalancer::push_task (void * task, int idx) inline protected
Sends a task to a worker.
It pushes a task to worker.
Parameters
task the task to be sent
idx ID of the worker.
Returns
The status of pushing the task to worker, which can either be true or false
Definition at line 89 of file lb.hpp.
References ff::ff_node::put(), and workers.
int ff::ff_loadbalancer::register_worker (ff_node * w) inline
Registers the given node into the workers' list.
It registers the given node in the worker list.
w is the worker
Returns
0 if successful, or -1 if not successful
Definition at line 507 of file lb.hpp.
References ff::error(), max_nworkers, nworkers, and workers.
Referenced by ff::ff_monode::run().
void ff::ff_loadbalancer::reset_channel_id () inline
Resets the channel id.
It reset the channel id to -2
Definition at line 417 of file lb.hpp.
References channelid.
int ff::ff_loadbalancer::run (bool = false) inline
Spawns workers threads.
It spawns workers threads.
Returns
0 if successful, otherwise -1 is returned
Definition at line 720 of file lb.hpp.
References ff::error(), filter, freeze(), ff::ff_node::getCPUId(), ff::ff_thread::isfrozen(), nworkers, running, ff::ff_thread::spawn(), and workers.
int ff::ff_loadbalancer::runlb (bool = false) inline
Runs the loadbalancer.
It runs the load balancer.
Returns
0 if successful, otherwise -1 is returned.
Definition at line 705 of file lb.hpp.
References ff::error(), filter, ff::ff_node::getCPUId(), and ff::ff_thread::spawn().
Referenced by ff::ff_monode::run().
virtual bool ff::ff_loadbalancer::schedule_task (void * task, unsigned int retry = (unsigned)-1, unsigned int ticks = 0) inline protected virtual
Scheduling of tasks.
It is the main scheduling function. This is a virtual function and can be redefined to implement a custom scheduling policy.
task is a void pointer retry is the number of tries to schedule a task ticks are the number of ticks to be lost
Returns
true, if successful, or false if not successful.
Definition at line 200 of file lb.hpp.
References FFTRACE, losetime_out(), nextw, ntentative(), selectworker(), and workers.
Referenced by ff_send_out_to(), and svc().
virtual int ff::ff_loadbalancer::selectworker () inline protected virtual
Virtual function that can be redefined to implement a new scheduling policy.
It is a virtual function that can be redefined to implement a new scheduling polity.
Returns
The number of worker to be selected.
Reimplemented in ff::ofarm_lb.
Definition at line 131 of file lb.hpp.
References nextw, and running.
Referenced by schedule_task().
int ff::ff_loadbalancer::set_filter (ff_node * f) inline
Sets filter node.
It sets the filter with the FastFlow node.
f is FastFlow node
Returns
0 if successful, otherwise -1
Definition at line 369 of file lb.hpp.
References ff::error(), ff_send_out_emitter(), filter, and ff::ff_node::registerCallback().
Referenced by ff::ff_monode::run().
void ff::ff_loadbalancer::set_in_buffer (FFBUFFER *const buff) inline
Sets input buffer.
It sets the input buffer with the instance of FFBUFFER
buff is a pointer of FFBUFFER
Definition at line 387 of file lb.hpp.
References buffer, and skip1pop.
Referenced by svc().
int ff::ff_loadbalancer::set_masterworker () inline
Decides master-worker schema.
It desides the master-worker schema.
Returns
0 if successful, or -1 if unsuccessful.
Definition at line 444 of file lb.hpp.
References ff::error(), and master_worker.
int ff::ff_loadbalancer::set_multi_input (ff_node ** mi, int misize) inline
Sets multiple input buffers.
It sets the multiple input buffers.
Returns
0 if successful, otherwise -1.
Definition at line 464 of file lb.hpp.
References ff::error(), multi_input, and multi_input_size.
void ff::ff_loadbalancer::skipfirstpop () inline
Skips first pop.
It sets skip1pop to true
Definition at line 434 of file lb.hpp.
References skip1pop.
Referenced by ff::ff_forall_farm< Tres >::run_then_freeze(), ff::ff_monode::skipfirstpop(), and svc().
void ff::ff_loadbalancer::stop () inline
Stops the thread.
It stops all workers and the emitter.
Definition at line 805 of file lb.hpp.
References nworkers, ff::ff_thread::stop(), and workers.
virtual void* ff::ff_loadbalancer::svc (void *) inline virtual
Load balances task.
It is a virtual function which loadbalances the task.
Implements ff::ff_thread.
Definition at line 533 of file lb.hpp.
References channelid, collect_task(), ff::diffmsec(), ff::ff_node::eosnotify(), ff::FF_EOS, ff::FF_EOS_NOFREEZE, FFTRACE, filter, get_in_buffer(), ff::ff_node::get_in_buffer(), GO_ON, master_worker, multi_input, multi_input_size, multi_input_start, pop(), push_eos(), push_goon(), running, schedule_task(), set_in_buffer(), skip1pop, skipfirstpop(), ff::ff_node::svc(), workers, wtstart, wtstop, and wttime.
virtual void ff::ff_loadbalancer::svc_end () inline virtual
Finalizes the loadbalancer task.
It is a virtual function which finalises the loadbalancer task.
Reimplemented from ff::ff_thread.
Definition at line 693 of file lb.hpp.
References filter, ff::ff_node::svc_end(), and tstop.
virtual int ff::ff_loadbalancer::svc_init () inline virtual
Initializes the load balancer task.
It is a virtual function which initialises the loadbalancer task.
Returns
0 if successful, otherwise -1 is returned.
Reimplemented from ff::ff_thread.
Definition at line 679 of file lb.hpp.
References filter, ff::ff_node::svc_init(), and tstart.
void ff::ff_loadbalancer::thaw (bool _freeze = false, int nw = -1) inline
Thaws the thread.
If nw != -1 it thaws running threads.
Definition at line 825 of file lb.hpp.
References nworkers, running, ff::ff_thread::thaw(), and workers.
int ff::ff_loadbalancer::wait () inline
Waits for workers to finish their task.
It waits for all workers to finish their tasks.
Returns
0 if successful, otherwise -1 is returned.
Definition at line 762 of file lb.hpp.
References ff::error(), running, ff::ff_thread::wait(), and workers.
int ff::ff_loadbalancer::wait_freezing () inline
Waits for freezing.
It waits for the freezing thread.
Returns
0 if successful, otherwise -1 is returned.
Definition at line 785 of file lb.hpp.
References ff::error(), running, ff::ff_thread::wait_freezing(), and workers.
int ff::ff_loadbalancer::waitlb () inline
Waits for load balancer.
It waits for the load balancer.
Returns
0 if successful, otherwise -1 is returned.
Definition at line 746 of file lb.hpp.
References ff::error(), and ff::ff_thread::wait().
Referenced by ff::ff_monode::wait().
virtual double ff::ff_loadbalancer::wffTime () inline virtual
FastFlow finish timing.
It returns the finishing of FastFlow timing.
Returns
The difference in FastFlow timing.
Definition at line 851 of file lb.hpp.
References ff::diffmsec(), wtstart, and wtstop.
Member Data Documentation
FFBUFFER* ff::ff_loadbalancer::buffer private
Definition at line 885 of file lb.hpp.
Referenced by collect_task(), get_in_buffer(), pop(), and set_in_buffer().
int ff::ff_loadbalancer::channelid private
Definition at line 882 of file lb.hpp.
Referenced by collect_task(), get_channel_id(), reset_channel_id(), and svc().
ff_node* ff::ff_loadbalancer::filter private
Definition at line 883 of file lb.hpp.
Referenced by collect_task(), pop(), run(), runlb(), set_filter(), svc(), svc_end(), and svc_init().
bool ff::ff_loadbalancer::master_worker private
Definition at line 887 of file lb.hpp.
Referenced by masterworker(), set_masterworker(), and svc().
int ff::ff_loadbalancer::max_nworkers private
Number of workers running.
Definition at line 879 of file lb.hpp.
Referenced by register_worker().
ff_node** ff::ff_loadbalancer::multi_input private
Definition at line 888 of file lb.hpp.
Referenced by set_multi_input(), and svc().
int ff::ff_loadbalancer::multi_input_size private
Definition at line 889 of file lb.hpp.
Referenced by set_multi_input(), and svc().
int ff::ff_loadbalancer::multi_input_start private
Definition at line 890 of file lb.hpp.
Referenced by collect_task(), and svc().
int ff::ff_loadbalancer::nextINw private
Definition at line 881 of file lb.hpp.
int ff::ff_loadbalancer::nextw private
Max number of workers allowed.
Definition at line 880 of file lb.hpp.
Referenced by ff_send_out_to(), schedule_task(), and selectworker().
int ff::ff_loadbalancer::nworkers private
Definition at line 877 of file lb.hpp.
Referenced by freeze(), ntentative(), register_worker(), run(), stop(), and thaw().
int ff::ff_loadbalancer::running private
Number of workers.
Definition at line 878 of file lb.hpp.
Referenced by broadcast_task(), getnworkers(), push_eos(), push_goon(), run(), selectworker(), svc(), thaw(), wait(), and wait_freezing().
bool ff::ff_loadbalancer::skip1pop private
Definition at line 886 of file lb.hpp.
Referenced by set_in_buffer(), skipfirstpop(), and svc().
struct timeval ff::ff_loadbalancer::tstart private
Definition at line 892 of file lb.hpp.
Referenced by ff_loadbalancer(), ffTime(), getstarttime(), and svc_init().
struct timeval ff::ff_loadbalancer::tstop private
Definition at line 893 of file lb.hpp.
Referenced by ff_loadbalancer(), ffTime(), getstoptime(), and svc_end().
ff_node** ff::ff_loadbalancer::workers private
Definition at line 884 of file lb.hpp.
Referenced by broadcast_task(), freeze(), push_eos(), push_goon(), push_task(), register_worker(), run(), schedule_task(), stop(), svc(), thaw(), wait(), wait_freezing(), and ~ff_loadbalancer().
struct timeval ff::ff_loadbalancer::wtstart private
Definition at line 894 of file lb.hpp.
Referenced by ff_loadbalancer(), getwstartime(), svc(), and wffTime().
struct timeval ff::ff_loadbalancer::wtstop private
Definition at line 895 of file lb.hpp.
Referenced by ff_loadbalancer(), getwstoptime(), svc(), and wffTime().
double ff::ff_loadbalancer::wttime private
Definition at line 896 of file lb.hpp.
Referenced by ff_loadbalancer(), and svc().
The documentation for this class was generated from the following file:
lb.hpp