fix8: FIX8::tty_save_state Class Reference
FIX8::tty_save_state Class Reference
#include <f8utils.hpp>
Public Member Functions
tty_save_state (int fd)
tty_save_state & operator= (const tty_save_state &from)
void unset_raw_mode ()
void set_raw_mode ()
Private Attributes
bool _raw_mode = false
int _fd
termio _tty_state
Detailed Description
Definition at line 1156 of file f8utils.hpp.
Constructor & Destructor Documentation
FIX8::tty_save_state::tty_save_state (int fd) inline explicit
Definition at line 1169 of file f8utils.hpp.
 : _fd(fd) {}
Member Function Documentation
tty_save_state& FIX8::tty_save_state::operator= (const tty_save_state & from) inline
Definition at line 1171 of file f8utils.hpp.
References _fd, _raw_mode, and _tty_state.
    {
       if (&from != this)
       {
          _raw_mode = from._raw_mode;
          _fd = from._fd;
 #ifndef _MSC_VER
          _tty_state = from._tty_state;
 #endif
       }
       return *this;
    }
void FIX8::tty_save_state::set_raw_mode () inline
Definition at line 1201 of file f8utils.hpp.
References _fd, _raw_mode, _tty_state, and FIX8::Str_error().
Referenced by MyMenu::get_string(), FIX8::ConsoleMenu::GetString(), and main().
    {
       if (!_raw_mode)
       {
 #ifndef _MSC_VER
 #ifdef __APPLE__
          if (ioctl(_fd, TIOCGETA, &_tty_state) < 0)
 #else
          if (ioctl(_fd, TCGETA, &_tty_state) < 0)
 #endif
          {
             std::cerr << Str_error(errno, "Cannot get ioctl") << std::endl;
             return;
          }
 #ifdef __APPLE__
          termios tty_state(_tty_state);
 #else
          termio tty_state(_tty_state);
 #endif
          tty_state.c_lflag = 0;
          tty_state.c_cc[VTIME] = 0;
          tty_state.c_cc[VMIN] = 1;
 #ifdef __APPLE__
          if (ioctl(_fd, TIOCSETA, &tty_state) < 0)
 #else
          if (ioctl(_fd, TCSETA, &tty_state) < 0)
 #endif
             std::cerr << Str_error(errno, "Cannot reset ioctl") << std::endl;
          else
 #endif
             _raw_mode = true;
       }
    }
void FIX8::tty_save_state::unset_raw_mode () inline
Definition at line 1184 of file f8utils.hpp.
References _fd, _raw_mode, _tty_state, and FIX8::Str_error().
Referenced by MyMenu::get_string(), FIX8::ConsoleMenu::GetString(), and main().
    {
       if (_raw_mode)
       {
 #ifndef _MSC_VER
 #ifdef __APPLE__
          if (ioctl(_fd, TIOCSETA, &_tty_state) < 0)
 #else
          if (ioctl(_fd, TCSETA, &_tty_state) < 0)
 #endif
             std::cerr << Str_error(errno, "Cannot reset ioctl") << std::endl;
          else
 #endif
             _raw_mode = false;
       }
    }
Member Data Documentation
int FIX8::tty_save_state::_fd private
Definition at line 1159 of file f8utils.hpp.
Referenced by operator=(), set_raw_mode(), and unset_raw_mode().
bool FIX8::tty_save_state::_raw_mode = false private
Definition at line 1158 of file f8utils.hpp.
Referenced by operator=(), set_raw_mode(), and unset_raw_mode().
termio FIX8::tty_save_state::_tty_state private
Definition at line 1164 of file f8utils.hpp.
Referenced by operator=(), set_raw_mode(), and unset_raw_mode().
The documentation for this class was generated from the following file:
f8utils.hpp