fix8: ff::zmqScatter Class Reference
ff::zmqScatter Class Reference
It provides implementation of the SCATTER communication pattern.
#include <zmqImpl.hpp>
Public Types
enum { MULTIPUT = 1 }
typedef zmqTransportMsg_t msg_t
typedef zmqTransport TransportImpl
typedef svector< msg_t > tosend_t
typedef msg_t torecv_t
typedef descriptor1_N descriptor
Public Member Functions
zmqScatter ()
zmqScatter (descriptor *D)
void setDescriptor (descriptor *D)
descriptor * getDescriptor ()
bool init (const std::string &address, const int nodeId=-1)
bool put (const tosend_t &msg)
bool putmore (const tosend_t &msg)
bool put (const msg_t &msg, const int to)
bool put (const msg_t &msg)
bool putmore (const msg_t &msg, const int to)
bool putmore (const msg_t &msg)
bool gethdr (torecv_t &msg, int &peer)
bool get (torecv_t &msg, int=0)
int getToWait () const
int putToPerform () const
bool close ()
void done ()
Protected Attributes
descriptor * desc
bool active
Detailed Description
It provides implementation of the SCATTER communication pattern.
This class is defined in zmqImpl.hpp
Definition at line 1511 of file zmqImpl.hpp.
Member Typedef Documentation
typedef descriptor1_N ff::zmqScatter::descriptor
Definition at line 1517 of file zmqImpl.hpp.
typedef zmqTransportMsg_t ff::zmqScatter::msg_t
Definition at line 1513 of file zmqImpl.hpp.
typedef msg_t ff::zmqScatter::torecv_t
Definition at line 1516 of file zmqImpl.hpp.
typedef svector<msg_t> ff::zmqScatter::tosend_t
Definition at line 1515 of file zmqImpl.hpp.
typedef zmqTransport ff::zmqScatter::TransportImpl
Definition at line 1514 of file zmqImpl.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MULTIPUT
Definition at line 1518 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::zmqScatter::zmqScatter () inline
Constructor (1)
It creates an empty scatter.
Definition at line 1525 of file zmqImpl.hpp.
ff::zmqScatter::zmqScatter (descriptor * D) inline
Constructor (2)
It creates a scatter with a scriptor.
D is the descriptor.
Definition at line 1534 of file zmqImpl.hpp.
Member Function Documentation
bool ff::zmqScatter::close () inline
It closes communication pattern
Returns
TODO
Definition at line 1673 of file zmqImpl.hpp.
References active, ff::descriptor1_N::close(), and desc.
void ff::zmqScatter::done () inline
The communication finished.
Definition at line 1683 of file zmqImpl.hpp.
bool ff::zmqScatter::get (torecv_t & msg, int = 0) inline
It receives one message.
Returns
TODO
Definition at line 1654 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recv().
descriptor* ff::zmqScatter::getDescriptor () inline
It returns the descriptor.
Returns
It returns the descriptor.
Definition at line 1551 of file zmqImpl.hpp.
References desc.
bool ff::zmqScatter::gethdr (torecv_t & msg, int & peer) inline
It receives the message header (should be called before get).
msg is the reference to the message. peer is the number of peers.
Returns
TODO
Definition at line 1647 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::recvhdr().
int ff::zmqScatter::getToWait () const inline
It returns the number of distinct messages for one single communication.
Returns
1 is always returned
Definition at line 1661 of file zmqImpl.hpp.
bool ff::zmqScatter::init (const std::string & address, const int nodeId = -1) inline
It initializes communication pattern.
address TOOD nodeId TODO
Returns
TODO
Definition at line 1561 of file zmqImpl.hpp.
References active, desc, and ff::descriptor1_N::init().
bool ff::zmqScatter::put (const tosend_t & msg) inline
It sends one message.
msg is the reference to the message.
Returns
TODO
Definition at line 1574 of file zmqImpl.hpp.
References desc, ff::descriptor1_N::getPeers(), ff::descriptor1_N::send(), and ff::svector< T >::size().
bool ff::zmqScatter::put (const msg_t & msg, const int to) inline
It places message.
msg is the reference to the message. to is the address of the receiving node.
Returns
TODO
Definition at line 1601 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::send().
bool ff::zmqScatter::put (const msg_t & msg) inline
It sends a message.
msg is the reference to message
Returns
A negative value is returned.
Definition at line 1612 of file zmqImpl.hpp.
bool ff::zmqScatter::putmore (const tosend_t & msg) inline
It places more messages.
msg is the reference to the message.
Returns
TODO
Definition at line 1589 of file zmqImpl.hpp.
bool ff::zmqScatter::putmore (const msg_t & msg, const int to) inline
It places many messages.
msg is the reference to the message. to is the address of the receiving node.
Returns
TODO
Definition at line 1624 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::sendmore().
bool ff::zmqScatter::putmore (const msg_t & msg) inline
It places more messages to the node.
msg is the reference to the message.
Returns
A negative value is returned.
Definition at line 1635 of file zmqImpl.hpp.
int ff::zmqScatter::putToPerform () const inline
Returns
TODO
Definition at line 1666 of file zmqImpl.hpp.
References desc, and ff::descriptor1_N::getPeers().
void ff::zmqScatter::setDescriptor (descriptor * D) inline
It sets the descriptor.
D is the descriptor.
Definition at line 1541 of file zmqImpl.hpp.
References ff::descriptor1_N::close(), and desc.
Member Data Documentation
bool ff::zmqScatter::active protected
Definition at line 1687 of file zmqImpl.hpp.
Referenced by close(), and init().
descriptor* ff::zmqScatter::desc protected
Definition at line 1686 of file zmqImpl.hpp.
Referenced by close(), get(), getDescriptor(), gethdr(), init(), put(), putmore(), putToPerform(), and setDescriptor().
The documentation for this class was generated from the following file:
zmqImpl.hpp