fix8: FIX8::Connection Class Reference
FIX8::Connection Class Reference
Complete Fix connection (reader and writer).
#include <connection.hpp>
Public Types
enum Role { cn_acceptor, cn_initiator, cn_unknown }
Roles: acceptor, initiator or unknown.
Public Member Functions
Connection (Poco::Net::StreamSocket *sock, Poco::Net::SocketAddress &addr, Session &session, Role role, const ProcessModel pmodel, unsigned hb_interval, bool secured)
virtual ~Connection ()
Dtor.
Role get_role () const
ProcessModel get_pmodel () const
bool is_secure () const
F8API void start ()
Start the reader and writer threads.
F8API void stop ()
Stop the reader and writer threads.
virtual bool connect ()
bool is_connected () const
virtual bool write (Message *from, bool destroy=true)
virtual bool write (Message &from)
size_t write_batch (const std::vector< Message * > &msgs, bool destroy)
int send (const char *from, size_t sz)
int send (const f8String &from)
void set_hb_interval (const unsigned hb_interval)
unsigned get_hb_interval () const
unsigned get_hb_interval20pc () const
Poco::Net::SocketAddress get_peer_socket_address () const
const Poco::Net::SocketAddress & get_socket_address () const
int join ()
bool is_socket_error () const
void set_recv_buf_sz (const unsigned sz) const
void set_send_buf_sz (const unsigned sz) const
void set_tcp_cork_flag (bool way) const
Session & get_session ()
int reader_execute ()
bool reader_poll (const Poco::Timespan &ts=Poco::Timespan()) const
int writer_execute ()
bool writer_poll (const Poco::Timespan &ts=Poco::Timespan()) const
Static Public Member Functions
static void set_recv_buf_sz (const unsigned sz, Poco::Net::Socket *sock)
static void set_send_buf_sz (const unsigned sz, Poco::Net::Socket *sock)
Protected Attributes
Poco::Net::StreamSocket * _sock
Poco::Net::SocketAddress _addr
f8_atomic< bool > _connected
Session & _session
Role _role
ProcessModel _pmodel
unsigned _hb_interval
unsigned _hb_interval20pc
FIXReader _reader
FIXWriter _writer
bool _secured
Detailed Description
Complete Fix connection (reader and writer).
Definition at line 508 of file connection.hpp.
Member Enumeration Documentation
enum FIX8::Connection::Role
Roles: acceptor, initiator or unknown.
Enumerator
cn_acceptor
cn_initiator
cn_unknown
Definition at line 512 of file connection.hpp.
 { cn_acceptor, cn_initiator, cn_unknown };
Constructor & Destructor Documentation
FIX8::Connection::Connection (Poco::Net::StreamSocket * sock, Poco::Net::SocketAddress & addr, Session & session, Role role, const ProcessModel pmodel, unsigned hb_interval, bool secured) inline
Ctor.
Parameters
sock connected socket
addr sock address structure
session session
role connection role
pmodel process model
hb_interval heartbeat interval
secured true for ssl connection
Definition at line 537 of file connection.hpp.
       : _sock(sock), _addr(addr), _connected(role == cn_acceptor), _session(session), _role(role), _pmodel(pmodel),
         _hb_interval(hb_interval), _hb_interval20pc(hb_interval + hb_interval / 5),
         _reader(sock, session, pmodel), _writer(sock, session, pmodel),
         _secured(secured) {}
virtual FIX8::Connection::~Connection () inline virtual
Dtor.
Definition at line 545 of file connection.hpp.
References FIX8::Session::clear_connection(), and stop().
 { stop(); _session.clear_connection(this); }
Member Function Documentation
virtual bool FIX8::Connection::connect () inline virtual
Get the connection state.
Returns
true if connected
Reimplemented in FIX8::ClientConnection.
Definition at line 567 of file connection.hpp.
References _connected.
Referenced by FIX8::Session::start().
 { return _connected; }
unsigned FIX8::Connection::get_hb_interval () const inline
Get the heartbeat interval for this connection.
Returns
the heartbeat interval
Definition at line 608 of file connection.hpp.
References _hb_interval.
Referenced by FIX8::Session::handle_logon(), FIX8::Session::heartbeat_service(), and FIX8::Session::start().
 { return _hb_interval; }
unsigned FIX8::Connection::get_hb_interval20pc () const inline
Get the heartbeat interval + %20 for this connection.
Returns
the heartbeat interval + %20
Definition at line 612 of file connection.hpp.
References _hb_interval20pc.
Referenced by FIX8::Session::heartbeat_service().
 { return _hb_interval20pc; }
Poco::Net::SocketAddress FIX8::Connection::get_peer_socket_address () const inline
Get the peer socket address
Returns
peer socket address reference
Definition at line 616 of file connection.hpp.
Referenced by FIX8::Session::handle_logon().
 { return _sock->peerAddress(); }
ProcessModel FIX8::Connection::get_pmodel () const inline
Get the process model
Returns
the process model
Definition at line 553 of file connection.hpp.
References _pmodel.
Referenced by FIX8::Session::handle_logon(), FIX8::Session::recover_seqnums(), FIX8::Session::send_process(), FIX8::Session::stop(), and FIX8::Session::update_persist_seqnums().
 { return _pmodel; }
Role FIX8::Connection::get_role () const inline
Get the role for this connection.
Returns
the role
Definition at line 549 of file connection.hpp.
References _role.
Referenced by FIX8::Session::handle_logon(), FIX8::Session::start(), FIX8::Session::stop(), and FIX8::Session::~Session().
 { return _role; }
Session& FIX8::Connection::get_session () inline
Get the session associated with this connection.
Returns
the session
Definition at line 670 of file connection.hpp.
References _session.
 { return _session; }
const Poco::Net::SocketAddress& FIX8::Connection::get_socket_address () const inline
Get the socket address
Returns
socket address reference
Definition at line 620 of file connection.hpp.
References _addr.
 { return _addr; }
bool FIX8::Connection::is_connected () const inline
Determine if this session is actually connected
Returns
true if connected
Definition at line 571 of file connection.hpp.
References _connected.
Referenced by FIX8::Session::activation_service(), and FIX8::Session::heartbeat_service().
 { return _connected; }
bool FIX8::Connection::is_secure () const inline
Check if this connection is secure
Returns
true if secure
Definition at line 557 of file connection.hpp.
References _secured.
 { return _secured; }
bool FIX8::Connection::is_socket_error () const inline
Check to see if the socket is in error
Returns
true if there was a socket error
Definition at line 628 of file connection.hpp.
References FIX8::FIXReader::is_socket_error().
 { return _reader.is_socket_error(); }
int FIX8::Connection::join () inline
Wait till reader thead has finished.
Returns
0 on success
Definition at line 624 of file connection.hpp.
References FIX8::FIXReader::join().
Referenced by FIX8::Session::start().
 { return _reader.join(); }
int FIX8::Connection::reader_execute () inline
Call the FIXreader method
Returns
result of call
Definition at line 674 of file connection.hpp.
References FIX8::AsyncSocket< T >::cancellation_token(), and FIX8::FIXReader::execute().
 { return _reader.execute(_reader.cancellation_token()); }
bool FIX8::Connection::reader_poll (const Poco::Timespan & ts = Poco::Timespan()) const inline
Check if the reader will block
Parameters
ts timeout
Returns
true if won't block
Definition at line 679 of file connection.hpp.
References FIX8::FIXReader::poll().
 { return _reader.poll(ts); }
int FIX8::Connection::send (const char * from, size_t sz) inline
Write a string message to the underlying socket.
Parameters
from Message (string) to write
sz number bytes to send
Returns
number of bytes written
Definition at line 594 of file connection.hpp.
References FIX8::FIXWriter::send().
Referenced by FIX8::Session::send_process().
 { return _writer.send(from, sz); }
int FIX8::Connection::send (const f8String & from) inline
Write a string message to the underlying socket.
Parameters
from Message (string) to write
Returns
number of bytes written
Definition at line 599 of file connection.hpp.
References FIX8::FIXWriter::send().
 { return _writer.send(from.data(), from.size()); }
void FIX8::Connection::set_hb_interval (const unsigned hb_interval) inline
Set the heartbeat interval for this connection.
Parameters
hb_interval heartbeat interval
Definition at line 603 of file connection.hpp.
References FIX8::defaults::hb_interval.
Referenced by FIX8::Session::handle_logon().
       { _hb_interval = hb_interval; _hb_interval20pc = hb_interval + hb_interval / 5; }
static void FIX8::Connection::set_recv_buf_sz (const unsigned sz, Poco::Net::Socket * sock) inline static
Set the socket recv buffer sz
Parameters
sock socket to operate on
sz new size
Definition at line 633 of file connection.hpp.
References glout_info.
Referenced by FIX8::ServerSession< T >::ServerSession().
    {
       const unsigned current_sz(sock->getReceiveBufferSize());
       sock->setReceiveBufferSize(sz);
       glout_info << "fd(" << sock->impl()->sockfd() << ") ReceiveBufferSize old:" << current_sz
          << " requested:" << sz << " new:" << sock->getReceiveBufferSize();
    }
void FIX8::Connection::set_recv_buf_sz (const unsigned sz) const inline
Set the socket recv buffer sz
Parameters
sz new size
Definition at line 653 of file connection.hpp.
References set_recv_buf_sz().
Referenced by set_recv_buf_sz().
 { set_recv_buf_sz(sz, _sock); }
static void FIX8::Connection::set_send_buf_sz (const unsigned sz, Poco::Net::Socket * sock) inline static
Set the socket send buffer sz
Parameters
sock socket to operate on
sz new size
Definition at line 644 of file connection.hpp.
References glout_info.
Referenced by FIX8::ServerSession< T >::ServerSession().
    {
       const unsigned current_sz(sock->getSendBufferSize());
       sock->setSendBufferSize(sz);
       glout_info << "fd(" << sock->impl()->sockfd() << ") SendBufferSize old:" << current_sz
          << " requested:" << sz << " new:" << sock->getSendBufferSize();
    }
void FIX8::Connection::set_send_buf_sz (const unsigned sz) const inline
Set the socket send buffer sz
Parameters
sz new size
Definition at line 657 of file connection.hpp.
References set_send_buf_sz().
Referenced by set_send_buf_sz().
 { set_send_buf_sz(sz, _sock); }
void FIX8::Connection::set_tcp_cork_flag (bool way) const inline
Set the tcp_cork flag
Parameters
way boolean true (on) or false(clear)
Definition at line 661 of file connection.hpp.
Referenced by MyMenu::send_all_preloaded().
    {
 #if defined FIX8_HAVE_DECL_TCP_CORK && TCP_CORK != 0
       _sock->setOption(IPPROTO_TCP, TCP_CORK, way ? 1 : 0);
 #endif
    }
void Connection::start ()
Start the reader and writer threads.
Definition at line 315 of file connection.cpp.
Referenced by FIX8::ReliableClientSession< T >::operator()(), and FIX8::Session::start().
 {
    _writer.start();
    _reader.start();
 }
void Connection::stop ()
Stop the reader and writer threads.
Definition at line 322 of file connection.cpp.
References scout_debug.
Referenced by FIX8::Session::stop(), ~Connection(), and FIX8::SessionInstance< T >::~SessionInstance().
 {
    scout_debug << "Connection::stop()";
    _writer.stop();
    _writer.join();
    scout_debug << "Connection::stop() => _reader.stop()";
    _reader.stop();
    if (_reader.started())
       _reader.socket()->shutdown();
    _reader.join();
 }
virtual bool FIX8::Connection::write (Message * from, bool destroy = true) inline virtual
Write a message to the underlying socket.
Parameters
from Message to write
destroy if true delete after send
Returns
true on success
Definition at line 577 of file connection.hpp.
References FIX8::FIXWriter::write().
Referenced by FIX8::Session::send().
 { return _writer.write(from, destroy); }
virtual bool FIX8::Connection::write (Message & from) inline virtual
Write a message to the underlying socket. Non-pipelined version.
Parameters
from Message to write
Returns
true on success
Definition at line 582 of file connection.hpp.
References FIX8::FIXWriter::write().
 { return _writer.write(from); }
size_t FIX8::Connection::write_batch (const std::vector< Message * > & msgs, bool destroy) inline
Write messages to the underlying socket as a single batch.
Parameters
msgs vector of Message to write
destroy if true delete after send
Returns
true on success
Definition at line 588 of file connection.hpp.
References FIX8::FIXWriter::write_batch().
Referenced by FIX8::Session::send_batch().
 { return _writer.write_batch(msgs, destroy); }
int FIX8::Connection::writer_execute () inline
Call the FIXreader method
Returns
result of call
Definition at line 683 of file connection.hpp.
References FIX8::AsyncSocket< T >::cancellation_token(), and FIX8::FIXWriter::execute().
 { return _writer.execute(_writer.cancellation_token()); }
bool FIX8::Connection::writer_poll (const Poco::Timespan & ts = Poco::Timespan()) const inline
Check if the writer will block
Parameters
ts timeout
Returns
true if won't block
Definition at line 688 of file connection.hpp.
References FIX8::FIXWriter::poll().
Referenced by MyMenu::send_all_preloaded().
 { return _writer.poll(ts); }
Member Data Documentation
Poco::Net::SocketAddress FIX8::Connection::_addr protected
Definition at line 516 of file connection.hpp.
Referenced by get_socket_address().
f8_atomic<bool> FIX8::Connection::_connected protected
Definition at line 517 of file connection.hpp.
Referenced by connect(), and is_connected().
unsigned FIX8::Connection::_hb_interval protected
Definition at line 521 of file connection.hpp.
Referenced by get_hb_interval().
unsigned FIX8::Connection::_hb_interval20pc protected
Definition at line 521 of file connection.hpp.
Referenced by get_hb_interval20pc().
ProcessModel FIX8::Connection::_pmodel protected
Definition at line 520 of file connection.hpp.
Referenced by get_pmodel().
FIXReader FIX8::Connection::_reader protected
Definition at line 523 of file connection.hpp.
Role FIX8::Connection::_role protected
Definition at line 519 of file connection.hpp.
Referenced by get_role().
bool FIX8::Connection::_secured protected
Definition at line 525 of file connection.hpp.
Referenced by is_secure().
Session& FIX8::Connection::_session protected
Definition at line 518 of file connection.hpp.
Referenced by get_session().
Poco::Net::StreamSocket* FIX8::Connection::_sock protected
Definition at line 515 of file connection.hpp.
FIXWriter FIX8::Connection::_writer protected
Definition at line 524 of file connection.hpp.
The documentation for this class was generated from the following files:
connection.hpp
connection.cpp