fix8: ff::dynqueue Class Reference
ff::dynqueue Class Reference
TODO.
#include <dynqueue.hpp>
Classes
struct Node
Public Types
enum { DEFAULT_CACHE_SIZE =1024 }
Public Member Functions
dynqueue (int cachesize=DEFAULT_CACHE_SIZE, bool fillcache=false)
bool init ()
~dynqueue ()
bool push (void *const data)
bool pop (void **data)
unsigned long length () const
bool mp_push (void *const data)
bool mp_pop (void **data)
Private Member Functions
Node * allocnode ()
Node * mp_allocnode ()
Private Attributes
Node *volatile head
long padding1 [longxCacheLine-(sizeof(Node *)/sizeof(long))]
Node *volatile tail
long padding2 [longxCacheLine-(sizeof(Node *)/sizeof(long))]
lock_t P_lock
long padding3 [longxCacheLine-sizeof(lock_t)]
lock_t C_lock
long padding4 [longxCacheLine-sizeof(lock_t)]
SWSR_Ptr_Buffer cache
Detailed Description
TODO.
This class is defined in dynqueue.hpp
Definition at line 65 of file dynqueue.hpp.
Member Enumeration Documentation
anonymous enum
TODO
Enumerator
DEFAULT_CACHE_SIZE
Definition at line 132 of file dynqueue.hpp.
Constructor & Destructor Documentation
ff::dynqueue::dynqueue (int cachesize = DEFAULT_CACHE_SIZE, bool fillcache = false) inline
TODO
Definition at line 137 of file dynqueue.hpp.
References C_lock, cache, ff::dynqueue::Node::data, head, ff::SWSR_Ptr_Buffer::init(), init_unlocked(), ff::dynqueue::Node::next, P_lock, ff::SWSR_Ptr_Buffer::push(), and tail.
ff::dynqueue::~dynqueue () inline
TODO
Definition at line 160 of file dynqueue.hpp.
References ff::SWSR_Ptr_Buffer::buffersize(), cache, head, ff::dynqueue::Node::next, ff::SWSR_Ptr_Buffer::pop(), and tail.
Member Function Documentation
Node* ff::dynqueue::allocnode () inline private
TODO
Definition at line 102 of file dynqueue.hpp.
References cache, and ff::SWSR_Ptr_Buffer::pop().
Referenced by push().
bool ff::dynqueue::init () inline
TODO
Definition at line 155 of file dynqueue.hpp.
unsigned long ff::dynqueue::length () const inline
TODO
Definition at line 212 of file dynqueue.hpp.
Node* ff::dynqueue::mp_allocnode () inline private
TODO
Definition at line 114 of file dynqueue.hpp.
References cache, P_lock, ff::SWSR_Ptr_Buffer::pop(), spin_lock(), and spin_unlock().
Referenced by mp_push().
bool ff::dynqueue::mp_pop (void ** data) inline
MS 2-lock MPMC algorithm POP method
Definition at line 231 of file dynqueue.hpp.
References C_lock, cache, head, ff::dynqueue::Node::next, ff::SWSR_Ptr_Buffer::push(), spin_lock(), and spin_unlock().
bool ff::dynqueue::mp_push (void *const data) inline
MS 2-lock MPMC algorithm PUSH method
Definition at line 217 of file dynqueue.hpp.
References ff::dynqueue::Node::data, data, mp_allocnode(), ff::dynqueue::Node::next, P_lock, spin_lock(), spin_unlock(), and tail.
bool ff::dynqueue::pop (void ** data) inline
TODO
Definition at line 188 of file dynqueue.hpp.
References cache, head, ff::dynqueue::Node::next, ff::SWSR_Ptr_Buffer::push(), and tail.
Referenced by ff::BufferPool::next_r(), ff::BufferPool::reset(), and ff::BufferPool::~BufferPool().
bool ff::dynqueue::push (void *const data) inline
TODO
Definition at line 174 of file dynqueue.hpp.
References allocnode(), ff::dynqueue::Node::data, data, ff::dynqueue::Node::next, and tail.
Referenced by ff::BufferPool::next_w().
Member Data Documentation
lock_t ff::dynqueue::C_lock private
Definition at line 86 of file dynqueue.hpp.
Referenced by dynqueue(), and mp_pop().
SWSR_Ptr_Buffer ff::dynqueue::cache private
Definition at line 95 of file dynqueue.hpp.
Referenced by allocnode(), dynqueue(), mp_allocnode(), mp_pop(), pop(), and ~dynqueue().
Node* volatile ff::dynqueue::head private
Definition at line 72 of file dynqueue.hpp.
Referenced by dynqueue(), mp_pop(), pop(), and ~dynqueue().
lock_t ff::dynqueue::P_lock private
Definition at line 84 of file dynqueue.hpp.
Referenced by dynqueue(), mp_allocnode(), and mp_push().
long ff::dynqueue::padding1[longxCacheLine-(sizeof(Node *)/sizeof(long))] private
Definition at line 73 of file dynqueue.hpp.
long ff::dynqueue::padding2[longxCacheLine-(sizeof(Node *)/sizeof(long))] private
Definition at line 75 of file dynqueue.hpp.
long ff::dynqueue::padding3[longxCacheLine-sizeof(lock_t)] private
Definition at line 85 of file dynqueue.hpp.
long ff::dynqueue::padding4[longxCacheLine-sizeof(lock_t)] private
Definition at line 87 of file dynqueue.hpp.
Node* volatile ff::dynqueue::tail private
Definition at line 74 of file dynqueue.hpp.
Referenced by dynqueue(), mp_push(), pop(), push(), and ~dynqueue().
The documentation for this class was generated from the following file:
dynqueue.hpp