fix8: FIX8::AsyncSocket< T > Class Template Reference
FIX8::AsyncSocket< T > Class Template Reference
Half duplex async socket wrapper with thread.
#include <connection.hpp>
Public Member Functions
AsyncSocket (Poco::Net::StreamSocket *sock, Session &session, const ProcessModel pmodel=pm_pipeline)
virtual ~AsyncSocket ()=default
Dtor.
size_t queued () const
bool started () const
int operator() ()
virtual int execute (f8_thread_cancellation_token &cancellation_token)
virtual void start ()
Start the processing thread.
virtual void request_stop ()
Start the processing thread.
virtual void quit ()
Stop the processing thread and quit.
Poco::Net::StreamSocket * socket ()
int join ()
f8_thread_cancellation_token & cancellation_token ()
Protected Attributes
coroutine _coro
Poco::Net::StreamSocket * _sock
f8_concurrent_queue< T > _msg_queue
Session & _session
ProcessModel _pmodel
f8_thread_cancellation_token _cancellation_token
f8_atomic< bool > _started
Private Attributes
f8_thread< AsyncSocket > _thread
Detailed Description
template<typename T>
class FIX8::AsyncSocket< T >
Half duplex async socket wrapper with thread.
Template Parameters
T the object type to queue
Definition at line 53 of file connection.hpp.
Constructor & Destructor Documentation
template<typename T> FIX8::AsyncSocket< T >::AsyncSocket (Poco::Net::StreamSocket * sock, Session & session, const ProcessModel pmodel = pm_pipeline) inline
Ctor.
Parameters
sock connected socket
session session
pmodel process model
Definition at line 72 of file connection.hpp.
       : _sock(sock), _session(session), _pmodel(pmodel), _started(false), _thread(std::ref(*this)) {}
template<typename T> virtual FIX8::AsyncSocket< T >::~AsyncSocket () virtual default
Dtor.
Member Function Documentation
template<typename T> f8_thread_cancellation_token& FIX8::AsyncSocket< T >::cancellation_token () inline
Obtain the thread cancellation token
Returns
the token
Definition at line 124 of file connection.hpp.
Referenced by FIX8::Connection::reader_execute(), and FIX8::Connection::writer_execute().
 { return _cancellation_token; }
template<typename T> virtual int FIX8::AsyncSocket< T >::execute (f8_thread_cancellation_token & cancellation_token) inline virtual
Execute the function operator
Returns
result of operator
Reimplemented in FIX8::FIXWriter, and FIX8::FIXReader.
Definition at line 92 of file connection.hpp.
Referenced by FIX8::AsyncSocket< f8String >::operator()().
 { return 0; }
template<typename T> int FIX8::AsyncSocket< T >::join () inline
Wait till processing thead has finished.
Returns
0 on success
Definition at line 120 of file connection.hpp.
Referenced by FIX8::FIXReader::join(), FIX8::FIXWriter::join(), and FIX8::AsyncSocket< f8String >::quit().
 { return _started ? _thread.join() : 0; }
template<typename T> int FIX8::AsyncSocket< T >::operator() () inline
Function operator. Called by thread to process message on queue.
Returns
0 on success
Definition at line 88 of file connection.hpp.
 { return execute(_cancellation_token); }
template<typename T> size_t FIX8::AsyncSocket< T >::queued () const inline
Get the number of messages queued on this socket.
Returns
number of queued messages
Definition at line 80 of file connection.hpp.
 { return _msg_queue.size(); }
template<typename T> virtual void FIX8::AsyncSocket< T >::quit () inline virtual
Stop the processing thread and quit.
Reimplemented in FIX8::FIXWriter, and FIX8::FIXReader.
Definition at line 112 of file connection.hpp.
Referenced by FIX8::FIXReader::quit(), and FIX8::FIXWriter::quit().
 { _thread.request_stop(); join(); }
template<typename T> virtual void FIX8::AsyncSocket< T >::request_stop () inline virtual
Start the processing thread.
Definition at line 109 of file connection.hpp.
Referenced by FIX8::FIXReader::stop(), and FIX8::FIXWriter::stop().
 { _thread.request_stop(); }
template<typename T> Poco::Net::StreamSocket* FIX8::AsyncSocket< T >::socket () inline
Get the underlying socket object.
Returns
the socket
Definition at line 116 of file connection.hpp.
 { return _sock; }
template<typename T> virtual void FIX8::AsyncSocket< T >::start () inline virtual
Start the processing thread.
Reimplemented in FIX8::FIXWriter, and FIX8::FIXReader.
Definition at line 95 of file connection.hpp.
Referenced by FIX8::FIXReader::start(), and FIX8::FIXWriter::start().
    {
       if (!_started)
       {
          _started = true;
          _thread.start();
       }
       else
       {
          glout_warn << "AsyncSocket already started.";
       }
    }
template<typename T> bool FIX8::AsyncSocket< T >::started () const inline
Check if this socket has started
Returns
true if started
Definition at line 84 of file connection.hpp.
 { return _started; }
Member Data Documentation
template<typename T> f8_thread_cancellation_token FIX8::AsyncSocket< T >::_cancellation_token protected
Definition at line 61 of file connection.hpp.
Referenced by FIX8::AsyncSocket< f8String >::cancellation_token().
template<typename T> coroutine FIX8::AsyncSocket< T >::_coro protected
Definition at line 56 of file connection.hpp.
template<typename T> f8_concurrent_queue<T> FIX8::AsyncSocket< T >::_msg_queue protected
Definition at line 58 of file connection.hpp.
template<typename T> ProcessModel FIX8::AsyncSocket< T >::_pmodel protected
Definition at line 60 of file connection.hpp.
template<typename T> Session& FIX8::AsyncSocket< T >::_session protected
Definition at line 59 of file connection.hpp.
template<typename T> Poco::Net::StreamSocket* FIX8::AsyncSocket< T >::_sock protected
Definition at line 57 of file connection.hpp.
Referenced by FIX8::AsyncSocket< f8String >::socket().
template<typename T> f8_atomic<bool> FIX8::AsyncSocket< T >::_started protected
Definition at line 62 of file connection.hpp.
Referenced by FIX8::AsyncSocket< f8String >::started().
template<typename T> f8_thread<AsyncSocket> FIX8::AsyncSocket< T >::_thread private
Definition at line 65 of file connection.hpp.
The documentation for this class was generated from the following file:
connection.hpp