fix8: ff::ff_monode Class Reference
ff::ff_monode Class Reference abstract
Multiple output FastFlow node.
#include <farm.hpp>
Public Member Functions
ff_monode (int max_num_workers=ff_farm<>::DEF_MAX_NUM_WORKERS)
Constructor.
~ff_monode ()
Destructor.
virtual int set_output (std::vector< ff_node * > &w)=0
Sets the output buffer.
void skipfirstpop (bool sk)
Skips the first pop.
int run (bool skip_init=false)
Executes the farm.
ff_loadbalancer * getlb () const
Gets the internal gatherer.
Public Member Functions inherited from ff::ff_node
virtual void * svc (void *task)=0
The svc method.
virtual int svc_init ()
The svc_init()
virtual void svc_end ()
The svc_end()
virtual void eosnotify (int id=-1)
Notifies EOS.
virtual int get_my_id () const
Gets the ID of the ff_node.
virtual void setAffinity (int cpuID)
Sets threads affinity.
virtual int getCPUId () const
Gets the CPU id (if set) of this node is pinned.
virtual bool put (void *ptr)
Pushes the task.
virtual bool get (void **ptr)
Pops the task.
virtual FFBUFFER * get_in_buffer () const
Gets input buffer.
virtual FFBUFFER * get_out_buffer () const
Gets pointer to the output buffer.
virtual struct timeval getstarttime () const
Gets start time.
virtual struct timeval getstoptime () const
Gets stop time.
virtual struct timeval getwstartime () const
Gets start time.
virtual struct timeval getwstoptime () const
Gets the stop time.
virtual void svc_createOCL ()
Create OCL.
virtual void svc_releaseOCL ()
Releases OCL.
void reset ()
Resets input/output queues.
Protected Member Functions
int cardinality (BARRIER_T *const barrier)
Cardinatlity.
int wait ()
Wait.
Protected Member Functions inherited from ff::ff_node
void set_id (int id)
Sets the node identifer.
virtual bool push (void *ptr)
Pushes to output buffer.
virtual bool pop (void **ptr)
Pops the data from input buffer.
bool skipfirstpop () const
Gets the status of skipfirstpop.
virtual int create_input_buffer (int nentries, bool fixedsize=true)
Creates the input buffer.
virtual int create_output_buffer (int nentries, bool fixedsize=false)
Creates the output buffer.
virtual int set_output_buffer (FFBUFFER *const o)
Sets the output buffer.
virtual int set_input_buffer (FFBUFFER *const i)
Sets the input buffer.
virtual int freeze_and_run (bool=false)
Freezes the thread and then run.
virtual int wait_freezing ()
Waits for thread to thaw.
virtual void stop ()
Stops the thread.
virtual void freeze ()
Freezes the thread.
virtual void thaw (bool _freeze=false)
Checks to thaw a thread.
virtual bool isfrozen ()
Checks if the thread is frozen.
virtual void set_barrier (BARRIER_T *const b)
Sets the barrier.
virtual double ffTime ()
Gets the time.
virtual double wffTime ()
Gets the time.
ff_node ()
Protected constructor.
virtual ~ff_node ()
Destructor.
virtual bool ff_send_out (void *task, unsigned int retry=((unsigned int)-1), unsigned int ticks=(TICKS2WAIT))
Sends out the task.
virtual void input_active (const bool onoff)
Private Attributes
ff_loadbalancer * lb
Additional Inherited Members
Public Types inherited from ff::ff_node
enum { TICKS2WAIT =1000 }
Detailed Description
Multiple output FastFlow node.
This class defines the FastFlow node with multiple output buffers.
This class is defined in farm.hpp
Definition at line 1574 of file farm.hpp.
Constructor & Destructor Documentation
ff::ff_monode::ff_monode (int max_num_workers = ff_farm<>::DEF_MAX_NUM_WORKERS) inline
Constructor.
It creates a FastFlow node with multiple output buffers.
max_num_workers defines the maximum number of workers
Definition at line 1613 of file farm.hpp.
ff::ff_monode::~ff_monode () inline
Destructor.
It deletes the load balancer.
Definition at line 1621 of file farm.hpp.
References lb.
Member Function Documentation
int ff::ff_monode::cardinality (BARRIER_T *const barrier) inline protected virtual
Cardinatlity.
Defines the cardinatlity of the FastFlow node.
barrier defines the barrier
Returns
1 is always returned.
Reimplemented from ff::ff_node.
Definition at line 1586 of file farm.hpp.
References lb, and ff::ff_thread::set_barrier().
ff_loadbalancer* ff::ff_monode::getlb () const inline
Gets the internal gatherer.
It gets the internal gatherer.
Returns
A pointer to the FastFlow load balancer
Definition at line 1681 of file farm.hpp.
References lb.
int ff::ff_monode::run (bool skip_init = false) inline virtual
Executes the farm.
It executes the farm.
skip_init defines if the initilization should be skipped
Returns
0 if successful, otherwsie -1 is returned.
Reimplemented from ff::ff_node.
Definition at line 1651 of file farm.hpp.
References ff::error(), lb, ff::ff_loadbalancer::register_worker(), ff::ff_loadbalancer::runlb(), ff::ff_loadbalancer::set_filter(), and set_output().
virtual int ff::ff_monode::set_output (std::vector< ff_node * > & w) pure virtual
Sets the output buffer.
It is a virtual function which sets the output buffer.
Referenced by run().
void ff::ff_monode::skipfirstpop (bool sk) inline virtual
Skips the first pop.
It skips the first pop.
Reimplemented from ff::ff_node.
Definition at line 1637 of file farm.hpp.
References lb, and ff::ff_loadbalancer::skipfirstpop().
int ff::ff_monode::wait () inline protected virtual
Wait.
It waits for TODO. Wait for what?
Returns
0 if successful, otherwise -1 is returned.
Reimplemented from ff::ff_node.
Definition at line 1598 of file farm.hpp.
References lb, and ff::ff_loadbalancer::waitlb().
Member Data Documentation
ff_loadbalancer* ff::ff_monode::lb private
Definition at line 1695 of file farm.hpp.
Referenced by cardinality(), getlb(), run(), skipfirstpop(), wait(), and ~ff_monode().
The documentation for this class was generated from the following file:
farm.hpp