fix8: XmlElement Class Reference
XmlElement Class Reference
A simple xml parser with Xpath style lookup.
#include <xml.hpp>
Classes
struct EntityOrderComp
Comparitor.
Public Types
enum Flags { noextensions, nocase }
using XmlSet = std::set< const XmlElement *, EntityOrderComp >
using XmlAttrs = std::map< std::string, std::string >
using XmlFlags = FIX8::ebitset< Flags >
Public Member Functions
F8API XmlElement (std::istream &ifs, int subidx, XmlElement *parent=nullptr, int txtline=0, int depth=0, const char *rootAttr=nullptr)
virtual F8API ~XmlElement ()
Dtor.
XmlElement (const XmlElement &)=delete
Copy Ctor. Non-copyable.
XmlElement & operator= (const XmlElement &)=delete
Assignment operator. Non-copyable.
F8API int ParseAttrs (const std::string &attlst)
F8API const XmlElement * find (const std::string &what, const std::string *atag=nullptr, const std::string *aval=nullptr, const char delim='/') const
F8API int find (const std::string &what, XmlSet &eset, const std::string *atag=nullptr, const std::string *aval=nullptr, const char delim='/') const
F8API const XmlElement * find_child (const std::string &what, const std::string *atag=nullptr, const std::string *aval=nullptr, const char delim='/') const
F8API int find_child (const std::string &what, XmlSet &eset, const std::string *atag=nullptr, const std::string *aval=nullptr, const char delim='/') const
F8API bool GetAttr (const std::string &what, std::string &target) const
bool GetAttrValue (std::string &target) const
bool HasAttr (const std::string &what) const
bool FindAttrGetValue (const std::string &what, std::string &target)
F8API bool findAttrByValue (const std::string &what, const std::string &value) const
template<typename T >
T FindAttr (const std::string &what, const T defValue) const
template<typename T >
T & FindAttrRef (const std::string &what, T &target) const
F8API bool Insert (XmlElement *what)
F8API const std::string & InplaceXlate (std::string &what)
int GetDepth () const
int GetErrorCnt () const
int GetLineCnt () const
int GetChildCnt () const
int GetLine () const
int GetSubIdx () const
int GetSequence () const
int GetMaxDepthPermitted () const
int GetMaxDepth () const
std::string GetPath () const
const std::string & GetTag () const
std::string GetLocString () const
const std::string * GetVal () const
const std::string * GetDecl () const
XmlAttrs::const_iterator abegin () const
XmlAttrs::const_iterator aend () const
XmlSet::const_iterator begin () const
XmlSet::const_iterator end () const
const XmlElement * GetRoot () const
const XmlElement * GetParent () const
Static Public Member Functions
static void set_flags (XmlFlags flags)
static F8API XmlElement * Factory (std::istream &istr, const char *docpath=nullptr)
static F8API XmlElement * Factory (const std::string &fname)
Public Attributes
XmlAttrs * attrs_
Static Public Attributes
static F8API const XmlAttrs emptyattrs_
static XmlFlags flags_
Private Types
enum { MaxDepth = 128 }
Maximum depth levels supported.
using XmlSubEls = std::multimap< std::string, XmlElement * >
Private Attributes
XmlElement * parent_
XmlElement * root_
int errors_
int line_
int incline_
int maxdepth_
int seq_
std::string inclusion_
std::string tag_
std::string * value_
std::string * decl_
int depth_
int sequence_
int txtline_
int chldcnt_
int subidx_
XmlSubEls * children_
simple n-ary tree
bool _was_include
XmlSet * ordchildren_
Set of all child elements in file order.
Static Private Attributes
static const Str2Chr stringtochar_
XML entity char lookup.
static FIX8::RegExp rCE_
static FIX8::RegExp rCX_
static FIX8::RegExp rIn_
static FIX8::RegExp rEn_
static FIX8::RegExp rEv_
static F8API const XmlSet emptyset_
Friends
F8API std::ostream & operator<< (std::ostream &os, const XmlElement &en)
Detailed Description
A simple xml parser with Xpath style lookup.
Definition at line 48 of file xml.hpp.
Member Typedef Documentation
using XmlElement::XmlAttrs = std::map<std::string, std::string>
Definition at line 75 of file xml.hpp.
using XmlElement::XmlFlags = FIX8::ebitset<Flags>
Definition at line 80 of file xml.hpp.
using XmlElement::XmlSet = std::set<const XmlElement *, EntityOrderComp>
XmlSet ordering preserved from source file
Definition at line 74 of file xml.hpp.
using XmlElement::XmlSubEls = std::multimap<std::string, XmlElement *> private
Definition at line 85 of file xml.hpp.
Member Enumeration Documentation
anonymous enum private
Maximum depth levels supported.
Enumerator
MaxDepth
Definition at line 54 of file xml.hpp.
 { MaxDepth = 128 };
enum XmlElement::Flags
Enumerator
noextensions
nocase
Definition at line 79 of file xml.hpp.
 { noextensions, nocase };
Constructor & Destructor Documentation
F8API XmlElement::XmlElement (std::istream & ifs, int subidx, XmlElement * parent = nullptr, int txtline = 0, int depth = 0, const char * rootAttr = nullptr)
Ctor.
Parameters
ifs input file stream
subidx the subindex for this child
parent parent XmlElement element
txtline xml sourcefile line number
depth depth nesting level
rootAttr root attribute string
XmlElement::~XmlElement () virtual
Dtor.
Definition at line 650 of file xml.cpp.
References _was_include, attrs_, children_, decl_, ordchildren_, and value_.
 {
    delete value_;
    delete attrs_;
    delete decl_;
    if (children_ && !_was_include)
       for_each (children_->begin(), children_->end(), [](XmlSubEls::value_type& pp) { delete pp.second; });
    delete children_;
    delete ordchildren_;
 }
XmlElement::XmlElement (const XmlElement &) delete
Copy Ctor. Non-copyable.
Member Function Documentation
XmlAttrs::const_iterator XmlElement::abegin () const inline
Get an iterator to the first child attribute.
Returns
const_iterator to first attribute
Definition at line 324 of file xml.hpp.
Referenced by output_attributes().
 { return attrs_ ? attrs_->begin() : emptyattrs_.end(); }
XmlAttrs::const_iterator XmlElement::aend () const inline
Get an iterator to the last+1 child attribute.
Returns
const_iterator to last+1 attribute
Definition at line 328 of file xml.hpp.
Referenced by output_attributes().
 { return attrs_ ? attrs_->end() : emptyattrs_.end(); }
XmlSet::const_iterator XmlElement::begin () const inline
Get an iterator to the first child element.
Returns
const_iterator to first element
Definition at line 332 of file xml.hpp.
 { return ordchildren_ ? ordchildren_->begin() : emptyset_.end(); }
XmlSet::const_iterator XmlElement::end () const inline
Get an iterator to the last+1 child element.
Returns
const_iterator to last+1 element
Definition at line 336 of file xml.hpp.
Referenced by FIX8::Configuration::find_element().
 { return ordchildren_ ? ordchildren_->end() : emptyset_.end(); }
static F8API XmlElement* XmlElement::Factory (std::istream & istr, const char * docpath = nullptr) static
Create a new root element (and recursively parse) from a given xml filename.
Parameters
istr an open std::istream of an xml document
docpath string providing info about the document or path
Returns
the new element
Referenced by main().
static F8API XmlElement* XmlElement::Factory (const std::string & fname) static
Create a new root element (and recursively parse) from a given xml istream.
Parameters
fname the xml filename
Returns
the new element
F8API const XmlElement* XmlElement::find (const std::string & what, const std::string * atag = nullptr, const std::string * aval = nullptr, const char delim = '/') const
Find an element with a given name, attribute name and attribute value.
Parameters
what the name to search for
atag the attribute name
aval the attribute value
delim the Xpath delimiter
Returns
the found or 0 if not found
Referenced by FIX8::Configuration::create_clients(), find_child(), FindAttrGetValue(), FIX8::Configuration::get_addresses(), load_fields(), load_fix_version(), FIX8::Configuration::load_map(), load_messages(), main(), precomp(), process(), and process_message_fields().
F8API int XmlElement::find (const std::string & what, XmlSet & eset, const std::string * atag = nullptr, const std::string * aval = nullptr, const char delim = '/') const
Recursively find all elements with a given name, attribute name and attribute value.
Parameters
what the name to search for
eset target XmlSet to place results
atag the attribute name
aval the attribute value
delim the Xpath delimiter
Returns
the number of found elements
F8API const XmlElement* XmlElement::find_child (const std::string & what, const std::string * atag = nullptr, const std::string * aval = nullptr, const char delim = '/') const inline
Find a child element with a given name, attribute name and attribute value. This version assumes the base of the search term already contains the current xpath tag and delimiter.
Parameters
what the name to search for
atag the attribute name
aval the attribute value
delim the Xpath delimiter
Returns
the found or 0 if not found
Definition at line 144 of file xml.hpp.
References find().
    {
       const std::string sterm(tag_ + '/' + what);
       return find(sterm, atag, aval, delim);
    }
F8API int XmlElement::find_child (const std::string & what, XmlSet & eset, const std::string * atag = nullptr, const std::string * aval = nullptr, const char delim = '/') const inline
Recursively find all child elements with a given name, attribute name and attribute value. This version assumes the base of the search term already contains the current xpath tag and delimiter.
Parameters
what the name to search for
eset target XmlSet to place results
atag the attribute name
aval the attribute value
delim the Xpath delimiter
Returns
the number of found elements
Definition at line 159 of file xml.hpp.
References find().
    {
       const std::string sterm(tag_ + '/' + what);
       return find(sterm, eset, atag, aval, delim);
    }
template<typename T > T XmlElement::FindAttr (const std::string & what, const T defValue) const inline
Find an attribute with the given name and return its typed value.
Template Parameters
type of target attribute
Parameters
what attribute to find
defValue value to return if attribute was not found
Returns
the value of the found attribute
Definition at line 209 of file xml.hpp.
Referenced by FIX8::Configuration::create_persister(), FIX8::Configuration::create_schedule(), FIX8::Configuration::create_session_schedule(), FIX8::Configuration::find_or_default(), FIX8::Configuration::get_logname(), and FIX8::recover_line().
    {
       if (attrs_)
       {
          XmlAttrs::iterator itr(attrs_->find(what));
          if (itr != attrs_->end())
             return FIX8::get_value<T>(itr->second);
       }
       return defValue;
    }
bool XmlElement::findAttrByValue (const std::string & what, const std::string & value) const
Find an attribute with the given name and value.
Parameters
what attribute to find
value attribute value
Returns
true if found
Definition at line 731 of file xml.cpp.
References attrs_.
 {
    if (attrs_)
    {
       XmlAttrs::iterator itr(attrs_->find(what));
       return itr != attrs_->end() && itr->second == val;
    }
    return false;
 }
bool XmlElement::FindAttrGetValue (const std::string & what, std::string & target) inline
Find an element and obtain the attribute's value with the name "value".
Parameters
what name to find
target where to place value
Returns
true if found
Definition at line 191 of file xml.hpp.
References find(), and GetAttrValue().
    {
        const XmlElement *inst(find(what));
        return inst ? inst->GetAttrValue(target) : false;
    }
template<typename T > T& XmlElement::FindAttrRef (const std::string & what, T & target) const inline
Find an attribute with the given name and populate supplied target with its typed value.
Template Parameters
type of target attribute
Parameters
what attribute to find
target location to return value
Returns
reference to value of the found attribute
Definition at line 227 of file xml.hpp.
Referenced by FIX8::Configuration::create_logger().
    {
       if (attrs_)
       {
          XmlAttrs::iterator itr(attrs_->find(what));
          if (itr != attrs_->end())
             target = FIX8::get_value<T>(itr->second);
       }
       return target;
    }
bool XmlElement::GetAttr (const std::string & what, std::string & target) const
Find an attribute's with the given name.
Parameters
what attribute to find
target where to place value
Returns
true if found
Definition at line 743 of file xml.cpp.
References attrs_.
Referenced by FIX8::Configuration::create_logger(), FIX8::Configuration::create_persister(), FIX8::Configuration::create_schedule(), FIX8::Configuration::create_session_schedule(), FIX8::Configuration::from_or_default(), FIX8::Configuration::get_logflags(), FIX8::Configuration::get_time_field(), and GetAttrValue().
 {
    if (attrs_)
    {
       XmlAttrs::iterator itr(attrs_->find(what));
       if (itr != attrs_->end())
       {
          target = itr->second;
          return true;
       }
    }
    return false;
 }
bool XmlElement::GetAttrValue (std::string & target) const inline
Find an attribute's value with the name "value".
Parameters
target where to place value
Returns
true if found
Definition at line 175 of file xml.hpp.
References GetAttr().
Referenced by FindAttrGetValue().
    {
       static const std::string valstr("value");
       return GetAttr(valstr, target);
    }
int XmlElement::GetChildCnt () const inline
Get the count of children this element has.
Returns
the number of children
Definition at line 264 of file xml.hpp.
References chldcnt_.
 { return chldcnt_; }
const std::string* XmlElement::GetDecl () const inline
Get the declaration if available.
Returns
the declaration
Definition at line 309 of file xml.hpp.
References decl_.
 { return decl_; }
int XmlElement::GetDepth () const inline
Get the depth of this element
Returns
the depth
Definition at line 252 of file xml.hpp.
References depth_.
 { return depth_; }
int XmlElement::GetErrorCnt () const inline
Get the global error count.
Returns
the error count
Definition at line 256 of file xml.hpp.
References errors_.
 { return errors_; }
int XmlElement::GetLine () const inline
Get the source line of this element (element order).
Returns
the line
Definition at line 268 of file xml.hpp.
References txtline_.
Referenced by output_attributes(), and FIX8::recover_line().
 { return txtline_; }
int XmlElement::GetLineCnt () const inline
Get the actual current source line.
Returns
the source line
Definition at line 260 of file xml.hpp.
References line_.
 { return line_; }
std::string XmlElement::GetLocString () const inline
Generate a formatted string for error reporting
Returns
formatted string
Definition at line 296 of file xml.hpp.
References GetPath().
    {
       std::ostringstream ostr;
       ostr << '"' << tag_ << "\" (" << GetPath() << ':' << txtline_ << ')';
       return ostr.str();
    }
int XmlElement::GetMaxDepth () const inline
Get the maximum depth from this node
Returns
the maximum depth
Definition at line 284 of file xml.hpp.
References maxdepth_.
 { return maxdepth_; }
int XmlElement::GetMaxDepthPermitted () const inline
Get the maximum depth supported.
Returns
the maximum depth
Definition at line 280 of file xml.hpp.
References MaxDepth.
 { return MaxDepth; }
const XmlElement* XmlElement::GetParent () const inline
Get the parent element of this tree, const version
Returns
the parent element, 0 if no parent
Definition at line 344 of file xml.hpp.
References parent_.
 { return parent_; }
std::string XmlElement::GetPath () const inline
Get the full xpath for the element; recursive
Returns
the path
Definition at line 288 of file xml.hpp.
References GetPath(), and tag_.
Referenced by GetLocString(), and GetPath().
 { return parent_ ? parent_->GetPath() + '/' + tag_ : "//" + tag_; }
const XmlElement* XmlElement::GetRoot () const inline
Get the root element of this tree, const version
Returns
the root element
Definition at line 340 of file xml.hpp.
References root_.
 { return parent_ ? parent_->root_ : this; }
int XmlElement::GetSequence () const inline
Get the sequence number for this element (incremented for each new element).
Returns
the sequence number
Definition at line 276 of file xml.hpp.
References sequence_.
Referenced by XmlElement::EntityOrderComp::operator()().
 { return sequence_; }
int XmlElement::GetSubIdx () const inline
Get the subindex.
Returns
the subindex
Definition at line 272 of file xml.hpp.
References subidx_.
 { return subidx_; }
const std::string& XmlElement::GetTag () const inline
Get the element tag name.
Returns
the tag
Definition at line 292 of file xml.hpp.
References tag_.
Referenced by Insert(), and precomp().
 { return tag_; }
const std::string* XmlElement::GetVal () const inline
Get the element value.
Returns
the value
Definition at line 305 of file xml.hpp.
References value_.
 { return value_; }
bool XmlElement::HasAttr (const std::string & what) const inline
Check if an attribute with the given name is present.
Parameters
what attribute to find
Returns
true if found
Definition at line 184 of file xml.hpp.
Referenced by FIX8::Configuration::create_logger(), and FIX8::Configuration::find_or_default().
       { return attrs_ ? attrs_->find(what) != attrs_->end() : false; }
const string & XmlElement::InplaceXlate (std::string & what)
Perform xml translation on the supplied string inplace. Translate predefined entities and numeric character references.
Parameters
what source string to translate
Returns
the translated string
Definition at line 759 of file xml.cpp.
References flags_, noextensions, rCE_, rCX_, rEn_, FIX8::RegExp::Replace(), rEv_, FIX8::RegExp::SearchString(), stringtochar_, and FIX8::RegExp::SubExpr().
 {
    RegMatch match;
    while (rCX_.SearchString(match, what, 2) == 2)
    {
       string whatv;
       rCX_.SubExpr(match, what, whatv, 0, 1);
       const auto sitr(stringtochar_.find(whatv));
       rCX_.Replace(match, what, sitr == stringtochar_.cend() ? '?' : sitr->second); // not found character entity replaces string with '?'
    }
    while (rCE_.SearchString(match, what, 2) == 2)  // translate Numeric character references &#x12d; or &#12;
    {
       string whatv;
       rCE_.SubExpr(match, what, whatv, 0, 1);
       istringstream istr(whatv);
       int value;
       if (whatv[0] == 'x')
       {
          istr.ignore();
          istr >> hex >> value;
       }
       else
          istr >> dec >> value;
       string oval;
       if (value & 0xff00)  // handle hi byte
          oval += static_cast<char>(value >> 8 & 0xff);
       oval += static_cast<char>(value & 0xff);
       rCE_.Replace(match, what, oval);
    }
    if (!(flags_ & noextensions))
    {
       if (rEn_.SearchString(match, what, 2) == 2)  // environment var replacement ${XXX}
       {
          string whatv;
          rEn_.SubExpr(match, what, whatv, 0, 1);
          const char *gresult(getenv(whatv.c_str()));
          if (gresult)
          {
             const string result(gresult);
             if (!result.empty())
                rEn_.Replace(match, what, result);
          }
       }
       if (rEv_.SearchString(match, what, 2) == 2)  // evaluate shell command and replace with result !{XXX}
       {
          string whatv;
          rEv_.SubExpr(match, what, whatv, 0, 1);
          string result;
          if (exec_cmd(whatv, result))
             rEv_.Replace(match, what, result);
       }
    }
    return what;
 }
bool XmlElement::Insert (XmlElement * what)
Insert an element as a child of this element
Parameters
what elekent to insert
Returns
true if successful
Definition at line 518 of file xml.cpp.
References children_, chldcnt_, GetTag(), and ordchildren_.
Referenced by main().
 {
    if (!what)
       return false;
    if (!children_)
    {
       children_ = new XmlSubEls;
       ordchildren_ = new XmlSet;
    }
    ++chldcnt_;
    children_->insert({what->GetTag(), what});
    ordchildren_->insert(what);
    return true;
 }
XmlElement& XmlElement::operator= (const XmlElement &) delete
Assignment operator. Non-copyable.
int XmlElement::ParseAttrs (const std::string & attlst)
Parse the xml attributes from an element.
Parameters
attlst string of attributes
Returns
number of attributes extracted
Definition at line 537 of file xml.cpp.
References attrs_, errors_, flags_, incline_, inclusion_, line_, noextensions, and root_.
 {
    istringstream istr(attlst);
    enum { ews, tag, es, oq, value, oc0, comment, cc0 } state(ews);
    string tmptag, tmpval;
    char comchar(0);
    while (istr.good())
    {
       char c;
       istr >> noskipws >> c;
       switch (state)
       {
       case comment:
          if (c == '*')
             state = cc0;
          break;
       case cc0:
          if (c == '/')
             state = ews;
          else
             state = comment;
          break;
       case ews:
          if (c == '/')
             state = oc0;
          else if (!isspace(c))
          {
             tmptag += c;
             state = tag;
          }
          break;
       case oc0:
          if (c == '*' && !(flags_ & noextensions))
          {
             state = comment;
             break;
          }
          else
          {
             tmptag += '/';
             tmptag += c;
             state = tag;
          }
       case tag:
          if (isspace(c))
             state = es;
          else if (c == '=')
             state = oq;
          else if (c == '"' || c == '\'')
          {
 illegal_char:
             ostringstream ostr;
             ostr << "Error (" << root_->line_ << ") attribute \'" << tmptag << "\' illegal character defined";
             if (!root_->inclusion_.empty())
                ostr << " in inclusion " << root_->inclusion_ << " (" << root_->incline_ << ')';
             throw XMLError(ostr.str());
          }
          else
             tmptag += c;
          break;
       case es:
          if (c == '=')
             state = oq;
          else if (c == '"' || c == '\'')
             goto illegal_char;
          break;
       case oq:
          if (c == '"' || c == '\'')
          {
             comchar = c;
             state = value;
          }
          else if (!isspace(c))
             goto illegal_char;
          break;
       case value:
          if (c != comchar)
             tmpval += c;
          else
          {
             if (tmptag.find_first_of("\\\'\"=") != string::npos)
                goto illegal_char;
             if (tmptag != "docpath")
             {
                if (!attrs_)
                   attrs_ = new XmlAttrs;
                if (!attrs_->insert({tmptag, InplaceXlate(tmpval)}).second)
                {
                   ++root_->errors_;
                   ostringstream ostr;
                   ostr << "Error (" << root_->line_ << ") attribute \'" << tmptag << "\' already defined";
                   if (!root_->inclusion_.empty())
                      ostr << " in inclusion " << root_->inclusion_ << " (" << root_->incline_ << ')';
                   throw XMLError(ostr.str());
                }
             }
             tmptag.clear();
             tmpval.clear();
             state = ews;
             comchar = 0;
          }
          break;
       default:
          break;
       }
    }
    return attrs_ ? static_cast<int>(attrs_->size()) : 0;
 }
static void XmlElement::set_flags (XmlFlags flags) inline static
Definition at line 82 of file xml.hpp.
 { flags_ = flags; }
Friends And Related Function Documentation
F8API std::ostream& operator<< (std::ostream & os, const XmlElement & en) friend
Inserter friend.
Parameters
os stream to send to
en XmlElement REFErence
Returns
stream
Member Data Documentation
bool XmlElement::_was_include private
Definition at line 88 of file xml.hpp.
Referenced by ~XmlElement().
XmlAttrs* XmlElement::attrs_
Definition at line 76 of file xml.hpp.
Referenced by findAttrByValue(), GetAttr(), operator<<(), ParseAttrs(), and ~XmlElement().
XmlSubEls* XmlElement::children_ private
simple n-ary tree
Definition at line 87 of file xml.hpp.
Referenced by Insert(), operator<<(), and ~XmlElement().
int XmlElement::chldcnt_ private
Definition at line 63 of file xml.hpp.
Referenced by GetChildCnt(), and Insert().
std::string * XmlElement::decl_ private
Definition at line 62 of file xml.hpp.
Referenced by GetDecl(), operator<<(), and ~XmlElement().
int XmlElement::depth_ private
Definition at line 63 of file xml.hpp.
Referenced by GetDepth(), and operator<<().
const XmlElement::XmlAttrs XmlElement::emptyattrs_ static
Definition at line 77 of file xml.hpp.
const XmlElement::XmlSet XmlElement::emptyset_ static private
Definition at line 92 of file xml.hpp.
int XmlElement::errors_ private
Definition at line 59 of file xml.hpp.
Referenced by GetErrorCnt(), and ParseAttrs().
XmlElement::XmlFlags XmlElement::flags_ static
Definition at line 81 of file xml.hpp.
Referenced by InplaceXlate(), and ParseAttrs().
int XmlElement::incline_ private
Definition at line 59 of file xml.hpp.
Referenced by ParseAttrs().
std::string XmlElement::inclusion_ private
Definition at line 60 of file xml.hpp.
Referenced by ParseAttrs().
int XmlElement::line_ private
Definition at line 59 of file xml.hpp.
Referenced by GetLineCnt(), and ParseAttrs().
int XmlElement::maxdepth_ private
Definition at line 59 of file xml.hpp.
Referenced by GetMaxDepth().
XmlSet* XmlElement::ordchildren_ private
Set of all child elements in file order.
Definition at line 91 of file xml.hpp.
Referenced by Insert(), operator<<(), and ~XmlElement().
XmlElement* XmlElement::parent_ private
Definition at line 57 of file xml.hpp.
Referenced by GetParent().
RegExp XmlElement::rCE_ static private
Definition at line 55 of file xml.hpp.
Referenced by InplaceXlate().
RegExp XmlElement::rCX_ static private
Definition at line 55 of file xml.hpp.
Referenced by InplaceXlate().
RegExp XmlElement::rEn_ static private
Definition at line 55 of file xml.hpp.
Referenced by InplaceXlate().
RegExp XmlElement::rEv_ static private
Definition at line 55 of file xml.hpp.
Referenced by InplaceXlate().
RegExp XmlElement::rIn_ static private
Definition at line 55 of file xml.hpp.
XmlElement * XmlElement::root_ private
Definition at line 57 of file xml.hpp.
Referenced by GetRoot(), and ParseAttrs().
int XmlElement::seq_ private
Definition at line 59 of file xml.hpp.
int XmlElement::sequence_ private
Definition at line 63 of file xml.hpp.
Referenced by GetSequence().
const Str2Chr XmlElement::stringtochar_ static private
Initial value:
{
   {"amp", '&'},     {"lt", '<'},      {"gt", '>'},
   {"apos", '\''},   {"quot", '"'},    {"nbsp", 160},
   {"iexcl", 161},   {"cent", 162},    {"pound", 163},
   {"curren", 164},  {"yen", 165},     {"brvbar", 166},
   {"sect", 167},    {"uml", 168},     {"copy", 169},
   {"ordf", 170},    {"laquo", 171},   {"not", 172},
   {"shy", 173},     {"reg", 174},     {"macr", 175},
   {"deg", 176},     {"plusmn", 177},  {"sup2", 178},
   {"sup3", 179},    {"acute", 180},   {"micro", 181},
   {"para", 182},    {"middot", 183},  {"cedil", 184},
   {"sup1", 185},    {"ordm", 186},    {"raquo", 187},
   {"frac14", 188},  {"frac12", 189},  {"frac34", 190},
   {"iquest", 191}
}
XML entity char lookup.
Definition at line 51 of file xml.hpp.
Referenced by InplaceXlate().
int XmlElement::subidx_ private
Definition at line 63 of file xml.hpp.
Referenced by GetSubIdx().
std::string XmlElement::tag_ private
Definition at line 62 of file xml.hpp.
Referenced by GetPath(), GetTag(), and operator<<().
int XmlElement::txtline_ private
Definition at line 63 of file xml.hpp.
Referenced by GetLine(), and operator<<().
std::string * XmlElement::value_ private
Definition at line 62 of file xml.hpp.
Referenced by GetVal(), operator<<(), and ~XmlElement().
The documentation for this class was generated from the following files:
xml.hpp
xml.cpp