fix8: f8cutils.cpp File Reference
f8cutils.cpp File Reference
#include "precomp.hpp"
#include <fix8/f8includes.hpp>
#include <fix8/usage.hpp>
#include <f8c.hpp>
Functions
void print_usage ()
int process (XmlElement &xf, Ctxt &ctxt)
int load_fix_version (XmlElement &xf, Ctxt &ctxt)
int load_fields (XmlElement &xf, FieldSpecMap &fspec)
void process_special_traits (const unsigned short field, FieldTraits &fts)
int process_message_fields (const std::string &where, XmlElement *xt, FieldTraits &fts, const FieldToNumMap &ftonSpec, FieldSpecMap &fspec, const Components &compon)
int load_messages (XmlElement &xf, MessageSpecMap &mspec, const FieldToNumMap &ftonSpec, FieldSpecMap &fspec)
void process_ordering (MessageSpecMap &mspec)
void process_value_enums (FieldSpecMap::const_iterator itr, ostream &ost_hpp, ostream &ost_cpp)
const string & mkel (const string &base, const string &compon, string &where)
void process_group_ordering (const CommonGroupMap &gm)
unsigned lookup_component (const Components &compon, const f8String &name)
string bintoaschex (const string &from)
ostream * open_ofile (const string &odir, const string &fname, string &target)
const string & filepart (const string &source, string &where)
int process_message_fields (const std::string &where, const XmlElement *xt, FieldTraits &fts, const FieldToNumMap &ftonSpec, FieldSpecMap &fspec, const Components &compon)
void process_message_group_ordering (const GroupMap &gm)
string insert_year ()
void generate_includes (ostream &to)
Variables
string shortName
string odir
string prefix
bool verbose
bool nocheck
bool nowarn
bool incpath
string spacer
string precompHdr
const string GETARGLIST
unsigned glob_errors
unsigned glob_warnings
Function Documentation
string bintoaschex (const string & from)
Definition at line 270 of file f8cutils.cpp.
Referenced by process().
 {
    ostringstream result;
    for (const auto& cc : from)
       result << uppercase << hex << setw(2) << setfill('0') << static_cast<unsigned short>(cc);
    return "FIX8_" + result.str() + '_';
 }
const string& filepart (const string & source, string & where)
Definition at line 108 of file f8cutils.cpp.
Referenced by main(), and FIX8::FileLogger::rotate().
 {
    string::size_type pos(source.find_last_of('/'));
    return pos == string::npos ? where = source : where = source.substr(pos + 1);
 }
void generate_includes (ostream & to)
Definition at line 393 of file f8cutils.cpp.
References incpath.
Referenced by process().
 {
    static const vector<string> incfiles
    {
       //"f8includes.hpp"
       "f8exception.hpp",
       "hypersleep.hpp",
       "mpmc.hpp",
       "thread.hpp",
       "f8types.hpp",
       "f8utils.hpp",
       "tickval.hpp",
       "logger.hpp",
       "traits.hpp",
       "field.hpp",
       "message.hpp"
    };
    to << "// f8 includes" << endl;
    for (const auto& pp : incfiles)
       to << "#include " << (incpath ? "<fix8/" : "<") << pp << '>' << endl;
 }
string insert_year ()
Definition at line 375 of file f8cutils.cpp.
Referenced by generate_preamble().
 {
    struct tm *ptim;
    time_t now(time(0));
 #ifdef _MSC_VER
    ptim = localtime (&now);
 #else
    struct tm tim;
    localtime_r(&now, &tim);
    ptim = &tim;
 #endif
    ostringstream ostr;
    ostr << setw(2) << (ptim->tm_year - 100);
    return ostr.str();
 }
int load_fields (XmlElement & xf, FieldSpecMap & fspec)
Definition at line 445 of file f8c.cpp.
References XmlElement::find(), glob_errors, glob_warnings(), FIX8::InPlaceStrToUpper(), nowarn(), FIX8::recover_line(), shortName, and FIX8::trim().
Referenced by process().
 {
    XmlElement::XmlSet flist;
    if (!xf.find("fix/fields/field", flist))
    {
       cerr << "error: No fields found in " << shortName << endl;
       return 0;
    }
    int fieldsLoaded(0);
    for(const auto *pp : flist)
    {
       string number, name, type;
       if (pp->GetAttr("number", number) && pp->GetAttr("name", name) && pp->GetAttr("type", type))
       {
          trim(number);
          trim(name);
          trim(type);
          InPlaceStrToUpper(type);
          const auto bmitr(FieldSpec::_baseTypeMap.find(type));
          FieldTrait::FieldType ft(bmitr == FieldSpec::_baseTypeMap.end() ? FieldTrait::ft_untyped : bmitr->second);
          pair<FieldSpecMap::iterator, bool> result;
          if (ft != FieldTrait::ft_untyped)
             result = fspec.insert({stoul(number), FieldSpec(name, ft)});
          else
          {
             if (!nowarn)
                cerr << shortName << ':' << recover_line(*pp) << ": warning: Unknown field type: " << type << " in " << name << endl;
             ++glob_warnings;
             continue;
          }
          pp->GetAttr("description", result.first->second._description);
          pp->GetAttr("comment", result.first->second._comment);
          ++fieldsLoaded;
          XmlElement::XmlSet realmlist;
          if (pp->find("field/value", realmlist))
          {
             for(const auto *pp : realmlist)
             {
                string enum_str, description;
                if (pp->GetAttr("enum", enum_str))
                {
                   if (!pp->GetAttr("description", description) || description.empty())
                      description = enum_str;    // use enum if no description supplied
                   if (!result.first->second._dvals)
                      result.first->second._dvals = new RealmMap;
                   string rangeend;
                   bool isRange(pp->GetAttr("range", rangeend) && (rangeend == "lower" || rangeend == "upper"));
                   RealmObject *realmval(RealmObject::create(enum_str, ft, isRange));
                   if (isRange)
                      result.first->second._dtype = RealmBase::dt_range;
                   if (realmval)
                      result.first->second._dvals->insert({realmval, description});
                }
                else
                {
                   cerr << shortName << ':' << recover_line(*pp) << ": error: field value element missing required attribute (enum)." << endl;
                   ++glob_errors;
                }
             }
          }
       }
       else
       {
          cerr << shortName << ':' << recover_line(*pp) << ": error: field definition element missing required attributes (number, name or type)" << endl;
          ++glob_errors;
       }
    }
    return fieldsLoaded;
 }
int load_fix_version (XmlElement & xf, Ctxt & ctxt)
Definition at line 115 of file f8cutils.cpp.
References FIX8::Ctxt::_beginstr, FIX8::Ctxt::_clname, FIX8::Ctxt::_fixns, FIX8::Ctxt::_systemns, FIX8::Ctxt::_version, XmlElement::find(), prefix, and shortName.
Referenced by main().
 {
    const XmlElement *fix(xf.find("fix"));
    if (!fix)
    {
       cerr << "No fix header element found in " << shortName << endl;
       return -1;
    }
    string major, minor, revision("0"), type("FIX");
    if (!fix->GetAttr("major", major) || !fix->GetAttr("minor", minor))
    {
       cerr << "Missing required attributes (major/minor) from fix header in " << shortName << endl;
       return -1;
    }
    if (!fix->GetAttr("revision", revision))
       fix->GetAttr("servicepack", revision);
    fix->GetAttr("type", type);
    // fix version: <Major:1><Minor:1><Revision:2> eg. 4.2r10 is 4210
    ctxt._version = stoi(major) * 1000 + stoi(minor) * 100 + stoi(revision);
    if (type == "FIX" && ctxt._version < 4000)
    {
       cerr << "Unsupported FIX version " << ctxt._version << " from fix header in " << shortName << endl;
       return -1;
    }
    ostringstream ostr;
    ostr << type << ctxt._version;
    ctxt._systemns = ostr.str();
    if (ctxt._fixns.empty())
       ctxt._fixns = ctxt._systemns;
    ctxt._clname = prefix;
    ostr.str("");
    ostr << type << '.' << major << '.' << minor;
    ctxt._beginstr = ostr.str();
    return 0;
 }
int load_messages (XmlElement & xf, MessageSpecMap & mspec, const FieldToNumMap & ftonSpec, FieldSpecMap & fspec)
unsigned lookup_component (const Components & compon, const f8String & name)
Definition at line 1498 of file f8c.cpp.
Referenced by parse_groups(), and process_message_fields().
 {
    Components::const_iterator citr(compon.find(name));
    return citr != compon.end() ? 1 + distance(compon.begin(), citr) : 0;
 }
const string& mkel (const string & base, const string & compon, string & where)
Definition at line 100 of file f8cutils.cpp.
Referenced by load_messages().
 {
    ostringstream ostr;
    ostr << base << '/' << compon;
    return where = ostr.str();
 }
ostream* open_ofile (const string & odir, const string & fname, string & target)
Definition at line 77 of file f8cutils.cpp.
References FIX8::CheckAddTrailingSlash(), and FIX8::exist().
Referenced by main().
 {
    if (!exist(odir))
       return nullptr;
    ostringstream ofs;
    string odirect(odir);
    ofs << CheckAddTrailingSlash(odirect) << fname;
    target = ofs.str();
    unique_ptr<ofstream> os(new ofstream(target.c_str()));
    if (!*os)
    {
       cerr << "Error opening file \'" << target << '\'';
       if (errno)
          cerr << " (" << strerror(errno) << ')';
       cerr << endl;
       return nullptr;
    }
    return os.release();
 }
void print_usage ()
Definition at line 320 of file f8cutils.cpp.
References UsageMan::add(), GETARGLIST, UsageMan::print(), and UsageMan::setdesc().
 {
    UsageMan um("f8c", GETARGLIST, "<input xml schema>");
    um.setdesc("f8c -- compile FIX xml schema");
    um.add('o', "odir <dir>", "output target directory (default ./)");
    um.add('p', "prefix <prefix>", "output filename prefix (default Myfix)");
    um.add('H', "pch <filename>", "use specified precompiled header name for Windows (default none)");
    um.add('d', "dump", "dump 1st pass parsed source xml file, exit");
    um.add('e', "extension", "Generate with .cxx/.hxx extensions (default .cpp/.hpp)");
    um.add('f', "fields", "generate code for all defined fields even if they are not used in any message (default no)");
    um.add('F', "xfields", "specify additional fields with associated messages (see documentation for details)");
    um.add('h', "help", "help, this screen");
    um.add('i', "ignore", "ignore errors, attempt to generate code anyhow (default no)");
    um.add('k', "keep", "retain generated temporaries even if there are errors (.*.tmp)");
    um.add('v', "version", "print version, exit");
    um.add('I', "info", "print package info, exit");
    um.add('s', "second", "2nd pass only, no precompile (default both)");
    um.add('S', "noshared", "Treat every group as unique and expose all static traits. Do not share metadata in message classes (default shared)");
    um.add('N', "nounique", "do not enforce unique field parsing (default false)");
    um.add('R', "norealm", "do not generate realm constructed field instantiators (default false)");
    um.add('W', "nowarn", "suppress warning messages (default false)");
    um.add('C', "nocheck", "do not embed version checking in generated code (default false)");
    um.add('D', "defaulted", "do not generate default router bodies. Application must provide all router definitions (default false)");
    um.add('U', "noconst", "Generate non-const Router method declarations (default false, const)");
    um.add('r', "retain", "retain 1st pass code (default delete)");
    um.add('b', "binary", "print binary/ABI details, exit");
    um.add('P', "incpath", "prefix system include path with \"fix8\" in generated compilation units (default yes)");
    um.add('c', "classes <server|client>", "generate user session classes (default neither)");
    um.add('t', "tabwidth", "tabwidth for generated code (default 3 spaces)");
    um.add('x', "fixt <file>", "For FIXT hosted transports or for FIX5.0 and above, the input FIXT schema file");
    um.add('V', "verbose", "be more verbose when processing");
    um.add('n', "namespace <ns>", "namespace to place generated code in (default FIXMmvv e.g. FIX4400)");
    um.add("e.g.");
    um.add("@f8c -p Texfix -n TEX myfix.xml");
    um.add("@f8c -rp Texfix -n TEX -x ../schema/FIXT11.xml myfix.xml");
    um.add("@f8c -p Texfix -n TEX -c client -x ../schema/FIXT11.xml myfix.xml");
    um.add("@f8c -p Texfix -n TEX -c client -x ../schema/FIXT11.xml myfix.xml -F \"<field number='9999' name='SampleUserField' type='STRING' messages='NewOrderSingle:Y ExecutionReport:Y OrderCancelRequest:N' />");
    um.print(cerr);
 }
int process (XmlElement & xf, Ctxt & ctxt)
Definition at line 910 of file f8c.cpp.
References FIX8::Ctxt::_beginstr, FIX8::Ctxt::_clname, FIX8::_csMap, FIX8::Ctxt::_fixns, FIX8::Ctxt::_out, FIX8::Ctxt::_version, bintoaschex(), FIX8::cs_divider, FIX8::cs_end_anon_namespace, FIX8::cs_end_namespace, FIX8::cs_generated_includes, FIX8::cs_header_preamble, FIX8::cs_start_anon_namespace, FIX8::cs_start_namespace, FIX8::cs_trailer_preamble, XmlElement::find(), gen_classes, gen_fields(), generate_common_group_bodies(), generate_export(), generate_group_bodies(), generate_includes(), generate_nested_group(), generate_preamble(), glob_errors, load_components(), load_fields(), load_messages(), nconst_router(), no_default_routers(), no_shared_groups(), norealm(), process_group_ordering(), process_ordering(), process_value_enums(), shortName, spacer, and verbose().
Referenced by main().
 {
    ostream& ost_cpp(*ctxt._out[Ctxt::types_cpp].second);
    ostream& ost_hpp(*ctxt._out[Ctxt::types_hpp].second);
    ostream& osr_cpp(*ctxt._out[Ctxt::traits_cpp].second);
    ostream& osc_hpp(*ctxt._out[Ctxt::classes_hpp].second);
    ostream& osc_cpp(*ctxt._out[Ctxt::classes_cpp].second);
    ostream& osu_hpp(*ctxt._out[Ctxt::router_hpp].second);
    ostream& oss_hpp(*ctxt._out[Ctxt::session_hpp].second);
    int result(0);
 // ================================= Field loading  =======================================
    FieldSpecMap fspec;
    int fields(load_fields(xf, fspec));
    if (!fields || glob_errors)
       return 0;
    if (verbose)
       cout << fields << " fields defined" << endl;
 // ================================= Message processing ===================================
    FieldToNumMap ftonSpec;
    for (const auto& pp : fspec)
       ftonSpec.insert({pp.second._name, pp.first});
    XmlElement::XmlSet comlist;
    Components components;
    xf.find("fix/components/component", comlist);
    load_components(comlist, components);
    MessageSpecMap mspec;
    CommonGroupMap globmap;
    int msgsloaded(load_messages(xf, mspec, ftonSpec, fspec, components, globmap));
    if (!msgsloaded)
       return result;
    if (verbose)
    {
       cout << msgsloaded << " messages defined" << endl;
       if (components.size())
          cout << components.size() << " components defined" << endl;
       if (globmap.size())
       {
          unsigned cgs(0), ugs(0), vars(0);
          for (const auto& pp : globmap)
          {
             vars += static_cast<unsigned>(pp.second.size());
             for (const auto& ii : pp.second)
             {
                if (ii.second._group_refcnt > 1)
                   ugs += ii.second._group_refcnt;
                else
                   ++cgs;
             }
          }
          cout << globmap.size() << " repeating group catagories (" << vars << " variants, "
             << ugs << " common, " << cgs << " unique) processed" << endl;
       }
    }
    process_ordering(mspec);
    process_group_ordering(globmap);
    // output file preambles
    generate_preamble(osu_hpp, ctxt._out[Ctxt::router_hpp].first.second, true);
    osu_hpp << "#ifndef " << bintoaschex(ctxt._out[Ctxt::router_hpp].first.second) << endl;
    osu_hpp << "#define " << bintoaschex(ctxt._out[Ctxt::router_hpp].first.second) << endl << endl;
    osu_hpp << _csMap.find(cs_start_namespace)->second << endl;
    osu_hpp << "namespace " << ctxt._fixns << " {" << endl;
    osu_hpp << endl << _csMap.find(cs_divider)->second << endl;
    generate_preamble(osc_hpp, ctxt._out[Ctxt::classes_hpp].first.second, true);
    osc_hpp << "#ifndef " << bintoaschex(ctxt._out[Ctxt::classes_hpp].first.second) << endl;
    osc_hpp << "#define " << bintoaschex(ctxt._out[Ctxt::classes_hpp].first.second) << endl << endl;
     generate_export(osc_hpp, ctxt._fixns);
     osc_hpp << _csMap.find(cs_start_namespace)->second << endl;
    osc_hpp << endl << "extern \"C\"" << endl << '{' << endl
       << spacer << "F8_" << ctxt._fixns << "_API const F8MetaCntx& " << ctxt._fixns << "_ctx();" << endl << '}' << endl << endl;
    osc_hpp << "namespace " << ctxt._fixns << " {" << endl;
    osc_hpp << endl << _csMap.find(cs_divider)->second << endl;
    osc_hpp << "using " << ctxt._clname << "_BaseMsgEntry = MsgTable;" << endl;
    osc_hpp << "/// Compiler generated metadata object, accessed through this function." << endl;
    osc_hpp << "F8_" << ctxt._fixns << "_API " << "const F8MetaCntx& ctx();" << endl;
    osc_hpp << "class " << ctxt._clname << "_Router;" << endl;
    osc_hpp << endl << _csMap.find(cs_divider)->second << endl;
    generate_preamble(osc_cpp, ctxt._out[Ctxt::classes_cpp].first.second, false);
    osc_cpp << _csMap.find(cs_generated_includes)->second << endl;
    generate_includes(osc_cpp);
    osc_cpp << "#include \"" << ctxt._out[Ctxt::types_hpp].first.second << '"' << endl;
    osc_cpp << "#include \"" << ctxt._out[Ctxt::router_hpp].first.second << '"' << endl;
    osc_cpp << "#include \"" << ctxt._out[Ctxt::classes_hpp].first.second << '"' << endl;
    osc_cpp << _csMap.find(cs_divider)->second << endl;
    osc_cpp << _csMap.find(cs_start_namespace)->second << endl;
    osc_cpp << "namespace " << ctxt._fixns << " {" << endl << endl;
    osc_cpp << _csMap.find(cs_start_anon_namespace)->second << endl << endl;
    osc_cpp << _csMap.find(cs_divider)->second << endl;
    generate_preamble(osr_cpp, ctxt._out[Ctxt::traits_cpp].first.second, false);
    osr_cpp << _csMap.find(cs_generated_includes)->second << endl;
    generate_includes(osr_cpp);
    osr_cpp << "#include \"" << ctxt._out[Ctxt::types_hpp].first.second << '"' << endl;
    osr_cpp << "#include \"" << ctxt._out[Ctxt::router_hpp].first.second << '"' << endl;
    osr_cpp << "#include \"" << ctxt._out[Ctxt::classes_hpp].first.second << '"' << endl;
    osr_cpp << _csMap.find(cs_divider)->second << endl;
    osr_cpp << _csMap.find(cs_start_namespace)->second << endl;
    osr_cpp << "namespace " << ctxt._fixns << " {" << endl << endl;
    osr_cpp << _csMap.find(cs_divider)->second << endl;
 // =============================== Message class definitions ==============================
    if (!no_shared_groups)
    {
       osr_cpp << "// Common group traits" << endl;
       osr_cpp << "namespace {" << endl;
       generate_common_group_bodies(fspec, osr_cpp, globmap);
       osr_cpp << "} // namespace" << endl << endl;
    }
 #if defined FIX8_HAVE_EXTENDED_METADATA
    else
    {
       osr_cpp << "//" << endl;
       osr_cpp << "// Shared groups disabled (--noshared). Static traits are now exposed." << endl;
       osr_cpp << "//" << endl;
    }
 #endif
    osr_cpp << _csMap.find(cs_divider)->second << endl;
    osr_cpp << "// Message traits" << endl;
    FieldSpecMap::const_iterator fsitr(fspec.find(35));   // always 35
    for (const auto& pp : mspec)
    {
       bool isTrailer(pp.second._name == "trailer");
       bool isHeader(pp.second._name == "header");
       osc_hpp << "/// " << pp.second._name << " (" << pp.first << "), "
          << (pp.second._is_admin ? "admin" : "application")
          << ", " <<  pp.second._fields.get_presence().size() << " fiel"
          << (pp.second._fields.get_presence().size() == 1 ? "d, " : "ds, ")
          << pp.second._groups.size() << " grou" << (pp.second._groups.size() == 1 ? "p." : "ps.");
       if (!pp.second._comment.empty())
          osc_hpp << ' ' << pp.second._comment;
       osc_hpp << endl;
       osc_hpp << "class " << pp.second._name << " : public "
          << (isTrailer || isHeader ? "MessageBase" : "Message") << endl << '{' << endl;
       if (pp.second._fields.get_presence().size())
       {
          osr_cpp << _csMap.find(cs_divider)->second << endl;
          osr_cpp << "const FieldTrait " << pp.second._name << "::_traits[]"
             << endl << '{' << endl;
          int felpos(0);
          for (Presence::const_iterator flitr(pp.second._fields.get_presence().begin());
             flitr != pp.second._fields.get_presence().end(); ++flitr, ++felpos)
          {
             bool spaceme(true);
             if (flitr != pp.second._fields.get_presence().begin())
             {
                osr_cpp << ',';
                if (felpos % 4 == 0)
                   osr_cpp << endl;
                else
                   spaceme = false;
             }
             ostringstream tostr;
             tostr << "0x" << setfill('0') << setw(2) << hex << flitr->_field_traits.get();
             osr_cpp << (spaceme ? spacer : " ");
             osr_cpp << '{' << setw(4) << right << flitr->_fnum << ','
                << setw(2) << right << flitr->_ftype << ',' << setw(3) << right
                << flitr->_pos << ',' << setw(3) << right << flitr->_component << ',' << tostr.str();
 #if defined FIX8_HAVE_EXTENDED_METADATA
             if (no_shared_groups && flitr->_field_traits.has(FieldTrait::group))
             {
                osr_cpp << ", " << endl << spacer << spacer;
                FieldSpecMap::const_iterator gsitr(fspec.find(flitr->_fnum));
                osr_cpp << gsitr->second._name << "::get_traits(), " << gsitr->second._name << "::get_fieldcnt()";
                osr_cpp << endl << spacer << '}';
                felpos = -1;
             }
             else
 #endif
                osr_cpp << '}';
          }
          osr_cpp << endl << "};" << endl;
          osr_cpp << "const FieldTrait_Hash_Array " << pp.second._name << "::_ftha(" << pp.second._name << "::_traits, "
             << pp.second._name << "::_fieldcnt);" << endl;
          osr_cpp << "const MsgType " << pp.second._name << "::_msgtype(\"" << pp.first << "\");" << endl;
             osc_hpp << spacer << "static F8_" << ctxt._fixns << "_API const FieldTrait _traits[];" << endl;
             osc_hpp << spacer << "static F8_" << ctxt._fixns << "_API const FieldTrait_Hash_Array _ftha; " << endl;
             osc_hpp << spacer << "static F8_" << ctxt._fixns << "_API const MsgType _msgtype;" << endl;
             osc_hpp << spacer << "static F8_" << ctxt._fixns << "_API const unsigned _fieldcnt = " << pp.second._fields.get_presence().size() << ';' << endl;
       }
       if (isHeader)
       {
          osc_hpp << endl << spacer << "begin_string *_begin_string;" << endl;
          osc_hpp << spacer << "body_length *_body_length;" << endl;
          osc_hpp << spacer << "msg_type *_msg_type;" << endl;
       }
       else if (isTrailer)
          osc_hpp << endl << spacer << "check_sum *_check_sum;" << endl;
       osc_hpp << endl;
       osc_hpp << "public:" << endl;
       osc_hpp << spacer << "explicit " << pp.second._name << "(bool deepctor=true)";
       if (pp.second._fields.get_presence().size())
          osc_hpp << " : " << (isTrailer || isHeader ? "MessageBase" : "Message")
             << "(ctx(), _msgtype(), _traits, _fieldcnt, &_ftha)";
       if (isHeader || isTrailer)
       {
          osc_hpp << ',' << endl << spacer << spacer;
          if (isHeader)
             osc_hpp << "_begin_string(new begin_string(ctx()._beginStr)), _body_length(new body_length), _msg_type(new msg_type)";
          else
             osc_hpp << "_check_sum(new check_sum)";
          osc_hpp << " { add_preamble(); }" << endl;
       }
       else if (!pp.second._groups.empty())
       {
          osc_hpp << endl << spacer << '{' << endl;
          osc_hpp << spacer << spacer << "if (deepctor)" << endl;
          osc_hpp << spacer << spacer << spacer << "_groups.insert({";
          if (pp.second._groups.size() == 1)
             osc_hpp << pp.second._groups.begin()->first << ", new " << pp.second._groups.begin()->second._name << " });" << endl;
          else
          {
             osc_hpp << endl;
             for (const auto& ii : pp.second._groups)
             {
                FieldSpecMap::const_iterator gsitr(fspec.find(ii.first));
                osc_hpp << spacer << spacer << spacer << spacer << "{ " << gsitr->first << ", new " << gsitr->second._name << " }," << endl;
             }
             osc_hpp << spacer << spacer << spacer << "});" << endl;
          }
          osc_hpp << spacer << '}' << endl;
       }
       else
          osc_hpp << " {}" << endl;
       osc_hpp << spacer << "~" << pp.second._name << "() = default;" << endl;
       if (!isHeader && !isTrailer)
       {
          osc_hpp << spacer << "bool process(Router& rt) const { return (static_cast<" << ctxt._clname << "_Router&>(rt))(this); }" << endl;
          if (pp.second._is_admin)
             osc_hpp << spacer << "bool is_admin() const { return true; }" << endl;
       }
       osc_hpp << endl << spacer << "static const " << fsitr->second._name << "& get_msgtype() { return _msgtype; }" << endl;
 #if defined FIX8_HAVE_EXTENDED_METADATA
       osc_hpp << spacer << "static const FieldTrait *get_traits() { return _traits; };" << endl;
       osc_hpp << spacer << "static const unsigned get_fieldcnt() { return _fieldcnt; };" << endl;
 #endif
       if (isHeader)
          osc_hpp << endl << _csMap.find(cs_header_preamble)->second << endl;
       else if (isTrailer)
          osc_hpp << endl << _csMap.find(cs_trailer_preamble)->second << endl;
 // =============================== Repeating group nested classes ==============================
         generate_nested_group(pp.second, fspec, 1, osc_hpp, ctxt._fixns);
       generate_group_bodies(pp.second, fspec, 1, fsitr->second._name, osr_cpp, osc_hpp, globmap, ctxt._fixns);
       osc_hpp << "};" << endl << endl;
       osc_hpp << _csMap.find(cs_divider)->second << endl;
    }
 // =============================== Message class instantiation ==============================
    osc_cpp << endl;
    osc_cpp << "const char *cn[] // Component names" << endl << '{' << endl;
    osc_cpp << spacer << "\"\"," << endl;
    for (Components::iterator citr(components.begin()); citr != components.end(); ++citr)
       osc_cpp << spacer << '"' << citr->first << "\", // " << (1 + distance(components.begin(), citr)) << endl;
    osc_cpp << "};" << endl;
    osc_cpp << endl << _csMap.find(cs_end_anon_namespace)->second << endl;
    osc_cpp << endl << _csMap.find(cs_divider)->second << endl;
    osc_cpp << "const " << ctxt._fixns << "::" << ctxt._clname << "_BaseMsgEntry::Pair "
       << "msgpairs[] " << endl << '{' << endl;
    for (MessageSpecMap::const_iterator mitr(mspec.begin()); mitr != mspec.end(); ++mitr)
    {
       if (mitr != mspec.begin())
          osc_cpp << ',' << endl;
       osc_cpp << spacer << "{ \"" << mitr->first << "\", { ";
       if (mitr->second._name == "trailer" || mitr->second._name == "header")
          osc_cpp << "Type2Type<" << ctxt._fixns << "::" << mitr->second._name << ", bool>()";
       else
          osc_cpp << "Type2Type<" << ctxt._fixns << "::" << mitr->second._name << ">()";
       osc_cpp << ", \"" << mitr->second._name << '"';
       if (!mitr->second._comment.empty())
          osc_cpp << ',' << endl << spacer << spacer << '"' << mitr->second._comment << "\" }";
       else
          osc_cpp << " }";
       osc_cpp << " }";
    }
    osc_cpp << endl << "}; // " << mspec.size() << endl;
    size_t fields_generated(0);
    for (const auto& pp : fspec)
       if (gen_fields || pp.second._used)
          ++fields_generated;
    osc_cpp << endl << "extern const " << ctxt._clname << "_BaseEntry::Pair fldpairs[];" << endl << endl
       << "/// Compiler generated metadata object, accessed through this function." << endl
       << "const F8MetaCntx& ctx() // avoid SIOF" << endl << '{' << endl
       << spacer << "static const " << ctxt._clname << "_BaseMsgEntry "
          << "bme(msgpairs, " << mspec.size() << ");" << endl
       << spacer << "static const " << ctxt._clname << "_BaseEntry "
          << "be(fldpairs, " << fields_generated << ");" << endl
       << spacer << "static const F8MetaCntx _ctx(" << ctxt._version << ", bme, be, cn, \"" << ctxt._beginstr << "\");" << endl
       << spacer << "return _ctx;" << endl << '}' << endl;
    osc_cpp << endl << "} // namespace " << ctxt._fixns << endl;
 // ==================================== Message router ==================================
    osu_hpp << "class " << ctxt._clname << "_Router : public Router" << endl
       << '{' << endl << "public:" << endl;
    osu_hpp << spacer << ctxt._clname << "_Router() {}" << endl;
    osu_hpp << spacer << "virtual ~" << ctxt._clname << "_Router() {}" << endl << endl;
    osu_hpp << spacer << "virtual bool operator() (const class Message *msg) ";
    if (!nconst_router)
       osu_hpp << "const ";
    osu_hpp << "{ return false; }" << endl;
    for (const auto& pp : mspec)
    {
       if (pp.second._name == "trailer" || pp.second._name == "header")
          continue;
       osu_hpp << spacer << "virtual bool operator() (const class " << pp.second._name << " *msg)";
       if (no_default_routers)
          osu_hpp << ';' << endl;
       else
       {
          if (!nconst_router)
             osu_hpp << " const";
          osu_hpp << " { return " << (pp.second._is_admin ? "true" : "false") << "; }" << endl;
       }
    }
    osu_hpp << "};" << endl;
    // terminate files
    osc_hpp << endl << "} // namespace " << ctxt._fixns << endl;
    osc_hpp << _csMap.find(cs_end_namespace)->second << endl;
    osc_hpp << "#endif // " << bintoaschex(ctxt._out[Ctxt::classes_hpp].first.second) << endl;
    osu_hpp << endl << "} // namespace " << ctxt._fixns << endl;
    osu_hpp << _csMap.find(cs_end_namespace)->second << endl;
    osu_hpp << "#endif // " << bintoaschex(ctxt._out[Ctxt::router_hpp].first.second) << endl;
    osr_cpp << endl << "} // namespace " << ctxt._fixns << endl;
    osr_cpp << _csMap.find(cs_end_namespace)->second << endl;
    osc_cpp << endl << "// Compiler generated metadata object accessible outside namespace through this function." << endl;
    osc_cpp << "extern \"C\"" << endl << '{' << endl
       << spacer << "const F8MetaCntx& " << ctxt._fixns << "_ctx() { return " << ctxt._fixns << "::ctx(); }"
       << endl << '}' << endl << endl;
    osc_cpp << _csMap.find(cs_end_namespace)->second << endl;
    osc_cpp << endl;
 // =============================== Generate optional user session and router ==============================
    if (!gen_classes.empty())
    {
       bool is_server(gen_classes == "server");
       generate_preamble(oss_hpp, ctxt._out[Ctxt::session_hpp].first.second, true, false);
       oss_hpp << "#ifndef " << bintoaschex(ctxt._out[Ctxt::session_hpp].first.second) << endl;
       oss_hpp << "#define " << bintoaschex(ctxt._out[Ctxt::session_hpp].first.second) << endl;
       oss_hpp << endl << _csMap.find(cs_divider)->second << endl;
       oss_hpp << "// " << gen_classes << " session and router classes" << endl;
       oss_hpp << _csMap.find(cs_divider)->second << endl;
       oss_hpp << "class " << ctxt._clname << "_session_" << gen_classes << ';' << endl << endl;
       oss_hpp << "class " << ctxt._clname << "_router_" << gen_classes
          << " : public FIX8::" << ctxt._fixns << "::" << ctxt._clname << "_Router" << endl << '{' << endl;
       oss_hpp << spacer << ctxt._clname << "_session_" << gen_classes << "& _session; " << endl << endl;
       oss_hpp << "public:" << endl;
       oss_hpp << spacer << ctxt._clname << "_router_" << gen_classes
          << '(' << ctxt._clname << "_session_" << gen_classes << "& session) : _session(session) {}" << endl;
       oss_hpp << spacer << "virtual ~" << ctxt._clname << "_router_" << gen_classes << "() {}" << endl << endl;
       oss_hpp << spacer << "// Override these methods to receive specific message callbacks." << endl;
       for (const auto& pp : mspec)
       {
          if (pp.second._name == "trailer" || pp.second._name == "header")
             continue;
          oss_hpp << spacer << "// bool operator() (const FIX8::"
             << ctxt._fixns << "::" << pp.second._name << " *msg) const;" << endl;
       }
       oss_hpp << "};" << endl;
       oss_hpp << endl << _csMap.find(cs_divider)->second << endl;
       oss_hpp << "class " << ctxt._clname << "_session_" << gen_classes
          << " : public FIX8::Session" << endl << '{' << endl;
       oss_hpp << spacer << ctxt._clname << "_router_" << gen_classes << " _router; " << endl << endl;
       oss_hpp << "public:" << endl;
       oss_hpp << spacer << ctxt._clname << "_session_" << gen_classes;
       if (is_server)
       {
          oss_hpp << "(const FIX8::F8MetaCntx& ctx, FIX8::Persister *persist=0," << endl;
          oss_hpp << spacer << spacer << "FIX8::Logger *logger=0, FIX8::Logger *plogger=0) : Session"
             "(ctx, persist, logger, plogger), _router(*this) {} " << endl << endl;
       }
       else
       {
          oss_hpp << "(const FIX8::F8MetaCntx& ctx, const FIX8::SessionID& sid, FIX8::Persister *persist=0," << endl;
          oss_hpp << spacer << spacer << "FIX8::Logger *logger=0, FIX8::Logger *plogger=0) : Session"
             "(ctx, sid, persist, logger, plogger), _router(*this) {} " << endl << endl;
       }
       oss_hpp << spacer << "// Override these methods if required but remember to call the base class method first." << endl
          << spacer << "// bool handle_logon(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_logon(const unsigned heartbeat_interval, const f8String davi=f8String());" << endl
          << spacer << "// bool handle_logout(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_logout();" << endl
          << spacer << "// bool handle_heartbeat(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_heartbeat(const f8String& testReqID);" << endl
          << spacer << "// bool handle_resend_request(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_resend_request(const unsigned begin, const unsigned end=0);" << endl
          << spacer << "// bool handle_sequence_reset(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_sequence_reset(const unsigned newseqnum, const bool gapfillflag=false);" << endl
          << spacer << "// bool handle_test_request(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_test_request(const f8String& testReqID);" << endl
          << spacer << "// bool handle_reject(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// Message *generate_reject(const unsigned seqnum, const char *what);" << endl
          << spacer << "// bool handle_admin(const unsigned seqnum, const FIX8::Message *msg);" << endl
          << spacer << "// void modify_outbound(FIX8::Message *msg);" << endl
          << spacer << "// bool authenticate(SessionID& id, const FIX8::Message *msg);" << endl << endl;
       oss_hpp << spacer << "// Override these methods to intercept admin and application methods." << endl
             << spacer << "// bool handle_admin(const unsigned seqnum, const FIX8::Message *msg);" << endl << endl
             << spacer << "bool handle_application(const unsigned seqnum, const FIX8::Message *&msg);" << endl
             << spacer << "/* In your compilation unit, this should be implemented with something like the following:" << endl
             << spacer << "bool " << ctxt._clname << "_session_" << gen_classes << "::handle_application(const unsigned seqnum, const FIX8::Message *&msg)" << endl
             << spacer << '{' << endl << spacer << spacer << "return enforce(seqnum, msg) || msg->process(_router);" << endl
             << spacer << '}' << endl << spacer << "*/" << endl;
       oss_hpp << "};" << endl;
       oss_hpp << endl << "#endif // " << bintoaschex(ctxt._out[Ctxt::session_hpp].first.second) << endl;
    }
 // ================================= Field processing =====================================
    // output file preambles
    generate_preamble(ost_hpp, ctxt._out[Ctxt::types_hpp].first.second, true);
    ost_hpp << "#ifndef " << bintoaschex(ctxt._out[Ctxt::types_hpp].first.second) << endl;
    ost_hpp << "#define " << bintoaschex(ctxt._out[Ctxt::types_hpp].first.second) << endl << endl;
    ost_hpp << _csMap.find(cs_start_namespace)->second << endl;
    ost_hpp << "namespace " << ctxt._fixns << " {" << endl;
    ost_hpp << endl << _csMap.find(cs_divider)->second << endl;
    generate_preamble(ost_cpp, ctxt._out[Ctxt::types_cpp].first.second, false);
    ost_cpp << _csMap.find(cs_generated_includes)->second << endl;
    generate_includes(ost_cpp);
    ost_cpp << "#include \"" << ctxt._out[Ctxt::types_hpp].first.second << '"' << endl;
    ost_cpp << _csMap.find(cs_divider)->second << endl;
    ost_cpp << _csMap.find(cs_start_namespace)->second << endl;
    ost_cpp << "namespace " << ctxt._fixns << " {" << endl << endl;
    ost_cpp << _csMap.find(cs_start_anon_namespace)->second << endl;
    ost_cpp << endl << _csMap.find(cs_divider)->second << endl;
    // generate field types
    for (FieldSpecMap::const_iterator fitr(fspec.begin()); fitr != fspec.end(); ++fitr)
    {
       if (!gen_fields && !fitr->second._used)
          continue;
       if (!fitr->second._comment.empty())
          ost_hpp << "// " << fitr->second._comment << endl;
       const auto tyitr(FieldSpec::_typeToCPP.find(fitr->second._ftype));
       ost_hpp << "using " << fitr->second._name << " = Field<"
          << (tyitr == FieldSpec::_typeToCPP.end() ? "unknown" : tyitr->second.first) << ", " << fitr->first << ">;" << endl;
       if (fitr->second._dvals)
          process_value_enums(fitr, ost_hpp, ost_cpp);
       ost_hpp << _csMap.find(cs_divider)->second << endl;
    }
    // generate realmbase objs
    ost_cpp << endl << _csMap.find(cs_divider)->second << endl;
    ost_cpp << "const RealmBase realmbases[] " << endl << '{' << endl;
    unsigned dcnt(0);
    for (auto& pp : fspec)
    {
       if ((!pp.second._used && !gen_fields) || !pp.second._dvals)
          continue;
       const auto tyitr(FieldSpec::_typeToCPP.find(pp.second._ftype));
       ost_cpp << spacer << "{ reinterpret_cast<const void *>(" << pp.second._name << "_realm), "
          << "RealmBase::" << (pp.second._dtype == RealmBase::dt_set ? "dt_set" : "dt_range") << ", "
          << "FieldTrait::" << tyitr->second.second << ", "
          << pp.second._dvals->size() << ", " << pp.second._name << "_descriptions }," << endl;
       pp.second._doffset = dcnt++;
    }
    ost_cpp << "};" << endl;
    // generate field instantiators
    ost_cpp << endl << _csMap.find(cs_divider)->second << endl;
    ost_cpp << endl << _csMap.find(cs_end_anon_namespace)->second << endl;
    // generate field instantiator lookup
    ost_hpp << "using " << ctxt._clname << "_BaseEntry = FieldTable;" << endl;
    ost_cpp << endl << _csMap.find(cs_divider)->second << endl;
    ost_cpp << "extern const " << ctxt._clname << "_BaseEntry::Pair fldpairs[];" << endl;
    ost_cpp << "const " << ctxt._clname << "_BaseEntry::Pair fldpairs[] "
       << endl << '{' << endl;
    for (FieldSpecMap::const_iterator fitr(fspec.begin()); fitr != fspec.end(); ++fitr)
    {
       if (!gen_fields && !fitr->second._used)
          continue;
       if (fitr != fspec.begin())
          ost_cpp << ',' << endl;
       ost_cpp << spacer << "{ " << fitr->first << ", { ";
       if (fitr->second._dvals && !norealm) // generate code to create a Field using a value taken from an index into a Realm
       {
          ost_cpp << "Type2Type<" << ctxt._fixns << "::" << fitr->second._name << ", ";
          string ttype;
          if (!FieldTrait::get_type_string(fitr->second._ftype, ttype).empty())
             ost_cpp << ttype;
          else
          {
             ost_cpp << "unknown";
             cerr << shortName << ": error: unknown FieldTrait::type in realm '" << fitr->second._name << '\'' << endl;
             ++glob_errors;
          }
       }
       else
          ost_cpp << "Type2Type<" << ctxt._fixns << "::" << fitr->second._name;
       ost_cpp << ">(), \"" << fitr->second._name << "\", " << fitr->first;
       if (fitr->second._dvals)
          ost_cpp << ", &" << ctxt._fixns << "::realmbases[" << fitr->second._doffset << ']';
       if (!fitr->second._comment.empty())
       {
          ost_cpp << ", ";
          if (!fitr->second._dvals)
             ost_cpp << "nullptr, ";
          ost_cpp << endl << spacer << spacer << '"' << fitr->second._comment << '"';
       }
       ost_cpp << " } }";
    }
    ost_cpp << endl << "}; // " << fields_generated << endl;
    // terminate files
    ost_cpp << "} // namespace " << ctxt._fixns << endl;
    ost_hpp << endl << "} // namespace " << ctxt._fixns << endl;
    ost_hpp << _csMap.find(cs_end_namespace)->second << endl;
    ost_hpp << "#endif // " << bintoaschex(ctxt._out[Ctxt::types_hpp].first.second) << endl;
    ost_cpp << endl << _csMap.find(cs_end_namespace)->second << endl;
    if (verbose)
    {
       unsigned cnt(0);
       for (const auto& pp : fspec)
          if (pp.second._used)
             ++cnt;
       cout << cnt << " of " << fspec.size() << " fields used in messages" << endl;
    }
    return result;
 }
void process_group_ordering (const CommonGroupMap & gm)
Definition at line 312 of file f8cutils.cpp.
References process_message_group_ordering().
Referenced by process().
 {
    for (const auto& pp : globmap)
       for (const auto& ii : pp.second)
          process_message_group_ordering(ii.second._groups);
 }
int process_message_fields (const std::string & where, XmlElement * xt, FieldTraits & fts, const FieldToNumMap & ftonSpec, FieldSpecMap & fspec, const Components & compon)
int process_message_fields (const std::string & where, const XmlElement * xt, FieldTraits & fts, const FieldToNumMap & ftonSpec, FieldSpecMap & fspec, const Components & compon)
Definition at line 220 of file f8cutils.cpp.
References FIX8::FieldTraits::add(), XmlElement::find(), glob_errors, glob_warnings, lookup_component(), nowarn, process_special_traits(), FIX8::recover_line(), and shortName.
Referenced by load_messages(), and parse_groups().
 {
    unsigned processed(0);
    XmlElement::XmlSet flist;
    if (xt->find(where, flist))
    {
       for(const auto *pp : flist)
       {
          string fname, required;
          if (pp->GetAttr("name", fname) && pp->GetAttr("required", required))
          {
             FieldToNumMap::const_iterator ftonItr(ftonSpec.find(fname));
             FieldSpecMap::iterator fs_itr;
             if (ftonItr == ftonSpec.end() || (fs_itr = fspec.find(ftonItr->second)) == fspec.end())
             {
                cerr << shortName << ':' << recover_line(*pp) << ": error: Field element missing required attributes" << endl;
                ++glob_errors;
                continue;
             }
             string compname;
             unsigned compidx(pp->GetAttr("component", compname) ? lookup_component(compon, compname) : 0);
             // add FieldTrait
             if (!fts.add(FieldTrait(fs_itr->first, fs_itr->second._ftype, pp->GetSubIdx(), required == "Y", false, compidx)))
             {
                if (!nowarn)
                   cerr << shortName << ':' << recover_line(*pp) << ": warning: Could not add trait object '" << fname << "' (duplicate ?)" << endl;
                ++glob_warnings;
             }
             else
             {
                process_special_traits(fs_itr->first, fts);
                ++processed;
                fs_itr->second.set_used();
             }
          }
          else
          {
             cerr << shortName << ':' << recover_line(*pp) << ": error: Field element missing required attributes" << endl;
             ++glob_errors;
          }
       }
    }
    return processed;
 }
void process_message_group_ordering (const GroupMap & gm)
Definition at line 294 of file f8cutils.cpp.
Referenced by process_group_ordering().
 {
    for (const auto& pp : gm)
    {
       FieldTraitOrder go;
       for (const auto& ii : pp.second._fields.get_presence())
          go.insert({&ii});
       unsigned gcnt(0);
       for (auto *ii : go)
          ii->_pos = ++gcnt;
       if (!pp.second._groups.empty())
          process_message_group_ordering(pp.second._groups);
    }
 }
void process_ordering (MessageSpecMap & mspec)
Definition at line 279 of file f8cutils.cpp.
Referenced by process().
 {
    for (const auto& pp : mspec)
    {
       FieldTraitOrder mo;
       for (const auto& ii : pp.second._fields.get_presence())
          mo.insert({&ii});
       unsigned cnt(0);
       for (auto *ii : mo)
          ii->_pos = ++cnt;
    }
 }
void process_special_traits (const unsigned short field, FieldTraits & fts)
Definition at line 159 of file f8cutils.cpp.
References FIX8::FieldTraits::clear(), FIX8::Common_BeginString(), FIX8::Common_BodyLength(), FIX8::Common_CheckSum(), FIX8::Common_MsgType(), and FIX8::FieldTraits::set().
Referenced by process_message_fields().
 {
    switch(field)
    {
    case Common_BeginString:
    case Common_BodyLength:
    case Common_CheckSum:
       fts.set(field, FieldTrait::suppress);  // drop through
    case Common_MsgType:
       fts.set(field, FieldTrait::automatic);
       fts.clear(field, FieldTrait::mandatory);  // don't check for presence
    default:
       break;
    }
 }
void process_value_enums (FieldSpecMap::const_iterator itr, ostream & ost_hpp, ostream & ost_cpp)
Definition at line 176 of file f8cutils.cpp.
References FIX8::InPlaceReplaceInSet(), and spacer.
Referenced by process().
 {
    string typestr;
    if (FieldTrait::get_type_string(itr->second._ftype, typestr).empty())
       return;
    typestr.insert(0, "const ");
    typestr += ' ';
    ost_cpp << typestr << itr->second._name << "_realm[]  " << endl << spacer << "{ ";
    unsigned cnt(0);
    for (RealmMap::const_iterator ditr(itr->second._dvals->begin()); ditr != itr->second._dvals->end(); ++ditr)
    {
       if (cnt)
          ost_cpp << ", ";
       ost_cpp << *ditr->first;
       string transdesc(ditr->second);
       // replace any illegal c++ identifier characters
       InPlaceReplaceInSet(ident_set, transdesc, '_');
       ost_hpp << typestr << itr->second._name << '_';
       if (ditr->first->is_range())
          ost_hpp << (cnt == 0 ? "lower" : "upper");
       else if (transdesc.empty())
          ost_hpp << *ditr->first;
       else
          ost_hpp << transdesc;
       ost_hpp << '(' << *ditr->first << ");" << endl;
       ++cnt;
    }
    ost_hpp << "const size_t " << itr->second._name << "_realm_els(" << itr->second._dvals->size() << ");" << endl;
    ost_cpp << " };" << endl;
    ost_cpp << "const char *" << itr->second._name << "_descriptions[]  " << endl << spacer << "{ ";
    cnt = 0;
    for (RealmMap::const_iterator ditr(itr->second._dvals->begin()); ditr != itr->second._dvals->end(); ++ditr)
    {
       if (cnt)
          ost_cpp << ", ";
       ost_cpp << '"' << ditr->second << '"';
       ++cnt;
    }
    ost_cpp << " };" << endl;
 }
Variable Documentation
const string GETARGLIST
Referenced by print_usage().
unsigned glob_errors
Referenced by process_message_fields().
unsigned glob_warnings
Referenced by process_message_fields().
bool incpath
Referenced by generate_includes().
bool nocheck
bool nowarn
Referenced by process_message_fields().
string odir
string precompHdr
Definition at line 96 of file f8c.cpp.
Referenced by generate_preamble(), and main().
string prefix
Referenced by load_fix_version().
string shortName
Definition at line 96 of file f8c.cpp.
Referenced by load_fix_version(), and process_message_fields().
string spacer
Definition at line 96 of file f8c.cpp.
Referenced by generate_group_bodies(), generate_group_traits(), generate_nested_group(), main(), operator<<(), UsageMan::print(), process(), FIX8::XmlFileLogger::process_logline(), process_value_enums(), and MyMenu::static_probe().
bool verbose