fix8: ff_queue.hpp File Reference
ff_queue.hpp File Reference
TODO.
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <memory.h>
#include <malloc.h>
#include <stdint.h>
#include <stdexcept>
#include <vector>
#include <memory>
Classes
class ff_queue
struct ff_queue::bucket_t
Macros
#define INLINE static __inline
#define NOINLINE
#define CACHE_LINE_SIZE 128
Functions
INLINE void * aligned_malloc (size_t sz)
INLINE void aligned_free (void *mem)
INLINE void atomic_addr_store_release (void *volatile *addr, void *val)
INLINE void * atomic_addr_load_acquire (void *volatile *addr)
Detailed Description
TODO.
Definition in file ff_queue.hpp.
Macro Definition Documentation
#define CACHE_LINE_SIZE 128
Definition at line 54 of file ff_queue.hpp.
Referenced by aligned_malloc().
#define INLINE static __inline
Definition at line 51 of file ff_queue.hpp.
#define NOINLINE
Definition at line 52 of file ff_queue.hpp.
Function Documentation
INLINE void aligned_free (void * mem)
TODO
Definition at line 72 of file ff_queue.hpp.
Referenced by ff_queue::enqueue_prepare_slow(), and ff_queue::~ff_queue().
INLINE void* aligned_malloc (size_t sz)
TODO
Definition at line 61 of file ff_queue.hpp.
References CACHE_LINE_SIZE.
Referenced by ff_queue::alloc_bucket().
INLINE void* atomic_addr_load_acquire (void *volatile * addr)
TODO
Definition at line 89 of file ff_queue.hpp.
Referenced by ff_queue::dequeue_prepare(), and ff_queue::enqueue_prepare_slow().
INLINE void atomic_addr_store_release (void *volatile * addr, void * val)
TODO
Definition at line 80 of file ff_queue.hpp.
Referenced by ff_queue::dequeue_commit(), ff_queue::dequeue_prepare(), ff_queue::enqueue_commit(), and ff_queue::enqueue_prepare_slow().