fix8: filePersister_test.cpp File Reference
filePersister_test.cpp File Reference
#include <f8headers.hpp>
#include <f8includes.hpp>
#include <persist.hpp>
#include <f8utils.hpp>
#include <limits>
#include <Poco/File.h>
#include <Poco/Path.h>
#include "utest_types.hpp"
#include "utest_router.hpp"
#include "utest_classes.hpp"
#include "gtest/gtest.h"
Classes
class persist_fixture
A helper class to create/remove persist file directory.
class check_session
A helper session to check retransmitted messages.
Functions
TEST (filePersister, create_file)
TEST (filePersister, seq_control)
TEST (filePersister, message_store)
TEST (filePersister, get_last_seqnum)
TEST (filePersister, find_nearest_highest_seq)
TEST (filePersister, resend_get)
TEST (filePersister, read_from_file)
Variables
f8String curPath = Poco::Path::current()
current working path
Function Documentation
TEST (filePersister , create_file)
persist file creation test
Parameters
filePersister test suit name
create_file test case name
Definition at line 122 of file filePersister_test.cpp.
References curPath, and FIX8::exist().
TEST (filePersister , seq_control)
sequence number test
Parameters
filePersister test suit name
seq_control test case name
Definition at line 133 of file filePersister_test.cpp.
References curPath, persist_fixture::filePer, FIX8::FilePersister::get(), and FIX8::FilePersister::put().
TEST (filePersister , message_store)
message persist test
Parameters
filePersister test suit name
message_store test case name
Definition at line 163 of file filePersister_test.cpp.
References curPath, persist_fixture::filePer, FIX8::FilePersister::get(), and FIX8::FilePersister::put().
TEST (filePersister , get_last_seqnum)
last sequence number test
Parameters
filePersister test suit name
get_last_seqnum test case name
Definition at line 191 of file filePersister_test.cpp.
References curPath, persist_fixture::filePer, FIX8::FilePersister::get_last_seqnum(), and FIX8::FilePersister::put().
TEST (filePersister , find_nearest_highest_seq)
test function FilePersister::find_nearest_highest_seq
Parameters
filePersister test suit name
find_nearest_highest_seq test case name
Definition at line 218 of file filePersister_test.cpp.
References curPath, persist_fixture::filePer, FIX8::FilePersister::find_nearest_highest_seqnum(), and FIX8::FilePersister::put().
TEST (filePersister , resend_get)
test for getting a bundle of persisted messages.
Parameters
filePersister test suit name
resend_get test case name
Definition at line 272 of file filePersister_test.cpp.
References check_session::_resends, FIX8::TEX::ctx, curPath, persist_fixture::filePer, FIX8::FilePersister::get(), FIX8::pm_thread, FIX8::FilePersister::put(), and FIX8::Session::retrans_callback().
TEST (filePersister , read_from_file)
persist file read test
Parameters
filePersister test suit name
read_from_file test case name
Definition at line 303 of file filePersister_test.cpp.
References curPath, persist_fixture::filePer, FIX8::FilePersister::get(), and FIX8::FilePersister::put().
Variable Documentation
f8String curPath = Poco::Path::current()
current working path
Definition at line 115 of file filePersister_test.cpp.
Referenced by TEST().