fix8: fileLogger_test.cpp File Reference
fileLogger_test.cpp File Reference
#include "f8headers.hpp"
#include <fix8/f8includes.hpp>
#include <Poco/File.h>
#include <Poco/Path.h>
#include <Poco/Thread.h>
#include <Poco/StringTokenizer.h>
#include "gtest/gtest.h"
#include "utest_types.hpp"
#include "utest_router.hpp"
#include "utest_classes.hpp"
Classes
class log_fixture
A helper class to create/remove log directory.
Functions
void test_log_line (f8String &str, f8String seq, f8String thread, f8String direction, f8String message)
TEST (filelogger, create_logfile)
TEST (filelogger, rotate)
Function Documentation
TEST (filelogger , create_logfile)
log file creation test
Parameters
filelogger test suit name
create_logfile test case name
Definition at line 113 of file fileLogger_test.cpp.
References curPath, FIX8::Logger::direction, FIX8::exist(), FIX8::hypersleep< h_milliseconds >(), FIX8::Logger::send(), FIX8::Logger::sequence, FIX8::ebitset< T, B >::set(), FIX8::Logger::stop(), test_log_line(), FIX8::Logger::thread, and FIX8::Logger::timestamp.
TEST (filelogger , rotate)
log file rotate test
Parameters
filelogger test suit name
rotate test case name
Definition at line 157 of file fileLogger_test.cpp.
References curPath, FIX8::Logger::direction, FIX8::exist(), FIX8::FileLogger::rotate(), FIX8::Logger::sequence, FIX8::ebitset< T, B >::set(), FIX8::Logger::stop(), FIX8::Logger::thread, and FIX8::Logger::timestamp.
void test_log_line (f8String & str, f8String seq, f8String thread, f8String direction, f8String message)
helper function to test log line
Parameters
str actual result string
seq expected seq
thread expected thread number
direction expected direction
message expected log string
Definition at line 96 of file fileLogger_test.cpp.
Referenced by TEST().