var files =
[
    [ "configuration.cpp", "configuration_8cpp.html", null ],
    [ "configuration.hpp", "configuration_8hpp.html", "configuration_8hpp" ],
    [ "connection.cpp", "connection_8cpp.html", null ],
    [ "connection.hpp", "connection_8hpp.html", "connection_8hpp" ],
    [ "consolemenu.cpp", "consolemenu_8cpp.html", null ],
    [ "consolemenu.hpp", "consolemenu_8hpp.html", "consolemenu_8hpp" ],
    [ "coroutine.hpp", "coroutine_8hpp.html", "coroutine_8hpp" ],
    [ "dllmain.cpp", "dllmain_8cpp.html", null ],
    [ "f8c.cpp", "f8c_8cpp.html", "f8c_8cpp" ],
    [ "f8c.hpp", "f8c_8hpp.html", "f8c_8hpp" ],
    [ "f8config.h", "f8config_8h.html", "f8config_8h" ],
    [ "f8cstatic.hpp", "f8cstatic_8hpp.html", "f8cstatic_8hpp" ],
    [ "f8cutils.cpp", "f8cutils_8cpp.html", "f8cutils_8cpp" ],
    [ "f8dll.h", "f8dll_8h.html", "f8dll_8h" ],
    [ "f8exception.hpp", "f8exception_8hpp.html", [
      [ "f8Exception", "classFIX8_1_1f8Exception.html", "classFIX8_1_1f8Exception" ],
      [ "InvalidMetadata", "structFIX8_1_1InvalidMetadata.html", "structFIX8_1_1InvalidMetadata" ],
      [ "DuplicateField", "structFIX8_1_1DuplicateField.html", "structFIX8_1_1DuplicateField" ],
      [ "InvalidDomainValue", "structFIX8_1_1InvalidDomainValue.html", "structFIX8_1_1InvalidDomainValue" ],
      [ "InvalidField", "structFIX8_1_1InvalidField.html", "structFIX8_1_1InvalidField" ],
      [ "UnknownField", "structFIX8_1_1UnknownField.html", "structFIX8_1_1UnknownField" ],
      [ "InvalidMsgSequence", "structFIX8_1_1InvalidMsgSequence.html", "structFIX8_1_1InvalidMsgSequence" ],
      [ "MsgSequenceTooLow", "structFIX8_1_1MsgSequenceTooLow.html", "structFIX8_1_1MsgSequenceTooLow" ],
      [ "InvalidBodyLength", "structFIX8_1_1InvalidBodyLength.html", "structFIX8_1_1InvalidBodyLength" ],
      [ "InvalidMessage", "structFIX8_1_1InvalidMessage.html", "structFIX8_1_1InvalidMessage" ],
      [ "IllegalMessage", "structFIX8_1_1IllegalMessage.html", "structFIX8_1_1IllegalMessage" ],
      [ "InvalidVersion", "structFIX8_1_1InvalidVersion.html", "structFIX8_1_1InvalidVersion" ],
      [ "BadSendingTime", "structFIX8_1_1BadSendingTime.html", "structFIX8_1_1BadSendingTime" ],
      [ "BadCompidId", "structFIX8_1_1BadCompidId.html", "structFIX8_1_1BadCompidId" ],
      [ "InvalidRepeatingGroup", "structFIX8_1_1InvalidRepeatingGroup.html", "structFIX8_1_1InvalidRepeatingGroup" ],
      [ "MissingRepeatingGroupField", "structFIX8_1_1MissingRepeatingGroupField.html", "structFIX8_1_1MissingRepeatingGroupField" ],
      [ "MissingMessageComponent", "structFIX8_1_1MissingMessageComponent.html", "structFIX8_1_1MissingMessageComponent" ],
      [ "MissingMandatoryField", "structFIX8_1_1MissingMandatoryField.html", "structFIX8_1_1MissingMandatoryField" ],
      [ "BadCheckSum", "structFIX8_1_1BadCheckSum.html", "structFIX8_1_1BadCheckSum" ],
      [ "f8_threadException", "structFIX8_1_1f8__threadException.html", "structFIX8_1_1f8__threadException" ],
      [ "PeerResetConnection", "structFIX8_1_1PeerResetConnection.html", "structFIX8_1_1PeerResetConnection" ],
      [ "InvalidConfiguration", "structFIX8_1_1InvalidConfiguration.html", "structFIX8_1_1InvalidConfiguration" ],
      [ "ConfigurationError", "structFIX8_1_1ConfigurationError.html", "structFIX8_1_1ConfigurationError" ],
      [ "LogfileException", "structFIX8_1_1LogfileException.html", "structFIX8_1_1LogfileException" ],
      [ "XMLError", "structFIX8_1_1XMLError.html", "structFIX8_1_1XMLError" ]
    ] ],
    [ "f8includes.hpp", "f8includes_8hpp.html", null ],
    [ "f8precomp.cpp", "f8precomp_8cpp.html", "f8precomp_8cpp" ],
    [ "f8types.hpp", "f8types_8hpp.html", "f8types_8hpp" ],
    [ "f8utils.cpp", "f8utils_8cpp.html", "f8utils_8cpp" ],
    [ "f8utils.hpp", "f8utils_8hpp.html", "f8utils_8hpp" ],
    [ "ff_wrapper.hpp", "ff__wrapper_8hpp.html", [
      [ "ff_unbounded_queue", "classFIX8_1_1ff__unbounded__queue.html", "classFIX8_1_1ff__unbounded__queue" ],
      [ "ff_unbounded_queue< T * >", "classFIX8_1_1ff__unbounded__queue_3_01T_01_5_01_4.html", "classFIX8_1_1ff__unbounded__queue_3_01T_01_5_01_4" ]
    ] ],
    [ "field.hpp", "field_8hpp.html", "field_8hpp" ],
    [ "filepersist.cpp", "filepersist_8cpp.html", null ],
    [ "FIX50SP2.xml", "FIX50SP2_8xml.html", null ],
    [ "gzstream.cpp", "gzstream_8cpp.html", null ],
    [ "gzstream.hpp", "gzstream_8hpp.html", null ],
    [ "harness.cpp", "harness_8cpp.html", "harness_8cpp" ],
    [ "hfprint.cpp", "hfprint_8cpp.html", "hfprint_8cpp" ],
    [ "hftest.cpp", "hftest_8cpp.html", "hftest_8cpp" ],
    [ "hftest.hpp", "hftest_8hpp.html", [
      [ "tex_router_client", "classtex__router__client.html", "classtex__router__client" ],
      [ "hf_session_client", "classhf__session__client.html", "classhf__session__client" ],
      [ "tex_router_server", "classtex__router__server.html", "classtex__router__server" ],
      [ "hf_session_server", "classhf__session__server.html", "classhf__session__server" ],
      [ "MyMenu", "classMyMenu.html", "classMyMenu" ],
      [ "MenuItem", "structMyMenu_1_1MenuItem.html", "structMyMenu_1_1MenuItem" ],
      [ "RandDev", "structRandDev.html", "structRandDev" ]
    ] ],
    [ "hypersleep.hpp", "hypersleep_8hpp.html", "hypersleep_8hpp" ],
    [ "logger.cpp", "logger_8cpp.html", null ],
    [ "logger.hpp", "logger_8hpp.html", "logger_8hpp" ],
    [ "mainpage.doxygen", "mainpage_8doxygen.html", null ],
    [ "memcachedpersist.cpp", "memcachedpersist_8cpp.html", null ],
    [ "message.cpp", "message_8cpp.html", null ],
    [ "message.hpp", "message_8hpp.html", "message_8hpp" ],
    [ "messagebus.hpp", "messagebus_8hpp.html", [
      [ "GenericMessage", "classFIX8_1_1MBUS_1_1GenericMessage.html", "classFIX8_1_1MBUS_1_1GenericMessage" ],
      [ "MessageBusSubscriber", "classFIX8_1_1MBUS_1_1MessageBusSubscriber.html", "classFIX8_1_1MBUS_1_1MessageBusSubscriber" ],
      [ "MessageBus", "classFIX8_1_1MBUS_1_1MessageBus.html", "classFIX8_1_1MBUS_1_1MessageBus" ]
    ] ],
    [ "modp_numtoa.c", "modp__numtoa_8c.html", "modp__numtoa_8c" ],
    [ "mpmc.hpp", "mpmc_8hpp.html", "mpmc_8hpp" ],
    [ "multisession.hpp", "multisession_8hpp.html", "multisession_8hpp" ],
    [ "myfix.cpp", "myfix_8cpp.html", "myfix_8cpp" ],
    [ "myfix.hpp", "myfix_8hpp.html", [
      [ "tex_router_client", "classtex__router__client.html", "classtex__router__client" ],
      [ "myfix_session_client", "classmyfix__session__client.html", "classmyfix__session__client" ],
      [ "tex_router_server", "classtex__router__server.html", "classtex__router__server" ],
      [ "myfix_session_server", "classmyfix__session__server.html", "classmyfix__session__server" ],
      [ "MyMenu", "classMyMenu.html", "classMyMenu" ],
      [ "MenuItem", "structMyMenu_1_1MenuItem.html", "structMyMenu_1_1MenuItem" ],
      [ "RandDev", "structRandDev.html", "structRandDev" ]
    ] ],
    [ "Myfix_classes.cpp", "Myfix__classes_8cpp.html", "Myfix__classes_8cpp" ],
    [ "Myfix_classes.hpp", "Myfix__classes_8hpp.html", "Myfix__classes_8hpp" ],
    [ "Myfix_router.hpp", "Myfix__router_8hpp.html", "Myfix__router_8hpp" ],
    [ "Myfix_traits.cpp", "Myfix__traits_8cpp.html", null ],
    [ "Myfix_types.cpp", "Myfix__types_8cpp.html", null ],
    [ "Myfix_types.hpp", "Myfix__types_8hpp.html", "Myfix__types_8hpp" ],
    [ "myprint.cpp", "myprint_8cpp.html", "myprint_8cpp" ],
    [ "Perf_classes.cpp", "Perf__classes_8cpp.html", "Perf__classes_8cpp" ],
    [ "Perf_classes.hpp", "Perf__classes_8hpp.html", "Perf__classes_8hpp" ],
    [ "Perf_router.hpp", "Perf__router_8hpp.html", "Perf__router_8hpp" ],
    [ "Perf_traits.cpp", "Perf__traits_8cpp.html", null ],
    [ "Perf_types.cpp", "Perf__types_8cpp.html", null ],
    [ "Perf_types.hpp", "Perf__types_8hpp.html", "Perf__types_8hpp" ],
    [ "persist.cpp", "persist_8cpp.html", "persist_8cpp" ],
    [ "persist.hpp", "persist_8hpp.html", [
      [ "Persister", "classFIX8_1_1Persister.html", "classFIX8_1_1Persister" ],
      [ "BDBPersister", "classFIX8_1_1BDBPersister.html", "classFIX8_1_1BDBPersister" ],
      [ "KeyDataBuffer", "structFIX8_1_1BDBPersister_1_1KeyDataBuffer.html", "structFIX8_1_1BDBPersister_1_1KeyDataBuffer" ],
      [ "Ubuf", "unionFIX8_1_1BDBPersister_1_1KeyDataBuffer_1_1Ubuf.html", "unionFIX8_1_1BDBPersister_1_1KeyDataBuffer_1_1Ubuf" ],
      [ "KeyDataPair", "structFIX8_1_1BDBPersister_1_1KeyDataPair.html", "structFIX8_1_1BDBPersister_1_1KeyDataPair" ],
      [ "MemoryPersister", "classFIX8_1_1MemoryPersister.html", "classFIX8_1_1MemoryPersister" ],
      [ "Prec", "structFIX8_1_1Prec.html", "structFIX8_1_1Prec" ],
      [ "IPrec", "structFIX8_1_1IPrec.html", "structFIX8_1_1IPrec" ],
      [ "FilePersister", "classFIX8_1_1FilePersister.html", "classFIX8_1_1FilePersister" ]
    ] ],
    [ "runtime/precomp.cpp", "runtime_2precomp_8cpp.html", null ],
    [ "compiler/precomp.cpp", "compiler_2precomp_8cpp.html", null ],
    [ "util/precomp.cpp", "util_2precomp_8cpp.html", null ],
    [ "runtime/precomp.hpp", "runtime_2precomp_8hpp.html", null ],
    [ "compiler/precomp.hpp", "compiler_2precomp_8hpp.html", null ],
    [ "util/precomp.hpp", "util_2precomp_8hpp.html", null ],
    [ "redispersist.cpp", "redispersist_8cpp.html", null ],
    [ "seqedit.cpp", "seqedit_8cpp.html", "seqedit_8cpp" ],
    [ "session.cpp", "session_8cpp.html", null ],
    [ "session.hpp", "session_8hpp.html", "session_8hpp" ],
    [ "sessionwrapper.hpp", "sessionwrapper_8hpp.html", [
      [ "SessionConfig", "structFIX8_1_1SessionConfig.html", "structFIX8_1_1SessionConfig" ],
      [ "ClientSessionBase", "classFIX8_1_1ClientSessionBase.html", "classFIX8_1_1ClientSessionBase" ],
      [ "ClientSession", "classFIX8_1_1ClientSession.html", "classFIX8_1_1ClientSession" ],
      [ "ReliableClientSession", "classFIX8_1_1ReliableClientSession.html", "classFIX8_1_1ReliableClientSession" ],
      [ "SessionInstance", "classFIX8_1_1SessionInstance.html", "classFIX8_1_1SessionInstance" ],
      [ "ServerSessionBase", "classFIX8_1_1ServerSessionBase.html", "classFIX8_1_1ServerSessionBase" ],
      [ "ServerSession", "classFIX8_1_1ServerSession.html", "classFIX8_1_1ServerSession" ],
      [ "SessionInstanceBase", "classFIX8_1_1SessionInstanceBase.html", "classFIX8_1_1SessionInstanceBase" ],
      [ "SessionInstance", "classFIX8_1_1SessionInstance.html", "classFIX8_1_1SessionInstance" ]
    ] ],
    [ "thread.hpp", "thread_8hpp.html", "thread_8hpp" ],
    [ "tickval.hpp", "tickval_8hpp.html", [
      [ "Tickval", "classFIX8_1_1Tickval.html", "classFIX8_1_1Tickval" ]
    ] ],
    [ "timer.hpp", "timer_8hpp.html", [
      [ "Timer", "classFIX8_1_1Timer.html", "classFIX8_1_1Timer" ],
      [ "TimerEvent", "classFIX8_1_1TimerEvent.html", "classFIX8_1_1TimerEvent" ],
      [ "Timer", "classFIX8_1_1Timer.html", "classFIX8_1_1Timer" ],
      [ "IntervalTimer", "classFIX8_1_1IntervalTimer.html", "classFIX8_1_1IntervalTimer" ]
    ] ],
    [ "traits.cpp", "traits_8cpp.html", null ],
    [ "traits.hpp", "traits_8hpp.html", "traits_8hpp" ],
    [ "usage.hpp", "usage_8hpp.html", [
      [ "UsageMan", "classUsageMan.html", "classUsageMan" ]
    ] ],
    [ "xml.cpp", "xml_8cpp.html", "xml_8cpp" ],
    [ "xml.hpp", "xml_8hpp.html", "xml_8hpp" ],
    [ "yield.hpp", "yield_8hpp.html", "yield_8hpp" ],
    [ "zeromq_mbus.hpp", "zeromq__mbus_8hpp.html", null ]
];