fix8: harness.cpp File Reference
harness.cpp File Reference
#include <iostream>
#include <memory>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <typeinfo>
#include <sys/ioctl.h>
#include <signal.h>
#include <termios.h>
#include <regex.h>
#include <errno.h>
#include <string.h>
#include <f8includes.hpp>
#include <usage.hpp>
#include <consolemenu.hpp>
#include "Myfix_types.hpp"
#include "Myfix_router.hpp"
#include "Myfix_classes.hpp"
#include "myfix.hpp"
Namespaces
namespace FIX8
Your bog standard RAII scoped lock.
namespace FIX8::TEX
Functions
void print_usage ()
const string GETARGLIST ("hl:svqc:R:S:rp:")
bool term_received (false)
bool quiet (false)
void sig_handler (int sig)
int main (int argc, char **argv)
Detailed Description
This is a complete working example of a FIX client/server using FIX8.
Usage: harness [-RSchlqrsv]
-R,–receive set next expected receive sequence number
-S,–send set next send sequence number
-c,–config xml config (default: myfix_client.xml or myfix_server.xml)
-h,–help help, this screen
-l,–log global log filename
-q,–quiet do not print fix output
-r,–reliable start in reliable mode
-s,–server run in server mode (default client mode)
-v,–version print version then exit
To use start the server:
% harness -sl server
In another terminal session, start the client:
% harness -l client
Notes
If you have configured with –enable-msgrecycle, the example will reuse allocated messages.
If you have configured with –enable-customfields, the example will add custom fields
defined below.
The client has a simple menu. Press ? to see options.
The server will wait for the client to logout before exiting.
The server uses myfix_client.xml and the client uses myfix_server.xml for configuration settings.
The example uses the files FIX50SP2.xml and FIXT11.xml in ./schema
Definition in file harness.cpp.
Function Documentation
const string GETARGLIST ("hl:svqc:R:S:rp:")
int main (int argc, char ** argv)
Definition at line 173 of file harness.cpp.
References FIX8::TEX::ctx(), MyMenu::get_tty(), GETARGLIST, FIX8::hypersleep< h_seconds >(), RandDev::init(), PACKAGE, print_usage(), quiet(), FIX8::tty_save_state::set_raw_mode(), sig_handler(), term_received(), VERSION, and FIX8::f8Exception::what().
void print_usage ()
Definition at line 349 of file f8cutils.cpp.
bool quiet (false)
Referenced by main().
void sig_handler (int sig)
Definition at line 157 of file harness.cpp.
References term_received().
Referenced by main(), and sig_handler().
bool term_received (false)
Referenced by main(), and sig_handler().