fix8: hfprint.cpp File Reference
hfprint.cpp File Reference
#include <iostream>
#include <memory>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <typeinfo>
#include <sys/ioctl.h>
#include <signal.h>
#include <termios.h>
#include <errno.h>
#include <string.h>
#include <fix8/f8includes.hpp>
#include <fix8/usage.hpp>
#include <fix8/consolemenu.hpp>
#include "Perf_types.hpp"
#include "Perf_router.hpp"
#include "Perf_classes.hpp"
#include "hftest.hpp"
Typedefs
using MessageCount = map< string, unsigned >
Functions
void print_usage ()
const string GETARGLIST ("hsvo:c")
bool term_received (false)
bool summary (false)
void sig_handler (int sig)
int main (int argc, char **argv)
Detailed Description
This is a simple logfile/logstream printer using the metadata generated for hftest.cpp.
hfprint – f8 protocol log printer
Usage: hfprint [-hosv] <fix protocol file, use '-' for stdin>
-h,–help help, this screen
-o,–offset bytes to skip on each line before parsing FIX message
-s,–summary summary, generate message summary
-v,–version print version then exit
e.g.
hfprint myfix_server_protocol.log
cat myfix_client_protocol.log | hfprint -
Definition in file hfprint.cpp.
Typedef Documentation
using MessageCount = map<string, unsigned>
Definition at line 102 of file hfprint.cpp.
Function Documentation
const string GETARGLIST ("hsvo:c")
Referenced by main(), and print_usage().
int main (int argc, char ** argv)
Definition at line 118 of file hfprint.cpp.
References FIX8::F8MetaCntx::_beginStr, FIX8::BaseMsgEntry::_name, FIX8::TEX::ctx(), FIX8_PACKAGE, FIX8_VERSION, GETARGLIST(), inputFile, print_usage(), sig_handler(), summary(), term_received(), FIX8::F8MetaCntx::version(), and FIX8::f8Exception::what().
 {
    int val, offset(0);
 #ifdef FIX8_HAVE_GETOPT_LONG
    option long_options[]
    {
       { "help",         0, 0, 'h' },
       { "offset",       1, 0, 'o' },
       { "version",      0, 0, 'v' },
       { "summary",      0, 0, 's' },
       { "context",      0, 0, 'c' },
       { 0 },
    };
    while ((val = getopt_long (argc, argv, GETARGLIST.c_str(), long_options, 0)) != -1)
 #else
    while ((val = getopt (argc, argv, GETARGLIST.c_str())) != -1)
 #endif
    {
       switch (val)
       {
       case 'v':
          cout << argv[0] << " for " FIX8_PACKAGE " version " FIX8_VERSION << endl;
          cout << "Released under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3. See <http://fsf.org/> for details." << endl;
          return 0;
       case ':': case '?': return 1;
       case 'h': print_usage(); return 0;
       case 'o': offset = stoi(optarg); break;
       case 's': summary = true; break;
       case 'c':
           cout << "Context FIX beginstring:" << TEX::ctx()._beginStr << endl;
           cout << "Context FIX version:" << TEX::ctx().version() << endl;
           return 0;
       default: break;
       }
    }
    signal(SIGTERM, sig_handler);
    signal(SIGINT, sig_handler);
    string inputFile;
    if (optind < argc)
       inputFile = argv[optind];
    if (inputFile.empty())
    {
       print_usage();
       return 1;
    }
    bool usestdin(inputFile == "-");
    filestdin ifs(usestdin ? &cin : new ifstream(inputFile.c_str()), usestdin);
    if (!ifs())
    {
       cerr << "Could not open " << inputFile << endl;
       return 1;
    }
    unsigned msgs(0);
    MessageCount *mc(summary ? new MessageCount : 0);
    const int bufsz(4096);
    char buffer[bufsz];
    try
    {
       while (!ifs().eof() && !term_received)
       {
          ifs().getline(buffer, bufsz);
          if (buffer[0])
          {
             unique_ptr<Message> msg(Message::factory(TEX::ctx(), buffer + offset));
             if (summary)
             {
                MessageCount::iterator mitr(mc->find(msg->get_msgtype()));
                if (mitr == mc->end())
                   mc->insert({msg->get_msgtype(), 1});
                else
                   mitr->second++;
             }
             cout << *msg << endl;
             ++msgs;
          }
       }
       if (term_received)
          cerr << "interrupted" << endl;
    }
    catch (f8Exception& e)
    {
       cerr << "exception: " << e.what() << endl;
    }
    catch (exception& e) // also catches Poco::Net::NetException
    {
       cerr << "exception: " << e.what() << endl;
    }
    cout << msgs << " messages decoded." << endl;
    if (summary)
    {
       for (MessageCount::const_iterator mitr(mc->begin()); mitr != mc->end(); ++mitr)
       {
          const BaseMsgEntry *bme(TEX::ctx()._bme.find_ptr(mitr->first.c_str()));
          cout << setw(20) << left << bme->_name << " (\"" << mitr->first << "\")" << '\t' << mitr->second << endl;
       }
    }
    return 0;
 }
void print_usage ()
Definition at line 229 of file hfprint.cpp.
References UsageMan::add(), GETARGLIST(), UsageMan::print(), and UsageMan::setdesc().
Referenced by main().
 {
    UsageMan um("hfprint", GETARGLIST, "<fix protocol file, use '-' for stdin>");
    um.setdesc("hfprint -- f8 protocol log printer");
    um.add('h', "help", "help, this screen");
    um.add('v', "version", "print version then exit");
    um.add('o', "offset", "bytes to skip on each line before parsing FIX message");
    um.add('s', "summary", "summary, generate message summary");
    um.add("e.g.");
    um.add("@hfprint myfix_server_protocol.log");
    um.add("@hfprint hfprint -s -o 12 myfix_client_protocol.log");
    um.add("@cat myfix_client_protocol.log | hfprint -");
    um.print(cerr);
 }
void sig_handler (int sig)
Definition at line 105 of file hfprint.cpp.
References term_received().
Referenced by main().
 {
    switch (sig)
    {
    case SIGTERM:
    case SIGINT:
       term_received = true;
       signal(sig, sig_handler);
       break;
    }
 }
bool summary (false)
Referenced by main().
bool term_received (false)
Referenced by main(), and sig_handler().