fix8: hftest.cpp File Reference
hftest.cpp File Reference
#include <iostream>
#include <memory>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <typeinfo>
#include <sys/ioctl.h>
#include <signal.h>
#include <termios.h>
#include <errno.h>
#include <string.h>
#include <fix8/f8includes.hpp>
#include <fix8/usage.hpp>
#include "Perf_types.hpp"
#include "Perf_router.hpp"
#include "Perf_classes.hpp"
#include "hftest.hpp"
Namespaces
FIX8
FIX8::TEX
Functions
void print_usage ()
const string GETARGLIST ("hl:svqc:R:S:rb:p:u:o")
bool term_received (false)
unsigned batch_size (1000)
unsigned preload_count (0)
unsigned update_count (5000)
bool quiet (true)
void sig_handler (int sig)
int main (int argc, char **argv)
Detailed Description
This is a complete working example of a HF FIX client/server using FIX8.
Usage: hftest [-RSchlqrsv]
-R,–receive set next expected receive sequence number
-S,–send set next send sequence number
-c,–config xml config (default: hf_client.xml or hf_server.xml)
-h,–help help, this screen
-l,–log global log filename
-q,–quiet do not print fix output
-u,–update update interval for console counters (default 5000)
-r,–reliable start in reliable mode
-s,–server run in server mode (default client mode)
-v,–version print version then exit
To use start the server:
% hftest -sl server
In another terminal session, start the client:
% hftest -l client
Notes
Configure with –enable-codectiming
The client has a simple menu. Press ? to see options.
The server will wait for the client to logout before exiting.
Press P to preload NewOrderSingle messages, T to transmit them.
The server uses hf_client.xml and the client uses hf_server.xml for configuration settings.
The example uses FIX42.xml
Definition in file hftest.cpp.
Function Documentation
unsigned batch_size (1000)
Referenced by MyMenu::batch_preload_new_order_single(), main(), and MyMenu::send_all_preloaded().
const string GETARGLIST ("hl:svqc:R:S:rb:p:u:o")
Referenced by main(), and print_usage().
int main (int argc, char ** argv)
Definition at line 172 of file hftest.cpp.
References batch_size(), FIX8::TEX::ctx(), FIX8_PACKAGE, FIX8_VERSION, GETARGLIST(), RandDev::init(), FIX8::SingleLogger< fn >::log(), next_receive(), next_send(), FIX8::pm_coro, FIX8::pm_pipeline, preload_count(), MyMenu::preload_new_order_single(), FIX8::Session::print, print_usage(), quiet(), FIX8::SingleLogger< fn >::set_global_filename(), sig_handler(), term_received(), update_count(), and FIX8::f8Exception::what().
 {
    int val;
    bool server(false), once(false), reliable(false);
    string clcf;
    unsigned next_send(0), next_receive(0);
 #ifdef FIX8_HAVE_GETOPT_LONG
    option long_options[]
    {
       { "help",      0, 0, 'h' },
       { "version",   0, 0, 'v' },
       { "once",      0, 0, 'o' },
       { "log",       1, 0, 'l' },
       { "config",    1, 0, 'c' },
       { "server",    0, 0, 's' },
       { "batch",     1, 0, 'b' },
       { "send",      1, 0, 'S' },
       { "receive",   1, 0, 'R' },
       { "quiet",     0, 0, 'q' },
       { "reliable",  0, 0, 'r' },
       { "preload",   1, 0, 'p' },
       { "update",    1, 0, 'u' },
       { 0 },
    };
    while ((val = getopt_long (argc, argv, GETARGLIST.c_str(), long_options, 0)) != -1)
 #else
    while ((val = getopt (argc, argv, GETARGLIST.c_str())) != -1)
 #endif
    {
       switch (val)
       {
       case 'v':
          cout << argv[0] << " for " FIX8_PACKAGE " version " FIX8_VERSION << endl;
          cout << "Released under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3. See <http://fsf.org/> for details." << endl;
          return 0;
       case ':': case '?': return 1;
       case 'h': print_usage(); return 0;
       case 'l': FIX8::GlobalLogger::set_global_filename(optarg); break;
       case 'c': clcf = optarg; break;
       case 'b': batch_size = stoul(optarg); break;
       case 'p': preload_count = stoul(optarg); break;
       case 'u': update_count = stoul(optarg); break;
       case 's': server = true; break;
       case 'o': once = true; break;
       case 'S': next_send = stoul(optarg); break;
       case 'R': next_receive = stoul(optarg); break;
       case 'q': quiet = false; break;
       case 'r': reliable = true; break;
       default: break;
       }
    }
    RandDev::init();
    signal(SIGTERM, sig_handler);
    signal(SIGINT, sig_handler);
 #ifndef _MSC_VER
     signal(SIGQUIT, sig_handler);
 #endif
    try
    {
       const string conf_file(server ? clcf.empty() ? "hf_server.xml" : clcf : clcf.empty() ? "hf_client.xml" : clcf);
       if (server)
       {
          unique_ptr<FIX8::ServerSessionBase> ms(new FIX8::ServerSession<hf_session_server>(FIX8::TEX::ctx(), conf_file, "TEX1"));
          XmlElement::XmlSet eset;
          for (unsigned scnt(0); !term_received; )
          {
             if (!ms->poll())
                continue;
             unique_ptr<FIX8::SessionInstanceBase> inst(ms->create_server_instance());
             if (!quiet)
                inst->session_ptr()->control() |= FIX8::Session::print;
             ostringstream sostr;
             sostr << "client(" << ++scnt << ") connection established.";
             FIX8::GlobalLogger::log(sostr.str());
             const FIX8::ProcessModel pm(ms->get_process_model(ms->_ses));
             inst->start(pm == FIX8::pm_pipeline, next_send, next_receive);
             cout << (pm == FIX8::pm_pipeline ? "Pipelined" : "Threaded") << " mode." << endl;
             if (inst->session_ptr()->get_connection()->is_secure())
                cout << "Session is secure (SSL)" << endl;
             if (pm != FIX8::pm_pipeline)
                while (!inst->session_ptr()->is_shutdown())
                   FIX8::hypersleep<FIX8::h_milliseconds>(100);
             cout << "Session(" << scnt << ") finished." << endl;
             inst->stop();
 #if defined FIX8_CODECTIMING
             FIX8::Message::report_codec_timings("server");
 #endif
             if (once)
                break;
          }
       }
       else
       {
          unique_ptr<FIX8::ClientSessionBase>
             mc(reliable ? new FIX8::ReliableClientSession<hf_session_client>(FIX8::TEX::ctx(), conf_file, "DLD1")
                         : new FIX8::ClientSession<hf_session_client>(FIX8::TEX::ctx(), conf_file, "DLD1"));
          if (!quiet)
             mc->session_ptr()->control() |= FIX8::Session::print;
          const FIX8::ProcessModel pm(mc->get_process_model(mc->_ses));
          if (!reliable)
             mc->start(false, next_send, next_receive, mc->session_ptr()->get_login_parameters()._davi());
          else
             mc->start(false, next_send, next_receive);
          MyMenu mymenu(*mc->session_ptr(), 0, cout);
          cout << endl << "Menu started. Press '?' for help..." << endl << endl;
          if (mc->session_ptr()->get_connection()->is_secure())
             cout << "Session is secure (SSL)" << endl;
          if (preload_count)
             mymenu.preload_new_order_single();
          char ch;
          mymenu.get_tty().set_raw_mode();
          if (pm == FIX8::pm_coro)
          {
             cout << "Coroutine mode." << endl;
             fd_set rfds;
             timeval tv {};
             while (!term_received)
             {
                mc->session_ptr()->get_connection()->reader_execute();
                char ch(0);
                FD_ZERO(&rfds);
                FD_SET(0, &rfds);
 #ifdef _MSC_VER
                if (kbhit())
                {
                   ch = getch();
 #else
                if (select(1, &rfds, 0, 0, &tv) > 0)
                {
                   if (read (0, &ch, 1) < 0)
                      break;
 #endif
                   if (ch == 'a')
                   {
                      cout << "Sending messages..." << endl;
                      coroutine coro;
                      while(mymenu.send_all_preloaded(coro, mc->session_ptr()))
                         mc->session_ptr()->get_connection()->reader_execute();
                   }
                   else if (ch == 0x3 || !mymenu.process(ch))
                      break;
                }
             }
          }
          else
          {
             cout << (pm == FIX8::pm_pipeline ? "Pipelined" : "Threaded") << " mode." << endl;
             while(!mymenu.get_istr().get(ch).bad() && !term_received && ch != 0x3 && mymenu.process(ch))
                ;
          }
          cout << endl;
 #if defined FIX8_CODECTIMING
          FIX8::Message::report_codec_timings("client");
 #endif
          if (!mc->session_ptr()->is_shutdown())
             mc->session_ptr()->stop();
          mymenu.get_tty().unset_raw_mode();
       }
    }
    catch (FIX8::f8Exception& e)
    {
       cerr << "exception: " << e.what() << endl;
    }
    catch (exception& e) // also catches Poco::Net::NetException
    {
       cerr << "exception: " << e.what() << endl;
    }
    if (term_received)
       cout << "terminated." << endl;
    return 0;
 }
unsigned preload_count (0)
Referenced by MyMenu::batch_preload_new_order_single(), main(), and MyMenu::preload_new_order_single().
void print_usage ()
Definition at line 557 of file hftest.cpp.
References UsageMan::add(), GETARGLIST(), UsageMan::print(), and UsageMan::setdesc().
Referenced by main().
 {
    UsageMan um("hftest", GETARGLIST, "");
    um.setdesc("hftest -- f8 HF test client/server");
    um.add('s', "server", "run in server mode (default client mode)");
    um.add('h', "help", "help, this screen");
    um.add('v', "version", "print version then exit");
    um.add('l', "log", "global log filename");
    um.add('c', "config", "xml config (default: hf_client.xml or hf_server.xml)");
    um.add('o', "once", "for server, allow one client session then exit");
    um.add('q', "quiet", "do not print fix output (default yes)");
    um.add('b', "batch", "if using batch send, number of messages in each batch (default 1000)");
    um.add('p', "preload", "if batching or preloading, default number of messages to create");
    um.add('R', "receive", "set next expected receive sequence number");
    um.add('S', "send", "set next send sequence number");
    um.add('r', "reliable", "start in reliable mode");
    um.add('u', "update", "message count update frequency (default 5000)");
    um.print(cerr);
 }
bool quiet (true)
Referenced by main().
void sig_handler (int sig)
Definition at line 153 of file hftest.cpp.
References term_received().
Referenced by main().
 {
    switch (sig)
    {
    case SIGTERM:
    case SIGINT:
 #ifndef _MSC_VER
    case SIGQUIT:
 #endif
       term_received = true;
       signal(sig, sig_handler);
       break;
    default:
       cerr << sig << endl;
       break;
    }
 }
bool term_received (false)
Referenced by main(), and sig_handler().
unsigned update_count (5000)
Referenced by main(), tex_router_client::operator()(), and MyMenu::send_all_preloaded().