fix8: mapping_utils.hpp File Reference
mapping_utils.hpp File Reference
This file contains utilities for thread pinning to cores and thread mapping.
#include <iostream>
#include <errno.h>
#include <ff/config.hpp>
#include <stddef.h>
Functions
static long ff_getThreadID ()
Returns the ID of the calling thread.
static unsigned long ff_getCpuFreq ()
Returnes the frequency of the CPU.
static int ff_numCores ()
Returns the number of cores in the system.
static int ff_setPriority (int priority_level=0)
Sets the scheduling priority.
static int ff_getMyCpu ()
Returns the ID of the CPU.
static int ff_mapThreadToCpu (int cpu_id, int priority_level=0)
Maps the calling thread to the given CPU.
Detailed Description
This file contains utilities for thread pinning to cores and thread mapping.
This file provides support for thread pinning and mapping at linux and MacOS.
Definition in file mapping_utils.hpp.
Function Documentation
static unsigned long ff_getCpuFreq () inline static
Returnes the frequency of the CPU.
It returns the frequency of the CPUs (On a shared memory system, all cores have the same frequency). It works on Linux OS and Apple OS.
Returns
An integer value showing the frequency of the core.
Definition at line 102 of file mapping_utils.hpp.
static int ff_getMyCpu () inline static
Returns the ID of the CPU.
It returns the ID of the CPU where the calling thread is running. It works on Linux OS and Apple OS.
Returns
An integer value showing the ID of the core. If the ID of the core is not found, then -1 is returned.
Definition at line 230 of file mapping_utils.hpp.
static long ff_getThreadID () inline static
Returns the ID of the calling thread.
It returns the ID of the calling thread. It works on Linux OS, Apple OS, Windows.
Returns
if successful the identifier of the thread is returned. Otherwise a negative vlue is returned.
Definition at line 81 of file mapping_utils.hpp.
static int ff_mapThreadToCpu (int cpu_id, int priority_level = 0) inline static
Maps the calling thread to the given CPU.
It maps the calling thread to the given core. It works on Linux OS, Apple OS, Windows.
Parameters
cpu_id the ID of the CPU to which the thread will be attached.
priority_level TODO
Returns
An integet value showing the priority level is returned if successful. Otherwise EINVAL is returned.
Definition at line 273 of file mapping_utils.hpp.
References ff_numCores(), and ff_setPriority().
Referenced by ff::ff_node::thWorker::svc_init().
static int ff_numCores () inline static
Returns the number of cores in the system.
It returns the number of cores present in the system. (Note that it does not take into account hyper threadings). It works on Linux OS, Apple OS and Windows.
Returns
An integer value showing the number of cores.
Definition at line 135 of file mapping_utils.hpp.
Referenced by ff_mapThreadToCpu(), and ff::threadMapper::threadMapper().
static int ff_setPriority (int priority_level = 0) inline static
Sets the scheduling priority.
It sets the scheduling priority of the process (or thread). The priority_level is a value in the range -20 to 19. The default priority is 0, lower priorities cause more favorable scheduling.
MA: This should be redesigned since it might have different behaviours in different systems.
priority_level defines the level of the priority. Default is set to 0.
Returns
An integer value showing the priority of the scheduling policy.
Definition at line 172 of file mapping_utils.hpp.
Referenced by ff_mapThreadToCpu().