fix8: mem_man.h File Reference
mem_man.h File Reference
#include <sys/sysinfo.h>
#include <cstdio>
#include <iostream>
#include <unistd.h>
#include <cstdlib>
#include <pthread.h>
Macros
#define MAX_RAM_PRESSURE_WAIT 0.5
#define MIN_RAM_PRESSURE_SIGNAL 0.6
Functions
double get_free_ram ()
void pushwait ()
void popsignal ()
Variables
pthread_mutex_t count_mutex = PTHREAD_MUTEX_INITIALIZER
pthread_cond_t condition_var = PTHREAD_COND_INITIALIZER
Macro Definition Documentation
#define MAX_RAM_PRESSURE_WAIT 0.5
Definition at line 17 of file mem_man.h.
Referenced by pushwait().
#define MIN_RAM_PRESSURE_SIGNAL 0.6
Definition at line 18 of file mem_man.h.
Referenced by popsignal().
Function Documentation
double get_free_ram ()
Definition at line 35 of file mem_man.h.
Referenced by popsignal(), and pushwait().
void popsignal ()
Definition at line 88 of file mem_man.h.
References condition_var, count_mutex, get_free_ram(), MIN_RAM_PRESSURE_SIGNAL, pthread_cond_signal(), pthread_mutex_lock(), and pthread_mutex_unlock().
void pushwait ()
Definition at line 71 of file mem_man.h.
References condition_var, count_mutex, get_free_ram(), MAX_RAM_PRESSURE_WAIT, pthread_cond_wait(), pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by ff::ff_gatherer::ff_gatherer(), ff::ff_loadbalancer::ff_loadbalancer(), ff::ff_node::ff_node(), ff::ff_gatherer::losetime_out(), and ff::ff_loadbalancer::losetime_out().
Variable Documentation
pthread_cond_t condition_var = PTHREAD_COND_INITIALIZER
Definition at line 69 of file mem_man.h.
Referenced by popsignal(), and pushwait().
pthread_mutex_t count_mutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 68 of file mem_man.h.
Referenced by popsignal(), and pushwait().