fix8: message_test.cpp File Reference
message_test.cpp File Reference
#include "f8headers.hpp"
#include <f8includes.hpp>
#include "gtest/gtest.h"
#include "utest_types.hpp"
#include "utest_router.hpp"
#include "utest_classes.hpp"
Macros
#define FIELD_TEST(field, expect, message, test_fun)
Functions
TEST (message, missing_field)
TEST (message, logon_decode)
TEST (message, neworder_decode)
TEST (message, neworder_group_decode)
TEST (message, calc_chksum)
TEST (message, fmt_chksum)
void extract_element_test (f8String msg, f8String expect_tag, f8String expect_val)
TEST (message, extract_element)
TEST (message, logon_encode)
TEST (message, neworder_encode)
TEST (message, nestedGroup_encode)
Macro Definition Documentation
#define FIELD_TEST (field, expect, message, test_fun)
Value:
{\
    UTEST::field value; \
    message->get(value); \
    test_fun(expect, value()); \
}
Definition at line 85 of file message_test.cpp.
Referenced by TEST().
Function Documentation
void extract_element_test (f8String msg, f8String expect_tag, f8String expect_val)
helper to test MessageBase::extract_element
Parameters
msg field string
expect_tag expected field tag
expect_val expected field val
Definition at line 248 of file message_test.cpp.
References FIX8::MessageBase::extract_element(), and MAX_FLD_LENGTH.
Referenced by TEST().
TEST (message , missing_field)
message missing mandatory field
Parameters
message test suit name
missing_field test case name
Definition at line 61 of file message_test.cpp.
References FIX8::TEX::ctx(), and FIX8::Message::factory().
TEST (message , logon_decode)
logon decoding test
Parameters
message test suit name
logon_decode test case name
Definition at line 71 of file message_test.cpp.
References FIX8::TEX::ctx(), FIX8::Message::factory(), FIX8::MessageBase::get_msgtype(), FIX8::Message::Header(), FIX8::Message::is_admin(), and FIX8::Message::Trailer().
TEST (message , neworder_decode)
new order entry decoding test
Parameters
message test suit name
neworder_decode test case name
Definition at line 95 of file message_test.cpp.
References FIX8::TEX::ctx(), FIX8::Message::factory(), FIELD_TEST, FIX8::MessageBase::get_msgtype(), FIX8::MessageBase::has(), FIX8::Message::Header(), FIX8::Message::is_admin(), and FIX8::Message::Trailer().
TEST (message , neworder_group_decode)
new order entry (with repeating groups) decoding test
Parameters
message test suit name
neworder_group_decode test case name
Definition at line 184 of file message_test.cpp.
References FIX8::TEX::ctx(), FIX8::Message::factory(), FIELD_TEST, FIX8::MessageBase::find_group(), FIX8::GroupBase::get_element(), and FIX8::GroupBase::size().
TEST (message , calc_chksum)
checksum test
Parameters
message test suit name
calc_chksum test case name
Definition at line 210 of file message_test.cpp.
References FIX8::Message::calc_chksum().
TEST (message , fmt_chksum)
checksum formating test
Parameters
message test suit name
fmt_chksum test case name
Definition at line 235 of file message_test.cpp.
References FIX8::Message::fmt_chksum().
TEST (message , extract_element)
MessageBase::extract_element test
Parameters
message test suit name
extract_element test case name
Definition at line 267 of file message_test.cpp.
References extract_element_test().
TEST (message , logon_encode)
logon encoding test
Parameters
message test suit name
logon_encode test case name
Definition at line 279 of file message_test.cpp.
TEST (message , neworder_encode)
new order entry encoding test
Parameters
message test suit name
neworder_encode test case name
Definition at line 296 of file message_test.cpp.
References FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION(), FIX8::TEX::OrdType_LIMIT(), FIX8::TEX::SecurityType_OPTION(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_DAY().
TEST (message , nestedGroup_encode)
new order entry (with repeating groups) encoding test
Parameters
message test suit name
nestedGroup_encode test case name
Definition at line 344 of file message_test.cpp.
References FIX8::GroupBase::create_group().