Fix8: myprint.cpp File Reference
myprint.cpp File Reference
#include <iostream>
#include <memory>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <bitset>
#include <typeinfo>
#include <sys/ioctl.h>
#include <signal.h>
#include <termios.h>
#include <regex.h>
#include <errno.h>
#include <string.h>
#include <f8includes.hpp>
#include <usage.hpp>
#include "Myfix_types.hpp"
#include "Myfix_router.hpp"
#include "Myfix_classes.hpp"
#include "myfix.hpp"
#include "myfix_custom.hpp"
Classes
class filestdin
Abstract file or stdin input.
Typedefs
typedef map< string, unsigned > MessageCount
Functions
void print_usage ()
const string GETARGLIST ("hsvo:")
bool term_received (false)
bool summary (false)
void sig_handler (int sig)
int main (int argc, char **argv)
Detailed Description
This is a simple logfile/logstream printer using the metadata generated for myfix.cpp.
f8print -- f8 protocol log printer
Usage: f8print [-hosv] <fix protocol file, use '-' for stdin> -h,--help help, this screen -o,--offset bytes to skip on each line before parsing FIX message -s,--summary summary, generate message summary -v,--version print version then exit e.g. f8print myfix_server_protocol.log cat myfix_client_protocol.log | f8print -
Definition in file myprint.cpp.
Typedef Documentation
typedef map<string, unsigned> MessageCount
Definition at line 96 of file myprint.cpp.
Function Documentation
const string GETARGLIST ("hsvo:")
int main (int argc, char ** argv)
Definition at line 131 of file myprint.cpp.
References FIX8::BaseMsgEntry::_name, FIX8::TEX::ctx, FIX8::MessageBase::get_msgtype(), GETARGLIST, inputFile, PACKAGE, print_usage(), FIX8::F8MetaCntx::set_ube(), sig_handler(), summary(), term_received(), VERSION, and FIX8::f8Exception::what().
void print_usage ()
Definition at line 314 of file f8cutils.cpp.
References UsageMan::add(), GETARGLIST, UsageMan::print(), and UsageMan::setdesc().
Referenced by main().
void sig_handler (int sig)
Definition at line 99 of file myprint.cpp.
References sig_handler(), and term_received().
bool summary (false)
Referenced by main().
bool term_received (false)
Referenced by main(), and sig_handler().