fix8: FIX8::UTEST Namespace Reference
FIX8::UTEST Namespace Reference
Classes
class Heartbeat
Heartbeat (0), admin, 1 field, 0 groups.
class TestRequest
TestRequest (1), admin, 1 field, 0 groups.
class ResendRequest
ResendRequest (2), admin, 2 fields, 0 groups.
class Reject
Reject (3), admin, 7 fields, 0 groups.
class SequenceReset
SequenceReset (4), admin, 2 fields, 0 groups.
class Logout
Logout (5), admin, 3 fields, 0 groups.
class IndicationofInterest
IndicationofInterest (6), application, 38 fields, 2 groups.
class Advertisement
Advertisement (7), application, 34 fields, 0 groups.
class ExecutionReport
ExecutionReport (8), application, 94 fields, 1 group.
class OrderCancelReject
OrderCancelReject (9), application, 15 fields, 0 groups.
class Logon
Logon (A), admin, 7 fields, 1 group.
class News
News (B), application, 11 fields, 3 groups.
class Email
Email (C), application, 13 fields, 3 groups.
class NewOrderSingle
NewOrderSingle (D), application, 76 fields, 2 groups.
class NewOrderList
NewOrderList (E), application, 12 fields, 1 group.
class OrderCancelRequest
OrderCancelRequest (F), application, 37 fields, 0 groups.
class OrderCancelReplaceRequest
OrderCancelReplaceRequest (G), application, 70 fields, 2 groups.
class OrderStatusRequest
OrderStatusRequest (H), application, 25 fields, 0 groups.
class Allocation
Allocation (J), application, 46 fields, 3 groups.
class ListCancelRequest
ListCancelRequest (K), application, 5 fields, 0 groups.
class ListExecute
ListExecute (L), application, 7 fields, 0 groups.
class ListStatusRequest
ListStatusRequest (M), application, 4 fields, 0 groups.
class ListStatus
ListStatus (N), application, 11 fields, 1 group.
class AllocationACK
AllocationACK (P), application, 10 fields, 0 groups.
class DontKnowTrade
DontKnowTrade (Q), application, 30 fields, 0 groups.
class QuoteRequest
QuoteRequest (R), application, 2 fields, 1 group.
class Quote
Quote (S), application, 38 fields, 0 groups.
class SettlementInstructions
SettlementInstructions (T), application, 36 fields, 0 groups.
class MarketDataRequest
MarketDataRequest (V), application, 7 fields, 2 groups.
class MarketDataSnapshotFullRefresh
MarketDataSnapshotFullRefresh (W), application, 24 fields, 1 group.
class MarketDataIncrementalRefresh
MarketDataIncrementalRefresh (X), application, 2 fields, 1 group.
class MarketDataRequestReject
MarketDataRequestReject (Y), application, 5 fields, 0 groups.
class QuoteCancel
QuoteCancel (Z), application, 6 fields, 1 group.
class QuoteStatusRequest
QuoteStatusRequest (a), application, 22 fields, 0 groups.
class QuoteAcknowledgement
QuoteAcknowledgement (b), application, 8 fields, 1 group.
class SecurityDefinitionRequest
SecurityDefinitionRequest (c), application, 27 fields, 1 group.
class SecurityDefinition
SecurityDefinition (d), application, 29 fields, 1 group.
class SecurityStatusRequest
SecurityStatusRequest (e), application, 23 fields, 0 groups.
class SecurityStatus
SecurityStatus (f), application, 36 fields, 0 groups.
class TradingSessionStatusRequest
TradingSessionStatusRequest (g), application, 5 fields, 0 groups.
class TradingSessionStatus
TradingSessionStatus (h), application, 15 fields, 0 groups.
class header
header (header), application, 27 fields, 0 groups.
class MassQuote
MassQuote (i), application, 6 fields, 1 group.
class BusinessMessageReject
BusinessMessageReject (j), application, 7 fields, 0 groups.
class BidRequest
BidRequest (k), application, 29 fields, 2 groups.
class BidResponse
BidResponse (l), application, 3 fields, 1 group.
class ListStrikePrice
ListStrikePrice (m), application, 3 fields, 1 group.
class trailer
trailer (trailer), application, 3 fields, 0 groups.
class utest_Router
Typedefs
typedef MsgTable utest_BaseMsgEntry
typedef Field< f8String, 1 > Account
typedef Field< f8String, 2 > AdvId
typedef Field< f8String, 3 > AdvRefID
typedef Field< char, 4 > AdvSide
typedef Field< f8String, 5 > AdvTransType
typedef Field< price, 6 > AvgPx
typedef Field< int, 7 > BeginSeqNo
typedef Field< f8String, 8 > BeginString
typedef Field< int, 9 > BodyLength
typedef Field< f8String, 10 > CheckSum
typedef Field< f8String, 11 > ClOrdID
typedef Field< Amt, 12 > Commission
typedef Field< char, 13 > CommType
typedef Field< Qty, 14 > CumQty
typedef Field< currency, 15 > Currency
typedef Field< int, 16 > EndSeqNo
typedef Field< f8String, 17 > ExecID
typedef Field
< MultipleStringValue, 18 > ExecInst
typedef Field< f8String, 19 > ExecRefID
typedef Field< char, 20 > ExecTransType
typedef Field< char, 21 > HandlInst
typedef Field< f8String, 22 > IDSource
typedef Field< f8String, 23 > IOIid
typedef Field< char, 25 > IOIQltyInd
typedef Field< f8String, 26 > IOIRefID
typedef Field< f8String, 27 > IOIShares
typedef Field< char, 28 > IOITransType
typedef Field< char, 29 > LastCapacity
typedef Field< Exchange, 30 > LastMkt
typedef Field< price, 31 > LastPx
typedef Field< Qty, 32 > LastShares
typedef Field< int, 33 > LinesOfText
typedef Field< int, 34 > MsgSeqNum
typedef Field< f8String, 35 > MsgType
typedef Field< int, 36 > NewSeqNo
typedef Field< f8String, 37 > OrderID
typedef Field< Qty, 38 > OrderQty
typedef Field< char, 39 > OrdStatus
typedef Field< char, 40 > OrdType
typedef Field< f8String, 41 > OrigClOrdID
typedef Field< UTCTimestamp, 42 > OrigTime
typedef Field< Boolean, 43 > PossDupFlag
typedef Field< price, 44 > Price
typedef Field< int, 45 > RefSeqNum
typedef Field< f8String, 46 > RelatdSym
typedef Field< char, 47 > Rule80A
typedef Field< f8String, 48 > SecurityID
typedef Field< f8String, 49 > SenderCompID
typedef Field< f8String, 50 > SenderSubID
typedef Field< UTCTimestamp, 52 > SendingTime
typedef Field< Qty, 53 > Shares
typedef Field< char, 54 > Side
typedef Field< f8String, 55 > Symbol
typedef Field< f8String, 56 > TargetCompID
typedef Field< f8String, 57 > TargetSubID
typedef Field< f8String, 58 > Text
typedef Field< char, 59 > TimeInForce
typedef Field< UTCTimestamp, 60 > TransactTime
typedef Field< char, 61 > Urgency
typedef Field< UTCTimestamp, 62 > ValidUntilTime
typedef Field< char, 63 > SettlmntTyp
typedef Field< LocalMktDate, 64 > FutSettDate
typedef Field< f8String, 65 > SymbolSfx
typedef Field< f8String, 66 > ListID
typedef Field< int, 67 > ListSeqNo
typedef Field< int, 68 > TotNoOrders
typedef Field< f8String, 69 > ListExecInst
typedef Field< f8String, 70 > AllocID
typedef Field< char, 71 > AllocTransType
typedef Field< f8String, 72 > RefAllocID
typedef Field< int, 73 > NoOrders
typedef Field< int, 74 > AvgPrxPrecision
typedef Field< LocalMktDate, 75 > TradeDate
typedef Field< f8String, 76 > ExecBroker
typedef Field< char, 77 > OpenClose
typedef Field< int, 78 > NoAllocs
typedef Field< f8String, 79 > AllocAccount
typedef Field< Qty, 80 > AllocShares
typedef Field< char, 81 > ProcessCode
typedef Field< int, 82 > NoRpts
typedef Field< int, 83 > RptSeq
typedef Field< Qty, 84 > CxlQty
typedef Field< int, 87 > AllocStatus
typedef Field< int, 88 > AllocRejCode
typedef Field< data, 89 > Signature
typedef Field< Length, 90 > SecureDataLen
typedef Field< data, 91 > SecureData
typedef Field< f8String, 92 > BrokerOfCredit
typedef Field< Length, 93 > SignatureLength
typedef Field< char, 94 > EmailType
typedef Field< Length, 95 > RawDataLength
typedef Field< data, 96 > RawData
typedef Field< Boolean, 97 > PossResend
typedef Field< int, 98 > EncryptMethod
typedef Field< price, 99 > StopPx
typedef Field< Exchange, 100 > ExDestination
typedef Field< int, 102 > CxlRejReason
typedef Field< int, 103 > OrdRejReason
typedef Field< char, 104 > IOIQualifier
typedef Field< f8String, 105 > WaveNo
typedef Field< f8String, 106 > Issuer
typedef Field< f8String, 107 > SecurityDesc
typedef Field< int, 108 > HeartBtInt
typedef Field< f8String, 109 > ClientID
typedef Field< Qty, 110 > MinQty
typedef Field< Qty, 111 > MaxFloor
typedef Field< f8String, 112 > TestReqID
typedef Field< Boolean, 113 > ReportToExch
typedef Field< Boolean, 114 > LocateReqd
typedef Field< f8String, 115 > OnBehalfOfCompID
typedef Field< f8String, 116 > OnBehalfOfSubID
typedef Field< f8String, 117 > QuoteID
typedef Field< Amt, 118 > NetMoney
typedef Field< Amt, 119 > SettlCurrAmt
typedef Field< currency, 120 > SettlCurrency
typedef Field< Boolean, 121 > ForexReq
typedef Field< UTCTimestamp, 122 > OrigSendingTime
typedef Field< Boolean, 123 > GapFillFlag
typedef Field< int, 124 > NoExecs
typedef Field< UTCTimestamp, 126 > ExpireTime
typedef Field< char, 127 > DKReason
typedef Field< f8String, 128 > DeliverToCompID
typedef Field< f8String, 129 > DeliverToSubID
typedef Field< Boolean, 130 > IOINaturalFlag
typedef Field< f8String, 131 > QuoteReqID
typedef Field< price, 132 > BidPx
typedef Field< price, 133 > OfferPx
typedef Field< Qty, 134 > BidSize
typedef Field< Qty, 135 > OfferSize
typedef Field< int, 136 > NoMiscFees
typedef Field< Amt, 137 > MiscFeeAmt
typedef Field< currency, 138 > MiscFeeCurr
typedef Field< char, 139 > MiscFeeType
typedef Field< price, 140 > PrevClosePx
typedef Field< Boolean, 141 > ResetSeqNumFlag
typedef Field< f8String, 142 > SenderLocationID
typedef Field< f8String, 143 > TargetLocationID
typedef Field< f8String, 144 > OnBehalfOfLocationID
typedef Field< f8String, 145 > DeliverToLocationID
typedef Field< int, 146 > NoRelatedSym
typedef Field< f8String, 147 > Subject
typedef Field< f8String, 148 > Headline
typedef Field< f8String, 149 > URLLink
typedef Field< char, 150 > ExecType
typedef Field< Qty, 151 > LeavesQty
typedef Field< Qty, 152 > CashOrderQty
typedef Field< price, 153 > AllocAvgPx
typedef Field< Amt, 154 > AllocNetMoney
typedef Field< double, 155 > SettlCurrFxRate
typedef Field< char, 156 > SettlCurrFxRateCalc
typedef Field< int, 157 > NumDaysInterest
typedef Field< double, 158 > AccruedInterestRate
typedef Field< Amt, 159 > AccruedInterestAmt
typedef Field< char, 160 > SettlInstMode
typedef Field< f8String, 161 > AllocText
typedef Field< f8String, 162 > SettlInstID
typedef Field< char, 163 > SettlInstTransType
typedef Field< f8String, 164 > EmailThreadID
typedef Field< char, 165 > SettlInstSource
typedef Field< f8String, 166 > SettlLocation
typedef Field< f8String, 167 > SecurityType
typedef Field< UTCTimestamp, 168 > EffectiveTime
typedef Field< int, 169 > StandInstDbType
typedef Field< f8String, 170 > StandInstDbName
typedef Field< f8String, 171 > StandInstDbID
typedef Field< int, 172 > SettlDeliveryType
typedef Field< f8String, 173 > SettlDepositoryCode
typedef Field< f8String, 174 > SettlBrkrCode
typedef Field< f8String, 175 > SettlInstCode
typedef Field< f8String, 176 > SecuritySettlAgentName
typedef Field< f8String, 177 > SecuritySettlAgentCode
typedef Field< f8String, 178 > SecuritySettlAgentAcctNum
typedef Field< f8String, 179 > SecuritySettlAgentAcctName
typedef Field< f8String, 180 > SecuritySettlAgentContactName
typedef Field< f8String, 181 > SecuritySettlAgentContactPhone
typedef Field< f8String, 182 > CashSettlAgentName
typedef Field< f8String, 183 > CashSettlAgentCode
typedef Field< f8String, 184 > CashSettlAgentAcctNum
typedef Field< f8String, 185 > CashSettlAgentAcctName
typedef Field< f8String, 186 > CashSettlAgentContactName
typedef Field< f8String, 187 > CashSettlAgentContactPhone
typedef Field< price, 188 > BidSpotRate
typedef Field< PriceOffset, 189 > BidForwardPoints
typedef Field< price, 190 > OfferSpotRate
typedef Field< PriceOffset, 191 > OfferForwardPoints
typedef Field< Qty, 192 > OrderQty2
typedef Field< LocalMktDate, 193 > FutSettDate2
typedef Field< price, 194 > LastSpotRate
typedef Field< PriceOffset, 195 > LastForwardPoints
typedef Field< f8String, 196 > AllocLinkID
typedef Field< int, 197 > AllocLinkType
typedef Field< f8String, 198 > SecondaryOrderID
typedef Field< int, 199 > NoIOIQualifiers
typedef Field< MonthYear, 200 > MaturityMonthYear
typedef Field< int, 201 > PutOrCall
typedef Field< price, 202 > StrikePrice
typedef Field< int, 203 > CoveredOrUncovered
typedef Field< int, 204 > CustomerOrFirm
typedef Field< DayOfMonth, 205 > MaturityDay
typedef Field< char, 206 > OptAttribute
typedef Field< Exchange, 207 > SecurityExchange
typedef Field< Boolean, 208 > NotifyBrokerOfCredit
typedef Field< int, 209 > AllocHandlInst
typedef Field< Qty, 210 > MaxShow
typedef Field< PriceOffset, 211 > PegDifference
typedef Field< Length, 212 > XmlDataLen
typedef Field< data, 213 > XmlData
typedef Field< f8String, 214 > SettlInstRefID
typedef Field< int, 215 > NoRoutingIDs
typedef Field< int, 216 > RoutingType
typedef Field< f8String, 217 > RoutingID
typedef Field< PriceOffset, 218 > SpreadToBenchmark
typedef Field< char, 219 > Benchmark
typedef Field< double, 223 > CouponRate
typedef Field< double, 231 > ContractMultiplier
typedef Field< f8String, 262 > MDReqID
typedef Field< char, 263 > SubscriptionRequestType
typedef Field< int, 264 > MarketDepth
typedef Field< int, 265 > MDUpdateType
typedef Field< Boolean, 266 > AggregatedBook
typedef Field< int, 267 > NoMDEntryTypes
typedef Field< int, 268 > NoMDEntries
typedef Field< char, 269 > MDEntryType
typedef Field< price, 270 > MDEntryPx
typedef Field< Qty, 271 > MDEntrySize
typedef Field< UTCDateOnly, 272 > MDEntryDate
typedef Field< UTCTimeOnly, 273 > MDEntryTime
typedef Field< char, 274 > TickDirection
typedef Field< Exchange, 275 > MDMkt
typedef Field
< MultipleStringValue, 276 > QuoteCondition
typedef Field
< MultipleStringValue, 277 > TradeCondition
typedef Field< f8String, 278 > MDEntryID
typedef Field< char, 279 > MDUpdateAction
typedef Field< f8String, 280 > MDEntryRefID
typedef Field< char, 281 > MDReqRejReason
typedef Field< f8String, 282 > MDEntryOriginator
typedef Field< f8String, 283 > LocationID
typedef Field< f8String, 284 > DeskID
typedef Field< char, 285 > DeleteReason
typedef Field< char, 286 > OpenCloseSettleFlag
typedef Field< int, 287 > SellerDays
typedef Field< f8String, 288 > MDEntryBuyer
typedef Field< f8String, 289 > MDEntrySeller
typedef Field< int, 290 > MDEntryPositionNo
typedef Field< char, 291 > FinancialStatus
typedef Field< char, 292 > CorporateAction
typedef Field< Qty, 293 > DefBidSize
typedef Field< Qty, 294 > DefOfferSize
typedef Field< int, 295 > NoQuoteEntries
typedef Field< int, 296 > NoQuoteSets
typedef Field< int, 297 > QuoteAckStatus
typedef Field< int, 298 > QuoteCancelType
typedef Field< f8String, 299 > QuoteEntryID
typedef Field< int, 300 > QuoteRejectReason
typedef Field< int, 301 > QuoteResponseLevel
typedef Field< f8String, 302 > QuoteSetID
typedef Field< int, 303 > QuoteRequestType
typedef Field< int, 304 > TotQuoteEntries
typedef Field< f8String, 305 > UnderlyingIDSource
typedef Field< f8String, 306 > UnderlyingIssuer
typedef Field< f8String, 307 > UnderlyingSecurityDesc
typedef Field< Exchange, 308 > UnderlyingSecurityExchange
typedef Field< f8String, 309 > UnderlyingSecurityID
typedef Field< f8String, 310 > UnderlyingSecurityType
typedef Field< f8String, 311 > UnderlyingSymbol
typedef Field< f8String, 312 > UnderlyingSymbolSfx
typedef Field< MonthYear, 313 > UnderlyingMaturityMonthYear
typedef Field< DayOfMonth, 314 > UnderlyingMaturityDay
typedef Field< int, 315 > UnderlyingPutOrCall
typedef Field< price, 316 > UnderlyingStrikePrice
typedef Field< char, 317 > UnderlyingOptAttribute
typedef Field< currency, 318 > UnderlyingCurrency
typedef Field< Qty, 319 > RatioQty
typedef Field< f8String, 320 > SecurityReqID
typedef Field< int, 321 > SecurityRequestType
typedef Field< f8String, 322 > SecurityResponseID
typedef Field< int, 323 > SecurityResponseType
typedef Field< f8String, 324 > SecurityStatusReqID
typedef Field< Boolean, 325 > UnsolicitedIndicator
typedef Field< int, 326 > SecurityTradingStatus
typedef Field< char, 327 > HaltReasonChar
typedef Field< Boolean, 328 > InViewOfCommon
typedef Field< Boolean, 329 > DueToRelated
typedef Field< Qty, 330 > BuyVolume
typedef Field< Qty, 331 > SellVolume
typedef Field< price, 332 > HighPx
typedef Field< price, 333 > LowPx
typedef Field< int, 334 > Adjustment
typedef Field< f8String, 335 > TradSesReqID
typedef Field< f8String, 336 > TradingSessionID
typedef Field< f8String, 337 > ContraTrader
typedef Field< int, 338 > TradSesMethod
typedef Field< int, 339 > TradSesMode
typedef Field< int, 340 > TradSesStatus
typedef Field< UTCTimestamp, 341 > TradSesStartTime
typedef Field< UTCTimestamp, 342 > TradSesOpenTime
typedef Field< UTCTimestamp, 343 > TradSesPreCloseTime
typedef Field< UTCTimestamp, 344 > TradSesCloseTime
typedef Field< UTCTimestamp, 345 > TradSesEndTime
typedef Field< int, 346 > NumberOfOrders
typedef Field< f8String, 347 > MessageEncoding
typedef Field< Length, 348 > EncodedIssuerLen
typedef Field< data, 349 > EncodedIssuer
typedef Field< Length, 350 > EncodedSecurityDescLen
typedef Field< data, 351 > EncodedSecurityDesc
typedef Field< Length, 352 > EncodedListExecInstLen
typedef Field< data, 353 > EncodedListExecInst
typedef Field< Length, 354 > EncodedTextLen
typedef Field< data, 355 > EncodedText
typedef Field< Length, 356 > EncodedSubjectLen
typedef Field< data, 357 > EncodedSubject
typedef Field< Length, 358 > EncodedHeadlineLen
typedef Field< data, 359 > EncodedHeadline
typedef Field< Length, 360 > EncodedAllocTextLen
typedef Field< data, 361 > EncodedAllocText
typedef Field< Length, 362 > EncodedUnderlyingIssuerLen
typedef Field< data, 363 > EncodedUnderlyingIssuer
typedef Field< Length, 364 > EncodedUnderlyingSecurityDescLen
typedef Field< data, 365 > EncodedUnderlyingSecurityDesc
typedef Field< price, 366 > AllocPrice
typedef Field< UTCTimestamp, 367 > QuoteSetValidUntilTime
typedef Field< int, 368 > QuoteEntryRejectReason
typedef Field< int, 369 > LastMsgSeqNumProcessed
typedef Field< UTCTimestamp, 370 > OnBehalfOfSendingTime
typedef Field< int, 371 > RefTagID
typedef Field< f8String, 372 > RefMsgType
typedef Field< int, 373 > SessionRejectReason
typedef Field< char, 374 > BidRequestTransType
typedef Field< f8String, 375 > ContraBroker
typedef Field< f8String, 376 > ComplianceID
typedef Field< Boolean, 377 > SolicitedFlag
typedef Field< int, 378 > ExecRestatementReason
typedef Field< f8String, 379 > BusinessRejectRefID
typedef Field< int, 380 > BusinessRejectReason
typedef Field< Amt, 381 > GrossTradeAmt
typedef Field< int, 382 > NoContraBrokers
typedef Field< int, 383 > MaxMessageSize
typedef Field< int, 384 > NoMsgTypes
typedef Field< char, 385 > MsgDirection
typedef Field< int, 386 > NoTradingSessions
typedef Field< Qty, 387 > TotalVolumeTraded
typedef Field< char, 388 > DiscretionInst
typedef Field< PriceOffset, 389 > DiscretionOffset
typedef Field< f8String, 390 > BidID
typedef Field< f8String, 391 > ClientBidID
typedef Field< f8String, 392 > ListName
typedef Field< int, 393 > TotalNumSecurities
typedef Field< int, 394 > BidType
typedef Field< int, 395 > NumTickets
typedef Field< Amt, 396 > SideValue1
typedef Field< Amt, 397 > SideValue2
typedef Field< int, 398 > NoBidDescriptors
typedef Field< int, 399 > BidDescriptorType
typedef Field< f8String, 400 > BidDescriptor
typedef Field< int, 401 > SideValueInd
typedef Field< double, 402 > LiquidityPctLow
typedef Field< double, 403 > LiquidityPctHigh
typedef Field< Amt, 404 > LiquidityValue
typedef Field< double, 405 > EFPTrackingError
typedef Field< Amt, 406 > FairValue
typedef Field< double, 407 > OutsideIndexPct
typedef Field< Amt, 408 > ValueOfFutures
typedef Field< int, 409 > LiquidityIndType
typedef Field< double, 410 > WtAverageLiquidity
typedef Field< Boolean, 411 > ExchangeForPhysical
typedef Field< Amt, 412 > OutMainCntryUIndex
typedef Field< double, 413 > CrossPercent
typedef Field< int, 414 > ProgRptReqs
typedef Field< int, 415 > ProgPeriodInterval
typedef Field< int, 416 > IncTaxInd
typedef Field< int, 417 > NumBidders
typedef Field< char, 418 > TradeType
typedef Field< char, 419 > BasisPxType
typedef Field< int, 420 > NoBidComponents
typedef Field< f8String, 421 > Country
typedef Field< int, 422 > TotNoStrikes
typedef Field< int, 423 > PriceType
typedef Field< Qty, 424 > DayOrderQty
typedef Field< Qty, 425 > DayCumQty
typedef Field< price, 426 > DayAvgPx
typedef Field< int, 427 > GTBookingInst
typedef Field< int, 428 > NoStrikes
typedef Field< int, 429 > ListStatusType
typedef Field< int, 430 > NetGrossInd
typedef Field< int, 431 > ListOrderStatus
typedef Field< LocalMktDate, 432 > ExpireDate
typedef Field< char, 433 > ListExecInstType
typedef Field< char, 434 > CxlRejResponseTo
typedef Field< double, 435 > UnderlyingCouponRate
typedef Field< double, 436 > UnderlyingContractMultiplier
typedef Field< Qty, 437 > ContraTradeQty
typedef Field< UTCTimestamp, 438 > ContraTradeTime
typedef Field< f8String, 439 > ClearingFirm
typedef Field< f8String, 440 > ClearingAccount
typedef Field< int, 441 > LiquidityNumSecurities
typedef Field< char, 442 > MultiLegReportingType
typedef Field< UTCTimestamp, 443 > StrikeTime
typedef Field< f8String, 444 > ListStatusText
typedef Field< Length, 445 > EncodedListStatusTextLen
typedef Field< data, 446 > EncodedListStatusText
typedef Field< UTCDateOnly, 449 > TotalVolumeTradedDate
typedef Field< UTCTimeOnly, 450 > TotalVolumeTradedTime
typedef Field< LocalMktDate, 743 > DeliveryDate
typedef Field< f8String, 9991 > SampleUserField2
typedef Field< f8String, 9999 > SampleUserField
typedef FieldTable utest_BaseEntry
Functions
const F8MetaCntx & ctx ()
Compiler generated metadata object, accessed through this function.
const char AdvSide_BUY ('B')
const char AdvSide_SELL ('S')
const char AdvSide_TRADE ('T')
const char AdvSide_CROSS ('X')
const size_t AdvSide_realm_els (4)
const f8String AdvTransType_CANCEL ("C")
const f8String AdvTransType_NEW ("N")
const f8String AdvTransType_REPLACE ("R")
const size_t AdvTransType_realm_els (3)
const char CommType_PER_SHARE ('1')
const char CommType_PERCENTAGE ('2')
const char CommType_ABSOLUTE ('3')
const size_t CommType_realm_els (3)
const f8String ExecInst_STAY_ON_OFFERSIDE ("0")
const f8String ExecInst_NOT_HELD ("1")
const f8String ExecInst_WORK ("2")
const f8String ExecInst_GO_ALONG ("3")
const f8String ExecInst_OVER_THE_DAY ("4")
const f8String ExecInst_HELD ("5")
const f8String ExecInst_PARTICIPATE_DONT_INITIATE ("6")
const f8String ExecInst_STRICT_SCALE ("7")
const f8String ExecInst_TRY_TO_SCALE ("8")
const f8String ExecInst_STAY_ON_BIDSIDE ("9")
const f8String ExecInst_NO_CROSS ("A")
const f8String ExecInst_OK_TO_CROSS ("B")
const f8String ExecInst_CALL_FIRST ("C")
const f8String ExecInst_PERCENT_OF_VOLUME ("D")
const f8String ExecInst_DO_NOT_INCREASE ("E")
const f8String ExecInst_DO_NOT_REDUCE ("F")
const f8String ExecInst_ALL_OR_NONE ("G")
const f8String ExecInst_INSTITUTIONS_ONLY ("I")
const f8String ExecInst_LAST_PEG ("L")
const f8String ExecInst_MID_PRICE_PEG ("M")
const f8String ExecInst_NON_NEGOTIABLE ("N")
const f8String ExecInst_OPENING_PEG ("O")
const f8String ExecInst_MARKET_PEG ("P")
const f8String ExecInst_PRIMARY_PEG ("R")
const f8String ExecInst_SUSPEND ("S")
const f8String ExecInst_FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER ("T")
const f8String ExecInst_CUSTOMER_DISPLAY_INSTRUCTION ("U")
const f8String ExecInst_NETTING ("V")
const f8String ExecInst_PEG_TO_VWAP ("W")
const size_t ExecInst_realm_els (29)
const char ExecTransType_NEW ('0')
const char ExecTransType_CANCEL ('1')
const char ExecTransType_CORRECT ('2')
const char ExecTransType_STATUS ('3')
const size_t ExecTransType_realm_els (4)
const char HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION ('1')
const char HandlInst_AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK ('2')
const char HandlInst_MANUAL_ORDER_BEST_EXECUTION ('3')
const size_t HandlInst_realm_els (3)
const f8String IDSource_CUSIP ("1")
const f8String IDSource_SEDOL ("2")
const f8String IDSource_QUIK ("3")
const f8String IDSource_ISIN_NUMBER ("4")
const f8String IDSource_RIC_CODE ("5")
const f8String IDSource_ISO_CURRENCY_CODE ("6")
const f8String IDSource_ISO_COUNTRY_CODE ("7")
const f8String IDSource_EXCHANGE_SYMBOL ("8")
const f8String IDSource_CONSOLIDATED_TAPE_ASSOCIATION ("9")
const size_t IDSource_realm_els (9)
const char IOIQltyInd_HIGH ('H')
const char IOIQltyInd_LOW ('L')
const char IOIQltyInd_MEDIUM ('M')
const size_t IOIQltyInd_realm_els (3)
const f8String IOIShares_LARGE ("L")
const f8String IOIShares_MEDIUM ("M")
const f8String IOIShares_SMALL ("S")
const size_t IOIShares_realm_els (3)
const char IOITransType_CANCEL ('C')
const char IOITransType_NEW ('N')
const char IOITransType_REPLACE ('R')
const size_t IOITransType_realm_els (3)
const char LastCapacity_AGENT ('1')
const char LastCapacity_CROSS_AS_AGENT ('2')
const char LastCapacity_CROSS_AS_PRINCIPAL ('3')
const char LastCapacity_PRINCIPAL ('4')
const size_t LastCapacity_realm_els (4)
const f8String MsgType_HEARTBEAT ("0")
const f8String MsgType_TEST_REQUEST ("1")
const f8String MsgType_RESEND_REQUEST ("2")
const f8String MsgType_REJECT ("3")
const f8String MsgType_SEQUENCE_RESET ("4")
const f8String MsgType_LOGOUT ("5")
const f8String MsgType_INDICATION_OF_INTEREST ("6")
const f8String MsgType_ADVERTISEMENT ("7")
const f8String MsgType_EXECUTION_REPORT ("8")
const f8String MsgType_ORDER_CANCEL_REJECT ("9")
const f8String MsgType_LOGON ("A")
const f8String MsgType_NEWS ("B")
const f8String MsgType_EMAIL ("C")
const f8String MsgType_ORDER_SINGLE ("D")
const f8String MsgType_ORDER_LIST ("E")
const f8String MsgType_ORDER_CANCEL_REQUEST ("F")
const f8String MsgType_ORDER_CANCEL_REPLACE_REQUEST ("G")
const f8String MsgType_ORDER_STATUS_REQUEST ("H")
const f8String MsgType_ALLOCATION ("J")
const f8String MsgType_LIST_CANCEL_REQUEST ("K")
const f8String MsgType_LIST_EXECUTE ("L")
const f8String MsgType_LIST_STATUS_REQUEST ("M")
const f8String MsgType_LIST_STATUS ("N")
const f8String MsgType_ALLOCATION_ACK ("P")
const f8String MsgType_DONT_KNOW_TRADE ("Q")
const f8String MsgType_QUOTE_REQUEST ("R")
const f8String MsgType_QUOTE ("S")
const f8String MsgType_SETTLEMENT_INSTRUCTIONS ("T")
const f8String MsgType_MARKET_DATA_REQUEST ("V")
const f8String MsgType_MARKET_DATA_SNAPSHOT_FULL_REFRESH ("W")
const f8String MsgType_MARKET_DATA_INCREMENTAL_REFRESH ("X")
const f8String MsgType_MARKET_DATA_REQUEST_REJECT ("Y")
const f8String MsgType_QUOTE_CANCEL ("Z")
const f8String MsgType_QUOTE_STATUS_REQUEST ("a")
const f8String MsgType_QUOTE_ACKNOWLEDGEMENT ("b")
const f8String MsgType_SECURITY_DEFINITION_REQUEST ("c")
const f8String MsgType_SECURITY_DEFINITION ("d")
const f8String MsgType_SECURITY_STATUS_REQUEST ("e")
const f8String MsgType_SECURITY_STATUS ("f")
const f8String MsgType_TRADING_SESSION_STATUS_REQUEST ("g")
const f8String MsgType_TRADING_SESSION_STATUS ("h")
const f8String MsgType_MASS_QUOTE ("i")
const f8String MsgType_BUSINESS_MESSAGE_REJECT ("j")
const f8String MsgType_BID_REQUEST ("k")
const f8String MsgType_BID_RESPONSE ("l")
const f8String MsgType_LIST_STRIKE_PRICE ("m")
const size_t MsgType_realm_els (46)
const char OrdStatus_NEW ('0')
const char OrdStatus_PARTIALLY_FILLED ('1')
const char OrdStatus_FILLED ('2')
const char OrdStatus_DONE_FOR_DAY ('3')
const char OrdStatus_CANCELED ('4')
const char OrdStatus_REPLACED ('5')
const char OrdStatus_PENDING_CANCEL ('6')
const char OrdStatus_STOPPED ('7')
const char OrdStatus_REJECTED ('8')
const char OrdStatus_SUSPENDED ('9')
const char OrdStatus_PENDING_NEW ('A')
const char OrdStatus_CALCULATED ('B')
const char OrdStatus_EXPIRED ('C')
const char OrdStatus_ACCEPTED_FOR_BIDDING ('D')
const char OrdStatus_PENDING_REPLACE ('E')
const size_t OrdStatus_realm_els (15)
const char OrdType_MARKET ('1')
const char OrdType_LIMIT ('2')
const char OrdType_STOP ('3')
const char OrdType_STOP_LIMIT ('4')
const char OrdType_MARKET_ON_CLOSE ('5')
const char OrdType_WITH_OR_WITHOUT ('6')
const char OrdType_LIMIT_OR_BETTER ('7')
const char OrdType_LIMIT_WITH_OR_WITHOUT ('8')
const char OrdType_ON_BASIS ('9')
const char OrdType_ON_CLOSE ('A')
const char OrdType_LIMIT_ON_CLOSE ('B')
const char OrdType_FOREX_C ('C')
const char OrdType_PREVIOUSLY_QUOTED ('D')
const char OrdType_PREVIOUSLY_INDICATED ('E')
const char OrdType_FOREX_F ('F')
const char OrdType_FOREX_G ('G')
const char OrdType_FOREX_H ('H')
const char OrdType_FUNARI ('I')
const char OrdType_PEGGED ('P')
const size_t OrdType_realm_els (19)
const char PossDupFlag_NO ('N')
const char PossDupFlag_YES ('Y')
const size_t PossDupFlag_realm_els (2)
const char Rule80A_AGENCY_SINGLE_ORDER ('A')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_B ('B')
const char Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG ('C')
const char Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG ('D')
const char Rule80A_REGISTERED_EQUITY_MARKET_MAKER_TRADES ('E')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_F ('F')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_H ('H')
const char Rule80A_INDIVIDUAL_INVESTOR_SINGLE_ORDER ('I')
const char Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER ('J')
const char Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER ('K')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE ('L')
const char Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER ('M')
const char Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER ('N')
const char Rule80A_COMPETING_DEALER_TRADES_O ('O')
const char Rule80A_PRINCIPAL ('P')
const char Rule80A_COMPETING_DEALER_TRADES_R ('R')
const char Rule80A_SPECIALIST_TRADES ('S')
const char Rule80A_COMPETING_DEALER_TRADES_T ('T')
const char Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY ('U')
const char Rule80A_ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER ('W')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE ('X')
const char Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY ('Y')
const char Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER ('Z')
const size_t Rule80A_realm_els (23)
const char Side_BUY ('1')
const char Side_SELL ('2')
const char Side_BUY_MINUS ('3')
const char Side_SELL_PLUS ('4')
const char Side_SELL_SHORT ('5')
const char Side_SELL_SHORT_EXEMPT ('6')
const char Side_UNDISCLOSED ('7')
const char Side_CROSS ('8')
const char Side_CROSS_SHORT ('9')
const size_t Side_realm_els (9)
const char TimeInForce_DAY ('0')
const char TimeInForce_GOOD_TILL_CANCEL ('1')
const char TimeInForce_AT_THE_OPENING ('2')
const char TimeInForce_IMMEDIATE_OR_CANCEL ('3')
const char TimeInForce_FILL_OR_KILL ('4')
const char TimeInForce_GOOD_TILL_CROSSING ('5')
const char TimeInForce_GOOD_TILL_DATE ('6')
const size_t TimeInForce_realm_els (7)
const char Urgency_NORMAL ('0')
const char Urgency_FLASH ('1')
const char Urgency_BACKGROUND ('2')
const size_t Urgency_realm_els (3)
const char SettlmntTyp_REGULAR ('0')
const char SettlmntTyp_CASH ('1')
const char SettlmntTyp_NEXT_DAY ('2')
const char SettlmntTyp_T_PLUS_2 ('3')
const char SettlmntTyp_T_PLUS_3 ('4')
const char SettlmntTyp_T_PLUS_4 ('5')
const char SettlmntTyp_FUTURE ('6')
const char SettlmntTyp_WHEN_ISSUED ('7')
const char SettlmntTyp_SELLERS_OPTION ('8')
const char SettlmntTyp_T_PLUS_5 ('9')
const size_t SettlmntTyp_realm_els (10)
const char AllocTransType_NEW ('0')
const char AllocTransType_REPLACE ('1')
const char AllocTransType_CANCEL ('2')
const char AllocTransType_PRELIMINARY ('3')
const char AllocTransType_CALCULATED ('4')
const char AllocTransType_CALCULATED_WITHOUT_PRELIMINARY ('5')
const size_t AllocTransType_realm_els (6)
const char OpenClose_CLOSE ('C')
const char OpenClose_OPEN ('O')
const size_t OpenClose_realm_els (2)
const char ProcessCode_REGULAR ('0')
const char ProcessCode_SOFT_DOLLAR ('1')
const char ProcessCode_STEP_IN ('2')
const char ProcessCode_STEP_OUT ('3')
const char ProcessCode_SOFT_DOLLAR_STEP_IN ('4')
const char ProcessCode_SOFT_DOLLAR_STEP_OUT ('5')
const char ProcessCode_PLAN_SPONSOR ('6')
const size_t ProcessCode_realm_els (7)
const int AllocStatus_ACCEPTED (0)
const int AllocStatus_REJECTED (1)
const int AllocStatus_PARTIAL_ACCEPT (2)
const int AllocStatus_RECEIVED (3)
const size_t AllocStatus_realm_els (4)
const int AllocRejCode_UNKNOWN_ACCOUNT (0)
const int AllocRejCode_INCORRECT_QUANTITY (1)
const int AllocRejCode_INCORRECT_AVERAGE_PRICE (2)
const int AllocRejCode_UNKNOWN_EXECUTING_BROKER_MNEMONIC (3)
const int AllocRejCode_COMMISSION_DIFFERENCE (4)
const int AllocRejCode_UNKNOWN_ORDERID (5)
const int AllocRejCode_UNKNOWN_LISTID (6)
const int AllocRejCode_OTHER (7)
const size_t AllocRejCode_realm_els (8)
const char EmailType_NEW ('0')
const char EmailType_REPLY ('1')
const char EmailType_ADMIN_REPLY ('2')
const size_t EmailType_realm_els (3)
const char PossResend_NO ('N')
const char PossResend_YES ('Y')
const size_t PossResend_realm_els (2)
const int EncryptMethod_NONE (0)
const int EncryptMethod_PKCS (1)
const int EncryptMethod_DES (2)
const int EncryptMethod_PKCS_DES (3)
const int EncryptMethod_PGP_DES (4)
const int EncryptMethod_PGP_DES_MD5 (5)
const int EncryptMethod_PEM_DES_MD5 (6)
const size_t EncryptMethod_realm_els (7)
const int CxlRejReason_TOO_LATE_TO_CANCEL (0)
const int CxlRejReason_UNKNOWN_ORDER (1)
const int CxlRejReason_BROKER_OPTION (2)
const int CxlRejReason_ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS (3)
const size_t CxlRejReason_realm_els (4)
const int OrdRejReason_BROKER_OPTION (0)
const int OrdRejReason_UNKNOWN_SYMBOL (1)
const int OrdRejReason_EXCHANGE_CLOSED (2)
const int OrdRejReason_ORDER_EXCEEDS_LIMIT (3)
const int OrdRejReason_TOO_LATE_TO_ENTER (4)
const int OrdRejReason_UNKNOWN_ORDER (5)
const int OrdRejReason_DUPLICATE_ORDER (6)
const int OrdRejReason_DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER (7)
const int OrdRejReason_STALE_ORDER (8)
const size_t OrdRejReason_realm_els (9)
const char IOIQualifier_ALL_OR_NONE ('A')
const char IOIQualifier_AT_THE_CLOSE ('C')
const char IOIQualifier_IN_TOUCH_WITH ('I')
const char IOIQualifier_LIMIT ('L')
const char IOIQualifier_MORE_BEHIND ('M')
const char IOIQualifier_AT_THE_OPEN ('O')
const char IOIQualifier_TAKING_A_POSITION ('P')
const char IOIQualifier_AT_THE_MARKET ('Q')
const char IOIQualifier_READY_TO_TRADE ('R')
const char IOIQualifier_PORTFOLIO_SHOW_N ('S')
const char IOIQualifier_THROUGH_THE_DAY ('T')
const char IOIQualifier_VERSUS ('V')
const char IOIQualifier_INDICATION ('W')
const char IOIQualifier_CROSSING_OPPORTUNITY ('X')
const char IOIQualifier_AT_THE_MIDPOINT ('Y')
const char IOIQualifier_PRE_OPEN ('Z')
const size_t IOIQualifier_realm_els (16)
const char ReportToExch_NO ('N')
const char ReportToExch_YES ('Y')
const size_t ReportToExch_realm_els (2)
const char LocateReqd_NO ('N')
const char LocateReqd_YES ('Y')
const size_t LocateReqd_realm_els (2)
const char ForexReq_NO ('N')
const char ForexReq_YES ('Y')
const size_t ForexReq_realm_els (2)
const char GapFillFlag_NO ('N')
const char GapFillFlag_YES ('Y')
const size_t GapFillFlag_realm_els (2)
const char DKReason_UNKNOWN_SYMBOL ('A')
const char DKReason_WRONG_SIDE ('B')
const char DKReason_QUANTITY_EXCEEDS_ORDER ('C')
const char DKReason_NO_MATCHING_ORDER ('D')
const char DKReason_PRICE_EXCEEDS_LIMIT ('E')
const char DKReason_OTHER ('Z')
const size_t DKReason_realm_els (6)
const char IOINaturalFlag_NO ('N')
const char IOINaturalFlag_YES ('Y')
const size_t IOINaturalFlag_realm_els (2)
const char MiscFeeType_REGULATORY ('1')
const char MiscFeeType_TAX ('2')
const char MiscFeeType_LOCAL_COMMISSION ('3')
const char MiscFeeType_EXCHANGE_FEES ('4')
const char MiscFeeType_STAMP ('5')
const char MiscFeeType_LEVY ('6')
const char MiscFeeType_OTHER ('7')
const char MiscFeeType_MARKUP ('8')
const char MiscFeeType_CONSUMPTION_TAX ('9')
const size_t MiscFeeType_realm_els (9)
const char ResetSeqNumFlag_NO ('N')
const char ResetSeqNumFlag_YES ('Y')
const size_t ResetSeqNumFlag_realm_els (2)
const char ExecType_NEW ('0')
const char ExecType_PARTIAL_FILL ('1')
const char ExecType_FILL ('2')
const char ExecType_DONE_FOR_DAY ('3')
const char ExecType_CANCELED ('4')
const char ExecType_REPLACE ('5')
const char ExecType_PENDING_CANCEL ('6')
const char ExecType_STOPPED ('7')
const char ExecType_REJECTED ('8')
const char ExecType_SUSPENDED ('9')
const char ExecType_PENDING_NEW ('A')
const char ExecType_CALCULATED ('B')
const char ExecType_EXPIRED ('C')
const char ExecType_RESTATED ('D')
const char ExecType_PENDING_REPLACE ('E')
const size_t ExecType_realm_els (15)
const char SettlCurrFxRateCalc_DIVIDE ('D')
const char SettlCurrFxRateCalc_MULTIPLY ('M')
const size_t SettlCurrFxRateCalc_realm_els (2)
const char SettlInstMode_DEFAULT ('0')
const char SettlInstMode_STANDING_INSTRUCTIONS_PROVIDED ('1')
const char SettlInstMode_SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING ('2')
const char SettlInstMode_SPECIFIC_ALLOCATION_ACCOUNT_STANDING ('3')
const size_t SettlInstMode_realm_els (4)
const char SettlInstTransType_CANCEL ('C')
const char SettlInstTransType_NEW ('N')
const char SettlInstTransType_REPLACE ('R')
const size_t SettlInstTransType_realm_els (3)
const char SettlInstSource_BROKERS_INSTRUCTIONS ('1')
const char SettlInstSource_INSTITUTIONS_INSTRUCTIONS ('2')
const size_t SettlInstSource_realm_els (2)
const f8String SettlLocation_CEDEL ("CED")
const f8String SettlLocation_DEPOSITORY_TRUST_COMPANY ("DTC")
const f8String SettlLocation_EUROCLEAR ("EUR")
const f8String SettlLocation_FEDERAL_BOOK_ENTRY ("FED")
const f8String SettlLocation_LOCAL_MARKET_SETTLE_LOCATION ("ISO Country Code")
const f8String SettlLocation_PHYSICAL ("PNY")
const f8String SettlLocation_PARTICIPANT_TRUST_COMPANY ("PTC")
const size_t SettlLocation_realm_els (7)
const f8String SecurityType_WILDCARD_ENTRY ("?")
const f8String SecurityType_BANKERS_ACCEPTANCE ("BA")
const f8String SecurityType_CONVERTIBLE_BOND ("CB")
const f8String SecurityType_CERTIFICATE_OF_DEPOSIT ("CD")
const f8String SecurityType_COLLATERALIZE_MORTGAGE_OBLIGATION ("CMO")
const f8String SecurityType_CORPORATE_BOND ("CORP")
const f8String SecurityType_COMMERCIAL_PAPER ("CP")
const f8String SecurityType_CORPORATE_PRIVATE_PLACEMENT ("CPP")
const f8String SecurityType_COMMON_STOCK ("CS")
const f8String SecurityType_FEDERAL_HOUSING_AUTHORITY ("FHA")
const f8String SecurityType_FEDERAL_HOME_LOAN ("FHL")
const f8String SecurityType_FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION ("FN")
const f8String SecurityType_FOREIGN_EXCHANGE_CONTRACT ("FOR")
const f8String SecurityType_FUTURE ("FUT")
const f8String SecurityType_GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION ("GN")
const f8String SecurityType_TREASURIES_PLUS_AGENCY_DEBENTURE ("GOVT")
const f8String SecurityType_MORTGAGE_IOETTE ("IET")
const f8String SecurityType_MUTUAL_FUND ("MF")
const f8String SecurityType_MORTGAGE_INTEREST_ONLY ("MIO")
const f8String SecurityType_MORTGAGE_PRINCIPAL_ONLY ("MPO")
const f8String SecurityType_MORTGAGE_PRIVATE_PLACEMENT ("MPP")
const f8String SecurityType_MISCELLANEOUS_PASS_THRU ("MPT")
const f8String SecurityType_MUNICIPAL_BOND ("MUNI")
const f8String SecurityType_NO_ISITC_SECURITY_TYPE ("NONE")
const f8String SecurityType_OPTION ("OPT")
const f8String SecurityType_PREFERRED_STOCK ("PS")
const f8String SecurityType_REPURCHASE_AGREEMENT ("RP")
const f8String SecurityType_REVERSE_REPURCHASE_AGREEMENT ("RVRP")
const f8String SecurityType_STUDENT_LOAN_MARKETING_ASSOCIATION ("SL")
const f8String SecurityType_TIME_DEPOSIT ("TD")
const f8String SecurityType_US_TREASURY_BILL ("USTB")
const f8String SecurityType_WARRANT ("WAR")
const f8String SecurityType_CATS_TIGERS_LIONS ("ZOO")
const size_t SecurityType_realm_els (33)
const int StandInstDbType_OTHER (0)
const int StandInstDbType_DTC_SID (1)
const int StandInstDbType_THOMSON_ALERT (2)
const int StandInstDbType_A_GLOBAL_CUSTODIAN (3)
const size_t StandInstDbType_realm_els (4)
const int AllocLinkType_F_X_NETTING (0)
const int AllocLinkType_F_X_SWAP (1)
const size_t AllocLinkType_realm_els (2)
const int PutOrCall_PUT (0)
const int PutOrCall_CALL (1)
const size_t PutOrCall_realm_els (2)
const int CoveredOrUncovered_COVERED (0)
const int CoveredOrUncovered_UNCOVERED (1)
const size_t CoveredOrUncovered_realm_els (2)
const int CustomerOrFirm_CUSTOMER (0)
const int CustomerOrFirm_FIRM (1)
const size_t CustomerOrFirm_realm_els (2)
const char NotifyBrokerOfCredit_NO ('N')
const char NotifyBrokerOfCredit_YES ('Y')
const size_t NotifyBrokerOfCredit_realm_els (2)
const int AllocHandlInst_MATCH (1)
const int AllocHandlInst_FORWARD (2)
const int AllocHandlInst_FORWARD_AND_MATCH (3)
const size_t AllocHandlInst_realm_els (3)
const int RoutingType_TARGET_FIRM (1)
const int RoutingType_TARGET_LIST (2)
const int RoutingType_BLOCK_FIRM (3)
const int RoutingType_BLOCK_LIST (4)
const size_t RoutingType_realm_els (4)
const char Benchmark_CURVE ('1')
const char Benchmark_5_YR ('2')
const char Benchmark_OLD_5 ('3')
const char Benchmark_10_YR ('4')
const char Benchmark_OLD_10 ('5')
const char Benchmark_30_YR ('6')
const char Benchmark_OLD_30 ('7')
const char Benchmark_3_MO_LIBOR ('8')
const char Benchmark_6_MO_LIBOR ('9')
const size_t Benchmark_realm_els (9)
const char SubscriptionRequestType_SNAPSHOT ('0')
const char SubscriptionRequestType_SNAPSHOT_PLUS_UPDATES ('1')
const char SubscriptionRequestType_DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST ('2')
const size_t SubscriptionRequestType_realm_els (3)
const int MDUpdateType_FULL_REFRESH (0)
const int MDUpdateType_INCREMENTAL_REFRESH (1)
const size_t MDUpdateType_realm_els (2)
const char AggregatedBook_NO ('N')
const char AggregatedBook_YES ('Y')
const size_t AggregatedBook_realm_els (2)
const char MDEntryType_BID ('0')
const char MDEntryType_OFFER ('1')
const char MDEntryType_TRADE ('2')
const char MDEntryType_INDEX_VALUE ('3')
const char MDEntryType_OPENING_PRICE ('4')
const char MDEntryType_CLOSING_PRICE ('5')
const char MDEntryType_SETTLEMENT_PRICE ('6')
const char MDEntryType_TRADING_SESSION_HIGH_PRICE ('7')
const char MDEntryType_TRADING_SESSION_LOW_PRICE ('8')
const char MDEntryType_TRADING_SESSION_VWAP_PRICE ('9')
const size_t MDEntryType_realm_els (10)
const char TickDirection_PLUS_TICK ('0')
const char TickDirection_ZERO_PLUS_TICK ('1')
const char TickDirection_MINUS_TICK ('2')
const char TickDirection_ZERO_MINUS_TICK ('3')
const size_t TickDirection_realm_els (4)
const f8String QuoteCondition_OPEN ("A")
const f8String QuoteCondition_CLOSED ("B")
const f8String QuoteCondition_EXCHANGE_BEST ("C")
const f8String QuoteCondition_CONSOLIDATED_BEST ("D")
const f8String QuoteCondition_LOCKED ("E")
const f8String QuoteCondition_CROSSED ("F")
const f8String QuoteCondition_DEPTH ("G")
const f8String QuoteCondition_FAST_TRADING ("H")
const f8String QuoteCondition_NON_FIRM ("I")
const size_t QuoteCondition_realm_els (9)
const f8String TradeCondition_CASH ("A")
const f8String TradeCondition_AVERAGE_PRICE_TRADE ("B")
const f8String TradeCondition_CASH_TRADE ("C")
const f8String TradeCondition_NEXT_DAY ("D")
const f8String TradeCondition_OPENING ("E")
const f8String TradeCondition_INTRADAY_TRADE_DETAIL ("F")
const f8String TradeCondition_RULE_127_TRADE ("G")
const f8String TradeCondition_RULE_155_TRADE ("H")
const f8String TradeCondition_SOLD_LAST ("I")
const f8String TradeCondition_NEXT_DAY_TRADE ("J")
const f8String TradeCondition_OPENED ("K")
const f8String TradeCondition_SELLER ("L")
const f8String TradeCondition_SOLD ("M")
const f8String TradeCondition_STOPPED_STOCK ("N")
const size_t TradeCondition_realm_els (14)
const char MDUpdateAction_NEW ('0')
const char MDUpdateAction_CHANGE ('1')
const char MDUpdateAction_DELETE ('2')
const size_t MDUpdateAction_realm_els (3)
const char MDReqRejReason_UNKNOWN_SYMBOL ('0')
const char MDReqRejReason_DUPLICATE_MDREQID ('1')
const char MDReqRejReason_INSUFFICIENT_BANDWIDTH ('2')
const char MDReqRejReason_INSUFFICIENT_PERMISSIONS ('3')
const char MDReqRejReason_UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE ('4')
const char MDReqRejReason_UNSUPPORTED_MARKETDEPTH ('5')
const char MDReqRejReason_UNSUPPORTED_MDUPDATETYPE ('6')
const char MDReqRejReason_UNSUPPORTED_AGGREGATEDBOOK ('7')
const char MDReqRejReason_UNSUPPORTED_MDENTRYTYPE ('8')
const size_t MDReqRejReason_realm_els (9)
const char DeleteReason_CANCELATION ('0')
const char DeleteReason_ERROR ('1')
const size_t DeleteReason_realm_els (2)
const char OpenCloseSettleFlag_DAILY_OPEN ('0')
const char OpenCloseSettleFlag_SESSION_OPEN ('1')
const char OpenCloseSettleFlag_DELIVERY_SETTLEMENT_PRICE ('2')
const size_t OpenCloseSettleFlag_realm_els (3)
const char FinancialStatus_BANKRUPT ('1')
const size_t FinancialStatus_realm_els (1)
const char CorporateAction_EX_DIVIDEND ('A')
const char CorporateAction_EX_DISTRIBUTION ('B')
const char CorporateAction_EX_RIGHTS ('C')
const char CorporateAction_NEW ('D')
const char CorporateAction_EX_INTEREST ('E')
const size_t CorporateAction_realm_els (5)
const int QuoteAckStatus_ACCEPTED (0)
const int QuoteAckStatus_CANCELED_FOR_SYMBOL (1)
const int QuoteAckStatus_CANCELED_FOR_SECURITY_TYPE (2)
const int QuoteAckStatus_CANCELED_FOR_UNDERLYING (3)
const int QuoteAckStatus_CANCELED_ALL (4)
const int QuoteAckStatus_REJECTED (5)
const size_t QuoteAckStatus_realm_els (6)
const int QuoteCancelType_CANCEL_FOR_SYMBOL (1)
const int QuoteCancelType_CANCEL_FOR_SECURITY_TYPE (2)
const int QuoteCancelType_CANCEL_FOR_UNDERLYING_SYMBOL (3)
const int QuoteCancelType_CANCEL_FOR_ALL_QUOTES (4)
const size_t QuoteCancelType_realm_els (4)
const int QuoteRejectReason_UNKNOWN_SYMBOL (1)
const int QuoteRejectReason_EXCHANGE (2)
const int QuoteRejectReason_QUOTE_REQUEST_EXCEEDS_LIMIT (3)
const int QuoteRejectReason_TOO_LATE_TO_ENTER (4)
const int QuoteRejectReason_UNKNOWN_QUOTE (5)
const int QuoteRejectReason_DUPLICATE_QUOTE (6)
const int QuoteRejectReason_INVALID_BID_ASK_SPREAD (7)
const int QuoteRejectReason_INVALID_PRICE (8)
const int QuoteRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY (9)
const size_t QuoteRejectReason_realm_els (9)
const int QuoteResponseLevel_NO_ACKNOWLEDGEMENT (0)
const int QuoteResponseLevel_ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES (1)
const int QuoteResponseLevel_ACKNOWLEDGE_EACH_QUOTE_MESSAGES (2)
const size_t QuoteResponseLevel_realm_els (3)
const int QuoteRequestType_MANUAL (1)
const int QuoteRequestType_AUTOMATIC (2)
const size_t QuoteRequestType_realm_els (2)
const int SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS (0)
const int SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED (1)
const int SecurityRequestType_REQUEST_LIST_SECURITY_TYPES (2)
const int SecurityRequestType_REQUEST_LIST_SECURITIES (3)
const size_t SecurityRequestType_realm_els (4)
const int SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_AS_IS (1)
const int SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE (2)
const int SecurityResponseType_LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST (3)
const int SecurityResponseType_LIST_OF_SECURITIES_RETURNED_PER_REQUEST (4)
const int SecurityResponseType_REJECT_SECURITY_PROPOSAL (5)
const int SecurityResponseType_CAN_NOT_MATCH_SELECTION_CRITERIA (6)
const size_t SecurityResponseType_realm_els (6)
const char UnsolicitedIndicator_NO ('N')
const char UnsolicitedIndicator_YES ('Y')
const size_t UnsolicitedIndicator_realm_els (2)
const int SecurityTradingStatus_OPENING_DELAY (1)
const int SecurityTradingStatus_TRADING_HALT (2)
const int SecurityTradingStatus_RESUME (3)
const int SecurityTradingStatus_NO_OPEN_NO_RESUME (4)
const int SecurityTradingStatus_PRICE_INDICATION (5)
const int SecurityTradingStatus_TRADING_RANGE_INDICATION (6)
const int SecurityTradingStatus_MARKET_IMBALANCE_BUY (7)
const int SecurityTradingStatus_MARKET_IMBALANCE_SELL (8)
const int SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_BUY (9)
const int SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_SELL (10)
const int SecurityTradingStatus_11 (11)
const int SecurityTradingStatus_NO_MARKET_IMBALANCE (12)
const int SecurityTradingStatus_NO_MARKET_ON_CLOSE_IMBALANCE (13)
const int SecurityTradingStatus_ITS_PRE_OPENING (14)
const int SecurityTradingStatus_NEW_PRICE_INDICATION (15)
const int SecurityTradingStatus_TRADE_DISSEMINATION_TIME (16)
const int SecurityTradingStatus_READY_TO_TRADE (17)
const int SecurityTradingStatus_NOT_AVAILABLE_FOR_TRADING (18)
const int SecurityTradingStatus_NOT_TRADED_ON_THIS_MARKET (19)
const int SecurityTradingStatus_UNKNOWN_OR_INVALID (20)
const size_t SecurityTradingStatus_realm_els (20)
const char HaltReasonChar_NEWS_DISSEMINATION ('D')
const char HaltReasonChar_ORDER_INFLUX ('E')
const char HaltReasonChar_ORDER_IMBALANCE ('I')
const char HaltReasonChar_ADDITIONAL_INFORMATION ('M')
const char HaltReasonChar_NEWS_PENDING ('P')
const char HaltReasonChar_EQUIPMENT_CHANGEOVER ('X')
const size_t HaltReasonChar_realm_els (6)
const char InViewOfCommon_NO ('N')
const char InViewOfCommon_YES ('Y')
const size_t InViewOfCommon_realm_els (2)
const char DueToRelated_NO ('N')
const char DueToRelated_YES ('Y')
const size_t DueToRelated_realm_els (2)
const int Adjustment_CANCEL (1)
const int Adjustment_ERROR (2)
const int Adjustment_CORRECTION (3)
const size_t Adjustment_realm_els (3)
const int TradSesMethod_ELECTRONIC (1)
const int TradSesMethod_OPEN_OUTCRY (2)
const int TradSesMethod_TWO_PARTY (3)
const size_t TradSesMethod_realm_els (3)
const int TradSesMode_TESTING (1)
const int TradSesMode_SIMULATED (2)
const int TradSesMode_PRODUCTION (3)
const size_t TradSesMode_realm_els (3)
const int TradSesStatus_HALTED (1)
const int TradSesStatus_OPEN (2)
const int TradSesStatus_CLOSED (3)
const int TradSesStatus_PRE_OPEN (4)
const int TradSesStatus_PRE_CLOSE (5)
const size_t TradSesStatus_realm_els (5)
const f8String MessageEncoding_EUC_JP ("EUC-JP")
const f8String MessageEncoding_ISO_2022_JP ("ISO-2022-JP")
const f8String MessageEncoding_SHIFT_JIS ("SHIFT_JIS")
const f8String MessageEncoding_UTF_8 ("UTF-8")
const size_t MessageEncoding_realm_els (4)
const int QuoteEntryRejectReason_UNKNOWN_SYMBOL (1)
const int QuoteEntryRejectReason_EXCHANGE (2)
const int QuoteEntryRejectReason_QUOTE_EXCEEDS_LIMIT (3)
const int QuoteEntryRejectReason_TOO_LATE_TO_ENTER (4)
const int QuoteEntryRejectReason_UNKNOWN_QUOTE (5)
const int QuoteEntryRejectReason_DUPLICATE_QUOTE (6)
const int QuoteEntryRejectReason_INVALID_BID_ASK_SPREAD (7)
const int QuoteEntryRejectReason_INVALID_PRICE (8)
const int QuoteEntryRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY (9)
const size_t QuoteEntryRejectReason_realm_els (9)
const int SessionRejectReason_INVALID_TAG_NUMBER (0)
const int SessionRejectReason_REQUIRED_TAG_MISSING (1)
const int SessionRejectReason_TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE (2)
const int SessionRejectReason_UNDEFINED_TAG (3)
const int SessionRejectReason_TAG_SPECIFIED_WITHOUT_A_VALUE (4)
const int SessionRejectReason_VALUE_IS_INCORRECT (5)
const int SessionRejectReason_INCORRECT_DATA_FORMAT_FOR_VALUE (6)
const int SessionRejectReason_DECRYPTION_PROBLEM (7)
const int SessionRejectReason_SIGNATURE_PROBLEM (8)
const int SessionRejectReason_COMPID_PROBLEM (9)
const int SessionRejectReason_SENDINGTIME_ACCURACY_PROBLEM (10)
const int SessionRejectReason_INVALID_MSGTYPE (11)
const size_t SessionRejectReason_realm_els (12)
const char BidRequestTransType_CANCEL ('C')
const char BidRequestTransType_NO ('N')
const size_t BidRequestTransType_realm_els (2)
const char SolicitedFlag_NO ('N')
const char SolicitedFlag_YES ('Y')
const size_t SolicitedFlag_realm_els (2)
const int ExecRestatementReason_GT_CORPORATE_ACTION (0)
const int ExecRestatementReason_GT_RENEWAL (1)
const int ExecRestatementReason_VERBAL_CHANGE (2)
const int ExecRestatementReason_REPRICING_OF_ORDER (3)
const int ExecRestatementReason_BROKER_OPTION (4)
const int ExecRestatementReason_PARTIAL_DECLINE_OF_ORDERQTY (5)
const size_t ExecRestatementReason_realm_els (6)
const int BusinessRejectReason_OTHER (0)
const int BusinessRejectReason_UNKOWN_ID (1)
const int BusinessRejectReason_UNKNOWN_SECURITY (2)
const int BusinessRejectReason_UNSUPPORTED_MESSAGE_TYPE (3)
const int BusinessRejectReason_APPLICATION_NOT_AVAILABLE (4)
const int BusinessRejectReason_CONDITIONALLY_REQUIRED_FIELD_MISSING (5)
const size_t BusinessRejectReason_realm_els (6)
const char MsgDirection_RECEIVE ('R')
const char MsgDirection_SEND ('S')
const size_t MsgDirection_realm_els (2)
const char DiscretionInst_RELATED_TO_DISPLAYED_PRICE ('0')
const char DiscretionInst_RELATED_TO_MARKET_PRICE ('1')
const char DiscretionInst_RELATED_TO_PRIMARY_PRICE ('2')
const char DiscretionInst_RELATED_TO_LOCAL_PRIMARY_PRICE ('3')
const char DiscretionInst_RELATED_TO_MIDPOINT_PRICE ('4')
const char DiscretionInst_RELATED_TO_LAST_TRADE_PRICE ('5')
const size_t DiscretionInst_realm_els (6)
const int LiquidityIndType_5_DAY_MOVING_AVERAGE (1)
const int LiquidityIndType_20_DAY_MOVING_AVERAGE (2)
const int LiquidityIndType_NORMAL_MARKET_SIZE (3)
const int LiquidityIndType_OTHER (4)
const size_t LiquidityIndType_realm_els (4)
const char ExchangeForPhysical_NO ('N')
const char ExchangeForPhysical_YES ('Y')
const size_t ExchangeForPhysical_realm_els (2)
const int ProgRptReqs_BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST (1)
const int ProgRptReqs_SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD (2)
const int ProgRptReqs_REAL_TIME_EXECUTION_REPORTS (3)
const size_t ProgRptReqs_realm_els (3)
const int IncTaxInd_NET (1)
const int IncTaxInd_GROSS (2)
const size_t IncTaxInd_realm_els (2)
const char TradeType_AGENCY ('A')
const char TradeType_VWAP_GUARANTEE ('G')
const char TradeType_GUARANTEED_CLOSE ('J')
const char TradeType_RISK_TRADE ('R')
const size_t TradeType_realm_els (4)
const char BasisPxType_CLOSING_PRICE_AT_MORNING_SESSION ('2')
const char BasisPxType_CLOSING_PRICE ('3')
const char BasisPxType_CURRENT_PRICE ('4')
const char BasisPxType_SQ ('5')
const char BasisPxType_VWAP_THROUGH_A_DAY ('6')
const char BasisPxType_VWAP_THROUGH_A_MORNING_SESSION ('7')
const char BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION ('8')
const char BasisPxType_VWAP_THROUGH_A_DAY_EXCEPT_YORI ('9')
const char BasisPxType_VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI ('A')
const char BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI ('B')
const char BasisPxType_STRIKE ('C')
const char BasisPxType_OPEN ('D')
const char BasisPxType_OTHERS ('Z')
const size_t BasisPxType_realm_els (13)
const int PriceType_PERCENTAGE (1)
const int PriceType_PER_SHARE (2)
const int PriceType_FIXED_AMOUNT (3)
const size_t PriceType_realm_els (3)
const int GTBookingInst_BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION (0)
const int GTBookingInst_ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES (1)
const int GTBookingInst_ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE (2)
const size_t GTBookingInst_realm_els (3)
const int NetGrossInd_NET (1)
const int NetGrossInd_GROSS (2)
const size_t NetGrossInd_realm_els (2)
const char ListExecInstType_IMMEDIATE ('1')
const char ListExecInstType_WAIT_FOR_EXECUTE_INSTRUCTION ('2')
const size_t ListExecInstType_realm_els (2)
const char CxlRejResponseTo_ORDER_CANCEL_REQUEST ('1')
const char CxlRejResponseTo_ORDER_CANCEL_REPLACE_REQUEST ('2')
const size_t CxlRejResponseTo_realm_els (2)
const char MultiLegReportingType_SINGLE_SECURITY ('1')
const char MultiLegReportingType_INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY ('2')
const char MultiLegReportingType_MULTI_LEG_SECURITY ('3')
const size_t MultiLegReportingType_realm_els (3)
Variables
const
UTEST::utest_BaseMsgEntry::Pair msgpairs []
const utest_BaseEntry::Pair fldpairs []
Typedef Documentation
typedef Field<f8String, 1> FIX8::UTEST::Account
Definition at line 64 of file utest_types.hpp.
typedef Field<Amt, 159> FIX8::UTEST::AccruedInterestAmt
Definition at line 723 of file utest_types.hpp.
typedef Field<double, 158> FIX8::UTEST::AccruedInterestRate
Definition at line 721 of file utest_types.hpp.
typedef Field<int, 334> FIX8::UTEST::Adjustment
Definition at line 1244 of file utest_types.hpp.
typedef Field<f8String, 2> FIX8::UTEST::AdvId
Definition at line 66 of file utest_types.hpp.
typedef Field<f8String, 3> FIX8::UTEST::AdvRefID
Definition at line 68 of file utest_types.hpp.
typedef Field<char, 4> FIX8::UTEST::AdvSide
Definition at line 70 of file utest_types.hpp.
typedef Field<f8String, 5> FIX8::UTEST::AdvTransType
Definition at line 77 of file utest_types.hpp.
typedef Field<Boolean, 266> FIX8::UTEST::AggregatedBook
Definition at line 957 of file utest_types.hpp.
typedef Field<f8String, 79> FIX8::UTEST::AllocAccount
Definition at line 448 of file utest_types.hpp.
typedef Field<price, 153> FIX8::UTEST::AllocAvgPx
Definition at line 708 of file utest_types.hpp.
typedef Field<int, 209> FIX8::UTEST::AllocHandlInst
Definition at line 897 of file utest_types.hpp.
typedef Field<f8String, 70> FIX8::UTEST::AllocID
Definition at line 420 of file utest_types.hpp.
typedef Field<f8String, 196> FIX8::UTEST::AllocLinkID
Definition at line 856 of file utest_types.hpp.
typedef Field<int, 197> FIX8::UTEST::AllocLinkType
Definition at line 858 of file utest_types.hpp.
typedef Field<Amt, 154> FIX8::UTEST::AllocNetMoney
Definition at line 710 of file utest_types.hpp.
typedef Field<price, 366> FIX8::UTEST::AllocPrice
Definition at line 1331 of file utest_types.hpp.
typedef Field<int, 88> FIX8::UTEST::AllocRejCode
Definition at line 475 of file utest_types.hpp.
typedef Field<Qty, 80> FIX8::UTEST::AllocShares
Definition at line 450 of file utest_types.hpp.
typedef Field<int, 87> FIX8::UTEST::AllocStatus
Definition at line 468 of file utest_types.hpp.
typedef Field<f8String, 161> FIX8::UTEST::AllocText
Definition at line 732 of file utest_types.hpp.
typedef Field<char, 71> FIX8::UTEST::AllocTransType
Definition at line 422 of file utest_types.hpp.
typedef Field<int, 74> FIX8::UTEST::AvgPrxPrecision
Definition at line 435 of file utest_types.hpp.
typedef Field<price, 6> FIX8::UTEST::AvgPx
Definition at line 83 of file utest_types.hpp.
typedef Field<char, 419> FIX8::UTEST::BasisPxType
Definition at line 1510 of file utest_types.hpp.
typedef Field<int, 7> FIX8::UTEST::BeginSeqNo
Definition at line 85 of file utest_types.hpp.
typedef Field<f8String, 8> FIX8::UTEST::BeginString
Definition at line 87 of file utest_types.hpp.
typedef Field<char, 219> FIX8::UTEST::Benchmark
Definition at line 926 of file utest_types.hpp.
typedef Field<f8String, 400> FIX8::UTEST::BidDescriptor
Definition at line 1452 of file utest_types.hpp.
typedef Field<int, 399> FIX8::UTEST::BidDescriptorType
Definition at line 1450 of file utest_types.hpp.
typedef Field<PriceOffset, 189> FIX8::UTEST::BidForwardPoints
Definition at line 842 of file utest_types.hpp.
typedef Field<f8String, 390> FIX8::UTEST::BidID
Definition at line 1432 of file utest_types.hpp.
typedef Field<price, 132> FIX8::UTEST::BidPx
Definition at line 637 of file utest_types.hpp.
typedef Field<char, 374> FIX8::UTEST::BidRequestTransType
Definition at line 1370 of file utest_types.hpp.
typedef Field<Qty, 134> FIX8::UTEST::BidSize
Definition at line 641 of file utest_types.hpp.
typedef Field<price, 188> FIX8::UTEST::BidSpotRate
Definition at line 840 of file utest_types.hpp.
typedef Field<int, 394> FIX8::UTEST::BidType
Definition at line 1440 of file utest_types.hpp.
typedef Field<int, 9> FIX8::UTEST::BodyLength
Definition at line 89 of file utest_types.hpp.
typedef Field<f8String, 92> FIX8::UTEST::BrokerOfCredit
Definition at line 492 of file utest_types.hpp.
typedef Field<int, 380> FIX8::UTEST::BusinessRejectReason
Definition at line 1395 of file utest_types.hpp.
typedef Field<f8String, 379> FIX8::UTEST::BusinessRejectRefID
Definition at line 1393 of file utest_types.hpp.
typedef Field<Qty, 330> FIX8::UTEST::BuyVolume
Definition at line 1236 of file utest_types.hpp.
typedef Field<Qty, 152> FIX8::UTEST::CashOrderQty
Definition at line 706 of file utest_types.hpp.
typedef Field<f8String, 185> FIX8::UTEST::CashSettlAgentAcctName
Definition at line 834 of file utest_types.hpp.
typedef Field<f8String, 184> FIX8::UTEST::CashSettlAgentAcctNum
Definition at line 832 of file utest_types.hpp.
typedef Field<f8String, 183> FIX8::UTEST::CashSettlAgentCode
Definition at line 830 of file utest_types.hpp.
typedef Field<f8String, 186> FIX8::UTEST::CashSettlAgentContactName
Definition at line 836 of file utest_types.hpp.
typedef Field<f8String, 187> FIX8::UTEST::CashSettlAgentContactPhone
Definition at line 838 of file utest_types.hpp.
typedef Field<f8String, 182> FIX8::UTEST::CashSettlAgentName
Definition at line 828 of file utest_types.hpp.
typedef Field<f8String, 10> FIX8::UTEST::CheckSum
Definition at line 91 of file utest_types.hpp.
typedef Field<f8String, 440> FIX8::UTEST::ClearingAccount
Definition at line 1583 of file utest_types.hpp.
typedef Field<f8String, 439> FIX8::UTEST::ClearingFirm
Definition at line 1581 of file utest_types.hpp.
typedef Field<f8String, 391> FIX8::UTEST::ClientBidID
Definition at line 1434 of file utest_types.hpp.
typedef Field<f8String, 109> FIX8::UTEST::ClientID
Definition at line 571 of file utest_types.hpp.
typedef Field<f8String, 11> FIX8::UTEST::ClOrdID
Definition at line 93 of file utest_types.hpp.
typedef Field<Amt, 12> FIX8::UTEST::Commission
Definition at line 95 of file utest_types.hpp.
typedef Field<char, 13> FIX8::UTEST::CommType
Definition at line 97 of file utest_types.hpp.
typedef Field<f8String, 376> FIX8::UTEST::ComplianceID
Definition at line 1377 of file utest_types.hpp.
typedef Field<f8String, 375> FIX8::UTEST::ContraBroker
Definition at line 1375 of file utest_types.hpp.
typedef Field<double, 231> FIX8::UTEST::ContractMultiplier
Definition at line 940 of file utest_types.hpp.
typedef Field<Qty, 437> FIX8::UTEST::ContraTradeQty
Definition at line 1577 of file utest_types.hpp.
typedef Field<f8String, 337> FIX8::UTEST::ContraTrader
Definition at line 1254 of file utest_types.hpp.
typedef Field<UTCTimestamp, 438> FIX8::UTEST::ContraTradeTime
Definition at line 1579 of file utest_types.hpp.
typedef Field<char, 292> FIX8::UTEST::CorporateAction
Definition at line 1076 of file utest_types.hpp.
typedef Field<f8String, 421> FIX8::UTEST::Country
Definition at line 1528 of file utest_types.hpp.
typedef Field<double, 223> FIX8::UTEST::CouponRate
Definition at line 938 of file utest_types.hpp.
typedef Field<int, 203> FIX8::UTEST::CoveredOrUncovered
Definition at line 876 of file utest_types.hpp.
typedef Field<double, 413> FIX8::UTEST::CrossPercent
Definition at line 1486 of file utest_types.hpp.
typedef Field<Qty, 14> FIX8::UTEST::CumQty
Definition at line 103 of file utest_types.hpp.
typedef Field<currency, 15> FIX8::UTEST::Currency
Definition at line 105 of file utest_types.hpp.
typedef Field<int, 204> FIX8::UTEST::CustomerOrFirm
Definition at line 881 of file utest_types.hpp.
typedef Field<Qty, 84> FIX8::UTEST::CxlQty
Definition at line 466 of file utest_types.hpp.
typedef Field<int, 102> FIX8::UTEST::CxlRejReason
Definition at line 525 of file utest_types.hpp.
typedef Field<char, 434> FIX8::UTEST::CxlRejResponseTo
Definition at line 1568 of file utest_types.hpp.
typedef Field<price, 426> FIX8::UTEST::DayAvgPx
Definition at line 1542 of file utest_types.hpp.
typedef Field<Qty, 425> FIX8::UTEST::DayCumQty
Definition at line 1540 of file utest_types.hpp.
typedef Field<Qty, 424> FIX8::UTEST::DayOrderQty
Definition at line 1538 of file utest_types.hpp.
typedef Field<Qty, 293> FIX8::UTEST::DefBidSize
Definition at line 1084 of file utest_types.hpp.
typedef Field<Qty, 294> FIX8::UTEST::DefOfferSize
Definition at line 1086 of file utest_types.hpp.
typedef Field<char, 285> FIX8::UTEST::DeleteReason
Definition at line 1053 of file utest_types.hpp.
typedef Field<f8String, 128> FIX8::UTEST::DeliverToCompID
Definition at line 626 of file utest_types.hpp.
typedef Field<f8String, 145> FIX8::UTEST::DeliverToLocationID
Definition at line 676 of file utest_types.hpp.
typedef Field<f8String, 129> FIX8::UTEST::DeliverToSubID
Definition at line 628 of file utest_types.hpp.
typedef Field<LocalMktDate, 743> FIX8::UTEST::DeliveryDate
Definition at line 1605 of file utest_types.hpp.
typedef Field<f8String, 284> FIX8::UTEST::DeskID
Definition at line 1051 of file utest_types.hpp.
typedef Field<char, 388> FIX8::UTEST::DiscretionInst
Definition at line 1421 of file utest_types.hpp.
typedef Field<PriceOffset, 389> FIX8::UTEST::DiscretionOffset
Definition at line 1430 of file utest_types.hpp.
typedef Field<char, 127> FIX8::UTEST::DKReason
Definition at line 617 of file utest_types.hpp.
typedef Field<Boolean, 329> FIX8::UTEST::DueToRelated
Definition at line 1231 of file utest_types.hpp.
typedef Field<UTCTimestamp, 168> FIX8::UTEST::EffectiveTime
Definition at line 795 of file utest_types.hpp.
typedef Field<double, 405> FIX8::UTEST::EFPTrackingError
Definition at line 1462 of file utest_types.hpp.
typedef Field<f8String, 164> FIX8::UTEST::EmailThreadID
Definition at line 742 of file utest_types.hpp.
typedef Field<char, 94> FIX8::UTEST::EmailType
Definition at line 496 of file utest_types.hpp.
typedef Field<data, 361> FIX8::UTEST::EncodedAllocText
Definition at line 1321 of file utest_types.hpp.
typedef Field<Length, 360> FIX8::UTEST::EncodedAllocTextLen
Definition at line 1319 of file utest_types.hpp.
typedef Field<data, 359> FIX8::UTEST::EncodedHeadline
Definition at line 1317 of file utest_types.hpp.
typedef Field<Length, 358> FIX8::UTEST::EncodedHeadlineLen
Definition at line 1315 of file utest_types.hpp.
typedef Field<data, 349> FIX8::UTEST::EncodedIssuer
Definition at line 1297 of file utest_types.hpp.
typedef Field<Length, 348> FIX8::UTEST::EncodedIssuerLen
Definition at line 1295 of file utest_types.hpp.
typedef Field<data, 353> FIX8::UTEST::EncodedListExecInst
Definition at line 1305 of file utest_types.hpp.
typedef Field<Length, 352> FIX8::UTEST::EncodedListExecInstLen
Definition at line 1303 of file utest_types.hpp.
typedef Field<data, 446> FIX8::UTEST::EncodedListStatusText
Definition at line 1599 of file utest_types.hpp.
typedef Field<Length, 445> FIX8::UTEST::EncodedListStatusTextLen
Definition at line 1597 of file utest_types.hpp.
typedef Field<data, 351> FIX8::UTEST::EncodedSecurityDesc
Definition at line 1301 of file utest_types.hpp.
typedef Field<Length, 350> FIX8::UTEST::EncodedSecurityDescLen
Definition at line 1299 of file utest_types.hpp.
typedef Field<data, 357> FIX8::UTEST::EncodedSubject
Definition at line 1313 of file utest_types.hpp.
typedef Field<Length, 356> FIX8::UTEST::EncodedSubjectLen
Definition at line 1311 of file utest_types.hpp.
typedef Field<data, 355> FIX8::UTEST::EncodedText
Definition at line 1309 of file utest_types.hpp.
typedef Field<Length, 354> FIX8::UTEST::EncodedTextLen
Definition at line 1307 of file utest_types.hpp.
typedef Field<data, 363> FIX8::UTEST::EncodedUnderlyingIssuer
Definition at line 1325 of file utest_types.hpp.
typedef Field<Length, 362> FIX8::UTEST::EncodedUnderlyingIssuerLen
Definition at line 1323 of file utest_types.hpp.
typedef Field<data, 365> FIX8::UTEST::EncodedUnderlyingSecurityDesc
Definition at line 1329 of file utest_types.hpp.
typedef Field<Length, 364> FIX8::UTEST::EncodedUnderlyingSecurityDescLen
Definition at line 1327 of file utest_types.hpp.
typedef Field<int, 98> FIX8::UTEST::EncryptMethod
Definition at line 511 of file utest_types.hpp.
typedef Field<int, 16> FIX8::UTEST::EndSeqNo
Definition at line 107 of file utest_types.hpp.
typedef Field<Boolean, 411> FIX8::UTEST::ExchangeForPhysical
Definition at line 1479 of file utest_types.hpp.
typedef Field<Exchange, 100> FIX8::UTEST::ExDestination
Definition at line 523 of file utest_types.hpp.
typedef Field<f8String, 76> FIX8::UTEST::ExecBroker
Definition at line 439 of file utest_types.hpp.
typedef Field<f8String, 17> FIX8::UTEST::ExecID
Definition at line 109 of file utest_types.hpp.
typedef Field<MultipleStringValue, 18> FIX8::UTEST::ExecInst
Definition at line 111 of file utest_types.hpp.
typedef Field<f8String, 19> FIX8::UTEST::ExecRefID
Definition at line 143 of file utest_types.hpp.
typedef Field<int, 378> FIX8::UTEST::ExecRestatementReason
Definition at line 1384 of file utest_types.hpp.
typedef Field<char, 20> FIX8::UTEST::ExecTransType
Definition at line 145 of file utest_types.hpp.
typedef Field<char, 150> FIX8::UTEST::ExecType
Definition at line 686 of file utest_types.hpp.
typedef Field<LocalMktDate, 432> FIX8::UTEST::ExpireDate
Definition at line 1561 of file utest_types.hpp.
typedef Field<UTCTimestamp, 126> FIX8::UTEST::ExpireTime
Definition at line 615 of file utest_types.hpp.
typedef Field<Amt, 406> FIX8::UTEST::FairValue
Definition at line 1464 of file utest_types.hpp.
typedef Field<char, 291> FIX8::UTEST::FinancialStatus
Definition at line 1072 of file utest_types.hpp.
typedef Field<Boolean, 121> FIX8::UTEST::ForexReq
Definition at line 601 of file utest_types.hpp.
typedef Field<LocalMktDate, 64> FIX8::UTEST::FutSettDate
Definition at line 408 of file utest_types.hpp.
typedef Field<LocalMktDate, 193> FIX8::UTEST::FutSettDate2
Definition at line 850 of file utest_types.hpp.
typedef Field<Boolean, 123> FIX8::UTEST::GapFillFlag
Definition at line 608 of file utest_types.hpp.
typedef Field<Amt, 381> FIX8::UTEST::GrossTradeAmt
Definition at line 1404 of file utest_types.hpp.
typedef Field<int, 427> FIX8::UTEST::GTBookingInst
Definition at line 1544 of file utest_types.hpp.
typedef Field<char, 327> FIX8::UTEST::HaltReasonChar
Definition at line 1217 of file utest_types.hpp.
typedef Field<char, 21> FIX8::UTEST::HandlInst
Definition at line 152 of file utest_types.hpp.
typedef Field<f8String, 148> FIX8::UTEST::Headline
Definition at line 682 of file utest_types.hpp.
typedef Field<int, 108> FIX8::UTEST::HeartBtInt
Definition at line 569 of file utest_types.hpp.
typedef Field<price, 332> FIX8::UTEST::HighPx
Definition at line 1240 of file utest_types.hpp.
typedef Field<f8String, 22> FIX8::UTEST::IDSource
Definition at line 158 of file utest_types.hpp.
typedef Field<int, 416> FIX8::UTEST::IncTaxInd
Definition at line 1496 of file utest_types.hpp.
typedef Field<Boolean, 328> FIX8::UTEST::InViewOfCommon
Definition at line 1226 of file utest_types.hpp.
typedef Field<f8String, 23> FIX8::UTEST::IOIid
Definition at line 170 of file utest_types.hpp.
typedef Field<Boolean, 130> FIX8::UTEST::IOINaturalFlag
Definition at line 630 of file utest_types.hpp.
typedef Field<char, 25> FIX8::UTEST::IOIQltyInd
Definition at line 172 of file utest_types.hpp.
typedef Field<char, 104> FIX8::UTEST::IOIQualifier
Definition at line 544 of file utest_types.hpp.
typedef Field<f8String, 26> FIX8::UTEST::IOIRefID
Definition at line 178 of file utest_types.hpp.
typedef Field<f8String, 27> FIX8::UTEST::IOIShares
Definition at line 180 of file utest_types.hpp.
typedef Field<char, 28> FIX8::UTEST::IOITransType
Definition at line 186 of file utest_types.hpp.
typedef Field<f8String, 106> FIX8::UTEST::Issuer
Definition at line 565 of file utest_types.hpp.
typedef Field<char, 29> FIX8::UTEST::LastCapacity
Definition at line 192 of file utest_types.hpp.
typedef Field<PriceOffset, 195> FIX8::UTEST::LastForwardPoints
Definition at line 854 of file utest_types.hpp.
typedef Field<Exchange, 30> FIX8::UTEST::LastMkt
Definition at line 199 of file utest_types.hpp.
typedef Field<int, 369> FIX8::UTEST::LastMsgSeqNumProcessed
Definition at line 1347 of file utest_types.hpp.
typedef Field<price, 31> FIX8::UTEST::LastPx
Definition at line 201 of file utest_types.hpp.
typedef Field<Qty, 32> FIX8::UTEST::LastShares
Definition at line 203 of file utest_types.hpp.
typedef Field<price, 194> FIX8::UTEST::LastSpotRate
Definition at line 852 of file utest_types.hpp.
typedef Field<Qty, 151> FIX8::UTEST::LeavesQty
Definition at line 704 of file utest_types.hpp.
typedef Field<int, 33> FIX8::UTEST::LinesOfText
Definition at line 205 of file utest_types.hpp.
typedef Field<int, 409> FIX8::UTEST::LiquidityIndType
Definition at line 1470 of file utest_types.hpp.
typedef Field<int, 441> FIX8::UTEST::LiquidityNumSecurities
Definition at line 1585 of file utest_types.hpp.
typedef Field<double, 403> FIX8::UTEST::LiquidityPctHigh
Definition at line 1458 of file utest_types.hpp.
typedef Field<double, 402> FIX8::UTEST::LiquidityPctLow
Definition at line 1456 of file utest_types.hpp.
typedef Field<Amt, 404> FIX8::UTEST::LiquidityValue
Definition at line 1460 of file utest_types.hpp.
typedef Field<f8String, 69> FIX8::UTEST::ListExecInst
Definition at line 418 of file utest_types.hpp.
typedef Field<char, 433> FIX8::UTEST::ListExecInstType
Definition at line 1563 of file utest_types.hpp.
typedef Field<f8String, 66> FIX8::UTEST::ListID
Definition at line 412 of file utest_types.hpp.
typedef Field<f8String, 392> FIX8::UTEST::ListName
Definition at line 1436 of file utest_types.hpp.
typedef Field<int, 431> FIX8::UTEST::ListOrderStatus
Definition at line 1559 of file utest_types.hpp.
typedef Field<int, 67> FIX8::UTEST::ListSeqNo
Definition at line 414 of file utest_types.hpp.
typedef Field<f8String, 444> FIX8::UTEST::ListStatusText
Definition at line 1595 of file utest_types.hpp.
typedef Field<int, 429> FIX8::UTEST::ListStatusType
Definition at line 1552 of file utest_types.hpp.
typedef Field<Boolean, 114> FIX8::UTEST::LocateReqd
Definition at line 584 of file utest_types.hpp.
typedef Field<f8String, 283> FIX8::UTEST::LocationID
Definition at line 1049 of file utest_types.hpp.
typedef Field<price, 333> FIX8::UTEST::LowPx
Definition at line 1242 of file utest_types.hpp.
typedef Field<int, 264> FIX8::UTEST::MarketDepth
Definition at line 950 of file utest_types.hpp.
typedef Field<DayOfMonth, 205> FIX8::UTEST::MaturityDay
Definition at line 886 of file utest_types.hpp.
typedef Field<MonthYear, 200> FIX8::UTEST::MaturityMonthYear
Definition at line 867 of file utest_types.hpp.
typedef Field<Qty, 111> FIX8::UTEST::MaxFloor
Definition at line 575 of file utest_types.hpp.
typedef Field<int, 383> FIX8::UTEST::MaxMessageSize
Definition at line 1408 of file utest_types.hpp.
typedef Field<Qty, 210> FIX8::UTEST::MaxShow
Definition at line 903 of file utest_types.hpp.
typedef Field<f8String, 288> FIX8::UTEST::MDEntryBuyer
Definition at line 1066 of file utest_types.hpp.
typedef Field<UTCDateOnly, 272> FIX8::UTEST::MDEntryDate
Definition at line 983 of file utest_types.hpp.
typedef Field<f8String, 278> FIX8::UTEST::MDEntryID
Definition at line 1025 of file utest_types.hpp.
typedef Field<f8String, 282> FIX8::UTEST::MDEntryOriginator
Definition at line 1047 of file utest_types.hpp.
typedef Field<int, 290> FIX8::UTEST::MDEntryPositionNo
Definition at line 1070 of file utest_types.hpp.
typedef Field<price, 270> FIX8::UTEST::MDEntryPx
Definition at line 979 of file utest_types.hpp.
typedef Field<f8String, 280> FIX8::UTEST::MDEntryRefID
Definition at line 1033 of file utest_types.hpp.
typedef Field<f8String, 289> FIX8::UTEST::MDEntrySeller
Definition at line 1068 of file utest_types.hpp.
typedef Field<Qty, 271> FIX8::UTEST::MDEntrySize
Definition at line 981 of file utest_types.hpp.
typedef Field<UTCTimeOnly, 273> FIX8::UTEST::MDEntryTime
Definition at line 985 of file utest_types.hpp.
typedef Field<char, 269> FIX8::UTEST::MDEntryType
Definition at line 966 of file utest_types.hpp.
typedef Field<Exchange, 275> FIX8::UTEST::MDMkt
Definition at line 994 of file utest_types.hpp.
typedef Field<f8String, 262> FIX8::UTEST::MDReqID
Definition at line 942 of file utest_types.hpp.
typedef Field<char, 281> FIX8::UTEST::MDReqRejReason
Definition at line 1035 of file utest_types.hpp.
typedef Field<char, 279> FIX8::UTEST::MDUpdateAction
Definition at line 1027 of file utest_types.hpp.
typedef Field<int, 265> FIX8::UTEST::MDUpdateType
Definition at line 952 of file utest_types.hpp.
typedef Field<f8String, 347> FIX8::UTEST::MessageEncoding
Definition at line 1288 of file utest_types.hpp.
typedef Field<Qty, 110> FIX8::UTEST::MinQty
Definition at line 573 of file utest_types.hpp.
typedef Field<Amt, 137> FIX8::UTEST::MiscFeeAmt
Definition at line 647 of file utest_types.hpp.
typedef Field<currency, 138> FIX8::UTEST::MiscFeeCurr
Definition at line 649 of file utest_types.hpp.
typedef Field<char, 139> FIX8::UTEST::MiscFeeType
Definition at line 651 of file utest_types.hpp.
typedef Field<char, 385> FIX8::UTEST::MsgDirection
Definition at line 1412 of file utest_types.hpp.
typedef Field<int, 34> FIX8::UTEST::MsgSeqNum
Definition at line 207 of file utest_types.hpp.
typedef Field<f8String, 35> FIX8::UTEST::MsgType
Definition at line 209 of file utest_types.hpp.
typedef Field<char, 442> FIX8::UTEST::MultiLegReportingType
Definition at line 1587 of file utest_types.hpp.
typedef Field<int, 430> FIX8::UTEST::NetGrossInd
Definition at line 1554 of file utest_types.hpp.
typedef Field<Amt, 118> FIX8::UTEST::NetMoney
Definition at line 595 of file utest_types.hpp.
typedef Field<int, 36> FIX8::UTEST::NewSeqNo
Definition at line 258 of file utest_types.hpp.
typedef Field<int, 78> FIX8::UTEST::NoAllocs
Definition at line 446 of file utest_types.hpp.
typedef Field<int, 420> FIX8::UTEST::NoBidComponents
Definition at line 1526 of file utest_types.hpp.
typedef Field<int, 398> FIX8::UTEST::NoBidDescriptors
Definition at line 1448 of file utest_types.hpp.
typedef Field<int, 382> FIX8::UTEST::NoContraBrokers
Definition at line 1406 of file utest_types.hpp.
typedef Field<int, 124> FIX8::UTEST::NoExecs
Definition at line 613 of file utest_types.hpp.
typedef Field<int, 199> FIX8::UTEST::NoIOIQualifiers
Definition at line 865 of file utest_types.hpp.
typedef Field<int, 268> FIX8::UTEST::NoMDEntries
Definition at line 964 of file utest_types.hpp.
typedef Field<int, 267> FIX8::UTEST::NoMDEntryTypes
Definition at line 962 of file utest_types.hpp.
typedef Field<int, 136> FIX8::UTEST::NoMiscFees
Definition at line 645 of file utest_types.hpp.
typedef Field<int, 384> FIX8::UTEST::NoMsgTypes
Definition at line 1410 of file utest_types.hpp.
typedef Field<int, 73> FIX8::UTEST::NoOrders
Definition at line 433 of file utest_types.hpp.
typedef Field<int, 295> FIX8::UTEST::NoQuoteEntries
Definition at line 1088 of file utest_types.hpp.
typedef Field<int, 296> FIX8::UTEST::NoQuoteSets
Definition at line 1090 of file utest_types.hpp.
typedef Field<int, 146> FIX8::UTEST::NoRelatedSym
Definition at line 678 of file utest_types.hpp.
typedef Field<int, 215> FIX8::UTEST::NoRoutingIDs
Definition at line 913 of file utest_types.hpp.
typedef Field<int, 82> FIX8::UTEST::NoRpts
Definition at line 462 of file utest_types.hpp.
typedef Field<int, 428> FIX8::UTEST::NoStrikes
Definition at line 1550 of file utest_types.hpp.
typedef Field<Boolean, 208> FIX8::UTEST::NotifyBrokerOfCredit
Definition at line 892 of file utest_types.hpp.
typedef Field<int, 386> FIX8::UTEST::NoTradingSessions
Definition at line 1417 of file utest_types.hpp.
typedef Field<int, 346> FIX8::UTEST::NumberOfOrders
Definition at line 1286 of file utest_types.hpp.
typedef Field<int, 417> FIX8::UTEST::NumBidders
Definition at line 1501 of file utest_types.hpp.
typedef Field<int, 157> FIX8::UTEST::NumDaysInterest
Definition at line 719 of file utest_types.hpp.
typedef Field<int, 395> FIX8::UTEST::NumTickets
Definition at line 1442 of file utest_types.hpp.
typedef Field<PriceOffset, 191> FIX8::UTEST::OfferForwardPoints
Definition at line 846 of file utest_types.hpp.
typedef Field<price, 133> FIX8::UTEST::OfferPx
Definition at line 639 of file utest_types.hpp.
typedef Field<Qty, 135> FIX8::UTEST::OfferSize
Definition at line 643 of file utest_types.hpp.
typedef Field<price, 190> FIX8::UTEST::OfferSpotRate
Definition at line 844 of file utest_types.hpp.
typedef Field<f8String, 115> FIX8::UTEST::OnBehalfOfCompID
Definition at line 589 of file utest_types.hpp.
typedef Field<f8String, 144> FIX8::UTEST::OnBehalfOfLocationID
Definition at line 674 of file utest_types.hpp.
typedef Field<UTCTimestamp, 370> FIX8::UTEST::OnBehalfOfSendingTime
Definition at line 1349 of file utest_types.hpp.
typedef Field<f8String, 116> FIX8::UTEST::OnBehalfOfSubID
Definition at line 591 of file utest_types.hpp.
typedef Field<char, 77> FIX8::UTEST::OpenClose
Definition at line 441 of file utest_types.hpp.
typedef Field<char, 286> FIX8::UTEST::OpenCloseSettleFlag
Definition at line 1058 of file utest_types.hpp.
typedef Field<char, 206> FIX8::UTEST::OptAttribute
Definition at line 888 of file utest_types.hpp.
typedef Field<f8String, 37> FIX8::UTEST::OrderID
Definition at line 260 of file utest_types.hpp.
typedef Field<Qty, 38> FIX8::UTEST::OrderQty
Definition at line 262 of file utest_types.hpp.
typedef Field<Qty, 192> FIX8::UTEST::OrderQty2
Definition at line 848 of file utest_types.hpp.
typedef Field<int, 103> FIX8::UTEST::OrdRejReason
Definition at line 532 of file utest_types.hpp.
typedef Field<char, 39> FIX8::UTEST::OrdStatus
Definition at line 264 of file utest_types.hpp.
typedef Field<char, 40> FIX8::UTEST::OrdType
Definition at line 282 of file utest_types.hpp.
typedef Field<f8String, 41> FIX8::UTEST::OrigClOrdID
Definition at line 304 of file utest_types.hpp.
typedef Field<UTCTimestamp, 122> FIX8::UTEST::OrigSendingTime
Definition at line 606 of file utest_types.hpp.
typedef Field<UTCTimestamp, 42> FIX8::UTEST::OrigTime
Definition at line 306 of file utest_types.hpp.
typedef Field<Amt, 412> FIX8::UTEST::OutMainCntryUIndex
Definition at line 1484 of file utest_types.hpp.
typedef Field<double, 407> FIX8::UTEST::OutsideIndexPct
Definition at line 1466 of file utest_types.hpp.
typedef Field<PriceOffset, 211> FIX8::UTEST::PegDifference
Definition at line 905 of file utest_types.hpp.
typedef Field<Boolean, 43> FIX8::UTEST::PossDupFlag
Definition at line 308 of file utest_types.hpp.
typedef Field<Boolean, 97> FIX8::UTEST::PossResend
Definition at line 506 of file utest_types.hpp.
typedef Field<price, 140> FIX8::UTEST::PrevClosePx
Definition at line 663 of file utest_types.hpp.
typedef Field<price, 44> FIX8::UTEST::Price
Definition at line 313 of file utest_types.hpp.
typedef Field<int, 423> FIX8::UTEST::PriceType
Definition at line 1532 of file utest_types.hpp.
typedef Field<char, 81> FIX8::UTEST::ProcessCode
Definition at line 452 of file utest_types.hpp.
typedef Field<int, 415> FIX8::UTEST::ProgPeriodInterval
Definition at line 1494 of file utest_types.hpp.
typedef Field<int, 414> FIX8::UTEST::ProgRptReqs
Definition at line 1488 of file utest_types.hpp.
typedef Field<int, 201> FIX8::UTEST::PutOrCall
Definition at line 869 of file utest_types.hpp.
typedef Field<int, 297> FIX8::UTEST::QuoteAckStatus
Definition at line 1092 of file utest_types.hpp.
typedef Field<int, 298> FIX8::UTEST::QuoteCancelType
Definition at line 1101 of file utest_types.hpp.
typedef Field<MultipleStringValue, 276> FIX8::UTEST::QuoteCondition
Definition at line 996 of file utest_types.hpp.
typedef Field<f8String, 299> FIX8::UTEST::QuoteEntryID
Definition at line 1108 of file utest_types.hpp.
typedef Field<int, 368> FIX8::UTEST::QuoteEntryRejectReason
Definition at line 1335 of file utest_types.hpp.
typedef Field<f8String, 117> FIX8::UTEST::QuoteID
Definition at line 593 of file utest_types.hpp.
typedef Field<int, 300> FIX8::UTEST::QuoteRejectReason
Definition at line 1110 of file utest_types.hpp.
typedef Field<f8String, 131> FIX8::UTEST::QuoteReqID
Definition at line 635 of file utest_types.hpp.
typedef Field<int, 303> FIX8::UTEST::QuoteRequestType
Definition at line 1130 of file utest_types.hpp.
typedef Field<int, 301> FIX8::UTEST::QuoteResponseLevel
Definition at line 1122 of file utest_types.hpp.
typedef Field<f8String, 302> FIX8::UTEST::QuoteSetID
Definition at line 1128 of file utest_types.hpp.
typedef Field<UTCTimestamp, 367> FIX8::UTEST::QuoteSetValidUntilTime
Definition at line 1333 of file utest_types.hpp.
typedef Field<Qty, 319> FIX8::UTEST::RatioQty
Definition at line 1165 of file utest_types.hpp.
typedef Field<data, 96> FIX8::UTEST::RawData
Definition at line 504 of file utest_types.hpp.
typedef Field<Length, 95> FIX8::UTEST::RawDataLength
Definition at line 502 of file utest_types.hpp.
typedef Field<f8String, 72> FIX8::UTEST::RefAllocID
Definition at line 431 of file utest_types.hpp.
typedef Field<f8String, 372> FIX8::UTEST::RefMsgType
Definition at line 1353 of file utest_types.hpp.
typedef Field<int, 45> FIX8::UTEST::RefSeqNum
Definition at line 315 of file utest_types.hpp.
typedef Field<int, 371> FIX8::UTEST::RefTagID
Definition at line 1351 of file utest_types.hpp.
typedef Field<f8String, 46> FIX8::UTEST::RelatdSym
Definition at line 317 of file utest_types.hpp.
typedef Field<Boolean, 113> FIX8::UTEST::ReportToExch
Definition at line 579 of file utest_types.hpp.
typedef Field<Boolean, 141> FIX8::UTEST::ResetSeqNumFlag
Definition at line 665 of file utest_types.hpp.
typedef Field<f8String, 217> FIX8::UTEST::RoutingID
Definition at line 922 of file utest_types.hpp.
typedef Field<int, 216> FIX8::UTEST::RoutingType
Definition at line 915 of file utest_types.hpp.
typedef Field<int, 83> FIX8::UTEST::RptSeq
Definition at line 464 of file utest_types.hpp.
typedef Field<char, 47> FIX8::UTEST::Rule80A
Definition at line 319 of file utest_types.hpp.
typedef Field<f8String, 9999> FIX8::UTEST::SampleUserField
Definition at line 1609 of file utest_types.hpp.
typedef Field<f8String, 9991> FIX8::UTEST::SampleUserField2
Definition at line 1607 of file utest_types.hpp.
typedef Field<f8String, 198> FIX8::UTEST::SecondaryOrderID
Definition at line 863 of file utest_types.hpp.
typedef Field<data, 91> FIX8::UTEST::SecureData
Definition at line 490 of file utest_types.hpp.
typedef Field<Length, 90> FIX8::UTEST::SecureDataLen
Definition at line 488 of file utest_types.hpp.
typedef Field<f8String, 107> FIX8::UTEST::SecurityDesc
Definition at line 567 of file utest_types.hpp.
typedef Field<Exchange, 207> FIX8::UTEST::SecurityExchange
Definition at line 890 of file utest_types.hpp.
typedef Field<f8String, 48> FIX8::UTEST::SecurityID
Definition at line 345 of file utest_types.hpp.
typedef Field<f8String, 320> FIX8::UTEST::SecurityReqID
Definition at line 1167 of file utest_types.hpp.
typedef Field<int, 321> FIX8::UTEST::SecurityRequestType
Definition at line 1169 of file utest_types.hpp.
typedef Field<f8String, 322> FIX8::UTEST::SecurityResponseID
Definition at line 1176 of file utest_types.hpp.
typedef Field<int, 323> FIX8::UTEST::SecurityResponseType
Definition at line 1178 of file utest_types.hpp.
typedef Field<f8String, 179> FIX8::UTEST::SecuritySettlAgentAcctName
Definition at line 822 of file utest_types.hpp.
typedef Field<f8String, 178> FIX8::UTEST::SecuritySettlAgentAcctNum
Definition at line 820 of file utest_types.hpp.
typedef Field<f8String, 177> FIX8::UTEST::SecuritySettlAgentCode
Definition at line 818 of file utest_types.hpp.
typedef Field<f8String, 180> FIX8::UTEST::SecuritySettlAgentContactName
Definition at line 824 of file utest_types.hpp.
typedef Field<f8String, 181> FIX8::UTEST::SecuritySettlAgentContactPhone
Definition at line 826 of file utest_types.hpp.
typedef Field<f8String, 176> FIX8::UTEST::SecuritySettlAgentName
Definition at line 816 of file utest_types.hpp.
typedef Field<f8String, 324> FIX8::UTEST::SecurityStatusReqID
Definition at line 1187 of file utest_types.hpp.
typedef Field<int, 326> FIX8::UTEST::SecurityTradingStatus
Definition at line 1194 of file utest_types.hpp.
typedef Field<f8String, 167> FIX8::UTEST::SecurityType
Definition at line 759 of file utest_types.hpp.
typedef Field<int, 287> FIX8::UTEST::SellerDays
Definition at line 1064 of file utest_types.hpp.
typedef Field<Qty, 331> FIX8::UTEST::SellVolume
Definition at line 1238 of file utest_types.hpp.
typedef Field<f8String, 49> FIX8::UTEST::SenderCompID
Definition at line 347 of file utest_types.hpp.
typedef Field<f8String, 142> FIX8::UTEST::SenderLocationID
Definition at line 670 of file utest_types.hpp.
typedef Field<f8String, 50> FIX8::UTEST::SenderSubID
Definition at line 349 of file utest_types.hpp.
typedef Field<UTCTimestamp, 52> FIX8::UTEST::SendingTime
Definition at line 351 of file utest_types.hpp.
typedef Field<int, 373> FIX8::UTEST::SessionRejectReason
Definition at line 1355 of file utest_types.hpp.
typedef Field<f8String, 174> FIX8::UTEST::SettlBrkrCode
Definition at line 812 of file utest_types.hpp.
typedef Field<Amt, 119> FIX8::UTEST::SettlCurrAmt
Definition at line 597 of file utest_types.hpp.
typedef Field<currency, 120> FIX8::UTEST::SettlCurrency
Definition at line 599 of file utest_types.hpp.
typedef Field<double, 155> FIX8::UTEST::SettlCurrFxRate
Definition at line 712 of file utest_types.hpp.
typedef Field<char, 156> FIX8::UTEST::SettlCurrFxRateCalc
Definition at line 714 of file utest_types.hpp.
typedef Field<int, 172> FIX8::UTEST::SettlDeliveryType
Definition at line 808 of file utest_types.hpp.
typedef Field<f8String, 173> FIX8::UTEST::SettlDepositoryCode
Definition at line 810 of file utest_types.hpp.
typedef Field<f8String, 175> FIX8::UTEST::SettlInstCode
Definition at line 814 of file utest_types.hpp.
typedef Field<f8String, 162> FIX8::UTEST::SettlInstID
Definition at line 734 of file utest_types.hpp.
typedef Field<char, 160> FIX8::UTEST::SettlInstMode
Definition at line 725 of file utest_types.hpp.
typedef Field<f8String, 214> FIX8::UTEST::SettlInstRefID
Definition at line 911 of file utest_types.hpp.
typedef Field<char, 165> FIX8::UTEST::SettlInstSource
Definition at line 744 of file utest_types.hpp.
typedef Field<char, 163> FIX8::UTEST::SettlInstTransType
Definition at line 736 of file utest_types.hpp.
typedef Field<f8String, 166> FIX8::UTEST::SettlLocation
Definition at line 749 of file utest_types.hpp.
typedef Field<char, 63> FIX8::UTEST::SettlmntTyp
Definition at line 395 of file utest_types.hpp.
typedef Field<Qty, 53> FIX8::UTEST::Shares
Definition at line 353 of file utest_types.hpp.
typedef Field<char, 54> FIX8::UTEST::Side
Definition at line 355 of file utest_types.hpp.
typedef Field<Amt, 396> FIX8::UTEST::SideValue1
Definition at line 1444 of file utest_types.hpp.
typedef Field<Amt, 397> FIX8::UTEST::SideValue2
Definition at line 1446 of file utest_types.hpp.
typedef Field<int, 401> FIX8::UTEST::SideValueInd
Definition at line 1454 of file utest_types.hpp.
typedef Field<data, 89> FIX8::UTEST::Signature
Definition at line 486 of file utest_types.hpp.
typedef Field<Length, 93> FIX8::UTEST::SignatureLength
Definition at line 494 of file utest_types.hpp.
typedef Field<Boolean, 377> FIX8::UTEST::SolicitedFlag
Definition at line 1379 of file utest_types.hpp.
typedef Field<PriceOffset, 218> FIX8::UTEST::SpreadToBenchmark
Definition at line 924 of file utest_types.hpp.
typedef Field<f8String, 171> FIX8::UTEST::StandInstDbID
Definition at line 806 of file utest_types.hpp.
typedef Field<f8String, 170> FIX8::UTEST::StandInstDbName
Definition at line 804 of file utest_types.hpp.
typedef Field<int, 169> FIX8::UTEST::StandInstDbType
Definition at line 797 of file utest_types.hpp.
typedef Field<price, 99> FIX8::UTEST::StopPx
Definition at line 521 of file utest_types.hpp.
typedef Field<price, 202> FIX8::UTEST::StrikePrice
Definition at line 874 of file utest_types.hpp.
typedef Field<UTCTimestamp, 443> FIX8::UTEST::StrikeTime
Definition at line 1593 of file utest_types.hpp.
typedef Field<f8String, 147> FIX8::UTEST::Subject
Definition at line 680 of file utest_types.hpp.
typedef Field<char, 263> FIX8::UTEST::SubscriptionRequestType
Definition at line 944 of file utest_types.hpp.
typedef Field<f8String, 55> FIX8::UTEST::Symbol
Definition at line 367 of file utest_types.hpp.
typedef Field<f8String, 65> FIX8::UTEST::SymbolSfx
Definition at line 410 of file utest_types.hpp.
typedef Field<f8String, 56> FIX8::UTEST::TargetCompID
Definition at line 369 of file utest_types.hpp.
typedef Field<f8String, 143> FIX8::UTEST::TargetLocationID
Definition at line 672 of file utest_types.hpp.
typedef Field<f8String, 57> FIX8::UTEST::TargetSubID
Definition at line 371 of file utest_types.hpp.
typedef Field<f8String, 112> FIX8::UTEST::TestReqID
Definition at line 577 of file utest_types.hpp.
typedef Field<f8String, 58> FIX8::UTEST::Text
Definition at line 373 of file utest_types.hpp.
typedef Field<char, 274> FIX8::UTEST::TickDirection
Definition at line 987 of file utest_types.hpp.
typedef Field<char, 59> FIX8::UTEST::TimeInForce
Definition at line 375 of file utest_types.hpp.
typedef Field<int, 393> FIX8::UTEST::TotalNumSecurities
Definition at line 1438 of file utest_types.hpp.
typedef Field<Qty, 387> FIX8::UTEST::TotalVolumeTraded
Definition at line 1419 of file utest_types.hpp.
typedef Field<UTCDateOnly, 449> FIX8::UTEST::TotalVolumeTradedDate
Definition at line 1601 of file utest_types.hpp.
typedef Field<UTCTimeOnly, 450> FIX8::UTEST::TotalVolumeTradedTime
Definition at line 1603 of file utest_types.hpp.
typedef Field<int, 68> FIX8::UTEST::TotNoOrders
Definition at line 416 of file utest_types.hpp.
typedef Field<int, 422> FIX8::UTEST::TotNoStrikes
Definition at line 1530 of file utest_types.hpp.
typedef Field<int, 304> FIX8::UTEST::TotQuoteEntries
Definition at line 1135 of file utest_types.hpp.
typedef Field<MultipleStringValue, 277> FIX8::UTEST::TradeCondition
Definition at line 1008 of file utest_types.hpp.
typedef Field<LocalMktDate, 75> FIX8::UTEST::TradeDate
Definition at line 437 of file utest_types.hpp.
typedef Field<char, 418> FIX8::UTEST::TradeType
Definition at line 1503 of file utest_types.hpp.
typedef Field<f8String, 336> FIX8::UTEST::TradingSessionID
Definition at line 1252 of file utest_types.hpp.
typedef Field<UTCTimestamp, 344> FIX8::UTEST::TradSesCloseTime
Definition at line 1282 of file utest_types.hpp.
typedef Field<UTCTimestamp, 345> FIX8::UTEST::TradSesEndTime
Definition at line 1284 of file utest_types.hpp.
typedef Field<int, 338> FIX8::UTEST::TradSesMethod
Definition at line 1256 of file utest_types.hpp.
typedef Field<int, 339> FIX8::UTEST::TradSesMode
Definition at line 1262 of file utest_types.hpp.
typedef Field<UTCTimestamp, 342> FIX8::UTEST::TradSesOpenTime
Definition at line 1278 of file utest_types.hpp.
typedef Field<UTCTimestamp, 343> FIX8::UTEST::TradSesPreCloseTime
Definition at line 1280 of file utest_types.hpp.
typedef Field<f8String, 335> FIX8::UTEST::TradSesReqID
Definition at line 1250 of file utest_types.hpp.
typedef Field<UTCTimestamp, 341> FIX8::UTEST::TradSesStartTime
Definition at line 1276 of file utest_types.hpp.
typedef Field<int, 340> FIX8::UTEST::TradSesStatus
Definition at line 1268 of file utest_types.hpp.
typedef Field<UTCTimestamp, 60> FIX8::UTEST::TransactTime
Definition at line 385 of file utest_types.hpp.
typedef Field<double, 436> FIX8::UTEST::UnderlyingContractMultiplier
Definition at line 1575 of file utest_types.hpp.
typedef Field<double, 435> FIX8::UTEST::UnderlyingCouponRate
Definition at line 1573 of file utest_types.hpp.
typedef Field<currency, 318> FIX8::UTEST::UnderlyingCurrency
Definition at line 1163 of file utest_types.hpp.
typedef Field<f8String, 305> FIX8::UTEST::UnderlyingIDSource
Definition at line 1137 of file utest_types.hpp.
typedef Field<f8String, 306> FIX8::UTEST::UnderlyingIssuer
Definition at line 1139 of file utest_types.hpp.
typedef Field<DayOfMonth, 314> FIX8::UTEST::UnderlyingMaturityDay
Definition at line 1155 of file utest_types.hpp.
typedef Field<MonthYear, 313> FIX8::UTEST::UnderlyingMaturityMonthYear
Definition at line 1153 of file utest_types.hpp.
typedef Field<char, 317> FIX8::UTEST::UnderlyingOptAttribute
Definition at line 1161 of file utest_types.hpp.
typedef Field<int, 315> FIX8::UTEST::UnderlyingPutOrCall
Definition at line 1157 of file utest_types.hpp.
typedef Field<f8String, 307> FIX8::UTEST::UnderlyingSecurityDesc
Definition at line 1141 of file utest_types.hpp.
typedef Field<Exchange, 308> FIX8::UTEST::UnderlyingSecurityExchange
Definition at line 1143 of file utest_types.hpp.
typedef Field<f8String, 309> FIX8::UTEST::UnderlyingSecurityID
Definition at line 1145 of file utest_types.hpp.
typedef Field<f8String, 310> FIX8::UTEST::UnderlyingSecurityType
Definition at line 1147 of file utest_types.hpp.
typedef Field<price, 316> FIX8::UTEST::UnderlyingStrikePrice
Definition at line 1159 of file utest_types.hpp.
typedef Field<f8String, 311> FIX8::UTEST::UnderlyingSymbol
Definition at line 1149 of file utest_types.hpp.
typedef Field<f8String, 312> FIX8::UTEST::UnderlyingSymbolSfx
Definition at line 1151 of file utest_types.hpp.
typedef Field<Boolean, 325> FIX8::UTEST::UnsolicitedIndicator
Definition at line 1189 of file utest_types.hpp.
typedef Field<char, 61> FIX8::UTEST::Urgency
Definition at line 387 of file utest_types.hpp.
typedef Field<f8String, 149> FIX8::UTEST::URLLink
Definition at line 684 of file utest_types.hpp.
typedef FieldTable FIX8::UTEST::utest_BaseEntry
Definition at line 1611 of file utest_types.hpp.
typedef MsgTable FIX8::UTEST::utest_BaseMsgEntry
Definition at line 64 of file utest_classes.hpp.
typedef Field<UTCTimestamp, 62> FIX8::UTEST::ValidUntilTime
Definition at line 393 of file utest_types.hpp.
typedef Field<Amt, 408> FIX8::UTEST::ValueOfFutures
Definition at line 1468 of file utest_types.hpp.
typedef Field<f8String, 105> FIX8::UTEST::WaveNo
Definition at line 563 of file utest_types.hpp.
typedef Field<double, 410> FIX8::UTEST::WtAverageLiquidity
Definition at line 1477 of file utest_types.hpp.
typedef Field<data, 213> FIX8::UTEST::XmlData
Definition at line 909 of file utest_types.hpp.
typedef Field<Length, 212> FIX8::UTEST::XmlDataLen
Definition at line 907 of file utest_types.hpp.
Function Documentation
const int FIX8::UTEST::Adjustment_CANCEL (1)
const int FIX8::UTEST::Adjustment_CORRECTION (3)
const int FIX8::UTEST::Adjustment_ERROR (2)
const size_t FIX8::UTEST::Adjustment_realm_els (3)
const char FIX8::UTEST::AdvSide_BUY ('B')
const char FIX8::UTEST::AdvSide_CROSS ('X')
const size_t FIX8::UTEST::AdvSide_realm_els (4)
const char FIX8::UTEST::AdvSide_SELL ('S')
const char FIX8::UTEST::AdvSide_TRADE ('T')
const f8String FIX8::UTEST::AdvTransType_CANCEL ("C")
const f8String FIX8::UTEST::AdvTransType_NEW ("N")
const size_t FIX8::UTEST::AdvTransType_realm_els (3)
const f8String FIX8::UTEST::AdvTransType_REPLACE ("R")
const char FIX8::UTEST::AggregatedBook_NO ('N')
const size_t FIX8::UTEST::AggregatedBook_realm_els (2)
const char FIX8::UTEST::AggregatedBook_YES ('Y')
const int FIX8::UTEST::AllocHandlInst_FORWARD (2)
const int FIX8::UTEST::AllocHandlInst_FORWARD_AND_MATCH (3)
const int FIX8::UTEST::AllocHandlInst_MATCH (1)
const size_t FIX8::UTEST::AllocHandlInst_realm_els (3)
const int FIX8::UTEST::AllocLinkType_F_X_NETTING (0)
const int FIX8::UTEST::AllocLinkType_F_X_SWAP (1)
const size_t FIX8::UTEST::AllocLinkType_realm_els (2)
const int FIX8::UTEST::AllocRejCode_COMMISSION_DIFFERENCE (4)
const int FIX8::UTEST::AllocRejCode_INCORRECT_AVERAGE_PRICE (2)
const int FIX8::UTEST::AllocRejCode_INCORRECT_QUANTITY (1)
const int FIX8::UTEST::AllocRejCode_OTHER (7)
const size_t FIX8::UTEST::AllocRejCode_realm_els (8)
const int FIX8::UTEST::AllocRejCode_UNKNOWN_ACCOUNT (0)
const int FIX8::UTEST::AllocRejCode_UNKNOWN_EXECUTING_BROKER_MNEMONIC (3)
const int FIX8::UTEST::AllocRejCode_UNKNOWN_LISTID (6)
const int FIX8::UTEST::AllocRejCode_UNKNOWN_ORDERID (5)
const int FIX8::UTEST::AllocStatus_ACCEPTED (0)
const int FIX8::UTEST::AllocStatus_PARTIAL_ACCEPT (2)
const size_t FIX8::UTEST::AllocStatus_realm_els (4)
const int FIX8::UTEST::AllocStatus_RECEIVED (3)
const int FIX8::UTEST::AllocStatus_REJECTED (1)
const char FIX8::UTEST::AllocTransType_CALCULATED ('4')
const char FIX8::UTEST::AllocTransType_CALCULATED_WITHOUT_PRELIMINARY ('5')
const char FIX8::UTEST::AllocTransType_CANCEL ('2')
const char FIX8::UTEST::AllocTransType_NEW ('0')
const char FIX8::UTEST::AllocTransType_PRELIMINARY ('3')
const size_t FIX8::UTEST::AllocTransType_realm_els (6)
const char FIX8::UTEST::AllocTransType_REPLACE ('1')
const char FIX8::UTEST::BasisPxType_CLOSING_PRICE ('3')
const char FIX8::UTEST::BasisPxType_CLOSING_PRICE_AT_MORNING_SESSION ('2')
const char FIX8::UTEST::BasisPxType_CURRENT_PRICE ('4')
const char FIX8::UTEST::BasisPxType_OPEN ('D')
const char FIX8::UTEST::BasisPxType_OTHERS ('Z')
const size_t FIX8::UTEST::BasisPxType_realm_els (13)
const char FIX8::UTEST::BasisPxType_SQ ('5')
const char FIX8::UTEST::BasisPxType_STRIKE ('C')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_A_DAY ('6')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_A_DAY_EXCEPT_YORI ('9')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_A_MORNING_SESSION ('7')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI ('A')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION ('8')
const char FIX8::UTEST::BasisPxType_VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI ('B')
const char FIX8::UTEST::Benchmark_10_YR ('4')
const char FIX8::UTEST::Benchmark_30_YR ('6')
const char FIX8::UTEST::Benchmark_3_MO_LIBOR ('8')
const char FIX8::UTEST::Benchmark_5_YR ('2')
const char FIX8::UTEST::Benchmark_6_MO_LIBOR ('9')
const char FIX8::UTEST::Benchmark_CURVE ('1')
const char FIX8::UTEST::Benchmark_OLD_10 ('5')
const char FIX8::UTEST::Benchmark_OLD_30 ('7')
const char FIX8::UTEST::Benchmark_OLD_5 ('3')
const size_t FIX8::UTEST::Benchmark_realm_els (9)
const char FIX8::UTEST::BidRequestTransType_CANCEL ('C')
const char FIX8::UTEST::BidRequestTransType_NO ('N')
const size_t FIX8::UTEST::BidRequestTransType_realm_els (2)
const int FIX8::UTEST::BusinessRejectReason_APPLICATION_NOT_AVAILABLE (4)
const int FIX8::UTEST::BusinessRejectReason_CONDITIONALLY_REQUIRED_FIELD_MISSING (5)
const int FIX8::UTEST::BusinessRejectReason_OTHER (0)
const size_t FIX8::UTEST::BusinessRejectReason_realm_els (6)
const int FIX8::UTEST::BusinessRejectReason_UNKNOWN_SECURITY (2)
const int FIX8::UTEST::BusinessRejectReason_UNKOWN_ID (1)
const int FIX8::UTEST::BusinessRejectReason_UNSUPPORTED_MESSAGE_TYPE (3)
const char FIX8::UTEST::CommType_ABSOLUTE ('3')
const char FIX8::UTEST::CommType_PER_SHARE ('1')
const char FIX8::UTEST::CommType_PERCENTAGE ('2')
const size_t FIX8::UTEST::CommType_realm_els (3)
const char FIX8::UTEST::CorporateAction_EX_DISTRIBUTION ('B')
const char FIX8::UTEST::CorporateAction_EX_DIVIDEND ('A')
const char FIX8::UTEST::CorporateAction_EX_INTEREST ('E')
const char FIX8::UTEST::CorporateAction_EX_RIGHTS ('C')
const char FIX8::UTEST::CorporateAction_NEW ('D')
const size_t FIX8::UTEST::CorporateAction_realm_els (5)
const int FIX8::UTEST::CoveredOrUncovered_COVERED (0)
const size_t FIX8::UTEST::CoveredOrUncovered_realm_els (2)
const int FIX8::UTEST::CoveredOrUncovered_UNCOVERED (1)
const F8MetaCntx & FIX8::UTEST::ctx ()
Compiler generated metadata object, accessed through this function.
Definition at line 156 of file utest_classes.cpp.
References fldpairs, and msgpairs.
Referenced by FIX8::UTEST::IndicationofInterest::NoIOIQualifiers::create_group(), FIX8::UTEST::IndicationofInterest::NoRoutingIDs::create_group(), FIX8::UTEST::ExecutionReport::NoContraBrokers::create_group(), FIX8::UTEST::Logon::NoMsgTypes::create_group(), FIX8::UTEST::News::LinesOfText::create_group(), FIX8::UTEST::News::NoRelatedSym::create_group(), FIX8::UTEST::News::NoRoutingIDs::create_group(), FIX8::UTEST::Email::LinesOfText::create_group(), FIX8::UTEST::Email::NoRelatedSym::create_group(), FIX8::UTEST::Email::NoRoutingIDs::create_group(), FIX8::UTEST::NewOrderSingle::NoAllocs::create_group(), FIX8::UTEST::NewOrderSingle::NoTradingSessions::create_group(), FIX8::UTEST::NewOrderList::NoOrders::create_group(), FIX8::UTEST::NewOrderList::NoOrders::NoAllocs::create_group(), FIX8::UTEST::NewOrderList::NoOrders::NoTradingSessions::create_group(), FIX8::UTEST::OrderCancelReplaceRequest::NoAllocs::create_group(), FIX8::UTEST::OrderCancelReplaceRequest::NoTradingSessions::create_group(), FIX8::UTEST::Allocation::NoOrders::create_group(), FIX8::UTEST::Allocation::NoAllocs::create_group(), FIX8::UTEST::Allocation::NoAllocs::NoMiscFees::create_group(), FIX8::UTEST::Allocation::NoExecs::create_group(), FIX8::UTEST::ListStatus::NoOrders::create_group(), FIX8::UTEST::QuoteRequest::NoRelatedSym::create_group(), FIX8::UTEST::MarketDataRequest::NoRelatedSym::create_group(), FIX8::UTEST::MarketDataRequest::NoMDEntryTypes::create_group(), FIX8::UTEST::MarketDataSnapshotFullRefresh::NoMDEntries::create_group(), FIX8::UTEST::MarketDataIncrementalRefresh::NoMDEntries::create_group(), FIX8::UTEST::QuoteCancel::NoQuoteEntries::create_group(), FIX8::UTEST::QuoteAcknowledgement::NoQuoteSets::create_group(), FIX8::UTEST::QuoteAcknowledgement::NoQuoteSets::NoQuoteEntries::create_group(), FIX8::UTEST::SecurityDefinitionRequest::NoRelatedSym::create_group(), FIX8::UTEST::SecurityDefinition::NoRelatedSym::create_group(), FIX8::UTEST::MassQuote::NoQuoteSets::create_group(), FIX8::UTEST::MassQuote::NoQuoteSets::NoQuoteEntries::create_group(), FIX8::UTEST::BidRequest::NoBidDescriptors::create_group(), FIX8::UTEST::BidRequest::NoBidComponents::create_group(), FIX8::UTEST::BidResponse::NoBidComponents::create_group(), FIX8::UTEST::ListStrikePrice::NoStrikes::create_group(), and TEST().
const int FIX8::UTEST::CustomerOrFirm_CUSTOMER (0)
const int FIX8::UTEST::CustomerOrFirm_FIRM (1)
const size_t FIX8::UTEST::CustomerOrFirm_realm_els (2)
const int FIX8::UTEST::CxlRejReason_BROKER_OPTION (2)
const int FIX8::UTEST::CxlRejReason_ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS (3)
const size_t FIX8::UTEST::CxlRejReason_realm_els (4)
const int FIX8::UTEST::CxlRejReason_TOO_LATE_TO_CANCEL (0)
const int FIX8::UTEST::CxlRejReason_UNKNOWN_ORDER (1)
const char FIX8::UTEST::CxlRejResponseTo_ORDER_CANCEL_REPLACE_REQUEST ('2')
const char FIX8::UTEST::CxlRejResponseTo_ORDER_CANCEL_REQUEST ('1')
const size_t FIX8::UTEST::CxlRejResponseTo_realm_els (2)
const char FIX8::UTEST::DeleteReason_CANCELATION ('0')
const char FIX8::UTEST::DeleteReason_ERROR ('1')
const size_t FIX8::UTEST::DeleteReason_realm_els (2)
const size_t FIX8::UTEST::DiscretionInst_realm_els (6)
const char FIX8::UTEST::DiscretionInst_RELATED_TO_DISPLAYED_PRICE ('0')
const char FIX8::UTEST::DiscretionInst_RELATED_TO_LAST_TRADE_PRICE ('5')
const char FIX8::UTEST::DiscretionInst_RELATED_TO_LOCAL_PRIMARY_PRICE ('3')
const char FIX8::UTEST::DiscretionInst_RELATED_TO_MARKET_PRICE ('1')
const char FIX8::UTEST::DiscretionInst_RELATED_TO_MIDPOINT_PRICE ('4')
const char FIX8::UTEST::DiscretionInst_RELATED_TO_PRIMARY_PRICE ('2')
const char FIX8::UTEST::DKReason_NO_MATCHING_ORDER ('D')
const char FIX8::UTEST::DKReason_OTHER ('Z')
const char FIX8::UTEST::DKReason_PRICE_EXCEEDS_LIMIT ('E')
const char FIX8::UTEST::DKReason_QUANTITY_EXCEEDS_ORDER ('C')
const size_t FIX8::UTEST::DKReason_realm_els (6)
const char FIX8::UTEST::DKReason_UNKNOWN_SYMBOL ('A')
const char FIX8::UTEST::DKReason_WRONG_SIDE ('B')
const char FIX8::UTEST::DueToRelated_NO ('N')
const size_t FIX8::UTEST::DueToRelated_realm_els (2)
const char FIX8::UTEST::DueToRelated_YES ('Y')
const char FIX8::UTEST::EmailType_ADMIN_REPLY ('2')
const char FIX8::UTEST::EmailType_NEW ('0')
const size_t FIX8::UTEST::EmailType_realm_els (3)
const char FIX8::UTEST::EmailType_REPLY ('1')
const int FIX8::UTEST::EncryptMethod_DES (2)
const int FIX8::UTEST::EncryptMethod_NONE (0)
const int FIX8::UTEST::EncryptMethod_PEM_DES_MD5 (6)
const int FIX8::UTEST::EncryptMethod_PGP_DES (4)
const int FIX8::UTEST::EncryptMethod_PGP_DES_MD5 (5)
const int FIX8::UTEST::EncryptMethod_PKCS (1)
const int FIX8::UTEST::EncryptMethod_PKCS_DES (3)
const size_t FIX8::UTEST::EncryptMethod_realm_els (7)
const char FIX8::UTEST::ExchangeForPhysical_NO ('N')
const size_t FIX8::UTEST::ExchangeForPhysical_realm_els (2)
const char FIX8::UTEST::ExchangeForPhysical_YES ('Y')
const f8String FIX8::UTEST::ExecInst_ALL_OR_NONE ("G")
const f8String FIX8::UTEST::ExecInst_CALL_FIRST ("C")
const f8String FIX8::UTEST::ExecInst_CUSTOMER_DISPLAY_INSTRUCTION ("U")
const f8String FIX8::UTEST::ExecInst_DO_NOT_INCREASE ("E")
const f8String FIX8::UTEST::ExecInst_DO_NOT_REDUCE ("F")
const f8String FIX8::UTEST::ExecInst_FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER ("T")
const f8String FIX8::UTEST::ExecInst_GO_ALONG ("3")
const f8String FIX8::UTEST::ExecInst_HELD ("5")
const f8String FIX8::UTEST::ExecInst_INSTITUTIONS_ONLY ("I")
const f8String FIX8::UTEST::ExecInst_LAST_PEG ("L")
const f8String FIX8::UTEST::ExecInst_MARKET_PEG ("P")
const f8String FIX8::UTEST::ExecInst_MID_PRICE_PEG ("M")
const f8String FIX8::UTEST::ExecInst_NETTING ("V")
const f8String FIX8::UTEST::ExecInst_NO_CROSS ("A")
const f8String FIX8::UTEST::ExecInst_NON_NEGOTIABLE ("N")
const f8String FIX8::UTEST::ExecInst_NOT_HELD ("1")
const f8String FIX8::UTEST::ExecInst_OK_TO_CROSS ("B")
const f8String FIX8::UTEST::ExecInst_OPENING_PEG ("O")
const f8String FIX8::UTEST::ExecInst_OVER_THE_DAY ("4")
const f8String FIX8::UTEST::ExecInst_PARTICIPATE_DONT_INITIATE ("6")
const f8String FIX8::UTEST::ExecInst_PEG_TO_VWAP ("W")
const f8String FIX8::UTEST::ExecInst_PERCENT_OF_VOLUME ("D")
const f8String FIX8::UTEST::ExecInst_PRIMARY_PEG ("R")
const size_t FIX8::UTEST::ExecInst_realm_els (29)
const f8String FIX8::UTEST::ExecInst_STAY_ON_BIDSIDE ("9")
const f8String FIX8::UTEST::ExecInst_STAY_ON_OFFERSIDE ("0")
const f8String FIX8::UTEST::ExecInst_STRICT_SCALE ("7")
const f8String FIX8::UTEST::ExecInst_SUSPEND ("S")
const f8String FIX8::UTEST::ExecInst_TRY_TO_SCALE ("8")
const f8String FIX8::UTEST::ExecInst_WORK ("2")
const int FIX8::UTEST::ExecRestatementReason_BROKER_OPTION (4)
const int FIX8::UTEST::ExecRestatementReason_GT_CORPORATE_ACTION (0)
const int FIX8::UTEST::ExecRestatementReason_GT_RENEWAL (1)
const int FIX8::UTEST::ExecRestatementReason_PARTIAL_DECLINE_OF_ORDERQTY (5)
const size_t FIX8::UTEST::ExecRestatementReason_realm_els (6)
const int FIX8::UTEST::ExecRestatementReason_REPRICING_OF_ORDER (3)
const int FIX8::UTEST::ExecRestatementReason_VERBAL_CHANGE (2)
const char FIX8::UTEST::ExecTransType_CANCEL ('1')
const char FIX8::UTEST::ExecTransType_CORRECT ('2')
const char FIX8::UTEST::ExecTransType_NEW ('0')
const size_t FIX8::UTEST::ExecTransType_realm_els (4)
const char FIX8::UTEST::ExecTransType_STATUS ('3')
const char FIX8::UTEST::ExecType_CALCULATED ('B')
const char FIX8::UTEST::ExecType_CANCELED ('4')
const char FIX8::UTEST::ExecType_DONE_FOR_DAY ('3')
const char FIX8::UTEST::ExecType_EXPIRED ('C')
const char FIX8::UTEST::ExecType_FILL ('2')
const char FIX8::UTEST::ExecType_NEW ('0')
const char FIX8::UTEST::ExecType_PARTIAL_FILL ('1')
const char FIX8::UTEST::ExecType_PENDING_CANCEL ('6')
const char FIX8::UTEST::ExecType_PENDING_NEW ('A')
const char FIX8::UTEST::ExecType_PENDING_REPLACE ('E')
const size_t FIX8::UTEST::ExecType_realm_els (15)
const char FIX8::UTEST::ExecType_REJECTED ('8')
const char FIX8::UTEST::ExecType_REPLACE ('5')
const char FIX8::UTEST::ExecType_RESTATED ('D')
const char FIX8::UTEST::ExecType_STOPPED ('7')
const char FIX8::UTEST::ExecType_SUSPENDED ('9')
const char FIX8::UTEST::FinancialStatus_BANKRUPT ('1')
const size_t FIX8::UTEST::FinancialStatus_realm_els (1)
const char FIX8::UTEST::ForexReq_NO ('N')
const size_t FIX8::UTEST::ForexReq_realm_els (2)
const char FIX8::UTEST::ForexReq_YES ('Y')
const char FIX8::UTEST::GapFillFlag_NO ('N')
const size_t FIX8::UTEST::GapFillFlag_realm_els (2)
const char FIX8::UTEST::GapFillFlag_YES ('Y')
const int FIX8::UTEST::GTBookingInst_ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES (1)
const int FIX8::UTEST::GTBookingInst_ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE (2)
const int FIX8::UTEST::GTBookingInst_BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION (0)
const size_t FIX8::UTEST::GTBookingInst_realm_els (3)
const char FIX8::UTEST::HaltReasonChar_ADDITIONAL_INFORMATION ('M')
const char FIX8::UTEST::HaltReasonChar_EQUIPMENT_CHANGEOVER ('X')
const char FIX8::UTEST::HaltReasonChar_NEWS_DISSEMINATION ('D')
const char FIX8::UTEST::HaltReasonChar_NEWS_PENDING ('P')
const char FIX8::UTEST::HaltReasonChar_ORDER_IMBALANCE ('I')
const char FIX8::UTEST::HaltReasonChar_ORDER_INFLUX ('E')
const size_t FIX8::UTEST::HaltReasonChar_realm_els (6)
const char FIX8::UTEST::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION ('1')
const char FIX8::UTEST::HandlInst_AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK ('2')
const char FIX8::UTEST::HandlInst_MANUAL_ORDER_BEST_EXECUTION ('3')
const size_t FIX8::UTEST::HandlInst_realm_els (3)
const f8String FIX8::UTEST::IDSource_CONSOLIDATED_TAPE_ASSOCIATION ("9")
const f8String FIX8::UTEST::IDSource_CUSIP ("1")
const f8String FIX8::UTEST::IDSource_EXCHANGE_SYMBOL ("8")
const f8String FIX8::UTEST::IDSource_ISIN_NUMBER ("4")
const f8String FIX8::UTEST::IDSource_ISO_COUNTRY_CODE ("7")
const f8String FIX8::UTEST::IDSource_ISO_CURRENCY_CODE ("6")
const f8String FIX8::UTEST::IDSource_QUIK ("3")
const size_t FIX8::UTEST::IDSource_realm_els (9)
const f8String FIX8::UTEST::IDSource_RIC_CODE ("5")
const f8String FIX8::UTEST::IDSource_SEDOL ("2")
const int FIX8::UTEST::IncTaxInd_GROSS (2)
const int FIX8::UTEST::IncTaxInd_NET (1)
const size_t FIX8::UTEST::IncTaxInd_realm_els (2)
const char FIX8::UTEST::InViewOfCommon_NO ('N')
const size_t FIX8::UTEST::InViewOfCommon_realm_els (2)
const char FIX8::UTEST::InViewOfCommon_YES ('Y')
const char FIX8::UTEST::IOINaturalFlag_NO ('N')
const size_t FIX8::UTEST::IOINaturalFlag_realm_els (2)
const char FIX8::UTEST::IOINaturalFlag_YES ('Y')
const char FIX8::UTEST::IOIQltyInd_HIGH ('H')
const char FIX8::UTEST::IOIQltyInd_LOW ('L')
const char FIX8::UTEST::IOIQltyInd_MEDIUM ('M')
const size_t FIX8::UTEST::IOIQltyInd_realm_els (3)
const char FIX8::UTEST::IOIQualifier_ALL_OR_NONE ('A')
const char FIX8::UTEST::IOIQualifier_AT_THE_CLOSE ('C')
const char FIX8::UTEST::IOIQualifier_AT_THE_MARKET ('Q')
const char FIX8::UTEST::IOIQualifier_AT_THE_MIDPOINT ('Y')
const char FIX8::UTEST::IOIQualifier_AT_THE_OPEN ('O')
const char FIX8::UTEST::IOIQualifier_CROSSING_OPPORTUNITY ('X')
const char FIX8::UTEST::IOIQualifier_IN_TOUCH_WITH ('I')
const char FIX8::UTEST::IOIQualifier_INDICATION ('W')
const char FIX8::UTEST::IOIQualifier_LIMIT ('L')
const char FIX8::UTEST::IOIQualifier_MORE_BEHIND ('M')
const char FIX8::UTEST::IOIQualifier_PORTFOLIO_SHOW_N ('S')
const char FIX8::UTEST::IOIQualifier_PRE_OPEN ('Z')
const char FIX8::UTEST::IOIQualifier_READY_TO_TRADE ('R')
const size_t FIX8::UTEST::IOIQualifier_realm_els (16)
const char FIX8::UTEST::IOIQualifier_TAKING_A_POSITION ('P')
const char FIX8::UTEST::IOIQualifier_THROUGH_THE_DAY ('T')
const char FIX8::UTEST::IOIQualifier_VERSUS ('V')
const f8String FIX8::UTEST::IOIShares_LARGE ("L")
const f8String FIX8::UTEST::IOIShares_MEDIUM ("M")
const size_t FIX8::UTEST::IOIShares_realm_els (3)
const f8String FIX8::UTEST::IOIShares_SMALL ("S")
const char FIX8::UTEST::IOITransType_CANCEL ('C')
const char FIX8::UTEST::IOITransType_NEW ('N')
const size_t FIX8::UTEST::IOITransType_realm_els (3)
const char FIX8::UTEST::IOITransType_REPLACE ('R')
const char FIX8::UTEST::LastCapacity_AGENT ('1')
const char FIX8::UTEST::LastCapacity_CROSS_AS_AGENT ('2')
const char FIX8::UTEST::LastCapacity_CROSS_AS_PRINCIPAL ('3')
const char FIX8::UTEST::LastCapacity_PRINCIPAL ('4')
const size_t FIX8::UTEST::LastCapacity_realm_els (4)
const int FIX8::UTEST::LiquidityIndType_20_DAY_MOVING_AVERAGE (2)
const int FIX8::UTEST::LiquidityIndType_5_DAY_MOVING_AVERAGE (1)
const int FIX8::UTEST::LiquidityIndType_NORMAL_MARKET_SIZE (3)
const int FIX8::UTEST::LiquidityIndType_OTHER (4)
const size_t FIX8::UTEST::LiquidityIndType_realm_els (4)
const char FIX8::UTEST::ListExecInstType_IMMEDIATE ('1')
const size_t FIX8::UTEST::ListExecInstType_realm_els (2)
const char FIX8::UTEST::ListExecInstType_WAIT_FOR_EXECUTE_INSTRUCTION ('2')
const char FIX8::UTEST::LocateReqd_NO ('N')
const size_t FIX8::UTEST::LocateReqd_realm_els (2)
const char FIX8::UTEST::LocateReqd_YES ('Y')
const char FIX8::UTEST::MDEntryType_BID ('0')
const char FIX8::UTEST::MDEntryType_CLOSING_PRICE ('5')
const char FIX8::UTEST::MDEntryType_INDEX_VALUE ('3')
const char FIX8::UTEST::MDEntryType_OFFER ('1')
const char FIX8::UTEST::MDEntryType_OPENING_PRICE ('4')
const size_t FIX8::UTEST::MDEntryType_realm_els (10)
const char FIX8::UTEST::MDEntryType_SETTLEMENT_PRICE ('6')
const char FIX8::UTEST::MDEntryType_TRADE ('2')
const char FIX8::UTEST::MDEntryType_TRADING_SESSION_HIGH_PRICE ('7')
const char FIX8::UTEST::MDEntryType_TRADING_SESSION_LOW_PRICE ('8')
const char FIX8::UTEST::MDEntryType_TRADING_SESSION_VWAP_PRICE ('9')
const char FIX8::UTEST::MDReqRejReason_DUPLICATE_MDREQID ('1')
const char FIX8::UTEST::MDReqRejReason_INSUFFICIENT_BANDWIDTH ('2')
const char FIX8::UTEST::MDReqRejReason_INSUFFICIENT_PERMISSIONS ('3')
const size_t FIX8::UTEST::MDReqRejReason_realm_els (9)
const char FIX8::UTEST::MDReqRejReason_UNKNOWN_SYMBOL ('0')
const char FIX8::UTEST::MDReqRejReason_UNSUPPORTED_AGGREGATEDBOOK ('7')
const char FIX8::UTEST::MDReqRejReason_UNSUPPORTED_MARKETDEPTH ('5')
const char FIX8::UTEST::MDReqRejReason_UNSUPPORTED_MDENTRYTYPE ('8')
const char FIX8::UTEST::MDReqRejReason_UNSUPPORTED_MDUPDATETYPE ('6')
const char FIX8::UTEST::MDReqRejReason_UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE ('4')
const char FIX8::UTEST::MDUpdateAction_CHANGE ('1')
const char FIX8::UTEST::MDUpdateAction_DELETE ('2')
const char FIX8::UTEST::MDUpdateAction_NEW ('0')
const size_t FIX8::UTEST::MDUpdateAction_realm_els (3)
const int FIX8::UTEST::MDUpdateType_FULL_REFRESH (0)
const int FIX8::UTEST::MDUpdateType_INCREMENTAL_REFRESH (1)
const size_t FIX8::UTEST::MDUpdateType_realm_els (2)
const f8String FIX8::UTEST::MessageEncoding_EUC_JP ("EUC-JP")
const f8String FIX8::UTEST::MessageEncoding_ISO_2022_JP ("ISO-2022-JP")
const size_t FIX8::UTEST::MessageEncoding_realm_els (4)
const f8String FIX8::UTEST::MessageEncoding_SHIFT_JIS ("SHIFT_JIS")
const f8String FIX8::UTEST::MessageEncoding_UTF_8 ("UTF-8")
const char FIX8::UTEST::MiscFeeType_CONSUMPTION_TAX ('9')
const char FIX8::UTEST::MiscFeeType_EXCHANGE_FEES ('4')
const char FIX8::UTEST::MiscFeeType_LEVY ('6')
const char FIX8::UTEST::MiscFeeType_LOCAL_COMMISSION ('3')
const char FIX8::UTEST::MiscFeeType_MARKUP ('8')
const char FIX8::UTEST::MiscFeeType_OTHER ('7')
const size_t FIX8::UTEST::MiscFeeType_realm_els (9)
const char FIX8::UTEST::MiscFeeType_REGULATORY ('1')
const char FIX8::UTEST::MiscFeeType_STAMP ('5')
const char FIX8::UTEST::MiscFeeType_TAX ('2')
const size_t FIX8::UTEST::MsgDirection_realm_els (2)
const char FIX8::UTEST::MsgDirection_RECEIVE ('R')
const char FIX8::UTEST::MsgDirection_SEND ('S')
const f8String FIX8::UTEST::MsgType_ADVERTISEMENT ("7")
const f8String FIX8::UTEST::MsgType_ALLOCATION ("J")
const f8String FIX8::UTEST::MsgType_ALLOCATION_ACK ("P")
const f8String FIX8::UTEST::MsgType_BID_REQUEST ("k")
const f8String FIX8::UTEST::MsgType_BID_RESPONSE ("l")
const f8String FIX8::UTEST::MsgType_BUSINESS_MESSAGE_REJECT ("j")
const f8String FIX8::UTEST::MsgType_DONT_KNOW_TRADE ("Q")
const f8String FIX8::UTEST::MsgType_EMAIL ("C")
const f8String FIX8::UTEST::MsgType_EXECUTION_REPORT ("8")
const f8String FIX8::UTEST::MsgType_HEARTBEAT ("0")
const f8String FIX8::UTEST::MsgType_INDICATION_OF_INTEREST ("6")
const f8String FIX8::UTEST::MsgType_LIST_CANCEL_REQUEST ("K")
const f8String FIX8::UTEST::MsgType_LIST_EXECUTE ("L")
const f8String FIX8::UTEST::MsgType_LIST_STATUS ("N")
const f8String FIX8::UTEST::MsgType_LIST_STATUS_REQUEST ("M")
const f8String FIX8::UTEST::MsgType_LIST_STRIKE_PRICE ("m")
const f8String FIX8::UTEST::MsgType_LOGON ("A")
const f8String FIX8::UTEST::MsgType_LOGOUT ("5")
const f8String FIX8::UTEST::MsgType_MARKET_DATA_INCREMENTAL_REFRESH ("X")
const f8String FIX8::UTEST::MsgType_MARKET_DATA_REQUEST ("V")
const f8String FIX8::UTEST::MsgType_MARKET_DATA_REQUEST_REJECT ("Y")
const f8String FIX8::UTEST::MsgType_MARKET_DATA_SNAPSHOT_FULL_REFRESH ("W")
const f8String FIX8::UTEST::MsgType_MASS_QUOTE ("i")
const f8String FIX8::UTEST::MsgType_NEWS ("B")
const f8String FIX8::UTEST::MsgType_ORDER_CANCEL_REJECT ("9")
const f8String FIX8::UTEST::MsgType_ORDER_CANCEL_REPLACE_REQUEST ("G")
const f8String FIX8::UTEST::MsgType_ORDER_CANCEL_REQUEST ("F")
const f8String FIX8::UTEST::MsgType_ORDER_LIST ("E")
const f8String FIX8::UTEST::MsgType_ORDER_SINGLE ("D")
const f8String FIX8::UTEST::MsgType_ORDER_STATUS_REQUEST ("H")
const f8String FIX8::UTEST::MsgType_QUOTE ("S")
const f8String FIX8::UTEST::MsgType_QUOTE_ACKNOWLEDGEMENT ("b")
const f8String FIX8::UTEST::MsgType_QUOTE_CANCEL ("Z")
const f8String FIX8::UTEST::MsgType_QUOTE_REQUEST ("R")
const f8String FIX8::UTEST::MsgType_QUOTE_STATUS_REQUEST ("a")
const size_t FIX8::UTEST::MsgType_realm_els (46)
const f8String FIX8::UTEST::MsgType_REJECT ("3")
const f8String FIX8::UTEST::MsgType_RESEND_REQUEST ("2")
const f8String FIX8::UTEST::MsgType_SECURITY_DEFINITION ("d")
const f8String FIX8::UTEST::MsgType_SECURITY_DEFINITION_REQUEST ("c")
const f8String FIX8::UTEST::MsgType_SECURITY_STATUS ("f")
const f8String FIX8::UTEST::MsgType_SECURITY_STATUS_REQUEST ("e")
const f8String FIX8::UTEST::MsgType_SEQUENCE_RESET ("4")
const f8String FIX8::UTEST::MsgType_SETTLEMENT_INSTRUCTIONS ("T")
const f8String FIX8::UTEST::MsgType_TEST_REQUEST ("1")
const f8String FIX8::UTEST::MsgType_TRADING_SESSION_STATUS ("h")
const f8String FIX8::UTEST::MsgType_TRADING_SESSION_STATUS_REQUEST ("g")
const char FIX8::UTEST::MultiLegReportingType_INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY ('2')
const char FIX8::UTEST::MultiLegReportingType_MULTI_LEG_SECURITY ('3')
const size_t FIX8::UTEST::MultiLegReportingType_realm_els (3)
const char FIX8::UTEST::MultiLegReportingType_SINGLE_SECURITY ('1')
const int FIX8::UTEST::NetGrossInd_GROSS (2)
const int FIX8::UTEST::NetGrossInd_NET (1)
const size_t FIX8::UTEST::NetGrossInd_realm_els (2)
const char FIX8::UTEST::NotifyBrokerOfCredit_NO ('N')
const size_t FIX8::UTEST::NotifyBrokerOfCredit_realm_els (2)
const char FIX8::UTEST::NotifyBrokerOfCredit_YES ('Y')
const char FIX8::UTEST::OpenClose_CLOSE ('C')
const char FIX8::UTEST::OpenClose_OPEN ('O')
const size_t FIX8::UTEST::OpenClose_realm_els (2)
const char FIX8::UTEST::OpenCloseSettleFlag_DAILY_OPEN ('0')
const char FIX8::UTEST::OpenCloseSettleFlag_DELIVERY_SETTLEMENT_PRICE ('2')
const size_t FIX8::UTEST::OpenCloseSettleFlag_realm_els (3)
const char FIX8::UTEST::OpenCloseSettleFlag_SESSION_OPEN ('1')
const int FIX8::UTEST::OrdRejReason_BROKER_OPTION (0)
const int FIX8::UTEST::OrdRejReason_DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER (7)
const int FIX8::UTEST::OrdRejReason_DUPLICATE_ORDER (6)
const int FIX8::UTEST::OrdRejReason_EXCHANGE_CLOSED (2)
const int FIX8::UTEST::OrdRejReason_ORDER_EXCEEDS_LIMIT (3)
const size_t FIX8::UTEST::OrdRejReason_realm_els (9)
const int FIX8::UTEST::OrdRejReason_STALE_ORDER (8)
const int FIX8::UTEST::OrdRejReason_TOO_LATE_TO_ENTER (4)
const int FIX8::UTEST::OrdRejReason_UNKNOWN_ORDER (5)
const int FIX8::UTEST::OrdRejReason_UNKNOWN_SYMBOL (1)
const char FIX8::UTEST::OrdStatus_ACCEPTED_FOR_BIDDING ('D')
const char FIX8::UTEST::OrdStatus_CALCULATED ('B')
const char FIX8::UTEST::OrdStatus_CANCELED ('4')
const char FIX8::UTEST::OrdStatus_DONE_FOR_DAY ('3')
const char FIX8::UTEST::OrdStatus_EXPIRED ('C')
const char FIX8::UTEST::OrdStatus_FILLED ('2')
const char FIX8::UTEST::OrdStatus_NEW ('0')
const char FIX8::UTEST::OrdStatus_PARTIALLY_FILLED ('1')
const char FIX8::UTEST::OrdStatus_PENDING_CANCEL ('6')
const char FIX8::UTEST::OrdStatus_PENDING_NEW ('A')
const char FIX8::UTEST::OrdStatus_PENDING_REPLACE ('E')
const size_t FIX8::UTEST::OrdStatus_realm_els (15)
const char FIX8::UTEST::OrdStatus_REJECTED ('8')
const char FIX8::UTEST::OrdStatus_REPLACED ('5')
const char FIX8::UTEST::OrdStatus_STOPPED ('7')
const char FIX8::UTEST::OrdStatus_SUSPENDED ('9')
const char FIX8::UTEST::OrdType_FOREX_C ('C')
const char FIX8::UTEST::OrdType_FOREX_F ('F')
const char FIX8::UTEST::OrdType_FOREX_G ('G')
const char FIX8::UTEST::OrdType_FOREX_H ('H')
const char FIX8::UTEST::OrdType_FUNARI ('I')
const char FIX8::UTEST::OrdType_LIMIT ('2')
const char FIX8::UTEST::OrdType_LIMIT_ON_CLOSE ('B')
const char FIX8::UTEST::OrdType_LIMIT_OR_BETTER ('7')
const char FIX8::UTEST::OrdType_LIMIT_WITH_OR_WITHOUT ('8')
const char FIX8::UTEST::OrdType_MARKET ('1')
const char FIX8::UTEST::OrdType_MARKET_ON_CLOSE ('5')
const char FIX8::UTEST::OrdType_ON_BASIS ('9')
const char FIX8::UTEST::OrdType_ON_CLOSE ('A')
const char FIX8::UTEST::OrdType_PEGGED ('P')
const char FIX8::UTEST::OrdType_PREVIOUSLY_INDICATED ('E')
const char FIX8::UTEST::OrdType_PREVIOUSLY_QUOTED ('D')
const size_t FIX8::UTEST::OrdType_realm_els (19)
const char FIX8::UTEST::OrdType_STOP ('3')
const char FIX8::UTEST::OrdType_STOP_LIMIT ('4')
const char FIX8::UTEST::OrdType_WITH_OR_WITHOUT ('6')
const char FIX8::UTEST::PossDupFlag_NO ('N')
const size_t FIX8::UTEST::PossDupFlag_realm_els (2)
const char FIX8::UTEST::PossDupFlag_YES ('Y')
const char FIX8::UTEST::PossResend_NO ('N')
const size_t FIX8::UTEST::PossResend_realm_els (2)
const char FIX8::UTEST::PossResend_YES ('Y')
const int FIX8::UTEST::PriceType_FIXED_AMOUNT (3)
const int FIX8::UTEST::PriceType_PER_SHARE (2)
const int FIX8::UTEST::PriceType_PERCENTAGE (1)
const size_t FIX8::UTEST::PriceType_realm_els (3)
const char FIX8::UTEST::ProcessCode_PLAN_SPONSOR ('6')
const size_t FIX8::UTEST::ProcessCode_realm_els (7)
const char FIX8::UTEST::ProcessCode_REGULAR ('0')
const char FIX8::UTEST::ProcessCode_SOFT_DOLLAR ('1')
const char FIX8::UTEST::ProcessCode_SOFT_DOLLAR_STEP_IN ('4')
const char FIX8::UTEST::ProcessCode_SOFT_DOLLAR_STEP_OUT ('5')
const char FIX8::UTEST::ProcessCode_STEP_IN ('2')
const char FIX8::UTEST::ProcessCode_STEP_OUT ('3')
const int FIX8::UTEST::ProgRptReqs_BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST (1)
const int FIX8::UTEST::ProgRptReqs_REAL_TIME_EXECUTION_REPORTS (3)
const size_t FIX8::UTEST::ProgRptReqs_realm_els (3)
const int FIX8::UTEST::ProgRptReqs_SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD (2)
const int FIX8::UTEST::PutOrCall_CALL (1)
const int FIX8::UTEST::PutOrCall_PUT (0)
const size_t FIX8::UTEST::PutOrCall_realm_els (2)
const int FIX8::UTEST::QuoteAckStatus_ACCEPTED (0)
const int FIX8::UTEST::QuoteAckStatus_CANCELED_ALL (4)
const int FIX8::UTEST::QuoteAckStatus_CANCELED_FOR_SECURITY_TYPE (2)
const int FIX8::UTEST::QuoteAckStatus_CANCELED_FOR_SYMBOL (1)
const int FIX8::UTEST::QuoteAckStatus_CANCELED_FOR_UNDERLYING (3)
const size_t FIX8::UTEST::QuoteAckStatus_realm_els (6)
const int FIX8::UTEST::QuoteAckStatus_REJECTED (5)
const int FIX8::UTEST::QuoteCancelType_CANCEL_FOR_ALL_QUOTES (4)
const int FIX8::UTEST::QuoteCancelType_CANCEL_FOR_SECURITY_TYPE (2)
const int FIX8::UTEST::QuoteCancelType_CANCEL_FOR_SYMBOL (1)
const int FIX8::UTEST::QuoteCancelType_CANCEL_FOR_UNDERLYING_SYMBOL (3)
const size_t FIX8::UTEST::QuoteCancelType_realm_els (4)
const f8String FIX8::UTEST::QuoteCondition_CLOSED ("B")
const f8String FIX8::UTEST::QuoteCondition_CONSOLIDATED_BEST ("D")
const f8String FIX8::UTEST::QuoteCondition_CROSSED ("F")
const f8String FIX8::UTEST::QuoteCondition_DEPTH ("G")
const f8String FIX8::UTEST::QuoteCondition_EXCHANGE_BEST ("C")
const f8String FIX8::UTEST::QuoteCondition_FAST_TRADING ("H")
const f8String FIX8::UTEST::QuoteCondition_LOCKED ("E")
const f8String FIX8::UTEST::QuoteCondition_NON_FIRM ("I")
const f8String FIX8::UTEST::QuoteCondition_OPEN ("A")
const size_t FIX8::UTEST::QuoteCondition_realm_els (9)
const int FIX8::UTEST::QuoteEntryRejectReason_DUPLICATE_QUOTE (6)
const int FIX8::UTEST::QuoteEntryRejectReason_EXCHANGE (2)
const int FIX8::UTEST::QuoteEntryRejectReason_INVALID_BID_ASK_SPREAD (7)
const int FIX8::UTEST::QuoteEntryRejectReason_INVALID_PRICE (8)
const int FIX8::UTEST::QuoteEntryRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY (9)
const int FIX8::UTEST::QuoteEntryRejectReason_QUOTE_EXCEEDS_LIMIT (3)
const size_t FIX8::UTEST::QuoteEntryRejectReason_realm_els (9)
const int FIX8::UTEST::QuoteEntryRejectReason_TOO_LATE_TO_ENTER (4)
const int FIX8::UTEST::QuoteEntryRejectReason_UNKNOWN_QUOTE (5)
const int FIX8::UTEST::QuoteEntryRejectReason_UNKNOWN_SYMBOL (1)
const int FIX8::UTEST::QuoteRejectReason_DUPLICATE_QUOTE (6)
const int FIX8::UTEST::QuoteRejectReason_EXCHANGE (2)
const int FIX8::UTEST::QuoteRejectReason_INVALID_BID_ASK_SPREAD (7)
const int FIX8::UTEST::QuoteRejectReason_INVALID_PRICE (8)
const int FIX8::UTEST::QuoteRejectReason_NOT_AUTHORIZED_TO_QUOTE_SECURITY (9)
const int FIX8::UTEST::QuoteRejectReason_QUOTE_REQUEST_EXCEEDS_LIMIT (3)
const size_t FIX8::UTEST::QuoteRejectReason_realm_els (9)
const int FIX8::UTEST::QuoteRejectReason_TOO_LATE_TO_ENTER (4)
const int FIX8::UTEST::QuoteRejectReason_UNKNOWN_QUOTE (5)
const int FIX8::UTEST::QuoteRejectReason_UNKNOWN_SYMBOL (1)
const int FIX8::UTEST::QuoteRequestType_AUTOMATIC (2)
const int FIX8::UTEST::QuoteRequestType_MANUAL (1)
const size_t FIX8::UTEST::QuoteRequestType_realm_els (2)
const int FIX8::UTEST::QuoteResponseLevel_ACKNOWLEDGE_EACH_QUOTE_MESSAGES (2)
const int FIX8::UTEST::QuoteResponseLevel_ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES (1)
const int FIX8::UTEST::QuoteResponseLevel_NO_ACKNOWLEDGEMENT (0)
const size_t FIX8::UTEST::QuoteResponseLevel_realm_els (3)
const char FIX8::UTEST::ReportToExch_NO ('N')
const size_t FIX8::UTEST::ReportToExch_realm_els (2)
const char FIX8::UTEST::ReportToExch_YES ('Y')
const char FIX8::UTEST::ResetSeqNumFlag_NO ('N')
const size_t FIX8::UTEST::ResetSeqNumFlag_realm_els (2)
const char FIX8::UTEST::ResetSeqNumFlag_YES ('Y')
const int FIX8::UTEST::RoutingType_BLOCK_FIRM (3)
const int FIX8::UTEST::RoutingType_BLOCK_LIST (4)
const size_t FIX8::UTEST::RoutingType_realm_els (4)
const int FIX8::UTEST::RoutingType_TARGET_FIRM (1)
const int FIX8::UTEST::RoutingType_TARGET_LIST (2)
const char FIX8::UTEST::Rule80A_AGENCY_SINGLE_ORDER ('A')
const char FIX8::UTEST::Rule80A_ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER ('W')
const char FIX8::UTEST::Rule80A_COMPETING_DEALER_TRADES_O ('O')
const char FIX8::UTEST::Rule80A_COMPETING_DEALER_TRADES_R ('R')
const char FIX8::UTEST::Rule80A_COMPETING_DEALER_TRADES_T ('T')
const char FIX8::UTEST::Rule80A_INDIVIDUAL_INVESTOR_SINGLE_ORDER ('I')
const char FIX8::UTEST::Rule80A_PRINCIPAL ('P')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER ('J')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG ('D')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY ('U')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER ('M')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER ('K')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG ('C')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY ('Y')
const char FIX8::UTEST::Rule80A_PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER ('N')
const size_t FIX8::UTEST::Rule80A_realm_els (23)
const char FIX8::UTEST::Rule80A_REGISTERED_EQUITY_MARKET_MAKER_TRADES ('E')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_B ('B')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_F ('F')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE ('L')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE ('X')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER ('Z')
const char FIX8::UTEST::Rule80A_SHORT_EXEMPT_TRANSACTION_H ('H')
const char FIX8::UTEST::Rule80A_SPECIALIST_TRADES ('S')
const size_t FIX8::UTEST::SecurityRequestType_realm_els (4)
const int FIX8::UTEST::SecurityRequestType_REQUEST_LIST_SECURITIES (3)
const int FIX8::UTEST::SecurityRequestType_REQUEST_LIST_SECURITY_TYPES (2)
const int FIX8::UTEST::SecurityRequestType_REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS (0)
const int FIX8::UTEST::SecurityRequestType_REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED (1)
const int FIX8::UTEST::SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_AS_IS (1)
const int FIX8::UTEST::SecurityResponseType_ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE (2)
const int FIX8::UTEST::SecurityResponseType_CAN_NOT_MATCH_SELECTION_CRITERIA (6)
const int FIX8::UTEST::SecurityResponseType_LIST_OF_SECURITIES_RETURNED_PER_REQUEST (4)
const int FIX8::UTEST::SecurityResponseType_LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST (3)
const size_t FIX8::UTEST::SecurityResponseType_realm_els (6)
const int FIX8::UTEST::SecurityResponseType_REJECT_SECURITY_PROPOSAL (5)
const int FIX8::UTEST::SecurityTradingStatus_11 (11)
const int FIX8::UTEST::SecurityTradingStatus_ITS_PRE_OPENING (14)
const int FIX8::UTEST::SecurityTradingStatus_MARKET_IMBALANCE_BUY (7)
const int FIX8::UTEST::SecurityTradingStatus_MARKET_IMBALANCE_SELL (8)
const int FIX8::UTEST::SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_BUY (9)
const int FIX8::UTEST::SecurityTradingStatus_MARKET_ON_CLOSE_IMBALANCE_SELL (10)
const int FIX8::UTEST::SecurityTradingStatus_NEW_PRICE_INDICATION (15)
const int FIX8::UTEST::SecurityTradingStatus_NO_MARKET_IMBALANCE (12)
const int FIX8::UTEST::SecurityTradingStatus_NO_MARKET_ON_CLOSE_IMBALANCE (13)
const int FIX8::UTEST::SecurityTradingStatus_NO_OPEN_NO_RESUME (4)
const int FIX8::UTEST::SecurityTradingStatus_NOT_AVAILABLE_FOR_TRADING (18)
const int FIX8::UTEST::SecurityTradingStatus_NOT_TRADED_ON_THIS_MARKET (19)
const int FIX8::UTEST::SecurityTradingStatus_OPENING_DELAY (1)
const int FIX8::UTEST::SecurityTradingStatus_PRICE_INDICATION (5)
const int FIX8::UTEST::SecurityTradingStatus_READY_TO_TRADE (17)
const size_t FIX8::UTEST::SecurityTradingStatus_realm_els (20)
const int FIX8::UTEST::SecurityTradingStatus_RESUME (3)
const int FIX8::UTEST::SecurityTradingStatus_TRADE_DISSEMINATION_TIME (16)
const int FIX8::UTEST::SecurityTradingStatus_TRADING_HALT (2)
const int FIX8::UTEST::SecurityTradingStatus_TRADING_RANGE_INDICATION (6)
const int FIX8::UTEST::SecurityTradingStatus_UNKNOWN_OR_INVALID (20)
const f8String FIX8::UTEST::SecurityType_BANKERS_ACCEPTANCE ("BA")
const f8String FIX8::UTEST::SecurityType_CATS_TIGERS_LIONS ("ZOO")
const f8String FIX8::UTEST::SecurityType_CERTIFICATE_OF_DEPOSIT ("CD")
const f8String FIX8::UTEST::SecurityType_COLLATERALIZE_MORTGAGE_OBLIGATION ("CMO")
const f8String FIX8::UTEST::SecurityType_COMMERCIAL_PAPER ("CP")
const f8String FIX8::UTEST::SecurityType_COMMON_STOCK ("CS")
const f8String FIX8::UTEST::SecurityType_CONVERTIBLE_BOND ("CB")
const f8String FIX8::UTEST::SecurityType_CORPORATE_BOND ("CORP")
const f8String FIX8::UTEST::SecurityType_CORPORATE_PRIVATE_PLACEMENT ("CPP")
const f8String FIX8::UTEST::SecurityType_FEDERAL_HOME_LOAN ("FHL")
const f8String FIX8::UTEST::SecurityType_FEDERAL_HOUSING_AUTHORITY ("FHA")
const f8String FIX8::UTEST::SecurityType_FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION ("FN")
const f8String FIX8::UTEST::SecurityType_FOREIGN_EXCHANGE_CONTRACT ("FOR")
const f8String FIX8::UTEST::SecurityType_FUTURE ("FUT")
const f8String FIX8::UTEST::SecurityType_GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION ("GN")
const f8String FIX8::UTEST::SecurityType_MISCELLANEOUS_PASS_THRU ("MPT")
const f8String FIX8::UTEST::SecurityType_MORTGAGE_INTEREST_ONLY ("MIO")
const f8String FIX8::UTEST::SecurityType_MORTGAGE_IOETTE ("IET")
const f8String FIX8::UTEST::SecurityType_MORTGAGE_PRINCIPAL_ONLY ("MPO")
const f8String FIX8::UTEST::SecurityType_MORTGAGE_PRIVATE_PLACEMENT ("MPP")
const f8String FIX8::UTEST::SecurityType_MUNICIPAL_BOND ("MUNI")
const f8String FIX8::UTEST::SecurityType_MUTUAL_FUND ("MF")
const f8String FIX8::UTEST::SecurityType_NO_ISITC_SECURITY_TYPE ("NONE")
const f8String FIX8::UTEST::SecurityType_OPTION ("OPT")
const f8String FIX8::UTEST::SecurityType_PREFERRED_STOCK ("PS")
const size_t FIX8::UTEST::SecurityType_realm_els (33)
const f8String FIX8::UTEST::SecurityType_REPURCHASE_AGREEMENT ("RP")
const f8String FIX8::UTEST::SecurityType_REVERSE_REPURCHASE_AGREEMENT ("RVRP")
const f8String FIX8::UTEST::SecurityType_STUDENT_LOAN_MARKETING_ASSOCIATION ("SL")
const f8String FIX8::UTEST::SecurityType_TIME_DEPOSIT ("TD")
const f8String FIX8::UTEST::SecurityType_TREASURIES_PLUS_AGENCY_DEBENTURE ("GOVT")
const f8String FIX8::UTEST::SecurityType_US_TREASURY_BILL ("USTB")
const f8String FIX8::UTEST::SecurityType_WARRANT ("WAR")
const f8String FIX8::UTEST::SecurityType_WILDCARD_ENTRY ("?")
const int FIX8::UTEST::SessionRejectReason_COMPID_PROBLEM (9)
const int FIX8::UTEST::SessionRejectReason_DECRYPTION_PROBLEM (7)
const int FIX8::UTEST::SessionRejectReason_INCORRECT_DATA_FORMAT_FOR_VALUE (6)
const int FIX8::UTEST::SessionRejectReason_INVALID_MSGTYPE (11)
const int FIX8::UTEST::SessionRejectReason_INVALID_TAG_NUMBER (0)
const size_t FIX8::UTEST::SessionRejectReason_realm_els (12)
const int FIX8::UTEST::SessionRejectReason_REQUIRED_TAG_MISSING (1)
const int FIX8::UTEST::SessionRejectReason_SENDINGTIME_ACCURACY_PROBLEM (10)
const int FIX8::UTEST::SessionRejectReason_SIGNATURE_PROBLEM (8)
const int FIX8::UTEST::SessionRejectReason_TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE (2)
const int FIX8::UTEST::SessionRejectReason_TAG_SPECIFIED_WITHOUT_A_VALUE (4)
const int FIX8::UTEST::SessionRejectReason_UNDEFINED_TAG (3)
const int FIX8::UTEST::SessionRejectReason_VALUE_IS_INCORRECT (5)
const char FIX8::UTEST::SettlCurrFxRateCalc_DIVIDE ('D')
const char FIX8::UTEST::SettlCurrFxRateCalc_MULTIPLY ('M')
const size_t FIX8::UTEST::SettlCurrFxRateCalc_realm_els (2)
const char FIX8::UTEST::SettlInstMode_DEFAULT ('0')
const size_t FIX8::UTEST::SettlInstMode_realm_els (4)
const char FIX8::UTEST::SettlInstMode_SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING ('2')
const char FIX8::UTEST::SettlInstMode_SPECIFIC_ALLOCATION_ACCOUNT_STANDING ('3')
const char FIX8::UTEST::SettlInstMode_STANDING_INSTRUCTIONS_PROVIDED ('1')
const char FIX8::UTEST::SettlInstSource_BROKERS_INSTRUCTIONS ('1')
const char FIX8::UTEST::SettlInstSource_INSTITUTIONS_INSTRUCTIONS ('2')
const size_t FIX8::UTEST::SettlInstSource_realm_els (2)
const char FIX8::UTEST::SettlInstTransType_CANCEL ('C')
const char FIX8::UTEST::SettlInstTransType_NEW ('N')
const size_t FIX8::UTEST::SettlInstTransType_realm_els (3)
const char FIX8::UTEST::SettlInstTransType_REPLACE ('R')
const f8String FIX8::UTEST::SettlLocation_CEDEL ("CED")
const f8String FIX8::UTEST::SettlLocation_DEPOSITORY_TRUST_COMPANY ("DTC")
const f8String FIX8::UTEST::SettlLocation_EUROCLEAR ("EUR")
const f8String FIX8::UTEST::SettlLocation_FEDERAL_BOOK_ENTRY ("FED")
const f8String FIX8::UTEST::SettlLocation_LOCAL_MARKET_SETTLE_LOCATION ("ISO Country Code")
const f8String FIX8::UTEST::SettlLocation_PARTICIPANT_TRUST_COMPANY ("PTC")
const f8String FIX8::UTEST::SettlLocation_PHYSICAL ("PNY")
const size_t FIX8::UTEST::SettlLocation_realm_els (7)
const char FIX8::UTEST::SettlmntTyp_CASH ('1')
const char FIX8::UTEST::SettlmntTyp_FUTURE ('6')
const char FIX8::UTEST::SettlmntTyp_NEXT_DAY ('2')
const size_t FIX8::UTEST::SettlmntTyp_realm_els (10)
const char FIX8::UTEST::SettlmntTyp_REGULAR ('0')
const char FIX8::UTEST::SettlmntTyp_SELLERS_OPTION ('8')
const char FIX8::UTEST::SettlmntTyp_T_PLUS_2 ('3')
const char FIX8::UTEST::SettlmntTyp_T_PLUS_3 ('4')
const char FIX8::UTEST::SettlmntTyp_T_PLUS_4 ('5')
const char FIX8::UTEST::SettlmntTyp_T_PLUS_5 ('9')
const char FIX8::UTEST::SettlmntTyp_WHEN_ISSUED ('7')
const char FIX8::UTEST::Side_BUY ('1')
const char FIX8::UTEST::Side_BUY_MINUS ('3')
const char FIX8::UTEST::Side_CROSS ('8')
const char FIX8::UTEST::Side_CROSS_SHORT ('9')
const size_t FIX8::UTEST::Side_realm_els (9)
const char FIX8::UTEST::Side_SELL ('2')
const char FIX8::UTEST::Side_SELL_PLUS ('4')
const char FIX8::UTEST::Side_SELL_SHORT ('5')
const char FIX8::UTEST::Side_SELL_SHORT_EXEMPT ('6')
const char FIX8::UTEST::Side_UNDISCLOSED ('7')
const char FIX8::UTEST::SolicitedFlag_NO ('N')
const size_t FIX8::UTEST::SolicitedFlag_realm_els (2)
const char FIX8::UTEST::SolicitedFlag_YES ('Y')
const int FIX8::UTEST::StandInstDbType_A_GLOBAL_CUSTODIAN (3)
const int FIX8::UTEST::StandInstDbType_DTC_SID (1)
const int FIX8::UTEST::StandInstDbType_OTHER (0)
const size_t FIX8::UTEST::StandInstDbType_realm_els (4)
const int FIX8::UTEST::StandInstDbType_THOMSON_ALERT (2)
const char FIX8::UTEST::SubscriptionRequestType_DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST ('2')
const size_t FIX8::UTEST::SubscriptionRequestType_realm_els (3)
const char FIX8::UTEST::SubscriptionRequestType_SNAPSHOT ('0')
const char FIX8::UTEST::SubscriptionRequestType_SNAPSHOT_PLUS_UPDATES ('1')
const char FIX8::UTEST::TickDirection_MINUS_TICK ('2')
const char FIX8::UTEST::TickDirection_PLUS_TICK ('0')
const size_t FIX8::UTEST::TickDirection_realm_els (4)
const char FIX8::UTEST::TickDirection_ZERO_MINUS_TICK ('3')
const char FIX8::UTEST::TickDirection_ZERO_PLUS_TICK ('1')
const char FIX8::UTEST::TimeInForce_AT_THE_OPENING ('2')
const char FIX8::UTEST::TimeInForce_DAY ('0')
const char FIX8::UTEST::TimeInForce_FILL_OR_KILL ('4')
const char FIX8::UTEST::TimeInForce_GOOD_TILL_CANCEL ('1')
const char FIX8::UTEST::TimeInForce_GOOD_TILL_CROSSING ('5')
const char FIX8::UTEST::TimeInForce_GOOD_TILL_DATE ('6')
const char FIX8::UTEST::TimeInForce_IMMEDIATE_OR_CANCEL ('3')
const size_t FIX8::UTEST::TimeInForce_realm_els (7)
const f8String FIX8::UTEST::TradeCondition_AVERAGE_PRICE_TRADE ("B")
const f8String FIX8::UTEST::TradeCondition_CASH ("A")
const f8String FIX8::UTEST::TradeCondition_CASH_TRADE ("C")
const f8String FIX8::UTEST::TradeCondition_INTRADAY_TRADE_DETAIL ("F")
const f8String FIX8::UTEST::TradeCondition_NEXT_DAY ("D")
const f8String FIX8::UTEST::TradeCondition_NEXT_DAY_TRADE ("J")
const f8String FIX8::UTEST::TradeCondition_OPENED ("K")
const f8String FIX8::UTEST::TradeCondition_OPENING ("E")
const size_t FIX8::UTEST::TradeCondition_realm_els (14)
const f8String FIX8::UTEST::TradeCondition_RULE_127_TRADE ("G")
const f8String FIX8::UTEST::TradeCondition_RULE_155_TRADE ("H")
const f8String FIX8::UTEST::TradeCondition_SELLER ("L")
const f8String FIX8::UTEST::TradeCondition_SOLD ("M")
const f8String FIX8::UTEST::TradeCondition_SOLD_LAST ("I")
const f8String FIX8::UTEST::TradeCondition_STOPPED_STOCK ("N")
const char FIX8::UTEST::TradeType_AGENCY ('A')
const char FIX8::UTEST::TradeType_GUARANTEED_CLOSE ('J')
const size_t FIX8::UTEST::TradeType_realm_els (4)
const char FIX8::UTEST::TradeType_RISK_TRADE ('R')
const char FIX8::UTEST::TradeType_VWAP_GUARANTEE ('G')
const int FIX8::UTEST::TradSesMethod_ELECTRONIC (1)
const int FIX8::UTEST::TradSesMethod_OPEN_OUTCRY (2)
const size_t FIX8::UTEST::TradSesMethod_realm_els (3)
const int FIX8::UTEST::TradSesMethod_TWO_PARTY (3)
const int FIX8::UTEST::TradSesMode_PRODUCTION (3)
const size_t FIX8::UTEST::TradSesMode_realm_els (3)
const int FIX8::UTEST::TradSesMode_SIMULATED (2)
const int FIX8::UTEST::TradSesMode_TESTING (1)
const int FIX8::UTEST::TradSesStatus_CLOSED (3)
const int FIX8::UTEST::TradSesStatus_HALTED (1)
const int FIX8::UTEST::TradSesStatus_OPEN (2)
const int FIX8::UTEST::TradSesStatus_PRE_CLOSE (5)
const int FIX8::UTEST::TradSesStatus_PRE_OPEN (4)
const size_t FIX8::UTEST::TradSesStatus_realm_els (5)
const char FIX8::UTEST::UnsolicitedIndicator_NO ('N')
const size_t FIX8::UTEST::UnsolicitedIndicator_realm_els (2)
const char FIX8::UTEST::UnsolicitedIndicator_YES ('Y')
const char FIX8::UTEST::Urgency_BACKGROUND ('2')
const char FIX8::UTEST::Urgency_FLASH ('1')
const char FIX8::UTEST::Urgency_NORMAL ('0')
const size_t FIX8::UTEST::Urgency_realm_els (3)
Variable Documentation
const utest_BaseEntry::Pair FIX8::UTEST::fldpairs
Definition at line 731 of file utest_types.cpp.
Referenced by ctx().
const UTEST::utest_BaseMsgEntry::Pair FIX8::UTEST::msgpairs[]
Definition at line 101 of file utest_classes.cpp.
Referenced by ctx().