fix8: FIX8 Namespace Reference
FIX8 Namespace Reference
Namespaces
defaults
MBUS
States
Session states and semantics.
TEX
Classes
class _f8_threadcore
pthread wrapper abstract base
struct _pair
Pair abstraction for use with GeneratedTable.
struct _pair< const char *, Val >
Partial specialisation of Pair abstraction for use with GeneratedTable.
class AsyncSocket
Half duplex async socket wrapper with thread.
struct BadCheckSum
An inbound message had an invalid (incorrect) checksum.
struct BadCompidId
A message was received with an invalid sender/target compid id.
struct BadSendingTime
A message was received with an invalid sending time.
struct BaseEntry
class BaseField
The base field class (ABC) for all fields.
struct BaseMsgEntry
Message instantiation table entry.
class BCLogger
A broadcast logger.
class bcostream
udp stream
class bcoutbuf
Socket output streambuf, inspiration from Josuttis N.M.
class buffered_ostream
struct CharRealm
f8c character realm type.
class ClientConnection
Client (initiator) specialisation of Connection.
class ClientSession
Client wrapper.
class ClientSessionBase
Base Client wrapper.
class Configuration
Class to encapsulate a Fix8 configuration.
struct ConfigurationError
An bad or missing configuration parameter.
class Connection
Complete Fix connection (reader and writer).
class ConsoleMenu
Console test harness menu.
struct Ctxt
f8c compilation context.
struct DuplicateField
A field was decoded in a message that has already been decoded.
class ebitset
Bitset for enums.
class ebitset_r
Atomic bitset for enums.
struct EnumType
Int2Type idiom. Kudos to Andrei Alexandrescu.
class f8_mutex
generic pthread_mutex wrapper
class f8_scoped_lock_impl
class f8_spin_lock
generic spin_lock wrapper
class f8_thread
Thread wrapper. Ctor provides T instance and specifies ptr to member to call or defaults to operator()
class f8_thread_cancellation_token
Thread cancellation token.
struct f8_threadException
A pthread attribute error occured.
class f8Exception
Base exception class.
struct F8MetaCntx
Static metadata context class - one per FIX xml schema.
class fdinbuf
Create a streambuf from an open file descriptor.
class fdoutbuf
File descriptor output streambuf, inspiration from Josuttis N.M.
class ff_unbounded_queue
class ff_unbounded_queue< T * >
class Field
Field template. There will ONLY be partial template specialisations of this template.
class Field< Boolean, field >
Partial specialisation for Boolean field type.
class Field< char *, field >
Partial specialisation for char * field type.
class Field< char, field >
Partial specialisation for unsigned short field type.
class Field< DayOfMonth, field >
Partial specialisation for DayOfMonth field type.
class Field< f8String, field >
Partial specialisation for f8String field type.
class Field< fp_type, field >
Partial specialisation for fp_type field type. fp_type is singe or double.
class Field< int, field >
Partial specialisation for int field type.
class Field< Length, field >
Partial specialisation for Length field type.
class Field< LocalMktDate, field >
Partial specialisation for LocalMktDate field type.
class Field< MonthYear, field >
Partial specialisation for MonthYear field type.
class Field< NumInGroup, field >
Partial specialisation for NumInGroup field type.
class Field< SeqNum, field >
Partial specialisation for SeqNum field type.
class Field< TagNum, field >
Partial specialisation for TagNum field type.
class Field< TZTimeOnly, field >
Partial specialisation for TZTimeOnly field type.
class Field< TZTimestamp, field >
Partial specialisation for TZTimestamp field type.
class Field< UTCDateOnly, field >
Partial specialisation for UTCDateOnly field type.
class Field< UTCTimeOnly, field >
Partial specialisation for UTCTimeOnly field type.
class Field< UTCTimestamp, field >
Partial specialisation for UTCTimestamp field type.
struct FieldSpec
f8c internal field representation.
struct FieldTrait
Used for static trait interrogation.
struct FieldTrait_Hash_Array
Fast index lookup for FieldTrait.
class FieldTraits
A collection of FieldTraits for a message. Which fields are required, which are present.
class FileLogger
A file logger.
class FilePersister
class filestdin
Abstract file or stdin input.
class FIXReader
Fix message reader.
class FIXWriter
Fix message writer.
class fptrostream
File pointer stream.
class GeneratedTable
Fast map for statically generated data types. Assumes table is sorted. Complexity is O(logN).
class GroupBase
Abstract base class for all repeating groups.
struct IllegalMessage
A message was read that was in an illegal format.
class Inst
Field metadata structures.
class IntervalTimer
High resolution interval timer.
struct InvalidBodyLength
A message was decoded with an invalid message body length.
struct InvalidConfiguration
An invalid configuration parameter was passed.
struct InvalidDomainValue
For field types with a specified domain (realm), a value was decoded that was not in the domain set/range.
struct InvalidField
An invalid field was requested or added.
struct InvalidMessage
An invalid message was requested or decoded.
struct InvalidMetadata
Indicates a static metadata lookup failed. With the exception of user defined fields there should never be an instance where a metatdata lookup fails.
struct InvalidMsgSequence
A message was received with an out of sequence sequence number.
struct InvalidRepeatingGroup
An invalid repeating group was found while attempting to encode a message.
struct InvalidVersion
A message was decoded that had a Fix version not configured for this session.
struct IPrec
class log_stream
struct LogfileException
Could not open a logfile.
class Logger
f8_thread delegated async logging class
struct LoginParameters
class MemoryPersister
Memory based message persister.
class Message
A complete Fix message with header, body and trailer.
class MessageBase
Base class for all fix messages.
struct MessageSpec
f8c internal message representation.
class Minst
Structures for framework generated message creation and static trait interrogation.
struct MissingMandatoryField
An outbound message was missing a mandatory field.
struct MissingMessageComponent
An outbound message was missing a header or trailer.
struct MissingRepeatingGroupField
An invalid repeating group field was found while decoding a message (first field is mandatory).
struct MsgSequenceTooLow
A message was received with an out of sequence sequence number.
struct null_insert
Template provides insert operator that inserts nothing.
struct PeerResetConnection
A connected peer has reset the connection (disconnected).
class Persister
Base (ABC) Persister class.
class PipeLogger
A pipe logger.
struct Prec
File persister.
class presorted_set
class presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >
class push_dir
struct RealmBase
Domain range/set static metadata base class.
class RealmObject
f8c range or set domain realm.
class RegExp
POSIX regex wrapper class.
class RegMatch
A class to contain regex matches using RegExp.
class ReliableClientSession
Reliable Client wrapper. This client attempts to recover from disconnects and login rejects.
class Router
Base class for inbound message routing.
struct Schedule
struct Server
Class to hold server settings for failoverable sessions.
class ServerConnection
Server (acceptor) specialisation of Connection.
class ServerManager
Multi Server Manager.
class ServerSession
class ServerSessionBase
Base Server Session.
class Session
Fix8 Base Session. User sessions are derived from this class.
struct Session_Schedule
struct SessionConfig
Base session wrapper.
class SessionID
Quickfix style sessionid.
class SessionInstance
Server session instance.
class SessionInstanceBase
Base Server session instance.
class SessionManager
Session Manager.
class SingleLogger
A global singleton logger.
class Singleton
struct SslContext
Class to hold SSL context for failoverable sessions.
struct StringLessThanNoCase
Case-insensitive string comparison.
struct StringPtrLessThan
Case-sensitive string comparison, pointer version.
struct StringPtrLessThanNoCase
Case-insensitive string comparison, pointer version.
struct StringRealm
f8c string realm type.
class Tickval
class Timer
High resolution timer.
class TimerEvent
Timer event object to provide callback context with Timer.
class tty_save_state
struct Type2Type
Type2Type idiom. Variadic template version. Kudos to Andrei Alexandrescu.
class TypedRealm
f8c typed realm.
struct UnknownField
An invalid field was decoded.
struct XMLError
An invalid configuration parameter was passed.
class XmlFileLogger
A file logger.
Typedefs
using MsgList = std::deque< FIX8::Message * >
using f8String = std::string
using fp_type = double
using Package_info = std::map< f8String, f8String >
using UTCTimestamp = EnumType< FieldTrait::ft_UTCTimestamp >
using UTCTimeOnly = EnumType< FieldTrait::ft_UTCTimeOnly >
using UTCDateOnly = EnumType< FieldTrait::ft_UTCDateOnly >
using LocalMktDate = EnumType< FieldTrait::ft_LocalMktDate >
using MonthYear = EnumType< FieldTrait::ft_MonthYear >
using TZTimeOnly = EnumType< FieldTrait::ft_TZTimeOnly >
using TZTimestamp = EnumType< FieldTrait::ft_TZTimestamp >
using Length = EnumType< FieldTrait::ft_Length >
using TagNum = EnumType< FieldTrait::ft_TagNum >
using SeqNum = EnumType< FieldTrait::ft_SeqNum >
using NumInGroup = EnumType< FieldTrait::ft_NumInGroup >
using DayOfMonth = EnumType< FieldTrait::ft_DayOfMonth >
using Boolean = EnumType< FieldTrait::ft_Boolean >
using Qty = fp_type
using Amt = fp_type
using price = fp_type
using PriceOffset = fp_type
using Percentage = fp_type
using MultipleCharValue = f8String
using MultipleStringValue = f8String
using country = f8String
using currency = f8String
using Exchange = f8String
using Language = f8String
using XMLData = f8String
using data = f8String
using msg_seq_num = Field< SeqNum, Common_MsgSeqNum >
using begin_seq_num = Field< SeqNum, Common_BeginSeqNo >
using end_seq_num = Field< SeqNum, Common_EndSeqNo >
using new_seq_num = Field< SeqNum, Common_NewSeqNo >
using ref_seq_num = Field< SeqNum, Common_RefSeqNum >
using body_length = Field< Length, Common_BodyLength >
using sender_comp_id = Field< f8String, Common_SenderCompID >
using target_comp_id = Field< f8String, Common_TargetCompID >
using msg_type = Field< f8String, Common_MsgType >
using check_sum = Field< f8String, Common_CheckSum >
using begin_string = Field< f8String, Common_BeginString >
using test_request_id = Field< f8String, Common_TestReqID >
using text = Field< f8String, Common_Text >
using default_appl_ver_id = Field< f8String, Common_DefaultApplVerID >
using ref_msg_type = Field< f8String, Common_RefMsgType >
using sending_time = Field< UTCTimestamp, Common_SendingTime >
using orig_sending_time = Field< UTCTimestamp, Common_OrigSendingTime >
using gap_fill_flag = Field< Boolean, Common_GapFillFlag >
using poss_dup_flag = Field< Boolean, Common_PossDupFlag >
using reset_seqnum_flag = Field< Boolean, Common_ResetSeqNumFlag >
using heartbeat_interval = Field< int, Common_HeartBtInt >
using encrypt_method = Field< int, Common_EncryptMethod >
using business_reject_reason = Field< int, Common_BusinessRejectReason >
using onbehalfof_comp_id = Field< f8String, Common_OnBehalfOfCompID >
using onbehalfof_sub_id = Field< f8String, Common_OnBehalfOfSubID >
using onbehalfof_location_id = Field< f8String, Common_OnBehalfOfLocationID >
using onbehalfof_sending_time = Field< UTCTimestamp, Common_OnBehalfOfSendingTime >
using logger_function = std::function< bool(const std::string &, Logger::Level, const char *, const unsigned)>
using GlobalLogger = SingleLogger< glob_log0 >
using GroupElement = std::vector< MessageBase * >
using Groups = std::map< unsigned short, GroupBase * >
using c_str_compare = std::function< bool(const char *, const char *)>
Field and Message metadata structures.
using msg_create = std::function< Message *(bool)>
using MsgTable = GeneratedTable< const char *, BaseMsgEntry >
using ReverseMsgTable = std::map< const char *const, const BaseMsgEntry *, c_str_compare >
using FieldTable = GeneratedTable< unsigned, BaseEntry >
using ReverseFieldTable = std::map< const char *const, const BaseEntry *, c_str_compare >
using Fields = std::map< unsigned short, BaseField * >
using Positions = std::multimap< unsigned short, BaseField * >
using ClientManager = SessionManager< ClientSessionBase >
Client Manager.
using SessionInstanceManager = SessionManager< SessionInstanceBase >
Session Instance Manager.
using Client = std::tuple< f8String, Poco::Net::IPAddress >
Class to hold client info settings for server sessions.
using Clients = std::unordered_map< f8String, Client >
template<typename T >
using f8_atomic = std::atomic< T >
using thread_id_t = std::thread::id
using f8_scoped_lock = f8_scoped_lock_impl< f8_mutex >
using f8_scoped_spin_lock = f8_scoped_lock_impl< f8_spin_lock >
template<typename T >
using dthread = f8_thread< T >
using _dthreadcore = _f8_threadcore
using dthread_cancellation_token = f8_thread_cancellation_token
using Presence = presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >
using RealmMap = std::map< RealmObject *, std::string, RealmObject::less >
using FieldSpecMap = std::map< unsigned, struct FieldSpec >
using FieldToNumMap = std::map< std::string, unsigned >
using GroupMap = std::map< unsigned, struct MessageSpec >
using BaseTypeMap = std::map< std::string, FieldTrait::FieldType >
using TypeToCPP = std::map< FieldTrait::FieldType, std::pair< std::string, std::string >>
using MessageSpecMap = std::map< const std::string, MessageSpec >
using FieldTraitOrder = std::multiset< const FieldTrait *, FieldTrait::PosCompare >
using CommonGroups = std::map< uint32_t, struct MessageSpec >
using CommonGroupMap = std::map< unsigned, CommonGroups >
using Components = std::map< std::string, const XmlElement * >
using CSMap = std::map< comp_str, std::string >
Enumerations
enum ProcessModel { pm_thread, pm_pipeline, pm_coro, pm_count }
Supported session process models.
enum TimeIndicator {
_time_only, _time_with_ms, _short_date_only, _date_only,
_sec_only, _with_ms
}
enum hyperunits_t {
h_seconds, h_milliseconds, h_microseconds, h_nanoseconds,
h_count
}
enum comp_str {
cs_do_not_edit, cs_start_namespace, cs_end_namespace, cs_start_anon_namespace,
cs_end_anon_namespace, cs_divider, cs_copyright, cs_copyright2,
cs_generated_includes, cs_header_preamble, cs_trailer_preamble
}
Functions
const unsigned char default_field_separator (0x1)
default FIX field separator (^A)
const unsigned char default_assignment_separator ('=')
default FIX assignment separator (=)
F8API std::string & InPlaceStrToUpper (std::string &src)
F8API std::string & InPlaceStrToLower (std::string &src)
F8API std::string StrToLower (const std::string &src)
F8API int decode_dow (const std::string &from)
F8API std::string & CheckAddTrailingSlash (std::string &source)
F8API std::string & InPlaceReplaceInSet (const std::string &iset, std::string &src, const char repl='_')
F8API std::string Str_error (const int err, const char *str=0)
F8API const std::string & GetTimeAsStringMS (std::string &result, const class Tickval *tv=0, const unsigned dplaces=6, bool use_gm=false)
std::string GetTimeAsStringMS (const class Tickval *tv, const unsigned dplaces=6, bool use_gm=false)
F8API const std::string & GetTimeAsStringMini (std::string &result, const Tickval *tv)
std::string GetTimeAsStringMini (const Tickval *tv)
std::string trim (const std::string &source, const std::string &ws=" \t")
const std::string & trim (std::string &source, const std::string &ws=" \t")
F8API const Package_info & package_info ()
F8API f8String find_package_info_string (const f8String &what)
template<typename T >
void ignore_value (T val)
template<typename T >
void ignore_value (T *val)
template<typename T >
T rotl (const T val, const int times)
template<typename T >
T rotr (const T val, const int times)
unsigned ROT13Hash (const std::string &str)
unsigned rothash (unsigned result, unsigned value)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator% (const std::basic_string< _CharT, _Traits, _Alloc > &__lhs, const std::basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator% (const _CharT *__lhs, const std::basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator% (const std::basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator^ (const std::basic_string< _CharT, _Traits, _Alloc > &__lhs, const std::basic_string< _CharT, _Traits, _Alloc > &__rhs)
F8API void create_path (const std::string &path)
template<typename T >
T get_value (const std::string &source)
template<>
unsigned get_value (const std::string &source)
template<>
int get_value (const std::string &source)
template<>
double get_value (const std::string &source)
template<>
float get_value (const std::string &source)
template<>
bool get_value (const std::string &source)
template<typename T >
T fast_atoi (const char *str, const char term='\0')
template<typename T >
size_t itoa (T value, char *result, int base)
Fast itoa.
template<>
size_t itoa< unsigned int > (unsigned int value, char *result, int base)
Fast itoa - unsigned int specialisation.
fp_type fast_atof (const char *p)
size_t modp_dtoa (double value, char *str, int prec)
Convert double to ascii.
constexpr unsigned bitsum ()
empty argument version
template<typename T , typename... Args>
constexpr unsigned bitsum (T value, Args...args)
template<typename T >
T enum_str_get (const std::vector< std::string > &sset, const std::string &what, const T def, bool ignorecase=false)
F8API int get_umask ()
bool exist (const std::string &fname)
void split_path (const std::string &source, std::string &filepart, std::string &dirpart)
char * CopyString (const std::string &src, char *target, unsigned limit=0)
const size_t MAX_MSGTYPE_FIELD_LEN (32)
const size_t HEADER_CALC_OFFSET (32)
void format0 (int data, char *to, int width)
size_t parse_decimal (const char *begin, size_t len, int &to)
time_t time_to_epoch (const tm &ltm, int utcdiff=0)
size_t date_time_format (const Tickval &tickval, char *to, TimeIndicator ind)
Tickval::ticks date_time_parse (const char *ptr, size_t len)
Tickval::ticks time_parse (const char *ptr, size_t len, bool timeonly=false)
Tickval::ticks date_parse (const char *ptr, size_t len)
const f8String Common_MsgType_HEARTBEAT ("0")
const f8String Common_MsgType_TEST_REQUEST ("1")
const f8String Common_MsgType_RESEND_REQUEST ("2")
const f8String Common_MsgType_REJECT ("3")
const f8String Common_MsgType_SEQUENCE_RESET ("4")
const f8String Common_MsgType_LOGOUT ("5")
const f8String Common_MsgType_LOGON ("A")
const f8String Common_MsgType_BUSINESS_REJECT ("j")
const char Common_MsgByte_HEARTBEAT ('0')
const char Common_MsgByte_TEST_REQUEST ('1')
const char Common_MsgByte_RESEND_REQUEST ('2')
const char Common_MsgByte_REJECT ('3')
const char Common_MsgByte_SEQUENCE_RESET ('4')
const char Common_MsgByte_LOGOUT ('5')
const char Common_MsgByte_LOGON ('A')
const char Common_MsgByte_BUSINESS_REJECT ('j')
const unsigned short Common_BeginSeqNo (7)
const unsigned short Common_BeginString (8)
const unsigned short Common_BodyLength (9)
const unsigned short Common_CheckSum (10)
const unsigned short Common_EndSeqNo (16)
const unsigned short Common_MsgSeqNum (34)
const unsigned short Common_MsgType (35)
const unsigned short Common_NewSeqNo (36)
const unsigned short Common_PossDupFlag (43)
const unsigned short Common_RefSeqNum (45)
const unsigned short Common_SenderCompID (49)
const unsigned short Common_SendingTime (52)
const unsigned short Common_TargetCompID (56)
const unsigned short Common_Text (58)
const unsigned short Common_EncryptMethod (98)
const unsigned short Common_HeartBtInt (108)
const unsigned short Common_TestReqID (112)
const unsigned short Common_OnBehalfOfCompID (115)
const unsigned short Common_OnBehalfOfSubID (116)
const unsigned short Common_OrigSendingTime (122)
const unsigned short Common_GapFillFlag (123)
const unsigned short Common_ResetSeqNumFlag (141)
const unsigned short Common_OnBehalfOfLocationID (144)
const unsigned short Common_OnBehalfOfSendingTime (370)
const unsigned short Common_RefMsgType (372)
const unsigned short Common_BusinessRejectReason (380)
const unsigned short Common_DefaultApplVerID (1137)
template<hyperunits_t >
int hypersleep (unsigned amt)
template<>
int hypersleep< h_seconds > (unsigned amt)
template<>
int hypersleep< h_milliseconds > (unsigned amt)
template<>
int hypersleep< h_microseconds > (unsigned amt)
template<>
int hypersleep< h_nanoseconds > (unsigned amt)
int hypersleep (unsigned amt, hyperunits_t units)
const size_t max_global_filename_length (1024)
std::ostream & operator<< (std::ostream &os, const GroupBase &what)
F8API std::ostream & operator<< (std::ostream &os, const FieldTrait &what)
F8API std::ostream & operator<< (std::ostream &os, const FieldTraits &what)
const string & GetTimeAsStringMS (string &result, const Tickval *tv, const unsigned dplaces, bool use_gm)
const string & GetTimeAsStringMini (string &result, const Tickval *tv)
string & CheckAddTrailingSlash (string &src)
string & InPlaceStrToUpper (string &src)
string & InPlaceReplaceInSet (const string &iset, string &src, const char repl)
string & InPlaceStrToLower (string &src)
string StrToLower (const string &src)
void create_path (const string &path)
int decode_dow (const string &from)
int recover_line (const XmlElement &xf)
const F8MetaCntx & TEX_ctx ()
Variables
F8API char glob_log0 [max_global_filename_length] { "global_filename_not_set.log" }
const CSMap _csMap
Detailed Description
All FIX8 classes and functions reside inside this namespace.
Typedef Documentation
using FIX8::_dthreadcore = typedef _f8_threadcore
Definition at line 454 of file thread.hpp.
using FIX8::Amt = typedef fp_type
Definition at line 2023 of file field.hpp.
using FIX8::BaseTypeMap = typedef std::map<std::string, FieldTrait::FieldType>
Definition at line 123 of file f8c.hpp.
using FIX8::begin_seq_num = typedef Field<SeqNum, Common_BeginSeqNo>
Definition at line 2138 of file field.hpp.
using FIX8::begin_string = typedef Field<f8String, Common_BeginString>
Definition at line 2149 of file field.hpp.
using FIX8::body_length = typedef Field<Length, Common_BodyLength>
Definition at line 2143 of file field.hpp.
using FIX8::Boolean = typedef EnumType<FieldTrait::ft_Boolean>
Definition at line 1910 of file field.hpp.
using FIX8::business_reject_reason = typedef Field<int, Common_BusinessRejectReason>
Definition at line 2164 of file field.hpp.
using FIX8::c_str_compare = typedef std::function<bool(const char *, const char *)>
Field and Message metadata structures.
Definition at line 201 of file message.hpp.
using FIX8::check_sum = typedef Field<f8String, Common_CheckSum>
Definition at line 2148 of file field.hpp.
using FIX8::Client = typedef std::tuple<f8String, Poco::Net::IPAddress>
Class to hold client info settings for server sessions.
Definition at line 181 of file session.hpp.
using FIX8::ClientManager = typedef SessionManager<ClientSessionBase>
Client Manager.
Definition at line 184 of file multisession.hpp.
using FIX8::Clients = typedef std::unordered_map<f8String, Client>
Definition at line 182 of file session.hpp.
using FIX8::CommonGroupMap = typedef std::map<unsigned, CommonGroups>
Definition at line 180 of file f8c.hpp.
using FIX8::CommonGroups = typedef std::map<uint32_t, struct MessageSpec>
Definition at line 179 of file f8c.hpp.
using FIX8::Components = typedef std::map<std::string, const XmlElement *>
Definition at line 183 of file f8c.hpp.
using FIX8::country = typedef f8String
Definition at line 2031 of file field.hpp.
using FIX8::CSMap = typedef std::map<comp_str, std::string>
Definition at line 201 of file f8c.hpp.
using FIX8::currency = typedef f8String
Definition at line 2032 of file field.hpp.
using FIX8::data = typedef f8String
Definition at line 2036 of file field.hpp.
using FIX8::DayOfMonth = typedef EnumType<FieldTrait::ft_DayOfMonth>
Definition at line 1875 of file field.hpp.
using FIX8::default_appl_ver_id = typedef Field<f8String, Common_DefaultApplVerID>
Definition at line 2152 of file field.hpp.
template<typename T > using FIX8::dthread = typedef f8_thread<T>
Definition at line 453 of file thread.hpp.
using FIX8::dthread_cancellation_token = typedef f8_thread_cancellation_token
Definition at line 455 of file thread.hpp.
using FIX8::encrypt_method = typedef Field<int, Common_EncryptMethod>
Definition at line 2163 of file field.hpp.
using FIX8::end_seq_num = typedef Field<SeqNum, Common_EndSeqNo>
Definition at line 2139 of file field.hpp.
using FIX8::Exchange = typedef f8String
Definition at line 2033 of file field.hpp.
template<typename T > using FIX8::f8_atomic = typedef std::atomic <T>
Definition at line 55 of file thread.hpp.
using FIX8::f8_scoped_lock = typedef f8_scoped_lock_impl<f8_mutex>
Definition at line 451 of file thread.hpp.
using FIX8::f8_scoped_spin_lock = typedef f8_scoped_lock_impl<f8_spin_lock>
Definition at line 452 of file thread.hpp.
using FIX8::f8String = typedef std::string
Definition at line 47 of file f8types.hpp.
using FIX8::Fields = typedef std::map <unsigned short, BaseField *>
Definition at line 377 of file message.hpp.
using FIX8::FieldSpecMap = typedef std::map<unsigned, struct FieldSpec>
Definition at line 118 of file f8c.hpp.
using FIX8::FieldTable = typedef GeneratedTable<unsigned, BaseEntry>
Definition at line 205 of file message.hpp.
using FIX8::FieldToNumMap = typedef std::map<std::string, unsigned>
Definition at line 119 of file f8c.hpp.
using FIX8::FieldTraitOrder = typedef std::multiset<const FieldTrait *, FieldTrait::PosCompare>
Definition at line 176 of file f8c.hpp.
using FIX8::fp_type = typedef double
Definition at line 51 of file f8types.hpp.
using FIX8::gap_fill_flag = typedef Field<Boolean, Common_GapFillFlag>
Definition at line 2158 of file field.hpp.
using FIX8::GlobalLogger = typedef SingleLogger<glob_log0>
Definition at line 593 of file logger.hpp.
using FIX8::GroupElement = typedef std::vector<MessageBase *>
Definition at line 53 of file message.hpp.
using FIX8::GroupMap = typedef std::map<unsigned, struct MessageSpec>
Definition at line 120 of file f8c.hpp.
using FIX8::Groups = typedef std::map<unsigned short, GroupBase *>
Definition at line 56 of file message.hpp.
using FIX8::heartbeat_interval = typedef Field<int, Common_HeartBtInt>
Definition at line 2162 of file field.hpp.
using FIX8::Language = typedef f8String
Definition at line 2034 of file field.hpp.
using FIX8::Length = typedef EnumType<FieldTrait::ft_Length>
Definition at line 1735 of file field.hpp.
using FIX8::LocalMktDate = typedef EnumType<FieldTrait::ft_LocalMktDate>
Definition at line 1342 of file field.hpp.
using FIX8::logger_function = typedef std::function<bool(const std::string&, Logger::Level, const char *, const unsigned)>
Definition at line 576 of file logger.hpp.
using FIX8::MessageSpecMap = typedef std::map<const std::string, MessageSpec>
Definition at line 175 of file f8c.hpp.
using FIX8::MonthYear = typedef EnumType<FieldTrait::ft_MonthYear>
Definition at line 1445 of file field.hpp.
using FIX8::msg_create = typedef std::function<Message *(bool)>
Definition at line 202 of file message.hpp.
using FIX8::msg_seq_num = typedef Field<SeqNum, Common_MsgSeqNum>
Definition at line 2137 of file field.hpp.
using FIX8::msg_type = typedef Field<f8String, Common_MsgType>
Definition at line 2147 of file field.hpp.
using FIX8::MsgList = typedef std::deque<FIX8::Message *>
Definition at line 44 of file consolemenu.hpp.
using FIX8::MsgTable = typedef GeneratedTable<const char *, BaseMsgEntry>
Definition at line 203 of file message.hpp.
using FIX8::MultipleCharValue = typedef f8String
Definition at line 2029 of file field.hpp.
using FIX8::MultipleStringValue = typedef f8String
Definition at line 2030 of file field.hpp.
using FIX8::new_seq_num = typedef Field<SeqNum, Common_NewSeqNo>
Definition at line 2140 of file field.hpp.
using FIX8::NumInGroup = typedef EnumType<FieldTrait::ft_NumInGroup>
Definition at line 1840 of file field.hpp.
using FIX8::onbehalfof_comp_id = typedef Field<f8String, Common_OnBehalfOfCompID>
Definition at line 2166 of file field.hpp.
using FIX8::onbehalfof_location_id = typedef Field<f8String, Common_OnBehalfOfLocationID>
Definition at line 2168 of file field.hpp.
using FIX8::onbehalfof_sending_time = typedef Field<UTCTimestamp, Common_OnBehalfOfSendingTime>
Definition at line 2169 of file field.hpp.
using FIX8::onbehalfof_sub_id = typedef Field<f8String, Common_OnBehalfOfSubID>
Definition at line 2167 of file field.hpp.
using FIX8::orig_sending_time = typedef Field<UTCTimestamp, Common_OrigSendingTime>
Definition at line 2156 of file field.hpp.
using FIX8::Package_info = typedef std::map<f8String, f8String>
Definition at line 172 of file f8utils.hpp.
using FIX8::Percentage = typedef fp_type
Definition at line 2026 of file field.hpp.
using FIX8::Positions = typedef std::multimap<unsigned short, BaseField *>
Definition at line 378 of file message.hpp.
using FIX8::poss_dup_flag = typedef Field<Boolean, Common_PossDupFlag>
Definition at line 2159 of file field.hpp.
using FIX8::Presence = typedef presorted_set<unsigned short, FieldTrait, FieldTrait::Compare>
Definition at line 434 of file traits.hpp.
using FIX8::price = typedef fp_type
Definition at line 2024 of file field.hpp.
using FIX8::PriceOffset = typedef fp_type
Definition at line 2025 of file field.hpp.
using FIX8::Qty = typedef fp_type
Definition at line 2022 of file field.hpp.
using FIX8::RealmMap = typedef std::map<RealmObject *, std::string, RealmObject::less>
Definition at line 115 of file f8c.hpp.
using FIX8::ref_msg_type = typedef Field<f8String, Common_RefMsgType>
Definition at line 2153 of file field.hpp.
using FIX8::ref_seq_num = typedef Field<SeqNum, Common_RefSeqNum>
Definition at line 2141 of file field.hpp.
using FIX8::reset_seqnum_flag = typedef Field<Boolean, Common_ResetSeqNumFlag>
Definition at line 2160 of file field.hpp.
using FIX8::ReverseFieldTable = typedef std::map<const char * const, const BaseEntry *, c_str_compare>
Definition at line 206 of file message.hpp.
using FIX8::ReverseMsgTable = typedef std::map<const char * const, const BaseMsgEntry *, c_str_compare>
Definition at line 204 of file message.hpp.
using FIX8::sender_comp_id = typedef Field<f8String, Common_SenderCompID>
Definition at line 2145 of file field.hpp.
using FIX8::sending_time = typedef Field<UTCTimestamp, Common_SendingTime>
Definition at line 2155 of file field.hpp.
using FIX8::SeqNum = typedef EnumType<FieldTrait::ft_SeqNum>
Definition at line 1805 of file field.hpp.
using FIX8::SessionInstanceManager = typedef SessionManager<SessionInstanceBase>
Session Instance Manager.
Definition at line 186 of file multisession.hpp.
using FIX8::TagNum = typedef EnumType<FieldTrait::ft_TagNum>
Definition at line 1770 of file field.hpp.
using FIX8::target_comp_id = typedef Field<f8String, Common_TargetCompID>
Definition at line 2146 of file field.hpp.
using FIX8::test_request_id = typedef Field<f8String, Common_TestReqID>
Definition at line 2150 of file field.hpp.
using FIX8::text = typedef Field<f8String, Common_Text>
Definition at line 2151 of file field.hpp.
using FIX8::thread_id_t = typedef std::thread::id
Definition at line 58 of file thread.hpp.
using FIX8::TypeToCPP = typedef std::map<FieldTrait::FieldType, std::pair<std::string, std::string>>
Definition at line 124 of file f8c.hpp.
using FIX8::TZTimeOnly = typedef EnumType<FieldTrait::ft_TZTimeOnly>
Definition at line 1549 of file field.hpp.
using FIX8::TZTimestamp = typedef EnumType<FieldTrait::ft_TZTimestamp>
Definition at line 1642 of file field.hpp.
using FIX8::UTCDateOnly = typedef EnumType<FieldTrait::ft_UTCDateOnly>
Definition at line 1239 of file field.hpp.
using FIX8::UTCTimeOnly = typedef EnumType<FieldTrait::ft_UTCTimeOnly>
Definition at line 1136 of file field.hpp.
using FIX8::UTCTimestamp = typedef EnumType<FieldTrait::ft_UTCTimestamp>
Definition at line 1028 of file field.hpp.
using FIX8::XMLData = typedef f8String
Definition at line 2035 of file field.hpp.
Enumeration Type Documentation
enum FIX8::comp_str
Enumerator
cs_do_not_edit
cs_start_namespace
cs_end_namespace
cs_start_anon_namespace
cs_end_anon_namespace
cs_divider
cs_copyright
cs_copyright2
cs_generated_includes
cs_header_preamble
cs_trailer_preamble
Definition at line 186 of file f8c.hpp.
 {
    cs_do_not_edit,
    cs_start_namespace,
    cs_end_namespace,
    cs_start_anon_namespace,
    cs_end_anon_namespace,
    cs_divider,
    cs_copyright,
    cs_copyright2,
    cs_generated_includes,
    cs_header_preamble,
    cs_trailer_preamble,
 };
enum FIX8::hyperunits_t
Enumerator
h_seconds
h_milliseconds
h_microseconds
h_nanoseconds
h_count
Definition at line 43 of file hypersleep.hpp.
 { h_seconds, h_milliseconds, h_microseconds, h_nanoseconds, h_count };
enum FIX8::ProcessModel
Supported session process models.
Enumerator
pm_thread
pm_pipeline
pm_coro
pm_count
Definition at line 56 of file f8types.hpp.
 { pm_thread, pm_pipeline, pm_coro, pm_count };
enum FIX8::TimeIndicator
Enumerator
_time_only
_time_with_ms
_short_date_only
_date_only
_sec_only
_with_ms
Definition at line 882 of file field.hpp.
 { _time_only, _time_with_ms, _short_date_only, _date_only, _sec_only, _with_ms };
Function Documentation
constexpr unsigned FIX8::bitsum ()
empty argument version
Definition at line 826 of file f8utils.hpp.
Referenced by bitsum().
 { return 0; }
template<typename T , typename... Args> constexpr unsigned FIX8::bitsum (T value, Args... args)
Calculate the value of a set of bit positions, e.g. bitsum(1,3,5,6)
Template Parameters
T first value, used to unpack
Args remaining values
Returns
result
Definition at line 833 of file f8utils.hpp.
References bitsum().
    { return 1 << value | bitsum(args...); }
F8API std::string& FIX8::CheckAddTrailingSlash (std::string & source)
Check if string has trailing slash, if not add.
Parameters
source source string
Returns
reference to modified string
Referenced by FIX8::FilePersister::initialise(), main(), and open_ofile().
string& FIX8::CheckAddTrailingSlash (string & src)
Definition at line 122 of file f8utils.cpp.
 {
    if (!src.empty() && *src.rbegin() != '/')
       src += '/';
    return src;
 }
const unsigned short FIX8::Common_BeginSeqNo (7)
const unsigned short FIX8::Common_BeginString (8)
Referenced by FIX8::TEX::header::add_preamble(), FIX8::Message::encode(), process_special_traits(), and FIX8::Message::setup_reuse().
const unsigned short FIX8::Common_BodyLength (9)
Referenced by FIX8::TEX::header::add_preamble(), FIX8::MessageBase::decode(), FIX8::Message::encode(), process_special_traits(), and FIX8::Message::setup_reuse().
const unsigned short FIX8::Common_BusinessRejectReason (380)
const unsigned short FIX8::Common_CheckSum (10)
Referenced by FIX8::TEX::trailer::add_preamble(), FIX8::Message::encode(), process_special_traits(), and FIX8::Message::setup_reuse().
const unsigned short FIX8::Common_DefaultApplVerID (1137)
const unsigned short FIX8::Common_EncryptMethod (98)
const unsigned short FIX8::Common_EndSeqNo (16)
const unsigned short FIX8::Common_GapFillFlag (123)
const unsigned short FIX8::Common_HeartBtInt (108)
const char FIX8::Common_MsgByte_BUSINESS_REJECT ('j')
const char FIX8::Common_MsgByte_HEARTBEAT ('0')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_LOGON ('A')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_LOGOUT ('5')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_REJECT ('3')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_RESEND_REQUEST ('2')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_SEQUENCE_RESET ('4')
Referenced by FIX8::Session::process().
const char FIX8::Common_MsgByte_TEST_REQUEST ('1')
Referenced by FIX8::Session::process().
const unsigned short FIX8::Common_MsgSeqNum (34)
Referenced by FIX8::Session::send_process(), and FIX8::Message::setup_reuse().
const unsigned short FIX8::Common_MsgType (35)
Referenced by FIX8::TEX::header::add_preamble(), and process_special_traits().
const f8String FIX8::Common_MsgType_BUSINESS_REJECT ("j")
Referenced by FIX8::Session::generate_business_reject().
const f8String FIX8::Common_MsgType_HEARTBEAT ("0")
Referenced by FIX8::Session::generate_heartbeat(), and FIX8::Session::process().
const f8String FIX8::Common_MsgType_LOGON ("A")
Referenced by FIX8::Session::generate_logon().
const f8String FIX8::Common_MsgType_LOGOUT ("5")
Referenced by FIX8::Session::generate_logout().
const f8String FIX8::Common_MsgType_REJECT ("3")
Referenced by FIX8::Session::generate_reject().
const f8String FIX8::Common_MsgType_RESEND_REQUEST ("2")
Referenced by FIX8::Session::generate_resend_request().
const f8String FIX8::Common_MsgType_SEQUENCE_RESET ("4")
Referenced by FIX8::Session::enforce(), FIX8::Session::generate_sequence_reset(), and FIX8::Session::send_process().
const f8String FIX8::Common_MsgType_TEST_REQUEST ("1")
Referenced by FIX8::Session::generate_test_request().
const unsigned short FIX8::Common_NewSeqNo (36)
const unsigned short FIX8::Common_OnBehalfOfCompID (115)
const unsigned short FIX8::Common_OnBehalfOfLocationID (144)
const unsigned short FIX8::Common_OnBehalfOfSendingTime (370)
const unsigned short FIX8::Common_OnBehalfOfSubID (116)
const unsigned short FIX8::Common_OrigSendingTime (122)
const unsigned short FIX8::Common_PossDupFlag (43)
Referenced by FIX8::Session::send_process().
const unsigned short FIX8::Common_RefMsgType (372)
const unsigned short FIX8::Common_RefSeqNum (45)
const unsigned short FIX8::Common_ResetSeqNumFlag (141)
Referenced by FIX8::Session::handle_logon().
const unsigned short FIX8::Common_SenderCompID (49)
Referenced by FIX8::Session::send_process().
const unsigned short FIX8::Common_SendingTime (52)
Referenced by MyMenu::load_msgs().
const unsigned short FIX8::Common_TargetCompID (56)
Referenced by FIX8::Session::send_process().
const unsigned short FIX8::Common_TestReqID (112)
const unsigned short FIX8::Common_Text (58)
char* FIX8::CopyString (const std::string & src, char * target, unsigned limit = 0) inline
Copy a string safely to a target.
Parameters
src source string
target target location
limit maximum bytes to copy, 0 for no limit
Returns
pointer to target
Definition at line 1100 of file f8utils.hpp.
Referenced by FIX8::SingleLogger< fn >::set_global_filename().
 {
    if (!target)
       return nullptr;
    const unsigned sz(limit && static_cast<unsigned>(src.size()) > limit ? limit : (unsigned)src.size() + 1);
    src.copy(target, sz - 1);
    target[sz - 1] = 0;
    return target;
 }
void FIX8::create_path (const string & path)
Definition at line 197 of file f8utils.cpp.
 {
    string new_path;
    for(string::const_iterator pos(path.begin()); pos != path.end(); ++pos)
    {
       new_path += *pos;
       if(*pos == '/' || *pos == '\\' || pos + 1 == path.end())
       {
 #ifdef _MSC_VER
          _mkdir(new_path.c_str());
 #else
          mkdir(new_path.c_str(), 0777); // umask applied after
 #endif
       }
    }
 }
F8API void FIX8::create_path (const std::string & path)
Create a full path, including nested directories
Parameters
path path to create
Referenced by FIX8::FileLogger::rotate().
Tickval::ticks FIX8::date_parse (const char * ptr, size_t len) inline
Definition at line 1010 of file field.hpp.
References FIX8::Tickval::billion, FIX8::Tickval::get_ticks(), parse_decimal(), and time_to_epoch().
 {
    if (len == 0 || (*ptr == 'n' && len == 3 && *(ptr + 1) == 'o' && *(ptr + 2) == 'w'))   // special cases initialise to 'now'
       return Tickval(true).get_ticks();
    tm tms {};
    ptr += parse_decimal(ptr, 4, tms.tm_year);
    tms.tm_year -= 1900;
    ptr += parse_decimal(ptr, 2, tms.tm_mon);
    --tms.tm_mon;
    if (len == 8)
       parse_decimal(ptr, 2, tms.tm_mday);
    else
       tms.tm_mday = 1;
    return time_to_epoch(tms) * Tickval::billion;
 }
size_t FIX8::date_time_format (const Tickval & tickval, char * to, TimeIndicator ind) inline
Format Tickval into a string.
Parameters
tickval input Tickval object
to output buffer, should make sure there is enough space reserved
ind indicating whether need millisecond or not _time_only, the format string will be "HH:MM:SS" _time_with_ms, the format string will be "HH:MM:SS.mmm" _short_date_only, the format string will be "YYYYMM" _date_only, the format string will be "YYYYMMDD" _sec_only, the format string will be "YYYYMMDD-HH:MM:SS" _with_ms, the format string will be "YYYYMMDD-HH:MM:SS.mmm"
Returns
length of formatted string
Definition at line 895 of file field.hpp.
References _date_only, _short_date_only, _time_with_ms, _with_ms, format0(), FIX8::Tickval::get_tm(), and FIX8::Tickval::msecs().
Referenced by FIX8::Field< UTCTimestamp, field >::print(), FIX8::Field< UTCTimeOnly, field >::print(), FIX8::Field< UTCDateOnly, field >::print(), FIX8::Field< LocalMktDate, field >::print(), and FIX8::Field< MonthYear, field >::print().
 {
    const tm result(tickval.get_tm());
    const char *start(to);
    if (ind > _time_with_ms)
    {
       format0(result.tm_year + 1900, to, 4);
       to += 4;
       format0(result.tm_mon + 1, to, 2);
       to += 2;
       if (ind == _short_date_only)
          return to - start;
       format0(result.tm_mday, to, 2);
       to += 2;
       if (ind == _date_only)
          return to - start;
       *to++ = '-';
    }
    format0(result.tm_hour, to, 2);
    to += 2;
    *to++ = ':';
    format0(result.tm_min, to, 2);
    to += 2;
    *to++ = ':';
    format0(result.tm_sec, to, 2);
    to += 2;
    if (ind == _time_with_ms || ind == _with_ms)
    {
       *to++ = '.';
       format0(tickval.msecs(), to, 3);
       to += 3;
    }
    return to - start;
 }
Tickval::ticks FIX8::date_time_parse (const char * ptr, size_t len) inline
Decode a DateTime string into ticks
Parameters
ptr input DateTime string, if *ptr == '!' return current time
len length of string
Returns
ticks decoded
Definition at line 938 of file field.hpp.
References FIX8::Tickval::billion, FIX8::Tickval::get_ticks(), FIX8::Tickval::million, FIX8::Tickval::noticks, parse_decimal(), and time_to_epoch().
 {
    if (len == 0 || (*ptr == 'n' && len == 3 && *(ptr + 1) == 'o' && *(ptr + 2) == 'w'))   // special cases initialise to 'now'
       return Tickval(true).get_ticks();
    Tickval::ticks result(Tickval::noticks);
    int millisecond(0);
    tm tms {};
    ptr += parse_decimal(ptr, 4, tms.tm_year);
    tms.tm_year -= 1900;
    ptr += parse_decimal(ptr, 2, tms.tm_mon);
    --tms.tm_mon;
    ptr += parse_decimal(ptr, 2, tms.tm_mday);
    ++ptr;
    ptr += parse_decimal(ptr, 2, tms.tm_hour);
    ++ptr;
    ptr += parse_decimal(ptr, 2, tms.tm_min);
    ++ptr;
    ptr += parse_decimal(ptr, 2, tms.tm_sec);
    switch(len)
    {
    case 21: //_with_ms: // 19981231-23:59:59.123
       parse_decimal(++ptr, 3, millisecond);
       result = millisecond * Tickval::million; // drop through
    case 17: //: // 19981231-23:59:59
       result += time_to_epoch(tms) * Tickval::billion;
       break;
    default:
       break;
    }
    return result;
 }
F8API int FIX8::decode_dow (const std::string & from)
Decode a weekday name into numeric dow (0=SUN), case insensitive only check at most the first 2 unique characters (will ignore any characters after that); alternatively, accept numeric dow 0-6;
Parameters
from source dow string
Returns
idx dow or -1 if not found
Referenced by FIX8::Configuration::create_schedule().
int FIX8::decode_dow (const string & from)
Definition at line 224 of file f8utils.cpp.
References StrToLower().
 {
    if (from.empty())
       return -1;
    const string source(StrToLower(from));
    if (isdigit(source[0]) && source.size() == 1 && source[0] >= '0' && source[0] <= '6')  // accept numeric dow
       return source[0] - '0';
    pair<Daymap::const_iterator, Daymap::const_iterator> result(daymap.equal_range(source[0]));
    switch(distance(result.first, result.second))
    {
    case 1:
       return result.first->second;
    default:
       if (source.size() == 1) // drop through
    case 0:
          return -1;
       break;
    }
    return day_names[result.first->second][1] == source[1]
        || day_names[(++result.first)->second][1] == source[1] ? result.first->second : -1;
 }
const unsigned char FIX8::default_assignment_separator (' = ')
default FIX assignment separator (=)
Referenced by FIX8::BaseField::encode(), FIX8::MessageBase::extract_element(), and FIX8::MessageBase::extract_element_fixed_width().
const unsigned char FIX8::default_field_separator (0x1)
default FIX field separator (^A)
Referenced by FIX8::BaseField::encode(), FIX8::MessageBase::extract_element(), FIX8::Session::process(), and FIX8::FIXReader::read().
template<typename T > T FIX8::enum_str_get (const std::vector< std::string > & sset, const std::string & what, const T def, bool ignorecase = false)
From a set of strings representing the names of an enumeration in order, return the enum of the given string.
Template Parameters
T enum return type
Parameters
sset the set of strings; if null return default value
what the string to find
def the default value to return if not found
ignorecase if true, ignore case
Returns
enum value or default
Definition at line 1048 of file f8utils.hpp.
Referenced by FIX8::Configuration::get_process_model().
 {
    if (sset.empty())
       return def;
    auto itr(sset.cbegin());
    for (; itr != sset.cend(); ++itr)
       if (ignorecase ? *itr % what : *itr == what)
          break;
    return itr == sset.cend() ? def : static_cast<T>(std::distance(sset.begin(), itr));
 }
bool FIX8::exist (const std::string & fname) inline
Check for file existance.
Parameters
fname filename to check
Returns
true if file exists
Definition at line 1068 of file f8utils.hpp.
Referenced by FIX8::Configuration::Configuration(), FIX8::FilePersister::initialise(), open_ofile(), FIX8::FileLogger::rotate(), and MyMenu::save_msg().
 {
 #ifdef _MSC_VER
    return _access(fname.c_str(), 0) == 0;
 #else
    return access(fname.c_str(), F_OK) == 0;
 #endif
 }
fp_type FIX8::fast_atof (const char * p) inline
Simple and fast atof (ascii to float) function. Executes about 5x faster than standard MSCRT library atof(). An attractive alternative if the number of calls is in the millions. Assumes input is a proper integer, fraction, or scientific format. Matches library atof() to 15 digits (except at extreme exponents). Follows atof() precedent of essentially no error checking. 09-May-2009 Tom Van Baak (tvb) www.LeapSecond.com
Parameters
p source string
Returns
double converted value
Definition at line 727 of file f8utils.hpp.
Referenced by FIX8::Field< fp_type, field >::set_from_raw().
 {
    bool frac(false);
    fp_type sign(1.), value(0.), scale(1.);
    while (isspace(*p))
       ++p;
    // Get sign, if any.
    if (*p == '-')
    {
       sign = -1.;
       ++p;
    }
    else if (*p == '+')
       ++p;
    // Get digits before decimal point or exponent, if any.
    while (isdigit(*p))
    {
       value = value * 10. + (*p - '0');
       ++p;
    }
    // Get digits after decimal point, if any.
    if (*p == '.')
    {
       ++p;
       fp_type mpow10(10.);
       while (isdigit(*p))
       {
          value += (*p - '0') / mpow10;
          mpow10 *= 10.;
          ++p;
       }
    }
    // Handle exponent, if any.
    if (toupper(*p) == 'E')
    {
       unsigned int expon(0);
       ++p;
    // Get sign of exponent, if any.
       if (*p == '-')
       {
          frac = true;
          ++p;
       }
       else if (*p == '+')
          ++p;
    // Get digits of exponent, if any.
       while (isdigit(*p))
       {
          expon = expon * 10 + (*p - '0');
          ++p;
       }
 #if defined FIX8_USE_SINGLE_PRECISION
       if (expon > 38)
          expon = 38;
 #else
       if (expon > 308)
          expon = 308;
    // Calculate scaling factor.
       while (expon >= 50)
       {
          scale *= 1E50;
          expon -= 50;
       }
 #endif
       while (expon >= 8)
       {
          scale *= 1E8;
          expon -=  8;
       }
       while (expon > 0)
       {
          scale *= 10.0;
          expon -=  1;
       }
    }
    // Return signed and scaled floating point result.
    return sign * (frac ? (value / scale) : (value * scale));
 }
template<typename T > T FIX8::fast_atoi (const char * str, const char term = '\0')
Decode a string into an int or unsigned.
Template Parameters
typename
Parameters
str source string
term terminating character, default = 0
Returns
the converted value
Definition at line 626 of file f8utils.hpp.
 {
    T retval(0);
    for (; *str != term; ++str)
       retval = (retval << 3) + (retval << 1) + *str - '0';
    return retval;
 }
f8String FIX8::find_package_info_string (const f8String & what)
Find a Package_info string value for the given tag
Parameters
what source string to look up
Returns
Package_info string value or an empty string
Definition at line 301 of file f8utils.cpp.
References package_info().
 {
    auto itr(package_info().find(what));
    return itr != package_info().cend() ? itr->second : f8String{};
 }
void FIX8::format0 (int data, char * to, int width) inline
Format ASCII decimal value
Parameters
data source value
to target location for string
width len of string
Returns
number bytes decoded
Definition at line 830 of file field.hpp.
Referenced by date_time_format().
 {
    while(width-- > 0)
    {
       to[width] = data % 10 + '0';
       data /= 10;
    }
 }
int FIX8::get_umask ()
Get the current file umask
Returns
int file mask
Definition at line 184 of file f8utils.cpp.
 {
 #ifdef _MSC_VER
    const int mask(_umask(0));
    _umask(mask);
 #else
    const int mask(umask(0));
    umask(mask);
 #endif
    return mask;
 }
template<typename T > T FIX8::get_value (const std::string & source) inline
Extract a typed value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 564 of file f8utils.hpp.
Referenced by FIX8::MessageBase::extract_element().
 {
    std::istringstream istr(source);
    T result((T()));
    istr >> result;
    return result;
 }
template<> unsigned FIX8::get_value (const std::string & source) inline
Extract a unsigned value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 577 of file f8utils.hpp.
 { return std::stoul(source); }
template<> int FIX8::get_value (const std::string & source) inline
Extract a int value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 584 of file f8utils.hpp.
 { return std::stoi(source); }
template<> double FIX8::get_value (const std::string & source) inline
Extract a double value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 591 of file f8utils.hpp.
 { return std::stod(source); }
template<> float FIX8::get_value (const std::string & source) inline
Extract a float value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 598 of file f8utils.hpp.
 { return std::stof(source); }
template<> bool FIX8::get_value (const std::string & source) inline
Extract a bool value from a string.
Template Parameters
typename
Parameters
source source string
Returns
the extracted value.
Definition at line 605 of file f8utils.hpp.
 {
    if (source.empty())
       return false;
 #if !defined FIX8_XMLENTITY_STRICT_BOOL
    return source % "true" || source % "yes" || source % "y" || source == "1";
 #else
    bool result(false);
    std::istringstream istr(source);
    istr >> std::boolalpha >> result;
    return result;
 #endif
 }
const string& FIX8::GetTimeAsStringMini (string & result, const Tickval * tv)
Definition at line 91 of file f8utils.cpp.
References FIX8::Tickval::now(), and FIX8::Tickval::secs().
 {
    const Tickval *startTime;
    Tickval gotTime;
    if (tv)
       startTime = tv;
    else
    {
       gotTime.now();
       startTime = &gotTime;
    }
 #ifdef _MSC_VER
    time_t tval(startTime->secs());
    struct tm *ptim(localtime (&tval));
 #else
    struct tm tim, *ptim;
    time_t tval(startTime->secs());
    localtime_r(&tval, &tim);
    ptim = &tim;
 #endif
 // 14-07-02 23:15:51
    ostringstream oss;
    oss << setfill('0') << setw(2) << ((ptim->tm_year + 1900) % 100) << '-';
    oss << setw(2) << (ptim->tm_mon + 1)  << '-' << setw(2) << ptim->tm_mday << ' ' << setw(2) << ptim->tm_hour;
    oss << ':' << setw(2) << ptim->tm_min << ':' << setfill('0') << setw(2) << ptim->tm_sec;
    return result = oss.str();
 }
F8API const std::string& FIX8::GetTimeAsStringMini (std::string & result, const Tickval * tv)
Format Tickval into mini string. 14-07-02 23:15:51
Parameters
result target string
tv tickval to use or 0 for current time
Returns
reference to target string
Referenced by GetTimeAsStringMini(), FIX8::Logger::process_logline(), and FIX8::XmlFileLogger::process_logline().
std::string FIX8::GetTimeAsStringMini (const Tickval * tv) inline
Format Tickval into mini string. 14-07-02 23:15:51
Parameters
tv tickval to use or 0 for current time
Returns
string
Definition at line 142 of file f8utils.hpp.
References GetTimeAsStringMini().
 {
    std::string result;
    GetTimeAsStringMini(result, tv);
    return result;
 }
const string& FIX8::GetTimeAsStringMS (string & result, const Tickval * tv, const unsigned dplaces, bool use_gm)
Definition at line 51 of file f8utils.cpp.
References FIX8::Tickval::now(), FIX8::Tickval::nsecs(), and FIX8::Tickval::secs().
 {
    const Tickval *startTime;
    Tickval gotTime;
    if (tv)
       startTime = tv;
    else
    {
       gotTime.now();
       startTime = &gotTime;
    }
 #ifdef _MSC_VER
    time_t tval(startTime->secs());
    struct tm *ptim(use_gm ? gmtime(&tval) : localtime (&tval));
 #else
    struct tm tim, *ptim;
    time_t tval(startTime->secs());
    use_gm ? gmtime_r(&tval, &tim) : localtime_r(&tval, &tim);
    ptim = &tim;
 #endif
    // 2014-07-02 23:15:51.514776595
    ostringstream oss;
    oss << setfill('0') << setw(4) << (ptim->tm_year + 1900) << '-';
    oss << setw(2) << (ptim->tm_mon + 1)  << '-' << setw(2) << ptim->tm_mday << ' ' << setw(2) << ptim->tm_hour;
    oss << ':' << setw(2) << ptim->tm_min << ':';
    if (dplaces)
    {
       const double secs((startTime->secs() % 60) + static_cast<double>(startTime->nsecs()) / Tickval::billion);
       oss.setf(ios::showpoint);
       oss.setf(ios::fixed);
       oss << setw(3 + dplaces) << setfill('0') << setprecision(dplaces) << secs;
    }
    else
       oss << setfill('0') << setw(2) << ptim->tm_sec;
    return result = oss.str();
 }
F8API const std::string& FIX8::GetTimeAsStringMS (std::string & result, const class Tickval * tv = 0, const unsigned dplaces = 6, bool use_gm = false)
Format Tickval into string. 2014-07-02 23:15:51.514776595
Parameters
result target string
tv tickval to use or 0 for current time
dplaces number of decimal places to report seconds (default 6)
use_gm if true, use gmtime, if false localtime
Returns
reference to target string
Referenced by generate_preamble(), and GetTimeAsStringMS().
std::string FIX8::GetTimeAsStringMS (const class Tickval * tv, const unsigned dplaces = 6, bool use_gm = false) inline
Format Tickval into string. 2014-07-02 23:15:51.514776595
Parameters
tv tickval to use or 0 for current time
dplaces number of decimal places to report seconds (default 6)
use_gm if true, use gmtime, if false localtime
Returns
string
Definition at line 126 of file f8utils.hpp.
References GetTimeAsStringMS().
 {
    std::string result;
    GetTimeAsStringMS(result, tv, dplaces, use_gm);
    return result;
 }
const size_t FIX8::HEADER_CALC_OFFSET (32)
Referenced by FIX8::Message::encode(), FIX8::Session::send_process(), and FIX8::Session::Session().
template<hyperunits_t > int FIX8::hypersleep (unsigned amt) inline
int FIX8::hypersleep (unsigned amt, hyperunits_t units) inline
A more reliable high precision sleep
Parameters
amt amount to sleep
units units that sleep value is in
Returns
0 on success
Definition at line 171 of file hypersleep.hpp.
References h_count.
 {
    enum { Div, Mul, Operation };
    static const unsigned hv[h_count][Operation]
    {
       { 1,            billion    }, // Seconds
       { thousand,     million    }, // Milliseconds
       { million,      thousand   }, // Microseconds
       { billion,      1          }, // Nanoseconds
    };
 #if defined FIX8_HAVE_CLOCK_NANOSLEEP
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ts.tv_sec += (amt / hv[units][Div]);    // calculate time to sleep in secs
    ts.tv_nsec += (hv[units][Mul] * (amt % hv[units][Div]));   // calculate time to sleep in nsecs
    return execute_clock_nanosleep(ts);
 #elif defined _MSC_VER
    Sleep(amt); // milliseconds
    return 0;
 #else
    const timespec tspec { amt / hv[units][Div], hv[units][Mul] * (amt % hv[units][Div]) };
    return nanosleep(&tspec, 0);
 #endif
 }
template<> int FIX8::hypersleep< h_microseconds > (unsigned amt) inline
A more reliable high precision sleep, microseconds specialisation
Parameters
amt amount to sleep
Returns
0 on success
Definition at line 127 of file hypersleep.hpp.
Referenced by FIX8::Logger::operator()().
 {
 #if defined FIX8_HAVE_CLOCK_NANOSLEEP
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ts.tv_sec += (amt / million);
    ts.tv_nsec += (thousand * (amt % million));
    return execute_clock_nanosleep(ts);
 #elif defined _MSC_VER
    Sleep(amt / million * thousand);
    return 0;
 #else
    const timespec tspec { amt / million, thousand * (amt % million) };
    return nanosleep(&tspec, 0);
 #endif
 }
template<> int FIX8::hypersleep< h_milliseconds > (unsigned amt) inline
A more reliable high precision sleep, milliseconds specialisation
Parameters
amt amount to sleep
Returns
0 on success
Definition at line 105 of file hypersleep.hpp.
Referenced by FIX8::ClientConnection::connect(), FIX8::Timer< T >::operator()(), FIX8::ReliableClientSession< T >::operator()(), server_process(), and FIX8::Session::stop().
 {
 #if defined FIX8_HAVE_CLOCK_NANOSLEEP
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ts.tv_sec += (amt / thousand);
    ts.tv_nsec += (million * (amt % thousand));
    return execute_clock_nanosleep(ts);
 #elif defined _MSC_VER
    Sleep(amt); // milliseconds
    return 0;
 #else
    const timespec tspec { amt / thousand, million * (amt % thousand) };
    return nanosleep(&tspec, 0);
 #endif
 }
template<> int FIX8::hypersleep< h_nanoseconds > (unsigned amt) inline
A more reliable high precision sleep, nanoseconds specialisation
Parameters
amt amount to sleep
Returns
0 on success
Definition at line 149 of file hypersleep.hpp.
Referenced by FIX8::ff_unbounded_queue< T >::pop(), and FIX8::ff_unbounded_queue< T * >::pop().
 {
 #if defined FIX8_HAVE_CLOCK_NANOSLEEP
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ts.tv_sec += (amt / billion);
    ts.tv_nsec += amt;
    return execute_clock_nanosleep(ts);
 #elif defined _MSC_VER
    Sleep(amt / billion * million);
    return 0;
 #else
    const timespec tspec { amt / billion, amt };
    return nanosleep(&tspec, 0);
 #endif
 }
template<> int FIX8::hypersleep< h_seconds > (unsigned amt) inline
A more reliable high precision sleep, seconds specialisation
Parameters
amt amount to sleep
Returns
0 on success
Definition at line 83 of file hypersleep.hpp.
Referenced by MyMenu::do_logout(), main(), and FIX8::Session::~Session().
 {
 #if defined FIX8_HAVE_CLOCK_NANOSLEEP
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ts.tv_sec += amt;
    ts.tv_nsec += (amt % (billion));
    return execute_clock_nanosleep(ts);
 #elif defined _MSC_VER
    Sleep(amt * thousand);
    return 0;
 #else
    const timespec tspec { amt, amt % billion };
    return nanosleep(&tspec, 0);
 #endif
 }
template<typename T > void FIX8::ignore_value (T val) inline
Sidestep the warn_unused_result attribute
Template Parameters
T type
Parameters
val value to ignore
Definition at line 188 of file f8utils.hpp.
Referenced by Str_error().
 { (void) val; }
template<typename T > void FIX8::ignore_value (T * val) inline
Sidestep the warn_unused_result attribute, ptr version
Template Parameters
T type
Parameters
val * value to ignore
Definition at line 194 of file f8utils.hpp.
 { (void) val; }
F8API std::string& FIX8::InPlaceReplaceInSet (const std::string & iset, std::string & src, const char repl = '_')
Replace any character found in the supplied set in string with supplied character
Parameters
iset set of characters
src source string
repl character to replace
Returns
reference to modified string
Referenced by process_value_enums().
string& FIX8::InPlaceReplaceInSet (const string & iset, string & src, const char repl)
Definition at line 140 of file f8utils.cpp.
 {
    for (string::iterator itr(src.begin()); itr != src.end(); ++itr)
       if (iset.find(*itr) == string::npos)
          *itr = repl;
    return src;
 }
F8API std::string& FIX8::InPlaceStrToLower (std::string & src)
In place string to lower case.
Parameters
src source string
Returns
reference to modified string
string& FIX8::InPlaceStrToLower (string & src)
Definition at line 149 of file f8utils.cpp.
Referenced by StrToLower().
 {
    for (auto& itr : src)
       if (isupper(itr))
          itr = tolower(itr);
    return src;
 }
F8API std::string& FIX8::InPlaceStrToUpper (std::string & src)
In place string to upper case.
Parameters
src source string
Returns
reference to modified string
Referenced by load_fields().
string& FIX8::InPlaceStrToUpper (string & src)
Definition at line 130 of file f8utils.cpp.
 {
    //for (string::iterator itr(src.begin()); itr != src.end(); ++itr)
    for (auto& itr : src)
       if (islower(itr))
          itr = toupper(itr);
    return src;
 }
template<typename T > size_t FIX8::itoa (T value, char * result, int base) inline
Fast itoa.
C++ version 0.4 char* style "itoa": Written by Lukas Chmela see http://www.strudel.org.uk/itoa
Template Parameters
T source type
Parameters
value source value
result target
base base
Returns
size in bytes encoded
Definition at line 647 of file f8utils.hpp.
Referenced by FIX8::BaseField::encode(), and FIX8::Field< int, field >::print().
 {
    // check that the base if valid
    if (base < 2 || base > 36)
    {
       *result = 0;
       return 0;
    }
    char *ptr(result), *ptr1(result);
    T tmp_value;
    do
    {
       tmp_value = value;
       value /= base;
       *ptr++ = "zyxwvutsrqponmlkjihgfedcba9876543210123456789abcdefghijklmnopqrstuvwxyz" [35 + (tmp_value - value * base)];
    }
    while (value);
    // Apply negative sign
    if (tmp_value < 0)
       *ptr++ = '-';
    *ptr-- = 0;
    while(ptr1 < ptr)
    {
       const char tmp_char(*ptr);
       *ptr-- = *ptr1;
       *ptr1++ = tmp_char;
    }
    return ::strlen(result);
 }
template<> size_t FIX8::itoa< unsigned int > (unsigned int value, char * result, int base) inline
Fast itoa - unsigned int specialisation.
Template Parameters
T source type
Parameters
value source value
result target
base base
Returns
size in bytes encoded
Definition at line 687 of file f8utils.hpp.
 {
    // check that the base if valid
    if (base < 2 || base > 36)
    {
       *result = 0;
       return 0;
    }
    char *ptr(result), *ptr1(result);
    unsigned int tmp_value;
    do
    {
       tmp_value = value;
       value /= base;
       *ptr++ = "zyxwvutsrqponmlkjihgfedcba9876543210123456789abcdefghijklmnopqrstuvwxyz" [35 + (tmp_value - value * base)];
    }
    while (value);
    *ptr-- = 0;
    while(ptr1 < ptr)
    {
       const char tmp_char(*ptr);
       *ptr-- = *ptr1;
       *ptr1++ = tmp_char;
    }
    return ::strlen(result);
 }
const size_t FIX8::max_global_filename_length (1024)
Referenced by FIX8::SingleLogger< fn >::set_global_filename().
const size_t FIX8::MAX_MSGTYPE_FIELD_LEN (32)
Referenced by FIX8::MessageBase::extract_header(), FIX8::Message::factory(), FIX8::Field< UTCTimestamp, field >::print(), FIX8::Field< UTCTimeOnly, field >::print(), FIX8::Field< UTCDateOnly, field >::print(), FIX8::Field< LocalMktDate, field >::print(), FIX8::Field< MonthYear, field >::print(), and FIX8::FIXReader::read().
size_t FIX8::modp_dtoa (double value, char * str, int prec)
Convert double to ascii.
Parameters
value the source value
str the target string
prec number of precision digits
Definition at line 68 of file modp_numtoa.c.
References pow10_, and strreverse().
Referenced by FIX8::Field< fp_type, field >::print().
 {
    /* if input is larger than thres_max, revert to exponential */
     const double thres_max = (double)(0x7FFFFFFF);
     double diff = 0.0;
     char* wstr = str;
    int neg = 0;
    int whole = 0;
     double tmp = 0.0;
     uint32_t frac = 0;
     /* Hacky test for NaN
      * under -fast-math this won't work, but then you also won't
      * have correct nan values anyways.  The alternative is
      * to link with libmath (bad) or hack IEEE double bits (bad)
      */
     if (! (value == value)) {
         str[0] = 'n'; str[1] = 'a'; str[2] = 'n'; str[3] = '\0';
         return 3; // DD
     }
     if (prec < 0) {
         prec = 0;
     } else if (prec > 9) {
         /* precision of >= 10 can lead to overflow errors */
         prec = 9;
     }
     /* we'll work in positive values and deal with the
        negative sign issue later */
     if (value < 0) {
         neg = 1;
         value = -value;
     }
     whole = (int) value;
     tmp = (value - whole) * pow10_[prec];
     frac = (uint32_t)(tmp);
     diff = tmp - frac;
     if (diff > 0.5) {
         ++frac;
         /* handle rollover, e.g.  case 0.99 with prec 1 is 1.0  */
         if (frac >= pow10_[prec]) {
             frac = 0;
             ++whole;
         }
     } else if (diff == 0.5 && ((frac == 0) || (frac & 1))) {
         /* if halfway, round up if odd, OR
            if last digit is 0.  That last part is strange */
         ++frac;
     }
     /* for very large numbers switch back to native sprintf for exponentials.
        anyone want to write code to replace this? */
     /*
       normal printf behavior is to print EVERY whole number digit
       which can be 100s of characters overflowing your buffers == bad
     */
     if (value > thres_max)
         return sprintf(str, "%e", neg ? -value : value); // DD
     if (prec == 0) {
         diff = value - whole;
         if (diff > 0.5) {
             /* greater than 0.5, round up, e.g. 1.6 -> 2 */
             ++whole;
         } else if (diff == 0.5 && (whole & 1)) {
             /* exactly 0.5 and ODD, then round up */
             /* 1.5 -> 2, but 2.5 -> 2 */
             ++whole;
         }
     } else {    // these mods DD: remove trailing zero in prec (unless there is only one 0)
         int count = prec, done = 0;
         // now do fractional part, as an unsigned number
         do
         {
             --count;
             if (frac % 10)
                 done += (*wstr++ = (char)(48 + (frac % 10)));
             else if (done)
                 *wstr++ = '0';
         }
         while (frac /= 10);
         // add extra 0s
         if (!done)
             *wstr++ = '0';
         else
             while (count-- > 0)
                 *wstr++ = '0';
         // add decimal
         *wstr++ = '.';
     }
     // do whole part
     // Take care of sign
     // Conversion. Number is reversed.
     do
         *wstr++ = (char)(48 + (whole % 10));
     while (whole /= 10);
     if (neg)
         *wstr++ = '-';
     *wstr = 0;
     strreverse(str, wstr-1);
     return wstr - str; // DD
 }
template<typename _CharT , typename _Traits , typename _Alloc > bool FIX8::operator% (const std::basic_string< _CharT, _Traits, _Alloc > & __lhs, const std::basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
case insensitive std::string == std::string operator
Template Parameters
_CharT char type
_Traits char traits
_Alloc allocator
Parameters
__lhs left hand value
__rhs right hand value
Returns
true if strings are equivalent
Definition at line 245 of file f8utils.hpp.
 {
 #ifdef _MSC_VER
    return _stricmp(__lhs.c_str(), __rhs.c_str()) == 0;
 #else
    return strcasecmp(__lhs.c_str(), __rhs.c_str()) == 0;
 #endif
 }
template<typename _CharT , typename _Traits , typename _Alloc > bool FIX8::operator% (const _CharT * __lhs, const std::basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
case insensitive char* == std::string operator
Template Parameters
_CharT char type
_Traits char traits
_Alloc allocator
Parameters
__lhs left hand value
__rhs right hand value
Returns
true if strings are equivalent
Definition at line 263 of file f8utils.hpp.
       { return strcasecmp(__lhs, __rhs.c_str()) == 0; }
template<typename _CharT , typename _Traits , typename _Alloc > bool FIX8::operator% (const std::basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
case insensitive std::string == char* operator
Template Parameters
_CharT char type
_Traits char traits
_Alloc allocator
Parameters
__lhs left hand value
__rhs right hand value
Returns
true if strings are equivalent
Definition at line 274 of file f8utils.hpp.
 {
 #ifdef _MSC_VER
    return _stricmp(__lhs.c_str(), __rhs) == 0;
 #else
    return strcasecmp(__lhs.c_str(), __rhs) == 0;
 #endif
 }
ostream & FIX8::operator<< (std::ostream & os, const FieldTrait & what)
Inserter friend.
Parameters
os stream to send to
what FieldTrait
Returns
stream
Definition at line 45 of file traits.cpp.
References FIX8::FieldTrait::_component, FIX8::FieldTrait::_field_traits, FIX8::FieldTrait::_fnum, FIX8::FieldTrait::_ftype, FIX8::FieldTrait::_pos, FIX8::FieldTrait::count, FIX8::ebitset< T, B >::get(), and FIX8::FieldTrait::get_type_string().
 {
    static const vector<string> bts { "mandatory", "present", "position", "group", "component", "suppress", "automatic" };
    os << "Tag:" << what._fnum << " Type:" << what._ftype << " (";
    string strtype;
    os << FieldTrait::get_type_string(what._ftype, strtype);
    os << ") Pos:" << what._pos;
    if (what._component)
       os << " Component:" << what._component;
    os << " Flags:";
    for (unsigned ii(what._field_traits.get()), pos(0); pos < FieldTrait::count; ++pos)
       if (ii >> pos & 0x1)
          os << bts[pos] << ' ';
    return os;
 }
ostream & FIX8::operator<< (std::ostream & os, const FieldTraits & what)
Inserter friend.
Parameters
os stream to send to
what FieldTraits
Returns
stream
Definition at line 62 of file traits.cpp.
References FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::begin(), FIX8::presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >::end(), and FIX8::FieldTraits::get_presence().
 {
    copy(what.get_presence().begin(), what.get_presence().end(), ostream_iterator<FieldTrait>(os, "\n"));
    return os;
 }
std::ostream& FIX8::operator<< (std::ostream & os, const GroupBase & what) inline
Inserter friend.
Parameters
os stream to send to
what messagebase
Returns
stream
Definition at line 1373 of file message.hpp.
References FIX8::GroupBase::_msgs.
 {
    for (const auto *pp : what._msgs)
       pp->print(os);
    return os;
 }
template<typename _CharT , typename _Traits , typename _Alloc > bool FIX8::operator^ (const std::basic_string< _CharT, _Traits, _Alloc > & __lhs, const std::basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
case insensitive std::string < std::string operator
Template Parameters
_CharT char type
_Traits char traits
_Alloc allocator
Parameters
__lhs left hand value
__rhs right hand value
Returns
true if lhs < rhs
Definition at line 291 of file f8utils.hpp.
 {
 #ifdef _MSC_VER
    return _stricmp(__lhs.c_str(), __rhs.c_str()) < 0;
 #else
    return strcasecmp(__lhs.c_str(), __rhs.c_str()) < 0;
 #endif
 }
const Package_info & FIX8::package_info ()
Return a Package_info map of strings with current package info
Returns
Package_info object reference
Definition at line 247 of file f8utils.cpp.
References FIX8_CODECTIMING, FIX8_CONFIGURE_OPTIONS, FIX8_CONFIGURE_SDATE, FIX8_CONFIGURE_TIME, FIX8_CONFIGURE_TIME_NUM, FIX8_CPPFLAGS, FIX8_DEBUG, FIX8_DEFAULT_PRECISION, FIX8_HOST_SYSTEM, FIX8_LDFLAGS, FIX8_LIBS, FIX8_MAGIC_NUM, FIX8_MAJOR_VERSION_NUM, FIX8_MAX_FLD_LENGTH, FIX8_MAX_MSG_LENGTH, FIX8_MINOR_VERSION_NUM, FIX8_MPMC_FF, FIX8_MPMC_SYSTEM, FIX8_MPMC_TBB, FIX8_PACKAGE, FIX8_PACKAGE_BUGREPORT, FIX8_PACKAGE_URL, FIX8_PATCH_VERSION_NUM, FIX8_THREAD_PTHREAD, FIX8_THREAD_STDTHREAD, FIX8_THREAD_SYSTEM, FIX8_VERSION, and STRINGIFY.
Referenced by find_package_info_string(), main(), and MyMenu::version_info().
 {
    //ostr << "Package info for " PACKAGE " version " VERSION;
    static const Package_info pinfo
    {
       { "FIX8_VERSION", FIX8_VERSION },
       { "FIX8_PACKAGE", FIX8_PACKAGE },
 #if defined FIX8_PACKAGE_BUGREPORT
       { "FIX8_PACKAGE_BUGREPORT", FIX8_PACKAGE_BUGREPORT },
 #endif
 #if defined FIX8_PACKAGE_URL
       { "FIX8_PACKAGE_URL", FIX8_PACKAGE_URL },
 #endif
       { "FIX8_MAGIC_NUM", STRINGIFY(FIX8_MAGIC_NUM) },
       { "FIX8_CONFIGURE_OPTIONS", FIX8_CONFIGURE_OPTIONS },
       { "FIX8_CPPFLAGS", FIX8_CPPFLAGS },
       { "FIX8_LIBS", FIX8_LIBS },
       { "FIX8_LDFLAGS", FIX8_LDFLAGS },
       { "FIX8_CONFIGURE_SDATE", FIX8_CONFIGURE_SDATE },
       { "FIX8_CONFIGURE_TIME", FIX8_CONFIGURE_TIME },
       { "FIX8_MAJOR_VERSION_NUM", STRINGIFY(FIX8_MAJOR_VERSION_NUM) },
       { "FIX8_MINOR_VERSION_NUM", STRINGIFY(FIX8_MINOR_VERSION_NUM) },
       { "FIX8_PATCH_VERSION_NUM", STRINGIFY(FIX8_PATCH_VERSION_NUM) },
       { "FIX8_CONFIGURE_TIME_NUM", STRINGIFY(FIX8_CONFIGURE_TIME_NUM) },
       { "FIX8_HOST_SYSTEM", FIX8_HOST_SYSTEM },
       { "FIX8_MAX_FLD_LENGTH", STRINGIFY(FIX8_MAX_FLD_LENGTH) },
       { "FIX8_MAX_MSG_LENGTH", STRINGIFY(FIX8_MAX_MSG_LENGTH) },
       { "FIX8_MPMC_FF", STRINGIFY(FIX8_MPMC_FF) },
       { "FIX8_MPMC_TBB", STRINGIFY(FIX8_MPMC_TBB) },
       { "FIX8_MPMC_SYSTEM", STRINGIFY(FIX8_MPMC_SYSTEM) },
       { "FIX8_DEFAULT_PRECISION", STRINGIFY(FIX8_DEFAULT_PRECISION) },
       { "FIX8_THREAD_PTHREAD", STRINGIFY(FIX8_THREAD_PTHREAD) },
       { "FIX8_THREAD_STDTHREAD", STRINGIFY(FIX8_THREAD_STDTHREAD) },
       { "FIX8_THREAD_SYSTEM", STRINGIFY(FIX8_THREAD_SYSTEM) },
 #if defined FIX8_SLEEP_NO_YIELD
       { "FIX8_SLEEP_NO_YIELD", STRINGIFY(FIX8_SLEEP_NO_YIELD) },
 #endif
 #if defined FIX8_CODECTIMING
       { "FIX8_CODECTIMING", STRINGIFY(FIX8_CODECTIMING) },
 #endif
 #if defined FIX8_HAVE_OPENSSL
       { "FIX8_HAVE_OPENSSL", STRINGIFY(FIX8_HAVE_OPENSSL) },
 #endif
 #if defined FIX8_HAVE_EXTENDED_METADATA
       { "FIX8_HAVE_EXTENDED_METADATA", STRINGIFY(FIX8_HAVE_EXTENDED_METADATA) },
 #endif
 #if defined FIX8_DEBUG
       { "FIX8_DEBUG", STRINGIFY(FIX8_DEBUG) },
 #endif
    };
    return pinfo;
 }
size_t FIX8::parse_decimal (const char * begin, size_t len, int & to) inline
Decode ASCII decimal value
Parameters
begin decode from
len number of bytes in string
to target location for value
Returns
number bytes decoded
Definition at line 844 of file field.hpp.
Referenced by date_parse(), date_time_parse(), and time_parse().
 {
    const char *bsv(begin);
    while(len-- > 0)
       to = (to << 3) + (to << 1) + (*begin++ - '0');
    return begin - bsv;
 }
int FIX8::recover_line (const XmlElement & xf) inline
Definition at line 204 of file f8c.hpp.
References XmlElement::FindAttr(), and XmlElement::GetLine().
Referenced by load_fields(), load_messages(), parse_groups(), and process_message_fields().
 { return xf.FindAttr("line", xf.GetLine()); }
unsigned FIX8::ROT13Hash (const std::string & str) inline
Generate a rot13 hash. No multiplication, algorithm by Serge Vakulenko. See http://vak.ru/doku.php/proj/hash/sources.
Parameters
str source string
Returns
hash value
Definition at line 216 of file f8utils.hpp.
References rotl().
 {
    unsigned int hash(0);
    for (const auto& pp : str)
    {
       hash += pp;
       hash -= rotl(hash, 13);
    }
    return hash;
 }
unsigned FIX8::rothash (unsigned result, unsigned value) inline
Definition at line 230 of file f8utils.hpp.
Referenced by group_hash().
 {
    // hash derived from http://stackoverflow.com/users/905902/wildplasser
    return result ^= (result >> 2) ^ (result << 5) ^ (result << 13) ^ value ^ 0x80001801;
 }
template<typename T > T FIX8::rotl (const T val, const int times) inline
Rotate left value the specified number of times
Template Parameters
T type
Parameters
val source value
times number of times to rotate left
Returns
the rotated value
Definition at line 203 of file f8utils.hpp.
Referenced by ROT13Hash().
 { return val << times | val >> (sizeof(T) * 8 - times); }
template<typename T > T FIX8::rotr (const T val, const int times) inline
Rotate right value the specified number of times
Template Parameters
T type
Parameters
val source value
times number of times to rotate right
Returns
the rotated value
Definition at line 211 of file f8utils.hpp.
 { return val >> times | val << (sizeof(T) * 8 - times); }
void FIX8::split_path (const std::string & source, std::string & filepart, std::string & dirpart) inline
Split a pathname into directory and filename parts
Parameters
source source path
filepart target for file part
dirpart target for directory part
Definition at line 1082 of file f8utils.hpp.
Referenced by FIX8::FileLogger::rotate().
 {
    std::string::size_type slpos(source.find_last_of("/\\"));
    if (slpos == std::string::npos)
       filepart = source;
    else
    {
       filepart.assign(source.substr(slpos + 1));
       dirpart.assign(source.substr(0, slpos));
    }
 }
string FIX8::Str_error (const int err, const char * str = 0)
Find standard error string for given errno.
Parameters
err errno value
str if not 0, prepend string to error string
Returns
error string
Definition at line 165 of file f8utils.cpp.
References ignore_value().
Referenced by MyMenu::load_msgs(), MyMenu::save_msg(), FIX8::tty_save_state::set_raw_mode(), and FIX8::tty_save_state::unset_raw_mode().
 {
    const size_t max_str(256);
    char buf[max_str] {};
 #ifdef _MSC_VER
    ignore_value(strerror_s(buf, max_str - 1, err));
 #else
    ignore_value(strerror_r(err, buf, max_str - 1));
 #endif
    if (str && *str)
    {
       ostringstream ostr;
       ostr << str << ": " << buf;
       return ostr.str();
    }
    return string(buf);
 }
F8API std::string FIX8::StrToLower (const std::string & src)
String to lower case.
Parameters
src source string
Returns
to new lowercase string
string FIX8::StrToLower (const string & src)
Definition at line 158 of file f8utils.cpp.
References InPlaceStrToLower().
Referenced by decode_dow().
 {
    string result(src);
    return InPlaceStrToLower(result);
 }
F8_TEX_API const F8MetaCntx & FIX8::TEX_ctx ()
Definition at line 437 of file Myfix_classes.cpp.
References FIX8::TEX::ctx().
 { return TEX::ctx(); }
Tickval::ticks FIX8::time_parse (const char * ptr, size_t len, bool timeonly = false) inline
Decode a Time string into ticks
Parameters
ptr input time string, if *ptr == '!' return current time
len length of string
timeonly if true, only calculate ticks for today
Returns
ticks decoded
Definition at line 978 of file field.hpp.
References FIX8::Tickval::billion, FIX8::Tickval::get_ticks(), FIX8::Tickval::million, FIX8::Tickval::noticks, parse_decimal(), and time_to_epoch().
Referenced by FIX8::Configuration::get_time_field().
 {
    if (len == 0 || (*ptr == 'n' && len == 3 && *(ptr + 1) == 'o' && *(ptr + 2) == 'w'))   // special cases initialise to 'now'
       return Tickval(true).get_ticks();
    Tickval::ticks result(Tickval::noticks);
    int millisecond(0);
    tm tms {};
    ptr += parse_decimal(ptr, 2, tms.tm_hour);
    ++ptr;
    ptr += parse_decimal(ptr, 2, tms.tm_min);
    ++ptr;
    ptr += parse_decimal(ptr, 2, tms.tm_sec);
    switch(len)
    {
    case 12: // 23:59:59.123
       parse_decimal(++ptr, 3, millisecond);
       result = millisecond * Tickval::million; // drop through
    case 8: // 23:59:59
       if (!timeonly)
          result += time_to_epoch(tms) * Tickval::billion;
       else
          result += (tms.tm_hour * 3600ULL + tms.tm_min * 60ULL + tms.tm_sec) * Tickval::billion;
       break;
    default:
       break;
    }
    return result;
 }
time_t FIX8::time_to_epoch (const tm & ltm, int utcdiff = 0) inline
Convert tm to time_t Based on Ghulam M. Babar's "mktime slow? use custom function" see http://gmbabar.wordpress.com/2010/12/01/mktime-slow-use-custom-function/
Parameters
ltm decode from
utcdiff utc offset in mins
Returns
time_t
Definition at line 858 of file field.hpp.
Referenced by date_parse(), date_time_parse(), and time_parse().
 {
    static const int mon_days[] {0,
       31,
       31 + 28,
       31 + 28 + 31,
       31 + 28 + 31 + 30,
       31 + 28 + 31 + 30 + 31,
       31 + 28 + 31 + 30 + 31 + 30,
       31 + 28 + 31 + 30 + 31 + 30 + 31,
       31 + 28 + 31 + 30 + 31 + 30 + 31 + 31,
       31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30,
       31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31,
       31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31 + 30,
       31 + 28 + 31 + 30 + 31 + 30 + 31 + 31 + 30 + 31 + 30 + 31
    };
    const int tyears(ltm.tm_year ? ltm.tm_year - 70 : 0); // tm->tm_year is from 1900.
    int tdays(mon_days[ltm.tm_mon] + (ltm.tm_mday ? ltm.tm_mday - 1 : 0) + tyears * 365 + (tyears + 2) / 4);
    if (ltm.tm_year && ltm.tm_year % 4 == 0 && ltm.tm_mon < 2) // works till 2100, adjust for leap year with jan/feb +1day error
       --tdays;
    return tdays * 86400 + (ltm.tm_hour + utcdiff) * 3600 + ltm.tm_min * 60 + ltm.tm_sec;
 }
std::string FIX8::trim (const std::string & source, const std::string & ws = " \t") inline
Trim leading and trailing whitespace from a string
Parameters
source source string
ws string containing whitespace characters to trim out
Returns
copy of trimmed string
Definition at line 153 of file f8utils.hpp.
Referenced by FIX8::Configuration::create_logger(), FIX8::Configuration::get_logflags(), load_fields(), main(), FIX8::ebitset< TraitTypes, unsigned short >::set(), and FIX8::ebitset_r< SessionControl >::set().
 {
     const size_t bgstr(source.find_first_not_of(ws));
     return bgstr == std::string::npos
        ? source : source.substr(bgstr, source.find_last_not_of(ws) - bgstr + 1);
 }
const std::string& FIX8::trim (std::string & source, const std::string & ws = " \t") inline
Trim leading and trailing whitespace from a string, inplace.
Parameters
source source string
ws string containing whitespace characters to trim out
Returns
trimmed string
Definition at line 164 of file f8utils.hpp.
 {
     const size_t bgstr(source.find_first_not_of(ws));
     return bgstr == std::string::npos
        ? source : source = source.substr(bgstr, source.find_last_not_of(ws) - bgstr + 1);
 }
Variable Documentation
const CSMap FIX8::_csMap
Definition at line 126 of file f8cstatic.hpp.
Referenced by generate_common_group_bodies(), generate_group_bodies(), generate_preamble(), and process().
char FIX8::glob_log0 { "global_filename_not_set.log" }
Definition at line 46 of file logger.cpp.