fix8: ff Namespace Reference
ff Namespace Reference
Classes
class SegmentAllocator
Uses standard libc allocator to allocate chunks of (possibly aligned) memory. It also keeps track of the amount of allocated memory.
struct Buf_ctl
A buffer controller.
struct Seg_ctl
The segment controller.
struct xThreadData
A buffer shared among threads (i.e. leak queue)
class SlabCache
Cache of slab segments.
class ff_allocator
The ff_allocator, based on the idea of the Slab allocator
class ffa_wrapper
struct FFAxThreadData
class FFAllocator
The FFAllocator, based on the ff_allocator.
class SWSR_Ptr_Buffer
Single-Writer/Single-Reader circular buffer.
class Lamport_Buffer
Implementation of the well-known Lamport's wait-free circular buffer.
class commPattern
This is a tempalte class which defines the communication pattern interface.
class commTransport
This class defines the transport pattern interface.
struct descriptor1_N
This struct is used in several communication patterns; Unicast, Broadcast, Scatter, On-Demand, OneToMany, FromAny etc.
struct descriptorN_1
Descriptor used in several communication patterns: AllGather, Collect FromAny, ManyToOne.
class zmq1_1
This class provides ZeroMQ implementation of the 1 to 1 communication pattern.
class zmqBcast
It implements the broadcast communication pattern of FastFlow in ZeroMQ.
class zmqAllGather
It provides implementation of the ALL_GATHER communication pattern.
class zmqFromAny
It provides implementation of the collect from ANY communication pattern.
class zmqScatter
It provides implementation of the SCATTER communication pattern.
class zmqOnDemand
ZeroMQ implementation of the ON-DEMAND communication pattern.
class zmq1_N
class zmqTransportMsg_t
It describes the sructure of 0MQ transport message.
class zmqTransport
This class describes the transport layer used in a distributed FastFlow environment.
class ff_dinout
A ff_dnode with both input and output channels.
class ff_dnode
A class representing the distributed version of ff_node.
class dynlinkedlist
TODO.
class dynqueue
TODO.
class ff_farm
The Farm skeleton, with Emitter (lb_t) and Collector (gt_t).
class ofarm_lb
Ordered farm.
class ofarm_gt
Ordered farm with gatherer.
class ff_ofarm
The ordered Farm skeleton.
class ff_minode
FastFlow node with multiple inputs.
class ff_monode
Multiple output FastFlow node.
class ff_gatherer
A class representing the Collector node in a Farm skeleton.
class ff_loadbalancer
A class representing the Emitter node in a typical Farm skeleton.
class map_lb
A loadbalancer for the map skeleton.
class map_gt
A gatherer for the map skeleton.
class ff_map
The map skeleton.
class baseTask
class threadMapper
The thread mapper allows to map threads to specific core using a predefined mapping policy.
class MPMC_Ptr_Queue
An implementation of the bounded Multi-Producer/Multi-Consumer queue.
class uMPMC_Ptr_Queue
An implementation of the unbounded Multi-Producer/Multi-Consumer queue.
class MSqueue
An implementation of the lock-free FIFO MPMC queue by Michael and Scott, described in the paper: "Simple, Fast, and Practical Non-Blocking and Blocking Concurrent Queue Algorithms", PODC 1996.
class multiSWSR
class scalableMPMCqueue
class multiMSqueue
class Barrier
Models a classical mutex.
class spinBarrier
Models a classical Mutex.
class ff_thread
Defines FastFlow's threads.
class ff_node
Describes the FastFlow node.
class ff_oclNode
OpenCL implementation of FastFlow node.
struct forall_task_t
class forallreduce_W
class forall_Scheduler
class ff_forall_farm
class basePartition
TODO.
class basePartitionList
TODO.
class basePartitioner
A basic interface for the partitioner used by the Map skeleton.
class LinearPartitioner
A linear partitioner.
class ff_pipeline
The Pipeline skeleton.
class Fstage
class squeue
class staticlinkedlist
TODO.
class svector
TODO.
class BufferPool
class uSWSR_Ptr_Buffer
Unbounded Single-Writer/Single-Reader circular buffer.
Typedefs
typedef void(* dnode_cbk_t)(void *, void *)
Defines callback.
Enumerations
enum { N_SLABBUFFER =9, MAX_SLABBUFFER_SIZE =8192 }
Functions
static bool isPowerOfTwoMultiple (size_t alignment, size_t multiple)
static void FFAkeyDestructorHandler (void *kv)
static void killMyself (ffa_wrapper *ptr)
static void * ff_malloc (size_t size)
static void ff_free (void *ptr)
static void * ff_realloc (void *ptr, size_t newsize)
static int ff_posix_memalign (void **memptr, size_t alignment, size_t size)
static int init_thread_affinity (pthread_attr_t *, int)
Initializes thread affinity.
static void * proxy_thread_routine (void *arg)
Proxy thread routine.
template<typename T >
ff_node * toffnode (T *p)
template<typename T >
ff_node * toffnode (T &p)
Variables
static const int POW2_MIN = 5
static const int POW2_MAX = 13
static const int buffersize [N_SLABBUFFER]
static const int nslabs_default [N_SLABBUFFER]
static const int longxCacheLine = (CACHE_LINE_SIZE/sizeof(long))
static const char FF_DEOS [] ="EOS"
static const unsigned long FF_EOS = (ULONG_MAX)
static const unsigned long FF_EOS_NOFREEZE = (FF_EOS-0x1)
static const unsigned long FF_GO_ON = (FF_EOS-0x2)
enum { START_TIME =0, STOP_TIME =1, GET_TIME =2 }
static ticks ticks_wait (ticks nticks)
static void ff_relax (unsigned long us)
static void error (const char *str,...)
static unsigned long getusec ()
static double diffmsec (const struct timeval &a, const struct timeval &b)
static bool time_compare (struct timeval &a, struct timeval &b)
static bool time_iszero (const struct timeval &a)
static void time_setzero (struct timeval &a)
static bool isPowerOf2 (unsigned int x)
static unsigned int nextPowerOf2 (unsigned int x)
static unsigned int nextMultipleOfIf (unsigned int x, unsigned int m)
static double ffTime (int tag, bool lock=false)
Detailed Description
Single-Writer/Single-Reader (SWSR) lock-free (wait-free) unbounded FIFO queue. No lock is needed around pop and push methods!!
The key idea underneath the implementation is quite simple: the unbounded queue is based on a pool of wait-free SWSR circular buffers (see buffer.hpp). The pool of buffers automatically grows and shrinks on demand. The implementation of the pool of buffers carefully try to minimize the impact of dynamic memory allocation/deallocation by using caching strategies.
More information about the uSWSR_Ptr_Buffer implementation and correctness proof can be found in the following report:
Massimo Torquati, "Single-Producer/Single-Consumer Queue on Shared Cache Multi-Core Systems", TR-10-20, Computer Science Department, University of Pisa Italy,2010 (http://compass2.di.unipi.it/TR/Files/TR-10-20.pdf.gz)
IMPORTANT:
This implementation has been optimized for 1 producer and 1 consumer. If you need to use more producers and/or more consumers you have several possibilities (top-down order):
to use an high level construct like the farm skeleton and compositions of multiple farms (in other words, use FastFlow ;-)).
to use one of the implementations in the MPMCqueues.hpp file
to use the SWSR_Ptr_Buffer but with the mp_push and the mc_pop methods both protected by (spin-)locks in order to protect the internal data structures.
Typedef Documentation
typedef void(* ff::dnode_cbk_t)(void *, void *)
Defines callback.
It defines the callback.
Definition at line 65 of file dnode.hpp.
Enumeration Type Documentation
anonymous enum
Enumerator
START_TIME
STOP_TIME
GET_TIME
Definition at line 59 of file utils.hpp.
anonymous enum
Enumerator
N_SLABBUFFER
MAX_SLABBUFFER_SIZE
Definition at line 112 of file allocator.hpp.
Function Documentation
static double ff::diffmsec (const struct timeval & a, const struct timeval & b) inline static
Compute a-b and return the difference in msec
Definition at line 144 of file utils.hpp.
Referenced by ffTime(), ff::ff_gatherer::ffTime(), ff::ff_pipeline::ffTime(), ff::ff_farm< ofarm_lb, ofarm_gt >::ffTime(), ff::ff_loadbalancer::ffTime(), ff::ff_node::ffTime(), ff::ff_pipeline::ffwTime(), ff::ff_farm< ofarm_lb, ofarm_gt >::ffwTime(), ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), ff::ff_node::thWorker::svc(), ff::ff_gatherer::wffTime(), ff::ff_loadbalancer::wffTime(), and ff::ff_node::wffTime().
static void ff::error (const char * str, ...) inline static
TODO
Definition at line 119 of file utils.hpp.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::add_collector(), ff::ff_farm< ofarm_lb, ofarm_gt >::add_workers(), ff::Barrier::Barrier(), ff::ff_pipeline::create_input_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::create_input_buffer(), ff::ff_pipeline::create_output_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::create_output_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::ff_farm(), ff::ff_forall_farm< Tres >::ff_forall_farm(), ff::ff_thread::ff_thread(), ff::FFAllocator::FFAllocator(), ff::ff_pipeline::freeze_and_run(), ff::ff_dnode< CommImplIn >::init(), ff::ff_allocator::init(), ff::ff_pipeline::load_result(), ff::ff_pipeline::load_result_nb(), ff::FFAllocator::malloc(), ff::FFAllocator::newAllocator(), ff::ff_pipeline::offload(), ff::ff_farm< ofarm_lb, ofarm_gt >::offload(), ff::ff_dinout< CommImplIn, CommImplOut >::pop(), ff::ff_dnode< CommImplIn >::pop(), ff::FFAllocator::posix_memalign(), ff::ff_pipeline::prepare(), ff::ff_gatherer::register_worker(), ff::ff_loadbalancer::register_worker(), ff::ff_pipeline::run(), ff::ff_gatherer::run(), ff::ff_farm< ofarm_lb, ofarm_gt >::run(), ff::ff_loadbalancer::run(), ff::ff_minode::run(), ff::ff_monode::run(), ff::ff_loadbalancer::runlb(), ff::ff_gatherer::set_filter(), ff::ff_loadbalancer::set_filter(), ff::ff_loadbalancer::set_masterworker(), ff::ff_farm< ofarm_lb, ofarm_gt >::set_multi_input(), ff::ff_loadbalancer::set_multi_input(), ff::ff_pipeline::set_output_buffer(), ff::ff_farm< ofarm_lb, ofarm_gt >::set_output_buffer(), ff::ff_map::setAffinity(), ff::ff_pipeline::setAffinity(), ff::ff_farm< ofarm_lb, ofarm_gt >::setAffinity(), ff::ff_node::setAffinity(), ff::threadMapper::setMappingList(), ff::ff_oclNode::svc_createOCL(), ff::ff_node::thWorker::svc_init(), ff::ff_farm< ofarm_lb, ofarm_gt >::thaw(), ff::ff_thread::thread_routine(), ff::threadMapper::threadMapper(), ff::ff_pipeline::wait(), ff::ff_thread::wait(), ff::ff_loadbalancer::wait(), ff::ff_pipeline::wait_freezing(), ff::ff_loadbalancer::wait_freezing(), ff::ff_loadbalancer::waitlb(), ff::ff_pipeline::wrap_around(), ff::ff_map::wrap_around(), and ff::ff_farm< ofarm_lb, ofarm_gt >::wrap_around().
static void ff::ff_free (void * ptr) inline static
Definition at line 1845 of file allocator.hpp.
References ff::FFAllocator::free(), and ff::FFAllocator::instance().
Referenced by FIX8::ff_unbounded_queue< T >::release().
static void* ff::ff_malloc (size_t size) inline static
Definition at line 1842 of file allocator.hpp.
References ff::FFAllocator::instance(), and ff::FFAllocator::malloc().
Referenced by FIX8::ff_unbounded_queue< T >::try_push().
static int ff::ff_posix_memalign (void ** memptr, size_t alignment, size_t size) inline static
Definition at line 1851 of file allocator.hpp.
References ff::FFAllocator::instance(), and ff::FFAllocator::posix_memalign().
static void* ff::ff_realloc (void * ptr, size_t newsize) inline static
Definition at line 1848 of file allocator.hpp.
References ff::FFAllocator::instance(), and ff::FFAllocator::realloc().
static void ff::ff_relax (unsigned long us) inline static
Definition at line 106 of file utils.hpp.
static void ff::FFAkeyDestructorHandler (void * kv) static
Definition at line 1831 of file allocator.hpp.
References ff::ff_allocator::deregisterAllocator(), ff::FFAxThreadData::f, and ff::ffa_wrapper::nomoremalloc().
Referenced by ff::FFAllocator::FFAllocator().
static double ff::ffTime (int tag, bool lock = false) inline static
TODO
Returns
TODO
Definition at line 209 of file utils.hpp.
References diffmsec(), GET_TIME, spin_lock(), spin_unlock(), START_TIME, and STOP_TIME.
static unsigned long ff::getusec () inline static
It returns the current time in usec
Definition at line 135 of file utils.hpp.
static int ff::init_thread_affinity (pthread_attr_t * , int) inline static
Initializes thread affinity.
It initializes thread affinity i.e. it defines to which core ths thread should be assigned.
Returns
always return -1 because no thread mapping is done
Definition at line 330 of file node.hpp.
References ff::threadMapper::instance().
Referenced by ff::ff_thread::spawn().
static bool ff::isPowerOf2 (unsigned int x) inline static
TODO
Definition at line 184 of file utils.hpp.
Referenced by ff::MPMC_Ptr_Queue::init(), ff::uMPMC_Ptr_Queue::init(), ff::multiSWSR::init(), nextPowerOf2(), ff::threadMapper::setMappingList(), and ff::threadMapper::threadMapper().
static bool ff::isPowerOfTwoMultiple (size_t alignment, size_t multiple) inline static
Definition at line 200 of file allocator.hpp.
Referenced by ff::ff_allocator::posix_memalign(), and ff::FFAllocator::posix_memalign().
static void ff::killMyself (ffa_wrapper * ptr) inline static
Definition at line 1836 of file allocator.hpp.
References ff::FFAllocator::deleteAllocator(), and ff::FFAllocator::instance().
Referenced by ff::ffa_wrapper::free().
static unsigned int ff::nextMultipleOfIf (unsigned int x, unsigned int m) inline static
Definition at line 198 of file utils.hpp.
static unsigned int ff::nextPowerOf2 (unsigned int x) inline static
TODO
Definition at line 191 of file utils.hpp.
References isPowerOf2().
Referenced by ff::MPMC_Ptr_Queue::init(), ff::uMPMC_Ptr_Queue::init(), ff::multiSWSR::init(), ff::threadMapper::setMappingList(), and ff::threadMapper::threadMapper().
static void * ff::proxy_thread_routine (void * arg) static
Proxy thread routine.
Definition at line 712 of file node.hpp.
References pthread_exit(), and ff::ff_thread::thread_routine().
static ticks ff::ticks_wait (ticks nticks) inline static
Definition at line 93 of file utils.hpp.
Referenced by ff::ff_node::ff_send_out(), ff::ff_pipeline::load_result(), ff::ff_farm< ofarm_lb, ofarm_gt >::load_result(), ff::ff_gatherer::losetime_in(), ff::ff_loadbalancer::losetime_in(), ff::ff_gatherer::losetime_out(), ff::ff_loadbalancer::losetime_out(), ff::ff_pipeline::offload(), ff::ff_farm< ofarm_lb, ofarm_gt >::offload(), ff::ff_node::thWorker::pop(), and ff::ff_node::thWorker::push().
static bool ff::time_compare (struct timeval & a, struct timeval & b) inline static
TODO
Definition at line 159 of file utils.hpp.
Referenced by ff::ff_farm< ofarm_lb, ofarm_gt >::getstoptime(), and ff::ff_farm< ofarm_lb, ofarm_gt >::getwstoptime().
static bool ff::time_iszero (const struct timeval & a) inline static
TODO
Definition at line 168 of file utils.hpp.
static void ff::time_setzero (struct timeval & a) inline static
TODO
Definition at line 176 of file utils.hpp.
Referenced by ff::ff_gatherer::ff_gatherer(), ff::ff_loadbalancer::ff_loadbalancer(), and ff::ff_node::ff_node().
template<typename T > ff_node* ff::toffnode (T * p)
Definition at line 666 of file pipeline.hpp.
template<typename T > ff_node* ff::toffnode (T & p)
Definition at line 668 of file pipeline.hpp.
Variable Documentation
const int ff::buffersize[N_SLABBUFFER] static
Initial value:
=
                                { 32, 64,128,256,512,1024,2048,4096,8192  }
Definition at line 117 of file allocator.hpp.
Referenced by ff::ff_allocator::init().
const char ff::FF_DEOS[] ="EOS" static
Definition at line 58 of file dnode.hpp.
Referenced by ff::ff_dnode< CommImplIn >::internal_push(), and ff::ff_dinout< CommImplIn, CommImplOut >::push().
const unsigned long ff::FF_EOS = (ULONG_MAX) static
Definition at line 54 of file config.hpp.
Referenced by ff::ff_gatherer::all_gather(), ff::ff_dnode< CommImplIn >::internal_push(), ff::ff_pipeline::load_result(), ff::ff_farm< ofarm_lb, ofarm_gt >::load_result(), ff::ff_dinout< CommImplIn, CommImplOut >::pop(), ff::ff_dnode< CommImplIn >::pop(), ff::ff_dinout< CommImplIn, CommImplOut >::push(), ff::ff_loadbalancer::push_eos(), ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), ff::ff_ofarm::ofarmE::svc(), and ff::ff_node::thWorker::svc().
const unsigned long ff::FF_EOS_NOFREEZE = (FF_EOS-0x1) static
Definition at line 55 of file config.hpp.
Referenced by ff::ff_gatherer::all_gather(), ff::ff_loadbalancer::push_eos(), ff::ff_gatherer::svc(), ff::ff_loadbalancer::svc(), ff::ff_node::thWorker::svc(), and ff::ff_thread::thread_routine().
const unsigned long ff::FF_GO_ON = (FF_EOS-0x2) static
Definition at line 56 of file config.hpp.
const int ff::longxCacheLine = (CACHE_LINE_SIZE/sizeof(long)) static
Definition at line 61 of file buffer.hpp.
Referenced by ff::dynlinkedlist::dynlinkedlist(), ff::SWSR_Ptr_Buffer::init(), ff::MPMC_Ptr_Queue::init(), ff::Lamport_Buffer::init(), ff::uMPMC_Ptr_Queue::init(), ff::SWSR_Ptr_Buffer::reset(), and ff::staticlinkedlist::staticlinkedlist().
const int ff::nslabs_default[N_SLABBUFFER] static
Initial value:
=
                                { 512,512,512,512,128,  64,  32,  16,   8 }
Definition at line 124 of file allocator.hpp.
Referenced by ff::ff_allocator::init().
const int ff::POW2_MAX = 13 static
Definition at line 114 of file allocator.hpp.
Referenced by ff::ff_allocator::getslabs().
const int ff::POW2_MIN = 5 static
Definition at line 113 of file allocator.hpp.
Referenced by ff::ff_allocator::getslabs().