var namespaceFIX8 =
[
    [ "defaults", "namespaceFIX8_1_1defaults.html", null ],
    [ "States", "namespaceFIX8_1_1States.html", null ],
    [ "TEX", "namespaceFIX8_1_1TEX.html", "namespaceFIX8_1_1TEX" ],
    [ "UTEST", "namespaceFIX8_1_1UTEST.html", "namespaceFIX8_1_1UTEST" ],
    [ "Server", "structFIX8_1_1Server.html", "structFIX8_1_1Server" ],
    [ "SslContext", "structFIX8_1_1SslContext.html", "structFIX8_1_1SslContext" ],
    [ "Configuration", "classFIX8_1_1Configuration.html", "classFIX8_1_1Configuration" ],
    [ "AsyncSocket", "classFIX8_1_1AsyncSocket.html", "classFIX8_1_1AsyncSocket" ],
    [ "FIXReader", "classFIX8_1_1FIXReader.html", "classFIX8_1_1FIXReader" ],
    [ "FIXWriter", "classFIX8_1_1FIXWriter.html", "classFIX8_1_1FIXWriter" ],
    [ "Connection", "classFIX8_1_1Connection.html", "classFIX8_1_1Connection" ],
    [ "ClientConnection", "classFIX8_1_1ClientConnection.html", "classFIX8_1_1ClientConnection" ],
    [ "ServerConnection", "classFIX8_1_1ServerConnection.html", "classFIX8_1_1ServerConnection" ],
    [ "ConsoleMenu", "classFIX8_1_1ConsoleMenu.html", "classFIX8_1_1ConsoleMenu" ],
    [ "f8Exception", "classFIX8_1_1f8Exception.html", "classFIX8_1_1f8Exception" ],
    [ "InvalidMetadata", "structFIX8_1_1InvalidMetadata.html", "structFIX8_1_1InvalidMetadata" ],
    [ "DuplicateField", "structFIX8_1_1DuplicateField.html", "structFIX8_1_1DuplicateField" ],
    [ "InvalidDomainValue", "structFIX8_1_1InvalidDomainValue.html", "structFIX8_1_1InvalidDomainValue" ],
    [ "InvalidField", "structFIX8_1_1InvalidField.html", "structFIX8_1_1InvalidField" ],
    [ "InvalidMsgSequence", "structFIX8_1_1InvalidMsgSequence.html", "structFIX8_1_1InvalidMsgSequence" ],
    [ "MsgSequenceTooLow", "structFIX8_1_1MsgSequenceTooLow.html", "structFIX8_1_1MsgSequenceTooLow" ],
    [ "InvalidBodyLength", "structFIX8_1_1InvalidBodyLength.html", "structFIX8_1_1InvalidBodyLength" ],
    [ "InvalidMessage", "structFIX8_1_1InvalidMessage.html", "structFIX8_1_1InvalidMessage" ],
    [ "IllegalMessage", "structFIX8_1_1IllegalMessage.html", "structFIX8_1_1IllegalMessage" ],
    [ "InvalidVersion", "structFIX8_1_1InvalidVersion.html", "structFIX8_1_1InvalidVersion" ],
    [ "BadSendingTime", "structFIX8_1_1BadSendingTime.html", "structFIX8_1_1BadSendingTime" ],
    [ "BadCompidId", "structFIX8_1_1BadCompidId.html", "structFIX8_1_1BadCompidId" ],
    [ "InvalidRepeatingGroup", "structFIX8_1_1InvalidRepeatingGroup.html", "structFIX8_1_1InvalidRepeatingGroup" ],
    [ "MissingRepeatingGroupField", "structFIX8_1_1MissingRepeatingGroupField.html", "structFIX8_1_1MissingRepeatingGroupField" ],
    [ "MissingMessageComponent", "structFIX8_1_1MissingMessageComponent.html", "structFIX8_1_1MissingMessageComponent" ],
    [ "MissingMandatoryField", "structFIX8_1_1MissingMandatoryField.html", "structFIX8_1_1MissingMandatoryField" ],
    [ "BadCheckSum", "structFIX8_1_1BadCheckSum.html", "structFIX8_1_1BadCheckSum" ],
    [ "dthreadException", "structFIX8_1_1dthreadException.html", "structFIX8_1_1dthreadException" ],
    [ "PeerResetConnection", "structFIX8_1_1PeerResetConnection.html", "structFIX8_1_1PeerResetConnection" ],
    [ "InvalidConfiguration", "structFIX8_1_1InvalidConfiguration.html", "structFIX8_1_1InvalidConfiguration" ],
    [ "LogfileException", "structFIX8_1_1LogfileException.html", "structFIX8_1_1LogfileException" ],
    [ "XMLError", "structFIX8_1_1XMLError.html", "structFIX8_1_1XMLError" ],
    [ "_Pair", "structFIX8_1_1__Pair.html", "structFIX8_1_1__Pair" ],
    [ "_Pair< const char *, Val >", "structFIX8_1_1__Pair_3_01const_01char_01_5_00_01Val_01_4.html", "structFIX8_1_1__Pair_3_01const_01char_01_5_00_01Val_01_4" ],
    [ "GeneratedTable", "classFIX8_1_1GeneratedTable.html", "classFIX8_1_1GeneratedTable" ],
    [ "StaticTable", "structFIX8_1_1StaticTable.html", "structFIX8_1_1StaticTable" ],
    [ "presorted_set", "classFIX8_1_1presorted__set.html", "classFIX8_1_1presorted__set" ],
    [ "Type2Type", "structFIX8_1_1Type2Type.html", "structFIX8_1_1Type2Type" ],
    [ "Type2Types", "structFIX8_1_1Type2Types.html", "structFIX8_1_1Type2Types" ],
    [ "scoped_ptr", "classFIX8_1_1scoped__ptr.html", "classFIX8_1_1scoped__ptr" ],
    [ "RegMatch", "classFIX8_1_1RegMatch.html", "classFIX8_1_1RegMatch" ],
    [ "RegExp", "classFIX8_1_1RegExp.html", "classFIX8_1_1RegExp" ],
    [ "StringPtrLessThanNoCase", "structFIX8_1_1StringPtrLessThanNoCase.html", "structFIX8_1_1StringPtrLessThanNoCase" ],
    [ "StringPtrLessThan", "structFIX8_1_1StringPtrLessThan.html", "structFIX8_1_1StringPtrLessThan" ],
    [ "StringLessThanNoCase", "structFIX8_1_1StringLessThanNoCase.html", "structFIX8_1_1StringLessThanNoCase" ],
    [ "ebitset", "classFIX8_1_1ebitset.html", "classFIX8_1_1ebitset" ],
    [ "ebitset_r", "classFIX8_1_1ebitset__r.html", "classFIX8_1_1ebitset__r" ],
    [ "DeleteObject", "structFIX8_1_1DeleteObject.html", "structFIX8_1_1DeleteObject" ],
    [ "DeleteArrayObject", "structFIX8_1_1DeleteArrayObject.html", "structFIX8_1_1DeleteArrayObject" ],
    [ "Delete1stPairObject", "structFIX8_1_1Delete1stPairObject.html", "structFIX8_1_1Delete1stPairObject" ],
    [ "Delete2ndPairObject", "structFIX8_1_1Delete2ndPairObject.html", "structFIX8_1_1Delete2ndPairObject" ],
    [ "free_ptr", "structFIX8_1_1free__ptr.html", "structFIX8_1_1free__ptr" ],
    [ "Singleton", "classFIX8_1_1Singleton.html", "classFIX8_1_1Singleton" ],
    [ "fdinbuf", "classFIX8_1_1fdinbuf.html", "classFIX8_1_1fdinbuf" ],
    [ "tty_save_state", "classFIX8_1_1tty__save__state.html", "classFIX8_1_1tty__save__state" ],
    [ "ff_unbounded_queue", "classFIX8_1_1ff__unbounded__queue.html", "classFIX8_1_1ff__unbounded__queue" ],
    [ "ff_unbounded_queue< T * >", "classFIX8_1_1ff__unbounded__queue_3_01T_01_5_01_4.html", "classFIX8_1_1ff__unbounded__queue_3_01T_01_5_01_4" ],
    [ "ff_atomic", "classFIX8_1_1ff__atomic.html", "classFIX8_1_1ff__atomic" ],
    [ "ff_atomic< T * >", "classFIX8_1_1ff__atomic_3_01T_01_5_01_4.html", "classFIX8_1_1ff__atomic_3_01T_01_5_01_4" ],
    [ "f8_mutex", "classFIX8_1_1f8__mutex.html", "classFIX8_1_1f8__mutex" ],
    [ "f8_spin_lock", "classFIX8_1_1f8__spin__lock.html", "classFIX8_1_1f8__spin__lock" ],
    [ "EnumType", "structFIX8_1_1EnumType.html", "structFIX8_1_1EnumType" ],
    [ "RealmBase", "structFIX8_1_1RealmBase.html", "structFIX8_1_1RealmBase" ],
    [ "BaseField", "classFIX8_1_1BaseField.html", "classFIX8_1_1BaseField" ],
    [ "Field", "classFIX8_1_1Field.html", null ],
    [ "Field< int, field >", "classFIX8_1_1Field_3_01int_00_01field_01_4.html", "classFIX8_1_1Field_3_01int_00_01field_01_4" ],
    [ "Field< char *, field >", "classFIX8_1_1Field_3_01char_01_5_00_01field_01_4.html", "classFIX8_1_1Field_3_01char_01_5_00_01field_01_4" ],
    [ "Field< f8String, field >", "classFIX8_1_1Field_3_01f8String_00_01field_01_4.html", "classFIX8_1_1Field_3_01f8String_00_01field_01_4" ],
    [ "Field< double, field >", "classFIX8_1_1Field_3_01double_00_01field_01_4.html", "classFIX8_1_1Field_3_01double_00_01field_01_4" ],
    [ "Field< char, field >", "classFIX8_1_1Field_3_01char_00_01field_01_4.html", "classFIX8_1_1Field_3_01char_00_01field_01_4" ],
    [ "Field< UTCTimestamp, field >", "classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4.html", "classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4" ],
    [ "Field< UTCTimeOnly, field >", "classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4.html", "classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4" ],
    [ "Field< UTCDateOnly, field >", "classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4.html", "classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4" ],
    [ "Field< LocalMktDate, field >", "classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4.html", "classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4" ],
    [ "Field< MonthYear, field >", "classFIX8_1_1Field_3_01MonthYear_00_01field_01_4.html", "classFIX8_1_1Field_3_01MonthYear_00_01field_01_4" ],
    [ "Field< TZTimeOnly, field >", "classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4.html", "classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4" ],
    [ "Field< TZTimestamp, field >", "classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4.html", "classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4" ],
    [ "Field< Length, field >", "classFIX8_1_1Field_3_01Length_00_01field_01_4.html", "classFIX8_1_1Field_3_01Length_00_01field_01_4" ],
    [ "Field< TagNum, field >", "classFIX8_1_1Field_3_01TagNum_00_01field_01_4.html", "classFIX8_1_1Field_3_01TagNum_00_01field_01_4" ],
    [ "Field< SeqNum, field >", "classFIX8_1_1Field_3_01SeqNum_00_01field_01_4.html", "classFIX8_1_1Field_3_01SeqNum_00_01field_01_4" ],
    [ "Field< NumInGroup, field >", "classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4.html", "classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4" ],
    [ "Field< DayOfMonth, field >", "classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4.html", "classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4" ],
    [ "Field< Boolean, field >", "classFIX8_1_1Field_3_01Boolean_00_01field_01_4.html", "classFIX8_1_1Field_3_01Boolean_00_01field_01_4" ],
    [ "Inst", "classFIX8_1_1Inst.html", "classFIX8_1_1Inst" ],
    [ "BaseEntry", "structFIX8_1_1BaseEntry.html", "structFIX8_1_1BaseEntry" ],
    [ "fdoutbuf", "classFIX8_1_1fdoutbuf.html", "classFIX8_1_1fdoutbuf" ],
    [ "fptrostream", "classFIX8_1_1fptrostream.html", "classFIX8_1_1fptrostream" ],
    [ "bcoutbuf", "classFIX8_1_1bcoutbuf.html", "classFIX8_1_1bcoutbuf" ],
    [ "bcostream", "classFIX8_1_1bcostream.html", "classFIX8_1_1bcostream" ],
    [ "Logger", "classFIX8_1_1Logger.html", "classFIX8_1_1Logger" ],
    [ "FileLogger", "classFIX8_1_1FileLogger.html", "classFIX8_1_1FileLogger" ],
    [ "PipeLogger", "classFIX8_1_1PipeLogger.html", "classFIX8_1_1PipeLogger" ],
    [ "BCLogger", "classFIX8_1_1BCLogger.html", "classFIX8_1_1BCLogger" ],
    [ "SingleLogger", "classFIX8_1_1SingleLogger.html", "classFIX8_1_1SingleLogger" ],
    [ "GroupBase", "classFIX8_1_1GroupBase.html", "classFIX8_1_1GroupBase" ],
    [ "Router", "classFIX8_1_1Router.html", "classFIX8_1_1Router" ],
    [ "Minst", "classFIX8_1_1Minst.html", "classFIX8_1_1Minst" ],
    [ "BaseMsgEntry", "structFIX8_1_1BaseMsgEntry.html", "structFIX8_1_1BaseMsgEntry" ],
    [ "F8MetaCntx", "structFIX8_1_1F8MetaCntx.html", "structFIX8_1_1F8MetaCntx" ],
    [ "MessageBase", "classFIX8_1_1MessageBase.html", "classFIX8_1_1MessageBase" ],
    [ "Message", "classFIX8_1_1Message.html", "classFIX8_1_1Message" ],
    [ "f8_scoped_lock_impl", "classFIX8_1_1f8__scoped__lock__impl.html", "classFIX8_1_1f8__scoped__lock__impl" ],
    [ "Persister", "classFIX8_1_1Persister.html", "classFIX8_1_1Persister" ],
    [ "BDBPersister", "classFIX8_1_1BDBPersister.html", "classFIX8_1_1BDBPersister" ],
    [ "MemoryPersister", "classFIX8_1_1MemoryPersister.html", "classFIX8_1_1MemoryPersister" ],
    [ "Prec", "structFIX8_1_1Prec.html", "structFIX8_1_1Prec" ],
    [ "IPrec", "structFIX8_1_1IPrec.html", "structFIX8_1_1IPrec" ],
    [ "FilePersister", "classFIX8_1_1FilePersister.html", "classFIX8_1_1FilePersister" ],
    [ "SessionID", "classFIX8_1_1SessionID.html", "classFIX8_1_1SessionID" ],
    [ "LoginParameters", "structFIX8_1_1LoginParameters.html", "structFIX8_1_1LoginParameters" ],
    [ "Session", "classFIX8_1_1Session.html", "classFIX8_1_1Session" ],
    [ "SessionConfig", "structFIX8_1_1SessionConfig.html", "structFIX8_1_1SessionConfig" ],
    [ "ClientSession", "classFIX8_1_1ClientSession.html", "classFIX8_1_1ClientSession" ],
    [ "ReliableClientSession", "classFIX8_1_1ReliableClientSession.html", "classFIX8_1_1ReliableClientSession" ],
    [ "ServerSession", "classFIX8_1_1ServerSession.html", "classFIX8_1_1ServerSession" ],
    [ "SessionInstance", "classFIX8_1_1SessionInstance.html", "classFIX8_1_1SessionInstance" ],
    [ "reference_wrapper", "classFIX8_1_1reference__wrapper.html", "classFIX8_1_1reference__wrapper" ],
    [ "_dthreadcore", "classFIX8_1_1__dthreadcore.html", "classFIX8_1_1__dthreadcore" ],
    [ "dthread", "classFIX8_1_1dthread.html", "classFIX8_1_1dthread" ],
    [ "dthread<>", "classFIX8_1_1dthread_3_4.html", "classFIX8_1_1dthread_3_4" ],
    [ "Tickval", "classFIX8_1_1Tickval.html", "classFIX8_1_1Tickval" ],
    [ "Timer", "classFIX8_1_1Timer.html", "classFIX8_1_1Timer" ],
    [ "TimerEvent", "classFIX8_1_1TimerEvent.html", "classFIX8_1_1TimerEvent" ],
    [ "IntervalTimer", "classFIX8_1_1IntervalTimer.html", "classFIX8_1_1IntervalTimer" ],
    [ "FieldTrait", "structFIX8_1_1FieldTrait.html", "structFIX8_1_1FieldTrait" ],
    [ "FieldTrait_Hash_Array", "structFIX8_1_1FieldTrait__Hash__Array.html", "structFIX8_1_1FieldTrait__Hash__Array" ],
    [ "presorted_set< unsigned short, FieldTrait, FieldTrait::Compare >", "classFIX8_1_1presorted__set_3_01unsigned_01short_00_01FieldTrait_00_01FieldTrait_1_1Compare_01_4.html", "classFIX8_1_1presorted__set_3_01unsigned_01short_00_01FieldTrait_00_01FieldTrait_1_1Compare_01_4" ],
    [ "FieldTraits", "classFIX8_1_1FieldTraits.html", "classFIX8_1_1FieldTraits" ],
    [ "Ctxt", "structFIX8_1_1Ctxt.html", "structFIX8_1_1Ctxt" ],
    [ "RealmObject", "classFIX8_1_1RealmObject.html", "classFIX8_1_1RealmObject" ],
    [ "TypedRealm", "classFIX8_1_1TypedRealm.html", "classFIX8_1_1TypedRealm" ],
    [ "StringRealm", "structFIX8_1_1StringRealm.html", "structFIX8_1_1StringRealm" ],
    [ "CharRealm", "structFIX8_1_1CharRealm.html", "structFIX8_1_1CharRealm" ],
    [ "FieldSpec", "structFIX8_1_1FieldSpec.html", "structFIX8_1_1FieldSpec" ],
    [ "MessageSpec", "structFIX8_1_1MessageSpec.html", "structFIX8_1_1MessageSpec" ],
    [ "push_dir", "classFIX8_1_1push__dir.html", "classFIX8_1_1push__dir" ]
];