fix8: FIX8::States Namespace Reference
FIX8::States Namespace Reference
Session states and semantics.
Enumerations
enum SessionStates {
st_none, st_continuous, st_session_terminated, st_wait_for_logon,
st_not_logged_in, st_logon_sent, st_logon_received, st_logoff_sent,
st_logoff_received, st_test_request_sent, st_sequence_reset_sent, st_sequence_reset_received,
st_resend_request_sent, st_resend_request_received, st_num_states
}
Functions
static bool is_live (SessionStates ss)
static bool is_established (SessionStates ss)
Detailed Description
Session states and semantics.
Enumeration Type Documentation
enum FIX8::States::SessionStates
Enumerator
st_none
st_continuous
st_session_terminated
st_wait_for_logon
st_not_logged_in
st_logon_sent
st_logon_received
st_logoff_sent
st_logoff_received
st_test_request_sent
st_sequence_reset_sent
st_sequence_reset_received
st_resend_request_sent
st_resend_request_received
st_num_states
Definition at line 158 of file session.hpp.
    {
       st_none, st_continuous, st_session_terminated,
       st_wait_for_logon, st_not_logged_in, st_logon_sent, st_logon_received, st_logoff_sent, st_logoff_received,
       st_test_request_sent, st_sequence_reset_sent, st_sequence_reset_received,
       st_resend_request_sent, st_resend_request_received, st_num_states
    };
Function Documentation
static bool FIX8::States::is_established (SessionStates ss) inline static
Determine if this session is in an established state
Parameters
ss SessateState to test
Returns
true if established
Definition at line 175 of file session.hpp.
References is_live(), st_logon_sent, st_not_logged_in, and st_wait_for_logon.
Referenced by FIX8::Session::enforce().
       { return ss != st_wait_for_logon && ss != st_not_logged_in && ss != st_logon_sent && is_live(ss); }
static bool FIX8::States::is_live (SessionStates ss) inline static
Determine if this session is live
Parameters
ss SessateState to test
Returns
true if live
Definition at line 169 of file session.hpp.
References st_none, and st_session_terminated.
Referenced by is_established().
       { return ss != st_none && ss != st_session_terminated; }