fix8: popen.c File Reference
popen.c File Reference
#include <stdio.h>
#include <errno.h>
#include <sys/wait.h>
#include <string.h>
#include <signal.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
Macros
#define CF_BUFSIZE 4096
#define CF_MAXSHELLARGS 20
Functions
int SplitCommand (char *comm, char arg[CF_MAXSHELLARGS][CF_BUFSIZE])
FILE * cfpopen (char *command, char *type)
int cfpclose (FILE *pp)
Variables
pid_t * CHILD
int MAXFD = 20
Macro Definition Documentation
#define CF_BUFSIZE 4096
Definition at line 51 of file popen.c.
Referenced by cfpopen().
#define CF_MAXSHELLARGS 20
Definition at line 52 of file popen.c.
Referenced by cfpopen(), and SplitCommand().
Function Documentation
int cfpclose (FILE * pp)
Definition at line 199 of file popen.c.
References CHILD, and MAXFD.
Referenced by FIX8::fptrostream::~fptrostream().
FILE* cfpopen (char * command, char * type)
Definition at line 61 of file popen.c.
References CF_BUFSIZE, CF_MAXSHELLARGS, CHILD, MAXFD, and SplitCommand().
Referenced by FIX8::PipeLogger::PipeLogger().
int SplitCommand (char * comm, char arg[CF_MAXSHELLARGS][CF_BUFSIZE])
Definition at line 240 of file popen.c.
References CF_MAXSHELLARGS.
Referenced by cfpopen().
Variable Documentation
pid_t* CHILD
Definition at line 54 of file popen.c.
Referenced by cfpclose(), and cfpopen().
int MAXFD = 20
Definition at line 55 of file popen.c.
Referenced by cfpclose(), and cfpopen().