fix8: pthread_minport_windows.h File Reference
pthread_minport_windows.h File Reference
#include <Windows.h>
#include <WinBase.h>
#include <process.h>
#include <intrin.h>
#include <stdio.h>
#include <errno.h>
#include <time.h>
Classes
struct _opaque_pthread_attr_t
struct _opaque_pthread_mutexattr_t
struct _opaque_pthread_condattr_t
Macros
#define INLINE __forceinline
#define NOINLINE __declspec(noinline)
#define RESTRICT __declspec()
#define PTHREAD_CANCEL_ENABLE 0x01 /* Cancel takes place at next cancellation point */
#define PTHREAD_CANCEL_DISABLE 0x00 /* Cancel postponed */
#define PTHREAD_CANCEL_DEFERRED 0x02 /* Cancel waits until cancellation point */
Typedefs
typedef HANDLE pthread_t
typedef struct
_opaque_pthread_attr_t pthread_attr_t
typedef struct
_opaque_pthread_mutexattr_t pthread_mutexattr_t
typedef struct
_opaque_pthread_condattr_t pthread_condattr_t
typedef DWORD pthread_key_t
typedef CRITICAL_SECTION pthread_mutex_t
typedef CONDITION_VARIABLE pthread_cond_t
Functions
INLINE int pthread_create (pthread_t RESTRICT *thread, const pthread_attr_t RESTRICT *attr, void *(*start_routine)(void *), void RESTRICT *arg)
INLINE int pthread_join (pthread_t thread, void **value_ptr)
INLINE void pthread_exit (void *value_ptr)
INLINE int pthread_attr_init (pthread_attr_t *attr)
INLINE int pthread_attr_destroy (pthread_attr_t *attr)
INLINE int pthread_setcancelstate (int state, int *oldstate)
INLINE int pthread_mutex_init (pthread_mutex_t RESTRICT *mutex, const pthread_mutexattr_t RESTRICT *attr)
INLINE int pthread_mutex_lock (pthread_mutex_t *mutex)
INLINE int pthread_mutex_unlock (pthread_mutex_t *mutex)
INLINE int pthread_mutex_destroy (pthread_mutex_t *mutex)
INLINE pthread_t pthread_self (void)
INLINE int pthread_key_create (pthread_key_t *key, void(*destructor)(void *))
INLINE int pthread_key_delete (pthread_key_t key)
INLINE int pthread_setspecific (pthread_key_t key, const void *value)
INLINE void * pthread_getspecific (pthread_key_t key)
INLINE int pthread_cond_init (pthread_cond_t RESTRICT *cond, const pthread_condattr_t RESTRICT *attr)
INLINE int pthread_cond_signal (pthread_cond_t *cond)
INLINE int pthread_cond_broadcast (pthread_cond_t *cond)
INLINE int pthread_cond_wait (pthread_cond_t RESTRICT *cond, pthread_mutex_t RESTRICT *mutex)
INLINE int pthread_cond_destroy (pthread_cond_t *cond)
Macro Definition Documentation
#define INLINE __forceinline
Definition at line 41 of file pthread_minport_windows.h.
#define NOINLINE __declspec(noinline)
Definition at line 42 of file pthread_minport_windows.h.
#define PTHREAD_CANCEL_DEFERRED 0x02 /* Cancel waits until cancellation point */
Definition at line 49 of file pthread_minport_windows.h.
#define PTHREAD_CANCEL_DISABLE 0x00 /* Cancel postponed */
Definition at line 48 of file pthread_minport_windows.h.
Referenced by ff::ff_thread::disable_cancelability().
#define PTHREAD_CANCEL_ENABLE 0x01 /* Cancel takes place at next cancellation point */
Definition at line 47 of file pthread_minport_windows.h.
#define RESTRICT __declspec()
Definition at line 43 of file pthread_minport_windows.h.
Typedef Documentation
typedef struct _opaque_pthread_attr_t pthread_attr_t
typedef CONDITION_VARIABLE pthread_cond_t
Definition at line 156 of file pthread_minport_windows.h.
typedef struct _opaque_pthread_condattr_t pthread_condattr_t
typedef DWORD pthread_key_t
Definition at line 57 of file pthread_minport_windows.h.
typedef CRITICAL_SECTION pthread_mutex_t
Definition at line 62 of file pthread_minport_windows.h.
typedef struct _opaque_pthread_mutexattr_t pthread_mutexattr_t
typedef HANDLE pthread_t
Definition at line 52 of file pthread_minport_windows.h.
Function Documentation
INLINE int pthread_attr_destroy (pthread_attr_t * attr)
Definition at line 97 of file pthread_minport_windows.h.
Referenced by ff::ff_thread::wait(), and FIX8::_dthreadcore::~_dthreadcore().
INLINE int pthread_attr_init (pthread_attr_t * attr)
Definition at line 92 of file pthread_minport_windows.h.
Referenced by FIX8::_dthreadcore::_dthreadcore(), and ff::ff_thread::spawn().
INLINE int pthread_cond_broadcast (pthread_cond_t * cond)
Definition at line 170 of file pthread_minport_windows.h.
Referenced by ff::Barrier::doBarrier().
INLINE int pthread_cond_destroy (pthread_cond_t * cond)
Definition at line 182 of file pthread_minport_windows.h.
INLINE int pthread_cond_init (pthread_cond_t RESTRICT * cond, const pthread_condattr_t RESTRICT * attr)
Definition at line 158 of file pthread_minport_windows.h.
Referenced by ff::Barrier::Barrier(), and ff::ff_thread::ff_thread().
INLINE int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 165 of file pthread_minport_windows.h.
Referenced by popsignal(), ff::ff_thread::thaw(), and ff::ff_thread::thread_routine().
INLINE int pthread_cond_wait (pthread_cond_t RESTRICT * cond, pthread_mutex_t RESTRICT * mutex)
Definition at line 175 of file pthread_minport_windows.h.
Referenced by ff::Barrier::doBarrier(), pushwait(), ff::ff_thread::thaw(), ff::ff_thread::thread_routine(), and ff::ff_thread::wait_freezing().
INLINE int pthread_create (pthread_t RESTRICT * thread, const pthread_attr_t RESTRICT * attr, void *(*)(void *) start_routine, void RESTRICT * arg)
Definition at line 64 of file pthread_minport_windows.h.
Referenced by FIX8::_dthreadcore::_start(), and ff::ff_thread::spawn().
INLINE void pthread_exit (void * value_ptr)
Definition at line 85 of file pthread_minport_windows.h.
Referenced by FIX8::_dthreadcore::exit(), and ff::proxy_thread_routine().
INLINE void* pthread_getspecific (pthread_key_t key)
Definition at line 150 of file pthread_minport_windows.h.
Referenced by ff::FFAllocator::deleteAllocator(), ff::FFAllocator::growsup(), ff::FFAllocator::malloc(), ff::FFAllocator::posix_memalign(), and ff::FFAllocator::realloc().
INLINE int pthread_join (pthread_t thread, void ** value_ptr)
Definition at line 74 of file pthread_minport_windows.h.
Referenced by FIX8::_dthreadcore::join(), and ff::ff_thread::wait().
INLINE int pthread_key_create (pthread_key_t * key, void(*)(void *) destructor)
Definition at line 135 of file pthread_minport_windows.h.
Referenced by ff::FFAllocator::FFAllocator().
INLINE int pthread_key_delete (pthread_key_t key)
Definition at line 140 of file pthread_minport_windows.h.
Referenced by ff::FFAllocator::~FFAllocator().
INLINE int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 125 of file pthread_minport_windows.h.
Referenced by FIX8::f8_mutex::~f8_mutex().
INLINE int pthread_mutex_init (pthread_mutex_t RESTRICT * mutex, const pthread_mutexattr_t RESTRICT * attr)
Definition at line 108 of file pthread_minport_windows.h.
Referenced by ff::Barrier::Barrier(), Environment::Environment(), FIX8::f8_mutex::f8_mutex(), and ff::ff_thread::ff_thread().
INLINE int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 115 of file pthread_minport_windows.h.
Referenced by Environment::createEntry(), ff::Barrier::doBarrier(), Environment::instance(), FIX8::f8_mutex::lock(), popsignal(), pushwait(), ff::ff_thread::thaw(), ff::ff_thread::thread_routine(), and ff::ff_thread::wait_freezing().
INLINE int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 120 of file pthread_minport_windows.h.
Referenced by Environment::createEntry(), ff::Barrier::doBarrier(), Environment::instance(), popsignal(), pushwait(), ff::ff_thread::thaw(), ff::ff_thread::thread_routine(), FIX8::f8_mutex::unlock(), and ff::ff_thread::wait_freezing().
INLINE pthread_t pthread_self (void)
Definition at line 131 of file pthread_minport_windows.h.
Referenced by FIX8::_dthreadcore::getid(), ff::SlabCache::putitem(), ff::SlabCache::register4free(), and FIX8::Logger::send().
INLINE int pthread_setcancelstate (int state, int * oldstate)
Definition at line 102 of file pthread_minport_windows.h.
Referenced by ff::ff_thread::disable_cancelability(), and ff::ff_thread::enable_cancelability().
INLINE int pthread_setspecific (pthread_key_t key, const void * value)
Definition at line 145 of file pthread_minport_windows.h.
Referenced by ff::FFAllocator::malloc(), and ff::FFAllocator::posix_memalign().