fix8: seqedit.cpp File Reference
seqedit.cpp File Reference
#include "precomp.hpp"
#include <fix8/f8includes.hpp>
#include <fix8/usage.hpp>
Functions
const string GETARGLIST ("hvdDR:S:iq")
void print_usage ()
int main (int argc, char **argv)
Detailed Description
seqedit – edit next expected send/receive
Usage: seqedit [-DRSdhiqv] <perist file prefix> -D,–rawdump dump all the raw data records referenced in the index
-R,–receive set next expected receive sequence number
-S,–send set next send sequence number
-d,–dump dump all the records in both the index and the data file
-h,–help help, this screen
-i,–index only dump the index not the data records
-q,–quiet set the sequence numbers silently
-v,–version print version, exit
e.g.
seqedit client.DLD_TEX.TEX_DLD
seqedit -R 23417 -S 2341 client.DLD_TEX.TEX_DLD
seqedit -d client.DLD_TEX.TEX_DLD
seqedit -D client.DLD_TEX.TEX_DLD
seqedit -id client.DLD_TEX.TEX_DLD
Definition in file seqedit.cpp.
Function Documentation
const string GETARGLIST ("hvdDR:S:iq")
Referenced by main(), and print_usage().
int main (int argc, char ** argv)
Definition at line 84 of file seqedit.cpp.
References FIX8::Prec::_offset, FIX8::IPrec::_prec, FIX8::IPrec::_seq, FIX8::Prec::_size, FIX8_MAX_MSG_LENGTH, FIX8_PACKAGE, FIX8_VERSION, GETARGLIST(), next_receive(), next_send(), O_BINARY, print_usage(), and quiet().
 {
    bool dump(false), rawdump(false), indexonly(false), quiet(false);
    int val;
    unsigned next_send(0), next_receive(0);
 #ifdef FIX8_HAVE_GETOPT_LONG
    const option long_options[]
    {
       { "help",      0, 0, 'h' },
       { "dump",      0, 0, 'd' },
       { "version",   0, 0, 'v' },
       { "rawdump",   0, 0, 'D' },
       { "index",     0, 0, 'i' },
       { "quiet",     0, 0, 'q' },
       { "send",      1, 0, 'S' },
       { "receive",   1, 0, 'R' },
       { 0 },
    };
    while ((val = getopt_long (argc, argv, GETARGLIST.c_str(), long_options, 0)) != -1)
 #else
    while ((val = getopt (argc, argv, GETARGLIST.c_str())) != -1)
 #endif
    {
       switch (val)
       {
       case 'v':
          cout << "seqedit for " FIX8_PACKAGE " version " FIX8_VERSION << endl;
          cout << "Released under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3. See <http://fsf.org/> for details." << endl;
          return 0;
       case 'h': print_usage(); return 0;
       case 'D': rawdump = true; // drop through
       case 'd': dump = true; break;
       case 'i': indexonly = true; break;
       case 'q': quiet = true; break;
       case 'S': next_send = stoul(optarg); break;
       case 'R': next_receive = stoul(optarg); break;
       case ':': case '?': return 1;
       default: break;
       }
    }
    if (optind >= argc)
    {
       cerr << "no input persistence file prefix specified" << endl;
       return 1;
    }
    const string dbFname(argv[optind]);
    const string dbIname(dbFname + ".idx");
    struct fdset
    {
       int fod, iod;
       fdset() : fod(), iod() {}
       ~fdset() { close(iod); close(fod); }
    }
    fds;
    if ((fds.fod = open(dbFname.c_str(), O_RDONLY | O_BINARY)) < 0)
    {
       cerr << "Error opening existing database: " << dbFname << " (" << strerror(errno) << ')' << endl;
       return 1;
    }
    if ((fds.iod = open(dbIname.c_str(), O_RDWR | O_BINARY)) < 0)
    {
       cerr << "Error opening existing database index: " << dbIname << " (" << strerror(errno) << ')' << endl;
       return 1;
    }
    IPrec iprec;
    ssize_t blrd(read(fds.iod, static_cast<void *>(&iprec), sizeof(IPrec)));
    if (blrd <= 0)
    {
       cerr << "Error reading existing database index: " << dbIname << " (" << strerror(errno) << ')' << endl;
       return 1;
    }
    if (!rawdump && !quiet)
    {
       cout << endl;
       cout << "Next      send         receive" << endl;
       cout << "==============================" << endl;
       cout << "Current   " << left << setw(10) << iprec._prec._offset << right << setw(10) << iprec._prec._size << endl;
    }
    if (!dump)
    {
       if (next_send > 0 || next_receive > 0)
       {
          if (next_send)
             iprec._prec._offset = next_send;
          if (next_receive)
             iprec._prec._size = next_receive;
          if (lseek(fds.iod, 0, SEEK_SET) < 0)
          {
             ostringstream eostr;
             cerr << "Error could not seek to 0 for seqnum persitence: " << dbIname << endl;
             return 1;
          }
          if (write (fds.iod, static_cast<void *>(&iprec), sizeof(iprec)) != sizeof(iprec))
          {
             ostringstream eostr;
             cerr << "Error writing seqnum persitence: " << dbIname << endl;
             return 1;
          }
          if (!quiet)
             cout << "New       " << left << setw(10) << iprec._prec._offset << right << setw(10) << iprec._prec._size << endl;
       }
       cout << endl;
    }
    else for(;;)
    {
       blrd = read(fds.iod, static_cast<void *>(&iprec), sizeof(IPrec));
       if (blrd < 0)
       {
          cerr << "Error reading existing database index: " << dbIname << " (" << strerror(errno) << ')' << endl;
          return 1;
       }
       if (blrd == 0)
          break; // eof
       if (!rawdump)
          cout << iprec << endl;
       if (iprec._seq == 0)
          continue;
       char buff[FIX8_MAX_MSG_LENGTH] {};
       if (lseek(fds.fod, iprec._prec._offset, SEEK_SET) < 0)
       {
          cerr << "Error could not seek to correct index location " << iprec._prec._offset << " for get: " << dbFname << endl;
          return 1;
       }
       int bytes_read = 0;
       if ((bytes_read = read(fds.fod, buff, iprec._prec._size)) != iprec._prec._size)
       {
          cerr << "Error could not read message record for seqnum " << iprec._seq << " from: " << dbFname
                << ": trying to read " << iprec._prec._size << ", but available " << bytes_read
                << endl;
          return 1;
       }
       if (rawdump)
          cout.write(buff, iprec._prec._size);
       else if (!indexonly)
          cout << buff << endl;
    }
    return 0;
 }
void print_usage ()
Definition at line 240 of file seqedit.cpp.
References UsageMan::add(), GETARGLIST(), UsageMan::print(), and UsageMan::setdesc().
Referenced by main().
 {
    UsageMan um("seqedit", GETARGLIST, "<perist file prefix>");
    um.setdesc("seqedit -- edit next expected send/receive for file based persister. Note: fix8pro users should use f8pseqedit which works with any persister");
    um.add('R', "receive", "set next expected receive sequence number");
    um.add('S', "send", "set next send sequence number");
    um.add('d', "dump", "dump all the records in both the index and the data file");
    um.add('D', "rawdump", "dump all the raw data records referenced in the index");
    um.add('h', "help", "help, this screen");
    um.add('i', "index", "only dump the index not the data records");
    um.add('q', "quiet", "set the sequence numbers silently");
    um.add('v', "version", "print version, exit");
    um.add("e.g.");
    um.add("@seqedit client.DLD_TEX.TEX_DLD");
    um.add("@seqedit -R 23417 -S 2341 client.DLD_TEX.TEX_DLD");
    um.add("@seqedit -d client.DLD_TEX.TEX_DLD");
    um.add("@seqedit -D client.DLD_TEX.TEX_DLD");
    um.add("@seqedit -id client.DLD_TEX.TEX_DLD");
    um.add("@seqedit -S 2005 server.TEX_DLD.DLD_TEX");
    um.print(cerr);
 }