fix8: session_test.cpp File Reference
session_test.cpp File Reference
#include <f8headers.hpp>
#include <f8config.h>
#include <errno.h>
#include <f8exception.hpp>
#include <hypersleep.hpp>
#include <mpmc.hpp>
#include <f8types.hpp>
#include <f8utils.hpp>
#include <xml.hpp>
#include <thread.hpp>
#include <gzstream.hpp>
#include <tickval.hpp>
#include <logger.hpp>
#include <traits.hpp>
#include <timer.hpp>
#include <field.hpp>
#include <message.hpp>
#include <mockConnection.hpp>
#include <session.hpp>
#include <configuration.hpp>
#include <persist.hpp>
#include <sessionwrapper.hpp>
#include "utest_types.hpp"
#include "utest_router.hpp"
#include "utest_classes.hpp"
#include "gtest/gtest.h"
#include "../runtime/session.cpp"
Classes
class test_session
a test session
class session_fixture
a session fixture to create and destory test session
class initiator_fixture
a initiator fixture, inherited from session_fixture
class sessionTest
gtest test suit event
Functions
TEST (sessionId, sessionId)
void fillSendHeader (MessageBase *header, unsigned seq)
void fillRecvHeader (MessageBase *header)
f8String getSingleMsg ()
helper to get the last output message
std::vector< f8String > getMsgs ()
helper to get all output messages
void clearOutputs ()
helper to clear cached output messages
f8String composeOrder (unsigned seq)
TEST_F (sessionTest, logon)
TEST_F (sessionTest, handle_resend_request)
TEST_F (sessionTest, handle_seq_reset)
TEST_F (sessionTest, handle_test_request)
TEST_F (sessionTest, send_test_request)
Function Documentation
void clearOutputs ()
helper to clear cached output messages
Definition at line 287 of file session_test.cpp.
References initiator_fixture::initiator, and sessionTest::initiator_test.
Referenced by TEST_F().
f8String composeOrder (unsigned seq)
helper to create a single new order and encode it to string
Parameters
seq sequence number
Returns
new order entry in string format
Definition at line 296 of file session_test.cpp.
References fillSendHeader(), FIX8::TEX::HandlInst_AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION(), FIX8::TEX::OrdType_LIMIT(), FIX8::TEX::SecurityType_OPTION(), FIX8::TEX::Side_BUY(), and FIX8::TEX::TimeInForce_DAY().
Referenced by TEST_F().
void fillRecvHeader (MessageBase * header)
helper to fill output message header
Parameters
header message header pointer
Definition at line 254 of file session_test.cpp.
References sessionTest::recv_seq.
Referenced by TEST_F().
void fillSendHeader (MessageBase * header, unsigned seq)
helper to fill incoming message header
Parameters
header message header pointer
seq sequence number
Definition at line 240 of file session_test.cpp.
Referenced by composeOrder(), and TEST_F().
std::vector<f8String> getMsgs ()
helper to get all output messages
Definition at line 279 of file session_test.cpp.
References initiator_fixture::initiator, and sessionTest::initiator_test.
Referenced by TEST_F().
f8String getSingleMsg ()
helper to get the last output message
Definition at line 266 of file session_test.cpp.
References initiator_fixture::initiator, and sessionTest::initiator_test.
Referenced by TEST_F().
TEST (sessionId , sessionId)
class SessionID test
Parameters
sessionId test suit name
sessionId test case name
Definition at line 88 of file session_test.cpp.
References FIX8::SessionID::get_beginString(), FIX8::SessionID::get_senderCompID(), and FIX8::SessionID::get_targetCompID().
TEST_F (sessionTest , logon)
session logon test
Parameters
sessionTest test suit name
logon test case name
Definition at line 324 of file session_test.cpp.
References clearOutputs(), fillRecvHeader(), getSingleMsg(), FIX8::States::st_continuous, and FIX8::States::st_logon_sent.
TEST_F (sessionTest , handle_resend_request)
session resend request test
Parameters
sessionTest test suit name
handle_resend_request test case name
Definition at line 354 of file session_test.cpp.
References clearOutputs(), composeOrder(), fillRecvHeader(), fillSendHeader(), getMsgs(), getSingleMsg(), and FIX8::States::st_continuous.
TEST_F (sessionTest , handle_seq_reset)
session sequence rest test
Parameters
sessionTest test suit name
handle_seq_reset test case name
Definition at line 462 of file session_test.cpp.
References fillRecvHeader().
TEST_F (sessionTest , handle_test_request)
incoming test request test
Parameters
sessionTest test suit name
handle_test_request test case name
Definition at line 482 of file session_test.cpp.
References clearOutputs(), fillRecvHeader(), and getSingleMsg().
TEST_F (sessionTest , send_test_request)
output test request test
Parameters
sessionTest test suit name
send_test_request test case name
Definition at line 506 of file session_test.cpp.
References clearOutputs(), fillRecvHeader(), getMsgs(), FIX8::States::st_continuous, FIX8::States::st_logoff_sent, and FIX8::States::st_test_request_sent.