fix8: spin-lock.hpp File Reference
spin-lock.hpp File Reference
This file contains the spin lock(s) used in FastFlow.
#include <ff/sysdep.h>
#include <ff/platforms/platform.h>
#include <ff/config.hpp>
#include <ff/atomic/abstraction_dcas.h>
Macros
#define _INLINE __forceinline
Typedefs
typedef volatile int lock_t [1]
Enumerations
enum { UNLOCKED =0 }
Functions
_INLINE void init_unlocked (lock_t l)
_INLINE void init_locked (lock_t l)
_INLINE void spin_lock (lock_t l)
_INLINE void spin_unlock (lock_t l)
Detailed Description
This file contains the spin lock(s) used in FastFlow.
Definition in file spin-lock.hpp.
Macro Definition Documentation
#define _INLINE __forceinline
Definition at line 42 of file spin-lock.hpp.
Typedef Documentation
typedef volatile int lock_t[1]
Definition at line 181 of file spin-lock.hpp.
Enumeration Type Documentation
anonymous enum
Enumerator
UNLOCKED
Definition at line 180 of file spin-lock.hpp.
Function Documentation
_INLINE void init_locked (lock_t l)
Definition at line 184 of file spin-lock.hpp.
References UNLOCKED.
_INLINE void init_unlocked (lock_t l)
Definition at line 183 of file spin-lock.hpp.
References UNLOCKED.
Referenced by ff::dynqueue::dynqueue(), ff::ff_node::ff_node(), ff::FFAllocator::FFAllocator(), ff::SlabCache::init(), and ff::uSWSR_Ptr_Buffer::uSWSR_Ptr_Buffer().
_INLINE void spin_lock (lock_t l)
Definition at line 213 of file spin-lock.hpp.
References UNLOCKED.
Referenced by ff::SlabCache::checkReclaim(), ff::FFAllocator::deleteAllocator(), ff::ffTime(), ff::FFAllocator::malloc(), ff::uSWSR_Ptr_Buffer::mc_pop(), ff::dynqueue::mp_allocnode(), ff::dynqueue::mp_pop(), ff::dynqueue::mp_push(), ff::uSWSR_Ptr_Buffer::mp_push(), ff::FFAllocator::newAllocator(), ff::FFAllocator::posix_memalign(), and ff::SlabCache::register4free().
_INLINE void spin_unlock (lock_t l)
Definition at line 219 of file spin-lock.hpp.
References UNLOCKED.
Referenced by ff::SlabCache::checkReclaim(), ff::FFAllocator::deleteAllocator(), ff::ffTime(), ff::FFAllocator::malloc(), ff::uSWSR_Ptr_Buffer::mc_pop(), ff::dynqueue::mp_allocnode(), ff::dynqueue::mp_pop(), ff::dynqueue::mp_push(), ff::uSWSR_Ptr_Buffer::mp_push(), ff::FFAllocator::newAllocator(), ff::FFAllocator::posix_memalign(), and ff::SlabCache::register4free().