fix8: FIX8::StaticTable< Key, Val, Compare > Struct Template Reference
FIX8::StaticTable< Key, Val, Compare > Struct Template Reference
A specialised map to enable native static initalisation.
#include <f8types.hpp>
Public Types
typedef std::map< Key, Val,
Compare > TypeMap
typedef TypeMap::value_type TypePair
typedef Val NotFoundType
Public Member Functions
StaticTable ()
Ctor.
Static Public Member Functions
static const Val find_value (const Key &key)
static const Val & find_ref (const Key &key)
static const Val * find_ptr (const Key &key)
static size_t get_count ()
static const TypePair * get_table_end ()
Static Public Attributes
static const TypePair _valueTable []
The actual data set.
static const TypeMap _valuemap
The container.
static const NotFoundType _noval
The value to return when the key is not found.
Detailed Description
template<typename Key, typename Val, typename Compare = std::less<Key>>
struct FIX8::StaticTable< Key, Val, Compare >
A specialised map to enable native static initalisation.
Template Parameters:
Key the key
Val the value
Compare the comparitor
Definition at line 127 of file f8types.hpp.
Member Typedef Documentation
template<typename Key, typename Val, typename Compare = std::less<Key>> typedef Val FIX8::StaticTable< Key, Val, Compare >::NotFoundType
Definition at line 131 of file f8types.hpp.
template<typename Key, typename Val, typename Compare = std::less<Key>> typedef std::map<Key, Val, Compare> FIX8::StaticTable< Key, Val, Compare >::TypeMap
Definition at line 129 of file f8types.hpp.
template<typename Key, typename Val, typename Compare = std::less<Key>> typedef TypeMap::value_type FIX8::StaticTable< Key, Val, Compare >::TypePair
Definition at line 130 of file f8types.hpp.
Constructor & Destructor Documentation
template<typename Key, typename Val, typename Compare = std::less<Key>> FIX8::StaticTable< Key, Val, Compare >::StaticTable () [inline]
Ctor.
Definition at line 143 of file f8types.hpp.
Member Function Documentation
template<typename Key, typename Val, typename Compare = std::less<Key>> static const Val* FIX8::StaticTable< Key, Val, Compare >::find_ptr (const Key & key) [inline, static]
Find a key (pointer).
Parameters:
key the key to find
Returns:
value found (pointer) or 0 if not found
Definition at line 166 of file f8types.hpp.
template<typename Key, typename Val, typename Compare = std::less<Key>> static const Val& FIX8::StaticTable< Key, Val, Compare >::find_ref (const Key & key) [inline, static]
Find a key (reference).
Parameters:
key the key to find
Returns:
value found (reference) or _noval if not found
Definition at line 157 of file f8types.hpp.
Referenced by generate_group_bodies(), generate_preamble(), main(), process(), MyMenu::process(), and FIX8::Session::process().
template<typename Key, typename Val, typename Compare = std::less<Key>> static const Val FIX8::StaticTable< Key, Val, Compare >::find_value (const Key & key) [inline, static]
Find a key (value).
Parameters:
key the key to find
Returns:
value found (value) or _noval if not found
Definition at line 148 of file f8types.hpp.
template<typename Key, typename Val, typename Compare = std::less<Key>> static size_t FIX8::StaticTable< Key, Val, Compare >::get_count () [inline, static]
Get the number of elements in the data set.
Returns:
number of elements
Definition at line 174 of file f8types.hpp.
template<typename Key, typename Val, typename Compare = std::less<Key>> static const TypePair* FIX8::StaticTable< Key, Val, Compare >::get_table_end () [inline, static]
Get a pointer to the end of the data set. Used as an end inputiterator for initialisation.
Returns:
pointer to end of table
Definition at line 178 of file f8types.hpp.
Member Data Documentation
template<typename Key, typename Val, typename Compare = std::less<Key>> const NotFoundType FIX8::StaticTable< Key, Val, Compare >::_noval [static]
The value to return when the key is not found.
Definition at line 140 of file f8types.hpp.
Referenced by FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::find_ref(), and FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::find_value().
template<typename Key, typename Val, typename Compare = std::less<Key>> const TypeMap FIX8::StaticTable< Key, Val, Compare >::_valuemap [static]
The container.
Definition at line 137 of file f8types.hpp.
Referenced by FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::find_ptr(), FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::find_ref(), FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::find_value(), and FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::get_count().
template<typename Key, typename Val, typename Compare = std::less<Key>> const TypePair FIX8::StaticTable< Key, Val, Compare >::_valueTable[] [static]
The actual data set.
Definition at line 134 of file f8types.hpp.
Referenced by FIX8::StaticTable< const f8String, bool(Session::*)(const unsigned, const Message *)>::get_table_end().
The documentation for this struct was generated from the following file:
f8types.hpp