fix8: FIX8::Schedule Struct Reference
FIX8::Schedule Struct Reference
#include <session.hpp>
Public Member Functions
Schedule ()
Schedule (Tickval start, Tickval end, Tickval duration=Tickval(), int utc_offset=0, int start_day=-1, int end_day=-1)
Schedule (const Schedule &from)
Schedule & operator= (const Schedule &that)
bool is_valid () const
bool test (bool prev=false) const
Public Attributes
Tickval _start
Tickval _end
Tickval _duration
int _utc_offset
int _start_day
int _end_day
Tickval::ticks _toffset
Friends
std::ostream & operator<< (std::ostream &os, const Schedule &what)
Detailed Description
Definition at line 200 of file session.hpp.
Constructor & Destructor Documentation
FIX8::Schedule::Schedule () inline
Definition at line 206 of file session.hpp.
               : _start(Tickval::errorticks()), _end(Tickval::errorticks()), _utc_offset(),
       _start_day(-1), _end_day(-1) {}
FIX8::Schedule::Schedule (Tickval start, Tickval end, Tickval duration = Tickval(), int utc_offset = 0, int start_day = -1, int end_day = -1) inline
Definition at line 209 of file session.hpp.
                                             :
       _start(start), _end(end), _duration(duration),
       _utc_offset(utc_offset), _start_day(start_day), _end_day(end_day),
       _toffset(static_cast<Tickval::ticks>(_utc_offset) * Tickval::minute)
    {
    }
FIX8::Schedule::Schedule (const Schedule & from) inline
Definition at line 217 of file session.hpp.
                                   :
       _start(from._start), _end(from._end), _duration(from._duration),
       _utc_offset(from._utc_offset), _start_day(from._start_day), _end_day(from._end_day),
       _toffset(from._toffset)
    {
    }
Member Function Documentation
bool FIX8::Schedule::is_valid () const inline
Determine if this schdule is valid
Returns
true if this schedule is valid
Definition at line 242 of file session.hpp.
References FIX8::Tickval::is_errorval().
Referenced by FIX8::Session::handle_logon().
 { return !_start.is_errorval(); }
Schedule& FIX8::Schedule::operator= (const Schedule & that) inline
Definition at line 224 of file session.hpp.
References _duration, _end, _end_day, _start, _start_day, _toffset, and _utc_offset.
    {
       if (this != &that)
       {
          _start = that._start;
          _end = that._end;
          _duration = that._duration;
          _utc_offset = that._utc_offset;
          _start_day = that._start_day;
          _end_day = that._end_day;
          _toffset = that._toffset;
       }
       return *this;
    }
bool FIX8::Schedule::test (bool prev = false) const inline
Take the current local time and test if it is within the range of this schedule
Parameters
prev current bool state that we will toggle
Returns
new toggle state
Definition at line 247 of file session.hpp.
References _end, FIX8::Tickval::adjust(), FIX8::Tickval::day, FIX8::Tickval::get_ticks(), FIX8::Tickval::get_tm(), and FIX8::Tickval::in_range().
Referenced by FIX8::Session::activation_service(), and FIX8::Session::handle_logon().
    {
       Tickval now(true);
       now.adjust(_toffset); // adjust for local utc offset
       const Tickval today(now.get_ticks() - (now.get_ticks() % Tickval::day));
       bool active(prev);
       if (_start_day < 0) // start/end day not specified; daily only
       {
          //cout >> now << ' ' >> (today + _start) << ' ' >> (today + _end) << endl;
          if (now.in_range(today + _start, today + _end))
          {
             if (!prev)
                active = true;
          }
          else if (prev)
             active = false;
       }
       else
       {
          const tm result(now.get_tm());
          //cout >> now << ' ' >> (today + _start) << ' ' >> (today + _end) << ' ' << result.tm_wday << endl;
          if (!prev)
          {
             if ( ((_start_day > _end_day && (result.tm_wday >= _start_day || result.tm_wday <= _end_day))
                || (_start_day < _end_day && result.tm_wday >= _start_day && result.tm_wday <= _end_day))
                && now.in_range(today + _start, today + _end))
                   active = true;
          }
          else if ( ((_start_day > _end_day && (result.tm_wday < _start_day && result.tm_wday > _end_day))
                  || (_start_day < _end_day && result.tm_wday >= _end_day))
                    && now > today + _end)
                active = false;
       }
       return active;
    }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Schedule & what) friend
Inserter friend.
Parameters
os stream to send to
what Session_Schedule reference
Returns
stream
Definition at line 292 of file session.hpp.
    {
       os << "start:" >> what._start << " end:" >> what._end << " duration:" << what._duration
          << " utc_offset:" << what._utc_offset << " start day:" << what._start_day << " end day:" << what._end_day;
       return os;
    }
Member Data Documentation
Tickval FIX8::Schedule::_duration
Definition at line 202 of file session.hpp.
Referenced by operator=().
Tickval FIX8::Schedule::_end
Definition at line 202 of file session.hpp.
Referenced by operator=(), and test().
int FIX8::Schedule::_end_day
Definition at line 203 of file session.hpp.
Referenced by operator=().
Tickval FIX8::Schedule::_start
Definition at line 202 of file session.hpp.
Referenced by operator=().
int FIX8::Schedule::_start_day
Definition at line 203 of file session.hpp.
Referenced by operator=().
Tickval::ticks FIX8::Schedule::_toffset
Definition at line 204 of file session.hpp.
Referenced by operator=().
int FIX8::Schedule::_utc_offset
Definition at line 203 of file session.hpp.
Referenced by operator=().
The documentation for this struct was generated from the following file:
session.hpp