fix8: ff::xThreadData Struct Reference
ff::xThreadData Struct Reference
A buffer shared among threads (i.e. leak queue)
#include <allocator.hpp>
Public Types
enum { MIN_BUFFER_ITEMS =8192, LEAK_CHUNK =1023 }
Public Member Functions
xThreadData (const bool allocator, size_t nslabs, const pthread_t key)
~xThreadData ()
Public Attributes
uSWSR_Ptr_Buffer * leak
const pthread_t key
long padding [longxCacheLine-((sizeof(const pthread_t)+sizeof(uSWSR_Ptr_Buffer *))/sizeof(long))]
Detailed Description
A buffer shared among threads (i.e. leak queue)
A buffer that is used as a channel for exchanging shared data among threads. It is built upon FastFlow's unbounded Single-Writer / Single-Reader queues (uSWSR_Ptr_Buffer). These buffers guarantee deadlock avoidance and scalability in stream-oriented applications.
This class is defined in allocator.hpp
Definition at line 343 of file allocator.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
MIN_BUFFER_ITEMS
LEAK_CHUNK
Definition at line 344 of file allocator.hpp.
Constructor & Destructor Documentation
ff::xThreadData::xThreadData (const bool allocator, size_t nslabs, const pthread_t key) inline
TODO
allocator TODO nslabs TODO key TODO
Definition at line 356 of file allocator.hpp.
References getAlignedMemory(), ff::uSWSR_Ptr_Buffer::init(), leak, and LEAK_CHUNK.
ff::xThreadData::~xThreadData () inline
TODO
Definition at line 368 of file allocator.hpp.
References freeAlignedMemory(), leak, and ff::uSWSR_Ptr_Buffer::~uSWSR_Ptr_Buffer().
Referenced by ff::SlabCache::~SlabCache().
Member Data Documentation
const pthread_t ff::xThreadData::key
Definition at line 373 of file allocator.hpp.
uSWSR_Ptr_Buffer* ff::xThreadData::leak
Definition at line 372 of file allocator.hpp.
Referenced by ff::SlabCache::getfrom_fb_delayed(), ff::SlabCache::putitem(), xThreadData(), and ~xThreadData().
long ff::xThreadData::padding[longxCacheLine-((sizeof(const pthread_t)+sizeof(uSWSR_Ptr_Buffer *))/sizeof(long))]
Definition at line 374 of file allocator.hpp.
The documentation for this struct was generated from the following file:
allocator.hpp