fix8: ff::descriptorN_1 Struct Reference
ff::descriptorN_1 Struct Reference
Descriptor used in several communication patterns: AllGather, Collect FromAny, ManyToOne.
#include <zmqImpl.hpp>
Public Types
typedef zmqTransportMsg_t msg_t
Public Member Functions
descriptorN_1 (const std::string name, const int peers, zmqTransport *const transport, const bool P)
~descriptorN_1 ()
int close ()
int init (const std::string &addr, const int nodeId=-1)
bool send (const msg_t &msg, int flags=0)
bool recvhdr (msg_t &msg, int &peer)
bool recv (msg_t &msg, int &peer)
bool recvreq ()
bool done (bool sendready=false)
int getPeers () const
void sendHelloRecvHi ()
bool recvreply (msg_t &msg)
bool sendreply (const msg_t &msg)
void recvHelloSendHi ()
Public Attributes
const std::string name
zmq::socket_t * socket
zmqTransport *const transport
const bool P
const int peers
bool recvHdr
std::vector< std::string > transportIDs
Detailed Description
Descriptor used in several communication patterns: AllGather, Collect FromAny, ManyToOne.
This class is defined in zmqImpl.hpp
Definition at line 497 of file zmqImpl.hpp.
Member Typedef Documentation
typedef zmqTransportMsg_t ff::descriptorN_1::msg_t
Definition at line 498 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::descriptorN_1::descriptorN_1 (const std::string name, const int peers, zmqTransport *const transport, const bool P) inline
Constructor.
It creates a Many-to-One descriptor, that is, instantiate a transport layer using the first node as a router.
Parameters
name is the name of the descriptor
peers is the number of peers involved (sending nodes)
transport is the pointer to the transport layer object of class zmqTransport
P is the flag that identifies whether the descriptor refers to a sender (i.e. a Router) or to a receiver.
Definition at line 513 of file zmqImpl.hpp.
References ff::zmqTransport::newEndPoint(), peers, socket, and transportIDs.
ff::descriptorN_1::~descriptorN_1 () inline
Destructor
Definition at line 531 of file zmqImpl.hpp.
References close(), and socket.
Member Function Documentation
int ff::descriptorN_1::close () inline
It closes active connection and delete the existing socket.
Returns
Deletes the end point and a null pointer is returned, otherwise a negative value is returned.
Definition at line 539 of file zmqImpl.hpp.
References ff::zmqTransport::deleteEndPoint(), socket, and transport.
Referenced by ff::zmqAllGather::close(), ff::zmqFromAny::close(), ff::zmqAllGather::setDescriptor(), ff::zmqFromAny::setDescriptor(), and ~descriptorN_1().
bool ff::descriptorN_1::done (bool sendready = false) inline
It resets recvHdr.
Exceptions
TODO
Returns
TODO
Definition at line 708 of file zmqImpl.hpp.
References peers, recvHdr, socket, and transportIDs.
Referenced by ff::zmqAllGather::done(), and ff::zmqFromAny::done().
int ff::descriptorN_1::getPeers () const inline
It returns the number of partners of the single communication (NOTE: if P, peers is 1).
Returns
The number of peers are returned.
Definition at line 731 of file zmqImpl.hpp.
References peers.
Referenced by ff::zmqAllGather::get(), and ff::zmqAllGather::getToWait().
int ff::descriptorN_1::init (const std::string & addr, const int nodeId = -1) inline
It initialises a socket and estabilish a connection to the given address.
Parameters
addr is the IP address in the form 'ip/host:port'.
nodeId is the node identifier in the range [0..inf[.
Exceptions
TODO
Returns
TODO
Definition at line 554 of file zmqImpl.hpp.
References ff::zmqTransport::getProcId(), name, P, recvHelloSendHi(), sendHelloRecvHi(), socket, and transport.
Referenced by ff::zmqAllGather::init(), and ff::zmqFromAny::init().
bool ff::descriptorN_1::recv (msg_t & msg, int & peer) inline
It receives a message after having received the header.
msg is a reference to the message to be sent.
Parameters
peers is the number of peers involved (sending nodes).
Exceptions
TODO
Returns
TODO
Definition at line 655 of file zmqImpl.hpp.
References recvHdr, socket, and zmqTDBG.
Referenced by ff::zmqAllGather::get(), ff::zmqFromAny::get(), and recvHelloSendHi().
bool ff::descriptorN_1::recvhdr (msg_t & msg, int & peer) inline
It receives a message header.
Exceptions
TODO
Returns
TODO
Definition at line 621 of file zmqImpl.hpp.
References recvHdr, socket, and zmqTDBG.
Referenced by ff::zmqAllGather::gethdr(), and ff::zmqFromAny::gethdr().
void ff::descriptorN_1::recvHelloSendHi () inline
It receive hello to sening hi.
Definition at line 800 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::getData(), name, peers, recv(), sendreply(), and zmqTDBG.
Referenced by init().
bool ff::descriptorN_1::recvreply (msg_t & msg) inline
It receives a reply.
Exceptions
TODO
Returns
TODO
Definition at line 764 of file zmqImpl.hpp.
References socket, and zmqTDBG.
Referenced by sendHelloRecvHi().
bool ff::descriptorN_1::recvreq () inline
It receives the request.
Exceptions
TODO
Returns
TODO
Definition at line 689 of file zmqImpl.hpp.
References socket, and zmqTDBG.
Referenced by ff::zmqAllGather::close(), and ff::zmqAllGather::put().
bool ff::descriptorN_1::send (const msg_t & msg, int flags = 0) inline
It sends a message.
Parameters
msg is a reference to the message to be sent.
flags is a flag indicating whether the operation should be in non-blocking mode or if the message is a multi-part message. See ØMQ's API for details.
Exceptions
TODO
Returns
TODO
Definition at line 606 of file zmqImpl.hpp.
References socket.
Referenced by ff::zmqAllGather::put(), ff::zmqFromAny::put(), ff::zmqAllGather::putmore(), ff::zmqFromAny::putmore(), and sendHelloRecvHi().
void ff::descriptorN_1::sendHelloRecvHi () inline
It sends hello to receiving node.
Definition at line 746 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::getData(), name, recvreply(), send(), and zmqTDBG.
Referenced by init().
bool ff::descriptorN_1::sendreply (const msg_t & msg) inline
It sends a reply.
Exceptions
TODO
Returns
TODO
Definition at line 782 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::copy(), peers, socket, and transportIDs.
Referenced by recvHelloSendHi().
Member Data Documentation
const std::string ff::descriptorN_1::name
Definition at line 733 of file zmqImpl.hpp.
Referenced by init(), recvHelloSendHi(), and sendHelloRecvHi().
const bool ff::descriptorN_1::P
Definition at line 736 of file zmqImpl.hpp.
Referenced by ff::zmqAllGather::close(), init(), and ff::zmqAllGather::init().
const int ff::descriptorN_1::peers
Definition at line 737 of file zmqImpl.hpp.
Referenced by descriptorN_1(), done(), getPeers(), recvHelloSendHi(), and sendreply().
bool ff::descriptorN_1::recvHdr
Definition at line 738 of file zmqImpl.hpp.
Referenced by done(), recv(), and recvhdr().
zmq::socket_t* ff::descriptorN_1::socket
Definition at line 734 of file zmqImpl.hpp.
Referenced by close(), descriptorN_1(), done(), init(), recv(), recvhdr(), recvreply(), recvreq(), send(), sendreply(), and ~descriptorN_1().
zmqTransport* const ff::descriptorN_1::transport
Definition at line 735 of file zmqImpl.hpp.
Referenced by close(), and init().
std::vector<std::string> ff::descriptorN_1::transportIDs
Definition at line 739 of file zmqImpl.hpp.
Referenced by descriptorN_1(), done(), and sendreply().
The documentation for this struct was generated from the following file:
zmqImpl.hpp