fix8: FIX8::RealmBase Struct Reference
FIX8::RealmBase Struct Reference
Domain range/set static metadata base class.
#include <field.hpp>
Public Types
enum RealmType { dt_range, dt_set }
Public Member Functions
RealmBase (const void *range, RealmType dtype, FieldTrait::FieldType ftype, int sz, const char *const *descriptions)
template<typename T >
bool is_valid (const T &what) const
template<typename T >
const T & get_rlm_val (const int idx) const
template<typename T >
int get_rlm_idx (const T &what) const
template<typename T >
std::ostream & _print (std::ostream &os, int idx) const
std::ostream & print (std::ostream &os, int idx) const
Public Attributes
const void * _range
RealmType _dtype
FieldTrait::FieldType _ftype
const int _sz
const char *const * _descriptions
Detailed Description
Domain range/set static metadata base class.
Definition at line 58 of file field.hpp.
Member Enumeration Documentation
enum FIX8::RealmBase::RealmType
Enumerator
dt_range
dt_set
Definition at line 60 of file field.hpp.
 { dt_range, dt_set };
Constructor & Destructor Documentation
FIX8::RealmBase::RealmBase (const void * range, RealmType dtype, FieldTrait::FieldType ftype, int sz, const char *const * descriptions) inline
Definition at line 68 of file field.hpp.
       : _range(range), _dtype(dtype), _ftype(ftype), _sz(sz), _descriptions(descriptions) {}
Member Function Documentation
template<typename T > std::ostream& FIX8::RealmBase::_print (std::ostream & os, int idx) const inline
Printer helper
Template Parameters
T target type
Parameters
os output stream
idx index of value in range
Returns
the output stream
Definition at line 110 of file field.hpp.
References _range.
 { return os << *((static_cast<const T *>(_range) + idx)); }
template<typename T > int FIX8::RealmBase::get_rlm_idx (const T & what) const inline
Get the realm index of this value in the domain set.
Template Parameters
T domain type
Parameters
what the value to check
Returns
the index in the domain set of this value
Definition at line 94 of file field.hpp.
References dt_set.
Referenced by FIX8::Field< int, field >::get_rlm_idx(), FIX8::Field< f8String, field >::get_rlm_idx(), FIX8::Field< fp_type, field >::get_rlm_idx(), FIX8::Field< char, field >::get_rlm_idx(), and FIX8::Field< Boolean, field >::get_rlm_idx().
    {
       if (_dtype == dt_set)
       {
          const T *rng(static_cast<const T*>(_range)), *res(std::lower_bound(rng, rng + _sz, what));
          return res != rng + _sz ? res - rng : -1;
       }
       return 0;
    }
template<typename T > const T& FIX8::RealmBase::get_rlm_val (const int idx) const inline
Get the realm value with the specified index
Template Parameters
T domain type
Parameters
idx of value
Returns
reference to the associated value
Definition at line 87 of file field.hpp.
References _range.
Referenced by FIX8::Inst::_gen::_make().
 { return *(static_cast<const T*>(_range) + idx); }
template<typename T > bool FIX8::RealmBase::is_valid (const T & what) const inline
Check if this value is a member/in range of the domain set.
Template Parameters
T domain type
Parameters
what the value to check
Returns
true if in the set or no domain available
Definition at line 76 of file field.hpp.
References dt_set.
Referenced by FIX8::Field< int, field >::is_valid(), FIX8::Field< f8String, field >::is_valid(), FIX8::Field< fp_type, field >::is_valid(), and FIX8::Field< char, field >::is_valid().
    {
       const T *rng(static_cast<const T*>(_range));
       return _dtype == dt_set ? std::binary_search(rng, rng + _sz, what) : *rng <= what && what <= *(rng + 1);
    }
std::ostream& FIX8::RealmBase::print (std::ostream & os, int idx) const inline
Print the given value by index to the supplied stream
Parameters
os output stream
idx index of value in range
Returns
the output stream
Definition at line 116 of file field.hpp.
References FIX8::FieldTrait::is_char(), FIX8::FieldTrait::is_float(), FIX8::FieldTrait::is_int(), and FIX8::FieldTrait::is_string().
Referenced by FIX8::ConsoleMenu::SelectRealm().
    {
       return FieldTrait::is_int(_ftype) ? _print<int>(os, idx)
          : FieldTrait::is_char(_ftype) ? _print<char>(os, idx)
          : FieldTrait::is_float(_ftype) ? _print<fp_type>(os, idx)
          : FieldTrait::is_string(_ftype) ? _print<f8String>(os, idx) : os;
    }
Member Data Documentation
const char* const* FIX8::RealmBase::_descriptions
Definition at line 66 of file field.hpp.
Referenced by FIX8::ConsoleMenu::SelectRealm().
RealmType FIX8::RealmBase::_dtype
Definition at line 63 of file field.hpp.
Referenced by FIX8::Inst::_gen::_make().
FieldTrait::FieldType FIX8::RealmBase::_ftype
Definition at line 64 of file field.hpp.
const void* FIX8::RealmBase::_range
Definition at line 62 of file field.hpp.
Referenced by _print(), and get_rlm_val().
const int FIX8::RealmBase::_sz
Definition at line 65 of file field.hpp.
Referenced by FIX8::Inst::_gen::_make(), and FIX8::ConsoleMenu::SelectRealm().
The documentation for this struct was generated from the following file:
field.hpp