fix8: FIX8::F8MetaCntx Struct Reference
FIX8::F8MetaCntx Struct Reference
Static metadata context class - one per FIX xml schema.
#include <message.hpp>
Public Member Functions
F8MetaCntx (const unsigned version, const MsgTable &bme, const FieldTable &be, const char **cn, const f8String &bg)
~F8MetaCntx ()
Dtor.
const BaseEntry * find_be (const unsigned short fnum) const
const BaseEntry * reverse_find_be (const char *fieldstr) const
unsigned short reverse_find_fnum (const char *fieldstr) const
BaseField * create_field (unsigned short fnum, const char *from) const
BaseField * create_field (const char *tag, const char *from) const
const BaseMsgEntry * find_bme (const char *tag) const
const BaseMsgEntry * reverse_find_bme (const char *msgstr) const
Message * create_msg_from_longname (const char *tag, bool deepctor=true) const
Message * create_msg (const char *tag, bool deepctor=true) const
unsigned version () const
const f8String & get_beginStr () const
Static Public Member Functions
static bool _comp (const char *p1, const char *p2)
Public Attributes
const unsigned _version
4 digit fix version <Major:1><Minor:1><Revision:2> eg. 4.2r10 is 4210
const MsgTable & _bme
Framework generated lookup table to generate Fix messages.
const FieldTable & _be
Framework generated lookup table to generate Fix fields.
const char ** _cn
Framework generated component name table.
const unsigned _flu_sz
Number of elements in Hash array.
const BaseEntry ** _flu
Hash array for field lookup (built by ctor)
msg_create _mk_hdr
References to the header and trailer create functions.
msg_create _mk_trl
const f8String _beginStr
Fix header beginstring.
const size_t _preamble_sz
Preamble length.
ReverseMsgTable _reverse_msgtable
ReverseFieldTable _reverse_fieldtable
Detailed Description
Static metadata context class - one per FIX xml schema.
Definition at line 210 of file message.hpp.
Constructor & Destructor Documentation
FIX8::F8MetaCntx::F8MetaCntx (const unsigned version, const MsgTable & bme, const FieldTable & be, const char ** cn, const f8String & bg) inline
Ctor.
Parameters
version FIX version
bme Generated Message Table
be Generated Field Table
cn Component name table
bg BeginString
Definition at line 242 of file message.hpp.
References FIX8::_pair< Key, Val >::_key, FIX8::_pair< Key, Val >::_value, FIX8::GeneratedTable< Key, Val >::at(), FIX8::GeneratedTable< Key, Val >::begin(), FIX8::GeneratedTable< Key, Val >::end(), and FIX8::GeneratedTable< Key, Val >::size().
       : _version(version), _bme(bme), _be(be), _cn(cn),
       _flu_sz(_be.at(_be.size() - 1)->_key + 1), _flu(new const BaseEntry *[_flu_sz]),
       _mk_hdr(_bme.find_ref("header")._create._do), _mk_trl(_bme.find_ref("trailer")._create._do),
       _beginStr(bg), _preamble_sz(2 + _beginStr.size() + 1 + 3),
       _reverse_msgtable(_comp), _reverse_fieldtable(_comp)
    {
       if (_flu_sz == 1)
          throw f8Exception("F8MetaCntx initialisation incomplete");
       std::fill(_flu, _flu + _flu_sz, nullptr);
       for (unsigned offset(0); offset < _be.size(); ++offset)
          *(_flu + _be.at(offset)->_key) = &_be.at(offset)->_value;
       std::for_each(_be.begin(), _be.end(), [this](const FieldTable::Pair& pp)
          { _reverse_fieldtable.emplace(std::make_pair(pp.second()._name, &pp.second())); });
       std::for_each(_bme.begin(), _bme.end(), [this](const MsgTable::Pair& pp)
          { _reverse_msgtable.emplace(std::make_pair(pp.second()._name, &pp.second())); });
    }
FIX8::F8MetaCntx::~F8MetaCntx () inline
Dtor.
Definition at line 262 of file message.hpp.
References _flu.
 { delete[] _flu; _flu = nullptr; }
Member Function Documentation
static bool FIX8::F8MetaCntx::_comp (const char * p1, const char * p2) inline static
Definition at line 234 of file message.hpp.
 { return ::strcmp(p1, p2) < 0; }
BaseField* FIX8::F8MetaCntx::create_field (unsigned short fnum, const char * from) const inline
Create a new field of the tag type passed, and from the raw string given.
Parameters
fnum FIX field number
from const char ptr to string containing value to construct from
Returns
ptr to BaseField or 0 if fnum not found
Definition at line 300 of file message.hpp.
References FIX8::BaseEntry::_create, FIX8::Inst::_do, FIX8::BaseEntry::_rlm, and find_be().
    {
       const BaseEntry *be(find_be(fnum));
       return be ? be->_create._do(from, be->_rlm, -1) : nullptr;
    }
BaseField* FIX8::F8MetaCntx::create_field (const char * tag, const char * from) const inline
Create a new field of the tag type passed, and from the raw string given.
Parameters
tag const char ptr to longname of field to create
from const char ptr to string containing value to construct from
Returns
ptr to BaseField or 0 if fnum not found
Definition at line 310 of file message.hpp.
References FIX8::BaseEntry::_create, FIX8::Inst::_do, FIX8::BaseEntry::_rlm, and reverse_find_be().
    {
       const BaseEntry *be(reverse_find_be(tag));
       return be ? be->_create._do(from, be->_rlm, -1) : nullptr;
    }
Message* FIX8::F8MetaCntx::create_msg (const char * tag, bool deepctor = true) const inline
Create a new message of the tag type passed.
Parameters
tag const char ptr to tag of message
deepctor if true, do deep message construction
Returns
ptr to Message or 0 if tag not found
Definition at line 344 of file message.hpp.
References FIX8::BaseMsgEntry::_create, FIX8::Minst::_do, and find_bme().
    {
       const BaseMsgEntry *bme(find_bme(tag));
       return bme ? bme->_create._do(deepctor) : nullptr;
    }
Message* FIX8::F8MetaCntx::create_msg_from_longname (const char * tag, bool deepctor = true) const inline
Create a new message from longname
Parameters
tag const char ptr to tag of message
deepctor if true, do deep message construction
Returns
ptr to Message or 0 if tag not found
Definition at line 334 of file message.hpp.
References FIX8::BaseMsgEntry::_create, FIX8::Minst::_do, and reverse_find_bme().
    {
       const BaseMsgEntry *bme(reverse_find_bme(tag));
       return bme ? bme->_create._do(deepctor) : nullptr;
    }
const BaseEntry* FIX8::F8MetaCntx::find_be (const unsigned short fnum) const inline
Get the field BaseEntry object for this field number. Will use fast field index lookup.
Parameters
fnum field to get
Returns
ptr to BaseEntry or 0 if not found
Definition at line 267 of file message.hpp.
Referenced by FIX8::MessageBase::check_set_rlm(), and create_field().
       { return fnum < _flu_sz ? _flu[fnum] : nullptr; }
const BaseMsgEntry* FIX8::F8MetaCntx::find_bme (const char * tag) const inline
Get the message BaseMsgEntry object for this message.
Parameters
tag const char ptr to name of message to get
Returns
ptr to BaseMsgEntry or 0 if not found
Definition at line 319 of file message.hpp.
References FIX8::GeneratedTable< Key, Val >::find_ptr().
Referenced by create_msg().
 { return _bme.find_ptr(tag); }
const f8String& FIX8::F8MetaCntx::get_beginStr () const inline
Get fix header beginstring
Returns
beginstring
Definition at line 356 of file message.hpp.
References _beginStr.
 { return _beginStr; }
const BaseEntry* FIX8::F8MetaCntx::reverse_find_be (const char * fieldstr) const inline
Get the field BaseEntry object for this field by tag. Reverse lookup.
Parameters
fieldstr const char ptr to longname of field to get
Returns
ptr to BaseEntry or 0 if not found
Definition at line 273 of file message.hpp.
Referenced by create_field().
    {
       if (fieldstr && *fieldstr)
       {
          auto itr(_reverse_fieldtable.find(fieldstr));
          return itr != _reverse_fieldtable.cend() ? itr->second : nullptr;
       }
       return nullptr;
    }
const BaseMsgEntry* FIX8::F8MetaCntx::reverse_find_bme (const char * msgstr) const inline
Get the message BaseMsgEntry object for this message. Reverse lookup.
Parameters
msgstr const char ptr to longname of message to get
Returns
ptr to BaseMsgEntry or 0 if not found
Definition at line 324 of file message.hpp.
Referenced by create_msg_from_longname().
    {
       auto itr(_reverse_msgtable.find(msgstr));
       return itr != _reverse_msgtable.cend() ? itr->second : nullptr;
    }
unsigned short FIX8::F8MetaCntx::reverse_find_fnum (const char * fieldstr) const inline
Get the field number for this field by tag. Reverse lookup.
Parameters
fieldstr const char ptr to longname of field to get
Returns
unsigned short field number
Definition at line 286 of file message.hpp.
Referenced by FIX8::MessageBase::get_field_by_name(), and FIX8::Message::get_field_by_name_flattened().
    {
       if (fieldstr && *fieldstr)
       {
          auto itr(_reverse_fieldtable.find(fieldstr));
          return itr != _reverse_fieldtable.cend() ? itr->second->_fnum : 0;
       }
       return 0;
    }
unsigned FIX8::F8MetaCntx::version () const inline
4 digit fix version <Major:1><Minor:1><Revision:2> eg. 4.2r10 is 4210
Returns
version
Definition at line 352 of file message.hpp.
References _version.
Referenced by main().
 { return _version; }
Member Data Documentation
const FieldTable& FIX8::F8MetaCntx::_be
Framework generated lookup table to generate Fix fields.
Definition at line 218 of file message.hpp.
const f8String FIX8::F8MetaCntx::_beginStr
Fix header beginstring.
Definition at line 228 of file message.hpp.
Referenced by get_beginStr(), FIX8::Session::handle_logon(), and main().
const MsgTable& FIX8::F8MetaCntx::_bme
Framework generated lookup table to generate Fix messages.
Definition at line 216 of file message.hpp.
Referenced by FIX8::Session::create_msg(), and FIX8::Message::factory().
const char** FIX8::F8MetaCntx::_cn
Framework generated component name table.
Definition at line 220 of file message.hpp.
const BaseEntry** FIX8::F8MetaCntx::_flu
Hash array for field lookup (built by ctor)
Definition at line 224 of file message.hpp.
Referenced by ~F8MetaCntx().
const unsigned FIX8::F8MetaCntx::_flu_sz
Number of elements in Hash array.
Definition at line 222 of file message.hpp.
msg_create FIX8::F8MetaCntx::_mk_hdr
References to the header and trailer create functions.
Definition at line 226 of file message.hpp.
msg_create FIX8::F8MetaCntx::_mk_trl
Definition at line 226 of file message.hpp.
const size_t FIX8::F8MetaCntx::_preamble_sz
Preamble length.
Definition at line 230 of file message.hpp.
ReverseFieldTable FIX8::F8MetaCntx::_reverse_fieldtable
Definition at line 233 of file message.hpp.
ReverseMsgTable FIX8::F8MetaCntx::_reverse_msgtable
Definition at line 232 of file message.hpp.
const unsigned FIX8::F8MetaCntx::_version
4 digit fix version <Major:1><Minor:1><Revision:2> eg. 4.2r10 is 4210
Definition at line 213 of file message.hpp.
Referenced by version().
The documentation for this struct was generated from the following file:
message.hpp