fix8: FIX8::dthread_cancellation_token Struct Reference
FIX8::dthread_cancellation_token Struct Reference
Thread cancellation token.
#include <thread.hpp>
Public Types
enum ThreadState { Unknown, Running, Stopping, Stopped }
Thread state enumerations.
Public Member Functions
dthread_cancellation_token ()
ctor
bool stop_requested () const
void request_stop ()
Tell the thread to stop.
operator bool () const
bool operator! () const
int thread_state () const
void thread_state (ThreadState state)
Private Attributes
f8_atomic< int > _stop_requested
f8_atomic< int > _thread_state
Detailed Description
Thread cancellation token.
Definition at line 252 of file thread.hpp.
Member Enumeration Documentation
enum FIX8::dthread_cancellation_token::ThreadState
Thread state enumerations.
Enumerator
Unknown
Running
Stopping
Stopped
Definition at line 273 of file thread.hpp.
Constructor & Destructor Documentation
FIX8::dthread_cancellation_token::dthread_cancellation_token () inline
ctor
Definition at line 255 of file thread.hpp.
References _stop_requested, _thread_state, and Unknown.
Member Function Documentation
FIX8::dthread_cancellation_token::operator bool () const inline
check if a stop has been requested
Returns
true if stop requested
Definition at line 266 of file thread.hpp.
References stop_requested().
bool FIX8::dthread_cancellation_token::operator! () const inline
check if a stop has been requested
Returns
false if stop requested
Definition at line 270 of file thread.hpp.
References stop_requested().
void FIX8::dthread_cancellation_token::request_stop () inline
Tell the thread to stop.
Definition at line 262 of file thread.hpp.
References _stop_requested, _thread_state, and Stopping.
Referenced by FIX8::dthread< FIX8::Timer >::request_stop(), and FIX8::Logger::stop().
bool FIX8::dthread_cancellation_token::stop_requested () const inline
check if a stop has been requested
Returns
true if stop requested
Definition at line 259 of file thread.hpp.
References _stop_requested.
Referenced by operator bool(), and operator!().
int FIX8::dthread_cancellation_token::thread_state () const inline
Get the current thread state
Returns
thread state enumeration
Definition at line 277 of file thread.hpp.
References _thread_state.
Referenced by FIX8::dthread< FIX8::Timer >::join(), and FIX8::dthread< T >::_helper::operator()().
void FIX8::dthread_cancellation_token::thread_state (ThreadState state) inline
Set the thread state
Parameters
state state to set to
Definition at line 281 of file thread.hpp.
References _thread_state.
Member Data Documentation
f8_atomic<int> FIX8::dthread_cancellation_token::_stop_requested private
Definition at line 284 of file thread.hpp.
Referenced by dthread_cancellation_token(), request_stop(), and stop_requested().
f8_atomic<int> FIX8::dthread_cancellation_token::_thread_state private
Definition at line 284 of file thread.hpp.
Referenced by dthread_cancellation_token(), request_stop(), and thread_state().
The documentation for this struct was generated from the following file:
thread.hpp