fix8: ff::descriptor1_N Struct Reference
ff::descriptor1_N Struct Reference
This struct is used in several communication patterns; Unicast, Broadcast, Scatter, On-Demand, OneToMany, FromAny etc.
#include <zmqImpl.hpp>
Public Types
typedef zmqTransportMsg_t msg_t
Public Member Functions
descriptor1_N (const std::string name, const int peers, zmqTransport *const transport, const bool P)
~descriptor1_N ()
int close ()
int init (const std::string &addr, const int nodeId=-1)
bool send (const msg_t &msg, int flags=0)
bool sendmore (const msg_t &msg, int flags)
bool send (const msg_t &msg, const int dest, int flags)
bool sendmore (const msg_t &msg, const int dest, int flags)
bool recvhdr (msg_t &msg)
bool recv (msg_t &msg)
int getPeers () const
void sendHelloRecvHi ()
bool sendreq (const msg_t &msg)
int recvreply (msg_t &msg)
bool recvreq (msg_t &msg)
bool sendReq (const msg_t &msg)
bool recvReq (int &peer, int flags=0)
bool sendreply (const msg_t &msg)
void recvHelloSendHi ()
Public Attributes
const std::string name
zmq::socket_t * socket
zmqTransport *const transport
const bool P
const int peers
bool zmqHdrSet
std::vector< std::string > transportIDs
Detailed Description
This struct is used in several communication patterns; Unicast, Broadcast, Scatter, On-Demand, OneToMany, FromAny etc.
This struct is defined in zmqImpl.hpp
Definition at line 94 of file zmqImpl.hpp.
Member Typedef Documentation
typedef zmqTransportMsg_t ff::descriptor1_N::msg_t
Definition at line 95 of file zmqImpl.hpp.
Constructor & Destructor Documentation
ff::descriptor1_N::descriptor1_N (const std::string name, const int peers, zmqTransport *const transport, const bool P) inline
Constructor.
It Creates a One-to-Many descriptor, that is, instantiate a transport layer using the first node as a router.
Parameters
name is the name of the descriptor.
peers is the number of peers involved (receiving nodes).
transport is a pointer to the transport layer object of class zmqTransport.
P is a flag that identifies whether the descriptor refers to a sender (i.e. a Router) or to a receiver.
Definition at line 111 of file zmqImpl.hpp.
References ff::zmqTransport::newEndPoint(), peers, socket, and transportIDs.
ff::descriptor1_N::~descriptor1_N () inline
Destructor
Definition at line 133 of file zmqImpl.hpp.
References close(), and socket.
Member Function Documentation
int ff::descriptor1_N::close () inline
It closes active connection and delete the existing socket.
Returns
It delets the end point from socket and return NULL. If it is not succefful then a negative value is returned.
Definition at line 141 of file zmqImpl.hpp.
References ff::zmqTransport::deleteEndPoint(), socket, and transport.
Referenced by ff::zmq1_1::close(), ff::zmqBcast::close(), ff::zmqScatter::close(), ff::zmqOnDemand::close(), ff::zmq1_N::close(), ff::zmq1_1::setDescriptor(), ff::zmqBcast::setDescriptor(), ff::zmqScatter::setDescriptor(), ff::zmqOnDemand::setDescriptor(), ff::zmq1_N::setDescriptor(), and ~descriptor1_N().
int ff::descriptor1_N::getPeers () const inline
It returns the total number of peers (NOTE: if !P, peers is 1).
Returns
The number of peers.
Definition at line 319 of file zmqImpl.hpp.
References peers.
Referenced by ff::zmqOnDemand::close(), ff::zmqOnDemand::init(), ff::zmqScatter::put(), ff::zmqOnDemand::put(), ff::zmq1_N::put(), and ff::zmqScatter::putToPerform().
int ff::descriptor1_N::init (const std::string & addr, const int nodeId = -1) inline
It initialises a socket and estabilishes a connection to the given address.
Parameters
addr is the IP address in the form 'ip/host:port'
nodeId is the node identifier in the range [0..inf[
Exceptions
TODO
Returns
TODO
Definition at line 155 of file zmqImpl.hpp.
References ff::zmqTransport::getProcId(), name, P, recvHelloSendHi(), sendHelloRecvHi(), socket, and transport.
Referenced by ff::zmq1_1::init(), ff::zmqBcast::init(), ff::zmqScatter::init(), ff::zmqOnDemand::init(), and ff::zmq1_N::init().
bool ff::descriptor1_N::recv (msg_t & msg) inline
It receives a message after having received the header.
TODO
Returns
TODO
Definition at line 302 of file zmqImpl.hpp.
References socket, and zmqTDBG.
Referenced by ff::zmq1_1::get(), ff::zmqBcast::get(), ff::zmqScatter::get(), ff::zmqOnDemand::get(), ff::zmq1_N::get(), and recvhdr().
bool ff::descriptor1_N::recvhdr (msg_t & msg) inline
It receives a message header
Returns
Contents of the message.
Definition at line 292 of file zmqImpl.hpp.
References recv().
Referenced by ff::zmq1_1::gethdr(), ff::zmqBcast::gethdr(), ff::zmqScatter::gethdr(), ff::zmqOnDemand::gethdr(), and ff::zmq1_N::gethdr().
void ff::descriptor1_N::recvHelloSendHi () inline
It defines the receiving of hi.
Definition at line 469 of file zmqImpl.hpp.
References name, recvreq(), send(), and zmqTDBG.
Referenced by init().
int ff::descriptor1_N::recvreply (msg_t & msg) inline
It defines the receiving of reply.
Exceptions
TODO
Returns
TODO
Definition at line 367 of file zmqImpl.hpp.
References socket, and zmqTDBG.
Referenced by sendHelloRecvHi().
bool ff::descriptor1_N::recvreq (msg_t & msg) inline
It receives a message from a ZMQ_ROUTER
Exceptions
TODO
Returns
TODO
Definition at line 385 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::getData(), name, peers, socket, and zmqTDBG.
Referenced by recvHelloSendHi().
bool ff::descriptor1_N::recvReq (int & peer, int flags = 0) inline
It is used in the on-demand pattern by the consumer (i.e. the on-demand producer).
Parameters
flags can be ZMQ_NOBLOCK
Exceptions
TODO
Returns
TODO
Definition at line 423 of file zmqImpl.hpp.
References socket, and zmqTDBG.
Referenced by ff::zmqOnDemand::close(), ff::zmqOnDemand::put(), and ff::zmqOnDemand::putmore().
bool ff::descriptor1_N::send (const msg_t & msg, int flags = 0) inline
It broadcast a message to all connected peers.
Parameters
msg is a eference to the message to be sent
flags is a flag indcating whether the operation should be in non-blocking mode or if the message is a multi-part message. See ØMQ's API for details.
Returns
TODO
Exceptions
TODO
Definition at line 208 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::copy(), peers, socket, transportIDs, and zmqHdrSet.
Referenced by ff::zmq1_1::put(), ff::zmqBcast::put(), ff::zmqScatter::put(), ff::zmqOnDemand::put(), ff::zmq1_N::put(), ff::zmq1_1::putmore(), recvHelloSendHi(), and sendmore().
bool ff::descriptor1_N::send (const msg_t & msg, const int dest, int flags) inline
It unicasts a message to a specified destination
Parameters
msg is a reference to the message to be sent
dest is the ID of the receiving peer.
flags is a flag indcating whether the operation should be in non-blocking mode or if the message is a multi-part message. See ØMQ's API for details.
Exceptions
TODO
Returns
TODO
Definition at line 255 of file zmqImpl.hpp.
References peers, socket, transportIDs, and zmqHdrSet.
void ff::descriptor1_N::sendHelloRecvHi () inline
It defines the sending of a message.
Definition at line 334 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::getData(), name, recvreply(), sendreq(), and zmqTDBG.
Referenced by init().
bool ff::descriptor1_N::sendmore (const msg_t & msg, int flags) inline
It broadcasts other parts of a multi-parts message to all connected peers. This method exits if the flag is not set to ZMQ_SNDMORE.
Parameters
msg eference to the message to be sent
flags a flag indcating whether the operation should be in non-blocking mode or if the message is a multi-part message. See ØMQ's API for details.
Returns
It returns the message.
Definition at line 235 of file zmqImpl.hpp.
References send(), and zmqHdrSet.
Referenced by ff::zmq1_1::putmore(), ff::zmqBcast::putmore(), ff::zmqScatter::putmore(), ff::zmqOnDemand::putmore(), and ff::zmq1_N::putmore().
bool ff::descriptor1_N::sendmore (const msg_t & msg, const int dest, int flags) inline
It unicasts other parts of a multi-parts message to a specified destination. This method exits if the flag is not set to ZMQ_SNDMORE.
Parameters
msg is a reference to the message to be sent
dest is the ID of the receiving peer.
flags is a flag indcating whether the operation should be in non-blocking mode or if the message is a multi-part message. See ØMQ's API for details.
Returns
The contents of the message is returned.
Definition at line 280 of file zmqImpl.hpp.
References send(), and zmqHdrSet.
bool ff::descriptor1_N::sendreply (const msg_t & msg) inline
It is used for sending back the message to the sender.
Exceptions
TODO
Returns
TODO
Definition at line 451 of file zmqImpl.hpp.
References ff::zmqTransportMsg_t::copy(), peers, socket, and transportIDs.
bool ff::descriptor1_N::sendreq (const msg_t & msg) inline
It defines the sending of requests.
Exceptions
TODO
Returns
TODO
Definition at line 352 of file zmqImpl.hpp.
References socket.
Referenced by sendHelloRecvHi(), and sendReq().
bool ff::descriptor1_N::sendReq (const msg_t & msg) inline
It is used in the on-demand pattern by the producer (i.e. the on-demand consumer).
Returns
The contents of the message.
Definition at line 412 of file zmqImpl.hpp.
References sendreq().
Referenced by ff::zmqOnDemand::sendReq().
Member Data Documentation
const std::string ff::descriptor1_N::name
Definition at line 322 of file zmqImpl.hpp.
Referenced by init(), recvHelloSendHi(), recvreq(), and sendHelloRecvHi().
const bool ff::descriptor1_N::P
Definition at line 325 of file zmqImpl.hpp.
Referenced by ff::zmqOnDemand::close(), init(), ff::zmq1_1::init(), and ff::zmqOnDemand::init().
const int ff::descriptor1_N::peers
Definition at line 326 of file zmqImpl.hpp.
Referenced by descriptor1_N(), getPeers(), recvreq(), send(), and sendreply().
zmq::socket_t* ff::descriptor1_N::socket
Definition at line 323 of file zmqImpl.hpp.
Referenced by close(), descriptor1_N(), init(), recv(), recvreply(), recvreq(), recvReq(), send(), sendreply(), sendreq(), and ~descriptor1_N().
zmqTransport* const ff::descriptor1_N::transport
Definition at line 324 of file zmqImpl.hpp.
Referenced by close(), and init().
std::vector<std::string> ff::descriptor1_N::transportIDs
Definition at line 328 of file zmqImpl.hpp.
Referenced by descriptor1_N(), send(), and sendreply().
bool ff::descriptor1_N::zmqHdrSet
Definition at line 327 of file zmqImpl.hpp.
Referenced by send(), and sendmore().
The documentation for this struct was generated from the following file:
zmqImpl.hpp