fix8: RandDev Struct Reference
RandDev Struct Reference
A random number generator wrapper.
#include <hftest.hpp>
Static Public Member Functions
static void init ()
Initialise the random number generator.
template<typename T >
static T getrandom (const T range=0)
static void init ()
template<typename T >
static T getrandom (const T range=0)
Detailed Description
A random number generator wrapper.
Definition at line 202 of file hftest.hpp.
Member Function Documentation
template<typename T > static T RandDev::getrandom (const T range = 0) inline static
Return a random number between 0 and n - 1, or between 0 and RAND_MAX
Template Parameters
T type of random number
Parameters
range upper range to return value within, or 0 for RAND_MAX
Returns
the random number of the specified type within the psecifed range
Definition at line 219 of file hftest.hpp.
Referenced by MyMenu::batch_preload_new_order_single(), MyMenu::generate_new_order_single(), MyMenu::generate_new_order_single_alternate(), main(), MyMenu::new_order_single(), tex_router_server::operator()(), and MyMenu::preload_new_order_single().
template<typename T > static T RandDev::getrandom (const T range = 0) inline static
Definition at line 238 of file myfix.hpp.
static void RandDev::init () inline static
Initialise the random number generator.
Definition at line 205 of file hftest.hpp.
Referenced by main().
static void RandDev::init () inline static
Definition at line 227 of file myfix.hpp.
The documentation for this struct was generated from the following files:
hftest.hpp
myfix.hpp